### ISSUE TITLE
Add a filter option

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#10]
I think it would be a nice feature!

## Why?

Because sometimes the file is too big to be completely loaded, so you need to use load_measured_data=False. But then you will lose all the other nice methods and will have to make lots of call to the get method.

## How?

We add a filter parameter to the ```__init__``` method, which would take a dictionary object like:

* ```{'channels': ['<name_1>', <...>, '<name_N>']}``` -> only read these channels
* ```{'channels': [(<idx_group_1>, <idx_channel_1>), <...>, (<idx_group_N>, <idx_channel_N>)]}``` -> only read these channels
* ```{'channel_groups': ['<idx_group_1>', <...>, '<idx_group_N>']}``` -> only read all channels of these groups

---

IMO, this feature would be very useful and could even have more options in the future.

Please let me know what you think about it. If you don't have enough time to implement it, I could also do the changes myself and make a PR. :)

**Comment by danielhrisca** [comment]
Hello Julien,

this is already implemented:

```python
from asammdf import MDF

x = MDF(r'E:\TMP\test.mf4', load_measured_data=False)

x = x.filter(['MAIN_CLOCK', 'dummy0086', 'dummy0253'])

print(x.channels_db)
```

which prints:
```python
{'MAIN_CLOCK': [(0, 1)], 'dummy0086': [(0, 2)], 'dummy0253': [(1, 1)]}
```

The original file has ~36000 channels

**Comment by JulienGrv** [comment]
oh! Are they loaded in the memory or not?

**Comment by danielhrisca** [comment]
Using _load_measured_data_ = _False_ does not make any restrictions anymore: in the past you could not append, it was more like a read-only usage.

So you can use all methods, whiteout restriction, but with some speed penalty if you call _get_.

**Comment by JulienGrv** [comment]
Ok I didn't know this. So I think I am going to use this filter option. it looks great. Sorry that I did not take the time to do a benchmark earlier but since you were still implementing a lots of nice changes I thought it could wait a bit :). I just started today looking into it again.

Another quick question: when I want to get a list of channels that belongs to the same group, I could do all the calls to the get method with asking only for the samples, so that it goes fast, but when I am finished, is there a way to get the master_channel?

**Comment by danielhrisca** [comment]
you could use something like this:

```python
master_index = mdf.masters_db[group_index]
master_samples = mdf.get(group=group_index, index=master_index)
```

There si also the _iter_to_pandas_ generator method that will go through all data groups and return the samples as pandas _DataFrame_.

Perhaps a new method could return the data group's samples as _DataFrame_ by giving the group index:
```python
df = mdf.to_pandas(group=group_index)
```

**Comment by JulienGrv** [comment]
Yes I thought about the first solution but I was wondering if there is a *better* way to do this.

If I call filter and then call iter_to_pandas, this will do the trick, doesn't it?

**Comment by danielhrisca** [comment]
Looking at the examples above:

```python
{'MAIN_CLOCK': [(0, 1)], 'dummy0086': [(0, 2)], 'dummy0253': [(1, 1)]}
```
In the original file _MAIN_CLOCK_ and _dummy0086_ where in the same data group. _dummy0253_ was in another data group. When the new filtered file is created _MAIN_CLOCK_ and _dummy0086_ are kept together in the same data group (now index 0 as you can see). There is a bug here in that the master channel does not appear in the channels_db (will be fixed in a few minutes).

If you call _iter_to_pandas_ on the new file you will get the channels grouped in the DataFrame like they were in the original file.

**Comment by JulienGrv** [comment]
Awesome, that is exactly what I was hoping for!

Amazing work Daniel, keep it up!

**Comment by danielhrisca** [comment]
Thank you Julien!
Have a look at the latest commit in the development branch

**Comment by JulienGrv** [comment]
After calling filter, I can get a signal but if I use iter_to_pandas, I get this error:

```python
from asammdf import MDF
mdf = MDF('<filepath>', load_measured_data=False)
mdf.filter(<channel_name_list>)
for df in mdf.iter_to_pandas():
    print(df)
Traceback (most recent call last):
  File "C:\Users\gra8hi\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\gra8hi\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gra8hi\workspace\apt\src\data\measurement_dataset.py", line 86, in _extract_mdf
    for df in mdf.iter_to_pandas():
  File "C:\Users\gra8hi\AppData\Roaming\Python\Python36\site-packages\asammdf-2.5.3.dev0-py3.6.egg\asammdf\mdf.py", line 396, in iter_to_pandas
    pandas_dict[name] = self.get(group=i, index=j, samples_only=True)
  File "C:\Users\gra8hi\AppData\Roaming\Python\Python36\site-packages\asammdf-2.5.3.dev0-py3.6.egg\asammdf\mdf4.py", line 1234, in get
    str_size = unpack_from('<I', signal_data, offset)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes
```
