### ISSUE TITLE
BufferedReader as input not currently working

### ISSUE THREAD

**Issue by CheMcKirgan** [danielhrisca/asammdf#1000]
### Python version
3.11

### asammdf version
7.4.2

### Description
The type hinting for the init istates that MDF supports `io.BufferedReader` as an input type. 
https://github.com/danielhrisca/asammdf/blob/2d20ad23d3ef71ca7e307273ddd74ce08cce83b5/src/asammdf/types.py#L38

https://github.com/danielhrisca/asammdf/blob/c9d0e449000ed70f2ea1dd47df7c80f3e74471c5/src/asammdf/mdf.py#L236
This type checking block has broken that support in this [commit](https://github.com/danielhrisca/asammdf/commit/6019d2c521f6d2adfc42b0f7b0e6fd76b37724f2). We've tested adding BufferedReader to this type check, `if isinstance(name, (BytesIO, BufferedReader)):`, and it seems that the type check is the only thing blocking this support.

**Comment by CheMcKirgan** [comment]
Further to documentation on the is file like check method. It would be very helpful to check that the input is a general 'BufferedIoBase', as BufferedIoBase meets your criteria for read and seek methods, after evaluating it is not any of the compressed file formats you support. 

https://github.com/danielhrisca/asammdf/blob/c9d0e449000ed70f2ea1dd47df7c80f3e74471c5/src/asammdf/blocks/utils.py#L1079

**Comment by danielhrisca** [comment]
@CheMcKirgan please try the development branch code
