### ISSUE TITLE
No block found for inverse conversion after cut function

### ISSUE THREAD

**Issue by fhaon** [danielhrisca/asammdf#1017]
# Python version
('python=3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.24.2'
'asammdf=7.4.2'

# Code 

  ## MDF version
  4.11

  ## Code snippet
```python
from asammdf import MDF

with MDF(name="E:/RecordFile_24-05-13_09_40_46_355.mf4", temporary_folder="E:/", version='4.11') as mdf4:
    mdf4_cut = mdf4.cut(start=2.5, stop=7.5)
    mdf4_cut.save("E:/RecordFile_24-05-13_09_40_46_355_cut.mf4", overwrite=True)
 ``` 
  ## Traceback
N/A

 ## MDF Validator Error
![error](https://github.com/danielhrisca/asammdf/assets/11522148/78635b31-66bc-4211-8897-10c2ba3a506a)

  
# Description
[RecordFile_24-05-13_09_40_46_355.zip](https://github.com/danielhrisca/asammdf/files/15292860/RecordFile_24-05-13_09_40_46_355.zip)

The MDF file obtained after using the cut function has errors (No block found for the inverse conversion function)

![error2](https://github.com/danielhrisca/asammdf/assets/11522148/eb4de16f-f48f-4328-b401-31c08a2bdb11)

**Comment by danielhrisca** [comment]
@fhaon the inverse conversion is simply ignored. The latest development code will generate correct files (the link address is set to 0)
