### ISSUE TITLE
Can i make Signals from time series data which datatype =string?

### ISSUE THREAD

**Issue by darlingbud** [danielhrisca/asammdf#1028]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) '
'[MSC v.1936 64 bit (AMD64)]')
'os=Windows-10-10.0.22621-SP0'
'numpy=1.26.4'
'asammdf=7.4.1'

```
# Code 

  ## MDF version
  MDF=4.0

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description
Thank you working , I have some question.
I want read  some time series data from '.CSV'  file and turn to MDF data , then save the data as MDF file.
I use pandas to read CSV file and turn the time series to Signals, then make MDF from the Signals.
I learn the document example 'Working with Signal',and imitate the code , It works when  the  datatype=' float' or 'int' .
But if the datatype = 'string', Can I make the time series data to Signal and make MDF file ?

**Comment by danielhrisca** [comment]
Have a look here 

https://github.com/danielhrisca/asammdf/blob/c9d0e449000ed70f2ea1dd47df7c80f3e74471c5/examples/mf4_demo.py#L67

you need to convert to bytes series and provide the encoding to the Signal object
