### ISSUE TITLE
Issue in mdf_v4, evaluate

### ISSUE THREAD

**Issue by schaefMa** [danielhrisca/asammdf#103]
# Python version
('python=3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) [MSC v.1900 '
 '64 bit (AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.15.2'
'asammdf=4.3.0'
# Code 

  ## MDF version
 4.10

  ## Code snippet
  values = evaluate("values * a + b") # in mdf_v4
=======>>>>change to:  values = values * a + b

  
  ## Traceback
 File "C:\Users\schae\Anaconda3\lib\site-packages\asammdf\mdf.py", line 1125, in export
    sig = self.get(group=i, index=j, data=data)
  File "C:\Users\schae\Anaconda3\lib\site-packages\asammdf\mdf_v4.py", line 5039, in get
    vals = conversion.convert(vals)
  File "C:\Users\schae\Anaconda3\lib\site-packages\asammdf\v4_blocks.py", line 2234, in convert
    values = evaluate("values * a + b")
  File "C:\Users\schae\Anaconda3\lib\site-packages\numexpr\necompiler.py", line 820, in evaluate
    return compiled_ex(*arguments, **kwargs)
TypeError: Iterator operand 3 dtype could not be cast from dtype('uint64') to dtype('int64') according to the rule 'safe'

# Description

Solution is: values = values * a + b

**Comment by schaefMa** [comment]
Hi @danielhrisca,

yeah, issue exist in latest commit too

**Comment by danielhrisca** [comment]
I've removed the use of numexpor evaluate. Pleas confirm again if the new code works.

**Comment by danielhrisca** [comment]
_savemat_ is called with the default value of _oned_as_ (row https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.savemat.html)

https://github.com/danielhrisca/asammdf/blob/development/asammdf/mdf.py#L1449

**Comment by danielhrisca** [comment]
Hello @schaefMa ,

please try the new keyword argument for the _export_ method that exposes the _savemat_ argument (https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.export)

```python
mdf =MDF(path)
mdf.export('mat', 'mat_exported.mat', oned_as="column")
```

**Comment by schaefMa** [comment]
Hi @danielhrisca,

the parameter oned_as in the export function has no effect and I can't see any changes in mdf / mdf_v4. I think this parameter will not be used.

**Comment by danielhrisca** [comment]
Is this not what you were expecting?

```python

from asammdf import MDF, Signal
from scipy.io import loadmat
import numpy as np

import os

for mode in ('row', 'column'):

    if os.path.exists('mat_export.mat'):
        os.remove('mat_export.mat')

    mdf = MDF()

    mdf.append(Signal(np.arange(100), np.arange(100), name='sig'))

    mdf.export('mat', 'mat_export.mat', single_time_base=True, oned_as=mode)

    x = loadmat('mat_export.mat')['sig']

    print(mode, x.shape)
```

which prints

```
row (1, 100)
column (100, 1)
```

**Comment by schaefMa** [comment]
That's exactly what I want. But I can't reproduce this result. My output of the code snippet is:
```
row (1, 100)
column (1, 100)
```
with
```
('python=3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) [MSC v.1900 '
 '64 bit (AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.15.2'
'asammdf=4.3.1'
```

**Comment by danielhrisca** [comment]
Well you need to install the code from thw development branch

``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by danielhrisca** [comment]
@schaefMa 
did you try the latest code?
