### ISSUE TITLE
Channels tab empty

### ISSUE THREAD

**Issue by pansini-asensus** [danielhrisca/asammdf#1030]
# Python version
3.10.4

  ## MDF version
MDF4

  
# Description
Hi,
I'm trying to open a mdf4 file created by Acontis Real-time Data Acquisition (DAQ) Library. Here the link of the website: [https://www.acontis.com/en/real-time-data-acquisition.html]

The library generated a file ([ecmaster_daq.zip](https://github.com/user-attachments/files/15511920/ecmaster_daq.zip)) 

I tried to open it using asammdf GUI but there is anything on the channels tab
![image](https://github.com/danielhrisca/asammdf/assets/107107648/e6570051-d733-4ed0-b6ca-0121daaa070c)
Any idea why I couldn't see anything?
Thanks

**Comment by danielhrisca** [comment]
It means that the file does not contain signals

**Comment by pansini-asensus** [comment]
Is there a way to open the mf4 file and look for the signals? The Acontis library provide only the API functions to configure and write the files so I couldn't look into that

**Comment by pansini-asensus** [comment]
I used Vector MDF Validator and this is the result:
![image](https://github.com/danielhrisca/asammdf/assets/107107648/26453a0a-f1f3-4865-890a-2334dd5cde3a)

**Comment by danielhrisca** [comment]
No data groups = no signals
