### ISSUE TITLE
I want to remove Groups from MDF file

### ISSUE THREAD

**Issue by wonyoung00** [danielhrisca/asammdf#104]
# Python version
_Please run the following snippet and write the output here_
: ('python=3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17134-SP0

try:
    import numpy
    pprint("numpy=" + numpy.__version__)   : 'numpy=1.15.4'

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)  : 'asammdf=4.3.0'

# Code 
    from asammdf import MDF

    mdf = MDF()                    
    FILENAME = "test.dat"         
    yop = MDF(FILENAME)
    yop2 = yop.resample(0.01)
    
    gr_no = yop2.whereis("WHL_SDD_RR")[-1][0]
    gr = yop2.get_group(gr_no)
    whl_spd_rr  = yop2.get("WHL_SPD_RR)

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``) : 3.2

  ## Code snippet
  _please write here the code snippet that triggers the error_
   : It take very long time to calculate
    groups are 192 and signals are 2000
  I just use 20 groups and 100 signals.
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

--------------------------------------
I have MDF file from a vehicle. that is too big about 100~200MBs
so, It's long time to resample (0.01sec) and calculate
I like to remove some groups not including in calculation

**Comment by danielhrisca** [comment]
Hello @wonyoung00 ,

the best way would be to filter the required channels:

```python
yop = MDF(file_name, memory='minimum')

to_keep = ['Channl1', 'Channel2'] # and so on
resamples = yop.filter(to_keep).resample(0.01)

# now you can use the new MDF object
s1 = resampled.get('Channel1')
```

**Comment by danielhrisca** [comment]
I've made some changes in the development branch that should help you out

I would suggest using this snippet

```python
yop = MDF(file_name, memory='minimum')

to_keep = ['Channl1', 'Channel2'] # and so on
df = yop.filter(to_keep).cut(start=240, stop=2050).export('pandas', raster=0.01)

```

**Comment by danielhrisca** [comment]
@wonyoung00 
did it work for you?

**Comment by wonyoung00** [comment]
Great!!!!. It works that I would make it. 
I'm sorry that I can't visit during weekend..
Thanks alot.

**Comment by danielhrisca** [comment]
I guess we can close this issue. Feel free to open again if you find related problems.

**Comment by wonyoung00** [comment]
@danielhrisca 
I have another problem.
My MDF file has same channel name and different values in different groups.
(I think that my subject name is "remove Groups from MDF file")

yop.whereis('CR_Bms_Soc_Pc')
((45, 1), (102, 11))

for example: 
soc_45 = yop.get_group(45).CR_Bms_Soc_Pc
min(soc_45) = 0.0
max(soc_45)=0.0

I only want to use group_102 not group_45
How do I treat group 102?

**Comment by danielhrisca** [comment]
You have this covered as well (see [filter documentation](https://asammdf.readthedocs.io/en/master/api.html#asammdf.mdf.MDF.filter))

```python
yop = MDF(file_name, memory='minimum')

to_keep = ['Channl1', 'Channel2', ('CR_Bms_Soc_Pc', 102) ] # and so on
df = yop.filter(to_keep).cut(start=240, stop=2050).export('pandas', raster=0.01)
```

**Comment by wonyoung00** [comment]
Thanks a lot  !!!
