### ISSUE TITLE
combination multiple small files together faced problem: OSError: [Errno 27] File too large

### ISSUE THREAD

**Issue by HuixuanGan** [danielhrisca/asammdf#1040]
## Code snippet
  def merge_mdf_files(file_paths):
    # Initialize the first MDF object
    mdf_list = []
    # merged_mdf = asammdf.MDF(file_paths[0])
    
    print(file_paths)
    # Load subsequent MDF files and append them to the first
    for file_path in file_paths:
        
        if os.path.exists(file_path): 
            
            mdf = asammdf.MDF(file_path)
           
            print(f"File found: {file_path}")  
            # This should append the contents of mdf to merged_mdf

        mdf_list.append(mdf)
    
    merged_mdf = asammdf.MDF.concatenate(mdf_list)  

# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

I wanted to combine about 700 MF4 files together which have about 320MB, however, I faced such error,  could you tell me how to resolve this?

**Comment by danielhrisca** [comment]
Share the complete error traceback mesage

**Comment by danielhrisca** [comment]
https://stackoverflow.com/questions/10956175/file-too-large-python

Are you using a file system that does not support large files?
