### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by subesokun** [danielhrisca/asammdf#105]
Hi, we'd like to use your library but we're facing some licensing issue introduced by the `matplotlib` which is one of the package's dependency. 

We're running our code in an Alpine-based Python3 variant and when `pip` tries to install `matplotlib` it complains that it can't find the `freetype` package. The `freetype-dev` package for Alpine (see https://pkgs.alpinelinux.org/package/edge/main/x86/freetype-dev) is licensed under  FTL (FreeType License) and GPL-2.0-or-later and it seems like the FTL doesn't require us to open source the code (none copyleft). Anyhow, we'd like to completely prevent installing this package because we do not use/need the GUI feature.

Hence I'd like to kindly ask if it would be possible to move the GUI part of this package into an extra package so that you can just install the ASM reader without the UI part. That would be awesome!

**Comment by danielhrisca** [comment]
Hello @subesokun ,

_matplotlib_ was used as optional dependency so I removed it from _setup.py_

Please check if the new development code is working ok

**Comment by subesokun** [comment]
@danielhrisca Awesome! Thanks a lot for the quick fix! Now the install works like a charm 👍

**Comment by danielhrisca** [comment]
great, let me know if you find other issues
