### ISSUE TITLE
asammdf-gui copy may cause only partial copy

### ISSUE THREAD

**Issue by mm-mm-bb** [danielhrisca/asammdf#1054]
# asammdf-gui version
development https://github.com/danielhrisca/asammdf/commit/872af032174317c8107ac4fa3bff4b766024e612 (broken)
release 7.5.0.dev2 (broken) 

# Description
- open some can mf4 can trace (in my case from canEdge1) with decent amount of data (>100.000 messages)
- enter "Can bus trace" view
- select a big chunk of data (all), ctrl+c
- in a text editor ctrl+v

both editors and asammdf will hang, after hanging the copied text has good changes to be only a cell instead of all the selection, sometimes panda/clipbard error on the console, sometimes dont, not sure if related (cant reproduce)

# Workaround
wait for asammdf to complete the "copy" before pasting; try switch tab or click a single element. asammdf  will hang until the "copy" is run, but after it will get unstuck, the ctrl + v will work as expected and paste all the selected data.
Probably quick fix is to add a little load animation

**Comment by danielhrisca** [comment]
@mm-mm-bb please try the development branch code

**Comment by mm-mm-bb** [comment]
tested with a 2mln and a 600k record file, now only the asammdf hangs (not responding).
Much better, but still a little "hey, this may take some time" message and/or a loadbar would be nice
