### ISSUE TITLE
Asammdf keeps file open when it cannot read it correctly

### ISSUE THREAD

**Issue by eblis** [danielhrisca/asammdf#1061]
# Python version
Asammdf 7.4.2
Python 3.9 and 3.11

# Code 

  ## MDF version
  4.10

  ## Code snippet
```python
try:
  with MDF(file_path) as mdf_obj:
    # ..
except Exception as ex:
  # mdf_obj.close() # can't call this function as mdf_obj is not defined anymore, and was never assigned a value to begin with
  move_file(file_path, "some/other/folder") # permission error, file_path is still in use
```
  
  ## Traceback
I don't have a traceback as I debugged this issue on a colleague's machine, but I can show you the call trail.
  
# Description

Asammdf keeps a file open after it has finished attempting to read from it (and failed with an exception), and we cannot access the file to move it even after asammdf object is out of scope. And since the asammdf object is out of scope we cannot manually try to close the file with `mdf_obj.close()` as `mdf_obj` isn't defined anymore.

We have an MDF file with 4.10 version, around 2GB in size which throws an exception in MDF.__init__() which has 2 issues:
1. The `with` statement cannot be used for such files, as it never enters the context manager, since the `__init__()` function crashes before `__enter__` has a chance to be called. Since `__enter__` is never called, nor will `__exit__` be called so there's no way for MDF object to close itself automatically.
2. The bigger issue I think, the underlying file is kept open by asammdf even after `__init__` has crashed with an exception, preventing anyone else from opening the file for writing or from moving the file to another location.

the `with MDF(file_path) as mdf_obj:` statement calls are like this:
* first `MDF.__init__()` is called, [here](https://github.com/danielhrisca/asammdf/blob/master/src/asammdf/mdf.py#L214)
* Since this is version 4.10 we end up loading [MDF4](https://github.com/danielhrisca/asammdf/blob/master/src/asammdf/mdf.py#L332)
* So `MDF4.__init__()` is called, [here](https://github.com/danielhrisca/asammdf/blob/master/src/asammdf/blocks/mdf_v4.py#L259)
* After some initializations and some other things, it memory maps the file and tries to read it, [here](https://github.com/danielhrisca/asammdf/blob/master/src/asammdf/blocks/mdf_v4.py#L385)
* First part is read ok, but when we get to read the [HeaderBlock](https://github.com/danielhrisca/asammdf/blob/master/src/asammdf/blocks/mdf_v4.py#L484) it crashes with some kind of seek offset error, 
* At this point an exception is raised and the `with` statement never finishes executing (context manager never engages). If we didn't have the `try/catch` block it would raise the exception to the calling method
* Since `__enter__` was never called, nor will `__exit__` be called, so the MDF file has opened `file_path` and never closed it at this point.
* And the bigger problem, the call to `move_file(file_path, "some/other/folder")` fails with permission error as the file_path is still kept open by `mdf_obj`, even though `mdf_obj` is no longer defined and cannot be used in code.

**Comment by danielhrisca** [comment]
@eblis please try the development branch code

**Comment by eblis** [comment]
The move operation is still prevented with permission error.
I think you need to close more than just the file.

We tried with the following changes and then it started working. Is there any downside to closing everything, calling `close()` on the MDF object, not only the `_file` ?
```diff
-                except:
-                    if self._file:
-                        self._file.close()
-                    raise
+                except:
+                    self.close()
+                    raise
```

**Comment by danielhrisca** [comment]
new commit

**Comment by eblis** [comment]
This works
