### ISSUE TITLE
save() doesn't close file

### ISSUE THREAD

**Issue by mw25** [danielhrisca/asammdf#1063]
# Python version
('python=3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]')
'os=Windows-10-10.0.19045-SP0'
'numpy=1.26.4'
'asammdf=7.4.5'

# Code 

  ## Code snippet

```
import os
from asammdf import MDF, Signal


signals = [Signal([1, 2, 3], [1, 2, 3], name='A')]

with MDF(None) as mdf4:
    mdf4.append(signals, 'Table')
    mdf4.save('file.mf4')
   
with MDF('file.mf4') as mdf4:
    mdf4.append(signals, 'Table')
    mdf4.save('file.mf4', overwrite=True)
    # mdf4._closed = False

os.remove('file.mf4')
```
  
  ## Traceback
  At the last line:
`PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'file.mf4'`

Translation: The process cannot access the file because it is being used by another process

  
# Description

When appending to an existing file, the file does not seem to be closed correctly with save().
When I activate the commented line it works fine.

**Comment by danielhrisca** [comment]
`save` will not close the file, you have to call `close` on the object

**Comment by mw25** [comment]
I'm sorry, but I still don't get it. On which object should I call `close`? `mdf4.close()` after `save()` doesn't help.
I open the file with the `with` statement and save/overwrite the same file. I thought the with statement would close that file with the `__exit__` function.

**Comment by MikeSuhy95** [comment]
I suggest re-opening this issue - calling ```save()``` to overwrite an existing file where the save destination is the same as the source the file was opened from leaves an opened file reference that is not closed when ```close()``` is called later.

If the condition on line 10216 in the ```save()``` function in mdf_v4.py is matched, the ```save()``` function calls ```self.close()``` on line 10217, which sets ```self._closed = True```. ```save()``` then re-opens the file on 10236 in mdf_v4.py but does not reset ```self._closed```. Subsequent calls to ```close()``` will hit the short-circuit condition on line 6475 and not release the file.

Manually setting ```._closed = False``` after saving as mw25 had in a commented-out line in the given example appears to be a successful workaround.
