### ISSUE TITLE
Channel Conversion Metadata Loses Precision

### ISSUE THREAD

**Issue by markwaterbury** [danielhrisca/asammdf#1073]
https://github.com/danielhrisca/asammdf/blob/c9d0e449000ed70f2ea1dd47df7c80f3e74471c5/src/asammdf/blocks/v4_blocks.py#L4061

When displaying the metadata() for a channel conversion block, rounding may cause no value to be displayed. If the conversion type is linear, for instance, the `a` factor can often be a small number like `1e-12`, but when rounded, will just show `0.0`.

**Comment by danielhrisca** [comment]
thanks, please check the development branch code

**Comment by markwaterbury** [comment]
Excellent, that fixes it. Thanks!
