### ISSUE TITLE
Streaming/Appending support?

### ISSUE THREAD

**Issue by jed-frey** [danielhrisca/asammdf#11]
Examples all use a fixed set of data to create new files.

I'd like to ditch CANalyzer and and dSpace setup and replace a chunk of it with a Pi, some MPC2515 based adapter and other middleware. [SocketCAN](https://en.wikipedia.org/wiki/SocketCAN) supports quite a few adapters. Being able to drop our CANcase Loggers for certain cases would be great.

Not sure the best way to implement it:

Pesudo code:

    mdf4 = MDF(version='4.00')
    s_engspd= Signal(name='EngineSpeed', unit='f8')

    ....

    signals = [s_engspd, s_imap, s_fuel]
    mdf4.stream(signals, 'Created by Python')

    t, s = pyccp.decode(python_can.read())
    s_engspd.append(timestamp = t, sample=s)
    
    mdf4.flush() # Write to disk.

Looking to shoehorn asammdf in with these tools for live data collection:

- [python-can](http://python-can.readthedocs.io/en/latest/interfaces.html)
- [pyccp](https://github.com/pySART/pyccp)
- [pyA2L](https://github.com/pySART/pyA2L)

**Comment by danielhrisca** [comment]
Hello Jed,

this is an interesting use case.

At a first glance I would go with a new _MDFRecorder_ class. This would use the _MDF_ class in the final step of writing the finished file. 
Some changes would also needed for the _Signal_ class. 

However I would not rush into a definitive conclusion. This is the kind of topic that requires careful analysis and design.

What is your estimate regarding the acquisition rate? What you want to accomplish is  the equivalent of CANape and I'm not sure Python is suitable for "real time" signal acquisition?

**Comment by jed-frey** [comment]
> However I would not rush into a definitive conclusion. This is the kind of topic that requires careful analysis and design.

Definitely. Dethroning a well entrenched industry tool is not a light task.

> What is your estimate regarding the acquisition rate? 

Assume 1 Mb/s as a minimum. It's the max data rate for existing CAN buses. J1939 is still at 250 kB/s. 

Eventually I'd like to workup to using the MPC5748G as a CAN<->Ethernet gateway and it supports up to 8 FlexCAN with optional CAN FD support.

Small SBCs these days are as fast as the machines we had a decade ago doing CANape work. The [CANcaseXL Loggers](https://vector.com/portal/medien/cmc/manuals/CANcaseXL_Manual_EN.pdf) are tiny embedded devices writing to SD cards (and haven't been upgraded that I've seen in a while). I don't think we should have a problem keeping up as long as the disk can handle the write speed.

**uvloop** is an async I/O event loop and has some pretty decent benchmarks: https://magic.io/blog/uvloop-blazing-fast-python-networking/ Granted this is serving message requests but @ 1 KiB message sizes it's serving 102MiB/s, and 100 KiB message sizes 2.3GiB/s. As long as we're not doing any heavy filtering or data processing I think a Pi should be able to handle the data rates. 

A machine with at least 2 cores should have no problem keeping up with reading packets and flushing them to disk.

**Comment by danielhrisca** [comment]
Hello Jed,

I've just pushed a new branch with the initial streaming support.

Here is how it should be used:

```python
from asammdf import Recorder, ChannelDescriptor
from numpy import dtype

rec = Recorder('measurement.mf4')

# first source
channels = [
    ChannelDescriptor('CH1', 's', 'first channel', dtype('S')),
    ChannelDescriptor('CH2', 'm', 'second channel', dtype('<u4')),
    ChannelDescriptor('CH3', 'rpm', 'third channel', dtype('<f2')),
]

deposit1 = rec.register(channels)


# second source
channels = [
    ChannelDescriptor('CH_A', 'mph', 'first channel', dtype('>u8')),
    ChannelDescriptor('CH_B', 'rad', 'second channel', dtype('<i4')),
    ChannelDescriptor('CH_C', 'us', 'third channel', dtype('<f8')),
]

deposit2 = rec.register(channels)

# start measurement

rec.start()


while 1:
    
    if source1.has_samples:
        # source samples is a list of python int, float or str objects
        deposit1.append(source1.samples)
        
    if source2.has_samples:
        # source samples is a list of python int, float or str objects
        deposit2.append(source2.samples) 
        
    # stop measurement when some condition is True
    if stop_condition:
        break
    
# stop recorder and the measurement is saved automatically

rec.stop()
```

You have to make sure to keep the sample values in the same order as the one used for registering to the Recorder object.

Everything is kept in the RAM until the _stop_ method is called. At this point the MF4 file is created and the used RAM should be freed.

I'm curious to see how this works and please let me know what you think about the API and features.

**Comment by jed-frey** [comment]
Looks interesting and a good start. Hopefully I can get some time to work with it in the next month(s).

In the future a ```flush()``` command to write to disk would help to balance RAM usage and data loss. I'd like to use a RaspberryPi as a field data logger.

**Comment by danielhrisca** [comment]
At this point the implementation is crude: just appending to a list and recording the timestamps. 
It is definitely desirable to have some sort of periodic data save to disk (nothing of this kind is implemented so far).
Another point would be to have some kind of plugin system, so that the Recorder can drive the data logging/polling; in short to work more la CANape.

**Comment by danielhrisca** [comment]
The new _extend_ method could be useful for streaming new samples to the _MDF_ object.
