### ISSUE TITLE
DBC state variable is not shown in Plot

### ISSUE THREAD

**Issue by Raf-ai-dev** [danielhrisca/asammdf#1114]
I'm having issues after loading a mf4 trace file into the GUI and start doing my plots that for some of the variables I have in my DBC (BMS state, VCU state) I'm only seeing hex numbers in the plot window. In the CANdb++ editor those signals have different states for example 0x5 is the state when the BMS is in charging AC mode and so on. In CANape I always see the text on those variables but for some reason it doesn't work like that in the asammdf gui. Is there a postsability to include this functionalty in the next update? I would love to include some data and pictures but I can't because of confidential provisions but I think it is clear.

Kind regards

**Comment by danielhrisca** [comment]
please try again with this build https://github.com/danielhrisca/asammdf/actions/runs/12290939445

**Comment by Raf-ai-dev** [comment]
Hey Daniel,

thanks a lot. Works now as expected! Amazing

Regards

Am Do., 12. Dez. 2024 um 07:26 Uhr schrieb Daniel Hrisca <
***@***.***>:
