### ISSUE TITLE
asammdf-gui Exception

### ISSUE THREAD

**Issue by id872** [danielhrisca/asammdf#112]
# Python version
'python=3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 '
 'bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.16.0'
'asammdf=4.7.5'

# MDF version
 V3

# Traceback
![s1](https://user-images.githubusercontent.com/45285868/51240785-bda72e00-197c-11e9-92e1-c294591cc75e.png)

# Description
This issue occurs in the latest asammdf. There is no problem in the asammdf 4.3.0.
I will send you an email with the details.

**Comment by danielhrisca** [comment]
@id872 
release 4.7.6 fixes this issue

**Comment by id872** [comment]
Fast fix. Thank you very much.

In the email I described other problem, the recursion exception. 
I don't know if it is the issue with my file (large group of signals) or if it is the problem in the asammdf.

**Comment by danielhrisca** [comment]
I'll close this and the recursion error will have to wait a bit for further testing (fix available in Py3 branch)
