### ISSUE TITLE
Question on Cutting Specific Data Points

### ISSUE THREAD

**Issue by Cages3** [danielhrisca/asammdf#114]
I am working with mdf files that have unreasonably high spikes at specific points due to hardware issues. I was wondering if there was any way to get rid of these specific points while keeping the rest of the data the same. Thank you.

**Comment by danielhrisca** [comment]
Hello @Cages3,

for now there is nothing specific for this and I doubt it makes sense.

You could do something like this:

```python
from asammdf import MDF
import numpy as np
mdf = MDF(file_name)

channel = mdf.get(channel_name)

range = lower, upper # unreasonable limits

valid_indexes = np.intersect1d(
    np.nonzero(channel>=lower), 
    np.nonzero(channel<=upper)
)

channel.samples = channel.samples[valid_indexes]
channel.timestamps = channel.timestamps[valid_indexes]

channel.plot() # should look clean now
```

**Comment by Cages3** [comment]
Would it also be possible to edit specific points? In that case the spike points can be turned into averages of their neighboring points.

**Comment by danielhrisca** [comment]
Try this

```python
from asammdf import MDF
import numpy as np
mdf = MDF(file_name)

channel = mdf.get(channel_name)

unreasonable_range = lower, upper # unreasonable limits

valid_indexes = np.intersect1d(
    np.nonzero(channel>=lower), 
    np.nonzero(channel<=upper)
)

old_timestamps = channel.timestamps

channel.samples = channel.samples[valid_indexes]
channel.timestamps = channel.timestamps[valid_indexes]

clean_channel = channel.interp(old_timestamps)

clean_channel.plot() # should look clean now
```

**Comment by danielhrisca** [comment]
The current release code will do linear interpolation for float channels and will repeat the previous sample for integer channels.

The Py3 branch can do a linear interpolation even for integer channels
