### ISSUE TITLE
GUI resample, filter and cut doesn't work

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#115]
# Python version
'python=3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.14393-SP0'
'numpy=1.15.4'
'asammdf=5.0.0dev'

# Code 

  ## MDF version
  4.10

  ## Code snippet
  N/A
  
  ## Traceback
 N/A
  
# Description

Resample, Filter and Cut doesn't work. After the selection of the target filename the process window is opened with text "Resampling measurement (not responding)"

The programm runs to asammdf\gui\utils.py line 81 
```
while widget.progress is None:
        sleep(0.1)
```
```
ipdb> thr.is_alive()
False
```

Example Data was created with asammdf:
```
timestamps = np.arange(0,150,0.1, dtype=np.float32)

# unit8
s_uint8 = Signal(samples=np.random.randint(0,254,1500),
             timestamps=timestamps,
             name='Uint8_Signal',
             unit='u1')
# int32
s_int32 = Signal(samples=np.random.randint(0,2500,1500),
                 timestamps=timestamps,
                 name='Int32_Signal',
                 unit='i4')

# float64
s_float64 = Signal(samples=np.random.random_sample(1500),
                   timestamps=timestamps,
                   name='Float64_Signal',
                   unit='f8')

# create empty MDf version 4.10 file
with MDF(version='4.10') as mdf4:

    # append the 3 signals to the new file
    signals = [s_uint8, s_int32, s_float64]
    mdf4.append(signals, 'Created by Python')

    # save new file
    mdf4.save('mdf_sample.mf4', overwrite=True)`
```

ressampling in IPython console works fine with: 

```
def create_mdf_resample(input_filename, output_filename, sample_rate):
    
    with MDF(input_filename) as mdfile:
        mdf4_resampled = MDF(version='4.10')
        mdf4_resampled = mdfile.resample(sample_rate,version='4.10')
        mdf4_resampled.save(output_filename)
        
        mdf4_resampled.save(filename_mdf, compression=2, overwrite=True)
```

**Comment by danielhrisca** [comment]
Hello @stlweb,

please try the new code from the Py3 branch

**Comment by stlweb** [comment]
Hello @danielhrisca, 
the new code works fine, but y-axis scaling doesn't work anymore. I'm not sure if it was working in the previeous version.

**Comment by danielhrisca** [comment]
You should be able to select a channel from the list and scroll on the axis that will appear in the right side of the plot

**Comment by danielhrisca** [comment]
I've disabled the context menu since it was taking a lot of time to generate the plot for a large number of selected channels.

The new code in Py3 fixes the axis scaling issue

**Comment by stlweb** [comment]
scaling of axis is fine, but resampling stoped working

`Traceback (most recent call last):
  File "D:\Software\WPy-3710_dev\python-3.7.1.amd64\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Software\WPy-3710_dev\python-3.7.1.amd64\lib\site-packages\asammdf-5.0.0.dev0-py3.7.egg\asammdf\gui\utils.py", line 142, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "D:\Software\WPy-3710_dev\python-3.7.1.amd64\lib\site-packages\asammdf-5.0.0.dev0-py3.7.egg\asammdf\blocks\mdf_v4.py", line 5322, in save
    write(bytes(block))
  File "D:\Software\WPy-3710_dev\python-3.7.1.amd64\lib\site-packages\asammdf-5.0.0.dev0-py3.7.egg\asammdf\blocks\v4_blocks.py", line 2935, in __bytes__
    fmt = v4c.FMT_DZ_COMMON + "{}s".format(self.zip_size)
AttributeError: zip_size`

**Comment by danielhrisca** [comment]
There was a bad implementation for DZBLOCK. Please try the new code

**Comment by stlweb** [comment]
The actual code runs fine. I've tested convert, filter, resample and concatenate of multiple files.

**Comment by danielhrisca** [comment]
I'll close this for now. You can reopen it if you come across new bugs.
