### ISSUE TITLE
Y-axis without values and name

### ISSUE THREAD

**Issue by loucik** [danielhrisca/asammdf#116]
# Python version
('python=3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.14.6'
'asammdf=4.7.7'
'pyqtgraph=0.10.0'

  ## MDF version of input file
4.00

  ## Code snippet
see the attached screen
![mdf_error](https://user-images.githubusercontent.com/46992568/51668535-b4444400-1fc2-11e9-9a1a-c512765e9cb0.PNG)

# Description of issue
There are missing values and names for signals of **y-axis** . No values, no description of y-axis.

**Comment by danielhrisca** [comment]
Hello @loucik ,

please print the channel so I can get an idea about the problem

```python
mdf = MDF(filename)
print(mdf.get(channelname))
```

**Comment by loucik** [comment]
Hello @danielhrisca,
info regarding signal is following:
`        samples=[8191 8191 8191 ... 4784 4824 4824]
        timestamps=[1.88256300e+00 1.92257300e+00 1.96257500e+00 ... 6.09821841e+03
 6.09825842e+03 6.09825842e+03]
        unit="Unit_Secon"
        conversion=<ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: {'text_0': {'id': b'##TX', 'reserved0': 0, 'block_len': 32, 'links_nr': 0, 'text': b'Init\x00'}, 'default_addr': <ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: None, address: 0xf7fd4890, fields: {'id': b'##CC', 'reserved0': 0, 'block_len': 96, 'links_nr': 4, 'name_addr': 0, 'unit_addr': 0, 'comment_addr': 0, 'inv_conv_addr': 0, 'conversion_type': 1, 'precision': 255, 'flags': 1, 'ref_param_nr': 0, 'val_param_nr': 2, 'min_phy_value': 0.0, 'max_phy_value': 0.0, 'b': 0.0, 'a': 0.001})>}, address: 0xf7fd48f0, fields: {'id': b'##CC', 'reserved0': 0, 'block_len': 104, 'links_nr': 6, 'name_addr': 0, 'unit_addr': 0, 'comment_addr': 0, 'inv_conv_addr': 0, 'text_0': 4160571504, 'default_addr': 4160571536, 'conversion_type': 7, 'precision': 0, 'flags': 4, 'ref_param_nr': 2, 'val_param_nr': 1, 'min_phy_value': 0.0, 'max_phy_value': 0.0, 'val_0': 8191.0})>
        source=SignalSource(name='Measure1', path='Header', comment='', source_type=1, bus_type=5)
        comment="none"
        mastermeta="('t', 1)"
        raw=True
        display_name=
        attachment=()>`

Just to note, if I plot same signal via Spyder console, I can see also y-axis name and values. No crash.
Also, did you try to plot more than one signal via MDF GUI? Can you see y-axis name and values?

Thanks for help.

**Comment by loucik** [comment]
Hello @danielhrisca,
I tried to copy folder "asammdf" from dev.branch. But still I am getting issue. Please, look at the screen.

**Comment by danielhrisca** [comment]
@loucik 

developemnt branchs eems to work for me:

![image](https://user-images.githubusercontent.com/20952040/51828169-af99cb80-22f3-11e9-879b-007bdf3fc44b.png)

run this to make sure the new code is updated

``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by danielhrisca** [comment]
You can see the _asammdf_ lib version in the lower right side of the window. In your case you have still 4.7.7

**Comment by loucik** [comment]
You are right, I did not update version.
Now, it seems bug is fixed. Can I ask, what was wrong?

Thanks for the support.

**Comment by danielhrisca** [comment]
fixed in release 4.7.8

**Comment by danielhrisca** [comment]
@stlweb 
please check if the new commit in Py3 fixes the problem
