### ISSUE TITLE
How to efficently record continuous data and convert an existing measurement

### ISSUE THREAD

**Issue by haniham** [danielhrisca/asammdf#117]
Hello,
Could anyone tell me what is the most efficient way to record continuous measured data?
Do i need to record all data in arrays and at the end write them back?

What is likewise the best way to convert an existing file to MDF?
Best wishes, Markus

**Comment by danielhrisca** [comment]
@haniham 
did you succeed in applying the suggestions?

**Comment by haniham** [comment]
Hey, thanks for your reply.

Currently i have little time to work on my solution but i now know that i have to keep the entire measurement in the memory because of the structure of the MDF File.

It doesn't allow me to continously write data to the HDD and then forget them.

**Comment by danielhrisca** [comment]
I'm working on a recorder in the Py3 branch
