### ISSUE TITLE
Code quality improvement.

### ISSUE THREAD

**Issue by jed-frey** [danielhrisca/asammdf#12]
I'm starting to do some static analysis and linting at work and needed a demo project so work can't claim it's anything I worked on (and let the commit record show I've not done anything for asammdf).

This is from Jenkins on a DigitalOcean instance and ran my fork of asammdf through flake8 (with a lot of customization).

Using the [Jenkins Warnings plugin](https://wiki.jenkins.io/display/JENKINS/Warnings+Plugin).

[Flake8 Warings](https://ci.do.exstatic.org/job/asammdf-flake8/4/warnings2Result/) Using a custom parser regex and mapping script.

The former allows more flexibility in reporting, the latter requires less setup. Both are using the same flake8 settings.

Build > Execute Shell:
```
. /opt/asammdf_venv/bin/activate
python --version
flake8 --version
flake8  --exit-zero --format=default --output-file=flake8.log
flake8  --exit-zero --format=pylint  --output-file=flake8_pylint.log
```

**Comment by danielhrisca** [comment]
Right now I'm tackling channel arrays for mdf version 4 (compatibility for convert, save). This will have to go lower on the priority list, but it will get it's turn.

**Comment by jed-frey** [comment]
More of an Enhancement/FYI. Once I get some breathing room on my personal projects as the northern hemisphere cools I hope to be a productive contributer.

**Comment by danielhrisca** [comment]
Hi Jed,
your links are no longer active.
Could you please run the checks again?

**Comment by danielhrisca** [comment]
I'm slowly advancing on this topic.
However there are some limitations on the linter side that will always flag errors. For example the way the underlying MDF3 or MDF4 object is hooked to the MDF class is not handled by the linters. Also the Python 2 compatibility _bytes_ function also is unavoidably will trigger an warning.

**Comment by jed-frey** [comment]
FYI: Jenkins server is going to go down as I re do my cloud 'infastructure'.
