### ISSUE TITLE
Feature - Independent time vectors.

### ISSUE THREAD

**Issue by allaboutjeeps** [danielhrisca/asammdf#120]
No bugs or issues, but I would like to request a feature/improvement.

In today's implementation, it takes the union of all the time vectors, uses it for all the signals and interpolates the signals at the new times. It would be extremely helpful to allow for each signal to have a truly independent time vector. This could be accomplished by writing each signal to a new and unique channel group block or data group block.

**Comment by danielhrisca** [comment]
Hello @allaboutjeeps ,

I think this is easy even with the current implementation: just call append for each signal

```python
mdf = MDF()
signals = [s1, s2, s3]
# single group with interpolated signals
mdf.append(signals)

# individual groups with independent time stamps
for signal in signals:
    mdf.append(signal)
```

**Comment by allaboutjeeps** [comment]
You are correct! Worked perfectly. Thanks for the help and great tool!
