### ISSUE TITLE
resample > 0 results in TypeError

### ISSUE THREAD

**Issue by ofesseler** [danielhrisca/asammdf#121]
# Python version
```
('python=3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 ' '64 bit (AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.15.0'
'asammdf=4.7.8'
```
# Code 

  ## MDF version
 '4.10'

  ## Code snippet
```
with MDF("data/test.mf4") as mdf: 
    mdf.resample(0)
    mdf.resample(1)
```
The first resample works, nothing changes. And the second one raises the TypeError below
  ## Traceback

```
TypeError                                 Traceback (most recent call last)
<ipython-input-28-4a54695af50c> in <module>()
      1 with MDF("data/test.mf4") as mdf:
      2     mdf.resample(0)
----> 3     mdf.resample(1)

~\AppData\Roaming\Python\Python37\site-packages\asammdf\mdf.py in resample(self, raster, memory, version)
   2495                             sigs,
   2496                             "Resampled to {}s".format(raster),
-> 2497                             common_timebase=True,
   2498                         )
   2499                     else:

~\AppData\Roaming\Python\Python37\site-packages\asammdf\blocks\mdf_v4.py in append(self, signals, source_info, common_timebase, units)
   3349 
   3350             inval_bits = fliplr(
-> 3351                 packbits(array(inval_bits).T).reshape(
   3352                     (cycles_nr, invalidation_bytes_nr)
   3353                 )

TypeError: Expected an input array of integer or boolean data type
```
  
# Description

Every time I try to resample one of our mf4-files, I'll get a TypeError. But if I try one of your test files the resampling method executes without an error. Since the data is delicate, I'm not allowed to send you that file. 
Maybe you could give me a hint what I could try or where to take a look.

**Comment by danielhrisca** [comment]
I'm not sure I will have to look tomorrow. 

What about sending a scrambled file?

**Comment by danielhrisca** [comment]
Hello Oliver,

I think I've fixed the problem: the resampling was not correctly applied to the invalidation bits.

Please try the development branch code and see if this work for your files as well.

**Comment by ofesseler** [comment]
Hello Daniel,

you are incredible fast! Thank you. I managed to write a minimal
example for testing. But according to your message I guess you found
it.

```
from asammdf import Signal, MDF
import numpy as np
mdf = MDF()
mdf.append(Signal(np.sin(np.linspace(np.pi, np.pi*2, 200)),
np.array(range(200))*0.1,
                  name="sig_a"))
mdf.append(Signal(np.sin(np.linspace(-np.pi, np.pi*2, 20)), np.array(range(20)),
                  name="sig_b",
                  invalidation_bits=np.zeros(20, dtype="bool")))

mdf = mdf.resample(0.1)
```


On Thu, Jan 31, 2019 at 10:38 PM Daniel Hrisca <notifications@github.com> wrote:
>
> Hello Oliver,
>
> I think I've fixed the problem: the resampling was not correctly applied to the invalidation bits.
>
> Please try the development branch code and see if this work for your files as well.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Oliver Fesseler

Mobile: 0172/7767173
Mail: oliver@fesseler.info

**Comment by ofesseler** [comment]
Thanks for fixing it. I don't get the error anymore.

**Comment by danielhrisca** [comment]
Thank you for reporting the issue
