### ISSUE TITLE
Export to mat 7.3 Problem

### ISSUE THREAD

**Issue by ZhuYuqicheng** [danielhrisca/asammdf#122]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  runfile('C:/Users/ZYH7ABT/Desktop/asam_mat_1/function_set.py', wdir='C:/Users/ZYH7ABT/Desktop/asam_mat_1')
C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):

  File "<ipython-input-1-68109e5b22a4>", line 1, in <module>
    runfile('C:/Users/ZYH7ABT/Desktop/asam_mat_1/function_set.py', wdir='C:/Users/ZYH7ABT/Desktop/asam_mat_1')

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ZYH7ABT/Desktop/asam_mat_1/function_set.py", line 52, in <module>
    mf4_file.export('mat', filename='test', format='7.3')

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\mdf.py", line 1503, in export
    oned_as=oned_as,

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\hdf5storage\__init__.py", line 1681, in savemat
    options=options)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\hdf5storage\__init__.py", line 1319, in writes
    None, options)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\hdf5storage\lowlevel.py", line 114, in write_data
    m.write(f, grp, name, data, type_string, options)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\hdf5storage\Marshallers.py", line 567, in write
    + ' not supported by MATLAB.')

TypeNotMatlabCompatibleError: Data type uint32 not supported by MATLAB.
  
# Description

Hallo, the problem is, when I want to export my mf4 data as mat 7.3, I have got above traceback but when I export mf4 into mat version 5, that works.

**Comment by danielhrisca** [comment]
Hello @ZhuYuqicheng ,

I've tried with multiple measurements that contain uint32 channels and had no problem. Any chance you can send your file?

**Comment by ZhuYuqicheng** [comment]
Hallo @danielhrisca 

I'd like to do that, but my test data is too large for E-mail. Is there any way to send you this data?

**Comment by danielhrisca** [comment]
@ZhuYuqicheng 

do you get errors if you use iter_groups to iterate over the channel groups?

**Comment by ZhuYuqicheng** [comment]
Hallo @danielhrisca ,

Thanks for your answer! I got no errors when I run iter_groups().

**Comment by ZhuYuqicheng** [comment]
And I got also no errors with iter_channels(). That means the Measurement is no problem?
I have tried with exporting the mf4 into mat without setting of **format='7.3'**, that works too.

The error seems to be that: some signal in Measurement can't save as mat7.3 or that is detected incorrectly here:

        if options.matlab_compatible \
                and not (data.dtype.type in self.__MATLAB_classes \
                or (data.dtype.fields is not None \
                and options.structured_numpy_ndarray_as_struct)):
            if options.action_for_matlab_incompatible == 'error':
                raise lowlevel.TypeNotMatlabCompatibleError( \
                    'Data type ' + data.dtype.name
                    + ' not supported by MATLAB.')
            elif options.action_for_matlab_incompatible == 'discard':
                return

I hope these informations are helpful!

**Comment by danielhrisca** [comment]
do you get errors when you run this snippet?

```python
mdf = MDF(filename)
for i, df in enumerate(mdf.iter_groups()):
    m = MDF()
    m.append(df)
    m.export('mat', filename='group_{}.mat'.format(i), format='7.3')
```

**Comment by ZhuYuqicheng** [comment]
I have got these Traceback:

`runfile('C:/Users/ZYH7ABT/Desktop/asam_mat_1/eyb2_test.py', wdir='C:/Users/ZYH7ABT/Desktop/asam_mat_1')
Traceback (most recent call last):

  File "<ipython-input-1-048f3102ff67>", line 1, in <module>
    runfile('C:/Users/ZYH7ABT/Desktop/asam_mat_1/eyb2_test.py', wdir='C:/Users/ZYH7ABT/Desktop/asam_mat_1')

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ZYH7ABT/Desktop/asam_mat_1/eyb2_test.py", line 13, in <module>
    m.append(df)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2643, in append
    self._append_dataframe(signals, source_info, units=units)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3544, in _append_dataframe
    s_type, s_size = fmt_to_datatype_v4(sig.dtype, sig.shape)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\blocks\utils.py", line 612, in fmt_to_datatype_v4
    raise MdfException(message)

MdfException: Unknown type: dtype=object, shape=(2,)`

**Comment by danielhrisca** [comment]
@ZhuYuqicheng 

see #186 . The error needs to be addressed in https://github.com/frejanordsiek/hdf5storage

**Comment by myrthel** [comment]
I ran into this error as well, here would be a fix:
in .\asammdf\Lib\site-packages\hdf5storage\Marshallers.py
line 514  some c-api types were missing.  Numpy types can be found here [https://numpy.org/devdocs/user/basics.types.html](https://numpy.org/devdocs/user/basics.types.html):

Partial workaround:
```python
       self.__MATLAB_classes = {np.bool_: 'logical',
                                 np.uint8: 'uint8',
                                 np.ubyte: 'uint8', # added
                                 np.uint16: 'uint16',
                                 np.ushort: 'uint16', # added
                                 np.uint32: 'uint32',
                                 np.uintc: 'uint32', # added
                                 np.uint64: 'uint64',
                                 np.int8: 'int8',
                                 np.byte: 'int8', # added
                                 np.int16: 'int16',
                                 np.short: 'int16', # added
                                 np.int32: 'int32',
                                 np.intc: 'int32', # added
                                 np.int64: 'int64',
                                 np.float32: 'single',
                                 np.float64: 'double',
                                 np.complex64: 'single',
                                 np.complex128: 'double',
                                 np.bytes_: 'char',
                                 np.unicode_: 'char',
                                 np.object_: 'cell'}
```

**Comment by danielhrisca** [comment]
@frejanordsiek do you think this can integrated in the next release?
