### ISSUE TITLE
GUI Enhancement suggestion

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#123]
# Gui Enhancement suggestion

1. It would be nice, when multiple channels could have the same y-axis/ same scaling to compare signals "on the first view on it" --> also a y-grid could be shown with multiple signals

2. simple operations on signals as add, multiply,... would be nice.

Kind regards

**Comment by danielhrisca** [comment]
Thank you for the input @stlweb 

1. a. I had this in mind but it's not so trivial to implement (needs a way to define common Y axis). I will look into this when I get some time.
    b. I could not get the Y grid to show with multiple channels. This need further investigation.
2. you can use almost all operators with the Signal class. Have a look at the example https://asammdf.readthedocs.io/en/master/examples.html#working-with-signal

**Comment by danielhrisca** [comment]
@stlweb 
I've got the grid command to work; the fix is available in the Py3 branch

**Comment by danielhrisca** [comment]
>     2. simple operations on signals as add, multiply,... would be nice.
I think I misinterpreted this as a general lib issue when in fact you meant this to be available in the GUI. This would require a bit of work to pull off.

**Comment by danielhrisca** [comment]
@stlweb
First implementation of common axis is ready in Py3: there is a new checkbox for each channel
![screenshot from 2019-02-04 21-29-26](https://user-images.githubusercontent.com/20952040/52232037-1efb5680-28c4-11e9-8c76-03b77cb48136.png)

The next thing would be to set the axis label to show all the linked channels

**Comment by stlweb** [comment]
> 
> 
> > ```
> > 2. simple operations on signals as add, multiply,... would be nice.
> > ```
> 
> I think I misinterpreted this as a general lib issue when in fact you meant this to be available in the GUI. This would require a bit of work to pull off.

This is what  I meant, signal operations in the gui

**Comment by stlweb** [comment]
The axis labels are still dosplazed for multiple signals on a common axis. Looks fine, at the moment. I will test it furthermore with real measurement data.

@danielhrisca thanks for your great and fast work

**Comment by danielhrisca** [comment]
@stlweb 
It is now possible to add new channels by pressing "Insert" after plotting some channels. The computations can only be defined using the plotted channels.

**Comment by stlweb** [comment]
@danielhrisca 
What do you mean with "insert"?

After deselection of a channel from common axis the axis label needs to be renewed, at the moment the label has also after unchecking of the checkbox the same label as before (names of all previous selected channels). The Labels of common axis is updated after selection of a channel

**Comment by danielhrisca** [comment]
![image](https://user-images.githubusercontent.com/20952040/52482522-24a1b680-2bba-11e9-9195-a7d8a84b0988.png)
![image](https://user-images.githubusercontent.com/20952040/52482549-384d1d00-2bba-11e9-8ccf-b236539ea698.png)
![image](https://user-images.githubusercontent.com/20952040/52482563-4438df00-2bba-11e9-93ba-036204855e60.png)

I will check why the axis label remains the same when one of the channels is deselected

**Comment by danielhrisca** [comment]
@stlweb 
the axis label issue should be fixed with the latest commit

**Comment by stlweb** [comment]
@danielhrisca 
Thanks.
axis label fix works fine now, also computing with channels is nice

**Comment by stlweb** [comment]
New enhancement idea:
it could be usefull to allow multiple file selection (filenamesOpenDialog) for single files and open each file in a new tab

**Comment by danielhrisca** [comment]
> New enhancement idea:
> it could be usefull to allow multiple file selection (filenamesOpenDialog) for single files and open each file in a new tab

Please check the latest commit

**Comment by stlweb** [comment]
It's working fine.

**Comment by danielhrisca** [comment]
I'll close this issue. Looking forward for new enhancement ideas.
