### ISSUE TITLE
The description for the method _included_channels is incorrect 

### ISSUE THREAD

**Issue by sambit19** [danielhrisca/asammdf#125]
The description for the method _included_channels is incorrect. Needs to be changed.

 """ get the indexes list of channels that are excluded when processing
        teh channel group. The candidates for exclusion are the master channel
        (since it is retrieved as `Signal` timestamps), structure channel
        composition component channels (since they are retrieved as fields in
        the `Signal` samples recarray) and channel dependencies (mdf version 3)
        / channel array axes

**Comment by danielhrisca** [comment]
Hello Sambit,

I've changed the docstrings in development and Py3 branches.
Let me know if you find other inconsistencies.
