### ISSUE TITLE
No error message on Mac, programs quits silently 

### ISSUE THREAD

**Issue by sambit19** [danielhrisca/asammdf#126]
# Python version
_Please run the following snippet and write the output here_
```
('python=3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) \n'
 '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
'os=Darwin-18.2.0-x86_64-i386-64bit'
'numpy=1.15.4'
'asammdf=4.7.9'
```
# Code 

  ## MDF version
 4.10

  ## Code snippet
 ```
    mdf = MDF('/Users/sambit/Downloads/first.MF4',memory='minimum')
    print(mdf.version)
    mdf.export('mat','/Users/sambit/temp/first.mat',format='7.3')
```
  
  ## Traceback
no error messages
  
# Description

The program runs without errors. But the file is not exported. This works on a Linux machine. Wondering if this library also works on Mac.

**Comment by danielhrisca** [comment]
Hello Sambit,

I can't confirm Mac compatibilty since I have no such device to test.
What I can suggest is to start here https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L1434 and place some print statements to see if the execution goes ok.

What about saving the file after doing the conversion? Is the new fiel saved?

```python
mdf = MDF('/Users/sambit/Downloads/first.MF4',memory='minimum')
mdf.export('mat','/Users/sambit/temp/first.mat',format='7.3')
mdf.save('/Users/sambit/Downloads/first_testsave.MF4')
```

**Comment by sambit19** [comment]
"first_testsave.MF4" gets saved but "first.mat" does not. Possibly there is an uncaught exception inside export.

**Comment by danielhrisca** [comment]
I think the file is saved to another place; there is no way an exception would go silent.

**Comment by sambit19** [comment]
Looks like a permission issue with the directory. Just for testing I did a chmod -R 777 on '/Users/sambit/temp/first.mat'

The file is generated but with a text "Terminated: 15"

Does this mean the file is correctly generated? I think before the mat file is written, it should do a permission/sanity check of the directory.

**Comment by sambit19** [comment]
I could find out the issue.  I did not have the "hdf5storage" in my virtual env on this machine. That's why the export was not working.

**Comment by danielhrisca** [comment]
I'll check that

**Comment by danielhrisca** [comment]
Following #63 the logging was configured wrong. 

I've pushed fixes to Py3 and development branches.
