### ISSUE TITLE
asammdf GUI application exceptions

### ISSUE THREAD

**Issue by id872** [danielhrisca/asammdf#127]
# Python version
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
'os=Windows-7-6.1.7601-SP1'
'numpy=1.16.1'
'asammdf=4.7.10'
latest pyqtgraph dev package
# Code 

  ## MDF version
  3.20
  
# Description
Hi,
There are several problems with the GUI application: 4.7.9 and 4.7.10. 
asammdf-4.7.6 **is not affected**. I think it is good to show the screenshots with description:

- Here is the problem with loading some channels:
![err1_loading_channel](https://user-images.githubusercontent.com/45285868/52705661-c131d300-2f83-11e9-99d9-8b9b3454c0f8.png)

- After above fail I have the "old chart" displayed ("selected channels" section is empty) and when I set the cursor I have this exception:
![err4_on_set_cursor_2](https://user-images.githubusercontent.com/45285868/52705930-6ba9f600-2f84-11e9-91c2-b562527d02ba.png)

- There is also the exception on successfully added channel to the chart when I set the cursor:
![err3_cursor_on_move](https://user-images.githubusercontent.com/45285868/52706039-b297eb80-2f84-11e9-8547-9591b27cd30f.png)

- I noticed also this exception, but I don't remember the context, sorry:
![err2](https://user-images.githubusercontent.com/45285868/52706150-00acef00-2f85-11e9-9b98-5881ce001281.png)

It is quite a lot of issues, but I think it would be better to have it in one place.
If you need something more, please don't hesitate to ask.

**Comment by danielhrisca** [comment]
@id872 
please try the code from development

**Comment by id872** [comment]
Hi,

Thanks, your changes partially fixed the issues. But I did more tests and I have got another two problems:

- When I have got more than one channel on the chart I have got this exception when setting the cursor:
![err_setting_cursor](https://user-images.githubusercontent.com/45285868/52783224-8d24e380-3051-11e9-86f3-5a719ac33b75.png)
(with one channel on the chart there is no exception)

- When I want to plot enum typed channel I have this:
![err_enum_signals_plot](https://user-images.githubusercontent.com/45285868/52783328-dd03aa80-3051-11e9-9b55-886176d01138.png)

**Comment by danielhrisca** [comment]
I've made some changes in development. There hould be an exception is the result of a conversion is not a numpy ndarray. Please try the new code and print the channel for which the conversion misbehaves.

**Comment by id872** [comment]
Sorry for the late response.
Thanks, the cursor problem is fixed.
Unfortunately there is still a problem with the enum type channels:

![enum_channel](https://user-images.githubusercontent.com/45285868/52952452-e14b0300-3384-11e9-9f15-7dbb82f8b982.png)

When I downgrade asammdf to 4.7.6, the problem does not exist.

**Comment by danielhrisca** [comment]
@id872 
the new code in development should work better

**Comment by danielhrisca** [comment]
It would be nice if you could give the Py3 code a test drive as well to see if it behaves correctly as well.

**Comment by id872** [comment]
Hello Daniel,

You fixed the problem.
I also tested the Py3 branch and I can confirm that the issue does not exists there.
I have to tell that the Py3 branch GUI application works much faster!

Thanks you.

**Comment by danielhrisca** [comment]
Excelent!
