### ISSUE TITLE
Concatenate does not work on filtered MDFs

### ISSUE THREAD

**Issue by sambit19** [danielhrisca/asammdf#128]
# Python version
_Please run the following snippet and write the output here_
```
('python=3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) \n'
 '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
'os=Darwin-18.2.0-x86_64-i386-64bit'
'numpy=1.15.4'
'asammdf=4.7.9'
```
# Code 

  ## MDF version
 4.10

  ## Code snippet
 ```

def _merge_mdfs(mdf_obj_list):

    """ This method will take a list of MDF object and return a merged MDF object
    Note: The files must have the same internal structure (same number of groups, and same channels in each group)
     """
    return MDF.concatenate(mdf_obj_list)

  ### This method passes
def test_merge_mdf():
    from asammdf import MDF
    """ Test if the merging of MDF works and returned object is a MDF """
    mf4_1 = MDF('/Users/sambit/Downloads/first.MF4', memory='minimum')
    mf4_2 = MDF('/Users/sambit/Downloads/second.MF4', memory='minimum')
    mdfs_list = (mf4_1,mf4_2)
    mdf = _merge_mdfs(mdfs_list)
    assert isinstance(mdf, MDF)


### This method fails
def test_merge_mdf():
    from asammdf import MDF
    """ Test if the merging of MDF works and returned object is a MDF """
    mf4_1 = MDF('/Users/sambit/Downloads/first.MF4', memory='minimum')
    mf4_2 = MDF('/Users/sambit/Downloads/second.MF4', memory='minimum')
    filtered_1 = mf4_1.filter(channel_name_list)
    filtered_2 = mf4_2.filter(channel_name_list)
    mdfs_list = (filtered_1,filtered_2)
    mdf = _merge_mdfs(mdfs_list)
    assert isinstance(mdf, MDF)

```
  
  ## Traceback
File "mf4_parser/parse_mf4_spark.py", line 102, in <module>
    run_mf4_parsing(mf4_dir,schema_file)
  File "mf4_parser/parse_mf4_spark.py", line 93, in run_mf4_parsing
    return _export_mat(_merge_mdfs(mdf_list),mf4_dir)
  File "mf4_parser/parse_mf4_spark.py", line 38, in _merge_mdfs
    return MDF.concatenate(mdf_obj_list)    
  File "/Users/sambit/anaconda3/envs/mf4-parse/lib/python3.6/site-packages/asammdf/mdf.py", line 2131, in concatenate
    first_timestamp, last_timestamp, i, os.path.basename(mdf.name), original_first_timestamp
  File "/Users/sambit/anaconda3/envs/mf4-parse/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
  
# Description

In the log I see os.path.basename(mdf.name) but I think mdf has a field called mdf._name

Not sure if it is a python problem

**Comment by danielhrisca** [comment]
Hello Sambit,

please try the development branch code to see if it fixes the problem.

**Comment by sambit19** [comment]
I tried the development branch and this fixes the problem.
