### ISSUE TITLE
If two float32 represented by one uint64 - invalid result after shifting, masking and casting

### ISSUE THREAD

**Issue by chege54** [danielhrisca/asammdf#129]
# Python version

('python=3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 '
'64 bit (AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.15.4'
'asammdf=4.7.10'

# Code

  ## MDF version

  4.10

  ## Code snippet

approx line #4778..#4890 in mdf_v4.py

```

                                    else:

                                        vals = vals >> bit_offset

 

                                if bit_count != size << 3:

                                    if data_type in v4c.SIGNED_INT:

                                        vals = as_non_byte_sized_signed_int(vals, bit_count)

                                    else:

                                        mask = (1 << bit_count) - 1

                                        if vals.flags.writeable:

                                            vals &= mask

                                        else:

                                            vals = vals & mask

 

```
  ## Traceback

no traceback just wrong read in value

# Description

See attached screenshots. A hope my findings are valid :)
I have tasted my "fix" on a few measurements, but I am not 100% sure it is correct. Someone who has larger overview can check it?
![asammdf_4_7_10_bug](https://user-images.githubusercontent.com/5606998/53151637-01143e00-35b4-11e9-82d6-ca938524a727.png)
![asammdf_4_7_10_fix](https://user-images.githubusercontent.com/5606998/53151647-06718880-35b4-11e9-98fe-df8486f32d22.png)

**Comment by danielhrisca** [comment]
Hello @chege54 ,

does you file contains overlapping float32 and uint64 channels? Can you provide some screenshots with the GUI tool (double click on the channel name to bring up the pop-up window with the channel details) or with MDFValidator?

**Comment by chege54** [comment]
Hello @danielhrisca,

do you mean something like this?
![2019-02-21_10h20_15](https://user-images.githubusercontent.com/5606998/53157917-c9f95900-35c2-11e9-9248-0546438b57cd.png)

If I am trying to plot the signal with the unmodified version I am getting this error:
--------------------------------------------------------------------------------

<class 'UnboundLocalError'>

local variable 'samples' referenced before assignment

--------------------------------------------------------------------------------

  File "c:\users\noh2bp\appdata\local\continuum\anaconda3\envs\rsb_clone\lib\site-packages\asammdf\gui\widgets\file.py", line 1377, in plot_pyqtgraph

    self.plot = Plot(signals, self.with_dots, self.step_mode, self)

  File "c:\users\noh2bp\appdata\local\continuum\anaconda3\envs\rsb_clone\lib\site-packages\asammdf\gui\widgets\plot.py", line 172, in __init__

    if samples.dtype.kind not in 'SV':

With the modified version it is working

**Comment by danielhrisca** [comment]
@chege54 
please try the development branch code (it also contains a fix for the plot error)

**Comment by chege54** [comment]
@danielhrisca 
it looks like working!

Thank you!

**Comment by danielhrisca** [comment]
Hello @chege54 ,

would you mind checking the Py3 branch code as well?

**Comment by chege54** [comment]
Hi @danielhrisca 
I have checked it. That is working too!

**Comment by danielhrisca** [comment]
Thank you!
