### ISSUE TITLE
GUI Concatenate failes with error 

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#130]
# Python version
Python 3.7.1. 
  ## MDF version
  4.10 
  ## Traceback
  <class 'Exception'>
name 'groups_nr' is not defined
--------------------------------------------------------------------------------
  File "d:\software\wpy-3710_dev\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\main.py", line 361, in cs_clicked
    progress=progress,
  File "d:\software\wpy-3710_dev\python-3.7.1.amd64\lib\site-packages\asammdf\gui\utils.py", line 99, in run_thread_with_progress
    raise Exception(thr.error)
  
# Description
Concatcenate in GUI from Py3 Branch doesn't work anymore. with Master Version 4.7.9 it is working.

**Comment by danielhrisca** [comment]
Hello @stlweb ,

please use the development branch to get a better error message.

**Comment by danielhrisca** [comment]
@stlweb 
the latest code in Py3 fixes this issue

**Comment by stlweb** [comment]
@danielhrisca Works fine, thanks. From my point of view, the issue can be closed
