### ISSUE TITLE
GUI enhancement

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#131]
Hello @danielhrisca,
a kind of split view for multiple plot windows could be nice.
```
-----------------------------------------------------------
| Channels         |   plot area 1                        |
|                  |                                      |
|                  |---------------------------------------
|------------------| plot area 2                          |
|Selected channels |                                      |
|                  |---------------------------------------
|                  | plot area 3                          |
|                  |                                      |
-----------------------------------------------------------
```

**Comment by danielhrisca** [comment]
Hello @stlweb 
I can tell that this would be a big rework. I will have this in mind for the future, but it is not a priority right now.

**Comment by JulienGrv** [comment]
@danielhrisca I thought about that too. IMO, [pyqtgraph dockarea](https://github.com/pyqtgraph/pyqtgraph/blob/3d3d0a24590a59097b6906d34b7a43d54305368d/examples/dockarea.py) would be perfect for that.

**Comment by danielhrisca** [comment]
@JulienGrv nice to see you again

My main concern is wiring all the existing logic to support multiple plots

**Comment by danielhrisca** [comment]
I was thinking about implementing something that looks like this;

```
|-----------------------------------------------------------------------------|
| Channels < Selected channels 1        |   plot area 1                        |
|          <                            |                                      |
|          <----------------------------|--------------------------------------|
|          < Selected channels 2        |   plot area 2                        |
|          <                            |                                      |
|          <----------------------------|--------------------------------------|
|          < Selected channels 3        |   plot area 3                        |
|          <                            |                                      |
|----------<----------------------------|--------------------------------------|

< means a splitter 
```
Each time you click on the plot button a new plot will be added.

Another change that I'm considering is to use just a single Y-axis on the left side of the plot; the Y-axis would change when a channel is clicked in the selection list.
What do you think?

**Comment by stlweb** [comment]
@danielhrisca 
Your 1st idea sounds good. But in addition there is a delete/ reset button necessary.

I don't understand your 2nd idea. Isn't that the same behaviour as it is now (on the right side)?

**Comment by danielhrisca** [comment]
> Your 1st idea sounds good. But in addition there is a delete/ reset button necessary.

Yes of course, there will be at least a close button for each plot

> I don't understand your 2nd idea. Isn't that the same behaviour as it is now (on the right side)?

Now if you select multiple channel you will see their Y-axis on the right side. What I want to do is to have a single Y-axis on the left side; the Y-axis "parent" channel will be changed by selecting a single channel in the selection list

**Comment by JulienGrv** [comment]
Hi Daniel, IMHO for the class model:

- a dock area can have multiple docks
- a dock can have one sort of plot
- a plot can have multiple signals 
- a signal multiple associated docks

For the user interface, that translates in the possibility to display a signal on any plots with let's say a drag and drop and to add a new Dock with a menu for that (I would first just keep the current plot as the default one but you can think of supporting other types of plots in the future with this class model)

I hope I could help :)

**Comment by danielhrisca** [comment]
There is a basic implementation in the latest development branch. Let me know what should be improved/fixed

**Comment by stlweb** [comment]
Hello @danielhrisca,
The implementation of the new plotting areas is that what I had in my mind. 

In my opinion, the following functions could be necessary for high acceptance in multiplot mode of the gui:
-	the time axis shout be synchronous (channel information and stats also?)
-	option in the plot menu to de-/activate the multiplot behaviour
-	saving of plotted channels, may be in sections grouped as they are arranged in the plot windows?

**Comment by danielhrisca** [comment]
> * the time axis shout be synchronous (channel information and stats also?)

I've added a menu option to enable/disable X-axis link between subplots

> * option in the plot menu to de-/activate the multiplot behaviour

I've added a menu option to enable/disable subplots 

> * saving of plotted channels, may be grouped in sections as they are arranged in the plot windows?

The save will still be made using the signals from the currently active subplot (it will not contain the signal from all subplots)

**Comment by danielhrisca** [comment]
Ctrl+S will save the channels from the current active subplot

Ctrl+Shift+S will save all the channels from all the subplots

**Comment by danielhrisca** [comment]
The pyqtgraph dock area implementation was not a succes. I have encountered strange crashed without any error message. 

I've decided to use MDI windows instead. It's not as "sexy" but it is working correctly.

**Comment by danielhrisca** [comment]
I would call this implemented. Re-open if you have issues with it
