### ISSUE TITLE
mdf.export function creating blank rows in csvfile

### ISSUE THREAD

**Issue by msnir009** [danielhrisca/asammdf#132]
# Python version
3.7.1

## MDF version
3.20

  ## Code snippet
from asammdf import MDF
import numpy as np
import pandas as pd
import csv
import idlsave
from os import listdir
from os.path import isfile, join, splitext, split
import mdfreader

for fullfilename in onlyfilenames:
    file_name, file_extension = splitext(fullfilename)
    if file_extension == ".DAT":
        input_file = dat_folder + fullfilename  #points to directory where the file is stored
        yop = MDF(input_file)
        df = yop.export('csv', filename = csv_folder + file_name)
  
  ## Traceback
no error but output of undesirable format
  
# Description
while trying to convert a .DAT file into MDF format and then into CSV format, the CSV file results in having blank rows in between each record as shown in attached image. What can be done in the yop.export function to avoid creating these blank rows? thanks,

![test](https://user-images.githubusercontent.com/11345816/53649218-f73cab80-3c41-11e9-9908-60079d61fea6.PNG)

**Comment by danielhrisca** [comment]
Hello @msnir009 ,

what asammdf version do you have? 

```python
import asammdf
print(asammdf.__version__)
```

**Comment by msnir009** [comment]
Hi Daniel, I am using version 4.7.10

**Comment by danielhrisca** [comment]
Can you try 5.0.2? It's available on pypi

**Comment by msnir009** [comment]
i have updated the version to 5.0.2 but unfortunately it is still generating csv files with blank rows in between.

**Comment by danielhrisca** [comment]
@msnir009 

please check the development branch code for the fix

**Comment by msnir009** [comment]
i saw the changes made and noticed the addition of newline='' that should solve the issue so I installed the latest version of 5.0.3 and tried my code again but it was still producing the blank rows. should I manually change something in my code too? thanks.

**Comment by danielhrisca** [comment]
The fix is in the development branch code and will be part of the release 5.0.4

**Comment by msnir009** [comment]
thank you very much, i tested with the latest version and it worked! :)
