### ISSUE TITLE
Issue with sorting by bits for Channel block

### ISSUE THREAD

**Issue by Cropkoman** [danielhrisca/asammdf#134]
# Python version
'python=3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.14393-SP0'
'numpy=1.16.1'
'asammdf=5.0.0'
# Code 

  ## MDF version
 4.10
  
  ## Traceback
 ```
Error message:
  File "D:/kpi_tool_chain/MDF_Processing/mdf_raw_data_to_pickle.py", line 214, in <module>
    statistic, dictionary = (export_to_pickle(mdf))
  File "D:/kpi_tool_chain/MDF_Processing/mdf_raw_data_to_pickle.py", line 127, in export_to_pickle
    for j in range(ch_nr)
  File "D:/kpi_tool_chain/MDF_Processing/mdf_raw_data_to_pickle.py", line 127, in <listcomp>
    for j in range(ch_nr)
  File "D:\kpi_tool_chain\MDF_Processing\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3861, in get
    record_count=record_count,
  File "D:\kpi_tool_chain\MDF_Processing\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4446, in get
    (str_size,) = UINT32_uf(signal_data, offset)
struct.error: unpack_from requires a buffer of at least 4 bytes
 ```
# Description

For VLSD buses with bit offset different than 0, channels within single byte, are sorted in descending manner.
The traceback if from completely different place but i think that quick look on ```__lt__ ```method  for Channel class in v4_blocks.py will do the thing.

.../blocks/v4_blocks.py -> line 1107 -> greater than sign should be switched to less than in if statement.

**Comment by danielhrisca** [comment]
Hello @Cropkoman ,

do you have an actual error or are you just surprised by the sorting order?

**Comment by Cropkoman** [comment]
Hello @danielhrisca 
Yes there was an actual error..
I attached traceback from version 5.0.0 in description. 
I think that attached image talks for itself. 

The minimal information which i provided is after deeper investigation of traceback issue and what i suppose is root cause for it. 
The wrong order of sorted channels with bit offset different than 0 can be observed in blocks/mdf_v4.py -> _prepare_record for variable __sortedchannels__.

In picture not correct 'greater than' sign with red and correct with green
![image](https://user-images.githubusercontent.com/48198304/53721459-94c2f580-3e63-11e9-9029-227e617859b1.png)
.

**Comment by danielhrisca** [comment]
I can tell you that the comparison is correct as it is. Please install the development branch code and see if you still have the error

**Comment by danielhrisca** [comment]
Consider this case:

```
byte        0        1        2 ...
record      |--------|--------|--...
channel1         XXX             
channel2           XXXXX  
```

channel1 has a lower bit offset. 

However when the record is mapped to a numpy.recarray it is better to 
consider channel2 as parent: the first recarray field will be a uint16 value that can later be used to extract both channel1 and channel2 using bitwise operations. 

If channel1 would be considered as parent then the first recarray field would be a uint8 that will only allow the extraction of channel1. In this case channel2 would be extracted as non-byte-aligned channel and this is more expensive operation (basically creating a new recarray just for this channel)

**Comment by danielhrisca** [comment]
Regarding your error: is it possible to send a scrambled file for investigation purpose?

**Comment by danielhrisca** [comment]
@Cropkoman any progress on this?

**Comment by SzczepekJakub** [comment]
Hello @danielhrisca I'm @Cropkoman coworker.

We will back to you when we found some time to investigate again this issue on our side.

**Comment by danielhrisca** [comment]
@SzczepekJakub thank you for the update

**Comment by danielhrisca** [comment]
@SzczepekJakub 
any updates?

**Comment by SzczepekJakub** [comment]
We abandoned of extraction of this bus so for us not is a blocker. Paralel we do not have resources to investigate that deeper.
