### ISSUE TITLE
Efficient MDF file Open

### ISSUE THREAD

**Issue by cristi-neagu** [danielhrisca/asammdf#136]
Hello,

When i work with an MDF file, i am never interested in every single channel. Also, sometimes, the channels i am interested in are missing, in which case i would like to find alternatives for those missing channels. As such, what i usually do is open and MDF file loading only metadata, search for the channels i am after, noting any channels that are missing, figuring out any replacement that i need to do, compiling a final list of channels i need from the file, after which i reopen the file with only the channels i need (using a channel filter), resample, and retrieve the data.

I am having multiple issues doing this.
1.  I can't see any way of using a list of channels to only load those channels, reducing used memory.
2. I tried using the `filter` method to create a new file that only contains the labels i want, but it doesn't work if `memory='low'` or `memory='minimum'` is used. (Suggestion: when `filter` is called, check to see if the channel data exists and if it doesn't, load it from disk.)

The only way i can achieve what i want is by opening the file with `memory='minimum'` (i need to do this step so i can save time if i cannot find the channels i need or replacements for them, so i can simply discard the file), building the channel list, then reloading the file with `memory='full'`, using `filter` to generate a smaller file, then resampling. I feel there would be a considerable performance improvement if i could only load the channels i require. 

For reference, using mdfreader to run through that procedure gives me the data i need in 1.29s, while asammdf takes 12.4s

Sample code:

```
mdfFile = asammdf.MDF(fName, memory='low')

# i'm doing this next bit just to simulate a channel search
missingChannels = [channel for channel in channelList if channel not in mdfFile]
mdfFile.close() # doesn't seem to have an effect on performance

mdfFile = asammdf.MDF(fName, memory='full')
# memory has to be 'full' otherwise we can't filter

filterFile = mdfFile.filter(channelList)
filterFile.resample(0.1)

# have to close the files because, as clever as caching is, it messes up the test
mdfFile.close()
filterFile.close()
```

That takes 12.4s on my machine with a file of about 1GB.

```
mdfFile = mdfreader.Mdf(fName, no_data_loading=True)

# i'm doing this next bit just to simulate a channel search
missingChannels = [channel for channel in channelList if channel not in mdfFile]

mdfFile = mdfreader.Mdf(fName, channel_list=channelList)
mdfFile.resample(0.1)
```

That takes 1.29s with the exact same file.

Do note that due to confidentiality reasons, i cannot share any mdf files.

Tha mdf file i am using is about 1GB in size, contains over 2300 channels, and i am looking at retrieving less than 10 channels out of it.

Thank you.

**Comment by danielhrisca** [comment]
> I am having multiple issues doing this.
> 
> 1. I can't see any way of using a list of channels to only load those channels, reducing used memory.
> 2. I tried using the `filter` method to create a new file that only contains the labels i want, but it doesn't work if `memory='low'` or `memory='minimum'` is used. (Suggestion: when `filter` is called, check to see if the channel data exists and if it doesn't, load it from disk.)

Hello Cristi,

1. you can achieve this using _filter_ and _select_ methods in combination with _low_ or _minimum_ options
2, what exactly happens? I've used this with all memory options and I had no problem.

Since you are using asammdf 4.x.x I would suggest that you update to the latest release 5.0.4 (see [here](https://github.com/danielhrisca/asammdf/releases/tag/5.0.0) the major changes from 4.x.x to 5.x.x), or even better you could test drive the latest development branch code.

**Comment by danielhrisca** [comment]
@cristi-neagu 

I've just released 5.1.0. You should test this instead of 5.0.4 or the development branch

**Comment by cristi-neagu** [comment]
The error i get when trying to filter is this:
```
~\AppData\Local\Continuum\miniconda3\envs\work\lib\site-packages\asammdf\mdf.py in filter(self, channels, version)
   1693                         )
   1694                         if version < "4.00":
-> 1695                             encoding = encodings[k]
   1696                             samples = sig[0]
   1697                             if encoding:

IndexError: list index out of range
```

Note that this is in v5.1.0. And since the `memory` parameter doesn't seem to be used any longer, i can't filter a file any longer. If you have any specific tests you want me to run, let me know.

**Comment by danielhrisca** [comment]
Thank you Cristi! There was a small error in the filter method. Please try the new code in the development branch

**Comment by cristi-neagu** [comment]
Hello,

I can confirm the fix works. I can filter now, and that brings the time i need to get the data out of that file from 12s to under 1s. Great!

Thank you.

**Comment by danielhrisca** [comment]
If we are comparing, what was the exact timing with asammdf?

At 2300 channels your file is quite simple. You should try processing files with +1000000 channels :)

**Comment by cristi-neagu** [comment]
I re-ran the code i showed earlier for `mdfreader` and the result was 1.2s. Ran this code for `asammdf`:

```
mdfFile = asammdf.MDF('fName)
missingChannels = [channel for channel in channelList if channel not in mdfFile]
filterFile = mdfFile.filter(channelList).resample(0.1)
mdfFile.close()
filterFile.close()
```
Result was 574ms

**Comment by danielhrisca** [comment]
> One thing i'd like to add, off-topic a bit: conda doesn't want to upgrade to 5.1.0 naturally. It wants to install version 4.7 by default and will install 5.1.0 only if forced. Not sure why that is, i'm not that proficient with conda.

I have no idea
