### ISSUE TITLE
Loading Data is slow since asammdf 5.x.x

### ISSUE THREAD

**Issue by legout** [danielhrisca/asammdf#137]
Hi Daniel,

since I updated asammdf to 5.x.x (used 5.0.3, 5.0.4 and 5.1.0dev so far), loading data is dramatically slower than before!

My general procedure for loading data into a pandas dataframe is:
 - loading the file
 - fetching (_asammdf.get()_) the samples, unit, comment and conversion of all channels using group and index information from channels_db
 - interpolation to the same raster (0.1s)
 - creating a pandas dataframe for the samples, units, comment

For a mdf3 file with a size of 1,7Gb this needs 12 minutes to load! Doing the same with mdfreader only needs 45s.

With asammdf 4.7.11 this only needs 26s.  Obviously a huge difference.

I think this is due to the removed _memory_ option. As mentioned in asammdfs documentation, i can speed up data loading by using _configure_ and tune the _read_fragment_size_ parameter. Is there a way to have the same loading speed as with the old _memory='full'_ option?

Regards,
legout

**Comment by danielhrisca** [comment]
You should use select to efficiently extract multiple channels in one go

**Comment by legout** [comment]
Hi Daniel,

this results in a __MemoryError__ on my 16 Gb RAM laptop.

Another mdf4 file with a compressed size of 150 Mb also results in a __MemoryError__.

Therefore, is it possible to use the _get()_ with adjusted _read_fragment_size_ ? Are there any other possibilities?

Regards,
legout

**Comment by danielhrisca** [comment]
Are you using asammdf 5.1.0?

**Comment by legout** [comment]
Yes I do.

Unfortunately I am not allowed to share the mdf files. But here are some more information on the size of each time master and the number of channels. Maybe this helps.

| master | master size | number of channels |
| :------: | :----------: | :-------------------: |
| time | 30272 | 2 |
| time_1 | 30273 | 2 |
| time_2 | 30273 | 3 |
| time_3 | 30273 | 2 |
| time_4 | 30273 | 2 |
| time_5 | 30273 | 3 |
| time_6 | 30273 | 3 |
| time_7 | 30274 | 4 |
| time_8 | 30274 | 4 |
| time_9 | 30273 | 2 |
| time_10 | 30273 | 3 |
| time_11 | 30273 | 3 |
| time_12 | 30273 | 3 |
| time_13 | 30273 | 5 |
| time_19 | 30273 | 4 |
| time_20 | 30273 | 5 |
| time_21 | 30273 | 3 |
| time_22 | 30273 | 3 |
| time_23 | 30273 | 2 |
| time_24 | 30273 | 3 |
| time_25 | 30272 | 3 |
| time_26 | 30272 | 3 |
| time_27 | 30272 | 3 |
| time_28 | 30272 | 3 |
| time_29 | 30272 | 2 |
| time_30 | 30272 | 3 |
| time_31 | 30272 | 3 |
| time_32 | 30272 | 3 |
| time_33 | 30272 | 2 |
| time_34 | 3028 | 32 |
| time_35 | 30274 | 541 |
| time_36 | 302735 | 89 |
| time_37 | 3027247 | 199 |
| time_38 | 151367 | 1543 |
| time_39 | 453977 | 30 |
| time_40 | 302730 | 2 |
| time_41 | 30273 | 2 |
| time_43 | 2 | 2 |
| time_44 | 1 | 2 |
| time_46 | 3027296 | 2 |
| time_47 | 3027296 | 2 |

Regards,
legout

**Comment by danielhrisca** [comment]
Please run this snippet:

```python
from asammdf import MDF

mdf = MDF(filename)
for i, group in enumerate(mdf.groups):
    print('GP', i, group.data_blocks)
```

**Comment by legout** [comment]
Hi Daniel,

here is the output:

GP 0 [DataBlockInfo(address=0x28D2AB, block_type=0, raw_size=302720, size=302720, param=0)]
GP 1 [DataBlockInfo(address=0x2D712B, block_type=0, raw_size=302730, size=302730, param=0)]
GP 2 [DataBlockInfo(address=0x320FB5, block_type=0, raw_size=363276, size=363276, param=0)]
GP 3 [DataBlockInfo(address=0x379AC1, block_type=0, raw_size=302730, size=302730, param=0)]
GP 4 [DataBlockInfo(address=0x3C394B, block_type=0, raw_size=302730, size=302730, param=0)]
GP 5 [DataBlockInfo(address=0x40D7D5, block_type=0, raw_size=363276, size=363276, param=0)]
GP 6 [DataBlockInfo(address=0x4662E1, block_type=0, raw_size=363276, size=363276, param=0)]
GP 7 [DataBlockInfo(address=0x4BEDED, block_type=0, raw_size=423836, size=423836, param=0)]
GP 8 [DataBlockInfo(address=0x526589, block_type=0, raw_size=423836, size=423836, param=0)]
GP 9 [DataBlockInfo(address=0x58DD25, block_type=0, raw_size=302730, size=302730, param=0)]
GP 10 [DataBlockInfo(address=0x5D7BAF, block_type=0, raw_size=363276, size=363276, param=0)]
GP 11 [DataBlockInfo(address=0x6306BB, block_type=0, raw_size=363276, size=363276, param=0)]
GP 12 [DataBlockInfo(address=0x6891C7, block_type=0, raw_size=363276, size=363276, param=0)]
GP 13 [DataBlockInfo(address=0x6E1CD3, block_type=0, raw_size=484368, size=484368, param=0)]
GP 14 [DataBlockInfo(address=0x0, block_type=0, raw_size=0, size=0, param=0)]
GP 15 [DataBlockInfo(address=0x0, block_type=0, raw_size=0, size=0, param=0)]
GP 16 [DataBlockInfo(address=0x0, block_type=0, raw_size=0, size=0, param=0)]
GP 17 [DataBlockInfo(address=0x0, block_type=0, raw_size=0, size=0, param=0)]
GP 18 [DataBlockInfo(address=0x0, block_type=0, raw_size=0, size=0, param=0)]
GP 19 [DataBlockInfo(address=0x7580E3, block_type=0, raw_size=423822, size=423822, param=0)]
GP 20 [DataBlockInfo(address=0x7BF871, block_type=0, raw_size=484368, size=484368, param=0)]
GP 21 [DataBlockInfo(address=0x835C81, block_type=0, raw_size=363276, size=363276, param=0)]
GP 22 [DataBlockInfo(address=0x88E78D, block_type=0, raw_size=484368, size=484368, param=0)]
GP 23 [DataBlockInfo(address=0x904B9D, block_type=0, raw_size=363276, size=363276, param=0)]
GP 24 [DataBlockInfo(address=0x95D6A9, block_type=0, raw_size=484368, size=484368, param=0)]
GP 25 [DataBlockInfo(address=0x9D3AB9, block_type=0, raw_size=484352, size=484352, param=0)]
GP 26 [DataBlockInfo(address=0xA49EB9, block_type=0, raw_size=484352, size=484352, param=0)]
GP 27 [DataBlockInfo(address=0xAC02B9, block_type=0, raw_size=484352, size=484352, param=0)]
GP 28 [DataBlockInfo(address=0xB366B9, block_type=0, raw_size=484352, size=484352, param=0)]
GP 29 [DataBlockInfo(address=0xBACAB9, block_type=0, raw_size=363264, size=363264, param=0)]
GP 30 [DataBlockInfo(address=0xC055B9, block_type=0, raw_size=484352, size=484352, param=0)]
GP 31 [DataBlockInfo(address=0xC7B9B9, block_type=0, raw_size=484352, size=484352, param=0)]
GP 32 [DataBlockInfo(address=0xCF1DB9, block_type=0, raw_size=484352, size=484352, param=0)]
GP 33 [DataBlockInfo(address=0xD681B9, block_type=0, raw_size=363264, size=363264, param=0)]
GP 34 [DataBlockInfo(address=0xDC0CB9, block_type=0, raw_size=211960, size=211960, param=0)]
GP 35 [DataBlockInfo(address=0xDF48B1, block_type=0, raw_size=54947310, size=54947310, param=0)]
GP 36 [DataBlockInfo(address=0x425B69F, block_type=0, raw_size=65996230, size=65996230, param=0)]
GP 37 [DataBlockInfo(address=0x814BC65, block_type=0, raw_size=705348551, size=705348551, param=0)]
GP 38 [DataBlockInfo(address=0x321F802C, block_type=0, raw_size=438510199, size=438510199, param=0)]
GP 39 [DataBlockInfo(address=0x4C42A2A3, block_type=0, raw_size=29054528, size=29054528, param=0)]
GP 40 [DataBlockInfo(address=0x4DFDF8E3, block_type=0, raw_size=4843680, size=4843680, param=0)]
GP 41 [DataBlockInfo(address=0x4E47E183, block_type=0, raw_size=484368, size=484368, param=0)]
GP 42 [DataBlockInfo(address=0x0, block_type=0, raw_size=0, size=0, param=0)]
GP 43 [DataBlockInfo(address=0x4E4F4593, block_type=0, raw_size=1040, size=1040, param=0)]
GP 44 [DataBlockInfo(address=0x4E4F49A3, block_type=0, raw_size=520, size=520, param=0)]
GP 45 [DataBlockInfo(address=0x0, block_type=0, raw_size=0, size=0, param=0)]
GP 46 [DataBlockInfo(address=0x4E4F4BAB, block_type=0, raw_size=27245664, size=27245664, param=0)]
GP 47 [DataBlockInfo(address=0x4FEF080B, block_type=0, raw_size=27245664, size=27245664, param=0)]

**Comment by danielhrisca** [comment]
I guess this is the mdf v3 file?

**Comment by legout** [comment]
Yes.

I can post the output of the mdf v4 file. However, this would be much more.

**Comment by danielhrisca** [comment]
Please do it

**Comment by legout** [comment]
I can´t post it, as the comment is limited to 65535 characters.
Can I send you an email?

**Comment by danielhrisca** [comment]
I will have a look at the email. Thank you.

For the mdf v3 filr can you share the screenshots of MDFvalidator for the first data group and channel group?

**Comment by danielhrisca** [comment]
The following snippet requires that you update to the code in the development branch

```python
from asammdf import MDF

mdf = MDF(filename)

group = mdf.groups[0]

stream = mdf._file

stream.seek(group.data_group.address)
print(stream.read(group.data_group.block_len))

stream.seek(group.channel_group.address)
print(stream.read(group.channel_group.block_len))
```

**Comment by legout** [comment]
> 
> 
> I will have a look at the email. Thank you.
> 
> For the mdf v3 filr can you share the screenshots of MDFvalidator for the first data group and channel group?
Hi Daniel,

here is the screenshot of the first data group:

![grafik](https://user-images.githubusercontent.com/1469563/54019954-da95fb80-418c-11e9-8d71-166bbdd974fc.png)

and the screenshot of the first channel group:
![grafik](https://user-images.githubusercontent.com/1469563/54020032-14670200-418d-11e9-87e6-5dd74a6eac93.png)

**Comment by legout** [comment]
> ```python
> mdf = MDF(filename)
> 
> group = mdf.groups[0]
> 
> stream = mdf._file
> 
> stream.seek(group.data_group.address)
> print(stream.read(group.data_group.block_len))
> 
> stream.seek(group.channel_group.address)
> print(stream.read(group.channel_group.block_len))
> ```
This is the output for the mdf v4 file:

```python
stream.seek(group.data_group.address)
print(stream.read(group.data_group.block_len))
```
b'##DG\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\xf0\x03{\x00\x00\x00\x00\x00\xe0\x14m\x00\x00\x00\x00\x00\xf0%\xc2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

```python
stream.seek(group.channel_group.address)
print(stream.read(group.channel_group.block_len))
```
b"##CG\x00\x00\x00\x00h\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000\x13m\x00\x00\x00\x00\x00p'R\x00\x00\x00\x00\x00\xa8\x14m\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x90'R\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00]\xbf\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00"

And the output for the mdf v3 file:

```python
stream.seek(group.data_group.address)
print(stream.read(group.data_group.block_len))
```
b'MDF     3.30    TGT 15.0\x00\x00\x00\x00'

```python
stream.seek(group.channel_group.address)
print(stream.read(group.channel_group.block_len))
```
b'CG\x1e\x00\x00\x00\x00\x00\xc0\xc8(\x00\xc8B\x03\x00#\x00\x02\x00\n\x00@v\x00\x00\x00\x00\x00\x00'

**Comment by legout** [comment]
By the way, is it possible to get the "old" behavior like with _memory='full'_ using _configure()_?

**Comment by danielhrisca** [comment]
> By the way, is it possible to get the "old" behavior like with _memory='full'_ using _configure()_?

There is no _memory_ option now: the single implementation follows the previous "low" option. You can't use _configure_ to modify this.

**Comment by danielhrisca** [comment]
I've made some fixes last night in the development branch. I think the new code might work with your mdf v3 file. Can you check?

**Comment by danielhrisca** [comment]
> By the way, is it possible to get the "old" behavior like with _memory='full'_ using _configure()_?

I you use _select_ to extract the signals from the measurement then you will get better performance with 5.x.x than using 'full' option with 4.x.x (initial mdf load time + signal extraction time)

**Comment by legout** [comment]
> 
> 
> I've made some fixes last night in the development branch. I think the new code might work with your mdf v3 file. Can you check?

Hi Daniel,

I have updated to 5.1.1dev, but  still get a __MemoryError__.

**Comment by legout** [comment]
> 
> 
> > By the way, is it possible to get the "old" behavior like with _memory='full'_ using _configure()_?
> 
> I you use _select_ to extract the signals from the measurement then you will get better performance with 5.x.x than using 'full' option with 4.x.x (initial mdf load time + signal extraction time)

This is true for some other(smaller) files. However, I did not have memory issues before using asammdf 4.7.11

Regards,
legout

**Comment by danielhrisca** [comment]
Let's get the memory issue sorted out and you will see what I mean.

**Comment by legout** [comment]
> 
> 
> I've made some fixes last night in the development branch. I think the new code might work with your mdf v3 file. Can you check?

I am now able to load the mdf v4 file. Here is the comparison of mdfreader and asammdf

|              |    asamdf    |    mdfreader    |
|   :------:  |    :------:     |    :----------:   |
| time       |   2min54s    |    3min44s      |
| memory |12857.15MiB| 3759.85MiB |

Regards,
legout

**Comment by danielhrisca** [comment]
12GB for asammf?

**Comment by legout** [comment]
Yes.  The mdf v4 file is 150 MB using compression option in INCA.

**Comment by danielhrisca** [comment]
Please share your script as I can't understand how it could consume 12GB (are you sure you are using 5.1.1dev?)

**Comment by legout** [comment]
To give an update for potential other readers. Yes I do use 5.1.1dev. Script and files sent via email for further investigation.

**Comment by legout** [comment]
Using 5.1.1dev0 finally solves the issue.

Here are the timings and memory usage comparison with mdfreader (using compression=True).
The mdf v4 file has compressed 210MB. (Note: The same comparison some posts above was done with a smaller mdf v4 file (150MB).)

|                       |    asamdf       |    mdfreader    |
|   :------:         |    :------:        |    :----------:   |
| time               |   1min41s      |    3min44s      |
| peak memory | 2775.05 MiB | 8060.30 MiB    |
| increment memory     | 1849.37 MiB | 6410.59 MiB   |

The improvement in speed and especially memory usage is really impressive.
