### ISSUE TITLE
List index out of range error for mdf_v4.groups

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#139]
Hi Daniel,

I am currently investigating an issue where I have N groups in my MDF4 but when I get occurrence from channels_db for a given signal, its gp_idx > N (where N=len(groups)).

So far, I have checked with MDFValidator how many groups there is exactly. The groups list length in asammdf is equal to 3425 whereas MDFValidator has 3430 groups (from 1 to 3431). So it seems something went wrong here.

I will let you know as I have more information (this will probably take a few days since I have other parallel tasks).

Cheers, Julien

**Comment by danielhrisca** [comment]
Is this a CAN bus logging measurement?

**Comment by JulienGrv** [comment]
Could it be related to the reading of can logging that is bypassed? (I used latest development with my fix for can_msg)

**Comment by JulienGrv** [comment]
Ok I think we are narrowing the root cause here

**Comment by danielhrisca** [comment]
@JulienGrv 
I've made a fix attempt in the development branch

**Comment by JulienGrv** [comment]
Hi Daniel, I quickly tried before going in weekend and there is still an issue but a different one now. I will continue on next Tuesday and let you know

**Comment by danielhrisca** [comment]
Share the error tracebacks so we can both investigate the root cause

**Comment by JulienGrv** [comment]
Hi Daniel,

I didn't post the traceback because I wish to fix it myself.

So far: the reading seems to be working fine now (correct amount of groups, channels, and so on).
The problem that I have now is that the channels_db returns wrong gp_idx for my signals. To get them properly I have to do ```gp_idx - 2```. So it seems that there is a regular shifting of 2 here so I am looking at the reading phase now to see why the entries in channels_db, in particular the gp_idx, are erroneous.

**Comment by danielhrisca** [comment]
Some entry shifting happens [here](https://github.com/danielhrisca/asammdf/blob/development/asammdf/blocks/mdf_v4.py#L654)

**Comment by JulienGrv** [comment]
Thx Daniel, I think the root cause lies in the new_group_index calculation. Could you explain me a bit why you must remove the group with raw_can? In particular, I am not sure if I correctly understand lines [659 ](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L659) to 674

**Comment by danielhrisca** [comment]
The idea was the if we can extract all signals from the raw can messages, then we could remove the original group (to save space and prevent duplication in case of multiple save and load operations).

One quick solution would be to just add new groups with extracted signals and keep the original groups.
