### ISSUE TITLE
Export to parquet

### ISSUE THREAD

**Issue by Nimi42** [danielhrisca/asammdf#142]
asammdf = 5.1.1

Hey there,

when I'm trying to export an MDF file I get the following error.

```python
           ...site-packages\asammdf\mdf.py", line 1451, in export
    write_parquet(name, DataFrame.from_dict(mdict))
UnboundLocalError: local variable 'mdict' referenced before assignment
```

I took a look at the Code in question

```python
elif fmt in ("pandas", "parquet"):
    if fmt == "pandas":
        return df
    else:
        name = name.with_suffix(".parquet")
        write_parquet(name, DataFrame.from_dict(mdict))
```

When DataFrame.from_dict(mdict) is changed to df it works, but I guess it has the wrong columns?
Anyways, help would be appreciated. I Need that feature.

**Comment by danielhrisca** [comment]
hello @Nimi42 

I've pushed the fixed that you have suggested. Why do you say that the columns are wrong?

**Comment by Nimi42** [comment]
I don't. I just wasn't sure, if my suggested solution is correct. Thanks for the quick Reply.
