### ISSUE TITLE
adding metadata date and time information into dataframe

### ISSUE THREAD

**Issue by msnir009** [danielhrisca/asammdf#143]
# Python version
3.7.1

assamdf version
5.0.2

# Code 
file = '..../.DAT'
file = MDF(file, metadata = 1)
df = file.export('pandas')
![time2](https://user-images.githubusercontent.com/11345816/54351192-3eb63500-464f-11e9-8d10-0afbcaae3c46.PNG)

 
  ## Traceback
no error but output of undesirable format
  
# Description
The MDF file that I have contains data recorded in different timestamps but this is not the problem as when I convert the mdf file to pandas dataframe, it creates the complete dataframe which looks great but the timestamp information is in seconds and saved as a float. The date and time information is contained in the metadata so the idea is to display the timestamp in the dataframe to also include this time and date information from the metadata. Is it possible to do this? I tried using the other mdfreader library which is able to include this metadata but it is resulting in multiple dataframes that is contained in a dictionary and not actually being displayed as a dataframe itself. Hope you can help. Thanks.

**Comment by danielhrisca** [comment]
Try this

```python
from asammdf import MDF
import numpy as np
import pandas as pd

mdf = MDF(r'c:\Users\uidn3651\Downloads\ASAP2_Demo_V161_4.00.mf4')

df = mdf.to_dataframe()

time_with_meta = np.array(df.index) + mdf.header.start_time.timestamp()
time_with_meta = pd.to_datetime(time_with_meta, unit='s')

df.set_index(time_with_meta, inplace=True)
```

**Comment by msnir009** [comment]
thanks, this worked.

**Comment by danielhrisca** [comment]
@msnir009 
I've included this feature in the development branch code (see `time_as_date` argument of [MDF.to_dataframe](https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.to_dataframe) method)

**Comment by danielhrisca** [comment]
This should work now
```python
from asammdf import MDF

mdf = MDF(file_name)

df = mdf.to_dataframe(time_as_date=True)

```
