### ISSUE TITLE
False converting mdf v4 to mdf v3 

### ISSUE THREAD

**Issue by legout** [danielhrisca/asammdf#144]
Hi Daniel,

using asammdf 5.1.1, there is a bug in saving/converting mdf v4 to mdf v3. If I convert a mdf v4 file to mdf v3 and save it to disk, only the last data group is saved. Furthermore, I can´t reload this file using asammdf.

Regards,
legout

**Comment by danielhrisca** [comment]
@legout 
please check the latest development branch code

**Comment by legout** [comment]
Now my tests pass. 

Thanks!

**Comment by danielhrisca** [comment]
Super!
