### ISSUE TITLE
Error while opening MF4 files

### ISSUE THREAD

**Issue by ahmedahmedov** [danielhrisca/asammdf#145]
I get the following error when trying to open an MF4 file. MDF files work just fine though.

Code:  MDF(file_name)

asammdf - ERROR - Expected "##TX" or "##MD" block @0x286998 but found "b'##CC'"
NoneType: None
asammdf - ERROR - Expected "##TX" or "##MD" block @0x285e28 but found "b'##CC'"
NoneType: None

('python=3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:28:22) [MSC v.1916 '
 '32 bit (Intel)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.2'
'asammdf=5.1.0'

**Comment by danielhrisca** [comment]
Hello Ahmed,

if don't see an actual python error traceback it means that you have a file that contains partial conversions. In this case you can just ignore the warning message.

**Comment by ahmedahmedov** [comment]
Hi Daniel, 

Thanks. The only problem is that I get more than a hundred of these messages. Is there a way to silence them?

**Comment by danielhrisca** [comment]
Have a try with the latest development branch code

**Comment by danielhrisca** [comment]
@ahmedahmedov 

are you satisfied with the implementation?

**Comment by ahmedahmedov** [comment]
I still haven't checked it out. Once I do, I will report back.
