### ISSUE TITLE
Export to pandas behave different with 5.x.x

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#146]
python=3.6.4 |Anaconda, Inc.
os=Windows-10
numpy=1.14.0
asammdf=4.7.11

# Code 

  ## MDF version
asammdf=4.7.11

  ## Code snippet
mdf_data = MDF(file)
mdf_red = mdf_data.filter(self.__Labels['id'])
data_frame = mdf_red.export('pandas', 'time_from_zero')
  
# Description
I switched from 4.7.11 to 5.1.3 and recon that using the export function to pandas the output will different The pandas data frame will now also have the time vectors of all the groups included. time_0, time_1 etc. What I'm doing wrong? Your help is much appreciated.

_Please describe the issue here._

**Comment by danielhrisca** [comment]
Hello @Lama09,

you should start using the dedicated method [MDF.to_dataframe](https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.to_dataframe)

**Comment by danielhrisca** [comment]
I've fixed the issue for the export method as well. You can try with the latest development branch code

**Comment by danielhrisca** [comment]
Just a heads up: in release 5.2.0 the pandas export will be removed. This means you will have to use the method _to_dataframe_ instead

**Comment by Lama09** [comment]
Hello @Daniel
many thanks for your support and this asammdf package. As recommended from your side, I changed to Version 5.2.0. and tried to use the function to_dataframe(). Unfortunately a few issues are came up. This is what I tried.

<
mdf_data = MDF(file)
mdf_red = mdf_data.filter(['Label1','Label2','Label3']) 
mdf_red.to_dataframe()

             Label1  Label2  Label3
time                                                
0.000000              NaN             NaN        NaN
0.009723              NaN             NaN        NaN
0.019761              NaN             NaN        NaN>

Caling only with one Label:
<
mdf_red.to_dataframe(['Label1'])

             Label1  Label2  Label3
time                                                
0.000000              NaN             NaN        NaN
0.009723              NaN             NaN        NaN
0.019761              NaN             NaN        NaN
>

Calling without any filter, will take very long and run within the following error.

<
mdf_data = MDF(file)
temp=mdf_data.to_dataframe(['Label1'])
>

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\core\indexes\base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'AI50%3'

....

  File "C:\Anaconda\lib\site-packages\pandas\core\internals.py", line 3831, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "C:\Anaconda\lib\site-packages\pandas\core\internals.py", line 4853, in _consolidate
    _can_consolidate=_can_consolidate)
  File "C:\Anaconda\lib\site-packages\pandas\core\internals.py", line 4876, in _merge_blocks
    new_values = new_values[argsort]
MemoryError

**Comment by Lama09** [comment]
Switching back to Version  4.7.11 and using the old export() function, I recon that the time vector is not evenly spaced. Despite the fact, that the raw data got a constant step size. Your help is much appreciated.
<
data_frame = mdf_red.export('pandas', 'time_from_zero') 
>

**Comment by danielhrisca** [comment]
The ``channels`` argument was actually not used at all. Also when _time_from_zero_ was True all the columns were botched with NaN values.

Please check if the fix from the development branch solves your problem

**Comment by Lama09** [comment]
Hello Daniel,
I could isolate the measurement file and tried to open is within the GUI tool asammdf. The results don't look us expected. The file seems to be ruined up somehow. I also debuged the run with version 5.4.0 the variable t got the following output:

6.013470020310746e-154
0.0
1.7358671437257422e+185
1.0330476859814591e-47
6.958732448875159e-66
0.0
6.0278294356607975e+63
0.0
9.535505218978812e-307
0.0
7.280097341961574e+199
0.0
1.593962e-317
6.027829435660255e+63
3.152160495711615e+117
0.0
1.382378603256239e+228
0.0
1.1231247271724824e+219
4.473790103048594e-62
...

Unfortunately it will properly not that easy to provide you the measurement file that you can debug it on your own.

![asammdf](https://user-images.githubusercontent.com/48772414/55864501-ea827000-5b7c-11e9-88c2-7717e90a8baf.png)

**Comment by danielhrisca** [comment]
Can you confirm the corrupted time channel with some other tool (CANape, MDA)?

**Comment by Lama09** [comment]
Yes
TurboLab: is crashing while open this file
MDA V7.2.11: Is not displaying any label. See figure.
![MDA](https://user-images.githubusercontent.com/48772414/55868486-df334280-5b84-11e9-984e-a9eb9ec8782a.png)

**Comment by danielhrisca** [comment]
In thsi case we can close the issue again

**Comment by Lama09** [comment]
I do understand that it is an issue of the user to provide valid files. Unfortunately we try to do a automated postprocessing by hundreds of files which can't be checked by hand. Is there any way to check the validity by the use of the asammdf package? Or can we ask for an feature request?

**Comment by danielhrisca** [comment]
You could use this as a simple check, but it will have a performance cost 

```python
def is_validation(mdf):
    for i, group in enumerate(mdf.groups):
        t = mdf.get_master(i)
        if np.any(np.isnan(t)) or np.any(np.diff(t) < 0):
            return False
    return True
```

**Comment by Lama09** [comment]
Many thanks for your advice. Unfortunately the RuntimeWarning will still appear.
for i, group in enumerate(mdf_data.groups):
    t = mdf_data.get_master(i)
    if np.any(np.isnan(t)) or np.any(np.diff(t) < 0):
        print('false')
    else:
        print('true')
true
true
true
true
true
true
false
C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py:3031: RuntimeWarning:
invalid value encountered in multiply
false
false

**Comment by danielhrisca** [comment]
> false
> C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py:3031:

At this point you are supposed to discard the measurement from your batch job
