### ISSUE TITLE
Feature request: Average value in signal statistic

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#148]
Hello @danielhrisca ,
it could be very usefull to have an **average value** for selected signal in **statistics view** for the selected signal and selected range. 

Thanke you

**Comment by danielhrisca** [comment]
Hello @stlweb,

I've added average and RMS values to the statistics panel. Please try out the development branch code

**Comment by stlweb** [comment]
@danielhrisca 
It works fine.
Could you also implement the rectangles at the range coursors as it is at the normal courser?

**Comment by danielhrisca** [comment]
Done. Check the new development branch code
