### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by Nimi42** [danielhrisca/asammdf#149]
I was wondering:

Why is there a to_dataframe method and an Export method,
which can both create Pandas Dataframes? The Export method
seems to create files, except for the Pandas dataframe. 
Therefore I thought, Maybe it's duplicate Code. I'd like to contribute,
but this needs clarification I think.

**Comment by danielhrisca** [comment]
I will remove the export option for pandas. to_dataframe will be only way to get a pandas DataFrame

**Comment by Nimi42** [comment]
Thanks good to know. Just one more Question.

What do I have to do to contribute? I read Wiki, but I feel uncomfortable just commiting something.
(This is my first time contributing to a GitHub Project)

**Comment by danielhrisca** [comment]
This sums it up nicely https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by danielhrisca** [comment]
I've removed the "pandas" export option. 

The users should use the _to_dataframe_ method from now on
