### ISSUE TITLE
Cut mdf3 file string operation on non-string array

### ISSUE THREAD

**Issue by zorce** [danielhrisca/asammdf#15]
Hi,

Get an error when trying to do a mdf.cut(start=300)
Stacktrace below, string operation on non-string array

<myFilePath>
300 320
Traceback (most recent call last):
  File "whlk.py", line 26, in <module>
    short = mdf.cut(start=first)
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf.py", line 220, in
cut
    data=data
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf3.py", line 1913, i
n get
    vals = encode(vals, 'latin-1')
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\core\defchararray.py", l
ine 540, in encode
    _vec_string(a, object_, 'encode', _clean_args(encoding, errors)))
TypeError: string operation on non-string array

**Comment by danielhrisca** [comment]
Hello Denis,

can you do
``` python
print(vals)
```
just before line 1913 in _mdf3.py_?

**Comment by zorce** [comment]
['' '']
['Date: 31.10.2017    Time: 13:40:42\n\nStart event occurred']
[]
Traceback (most recent call last):
  File "whlk.py", line 26, in <module>
    short = mdf.cut(start=first)
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf.py", line 220, in
cut
    data=data
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf3.py", line 1914, i
n get
    vals = encode(vals, 'latin-1')
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\core\defchararray.py", l
ine 540, in encode
    _vec_string(a, object_, 'encode', _clean_args(encoding, errors)))
TypeError: string operation on non-string array

**Comment by zorce** [comment]
Python --version 3.6.3

**Comment by danielhrisca** [comment]
Ok so you had an a group with no samples.
Please put

```python
if cycles_nr:
```
 at line 1902, and identify up to line 2028.

**Comment by zorce** [comment]
It seems to work, thanks for fast response. Will continue test the library. 
Btw when I save the new file after cut it seem to be empty, do I have to specify the signals I want to store or can I store all?

Currently look for some condition in one signal. Find the first and last occurence and save to new log file.

Have to run with load_measured_data=False, due to big file (~500mb, 2397 channels)

mdf = MDF(path, load_measured_data=False)
newmdf = mdf.cut(start=first, stop=last

**Comment by danielhrisca** [comment]
The _cut_ method will return a new _MDF_ with all the channels cut according to the _start_, _stop_ and _whence_ arguments. This means that you don't have to specify channels. In your example 
``` python
mdf.cut(start=300)
```
the cut is done starting from timestamp=300s to the end of measurement. If you get an empty file then you should check if there are any samples beyond 300s.

You can chain _cut_ and _filter_ to get a subset of channels
```python
signals = ["s1", "s2", "s3]
new_mdf = mdf.filter(signals).cut(start=300)
```

Have a look at the _cut_ documentation here http://asammdf.readthedocs.io/en/stable/mdf.html. To cut, for example, from the start of the measurement and up to 5s relative to the start of measurement you can write
```python
mdf.cut(stop=5, whence=1)
```

On 32bit Python your only bet is to use _load_measured_data=False_

**Comment by zorce** [comment]
Have tested that, after the save of the cut file the mdf file gets corrupted. Have alot of errors and warnings in all data groups. 
![image](https://user-images.githubusercontent.com/9129856/32315037-c45a0b8c-bfaa-11e7-8219-4832c360e9d8.png)

**Comment by danielhrisca** [comment]
Hello Dennis,

I think I solved the issue. Please try the latest commit from development https://github.com/danielhrisca/asammdf/commit/7129409036bd31cb8c0d5b24446ca941e9b9b7f9

**Comment by zorce** [comment]
Hi,

Yes that solved it! One additional comment ^^ When I have both start and stop condition with cut I get the following stacktrace. If I only have the start condition it works, and also only with stop it works.
Detected between 310.142321087126 and 310.2516405264248
Traceback (most recent call last):
  File "whlk.py", line 85, in <module>
    short = mdf.cut(start=first, stop=last)
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf-2.6.7-py3.6.egg\asammd
f\mdf.py", line 221, in cut
  File "C:\Users\dennis.delin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf-2.6.7-py3.6.egg\asammd
f\signal.py", line 301, in cut
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by danielhrisca** [comment]
Can you try the latest development commit?

**Comment by zorce** [comment]
Yes this was with latest.. git pull --rebase and python setup.py install
commit f8e059bd925d5e92acb599345ebd6d1850a31739
Author: danielhrisca <daniel.hrisca@gmail.com>
Date:   Thu Nov 2 14:48:37 2017 +0200

    release 2.6.7

**Comment by danielhrisca** [comment]
I meant this commit https://github.com/danielhrisca/asammdf/commit/2dff83f4699ebefc8e5ec716b761d8ea4ad28f4a

**Comment by zorce** [comment]
How could I list that commit? when git pull I can see it in the git log. But when git checkout 2dff83f I get it.
The commit works! Thanks alot!

**Comment by zorce** [comment]
Found it .. remote branch ^^

**Comment by danielhrisca** [comment]
Thank you for your support. I did a big code refactoring and those bugs were inserted into the previously work code.

If all is working now I guess you could close this issue.

**Comment by zorce** [comment]
Yes you can close it! Thank you!

**Comment by danielhrisca** [comment]
Fixed.
