### ISSUE TITLE
Empty Signal is not empty?

### ISSUE THREAD

**Issue by Nimi42** [danielhrisca/asammdf#151]
I have an mdf file with an empty channel, which does not Show any data in MDA (measurment data analyzer)

When I convert it to a dataframe it will print

```python
     $EVENT_COMMENTS
time                
0.0           b'nan'
```

even with the skip Option. I can not attach the file here, but if necessary I will send it to you.

Thanks for the good work.
Keep it up

**Comment by danielhrisca** [comment]
@Nimi42 
please check the development branch. The last fix might also help in your case
