### ISSUE TITLE
Importing dat and exporting to mf4 - large file size increase

### ISSUE THREAD

**Issue by choo2388** [danielhrisca/asammdf#153]
# Python version
`('python=3.6.7 |Anaconda 4.4.0 (64-bit)| (default, Oct 28 2018, 19:44:12) [MSC '
 'v.1915 64 bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.16.2'
'asammdf=5.1.1'
```
# Code 
  
# Description

Importing a smaller dat file as MDF and reexporting to mf4 format results in large file size increase

_Please describe the issue here._
# Hi, I am importing a dat file (13MB) through asammdf and converting the file to dataframe format.  This allows me to time align my file. Once I complete the process, I am exporting the file as MDF.save(dst), however the file size now is nearly (70MB).  There was no change to the data except the time column was altered to align with another file.

What could be the reason for this?  I tried compression=2, although the mf4 file is smaller, the moment I convert it back to dat (using ETAS), I am back at 70 MB.

Thank you.

**Comment by danielhrisca** [comment]
Hello @choo2388 ,

you probably have a file with overlapping channels or bit packed channels (not standard 8, 16, 32 or 64 bit integers). 

For example a channels that is used as a flag (single bit, 0 or 1) will be stored as an 8bit channel in the new file. This is how the library works and I don't see a chance to change this behavior as it will complicated thing a lot.

**Comment by choo2388** [comment]
Ok great, Thanks Daniel. One last question. I have calculated my "shift" delta time.  However, when I update the column in pandas and try to export as mdf.save(dst), I am getting all NaNs. This problem only occurs if I touch the time column. What is the best recommended way to update the time column? Thank you.

**Comment by danielhrisca** [comment]
You need to be a bit more specific and maybe share some code snippet. I can't see extacly what you are doing. Mdf -> pandas -> Mdf ?

**Comment by choo2388** [comment]
Ok, here is a sample code.
[pandas_time_column_issue_sample.zip](https://github.com/danielhrisca/asammdf/files/3036092/pandas_time_column_issue_sample.zip)

*************************
# First I import the dat file, turn into a dataframe and change time to a column from index:
*************************

test_file = MDF('2019-04-02_test_for_daniel.dat')

## Convert the mdf file to dataframe
test_df = test_file.to_dataframe()

print('Original shapes of the dataframes:')
print(test_df.shape)

## Turn the time into a column from index
test_df = test_df.reset_index(level=0)
test_df

*************************
# Next I increment the time col by 0.5 and reexport as a new MDF file
*************************
test_df['time'] = test_df['time'] + 0.5
test_df = test_df.set_index('time')

cols_datfile = test_df.select_dtypes(include=['floating','integer']).columns
units_datfile = dict.fromkeys(cols_datfile, 'zzz')

new_testfile_datfile = MDF()
new_testfile_datfile.append(test_df, units=units_datfile)
new_testfile_datfile.save(path + outfolder + dt.date.today().strftime('%Y-%m-%d')+ '_test_export_for_daniel_modified'+ '.mdf')

*************************
## Now when I read it back in, I see only NaNs
*************************
test_file_modified = MDF('2019-04-02_test_export_for_daniel_modified.mf4')

## Convert the mdf file to dataframe
test_df_modified = test_file_modified.to_dataframe()

print('Original shapes of the dataframes:')
print(test_df_modified.shape)

## Turn the time into a column from index
test_df_modified = test_df_modified.reset_index(level=0)
test_df_modified

**Comment by danielhrisca** [comment]
I think the NaN problem is fixed if you update to asammdf 5.3.1

I guess your final goal is to stack multiple files into a single synchronized file. Have you tried to use the [_stack_ method](https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.stack)? This should automatically sync the files based on the measurement start time stamp (if the recording software has set properly)

**Comment by danielhrisca** [comment]
Was there supoosed to be an error in the mf4 file from the archive? It looks ok
![image](https://user-images.githubusercontent.com/20952040/55456131-ea1f2d80-55ee-11e9-82d1-cf970c79bab5.png)
![image](https://user-images.githubusercontent.com/20952040/55456135-ed1a1e00-55ee-11e9-9086-67f6167a3405.png)

**Comment by choo2388** [comment]
hey - thats so funny. I see NaNs when I import. Thanks for your patience. 

Try running the following code and let me know what you see

`test_file_modified = MDF('2019-04-02_test_export_for_daniel_modified.mf4')`

### Convert the mdf file to dataframe
```
test_df_modified = test_file_modified.to_dataframe()
print('Original shapes of the dataframes:')
print(test_df_modified.shape)
```

### Turn the time into a column from index
```
test_df_modified = test_df_modified.reset_index(level=0)
test_df_modified
```

> time | sample_col_1
> -- | --
> 0.000000 | NaN
> 0.322185 | NaN
> 0.326125 | NaN
> 0.327625 | NaN
> 0.328625 | NaN

**Comment by danielhrisca** [comment]
Something is fishy:

```python
test_file_modified = MDF(r'2019-04-02_test_export_for_daniel_modified.mf4')

test_df_modified = test_file_modified.to_dataframe()
print('Original shapes of the dataframes:')
print(test_df_modified.shape)
print(test_df_modified)
test_df_modified = test_df_modified.reset_index(level=0)
print(test_df_modified)
```

Output with asammdf 5.4.0

```
Original shapes of the dataframes:
(5, 1)
          sample_col_1
time                  
0.000000     -1.212330
0.322185     -1.212330
0.326125     -1.050236
0.327625     -0.780750
0.328625     -0.612320
       time  sample_col_1
0  0.000000     -1.212330
1  0.322185     -1.212330
2  0.326125     -1.050236
3  0.327625     -0.780750
4  0.328625     -0.612320
```

**Comment by choo2388** [comment]
2 updates for you.

1. upgrading to 5.4.0 fixes the nan issue.
2. I am also able to get the output like you show.

Only question remains, why doesnt the time column update?

FYI - if I open the file using MDA (measurement data analyser), the time column seems to be fine.

Something is truly fishy..:)

**Comment by danielhrisca** [comment]
> Only question remains, why doesnt the time column update?
> 
> FYI - if I open the file using MDA (measurement data analyser), the time column seems to be fine.

I don't get it. What doesn't update?

**Comment by choo2388** [comment]
Actual output

> time | sample_col_1
> -- | --
> 0.000000 | -1.212330
> 0.322185 | -1.212330
> 0.326125 | -1.050236
> 0.327625 | -0.780750
> 0.328625 | -0.612320

Expected output (time = time + 0.5)

>           sample_col_1
> time                  
> 0.500000     -1.212330
> 0.822185     -1.212330
> 0.826125     -1.050236
> 0.827625     -0.780750
> 0.828625     -0.612320



the time column doesn't update when you import back into python. Its not an issue, but if I wanted to verify the output using by importing into python, it doesnt seem to recognize the change.

**Comment by choo2388** [comment]
Hey daniel, 

I think I found the problem.  When exporting the dataframe with the "first value of time" not equal to 0, this causes a problem.  You have to manually add time=0.

Thanks.

**Comment by danielhrisca** [comment]
Pay attention to the _time_from_zero_ argument which defaults to _True_ https://asammdf.readthedocs.io/en/master/api.html#asammdf.mdf.MDF.to_dataframe

**Comment by danielhrisca** [comment]
```python
test_file_modified = MDF(r'2019-04-02_test_export_for_daniel_modified.mf4')

test_df_modified = test_file_modified.to_dataframe()
print('Original shapes of the dataframes:')
print(test_df_modified)

test_df_modified.set_index(test_df_modified.index + 0.5, inplace=True)

mdf = MDF()

mdf.append(test_df_modified)

mdf.save(r'2019-04-02_test_export_for_daniel_modified_+0.5.mf4')

mdf = MDF(r'2019-04-02_test_export_for_daniel_modified_+0.5.mf4')
print(mdf.to_dataframe())
print(mdf.to_dataframe(time_from_zero=False))
```

```
Original shapes of the dataframes:
          sample_col_1
time                  
0.000000     -1.212330
0.322185     -1.212330
0.326125     -1.050236
0.327625     -0.780750
0.328625     -0.612320

          sample_col_1
time                  
0.000000     -1.212330
0.322185     -1.212330
0.326125     -1.050236
0.327625     -0.780750
0.328625     -0.612320
          sample_col_1
time                  
0.500000     -1.212330
0.822185     -1.212330
0.826125     -1.050236
0.827625     -0.780750
0.828625     -0.612320

```
