### ISSUE TITLE
To dataframe returns with exception

### ISSUE THREAD

**Issue by Nimi42** [danielhrisca/asammdf#154]
I get the following exception, when using to_dataframe with one of my data files.

```python
2019-04-02 14:07:53,168 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "/home/nemo/IdeaProjects/Hadoop/test.py", line 44, in <module>
    df = blub.to_dataframe(raster=0.1)
  File "/home/nemo/miniconda/envs/hadoop/lib/python3.6/site-packages/asammdf/mdf.py", line 3340, in to_dataframe
    for name, series in components(sig.samples, sig.name, used_names, master):
  File "/home/nemo/miniconda/envs/hadoop/lib/python3.6/site-packages/asammdf/blocks/utils.py", line 1064, in components
    if prefix:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I took a look at the Code at Question and I think that `master` has to be changed to `master=master`, because no prefix Argument is provided.

```python
# arrays and structures
elif sig.samples.dtype.names:
    for name, series in components(sig.samples, sig.name, used_names, master):
        df[name] = series
```

**Comment by Nimi42** [comment]
I can probably fix that myself.

**Comment by danielhrisca** [comment]
It's probably already fixes in the development branch code

**Comment by Nimi42** [comment]
@danielhrisca 

I edited the comment above. Is that fixed as well?

**Comment by danielhrisca** [comment]
run these commands to get the latest development branch code and check if you still have errors:

``
pip install natsort
pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip
``

**Comment by Nimi42** [comment]
The development Version does indeed work without Problems. I noticed though, that asammdf includes the device Name for .dat files, but not for .mf4. Does that have specific reason? I'd rather have it consistent to be honest or optional, because I don't need the device name.

**Comment by danielhrisca** [comment]
In the .dat files your channels probably have the device name embedded in the channel name. For .mf4 you could probably get the same names if you create the MDF object with ``MDF(filename, use_display_names=True)``, in which case the display name will be searched for in the channel XML comment

**Comment by Nimi42** [comment]
@danielhrisca 

not sure about that. When I look at the Signal names the device is always included for mf4 as well.
It would be nice if could remove the device for .dat as well.

**Comment by coppolajj** [comment]
I tend use both .dat and .mf4 formats when collecting data as well so I run the following after converting to pandas:
```python
# for a given panadas dataframe "df"
lstHdr = list(df)
for ii in range(len(lstHdr)):
    lstHdr[ii], b, c = lstHdr[ii].partition('\\')
df.columns = lstHdr
```
...if the device is there it will be removed and do nothing if it's not.

**Comment by Nimi42** [comment]
Nice...

So devices will always be added with \\. 
Thanks for the code. I’ll make good use of it.

**Comment by coppolajj** [comment]
> So devices will always be added with `\\`.

In my experience the device is separated with a single backslash.  You need two here because of the "escaping" nature of a single backslash in python.

**Comment by danielhrisca** [comment]
I've added a new keyward argument to the MDF class to remove the source from the channel names

```python
mdf = MDF(filename, remove_source_from_channel_names=True)
```
