### ISSUE TITLE
Opening read-only mdf

### ISSUE THREAD

**Issue by tistelac** [danielhrisca/asammdf#156]
('python=3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.2'
'asammdf=5.1.1'
5.1.1
3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]

  ## MDF version
 mdf version
3.10
  ## Code snippet
mdf = MDF(MyMdfFileName, 'low')

  
  ## Traceback
  File "C:\Data\Hyper Digitalization\PyCharmVE\lib\site-packages\asammdf\blocks\mdf_v3.py", line 184, in __init__
    self._file = open(self.name, "r+b") 
PermissionError: [Errno 13] Permission denied: 'x:\\MyFile.mdf'
  
# Description

x: drive is read only. It seems to try and open the file in mode "read + write binary" 
When I change line 184 in mdf_v3.py from "...r+b" to "...rb" it fixes the issue, not sure if it is "r+b for a reason though

**Comment by danielhrisca** [comment]
This is fixed in the latest release https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/mdf_v4.py#L235

**Comment by Lama09** [comment]
I crashed at the same line today (asammdf (5.4.0)) and was wondering if it will be possible to include the open() function in to some exception handling?

**Comment by danielhrisca** [comment]
@Lama09 
https://github.com/danielhrisca/asammdf/releases
