### ISSUE TITLE
extract_can_logging(dbc) only returns scaling of the 1st data group

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#157]
I have a CAN bus log file from a logging device with 2 physical CAN channels. 

In both channels, the same J1939 CAN data frame is recorded, split by data group. This case may occur if e.g a single device is recording data from two identical machines in parallel.

I would like to dbc-convert the raw data, but my understanding of using extract_can_logging(dbc) on the overall MDF is that it will "collapse" the original data group separation into a single data group to reflect that the two physical CAN channels are recording the same CAN ID. I would need this separated as the data would in practice not be identical.

To do so, I assumed I would be able to split the original MDF into two MDFs, one for each data group - and then afterwards apply extract_can_logging. However, that seems to provide an empty MDF with no matches. I also notice that the structure of the resulting mdf1 and mdf2 files are slightly different vs. their counterpart data groups in the concatenated MDF. 

Perhaps I'm simply doing the splitting of data groups wrongly - if so, I'll close this asap.

My code: (data: [sample_files.zip](https://github.com/danielhrisca/asammdf/files/3049504/sample_files.zip))

```
from asammdf import MDF

files = ['AC6013CD_00003277_00000001.mf4', 'AC6013CD_00003277_00000005.mf4']
dbc = ['CSS-Electronics-SAE-J1939-DEMO.dbc']

mdf = MDF.concatenate(files,time_from_zero=False)

# split MDF into CAN channel 1 and 2
mdf1 = MDF(version='4.10')
mdf2 = MDF(version='4.10')

mdf1.append([mdf.get("CAN_DataFrame", group=0)])
mdf2.append([mdf.get("CAN_DataFrame", group=1)])

mdf1.save(dest+'CAN_1', overwrite=True)
mdf2.save(dest+'CAN_2', overwrite=True)

mdf1_scaled = mdf1.extract_can_logging(dbc)
mdf2_scaled = mdf2.extract_can_logging(dbc)

mdf1_scaled.save('mdf1_scaled.mf4')
mdf2_scaled.save('mdf2_scaled.mf4')

```
**Expected behavior**
I would expect above code to produce two MDFs, one per data group. Converting each of these two MDFs with the dbc would then yield the scaled signal separately for mdf1 and mdf2.

**Actual behavior**
The resulting mdf1 and mdf2 seem to be structured slightly differently than the data groups in the concatenated MDF (when viewing via MDFValidator). The scaling thus yields an empty MDF for both mdf1 and mdf2.

Sorry if this is just a rookie mistake on extracting the data groups into new MDFs - I was not able to find a simple solution for this scenario beyond the above.

Martin

**Comment by danielhrisca** [comment]
Hello Martin,

have a try with the latest development branch code. 

![image](https://user-images.githubusercontent.com/20952040/55667886-f1eb0600-586a-11e9-81fc-503bcf64123c.png)
![image](https://user-images.githubusercontent.com/20952040/55667890-08915d00-586b-11e9-9e11-c53fdebd97bc.png)
![image](https://user-images.githubusercontent.com/20952040/55667897-0fb86b00-586b-11e9-92c7-1771c026e78d.png)
![image](https://user-images.githubusercontent.com/20952040/55667900-1cd55a00-586b-11e9-9251-5a48dc95eae2.png)

**Comment by MatinF** [comment]
Hi Daniel, I believe I'm able to replicate this result now - which is awesome!

One observation is that it works when I directly scale one of my original log files.

However, if I concatenate the two files in my zip and then afterwards scale the concatenated file, the scaled MDF seems to still only contain data for the 1st data group - even if the structure of my concatenated file looks similar to the original file pre-scaling.

I guess the concatenation function somehow changes something in the file, resulting in this behavior?

**Comment by MatinF** [comment]
Quick update on this Daniel:

I tried using the latest development code and the below script with sample file 'AC6013CD_00003277_00000001.mf4':

```
from asammdf import MDF
 
mdf = MDF.concatenate(r"AC6013CD_00003277_00000001.mf4")
mdf_scaled = mdf.extract_can_logging(r"CSS-Electronics-SAE-J1939-DEMO.dbc")
```
This yields an error as below:

```
Traceback (most recent call last):
  File "C:\Users\marti\Documents\api-examples\examples\mdf\asammdf_basics.py", line 44, in <module>
    mdf_scaled = mdf.extract_can_logging(dbc)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\mdf.py", line 3542, in extract_can_logging
    sig = self.get_can_signal(f'{can_id}.{message.name}.{name}', db=dbc)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 5051, in get_can_signal
    ignore_invalidation_bits=ignore_invalidation_bits,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3751, in get
    name, group, index, source=source
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1886, in _validate_channel_selection
    raise MdfException(message)
asammdf.blocks.utils.MdfException: Channel "CAN_DataFrame.ID" not found in group 2
```

Interestingly, everything seems to work as expected if I do not use the concatenate function on the single file, but rather just load this directly as an MDF.

Best,
Martin

**Comment by MatinF** [comment]
Quick update: From what I can see, the latest commits enable me to save both channels as a scaled MDF as expected. I'm stilling getting the error message, though - not sure why it occurs as the concatenated MDF only has a Group 0 and a Group 1.

**Comment by danielhrisca** [comment]
Hello Martin,

please try the latest development branch code

**Comment by MatinF** [comment]
Hi Daniel, as mentioned in our chat, I seem to be getting the right result when loading/concatenating a single file - but not when concatenating multiple files as per the sample zip I sent. Let me know if I should clarify further or provide more detailed replication examples on this.

**Comment by MatinF** [comment]
Hi Daniel, I believe this is working as well now.

One thing I did notice when working with the sample file "7F34B296_00000008_00000001.mf4":

When I try to run the below code, I get an error:

```
mdf = MDF.concatenate(r"7F34B296_00000008_00000001.mf4")
mdf_filter = mdf.filter(["CAN_DataFrame.BusChannel", "CAN_DataFrame.ID", "CAN_DataFrame.DataBytes"])
```

The error is below. What I don't understand is that when I e.g. export the above MDF as a CSV, the timestamp and buschannel columns seem to be identical in length (146578 rows) - so I'm not sure where the 131072 comes from. Any ideas?

```
asammdf - ERROR - CAN_DataFrame.BusChannel samples and timestamps length mismatch (146578 vs 131072)
NoneType: None
Log file(s):  ['input\\7F34B296_00000008_00000001.mf4'] 
DBC(s):  ['input\\CSS-Electronics-SAE-J1939-2018-08_v1.3.dbc']
MDF ============================================================================
name: new.mf4
version: 4.10
read fragment size: 0
write fragment size: 4194304

GROUP ==========================================================================
sorted: True
data location: 1
Traceback (most recent call last):
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4710, in get
    encoding=encoding,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\signal.py", line 99, in __init__
    raise MdfException(message)
asammdf.blocks.utils.MdfException: CAN_DataFrame.BusChannel samples and timestamps length mismatch (146578 vs 131072)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marti\Documents\api-examples\examples\mdf\asammdf_basics.py", line 37, in <module>
    mdf_filter = mdf.filter(["CAN_DataFrame.BusChannel", "CAN_DataFrame.ID", "CAN_DataFrame.DataBytes"])
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\mdf.py", line 1651, in filter
    copy_master=False,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4713, in get
    debug_channel(self, grp, channel, dependency_list)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\utils.py", line 620, in debug_channel
    print("data size:", group["data_size"], file=file)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\utils.py", line 1008, in __getitem__
    return self.__getattribute__(item)
AttributeError: 'Group' object has no attribute 'data_size'
```

**Comment by MatinF** [comment]
I believe I found the issue as per my separate message, it was related to something else. This works as intended now - thanks!
