### ISSUE TITLE
how can i resample mdf using master_channel instead of raster

### ISSUE THREAD

**Issue by az299260** [danielhrisca/asammdf#158]
## Python version
'python=3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.15.4'
'asammdf=5.4.1'
# Code 

  ## MDF version
3.10

  ## Code snippet
def resample(self, raster, version=None):
   
# Description
As per the code to resample i need to provide raster as float. is there any way i can give a signal name(master_signal) so that i get all the signals samples with reference to master_signal in asam library

I have seen such type of format in mdfreader.py ,
  def resample(self, sampling_time=None, master_channel=None):

**Comment by danielhrisca** [comment]
Hello @az299260 ,

this is currently not possible directly from the API. I will think about this

**Comment by az299260** [comment]
will it be possible for me to integrate the resample part of mdfreader into asammdf and save it?

**Comment by danielhrisca** [comment]
The implementations are very different. I don't think it's possible

**Comment by az299260** [comment]
is there any other way, to change the input argument, may be i'm missing some logic

**Comment by danielhrisca** [comment]
@az299260 

I've implemented this in the development branch.

Now the raster argument can be:

* a float value used as step (this was the implementation until now)
* an array that will be used as raster
* a channel name who's timestamps will be used as raster

So you can use something like

```python
from asammdf import MDF

mdf = MDF(filename)

# raster of 0.5s
resampled = mdf.resample(raster=0.5)

# raster as array
resampled = mdf.resample(raster=[1,2,3,4,5])

# raster as channel's timestamps
ressampled = mdf.resample(raster='EngineSpeed')
```

**Comment by az299260** [comment]
i tried using the new sampling method, but i got following error

`ressampled = myobj.resample(raster='XXXXXXXXX')
Traceback (most recent call last):

  File "<ipython-input-11-b47d02472686>", line 1, in <module>
    ressampled = myobj.resample(raster='XXXXXXXXX')

  File "C:\Users\*********\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 2472, in resample
    num = float(np.float32((master[-1] - master[0]) / raster))

TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

**Comment by danielhrisca** [comment]
Please print master just before the line that triggers the error

**Comment by az299260** [comment]
I have done storing master in a variable. please find my code below

`myobj = MDF(filename)

signal1 = yop.get('aaaaa').samples #88981 values
signal2 = yop.get('bbbbb').samples #88322 values
signal3 = yop.get('ccccc').samples #master signal - 883190 values

#tried with below two methods
resampledmyobj = myobj.resample(raster='signal3')

resampledmyobj = myobj.resample(raster='ccccc')`

**Comment by danielhrisca** [comment]
This should work

```python
myobj = MDF(filename)

signal3 = yop.get('ccccc').timestamps

#tried with below two methods
resampledmyobj = myobj.resample(raster=signal3)

resampledmyobj = myobj.resample(raster='ccccc')
```

**Comment by az299260** [comment]
still got an error

resampledmyobj = myobj.resample(raster=signal3)
##  if raster:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by az299260** [comment]
still got an error

resampledmyobj = myobj.resample(raster=signal3)

 if raster :
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by danielhrisca** [comment]
@az299260 

1. it is better if you share the complete error traceback so I can see exactly were the error occurs.
2. did you properly udpate to the latest development branch code ?  ``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by az299260** [comment]
sorry my bad, i didn't update the dev code properly. 
i have the pip command, but now i'm getting error while creating the mdf object

```
Traceback (most recent call last):

  File "<ipython-input-46-e8a2673733f2>", line 1, in <module>
    runfile('C:/Users/*****/.spyder-py3/dummy.py', wdir='C:/Users/*****/.spyder-py3')

  File "C:\Users\*****\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\*****\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/*****/.spyder-py3/dummy.py", line 13, in <module>
    yop = MDF(filename)

  File "C:\Users\*****\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 113, in __init__
    self._mdf = MDF3(name, **kwargs)

  File "C:\Users\*****\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 179, in __init__
    self._read(mapped=True)

  File "C:\Users\*****\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 690, in _read
    self.identification = FileIdentificationBlock(stream=stream)

  File "C:\Users\*****\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\v2_v3_blocks.py", line 2390, in __init__
    self.address = 0

TypeError: descriptor 'address' for 'FileIdentificationBlock' objects doesn't apply to 'FileIdentificationBlock' object
```

**Comment by danielhrisca** [comment]
This might have to do with the Ipython kernel. Close the console and run the script again to start with a fresh console

**Comment by az299260** [comment]
error at line 2447
```
ressampled = myobj.resample(raster='signal3')
Traceback (most recent call last):

  File "<ipython-input-3-ffb2b36f3787>", line 1, in <module>
    ressampled = myobj.resample(raster='signal3')

  File "C:\Users\******\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 2447, in resample
    assert raster > 0

TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by danielhrisca** [comment]
I've fixed the error, so you should update again

Note that if you provide as string (``raster='signal3'``) it must be a channel name from the MDF file not a variable name

**Comment by az299260** [comment]
yeah now it works. thanks a lot for the help daniel

**Comment by danielhrisca** [comment]
re-open if you still have related errors
