### ISSUE TITLE
Iter channels gets really slow.

### ISSUE THREAD

**Issue by Nimi42** [danielhrisca/asammdf#159]
I have an .mf4 file for which the Iteration through the channels gets really slow. I enumerated and printed the number for each Iteration and it seems that at some point the Iteration gets slower for some reason. If you want to I can scramble and send that file to you.

cheers

**Comment by danielhrisca** [comment]
Hello @Nimi42 

please try new development branch code.

```python
mdf = MDF(filename)

for ch in mdf.iter_channels():
    ...

# faster but make sure not to modify timestamps inplace
for ch in mdf.iter_channels(copy_master=False):
    ...
```

**Comment by Nimi42** [comment]
I did and it is faster, but it seems there is some Kind of memory leak. I'm going OOM now.

**Comment by danielhrisca** [comment]
> I did and it is faster, but it seems there is some kind of memory leak. I'm going OOM now.

Do you call the function with _copy_master=False_?

**Comment by Nimi42** [comment]
Yes, with the new asammdf Version I'm going out of memory. No matter false or true. I can't tell for sure though, if it's the fault of asammdf, Pandas or pyarrow. But somewhere Memory is leaking.

**Comment by danielhrisca** [comment]
Please send a scrambled file

**Comment by Nimi42** [comment]
I guess it's not a leak after all, but for some reason it needs more memory. It's a huge file though. Should I send it to your E-Mail?

**Comment by danielhrisca** [comment]
Yes thank you.

The new implementation requires more RAM as it gets all channel from a channel group using select. In the previous implementation a simple get was used: this is memory efficient but very slow (for each channel the complete group raw samples are read again)

**Comment by Nimi42** [comment]
@danielhrisca 

Can't have it all I guess. Thanks for the info.

**Comment by Nimi42** [comment]
Would there be an efficient way to iterate through the column names or is it the same es getting the signals.

**Comment by danielhrisca** [comment]
MDF uses row oriented storage, so accessing a channel needs to read all rows. 

What could help if you first filter only the needed channels 

```python
mdf = MDF(filename).filter(channel_list)

for ch in mdf.iter_channels():
    ...
```

**Comment by Nimi42** [comment]
I Need to iterate through the whole mdf in chunks. What I did is build a generator, that iterates through the channels and Returns the first n column names and then the next n names. 
Then I filter the mdf and convert it to a dataframe and afterwards parquet. It's still the same thing from the converting large files. 

So I can't prefilter the mdf. But there must be a way to iterate through the columns.

**Comment by danielhrisca** [comment]
[ASAP2_Demo_V161_4.00.mf4.zip](https://github.com/danielhrisca/asammdf/files/3054004/ASAP2_Demo_V161_4.00.mf4.zip)
 take this file for example

The second group has 12 channels (time included). In the previous implementation to iterate over the 11 channels the raw data had to be read 11 times: this is slow but it is done using chunked reading so it is memory efficient

![image](https://user-images.githubusercontent.com/20952040/55720822-627c5900-5a0a-11e9-9f19-5f643d927316.png)


With the new implementation the speed is increased because all 11 channels are returned in one call, but the memory required is higher because you have all 11 returned signal objects in the memory at the same time (this the source of your OOM). The raw data read  only 1 time and is done using chunked reading.

I your case I would not use the _iter_channels_ but instead use _select_ with channels from the same group. You can then tune the size of the channel list used by _select_ if you still have OOM

```python
gp_index = 1
ch_index = None
channels = [(ch.name, gp_index, ch_index) for ch in mdf.groups[1].channels]

try:
    # get all channels from the second group
    signals = mdf.select(channels)
except MemoryError:
    chunk_size = N
    idx = 0
    while True:
        subset = channels[idx * chunk_size: (idx+1) * chunksize]
        if subset:
            signals = mdf.sleect(subset)
        else:
            break
```

**Comment by Nimi42** [comment]
Something like this would be no good? The Problem select defines its own to_dataframe method and I'm getting used to the one that is working.

mdf
```python
def iter_column_names(self, skip_master=True, copy_master=True):
        """ generator that yields a *Signal* for each non-master channel

        Parameters
        ----------
        skip_master : bool
            do not yield master channels; default *True*
        copy_master : bool
            copy master for each yielded channel

        """
        for i, group in enumerate(self.groups):

            included_channels = self._included_channels(i, skip_master=skip_master)

            channels = [
                (i, idx)
                for idx in included_channels
            ]

            return [self._get_column_name(i[0], i[1]) for i in channels]
```

mdf_v4
```python
def _get_column_name(self, group, index):
        gp_nr, ch_nr = self._validate_channel_selection(None, group, index)
        grp = self.groups[gp_nr]
        if ch_nr >= 0:
            channel = grp.channels[ch_nr]
        else:
            channel = grp.logging_channels[-ch_nr - 1]

        return channel.name

```

**Comment by danielhrisca** [comment]
> Something like this would be no good? The problem is select defines its own to_dataframe method and I'm getting used to the one in mdf that is working.

_select_ is just an efficient way to extract multiple channels at once (instead of calling _get_ for each of them) and it has nothing to to with _to_dataframe_

The mdf standard does not use the _column_ notion so I would avoid using it.

**Comment by Nimi42** [comment]
hm... mdfreader provided a similiar functionality. Call it iter_channel_name if you will. It's just a sparse format of iter_channels

**Comment by danielhrisca** [comment]
Assuming you have no repeating channel names you can do this

```python
for group in mdf.groups:
    names = [ch.name for ch in group.channels]
```
 If you have repeating names then you need to precisely specify the channels

**Comment by danielhrisca** [comment]
I think it's a good idea for you to send your processing script so I can see exactly what you want to do. My feeling is that you want to bend the lib to work in a way that is not designed to

**Comment by Nimi42** [comment]
Well... I do have requirement now that I need to check the channel names against some metadata. I found a method called get_channel_name in the mdf_v3 as well. So I'm not sure why you are being so protective about it. All it would take is adding get_channel_name to mdf_v4 and an iter_channel_names method in mdf.

I need the channel names in a performant way. There is no way around it.

**Comment by danielhrisca** [comment]
There is already a [get_channel_name](https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/mdf_v4.py#L5758) method in the MDF4 class

Just to summarize as I think I'm not being well understood:
1. _get_ is not performant; for best performance with multiple channels you have to use _select_
2. _iter_channel_ (in its new implementation) uses _select_ for fetch all channel group channels and then yields them. This is better performant then _get_ but uses higher memory (especially for channel groups with many channels). This why I advised to use _select_ with subsets of channel group's channels
3. the fastest way to get the channel names is with the snippet that I've previously shared
```python
for group in mdf.groups:
    names = [ch.name for ch in group.channels]
```

**Comment by Nimi42** [comment]
Oh... please excuse me. I was getting ahead of myself. I’ll use mdf.groups then.

**Comment by Nimi42** [comment]
Oh... please excuse me. I was getting ahead of myself. I’ll use mdf.groups then.

**Comment by danielhrisca** [comment]
Is there any point in keeping this issue opened?

**Comment by Nimi42** [comment]
Can be closed.
