### ISSUE TITLE
Select returns NaN dataframe

### ISSUE THREAD

**Issue by cristi-neagu** [danielhrisca/asammdf#160]
Hello,

Using `MDF.select` with `dataframe=True` returns a dataframe filled with NaN.

Using asammdf v5.4.1, with a MDF3 file, Python 3.7.

**Comment by danielhrisca** [comment]
It should be fixed in the development branch

**Comment by cristi-neagu** [comment]
Can confirm the issue is resolved in the development branch. Thank you.
