### ISSUE TITLE
GUI: Support auto-conversion of "buslogging" MDF by loading DBC 

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#162]
Hi Daniel,

With the recent great improvements to the extract_can_logging API function, one thought from my side was whether this could be implemented into the GUI - to enable a broader appeal of this functionality. 

I believe the recent introduction of the bus logging format in the MDF standard will entail an increasing number of use cases where a DBC file will be applied ex post rather than being pre-attached. Further, many users will want to apply a "full" DBC, not necessarily knowing what signals are included in a specific data set in advance.

A simple way to enable this could be below:

**Proposed Implementation**
1) A user loads a raw buslogging MDF file in the GUI via File/Open MDF
_This loads the buslogging file just as in the current implementation (showing the CAN_DataFrame channels)._ 

2) The user then loads a DBC file via File/Open DBC
_Doing so immediately converts the loaded MDF file using the extract_can_logging function. For larger files, a small loading bar might be added. When done, the GUI displays the scaled MDF, which can then be used in plots, saved etc. I.e. exactly as it works today if the user loads a scaled MDF file. For memory challenges on larger files, the scaled MDF could be temporarily stored somewhere during usage._ 

**Advantages**
A) Users will be able to utilize the GUI end-2-end: From logging raw data, scaling it, plotting it etc. - without needing API or coding experiences
B) By utilizing the extract_can_logging function, the implementation may be relatively simple - compared to e.g. having to specify what signals to convert
C) To our knowledge, this would make asammdf the only open source GUI tool that enables DBC conversion of buslogging MDF files

Anyway, just wanted to add this feature suggestion - we've already had some beta testers that thought this would be a great feature. However, also fully realize that this may be a more extensive thing to add. 

Let me know your thoughts,
Martin

**Comment by danielhrisca** [comment]
Hello Martin,

have a try with the development branch code. There is a new tab in the GUI for this purpose

![image](https://user-images.githubusercontent.com/20952040/56155499-ba473100-5fc3-11e9-88a2-dbf7209bf9cd.png)

**Comment by MatinF** [comment]
That's amazing Daniel, incredibly speed you're working at :-) 

I think it works really great. A few minor observations:

**1)** The flow could perhaps be tweaked slightly: 
1.1 I open asammdf
1.2 I then open an MDF file (raw bus logging)
1.3 Next, I go to the DBC tab and load the DBC file
1.4 Finally, I click Extract CAN signals

In the last step, I'd intuitively expect that my currently loaded file from 1.1 would be the one to be converted - but instead the GUI asks to load a new file. My response to this is to load the same file again, which produces a warning as that file is already loaded.

It's in no way critical, but just a consideration in regards to the flow - happy to hear your thoughts on this. 

**2)** When I load the sample file 7F34B296_00000008_00000001.mf4 with the full J1939 DBC, I get the below warning multiple times in the command prompt:

`asammdf - WARNING - Expected AT, CG, SD, DL, DZ or CN block at 0xb88 but found id="b''"`

Other times where I try to convert the same file, I am unable to do so as it seems to get stuck and the "Extract CAN Logging" pop up modal goes into "Not Responding" mode. In comparison, the API takes ~15 seconds to convert that file using the same DBC. I'm not sure what causes this.

**3)** The tool currently overwrites the file that is loaded with the DBC converted version. I think it would be ideal to create a copy next to the loaded file with a _scaled version as many users will want to keep both types of files. However, this can be worked around by doing a copy prior to loading it.

Really awesome work, this is going to be a really awesome addition to the GUI!

Thanks for all your hard work,
Martin

**Comment by danielhrisca** [comment]
> **2)** When I load the sample file 7F34B296_00000008_00000001.mf4 with the full J1939 DBC, I get the below warning multiple times in the command prompt:
> 
> `asammdf - WARNING - Expected AT, CG, SD, DL, DZ or CN block at 0xb88 but found id="b''"`

It looks like you have a channel who's signal data link points to an invalid address.

**Comment by danielhrisca** [comment]
> In the last step, I'd intuitively expect that my currently loaded file from 1.1 would be the one to be converted - but instead the GUI asks to load a new file. My response to this is to load the same file again, which produces a warning as that file is already loaded.

![image](https://user-images.githubusercontent.com/20952040/56184964-b1d31280-6024-11e9-8dbd-dd2f916c108d.png)
 This dialog is used to select the output file. The input file is always the file opened at step 1.1

**Comment by danielhrisca** [comment]
> **3)** The tool currently overwrites the file that is loaded with the DBC converted version. I think it would be ideal to create a copy next to the loaded file with a _scaled version as many users will want to keep both types of files. However, this can be worked around by doing a copy prior to loading it.

I could do this to avoid further confusion but I'm not sure if "scaled" is the proper term here.

Regarding the errors during extraction maybe you can share the file for debugging.

**Comment by MatinF** [comment]
Hi again Daniel, thanks for the explanation:

1) I've attached the sample file I used - the DBC file I used is the full DBC that I believe you have (else let me know). If there's an issue with an invalid signal, is this something that is wrong in the original sample file - or something that goes wrong during the conversion (i.e. potentially related to the DBC)?

[7F34B296_00000008_00000001.zip](https://github.com/danielhrisca/asammdf/files/3084237/7F34B296_00000008_00000001.zip)

Also, it seems I do not consistently get that error message - at least in the latest version of the development branch that I tried today. However, it seems the conversion time is 10x+ of what the time is when using the API - not sure what might be causing this, but perhaps you can test on your end to see if you experience the same when using the above sample file and the full DBC.

2) That makes sense to me now, thanks for clarifying - I think that answers point 3) as well, since the overwriting issue was due to me selecting the same file due to a misunderstanding.


I think overall, the GUI works really well at this stage if the speed can be similar to when using the API - I'm happy to do any further tests in this regard if I can try in helping to identify what might be causing the GUI to have challenges with the sample file I attached above and the full DBC. It seems it might be struggling due to that file having more signals than the other sample files I've shared in the past - but it's just strange when the API seems to be able to handle it fairly fast.

Thanks again,
Martin

**Comment by danielhrisca** [comment]
Hello Martin,

I can't seem to replicate your problems. On my PC extracting with the lib or with the GUI takes roughly the same: 4.75s vs 5.00s. The progress dialog does not work that well for now

**Comment by MatinF** [comment]
Hi again Daniel, thanks for following up on this.

I tested again now with the following steps:
1) I upgraded to the latest canmatrix and asammdf development codes
2) I open asammdf.exe and load the sample log file, "7F34B296_00000008_00000001.mf4" and the dbc "CSS-Electronics-SAE-J1939-2018-08_v1.3.dbc", then create a new output file
3) When doing so, the GUI stalls and takes a very long time to complete the scaling (10+ minutes)

I'm not sure if I'm using an inadequate version of some dependency or similar. I'm on Windows 10, Python 3.7. 

When running it this time, I get below error message:

`C:\Users\marti\Documents\api-examples\examples\mdf\input\7F34B296_00000008_00000001.mf4 {'CAN1': {486537216: 0, 418377733: 0, 201326598: 0, 82771974: 0, 418316294: 0, 418377735: 0, 419428357: 0, 419428377: 0, 418377762: 0, 419325986: 0, 417990651: 0, 485230587: 0, 217991217: 0, 419315762: 0, 419428401: 0, 419315767: 0, 419428407: 0, 419362887: 0, 419428423: 0, 419428428: 0, 419428491: 0, 218101900: 0, 419428492: 0, 419315861: 0, 419428501: 0, 419428550: 0, 218101973: 0, 419428603: 0, 417988859: 0, 418050299: 0, 485290235: 0, 419326208: 0, 419358976: 0, 419367171: 0, 418382086: 0, 419367175: 0, 217977122: 0, 419367203: 0, 419367202: 0, 419367206: 0, 484847910: 0, 418382120: 0, 419367223: 0, 217989431: 0, 217991495: 0, 419361095: 0, 419367239: 0, 419367307: 0, 419367308: 0, 419367317: 0, 418002939: 0, 485242875: 0, 419367353: 0, 419367408: 0, 419356416: 0, 418030075: 0, 418036219: 0, 485270011: 0, 485276155: 0, 419351040: 0, 419361280: 0, 419428864: 0, 419428867: 0, 217063941: 0, 217975301: 0, 218102277: 0, 218102278: 0, 419428869: 0, 419428871: 0, 419428883: 0, 419428889: 0, 217977378: 0, 419428898: 0, 419428900: 0, 419428899: 0, 485246971: 0, 419428913: 0, 419428914: 0, 419428919: 0, 419428935: 0, 419429003: 0, 419429062: 0, 217979605: 0, 418325205: 0, 419429077: 0, 218102512: 0, 419429104: 0, 485228288: 0, 485293824: 0, 417997563: 0, 418030331: 0, 485237499: 0, 485270267: 0, 418390784: 0, 419279616: 0, 419265280: 0, 485227267: 0, 217056000: 0, 419429125: 0, 419429126: 0, 419427079: 0, 217989895: 0, 418316035: 0, 419430147: 0, 485227271: 0, 485292803: 0, 485292807: 0, 418381573: 0, 419430149: 0, 418381574: 0, 419430150: 0, 418381575: 0, 419430151: 0, 217977634: 0, 485227298: 0, 485227299: 0, 485292834: 0, 484870950: 0, 484844326: 0, 417921830: 0, 419427112: 0, 485227302: 0, 485292835: 0, 485292838: 0, 419429169: 0, 419388210: 0, 486538034: 0, 218051383: 0, 218102583: 0, 485227319: 0, 485292855: 0, 486538039: 0, 419427143: 0, 485227335: 0, 485292871: 0, 485227403: 0, 485227404: 0, 485292939: 0, 485292940: 0, 485227413: 0, 485292949: 0, 418118561: 0, 418118562: 0, 418184097: 0, 418184098: 0, 418118565: 0, 418184101: 0, 418316066: 0, 418381603: 0, 419430180: 0, 419362609: 0, 418381606: 0, 419430182: 0, 484900646: 0, 485227449: 0, 485292985: 0, 218102726: 0, 419429360: 0, 485227504: 0, 485293040: 0, 418381618: 0, 419235622: 0, 417989627: 0, 418024443: 0, 417997819: 0, 485229563: 0, 485237755: 0, 217056256: 0, 419265536: 0, 485264379: 0, 217977890: 0, 217990180: 0, 418335782: 0, 419286054: 0, 484840486: 0, 484844582: 0, 218051639: 0, 218000455: 0, 419363911: 0, 217959569: 0, 419286256: 0, 419388656: 0, 418024699: 0, 485264635: 0, 419357952: 0, 419362048: 0, 419216640: 0, 419347712: 0, 419353856: 0, 419274009: 0, 418370850: 0, 217978146: 0, 217990435: 0, 419335473: 0, 419378482: 0, 419274033: 0, 419335479: 0, 419378487: 0, 419274123: 0, 419286417: 0, 419335573: 0, 419378581: 0, 419317523: 0, 419317542: 0, 484853542: 0, 418027003: 0, 418031099: 0, 485266939: 0, 485271035: 0, 418317824: 0, 419321344: 0, 419360256: 0, 218103299: 0, 419362304: 0, 218103301: 0, 218103302: 0, 419429893: 0, 484910597: 0, 484910598: 0, 484910599: 0, 285212179: 0, 419429908: 0, 484910612: 0, 419429913: 0, 484910626: 0, 484910627: 0, 419429924: 0, 484910628: 0, 484836902: 0, 486538792: 0, 484910641: 0, 419378738: 0, 419378743: 0, 484910647: 0, 150892103: 0, 418383431: 0, 419343943: 0, 484910663: 0, 419429959: 0, 419429964: 0, 418326155: 0, 218103436: 0, 484910731: 0, 218103441: 0, 419378837: 0, 218103494: 0, 484910790: 0, 217980629: 0, 217990869: 0, 484910843: 0, 417998587: 0, 485238523: 0, 419360512: 0, 419362560: 0, 418316032: 0, 418381568: 0, 217054976: 0, 217054979: 0, 419358470: 0, 417922819: 0, 217054981: 0, 414318342: 0, 218103559: 0, 284163847: 0, 414318343: 0, 418053894: 0, 418316037: 0, 418316038: 0, 418316039: 0, 212664083: 0, 218103571: 0, 418316051: 0, 418316052: 0, 418381587: 0, 419430163: 0, 418316057: 0, 418381593: 0, 419317529: 0, 419362585: 0, 419430164: 0, 418381602: 0, 419430178: 0, 419430179: 0, 218103586: 0, 218103587: 0, 284163876: 0, 419317544: 0, 417922851: 0, 418053926: 0, 418316067: 0, 418316068: 0, 418316070: 0, 418316072: 0, 484837158: 0, 419317553: 0, 218103601: 0, 217055026: 0, 402718513: 0, 418316081: 0, 418316082: 0, 418316086: 0, 217055031: 0, 416350007: 0, 418316087: 0, 418381623: 0, 419317559: 0, 419362615: 0, 402718535: 0, 418316103: 0, 418381639: 0, 419317575: 0, 419430215: 0, 418316108: 0, 486399815: 0, 418316171: 0, 419428236: 0, 218103692: 0, 418316172: 0, 418381707: 0, 418381708: 0, 418316177: 0, 419362700: 0, 217055125: 0, 417922965: 0, 418316181: 0, 418316184: 0, 418381717: 0, 419317653: 0, 419362709: 0, 418316193: 0, 418316194: 0, 417922977: 0, 417922978: 0, 417922981: 0, 418316195: 0, 418316196: 0, 418316197: 0, 418316217: 0, 418316230: 0, 217980885: 0, 218103765: 0, 418316245: 0, 418381781: 0, 419430357: 0, 418316283: 0, 418381819: 0, 486539259: 0, 418316272: 0, 418381808: 0, 419430384: 0, 418007035: 0, 418054142: 0}, 'CAN2': {}}`

Also, on the latest asammdf development version, I get below error when I try to concatenate the file (just FYI, in case the two may be related somehow): 

```
Traceback (most recent call last):
  File "C:\Users\marti\Documents\api-examples\examples\mdf\asammdf_basics.py", line 17, in <module>
    mdf = MDF.concatenate(logfiles)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\mdf.py", line 2078, in concatenate
    merged.append(signals, common_timebase=True)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2671, in append
    inval_cntr,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1566, in _append_structure_composition
    assert len(can_id) == 1
AssertionError
```

Happy to do a video recording of my steps or change parts of my installation setup to match your version if possible.

Martin

**Comment by danielhrisca** [comment]
Hello Martin,

I had to do a "small" reafactoring of _extract_can_logging_ to improve performance. Now it extracts "7F34B296_00000008_00000001.mf4" in under 1s on my laptop.

**Comment by MatinF** [comment]
Hi Daniel, this now seems to work great based on my tests - I'll let you know when I get to test with larger files, but for now I'm closing this. Amazing work :-)

**Comment by danielhrisca** [comment]
Thank you Martin
