### ISSUE TITLE
After resampling, channel values are getting approximated to 1 decimal value

### ISSUE THREAD

**Issue by az299260** [danielhrisca/asammdf#166]
# Python version
'python=3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.15.4'
'asammdf=5.4.1'
```
# Code 

  ## MDF version
3.10

  ## Code snippet
def resample(self, raster, version=None):
  
  ## Traceback
  
# Description

After resampling using master channel, signal values are getting approximated to 1 decimal value

_Please describe the issue here._

Python | expected
1.2 | 1.22312
1.2 | 1.24625
1.2 | 1.21278
1.3 | 1.34312
1.3 | 1.35655

**Comment by danielhrisca** [comment]
Please print the original samples and the raster

**Comment by az299260** [comment]
just checked,, data is getting approximated during the initial read stage. and the same is getting populated during raster

**Comment by danielhrisca** [comment]
You need to provide more details

**Comment by danielhrisca** [comment]
@az299260 
any progress?

**Comment by danielhrisca** [comment]
@az299260 

are you still interested in solving this issue?

**Comment by az299260** [comment]
Hi,
sorry for late reply.
the issue is when i time sample mdf file using matlab i'm getting values with up to 6/7 decimal places. But when i'm sampling using asammdf the values are getting truncated up to 1 decimal place

For example, the value i got from matlab is '2.5698752', and the same signal value i'm getting from asammdf is '2.5' or '2.6'.  The rest of the decimal places are being approximated or truncated i suppose 

I would like to have the preceding decimal values also as i have few parameters where i need to find the peak intervals.

**Comment by danielhrisca** [comment]
Can you share some code snippet that you use? I can't see why the values would be truncated like this

**Comment by az299260** [comment]
i'm using the asammdf resample code...and i haven't done any further modifications to the signal,

```
myobj = asammdf.MDF(filename).filter(['signal1','signal2','signal3'])
asamyop = myobj.resample(raster='signal2') 
values = asamyop.get('signal3').samples 
```

**Comment by danielhrisca** [comment]
Please print s1, s2 and s3

**Comment by az299260** [comment]
what i have observed is, the original data before sampling is with 1 decimal point. But when sampled using matlab the values are populated with multiple decimal places.

but with asammdf, i guess it's still retaining the single decimal precision as per the original signal values

**Comment by danielhrisca** [comment]
It would help me if you could print the 3 signals

**Comment by az299260** [comment]
i have printed both before and after sampling of a signal. 
![asamdecimal](https://user-images.githubusercontent.com/49338300/57119499-35606380-6d88-11e9-9983-b5bd968b8a0d.PNG)

**Comment by danielhrisca** [comment]
It looks ok to me. Re-open if you have other problems
