### ISSUE TITLE
to_dataframe, time_from_zero select channel

### ISSUE THREAD

**Issue by meretp** [danielhrisca/asammdf#167]
# Python version
('python=3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 '
 '64 bit (AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.14.0'
'asammdf=5.4.0'
 
# Description

I am using  to_dataframe with different channels and the flag time_from_zero = True. Is there a way to select one channel for the starting point of the time vector?

**Comment by danielhrisca** [comment]
Hello @meretp 

if you update to release 5.5.0 you can specify the raster as channel name or as am array https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.to_dataframe

**Comment by meretp** [comment]
mdf_data = MDF(file)
dataframe = mdf_data.to_dataframe(channels=['P','F','L'],raster = 'P', time_from_zero=True) 

Hello @danielhrisca 

I switched to version 5.5.0 and applied the code above. Unfortunately an error will occur:
  File "...\lib\site-packages\asammdf\mdf.py", line 3421, in to_dataframe
    reduce_memory_usage=reduce_memory_usage,
  File "..\lib\site-packages\asammdf\mdf.py", line 3445, in to_dataframe
    df["time"] = pd.Series(master, index=np.arange(len(master)))
UnboundLocalError: local variable 'master' referenced before assignment

**Comment by meretp** [comment]
If I switch back to my old assignment and using the raster as predefined step size like this  
       dataframe = mdf_data.to_dataframe(channels=['P','F','L'],raster = 0.01 , time_from_zero=True)
the same error will occur.

**Comment by danielhrisca** [comment]
Yes you need to assign raster to master here https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L3437
``master = raster ``

**Comment by meretp** [comment]
Now it's working, thanks! 
Will you change this in the next update in general ?

**Comment by danielhrisca** [comment]
I will release 5.5.1 asap
