### ISSUE TITLE
something about MDF format

### ISSUE THREAD

**Issue by ahao1995** [danielhrisca/asammdf#168]
Hello：
You may have a deep understanding of MDF format. As you know in some cases, we may need to write unsorted MDF, it should have a record_id, but I don't have detail format of MDF, and don't have some examples, do you have some test files about this or have some suggests about it? I have some difficulties in how to write unsorted MDF, especially 3.3.0 version. 
looking forward to your reply.Thank you!

**Comment by ssd4130** [comment]
I have a python package that can generate unsorted MDF in this version.

**Comment by danielhrisca** [comment]
https://github.com/danielhrisca/asammdf/files/3111848/test.demo.zip

**Comment by ahao1995** [comment]
> 
> 


> 
> 
> I have a python package that can generate unsorted MDF in this version.

where can I find the package? Thank you

**Comment by ahao1995** [comment]
where can I find the package? Thank you @ssd4130

**Comment by ahao1995** [comment]
@danielhrisca Thank you very much!!!

**Comment by danielhrisca** [comment]
You can get mdfvalidator and the mdf 3.3.0 spec free from vector https://www.vector.com/int/en/search/?tx_solr[filter][0]=categoryContent%3A7&tx_solr[filter][1]=categoryStandard%3A54

**Comment by ahao1995** [comment]
@danielhrisca Thank you once again!
