### ISSUE TITLE
Rename Channels in MDF

### ISSUE THREAD

**Issue by wangdino** [danielhrisca/asammdf#169]
Hello! 

First of all many thanks for this great library - it has saved me huge amount of time working with MDF files.

As I'm a python noob I'd like to ask for some experts' opinion about the best way to rename some channels in MDF files.

Say I have a configuration file/dictionary `cfg` where keys are the normalized channel names and values are the raw channel names. Intention is to have a universal channel name system when working across different projects in future.

What I've tried:

```python
def data_prep(filename, cfg, freq=0.01):
    signals_normal = list()
    signals_raw = list()
    for key, val in cfg.items():
        signals_normal.append(key)
        signals_raw.append(val)
    with MDF(filename) as mdf_file:
        mdf_reduce = mdf_file.filter(signals_raw)
        mdf_output = mdf_reduce.resample(freq)
        # Rename <Raw Signal Names> to <Normalized Signal Names>
        counter = 0
        for channel in mdf_output.iter_channels():
            channel.name = signals_normal[counter]
            print(channel.name)
            counter += 1
        signals_output = mdf_output.select(signals_normal, raw=False, dataframe=False)
        print(signals_output)
    return
```

At the `print(channel.name)` line it looks like the channel name property is changed, but the change isn't reflected in the `mdf_output` object. If I try to select channel list using the  `mdf_output.select(signals_normal)` method, apparently it will return "Channel "xxx" not found".

So my question is whether there's a way to carry out the renaming action? For now I'm assuming there's no duplicated channel names in the MDF.

Thanks!

**Comment by danielhrisca** [comment]
Hello Dino,

since you are a beginner I will first give you some general points

```python
signals_normal = list(cfg)
#or 
signals_normal = list(get.keys())

signals_raw = list(get.values())


for counter, channel in enumerate(mdf_output.iter_channels()):
    # no need to manage the counter

```

now coming to your question: the _iter_channels_ method yields `Signal` objects (see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.iter_channels and  https://asammdf.readthedocs.io/en/latest/api.html#signal) that are decoupled from the mdf_output object. You are setting the name but the change does not affect mdf_output

What you need to do is reach into the mdf_output internal structure

```python
# here we need to manage the counter
counter = 0
for i, gp in enumerate(mdf_output.groups):
    for j, channel in enumerate(gp.channels):
        channel.name = signals_normal[counter]
        counter += 1
```

**Comment by wangdino** [comment]
Thanks for the reply and suggestion Daniel! Apparently I misunderstood the _iter_channels_ method.

Running your sample code it looks like the returned channels are not as expected. Assuming I have 5 signals defined in `dict(cfg)`, and after the _filter_ and _resample_ I run:

``` python
counter = 0
for i, group in enumerate(mdf_output.groups):
    for j, channel in enumerate(group.channels):
        print(counter, channel.name)
        counter += 1
```

The result is:

> 0 t
> 1 Channel1
> 2 t
> 3 Channel2
> ...
> 8 t
> 9 Channel5

While this can be dealt with, I'm not sure if the behaviour would be the same for other MDF files. Do you think this is expected?

Thanks for any insights!

**Comment by danielhrisca** [comment]
> It looks like the mdf.select method tries to validate channel names in channels_db instead of iterating through the actual channels (which is understandable). Question is, how can I get around this?

I didn't see far enough. You need to update the channels_db if you want to access the channels with the new names using the same MDF object.
