### ISSUE TITLE
mdf.get(): TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by JensLo** [danielhrisca/asammdf#17]
Hey,

just tried to use your library. Unfortunately I get an error loading data from a measurement, which was recorded with ETAS INCA 7.2. It is a mdf version 3 file.

```
from asammdf.asammdf import MDF, Signal, configure
import numpy as np
import os


DIR = r'...\Desktop'  
FILE = r'some_measurement.dat'

mdf_file = MDF(os.path.join(DIR, FILE))

mdf_file.get('some_signal')
```

This produces the following error.

> --------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-4-9d1935140eed> in <module>()
> ----> 1 mdf_file.get('some_signal')
> 
> ...\asammdf\asammdf\mdf3.py in get(self, name, group, index, raster, samples_only, data)
>    2184                 if 'record' not in grp:
>    2185                     if dtypes.itemsize:
> -> 2186                         record = fromstring(data, dtype=dtypes)
>    2187                     else:
>    2188                         record = None
> 
> ...\Continuum\Anaconda3_4.4\lib\site-packages\numpy\core\records.py in fromstring(datastring, dtype, shape, offset, formats, names, titles, aligned, byteorder)
>     707         shape = (len(datastring) - offset) / itemsize
>     708 
> --> 709     _array = recarray(shape, descr, buf=datastring, offset=offset)
>     710     return _array
>     711 
> 
> ...\Continuum\Anaconda3_4.4\lib\site-packages\numpy\core\records.py in __new__(subtype, shape, dtype, buf, offset, strides, formats, names, titles, byteorder, aligned, order)
>     421             self = ndarray.__new__(subtype, shape, (record, descr),
>     422                                       buffer=buf, offset=offset,
> --> 423                                       strides=strides, order=order)
>     424         return self
>     425 
> 
> TypeError: 'float' object cannot be interpreted as an integer

Due to legal restrictions I can not post more details. However I can send you the print out of gr['parents']  and gr['types'] via Mail.

**Comment by danielhrisca** [comment]
What numpy version do you have?

**Comment by danielhrisca** [comment]
Please check if it's the same numpy problem as issue #7

**Comment by JensLo** [comment]
```
import numpy                                                                                                       
numpy.__version__   

```
> '1.12.1'

Update to version 1.13.1 solved the problem.
