### ISSUE TITLE
Mixed raw and phy Signal Output

### ISSUE THREAD

**Issue by wangdino** [danielhrisca/asammdf#170]
# Python version
'3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]'
OS: 'Windows-10-10.0.17134-SP0'
numpy: '1.16.2'
asammdf: '5.4.1'

  ## MDF version
  4.10

# Description
In the MDF file I'm working on, some channels have number-to-text conversion, for example:

_Gear_
> raw = 7
> phy = b'7th Gear'

While other channels have normal number-to-number conversions, for example:

_Speed_
> raw = 8889
> phy = 88.89

# Question
Is there a way to generate a list of channels, whose _samples_ are all sort of numbers (int or float doesn't matter)? Meanwhile for convenience I'd like to keep the number-to-number conversions in phy format. This will lead to a mix of raw and phy _Signals_.

Pseudo code:
```python
def generate_numeric_signals(mdf, wanted_signals):
    signals = mdf.select(wanted_signals, raw=False)
    for signal in signals:
        if type(signal.samples[0]) == numpy.bytes_:
            signal.samples = convert_to_raw(signal)
    return signals
```
Does it work this way? If so how do I write the "convert_to_raw" function? 
What's a better way to do this?

Thanks!

**Comment by danielhrisca** [comment]
I would suggest the you call _select_ with _raw=True_ and check the channel conversion type
(https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/v4_constants.py#L85)

```python
signals = mdf.select(names, raw=True)
for i, sig in enumerate(signals):
    if sig.conversion and sig.conversion.conversion_type < 7:
        signals[i] = sig.physical()
```

**Comment by wangdino** [comment]
Thanks! 

By conversion type were you referring to this?
![image](https://user-images.githubusercontent.com/17481387/56900315-dd500580-6ad8-11e9-9675-961a3844ccfd.png)

**Comment by danielhrisca** [comment]
> Thanks!
> 
> By conversion type were you referring to this?
> ![image](https://user-images.githubusercontent.com/17481387/56900315-dd500580-6ad8-11e9-9675-961a3844ccfd.png)

Yes.
