### ISSUE TITLE
Multi-file export support?

### ISSUE THREAD

**Issue by NewGuy012** [danielhrisca/asammdf#171]
Hello,

Is it currently possible to export multiple files at once in the GUI?
It would be nice if there was an export button in the multiple files toolbox page in the GUI.

Thanks.

**Comment by danielhrisca** [comment]
Sure, I'll add thhis to the 5.6.0 release

**Comment by danielhrisca** [comment]
@NewGuy012 

The first implementation is now available in the development branch. Please try it out and give your feed-back

**Comment by MatinF** [comment]
Awesome work!

**Comment by NewGuy012** [comment]
Hi Daniel,

Thank you for the quick response, it works great!

A slightly separate question, but is it currently possible to drag and drop multiple files into the batch processing mode GUI instead of clicking on File -> Open?

**Comment by danielhrisca** [comment]
You can drag and drop (after selecting the natch mode from the menu) but there is a small issue with rearranging the files in the list since I couldn't enable internal mode.

![batch](https://user-images.githubusercontent.com/20952040/57039565-a9561b00-6c65-11e9-8703-da3be87927de.gif)

**Comment by NewGuy012** [comment]
Hi Daniel,

I can drag and drop a single file into the "Single Files" mode but, it does not seem to be working in the "Batch Processing" mode. 

I think it may be related to the startDrag function in the widgets because when I load the files manually (by clicking File -> Open) and then try to drag the files, I get this error:

-------------------------------------------------------------------------
(Python3) C:\Users\Public\Documents\Python Scripts>asammdf
QMdiSubWindow::setSystemMenu: system menu is already set
Could not parse stylesheet of object 0xf529ff0
  File "c:\programdata\anaconda3\envs\python3\lib\site-packages\asammdf\gui\widgets\list.py", line 61, in startDrag
    t = [self.itemWidget(i).text() for i in self.selectedItems()]
  File "c:\programdata\anaconda3\envs\python3\lib\site-packages\asammdf\gui\widgets\list.py", line 61, in <listcomp>
    t = [self.itemWidget(i).text() for i in self.selectedItems()]

<class 'AttributeError'>: 'NoneType' object has no attribute 'text'
-------------------------------------------------------------------------

I've attached a sample data file for your reference.
[sample_data.zip](https://github.com/danielhrisca/asammdf/files/3136105/sample_data.zip)

Thanks.

**Comment by danielhrisca** [comment]
You need to update to the latest development code

**Comment by NewGuy012** [comment]
Awesome, the feature works great! Thank you so much.
