### ISSUE TITLE
IndexError: list index out of range when export mf4 to csv

### ISSUE THREAD

**Issue by jajapang** [danielhrisca/asammdf#172]
# Python version
('python=3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08) \n'
 '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
'os=Darwin-18.5.0-x86_64-i386-64bit'

# numpy version
'numpy=1.16.3'

# asammdf version
5.5.0

# Code 
mf4 = MDF('./data/test.MF4')
mf4 = mf4.export('csv','test.csv')

  ## MDF version
4.10

  ## Code snippet
mf4 = MDF('./data/test.MF4')
mf4 = mf4.export('csv','test.csv')
  
  ## Traceback
IndexError                                Traceback (most recent call last)
<ipython-input-27-84dd17276353> in <module>
----> 1 mf4 = mf4.export('csv','test.csv')

~/anaconda3/envs/test/lib/python3.6/site-packages/asammdf/mdf.py in export(self, fmt, filename, **kargs)
   1359                                 channels = [
   1360                                     self.get(group=i, index=j, data=data)
-> 1361                                     for j in range(ch_nr)
   1362                                     if j != master_index
   1363                                 ]

~/anaconda3/envs/test/lib/python3.6/site-packages/asammdf/mdf.py in <listcomp>(.0)
   1360                                     self.get(group=i, index=j, data=data)
   1361                                     for j in range(ch_nr)
-> 1362                                     if j != master_index
   1363                                 ]
   1364 

~/anaconda3/envs/test/lib/python3.6/site-packages/asammdf/blocks/mdf_v4.py in get(self, name, group, index, raster, samples_only, data, raw, ignore_invalidation_bits, source, record_offset, record_count, copy_master)
   4069                                     try:
   4070                                         ref_dg_nr, ref_ch_nr = ca_block.referenced_channels[
-> 4071                                             i
   4072                                         ]
   4073                                     except:

IndexError: list index out of range
  
# Description

It throws "IndexError: list index out of range" error when I tried to export mf4 file to csv.

**Comment by jajapang** [comment]
Also, if I try to convert MF4 to dataframe with mf4.to_dataframe(). It throws similar error message.
----> 1 mf4 = mf4.to_dataframe()

~/anaconda3/envs/test/lib/python3.6/site-packages/asammdf/mdf.py in to_dataframe(self, channels, raster, time_from_zero, empty_channels, keep_arrays, use_display_names, time_as_date, reduce_memory_usage)
   3472                 for k, index in enumerate(included_channels):
   3473                     signal = self.get(
-> 3474                         group=group_index, index=index, data=fragment, samples_only=True, ignore_invalidation_bits=True
   3475                     )
   3476                     signals[k].append(signal[0])

~/anaconda3/envs/test/lib/python3.6/site-packages/asammdf/blocks/mdf_v4.py in get(self, name, group, index, raster, samples_only, data, raw, ignore_invalidation_bits, source, record_offset, record_count, copy_master)
   4069                                     try:
   4070                                         ref_dg_nr, ref_ch_nr = ca_block.referenced_channels[
-> 4071                                             i
   4072                                         ]
   4073                                     except:

IndexError: list index out of range

**Comment by danielhrisca** [comment]
Hello Cynthia,

are you allowed the share a scrambled file?

**Comment by jajapang** [comment]
Hi Daniel,

unfortunately I am not allowed to share a scrambled file. Is there any other additional information I can provide to help debugging?

**Comment by danielhrisca** [comment]
I will have a look tonight and I will ask for more info

**Comment by danielhrisca** [comment]
This line (https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/mdf_v4.py#L4074) should give some printed outputbefore the exception is raised again. Can you post it here?

**Comment by danielhrisca** [comment]
@jajapang 

did you retry using the latest development branch code?

**Comment by danielhrisca** [comment]
@jajapang 
any updates?
