### ISSUE TITLE
Have identical number of samples for selected signals

### ISSUE THREAD

**Issue by wangdino** [danielhrisca/asammdf#173]
# Python version
'3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]'
OS: 'Windows-10-10.0.17134-SP0'
numpy: '1.16.2'
asammdf: '5.4.1'

  ## MDF version
  4.10
  
# Description

Sometimes due to the latency among different measurement devices the number of samples in an MDF file isn't always identical across all signals. For example I selected a list of signals in a file and printed the first and last timestamp as well as the number of samples of these signals:
![image](https://user-images.githubusercontent.com/17481387/56963054-6891cf80-6b9b-11e9-866e-63881592ab27.png)

It appears the difference is at the beginning of the measurement. Is there a way to retrieve identical number of samples for selected signals?

More importantly what's an optimal way to do this automatically? For example all my signals are measured at 100Hz and if signals with most and least samples are differed by 5 samples I'd just discard 1 to 5 samples (or 0.01 to 0.05 seconds equivalent of data) in the beginning of the concerned signals.

Having read the document I'm not sure between _MDF.cut(start=xx)_ and _MDF.select(record_offset=xx)_ as these part of the documentation isn't very descriptive. 

Thanks!

Btw this seems to be a discrepancy in the documentation:
![image](https://user-images.githubusercontent.com/17481387/56964053-bd364a00-6b9d-11e9-90fe-b223995cbe4a.png)

**Comment by danielhrisca** [comment]
The _record_offset_ argument will be applied to all channel groups, so you will still have a samples discrepancy. 

You could get the first timesamps for all groups and cut from the maximum (see the algorithm here https://github.com/danielhrisca/asammdf/blob/development/asammdf/mdf.py#L642 and you can delete line 644 https://github.com/danielhrisca/asammdf/blob/development/asammdf/mdf.py#L644)

I've fixed the documentation as well

**Comment by wangdino** [comment]
Probably dumb questions but as they're related to the post I'll just ask here...

### 1. What's the fastest way to get the number of all channels in a given MDF?
I know `len(list(mdf.iter_channels()))` will get me the number but counting a list of generator doesn't sound right.

### 2. What's the fastest way to get the number of samples from all channels in a given MDF?
My current approach:
```python
sizes = list()
for channel in mdf.iter_channels():
    sizes.append(numpy.size(channel.samples))
```
### 3. What's the optimal way to get the previous answers combined?
My thought based on your suggestion:
1. get the number of samples from all channels
2. find the channel with least amount of samples
3. get the first timestamp `ts1` of that channel
4. use that timestamp to construct a `mdf.cut(start = ts1)` 
I understand I could just:
1. get the first timestamp of all channels
2. find the maximum of the timestamps `ts1_max`
3. use that timestamp to construct a `mdf.cut(start = ts1_max)`
But still I'd like to verify whether the numbers of samples from all channels are same or not after the operation. If there's a better way to verify please instruct.

All that being said, do you think it's worthwhile to have this built into one of the functions (for example `mdf.resample(align_samples=True)`? I could be wrong but my assumption is people who resample signals would probably want same number of samples from all channels.

Thank you for the help as always!

**Comment by danielhrisca** [comment]
1. 
    ```python
    nr = sum(len(gp.channels) for gp in mdf.groups)
    ```

2. you can simply check the _cycles_nr_ attribute of the channel group
    ```python
    sizes = [gp.channel_group.cycles_nr for gp in mdf.groups]

3. In your cased it might be this simple, but there are other cases (different sampling rates, asynchronous sampling, channel groups without any recorded sample).

You can just feed a custom _raster_ to the _resample_ method and this will be applied for all channels

```python
from asammdf import MDF, Signal

mdf = MDF()

s1 = Signal(
    samples = [1,2,3,4],
    timestamps = [5,10,15,20],
    name='S1',
)

mdf.append(s1)

s2 = Signal(
    samples = [5,6,7,8],
    timestamps = [3,5,7,9],
    name='S2',
)

mdf.append(s2)

mdf = mdf.resample(raster=[5.5, 6.5, 7.5, 8])

print(mdf.get('S1'))
print(mdf.get('S2'))
```

```
<Signal S1:
        samples=[1 1 1 1]
        timestamps=[5.5 6.5 7.5 8. ]
        invalidation_bits=None
        unit=""
        conversion=None
        source=SignalSource(name='Python', path='Python', comment='', source_type=4, bus_type=0)
        comment=""
        mastermeta="('time', 1)"
        raw=False
        display_name=
        attachment=()>

<Signal S2:
        samples=[6 6 7 7]
        timestamps=[5.5 6.5 7.5 8. ]
        invalidation_bits=None
        unit=""
        conversion=None
        source=SignalSource(name='Python', path='Python', comment='', source_type=4, bus_type=0)
        comment=""
        mastermeta="('time', 1)"
        raw=False
        display_name=
        attachment=()>
```

**Comment by wangdino** [comment]
Thank you Daniel. I tried to write a function based on your hint and here're some of my observations.

``` python
def data_prep_prototype(filename):
    with MDF(filename) as mdf_file:
        # Number of all channels in MDF
        n_channels = sum(len(group.channels) for group in mdf_file.groups)

        # Getting numbers of samples for each channel
        counter = 0
        n_samples = numpy.empty(n_channels, numpy.int)
        i_channels = list()
        for i, group in enumerate(mdf_file.groups):
            for j, channel in enumerate(group.channels):
                n_samples[counter] = group.channel_group.cycles_nr
                i_channels.append((channel.name, i, j))
                counter += 1
        print(n_samples, len(n_samples), len(set(n_samples)))

        # Looking for channels with maximum number of samples
        indices = numpy.where(n_samples == numpy.max(n_samples))
        # indices[0][0] is timestamp, indices[0][1] is actual channel
        # signal_index in format: (channel name, group index, channel index) tuple
        signal_index = i_channels[indices[0][1]]
        # Select one channel that has the most samples hence longest timestamps
        long_signal = mdf_file.select([signal_index])

        # Generating resampled MDF
        # Among 3 given options for raster, 2 will fail
        raster_array = long_signal[0].timestamps  # this will fail
        raster_name = signal_index[0]  # this will fail too
        raster_float = 0.01  # only this works
        mdf_file.configure(integer_interpolation=0)
        mdf_resample = mdf_file.resample(raster_float)

        # Verification
        counter = 0
        n_samples = numpy.empty(n_channels, numpy.int)
        for group in mdf_resample.groups:
            for channel in group.channels:
                n_samples[counter] = group.channel_group.cycles_nr
                counter += 1
        print(n_samples, len(n_samples), len(set(n_samples)))
    return
```
Output from the two `print` lines:
#### Output 1 - original MDF

> [    0     0 46268 46268 46264 46264 46268 46268 46259 46259 46259 46259
>  46259 46259 46259 46259 46259 46259 46259 46259 46259 46259 46259 46259
>  46259 46259 46265 46265 46265 46265 46265 46265 46259 46259 46263 46263
>  46268 46268 46268 46268 46268 46268 46268 46268 46263 46263 46263 46263
>  46263 46263 46263 46263 46263 46263 46263 46263 46263 46263 46263 46263
>  46263 46263 46263 46263 46263 46263 46263 46263 46263 46263 46263 46263
>  46263 46263 46268 46268 46267 46267 46268 46268 46267 46267 46268 46268
>  46267 46267 46269 46269 46268 46268 46268 46268 46268 46268 46268 46268
>  46267 46267 46267 46267 46267 46267 46267 46267 46263 46263 46263 46263
>  46263 46263 46263 46263 46263 46263 46263 46263 46263 46263 46263 46263
>  46263 46263 46263 46263 46267 46267 46263 46263 46263 46263 46263 46263
>  46263 46263 46263 46263 46263 46263 46263 46263 46268 46268 46268 46268
>  46268 46268 46268 46268 46268 46268 46267 46267 46267 46267 46267 46267
>      0     0     0     0 46268 46268 46268 46268 46268 46268 46268 46268
>  46268 46268 46268 46268 46268 46268 46268 46268 46268 46268 46268 46268
>  46268 46268 46268 46268 46268 46268 46268 46268 46268 46268 46268 46268
>  46268 46268 46268 46268 46268 46268 46268 46268 46268 46268 46267 46267
>  46267 46267 46267 46267 46266 46266 46266 46266 46266 46266 46267 46267
>      0     0 46269 46269 46269 46269 46269 46269 46269 46269 13878 13878
>  13880 13880 46265 46265 46265 46265 46265 46265 46265 46265 46265 46265
>  46265 46265 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267
>  46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267
>  46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46269 46269
>  46269 46269 46269 46269 46268 46268 46268 46268 46268 46268 46268 46268
>  46270 46270 46270 46270] 292 12
> 

#### Output 2 - resampled MDF

> [    0     0 46267 46267 46263 46263 46267 46267 46258 46258 46258 46258
>  46258 46258 46258 46258 46258 46258 46258 46258 46258 46258 46258 46258
>  46258 46258 46264 46264 46264 46264 46264 46264 46258 46258 46262 46262
>  46267 46267 46267 46267 46267 46267 46267 46267 46262 46262 46262 46262
>  46262 46262 46262 46262 46262 46262 46262 46262 46262 46262 46262 46262
>  46262 46262 46262 46262 46262 46262 46262 46262 46262 46262 46262 46262
>  46262 46262 46267 46267 46266 46266 46267 46267 46266 46266 46267 46267
>  46266 46266 46268 46268 46267 46267 46267 46267 46267 46267 46267 46267
>  46266 46266 46266 46266 46266 46266 46266 46266 46262 46262 46262 46262
>  46262 46262 46262 46262 46262 46262 46262 46262 46262 46262 46262 46262
>  46262 46262 46262 46262 46266 46266 46262 46262 46262 46262 46262 46262
>  46262 46262 46262 46262 46262 46262 46262 46262 46267 46267 46267 46267
>  46267 46267 46267 46267 46267 46267 46266 46266 46266 46266 46266 46266
>      0     0     0     0 46267 46267 46267 46267 46267 46267 46267 46267
>  46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267
>  46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267
>  46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46266 46266
>  46266 46266 46266 46266 46265 46265 46265 46265 46265 46265 46266 46266
>      0     0 46268 46268 46268 46268 46268 46268 46268 46268 46255 46255
>  46264 46264 46263 46263 46263 46263 46263 46263 46263 46263 46263 46263
>  46263 46263 46265 46265 46265 46265 46265 46265 46265 46265 46265 46265
>  46265 46265 46265 46265 46265 46265 46265 46265 46265 46265 46265 46265
>  46265 46265 46265 46265 46265 46265 46265 46265 46265 46265 46267 46267
>  46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267 46267
>  46268 46268 46268 46268] 292 10

It appears that `mdf.resample` isn't very helpful in this case - after the resample I still have 10 different numbers of samples among all signals. Did I miss anything or is there another way?

Eventually I'd like to pass the data to a SQL database and it would be critical for all signals to have the same amount of datapoints and that they are indexed to one time axis.

Regarding the options to feed _raster_ in the `mdf.resample` method, I followed the documentation:
https://asammdf.readthedocs.io/en/master/api.html#asammdf.mdf.MDF.resample

In this case if I feed the timestamp array, it will return:

>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 2471, in resample
>     if raster:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

If I feed the name of the channel, it will return:

>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 2472, in resample
>     num = float(np.float32((master[-1] - master[0]) / raster))
> TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I don't know enough to tell what happened in the source code. If you need further information to diagnose I'll try my best to provide. Thanks!

**Comment by danielhrisca** [comment]
The _raster_ as channel name or user defined array was introduced in asammdf 5.5.0. You need to update first

**Comment by wangdino** [comment]
You're right! Silly me!

Now it works like a charm:

> [    0     0 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>      0     0     0     0 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>      0     0 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270 46270
>  46270 46270 46270 46270] 292 2

Performance-wise do you think this is optimal? As I resampled based on the longest timestamps among all signals, basically all the other signals will be re-calculated (interpolated), correct?

Is there a quick way to remove one channel from a MDF (given name or index)?

Thanks!

**Comment by danielhrisca** [comment]
Curently you can only use the _filter_ method ( filter then resample)
