### ISSUE TITLE
Question: Is there a configuration to turn off attachment extraction?

### ISSUE THREAD

**Issue by wangdino** [danielhrisca/asammdf#174]
# Python version

> ('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
>  '(AMD64)]')
> 'os=Windows-10-10.0.17134-SP0'
> 'numpy=1.16.2'
> 'asammdf=5.5.1'

# Description

A couple of signals in my MDF has attachments which are huge video recordings so I don't keep them in the working folder. While working with such MDFs, certain method will yield warnings:

> asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')

Is there a way to turn this off? Based on various situation the warning would appear at various positions in console (not a big deal though).

What's annoying is that calling certain mdf methods after `mdf.iter_channels()` will yield errors, for example:

#### This works, if channels with attachment are filtered out
``` python
def data_prep_full(filename, sample_rate=0.01):

    with MDF(filename) as mdf_file:

        # Construct MDF object: exclude empty channels and channels with attachment
        selected_signals = list()
        for n, channel in enumerate(mdf_file.iter_channels()):
            if numpy.size(channel.samples) == 0:
                continue
            elif channel.attachment:
                continue
            else:
                selected_signals.append(channel.name)
        mdf_filter = mdf_file.filter(selected_signals)

        mdf_resample = mdf_filter.resample(raster=sample_rate)

        # some other code

    return
```

#### This will fail, as channels with attachment are kept
``` python
def data_prep_full(filename, sample_rate=0.01):

    with MDF(filename) as mdf_file:

        # Construct MDF object: exclude empty channels and channels with attachment
        selected_signals = list()
        for n, channel in enumerate(mdf_file.iter_channels()):
            if numpy.size(channel.samples) == 0:
                continue
            # elif channel.attachment:
            #     continue
            else:
                selected_signals.append(channel.name)
        mdf_filter = mdf_file.filter(selected_signals)

        mdf_resample = mdf_filter.resample(raster=sample_rate)

        # some other code

    return
```

My console output:

>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 2659, in resample
>     copy_master=False,
>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 2826, in select
>     ignore_invalidation_bits=True,
>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4693, in get
>     index = self._attachments_map[channel.data_block_addr]
> KeyError: 0

#### Even calling `mdf.iter_channels` for the second time would fail
``` python
def data_prep_full(filename, sample_rate=0.01):
    with MDF(filename) as mdf_file:
        # Construct MDF object: exclude empty channels and channels with attachment
        selected_signals = list()
        for n, channel in enumerate(mdf_file.iter_channels()):
            if numpy.size(channel.samples) == 0:
                continue
            # elif channel.attachment:
            #     continue
            else:
                selected_signals.append(channel.name)
        mdf_filter = mdf_file.filter(selected_signals)

        t_start = list()
        t_end = list()
        n_sample = list()
        for n, channel in enumerate(mdf_filter.iter_channels()):
            t_start.append(channel.timestamps[0])
            t_end.append(channel.timestamps[-1])
            n_sample.append(numpy.size(channel.samples))
    return
```

My console output:

>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 2449, in iter_channels
>     copy_master=copy_master,
>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 2826, in select
>     ignore_invalidation_bits=True,
>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4693, in get
>     index = self._attachments_map[channel.data_block_addr]
> KeyError: 0

Did I miss anything here? Thanks...

**Comment by danielhrisca** [comment]
Hello Dino,

I've pushed a fix in the development branch

You can update using 

``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by wangdino** [comment]
Tested using the "calling mdf.iter_channels for the second time" codes, here's the output:

>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 814, in cut
>     sigs, f"Cut from {start_} to {stop_}", common_timebase=True
>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2513, in append
>     at_data, at_name = signal.attachment
> ValueError: not enough values to unpack (expected 2, got 0)

Tested using the "calling mdf.resample after mdf.iter_channels" codes, here's the output:

>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\mdf.py", line 2711, in resample
>     mdf.append(sigs, common_timebase=True)
>   File "C:\Users\dino\PycharmProjects\Kirribilli\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2513, in append
>     at_data, at_name = signal.attachment
> ValueError: not enough values to unpack (expected 2, got 0)

**Comment by danielhrisca** [comment]
Can you try again with the new code?

**Comment by wangdino** [comment]
Works now in both cases. Thanks a lot for the quick response. Really appreciate that!

**Comment by wangdino** [comment]
One more question - using the MDF object, how do I get the names of the channels with attachment?

I found that `mdf.groups[x].channels[y].attachment` is always _None_

**Comment by danielhrisca** [comment]
You should  check if they have a link to an attachment

```python
mdf.groups[x].channels[y].attachment_addr
```

**Comment by wangdino** [comment]
It's very weird because in my environment it seems to be overwritten...
![image](https://user-images.githubusercontent.com/17481387/57059621-807f6580-6cf9-11e9-8c87-0f0a115c441f.png)


#### Value of `channel.attachment_addr`:

> 'Traceback (most recent call last):
>   File "C:\\Program Files\\JetBrains\\PyCharm 2019.1\\helpers\\pydev\\_pydevd_bundle\\pydevd_resolver.py", line 178, in _getPyDictionary
>     attr = getattr(var, n)
> AttributeError: attachment_addr
> '

As I mentioned I don't keep the actual attachment in the working folder. Could that be the reason?

Currently I'm building a list of block addresses using _mdf.attachments[x].address_:
``` python
# Construct a list of 'data_block_addr' for attachment
att_addr = list()
for att in mdf0_file.attachments:
	att_addr.append(att.address)
```
And later in my iterations in _groups_ and _channels_ I use `if channel.data_block_addr in att_addr` to tell if the _channel_ has an attachment. Not sure if there's a better way though.

**Comment by danielhrisca** [comment]
In your case since you have stream sync channels it is ok to compare data_block_addr with the available attachment addresses.
