### ISSUE TITLE
OBD2 conversion via DBC (complex_multiplexing)

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#175]
**Context** 
OBD2 data logging is one of the most popular use cases for end users as it's relevant across practically all cars. However, OBD2 conversion typically requires a custom script as the conversion technique differs from what is easily supported via CAN DBC files.

However, with some clever techniques, Eduard from the canmatrix team has found a way to fully handle OBD2 Mode 01 PID conversion in the DBC file standard using complex multiplexing, which is now supported in their complex_multiplexing development branch. 

See also the thread on this:
https://github.com/ebroecker/canmatrix/issues/352

**Improvement Suggestion**
It would be awesome if the new canmatrix functionality could be integrated with asammdf to allow the loading of complex_multiplexing DBC files. That would then allow direct conversion of OBD2 responses in CAN bus logging MDF data - to the benefit of many end users.

**Sample Files & DBC**
For the purpose, I've attached a sample MDF raw bus logging file (from our device) and a draft OBD2 DBC file (from the canmatrix team). The sample file contains both request and response OBD2 messages, with the responses incl. e.g. Speed and RPM - which should be possible to decode if the implementation is feasible.

[obd2_dbc_and_asc.zip](https://github.com/danielhrisca/asammdf/files/3135601/obd2_dbc_and_asc.zip)

We think this would be a great addition - let me know your thoughts Daniel and if you think anything else would be required in regards to samples e.g.

Martin

**Comment by danielhrisca** [comment]
CAN signal multiplexing is available in release 5.6.0
