### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'samples'

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#176]
Hi Daniel,

It seems you are trying [here](https://github.com/danielhrisca/asammdf/blob/77166ac73df7069bd23878f2e5b0cfbb94cf061a/asammdf/blocks/mdf_v4.py#L540) to read can_ids like a Signal object but it's actually a numpy.ndarray object (see also [here](https://github.com/danielhrisca/asammdf/blob/77166ac73df7069bd23878f2e5b0cfbb94cf061a/asammdf/blocks/mdf_v4.py#L483)).

**Comment by danielhrisca** [comment]
Hello Julien,

please check the new development branch code

**Comment by danielhrisca** [comment]
Fixed in release 5.6.0
