### ISSUE TITLE
Writing virtual channels

### ISSUE THREAD

**Issue by christianfrick** [danielhrisca/asammdf#177]
Dear all

As far as I do understand the ASAMMDF library it does support to read virtual channels but doesn't allow to create such - or at least not by using the append() function. Is this true?

Is such functionality planned to be implemented in near future?

Best regards
Christian

('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.16.3'
'asammdf=5.5.0'

**Comment by danielhrisca** [comment]
Hello Christian,

for simplicity this is not supported now. What mdf version do you use?

**Comment by christianfrick** [comment]
Hi Daniel
I plan to use MDF Verison 4.11

**Comment by danielhrisca** [comment]
You can use compression if you need smaller file size

**Comment by christianfrick** [comment]
Thanks a lot for your very fast responses. Haha, yes, that's true - but... I'm thinking about creating a proposal and a first implementation of how do introduce it to the library. Are you generally interested or do you already know that you don't want to support generating virtual channels in general?

**Comment by danielhrisca** [comment]
I wouldn't want to complicate things more then necessary. The format is already complex. This doesn't mean we can't experiment and see if it makes sense to integrate such functionality

**Comment by christianfrick** [comment]
I will have a look and may get back to you. Thanks a lot, the library helps us a lot.

**Comment by DT-one** [comment]
Hi Daniel 

I see this ticket is marked complete, but did this enhancement actually get implemented?

I am working with large volumes of constant high-rate sensor data and the time signal is taking up 4/5 or more of the file size, with compression! I'd love to be able to define a virtual channel for the time signal either through append() or manual creation of the channel group blocks (although still working out how to achieve that)

PS, fantastic work on this library, it is really great even as it stands!!

**Comment by danielhrisca** [comment]
Nothing happened for 1 year so I closed it.

**Comment by danielhrisca** [comment]
Nothing happened for 1 year so I closed it.

**Comment by DT-one** [comment]
Thanks for the fast reply!

I've had a read of the append method, I might have a go at implementing something. 

We stand to gain gigabytes in our use case.

Just to confirm: Reading virtual signals is implemented in v3 and v4?

**Comment by danielhrisca** [comment]
can you send a demo file and some details on my e-mail?

**Comment by DT-one** [comment]
Without going into it too deep, I don't have any files. I do have access to a friends Vector tools and CANape licence occasionally, if I organise it.

The data does come from vehicle instrumentation but not as MDF natively. And we currently don't use any standard automotive tools (which we should be!). I am trying to suggest we go that way, but for now I want to make the best use of MDF as a format for its MATLAB and python integration and asammdf gui for its excellent usability for non-coders.

The conversion rules and other metadata are a real strengths but unfortunately the mandatory time bases are taking up a lot of unnecessary space!

**Comment by danielhrisca** [comment]
So you are creating new measurements in Python with asammdf, using data recorded in other formats?

**Comment by DT-one** [comment]
Essentially yes. Which I hope will be compatible with Vector tools in the future.

If MDF proves successful, we may try moving to some C++ libraries for bulk conversion but we would definitely still leverage asammdf for python integration, viewing and ad-hoc work

**Comment by danielhrisca** [comment]
With the development branch code you can append virtual channels and virtual master channels like this

```python
from asammdf import MDF, Signal

m = MDF()

s = Signal(
    samples=[2,2,2,2,2],
    timestamps=[0,0.1, 0.2, 0.3, 0.4],
    virtual_conversion={"a": 0, "b": 2},
    virtual_master_conversion={"a": 0.1, "b": 0},
    flags=Signal.Flags.virtual | Signal.Flags.virtual_master,
    name='SSS'
)
s1 = Signal(
    samples=[2,2,2,2,2],
    timestamps=[0,0.1, 0.2, 0.3, 0.4],
    virtual_master_conversion={"a": 0.1, "b": 0},
    flags=Signal.Flags.virtual_master,
    name='SSS1'
)

m.append([s, s1])

m.save(r'D:\TMP\virt.mf4', overwrite=True)
```

keep in mind that virtualchannels and virtual master channels are computed using the 0-based index array and the conversion rule
![image](https://github.com/danielhrisca/asammdf/assets/20952040/4881eb3b-7280-4ab1-a69c-0191366845c9)
![image](https://github.com/danielhrisca/asammdf/assets/20952040/0489987c-8d18-4761-ae35-419a2b35aba5)
![image](https://github.com/danielhrisca/asammdf/assets/20952040/3c82acca-6b0a-4202-b195-2e0b6a60d735)

**Comment by DT-one** [comment]
Stoked! I'll give it a try. You've implemented it just how I was thinking I'd try.

Only thought is do you think the master conversion needs to be limited for use on a virtual master signal? If the time conversion in Signal was just a 'time_conversion' you could use in either case, you could supply time samples, say UTC time in nanoseconds, as a 64bit integer (a time base format we work with regularly), and apply a conversion to scale it down to seconds. And the 'virtual_master' flag would specify whether the signal is virtual or not. Or, the flag could be set implicitly by specifying timestamps=None?

For example, the time now may be expressed as 1696841403123245000 ns UTC. And this consumes 64bits. With a conversion rule we could use the conversion {"a": 1000, "b":1696841000000000000} and store 403123240 in 32 bits and keep ms precision.
Or, we could store the 64bit times and convert them to seconds for display from midnight {"a": 0.000000001, "b":1696809600}

Does MDF support conversion rules on 'normal' timebases?
