### ISSUE TITLE
Subplot Tile shoud be arange horizontal not vertical and multiple y-axis

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#178]
Hello @danielhrisca ,
is it possible to arange subplots also in horizontal split view? In my opinion the implementation as it is, is not very usable.

Furthermore, there was a nice multi axis view without subplots, if multiple channels where selected in the past. 
Is it possible to re-activate this feature?

Kind regards StlWeb

**Comment by danielhrisca** [comment]
Tiling is done automacally by qt, I will see what can be done for horizontal tiling.

The multiple axis was nkt optimal, having many signals selected would cover the plot area completly. Maybe we would have a manually enable the additional axis on a per signal basis

**Comment by danielhrisca** [comment]
@stlweb 

I've added horizontal and vertical tiling support

![tile](https://user-images.githubusercontent.com/20952040/57184487-ee2bbd00-6ec4-11e9-92c0-bde04e61256e.gif)

**Comment by danielhrisca** [comment]
@stlweb 

I've re-implemented the individual axis, but now it is based on a new checkbox in the channel selection list


![individual_axis](https://user-images.githubusercontent.com/20952040/57191443-68445c00-6f2e-11e9-819d-3cd6fe0a9cf0.gif)
