### ISSUE TITLE
mdf.info() failed due to AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jajapang** [danielhrisca/asammdf#179]
# Python version
('python=3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08) \n'
'[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
'os=Darwin-18.5.0-x86_64-i386-64bit'

# Numpy version
'numpy=1.16.3'

# asammdf version
5.5.0

# Code 
mdf = MDF('./data/test.MDF')
mdf.info()

  ## MDF version
3.10

  ## Code snippet
mdf = MDF('./data/test.MDF')
mdf.info()

  ## Traceback
AttributeError                            Traceback (most recent call last)
<ipython-input-3-c550d4aac4be> in <module>
----> 1 mdf.info()

~/anaconda3/envs/test/lib/python3.6/site-packages/asammdf/blocks/mdf_v3.py in info(self)
   3108         info = {}
   3109         for key in ("author", "department", "project", "subject"):
-> 3110             value = self.header[key].decode("latin-1").strip(" \n\t\0")
   3111             info[key] = value
   3112         info["version"] = self.version    

AttributeError: 'str' object has no attribute 'decode'
  
# Description

Fail to print out info of MDF3 files due to error "AttributeError: 'str' object has no attribute 'decode'".

**Comment by danielhrisca** [comment]
Hello Cynthia,

please check the latest development branch code.

I've also fixes the _debug_channel_ function so you should be able to see the correct print needed for issue #172 . Can you give it a go as well?

**Comment by jajapang** [comment]
Thank you Daniel, this problem is fixed in the development branch.
