### ISSUE TITLE
something about GUI

### ISSUE THREAD

**Issue by ahao1995** [danielhrisca/asammdf#180]
Hello:
Sorry to bother you, I have some question about "Plot/Sub-plots area"  function in asammdf 5.7. When I want to use subplot, the previous window disappeared, I don't know why, and I watch some codes, there is nothing wrong. If you know why, please reply to me. Thank you!

**Comment by danielhrisca** [comment]
Settings -> sub-plots -> Enabled

**Comment by ahao1995** [comment]
@danielhrisca Thank you！I forgot to set it.
