### ISSUE TITLE
CSV Export - Possible to use raw values? Possible to add timestamps?

### ISSUE THREAD

**Issue by wangdino** [danielhrisca/asammdf#181]
# Python version
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.16.2'
'asammdf=5.6.0'

# Code 

  ## MDF version
  4.10

  ## Code snippet
  ```python
from asammdf import MDF, Signal


with MDF('data/sample_data.mf4') as mdf_file:
    signals = mdf_file.select(['GPS_Lat', 'GPS_Lon', 'VEH_GearActual'], 
                              raw=True, 
                              copy_master=True)
    for i, sig in enumerate(signals):
        if sig.conversion and sig.conversion.conversion_type < 7:
            signals[i] = sig.physical()
    with MDF(version='4.10') as mf4_file:
        mf4_file.append(signals)
        export_filename = 'data/test_export.csv'
        mf4_file.export(fmt='csv',
                        filename=export_filename,
                        single_time_base=True,
                        raster=None,
                        time_from_zero=True,
                        empty_channels='skip',
                        reduce_memory_usage=False)

```
  
  ## Traceback
  No error reported. Here's the content of the csv generated:
![image](https://user-images.githubusercontent.com/17481387/57348124-4ea64d00-7198-11e9-83ab-f2637d8fa9e9.png)

  
# Description

I could be wrong but perhaps this is partially related to #170. 

I was trying to use csv export to quickly check some signals. Before export I was hoping to manipulate the raw/physical values so that in the exported file signals are just sort of numeric values instead of being "translated" to the "text" values. Apparently I failed. 

I'm guessing when I use `mf4_file.append` to pass the processed signals in, the conversion table is still there, hence the results. Is there a way to avoid this?

One more thing, the export doesn't contain the timestamps. Is this expected? If so how can I, for example, put the timestamps in the first column?

Thanks!

**Comment by wangdino** [comment]
Well I can answer myself regarding the conversion, I can just add `sig.conversion = None` to remove the conversion table.

```python
    for i, sig in enumerate(signals):
        if sig.conversion and sig.conversion.conversion_type < 7:
            signals[i] = sig.physical()
        else:
            sig.conversion = None
```

Still wondering if there's a way to add timestamps to column 1.

**Comment by danielhrisca** [comment]
Hello Dino,

the csv export has been improved in thw development branch code. The time channel is included as well

**Comment by wangdino** [comment]
Thank you Daniel! Works like a charm.
