### ISSUE TITLE
use pyqtgraph to plot

### ISSUE THREAD

**Issue by ahao1995** [danielhrisca/asammdf#182]
hello:
 I want to ask something about how to use 'pyqtgraph' to plot. If you use CANOE, there is a 'show signals in separate diagrams' function. It displays several signals in different y, and the same x, but it can zoom in and out at the same time for all signals, and have the same cursor, do you know some ways to do this?
Thank you

**Comment by danielhrisca** [comment]
You have the option link the sub-plots x-axis, but there each  sub-plot has an independent cursor
![xlink](https://user-images.githubusercontent.com/20952040/57352065-d4ac9e80-716c-11e9-9126-fa04546b2b8e.gif)

**Comment by ahao1995** [comment]
@danielhrisca I know this，are there any ways to synchronize the cursor？

**Comment by danielhrisca** [comment]
For now there are only independent cursors

**Comment by ahao1995** [comment]
@danielhrisca Ok，thank you~Let me think about it

**Comment by danielhrisca** [comment]
It turns out that connecting the cursors was not so hard. You need to use the latest development branch code
![xlink](https://user-images.githubusercontent.com/20952040/57354536-594eeb00-7174-11e9-9f63-a692e364b567.gif)

**Comment by ahao1995** [comment]
@danielhrisca perfect!Thanks
