### ISSUE TITLE
GUI enhancement: Add bus logging "CSV style" preview vindow

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#183]
Hi Daniel,

We've worked quite a bit now with the GUI and it's a really great tool! 
One thing we thought would be a nice enhancement would be a "csv style" preview for bus logging files - described below:

**Context**
Users that record raw CAN data in MDF will often want to do a quick check to determine if the data contains the expected patterns - for example, did a specific ID filter work as intended - or was no data logged at all?

To do so, the users can today load a raw MDF (bus logging) in asammdf and export the file to CSV. However, this is rather cumbersome for quick analysis purposes. Further, for MDF files of 50 MB or e.g. 200 MB, it's rather cumbersome to export it all into CSV (and you won't be able to load that data in Excel) - and cutting it before export is also cumbersome. 

**Suggestion**
To enable users to skim their log file data, an additional window button could be added in the Channels tab. This would open up a view that has similarities to the Numeric view. However, instead of presenting a single sample of the selected channels, it would present multiple samples in a table view. 

I've illustrated the idea in the below picture:
![asammdf_buslogging_preview](https://user-images.githubusercontent.com/26184427/57448163-000cb780-7259-11e9-9567-68767fef7892.png)

**Comments**
1) Ideally, the user could select a start/end time for the preview - but a simpler indexing method could also be fine (e.g. show 1st 1000 rows, 2nd 1000 rows or something similar). 
2) Ideally, over time, a filter option could be added. This is probably for a later stage, but the idea would be that a user could e.g. add filters to show only specific frames with IDs or data bytes they're interested in
3) The functionality could be used for physical values as well - but here the plot functionality provides a lot of good functionality for analyzing the data. Hence I think a bus logging variant could be a good 1st step (the button could then be grayed out when the file is not of the buslogging type)

Happy to hear your thoughts on this - we think it would be a great addition :-) 

Martin

**Comment by danielhrisca** [comment]
Hello Martin,

I think this would be more suited to the _CAN logging_ tab

**Comment by MatinF** [comment]
Hi Daniel,

I see what you mean. My thinking had been that the "CAN logging" tab was in practice a "DBC conversion" tab. I've added below a few pros/cons of each placement from my view:

**CAN logging tab**
Pros: 
1) There's a logical link to the DBC conversion, assuming the csv preview is only for raw bus logging data
2) The tab is already grayed out for physical values
3) Since bus logging is perhaps not used by all, it makes sense to put it at the end 

Cons:
1) The csv preview would probably be used in similar scenarios as when users plot data or use the current numeric view - as such, it may be more logically placed in the Channels tab
2) Further, over time it could be that the preview functionality could also be useful for physical values - to allow users to visualize e.g. 3 signals in each their column next to a timestamp
3) By using the Channels view, the csv preview could be linked to the left-side hierarchy tree, allowing users to specify what specific channels/channel groups they want to plot. It's particularly relevant in cases with multiple bus channels (e.g. 2 x CAN). Adding similar functionality in the CAN logging tab would potentially require a duplication of the Channels hierarchy tree. Doing so in the current layout may be a bit difficult

Overall, I think both solutions can work - happy to hear your thoughts on the above.

Martin

**Comment by MatinF** [comment]
Hi again Daniel,

I've played around with the preview in dev version 5.7.8 - a few comments:

**Comments**
1) I really like how you implemented it so the tabular display can be used for both raw bus logging data and physical values seamlessly. In particular, it's possible to plot physical values across various channel groups which I think is awesome - great work!

2) The current methodology works great in my view for files up to ~10 MB, where the load time is <5 seconds on my PC, which I think is very impressive. E.g. 240,000+ rows (~8 MB) in ~3 seconds. 

**Further potential improvements**

**1) Partial loading:** I believe you've tested as well with the 50 MB MDF example (1.5 million rows). Here, the loading time is ~20 seconds on my PC. I think this is still a very good performance, though users new to this might think that the button is not working at first. 

An improvement for a future version could be to e.g. max load the first 100,000 rows - and then allow the user to load further rows by e.g. selecting a start/end timestamp. The benefit would be that it would always be a lightning fast preview. The challenge might be that doing this requires a more custom approach vs. the methods you're able to utilize now. If it adds significant complexity, I think the current version is already a very strong feature.

**2) Basic statistics:** When previewing a data set, some of the typical questions that might arise would be: A) Total #rows in the data set, B) Start date & timestamp (from file header), 3) Total file duration in eg HH:MM:SS.ttt. Perhaps this info could be displayed below the tabular window to provide users with a quick overview of the data.

**3) Filters:** If the method under the hood is based on a pandas dataframe put into a QTreeWidget, then perhaps it would be possible to apply standard pandas filters on the underlying dataframe, then re-load the updated dataframe into QTreeWidget. Perhaps that methodology could be used to allow a single filter field for users to add a filter string that could be utilized to filter the pandas. However, it could be that this is far more difficult to set up than it seems. Anyway, just a thought. The use case would probably typically be for users to get a quick view of a specific ID e.g. (so the filter string would in pseudo terms be "CAN_DataFrame.ID == CF00400").


The above are purely to be seen as inputs - I think the current version is really great, much appreciated to have this as part of the GUI!

Best,
Martin

**Comment by MatinF** [comment]
By the way, one other small reflection when working with both raw/physical data:

I think in most cases, it would be more intuitive to have the default Channels view be the "Internal file structure" - rather than the the "Natural sort". Minor detail, but just wanted to share this input.

Martin

**Comment by danielhrisca** [comment]
> I think in most cases, it would be more intuitive to have the default Channels view be the "Internal file structure" - rather than the the "Natural sort". Minor detail, but just wanted to share this input.

The default view is remembered automatically.

**Comment by danielhrisca** [comment]
> **3) Filters:** If the method under the hood is based on a pandas dataframe put into a QTreeWidget, then perhaps it would be possible to apply standard pandas filters on the underlying dataframe, then re-load the updated dataframe into QTreeWidget. Perhaps that methodology could be used to allow a single filter field for users to add a filter string that could be utilized to filter the pandas. However, it could be that this is far more difficult to set up than it seems. Anyway, just a thought. The use case would probably typically be for users to get a quick view of a specific ID e.g. (so the filter string would in pseudo terms be "CAN_DataFrame.ID == CF00400").

Check out the new filtering in the development branch

![filter_tabular](https://user-images.githubusercontent.com/20952040/57605575-a6193400-756f-11e9-85e7-15843e5edeb2.gif)

**Comment by MatinF** [comment]
Hi Daniel, the gif looks awesome! I tried updating to the latest development, but it seems I'm not able to open the  GUI from the start menu as I usually am. I get the following error:

```
Traceback (most recent call last):
  File "c:\users\marti\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\Scripts\asammdf.exe\__main__.py", line 5, in <module>
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\asammdfgui.py", line 7, in <module>
    from asammdf.gui.widgets.main import MainWindow
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\main.py", line 18, in <module>
    from .file import FileWidget
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\file.py", line 28, in <module>
    from .tabular import Tabular
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\tabular.py", line 12, in <module>
    from .tabular_filter import TabularFilter
ModuleNotFoundError: No module named 'asammdf.gui.widgets.tabular_filter'
```

**Comment by danielhrisca** [comment]
I forgot to add the new files. Try again

**Comment by MatinF** [comment]
It loads now - strangely enough it seems the GUI loads in 30% of the usual start time, though might just be a coincidence. 

I think the way you've designed the filtering is perfect, really like it!

A few observations:
1) I tried to filter a raw data sample (attached) based on Timestamp, setting it to:

AND Timestamp > 10163

However, this results in below console error:

`asammdf.gui - ERROR - Failed to apply filter for tabular window
Traceback (most recent call last):
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\tabular.py", line 127, in apply_filters
    new_df = df.query(' '.join(filters))
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py", line 3088, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py", line 3203, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\eval.py", line 299, in eval
    ret = eng_inst.evaluate()
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\engines.py", line 76, in evaluate
    res = self._evaluate()
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\engines.py", line 123, in _evaluate
    return ne.evaluate(s, local_dict=scope, truediv=truediv)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\numexpr\necompiler.py", line 822, in evaluate
    zip(names, arguments)]
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\numexpr\necompiler.py", line 821, in <listcomp>
    signature = [(name, getType(arg)) for (name, arg) in
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\numexpr\necompiler.py", line 703, in getType
    raise ValueError("unknown type %s" % a.dtype.name)
ValueError: unknown type object`

2) When I tried to use a filter on a CAN ID, I also get an error:

AND CAN_DataFrame.ID == CFE1222

`Traceback (most recent call last):
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\tabular.py", line 127, in apply_filters
    new_df = df.query(' '.join(filters))
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py", line 3088, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py", line 3203, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\eval.py", line 294, in eval
    truediv=truediv)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 749, in __init__
    self.terms = self.parse()
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 766, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 331, in visit
    return visitor(node, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 337, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 331, in visit
    return visitor(node, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 340, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 331, in visit
    return visitor(node, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 666, in visit_Compare
    return self.visit(binop)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 331, in visit
    return visitor(node, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 435, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 374, in _maybe_transform_eq_ne
    right = self.visit(node.right, side='right')
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 331, in visit
    return visitor(node, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\expr.py", line 449, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\ops.py", line 64, in __init__
    self._value = self._resolve_name()
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\ops.py", line 81, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\pandas\core\computation\scope.py", line 194, in resolve
    raise compu.ops.UndefinedVariableError(key, is_local)
pandas.core.computation.ops.UndefinedVariableError: name 'CFE1222' is not defined`

I guess the second error might be because the underlying CAN ID data is in Decimal, while the Tabular display shows it in Hexadecimal?

Martin

**Comment by danielhrisca** [comment]
Now you can write the hex value ``0xCFE1222`` or the decimal value ``217977378``

**Comment by MatinF** [comment]
Thanks Daniel! 

I tested it just now and the ID is now possible to filter via the above. 

Quick observations:
1) I think it makes sense that filtering is by default based on decimal values since this is a functionality that works also for physical values. For the case of raw bus logging data where the CAN ID is e.g. in HEX, maybe it would be possible via hover info to indicate something ala: "Note: Hexadecimal values should be added with 0x in front" when the mouser hovers the value field. Not critical, though.

2) When the data is filtered, the tabular display shows it as decimal form (both the CAN ID and CAN DataBytes). Again, this is probably specific to the bus logging scenario, but if possible I think it would be ideal if the filtered version is kept in hex for these columns. 

Again, this is an awesome functionality - I'm already using the tabular display heavily in doing some basic analyses of the data.

**Comment by danielhrisca** [comment]
@MatinF 
I've added validators for the target values and also a display for the pandas query used to filter the data

**Comment by MatinF** [comment]
Hi Daniel, it works great!

Minor observations:
1) When I try to filter e.g. a CAN ID, I choose the ID from the dropdown and try to select the "==" field. Doing so, however, yields a warning message that the ID requires an integer target value. 

Perhaps the warnings should only come once the user tries to apply a filter - to avoid early warnings that may be redundant.

2) Further, for the CAN ID I'm actually able to use the HEX value directly (e.g. 4EF0006), which I think is quite intuitive and nice. I also like that the query console below provides details on the decimal value corresponding to this. However, in this case in particular, I think the warning in 1) should only come when trying to apply the filter - and the text should probably be changed to also indicate that a hex value is accepted.

3) I'm not able to filter based on the Timestamp still, though I'm no longer getting the error message from before.

Great with the change so that the displayed filtered data looks like the unfiltered data!

**Comment by danielhrisca** [comment]
1. fixed
2. ``7DF`` will be replaced in the target input box with ``0x7DF``
3.  the name was colliding with https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html

**Comment by MatinF** [comment]
Really cool with the auto addition of 0x in front of HEX, good call. I tested around with multiple filters and I think it's excellent! 

A few final thoughts on this:

1) It might be useful to see the implicit parentheses in the more complex filter queries in the query window below - see e.g. the attached example where it can be a bit difficult to identify what the order of operations is: 

![Filters2](https://user-images.githubusercontent.com/26184427/57622659-657ce300-758e-11e9-86ec-854f52182876.PNG)

2) For the CAN_DataFrame.DataBytes, I'm having a bit of trouble filtering. I've tried both including/excluding spaces between the data bytes, but it seems the filter is not being applied when I e.g. set the DataBytes equal to a specific 8 data bytes string.

3) For the DataBytes special case, one final filtering mechanism that would be useful would be masking. A "simple" implementation of this could be to enable masking at the 4 bit level by e.g. using the current operator system and then replacing "masked" parts of the data bytes with stars as below:

![FilterMasking](https://user-images.githubusercontent.com/26184427/57623652-7b8ba300-7590-11e9-8b7b-6563690a2c6d.PNG)

The advantage would be that users could look for specific data values without having to convert the data first. For e.g. OBD2 data, it would also allow a user to filter out specific PIDs. In the more extreme case, an alternative masking would be to allow for bit level masking.

However, in regards to this third point it might be too specific to the bus logging case - so up to you if you think it's worth the effort to include. I think the current functionality is extremely useful already.

Martin

**Comment by MatinF** [comment]
A minor visual detail might also be to make the query window a bit smaller in height as it seems to be 1 line only.

**Comment by danielhrisca** [comment]
> 2\. For the DataBytes special case, one final filtering mechanism that would be useful would be masking. A "simple" implementation of this could be to enable masking at the 4 bit level by e.g. using the current operator system and then replacing "masked" parts of the data bytes with stars as below:

I don't want things to get to complex. We'll see if it is worth implementing

**Comment by MatinF** [comment]
I think that's 100% fair - in that case, I think the only pending thing would be in regards to being able to filter based on the current operators on the DataBytes. Maybe it's just that I'm using an inaccurate syntax for the value field currently.

**Comment by MatinF** [comment]
Hi Daniel,

Just a quick FYI: 

I tested the latest development version. It seems the Tabular display load time increased from ~20 seconds to ~80 seconds on my PC for a 50 MB file. Not sure what causes this. 

Once loaded, the file works without issues. I think this started maybe after the "tabular window improvements" commit, but not 100% sure. 

I like the new info tab btw, looks good :-)

**Comment by danielhrisca** [comment]
The slowdown is caused by the column sorting

![image](https://user-images.githubusercontent.com/20952040/57674128-fb644c80-7626-11e9-97c7-24ddff72a0be.png)

**Comment by MatinF** [comment]
Hi Daniel,

Thanks for the update, appreciated. 

Looking at the data before/after the addition of the column sorting, I'm not immediately able to see a difference. The previous data already looked sorted to me based on the timestamp - but maybe that's by coincidence?

Looking at it again, I guess the change is the addition of the possibility to sort by a specific column? I think this is a nice feature, though perhaps it's possible to set it up so that the sorting is not done by default on a new load - but only done if the user chooses so after the data has been loaded. Assuming the data is by default sorted by the timestamp, I think that would be the preferred sorting in most cases - and here the previous speed advantage would probably be preferable. But again, I may be missing something.

Best,
Martin

**Comment by danielhrisca** [comment]
I've added a new checkbox to manually control sorting. By default sorting will be disabled to improve initial loading speed. 

Sorting allows you to sort using any column

**Comment by MatinF** [comment]
Thanks Daniel, I think this works nicely as a solution for the speed.

**Comment by danielhrisca** [comment]
@MatinF 
I've pushed a workaround for filtering bytearray columns.

**Comment by MatinF** [comment]
Fantastic work Daniel! The new data bytes filter works great. We're already using the tabular view heavily in our team - really appreciate all the great design solutions on e.g. the filters and query window you made. I'm closing this issue now.
