### ISSUE TITLE
pandas DataFrame to Signal

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#184]
Hallo danielhrisca,

I like to export a pandas DataFrame in to mf4-file. Currently I create over a for loop a list of Signal objects and save this to an mf4-File. I was wondering if it might possible to create a Signal object from a complete DataFrame?

  Signal(samples=df, timestamps=df.iloc[:, 0], name=df.keys(),unit='')

**Comment by danielhrisca** [comment]
Check _append_ documentation https://asammdf.readthedocs.io/en/master/api.html#mdf4. You can append the dataframe directly

```python
mdf = MDF()
mdf.append(df)
```

**Comment by Lama09** [comment]
Many thanks for pointing to the documentation. I have not found this before.
