### ISSUE TITLE
Wrong master channel values / data type

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#185]
Hi Daniel,

I found out an issue regarding my master channels in a measurement where they all have wrong values. After investigation, I was able to find a workaround but not the proper fix. Probably you can help with this. The workaround was to simply comment out [line 771 in blocks/mdf_v4.py](https://github.com/danielhrisca/asammdf/blob/fbc85328c0c8df5abd86ccf045fc921fe91e748e/asammdf/blocks/mdf_v4.py#L771).

Thanks, Julien

**Comment by danielhrisca** [comment]
Hello Julien,

can you send a scrambled file?

**Comment by JulienGrv** [comment]
I will see if I can do that. Never tried so far. I will let you know. In the meantime, I sent you a screenshot from MDFValidator.

**Comment by danielhrisca** [comment]
This is really straight forward 

![scramble](https://user-images.githubusercontent.com/20952040/57544142-26b51600-735f-11e9-9921-63b2cf0987c0.gif)

**Comment by JulienGrv** [comment]
To answer your email: the line you linked is regarding ChannelArrayBlock but I don't see the link with this issue since it only concerns the master channels. To my understanding, the reading of the master channel values is affected because we _overwrite_ the channel.dtype_fmt at [line 771 in mdf_v4.py](https://github.com/danielhrisca/asammdf/blob/fbc85328c0c8df5abd86ccf045fc921fe91e748e/asammdf/blocks/mdf_v4.py#L771).

PS: no problem with the scramble usage, just my measurement is really big. What if I just filter my channel and then scramble, would that be enough for you to debug?

**Comment by JulienGrv** [comment]
One more information: the issue came with [this commit](https://github.com/danielhrisca/asammdf/commit/39af3713cc0a10c0619f50155875343beab44bab) from release [4.7.7](https://github.com/danielhrisca/asammdf/compare/4.7.6...4.7.7) and is still present in the development branch.

**Comment by danielhrisca** [comment]
> PS: no problem with the scramble usage, just my measurement is really big. What if I just filter my channel and then scramble, would that be enough for you to debug?

The idea is to have the original internal file structure. If you filter using _asammdf_ then this information is lost.



> One more information: the issue came with [this commit](https://github.com/danielhrisca/asammdf/commit/39af3713cc0a10c0619f50155875343beab44bab) from release [4.7.7](https://github.com/danielhrisca/asammdf/compare/4.7.6...4.7.7) and is still present in the development branch.

As the commit message states, this is meant to improve the performance of structure channels: if the structure can be parsed directly using numpy (it has only standard size types, non overlapping, no virtual  channels) then it can be read directly from the raw data.

**Comment by danielhrisca** [comment]
> PS: no problem with the scramble usage, just my measurement is really big. What if I just filter my channel and then scramble, would that be enough for you to debug?

I can give you access to my google drive to upload the file if you are able to do so.

**Comment by danielhrisca** [comment]
@JulienGrv 
any progress?

**Comment by JulienGrv** [comment]
Hi Daniel,

In order to share a measurement with you, I will need to change something regarding the scramble method because it does not scramble attachment
I was working on other topics recently and I also discover another issue with a measurement where I have the values of a signal that are wrong, not sure if this is related to this issue though.

**Comment by JulienGrv** [comment]
Issue is fixed. I'm closing the ticket. Thanks Daniel
