### ISSUE TITLE
MATLAB export - observations/minor bugs

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#186]
Hi Daniel,

We've worked a bit more with the various export options. 

I've added some observations/suggestions on the MATLAB export (see attached bus logging sample file for replication):
[7F34B296_00000009_00000008.zip](https://github.com/danielhrisca/asammdf/files/3170150/7F34B296_00000009_00000008.zip)

**Version:** **5.8.0 development**
**Type:** GUI

**Observations & Suggestions**
**1) Flickering dialog box:** 
When exporting a raw bus logging file using default settings, it seems to create the file correctly - but after creating the file there is for a period a series of very fast dialog boxes for the "Export measurements" that "flicker". The console doesn't provide any warnings and after a minute or two it disappears. However, until then it blocks use of the GUI 

**2) Single Time Base error:** 
Exporting to e.g. Mat 4 with "Single Time Base" enabled leads to a NoneType error; the error includes the below 

```
   raise NotImplementedError('Can''t write data type: '+str(tp))
NotImplementedError: Cant write data type: <class 'numpy.uint32'>
```

**3) Bus logging timestamp array vs. struct:** 
When loading a bus logging file in the asammdf GUI, the Channels tab displays a timestamp together with the other channels as in below screen:
![pasted_4](https://user-images.githubusercontent.com/26184427/57585613-ba671d80-74ea-11e9-83e7-2ebec1bf579c.png)

However, when exporting to MATLAB, the structure is as below:
![pasted_5](https://user-images.githubusercontent.com/26184427/57585619-ce128400-74ea-11e9-912f-26b705e25b23.png)

I believe this is working as intended and is due to the basic structure of a raw bus logging file, in which the timestamp figures as a master channel on the same level as the overall CAN_DataFrame channel, while e.g. ID, DataBytes etc. figure on a sub level to the CAN_DataFrame channel. However, it would probably be very helpful for end users in MATLAB working with such a raw export if the timestamp could be part of the struct, rather than a separate array. That way, filters applied to the struct array directly result in a corresponding time series.

Hope above make sense, else let me know.

Best,
Martin

**Comment by danielhrisca** [comment]
1. fixed in development
2. what are the versions of the following libs: numpy, hdf5storage?

**Comment by danielhrisca** [comment]
2. I was able to replicate the error. I think this requires raising an issue in https://github.com/frejanordsiek/hdf5storage

**Comment by MatinF** [comment]
Thanks for the update on this Daniel! 

Regarding the hdf5storage issue, I'd like to help raise it - though I'm not sure I'll be able to provide the correct description for Freja. If you think it's helpful I can try and provide an end user perspective of what I observe and then see if it's enough for her. 

Martin

**Comment by MatinF** [comment]
Hi Daniel, regarding the Mat7.3 export I suggest we close this issue as well - I'll do so later today.

I verified that this is only a problem for the bus logging format, not the converted data. 

Similar to the "Single time base" CSV suggestion in the other issue, a consideration might be to gray out/remove the Mat 7.3 export option for bus logging data. I think it's more reasonable at this stage than fixing the hdf5storage issue - and by not making it an option for bus logging data, no confusion will arise for end users. But 100% your call.
