### ISSUE TITLE
MDF.Select function is too slow

### ISSUE THREAD

**Issue by rahulparmar21** [danielhrisca/asammdf#187]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._
I am using this line of code to read from my MF4 file and convert it to a dataframe.
df = MDF.select(df, channels = fl, dataframe = False)

I am passing fl as channels argument - it is a list containg 548 channel names.

Expected output:
Each channel name will be a column of date frame. 

But the code df = MDF.select(df, channels = fl, dataframe = False) is taking hours to fetch data from just one MF4 file.

If I use vector tools to perform the same operation; one file takes approximately 3 minutes for 1 GB file

**Comment by danielhrisca** [comment]
Hello @rahulparmar21 

this looks interesting. 

The best way to see what can be improved is if you could send the file. You can scrmable it first to anonymize the data.

What asammdf version do you use?

**Comment by rahulparmar21** [comment]
Hello @danielhrisca 

I am using asammdf-5.2.0. 

I am not exactly sure, if I can share the data as it belongs to my organization. But here is what I am trying to do:

1. Reading the file (df = MDF(my_file))

2. finding which signals are available in the imported file (This step is super fast): 

signal_list = []
for items in some_text_file:
  y = MDF.whereis(df, items)
     if y:
	signal_list.append(items)

3. Once I know what signals are available in my file, I am creating a dataframe containing all the signals:

df = MDF.select(df, channels = signal_list, dataframe = True)

but this step is very very slow.

4. My next step would be to store the data frame as a pickle file.

**Comment by danielhrisca** [comment]
I think you have multiple sampling rates that effectively increase the processing time since the dataframe will have the union of all individual time stamps.

How long does it take you call  _select_ with _dataframe=False_?

**Comment by rahulparmar21** [comment]
when I select Dataframe = False. Even that takes > 2 hour (I do not have exact time), but it is faster than Dataframe = True.

Also,
How do I make sure that all the data points I receive is 1 row per second (so a sampling rate of 1s)?

**Comment by danielhrisca** [comment]
First update to the latest development branch code

``pip install -U https://github.com/danielhrisca/asammdf/archive/development.zip``

I think this will improve the performance if you have unsorted CAN bus logging

**Comment by rahulparmar21** [comment]
This will improve the performance for dataframe=False? or dataframe=True? or both?

**Comment by danielhrisca** [comment]
For both if my assumption is correct.

It would really help if you could provide a scrambled file https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.scramble

**Comment by rahulparmar21** [comment]
The dataframe=False version is fast now (Just took two minutes). Also, just so you know the step "2. finding which signals are available in the imported file (This step is super fast):" took one minute now. so basically the dateframe=False version just took one minute or so.

The dataframe=true version throws this error: "ValueError: Length of passed values is 0, index implies 20018539" . It took 8 minutes to get to this error. so seem like the speed has improved for this version too.

I will work on getting the file to you.

**Comment by danielhrisca** [comment]
Thank you. Please share the error traceback to see were the exception is raised

**Comment by rahulparmar21** [comment]
Traceback (most recent call last):
  File "MF4_To_Pickle.py", line 131, in <module>
    func_concat(concat_list,unique_dates,path,dest)
  File "MF4_To_Pickle.py", line 98, in func_concat
    df = MDF.select(df, channels = fl, dataframe = True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\asammdf\mdf.py", line 3026, in select
    df[channel_name] = pd.Series(sig.samples, index=master)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 262, in __init__
    .format(val=len(data), ind=len(index)))
ValueError: Length of passed values is 0, index implies 20018539

**Comment by danielhrisca** [comment]
I think one of your signals has no samples. Using _to_dataframe_ is better and gives you more option (see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.to_dataframe)

```python
mdf = MDF(file_name)
# you can set the raster to 1s 
df = mdf.to_dataframe(channels=signal_list, raster=1)
```



> df = MDF.select(df, channels = fl, dataframe = True)

This is a bit unusual to call the class method using the instance. Why not ``df.select(channels=flm dataframe=True)``?

**Comment by rahulparmar21** [comment]
The to_dataframe works great but I get lots of warnings. I am not sure why 

![image](https://user-images.githubusercontent.com/49165778/57805849-ab62b400-7712-11e9-979c-19e8a0606e5e.png)

**Comment by danielhrisca** [comment]
Most of the messages are related to attachments that refer to external files (the CAN DBC files). The channel group metadata warning looks unnecessary (the xml tags might be correct in the context of CAN bus logging), but can be ignored as well.

**Comment by rahulparmar21** [comment]
Also,
some columns have junk values (For Ex: Instead of Integer values it has b'Minimum DC link ', b'PASSIVE', b'INIT', b'OPERATION', b'Not active')

**Comment by danielhrisca** [comment]
> Also,
> some columns have junk values (For Ex: Instead of Integer values it has b'Minimum DC link ', b'PASSIVE', b'INIT', b'OPERATION', b'Not active')

Those channels have a value to text conversion rule. This is valid data



> The to_dataframe works great

You should use this method from now on since I plan to remove the _dataframe_ argument from the _select_ method

**Comment by rahulparmar21** [comment]
What if I need to ignore value to text conversion rule? are you planning on adding a parameter?

**Comment by danielhrisca** [comment]
> What if I need to ignore value to text conversion rule? are you planning on adding a parameter?

This has come up freqently. I will think of a solution.

**Comment by danielhrisca** [comment]
How is your execution timing now?

**Comment by rahulparmar21** [comment]
About execution timing:

MF4 file size = 1.46 GB
Converted CSV file size = 21.4 MB (6448 rows and 362 columns (signals))

Total Run Time :  2 minutes 10 seconds (Improvement of zillion times)

2. finding which signals are available in the imported file (This step got slower and took 1 minute 5 seconds):
signal_list = []
  for items in some_text_file:
    y = MDF.whereis(df, items)
    if y:
      signal_list.append(items)

3. Once I know what signals are available in my file, I am creating a dataframe containing all the signals:

df = mdf.to_dataframe(channels=fl, raster=1)

This step took 1 minutes 05 seconds.

Overall I am very happy with the performance and will start using it frequently

**Comment by rahulparmar21** [comment]
After running on multiple files, I am observing that the last second's data is not extracted. (What I mean is using your library has one less row of data compared to vector tools) - This issue needs to be addressed.

Also,
when would the new version roll out as I am using the development fix right now.

**Comment by danielhrisca** [comment]
@wangdino @rahulparmar21 @legout

I've added the argument _ignore_value2text_conversions_ to the _to_dataframe_ method (https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.to_dataframe)

**Comment by rahulparmar21** [comment]
@danielhrisca 

Awesome. when would the new version rollout? (the one with all the fixes and this new option)

**Comment by danielhrisca** [comment]
https://pypi.org/project/asammdf/
https://github.com/danielhrisca/asammdf/releases
