### ISSUE TITLE
cannot name groups with MDF.append() function

### ISSUE THREAD

**Issue by MaximeLecuona** [danielhrisca/asammdf#188]
# Python version
python=3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
os=Windows-7-6.1.7601-SP1
numpy=1.15.1
asammdf=4.1.6

# Description

My problem is not so much a bug as it is a feature request (or clarification on an existing feature that I might have missed).

I used asammdf to  create an environment that reads in various formats, provides data processing features to my users, and allows them to save their results in a variety of formats. The most commonly used of those formats is mdf4. 
In order to create the group structure of my mdf4 file, I use MDF.append(). And for the most part, it does exactly what I need it to do. The only problem, (and it is actually becoming a real problem downstream) is that I haven't found a way to name the groups created. 
Is there a parameter I can use in the append function call to give a name to the groups being created? Or a way to name them after the fact?

Thanks in advance for any help you may provide.

**Comment by danielhrisca** [comment]
Hello Maxime,

first I think you should upgrade to the latest release. 

With the current release you can set the channel group and data group comments:

```python
mdf.append(sigs)

last_group = mdf.groups[-1]

last_group.channel_group.comment = 'channel group comment'
last_group.data_group.comment = 'data group comment'

mdf.save(out_path)
```

**Comment by MaximeLecuona** [comment]
Hi Daniel,

Thanks a lot for getting back to me. I've followed your advice, and it is indeed useful. Is there a way to do something similar for the name of the group?

**Comment by danielhrisca** [comment]
The data group block does not have a _name_ link. You can only set the _comment_ using the snippet that I've posted.

For the channel group you can additionally set the acquisition name

```python
last_group.channel_group.acq_name = 'name'
```

![image](https://user-images.githubusercontent.com/20952040/57676710-d0c9c200-762d-11e9-8983-1b7aad5b4432.png)

**Comment by MaximeLecuona** [comment]
Thank you so much for your help. It's exactly what I needed
