### ISSUE TITLE
Plot Signals with strings

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#189]
Hello @danielhrisca,
is there a possibility to visualize measurement values of type byte in the plot (or raw values without channel conversion)? When Plotting signals with bytes I can the measurement points, but the change of values is only seen in the channel information field.
Furthermore a time sync betwen numeric window and plot would be nice, as it is with different plots.

Thanks, 
stlweb

**Comment by danielhrisca** [comment]
You can try the new tabular window available in the development branch (see https://github.com/danielhrisca/asammdf/issues/183)

**Comment by stlweb** [comment]
I've still tryed the tabulat window. But in combination with other signals (e.g. reaction/ DUT behaviour) it would be a nice and usefull feature to see different signal level.

**Comment by stlweb** [comment]
An option do deactivate the conversion / plot raw signals of single channels could also be a variant.

**Comment by danielhrisca** [comment]
> Furthermore a time sync betwen numeric window and plot would be nice, as it is with different plots.

This is now implemented in the development branch
