### ISSUE TITLE
Incorrect values in signal

### ISSUE THREAD

**Issue by fizcris** [danielhrisca/asammdf#190]
# Python version
```
('python=3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) '
 '[MSC v.1900 64 bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.15.4'
'asammdf=5.8.1
```

# Code 

  ## MDF version
  4.10

  ## Code snippet
  # FlexRay file
     
```
channelsToExtractFlexRay = [(None,0,1)]

with mdf.MDF(filepath,) as mdf_file:
    print(mdf_file.version)
    FlexRaySignals= mdf_file.filter(channelsToExtractFlexRay)
    pd = FlexRaySignals.to_dataframe()
pd
```
  
  ## Traceback
  No error
  
# Description

When the file is opened by any Vector viewer the channel data can be seen and plotted but when using the asammdf tool the values in this signal are not converted correctly. Instead of numerical values we have all the points cointaining the "Fault " string.

Scrambled file sent by email.

**Comment by fizcris** [comment]
Update. 
Basically is populating all the values of the signal for every timestamp with the value in text_1 in the reference block.

![image](https://user-images.githubusercontent.com/5770003/57927026-d2e98600-78a4-11e9-8b52-331628115e66.png)

Regards.

**Comment by danielhrisca** [comment]
Hello Christian,

thank you for the report. I'm working on a fix

**Comment by danielhrisca** [comment]
@fizcris 

please check using the latest code from the development branch

**Comment by fizcris** [comment]
@danielhrisca 

I can comfirm that the issue has been fix.

Thank you a lot for the so quick turnaround!
