### ISSUE TITLE
creating subplots after converting mdf to dataframe

### ISSUE THREAD

**Issue by msnir009** [danielhrisca/asammdf#192]
# Python version
3.7

Assamdf version: 5.2.0
Numpy version: 1.16.2
```
  
# Description
Plotting signal plots using subplots. 

_Please describe the issue here._
I converted the mdf file into a dataframe format using:
df = eff1.filter(to_keep).to_dataframe(time_as_date=True)

when I attempt to create subplots, the code runs but does not display the chart and simply results as '<matplotlib.axes._subplots.AxesSubplot at 0x264de6c2668>'

I have already tried changing the matplotlib backend to GtkAgg from TkAgg and it is still the same.  Hence how can I create subplots for the signals maybe without first converting it into a dataframe.

**Comment by danielhrisca** [comment]
Can share more of your code? 

I can't understand what you want to achieve using the pandas DataFrame

**Comment by msnir009** [comment]
I have a file in .DAT format and starting from this point, the code is as below:

f1 = r"<file directory>"
eff1 = MDF(f1)
to_keep = ['col1', 'col2','col3']

df = eff1.filter(to_keep).to_dataframe(time_as_date=True)
df['time'] = df.index #i do this because when i tried to plot using df.plot(df.index, col1) it returned keyerror

fig, axes = plt.subplots(1,2)
axes[0].plot(df['time'], df['col1'])
axes[1].plot(df['time'], df['col2'])

#this results as below
[<matplotlib.lines.Line2D at 0x264e510f5f8>]

**Comment by danielhrisca** [comment]
I have no experience with matplotlib.

Also you should update to the latest pypi release.

**Comment by msnir009** [comment]
okay I will do that. thanks for your response.

**Comment by stlweb** [comment]
Hello @msnir009, 

> df['time'] = df.index #i do this because when i tried to plot using df.plot(df.index, col1) it returned keyerror

You have to use df.plot(df.index.values, col1)

> 
> fig, axes = plt.subplots(1,2)
> axes[0].plot(df['time'], df['col1'])
> axes[1].plot(df['time'], df['col2'])
> 
> #this results as below
> [<matplotlib.lines.Line2D at 0x264e510f5f8>]

This is a normal behaviour of the plot function. If you use spyder as IDE, an new window should be opend in the background (with calling plt.subplots() a empty figure is created). 
As Workaround you could save the figure
`fig.savefig('figure_filename.svg`)

**Comment by danielhrisca** [comment]
I'll close this as it is not really the subject of _asammdf_
