### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'frame_by_id' by reading MF4 file with CAN log data

### ISSUE THREAD

**Issue by alho5** [danielhrisca/asammdf#194]
# Python version

> ('python=3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) \n'
>  '[Clang 6.0 (clang-600.0.57)]')
> 'os=Darwin-18.6.0-x86_64-i386-64bit'
> 'numpy=1.16.3'
> 'asammdf=5.8.3'

# Code 

  ## MDF version
  4.10

  ## Code snippet
```
file = r'./with_DBC_attachement.MF4'
with asammdf.MDF(file) as mdf_file:
    print(mdf_file.version)
    lst = list(mdf_file.attachments)
    nMO = mdf_file.get('iItfInput.n_mot')
    dbc = mdf_file.extract_attachment(index=2)
    nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", db=dbc, ignore_invalidation_bits=False)
```

  ## Traceback

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-13-ac33073c2154> in <module>
>       5     nMO = mdf_file.get('iItfInput.n_mot')
>       6     dbc = mdf_file.extract_attachment(index=2)
> ----> 7     nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", db=dbc, ignore_invalidation_bits=False)
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py in get_can_signal(self, name, database, db, ignore_invalidation_bits)
>    5006             message = db.frame_by_name(message_id)
>    5007         else:
> -> 5008             message = db.frame_by_id(message_id)
>    5009 
>    5010         for sig in message.signals:
> 
> AttributeError: 'tuple' object has no attribute 'frame_by_id'

# Description

Hi, I have a mf4 file measured with CANape version 16 and the CAN Buslog feature activated. The DBC file is attached to the mf4 file as 3rd attachment.
By opening the file I get the AttributeError message above. 

When I try to get_can_signal with the original DBC file I get another error and I am also not successful. Any ideas?

### code with DBC file loaded from file uses for the measurement
```
file = r'./with_DBC_attachement.MF4'
dbc_file = r'./dbc.dbc'
with asammdf.MDF(file) as mdf_file:
    nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", database=dbc_file, ignore_invalidation_bits=False)
```

> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-14-95c2f8cd852d> in <module>
>       2 dbc_file = r'./dbc.dbc'
>       3 with asammdf.MDF(file) as mdf_file:
> ----> 4     nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", database=dbc_file, ignore_invalidation_bits=False)
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py in get_can_signal(self, name, database, db, ignore_invalidation_bits)
>    4965                     db = self._external_dbc_cache[md5_sum]
>    4966                 else:
> -> 4967                     db = load_can_database(database, db_string)
>    4968                     if db is None:
>    4969                         raise MdfException('failed to load database')
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/asammdf/blocks/utils.py in load_can_database(file, contents)
>    1532                 contents,
>    1533                 import_type=import_type,
> -> 1534                 key="db",
>    1535             )
>    1536         except UnicodeDecodeError:
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/canmatrix/formats/dbc.py in load(f, **options)
>     942                         signal.attributes[define] = signal.attributes[define][1:-1]
>     943 
> --> 944     db.enum_attribs_to_values()
>     945     for frame in db.frames:
>     946         if "_FD" in frame.attributes.get("VFrameFormat", ""):
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/canmatrix/canmatrix.py in enum_attribs_to_values(self)
>    1981                 for frame in self.frames:
>    1982                     if define in frame.attributes:
> -> 1983                         frame.attributes[define] = self.frame_defines[define].values[int(frame.attributes[define])]
>    1984 
>    1985         for define in self.signal_defines:
> 
> IndexError: list index out of range

**Comment by danielhrisca** [comment]
First update canmatrix to version 0.8

**Comment by alho5** [comment]
Version 0.8 is installed

$ pip install canmatrix --upgrade
Requirement already up-to-date: canmatrix in /Users/alex/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages (0.8)

**Comment by danielhrisca** [comment]
Hello Alexander,

I've made some fixes in the release 5.9.0
Let me know if it fixes the error for you

**Comment by alho5** [comment]
Hi Daniel,
thanks for the quick response. When I read the DBC from the attachment directly the error message changed. 

### Python Version

> ('python=3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) \n'
>  '[Clang 6.0 (clang-600.0.57)]')
> 'os=Darwin-18.6.0-x86_64-i386-64bit'
> 'numpy=1.16.3'
> 'asammdf=5.9.0'
> 'canmatrix=0.8'

### Code
```Python
file = r'./with_DBC_attachement.MF4'
with asammdf.MDF(file) as mdf_file:
    print(mdf_file.version)
    lst = list(mdf_file.attachments)
    nMO = mdf_file.get('iItfInput.n_mot')
    dbc = mdf_file.extract_attachment(index=2)
    nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", db=dbc, ignore_invalidation_bits=False)
```

### Traceback

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-4-ac33073c2154> in <module>
>       5     nMO = mdf_file.get('iItfInput.n_mot')
>       6     dbc = mdf_file.extract_attachment(index=2)
> ----> 7     nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", db=dbc, ignore_invalidation_bits=False)
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py in get_can_signal(self, name, database, db, ignore_invalidation_bits)
>    5013             for msg in db:
>    5014                 for signal in msg:
> -> 5015                     if signal.name == name:
>    5016                         message = msg
>    5017 
> 
> AttributeError: 'int' object has no attribute 'name'


### Read DBC from file
When I read the DBC from file the error message stays the same.

### Code
```Python
file = r'./with_DBC_attachement.MF4'
dbc_file = r'./dbc.dbc'
with asammdf.MDF(file) as mdf_file:
    nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", database=dbc_file, ignore_invalidation_bits=False)
```

### Traceback

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-95c2f8cd852d> in <module>
      2 dbc_file = r'./dbc.dbc'
      3 with asammdf.MDF(file) as mdf_file:
----> 4     nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", database=dbc_file, ignore_invalidation_bits=False)

~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py in get_can_signal(self, name, database, db, ignore_invalidation_bits)
   4965                     db = self._external_dbc_cache[md5_sum]
   4966                 else:
-> 4967                     db = load_can_database(database, db_string)
   4968                     if db is None:
   4969                         raise MdfException('failed to load database')

~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/asammdf/blocks/utils.py in load_can_database(file, contents)
   1532                 contents,
   1533                 import_type=import_type,
-> 1534                 key="db",
   1535             )
   1536         except UnicodeDecodeError:

~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/canmatrix/formats/dbc.py in load(f, **options)
    942                         signal.attributes[define] = signal.attributes[define][1:-1]
    943 
--> 944     db.enum_attribs_to_values()
    945     for frame in db.frames:
    946         if "_FD" in frame.attributes.get("VFrameFormat", ""):

~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/canmatrix/canmatrix.py in enum_attribs_to_values(self)
   1981                 for frame in self.frames:
   1982                     if define in frame.attributes:
-> 1983                         frame.attributes[define] = self.frame_defines[define].values[int(frame.attributes[define])]
   1984 
   1985         for define in self.signal_defines:

IndexError: list index out of range

**Comment by danielhrisca** [comment]
Hello Alexander,

I see no reason for this error to appear. Can you send the DBC file?

**Comment by alho5** [comment]
Hi Daniel,
I really like to share this with you that we may find the problem, but this is a OEM DBC file which I can't publish on the internet. Is there any other way that I could provide more helpful information to you?
Best regards,
Alex

**Comment by danielhrisca** [comment]
I see. I would double check that canmatrix 0.8 is properly installed

**Comment by alho5** [comment]
When I print the canmatrix.__version__ I see canmatrix version = 0.8.
Is there anything else I can check?

**Comment by danielhrisca** [comment]
Hello Alexander,

I've just now realized that you were using not calling the function with the proper arguments: the _db_ argument must be a database object object loaded by canmatrix

```python
try:
    from canmatrix.dbc import load as dbc_load
except ModuleNotFoundError:
    from canmatrix.formats.dbc import load as dbc_load
from io import BytesIO

file = r'./with_DBC_attachement.MF4'
with asammdf.MDF(file) as mdf_file:
    print(mdf_file.version)
    lst = list(mdf_file.attachments)
    nMO = mdf_file.get('iItfInput.n_mot')
    dbc_contents, path_name = mdf_file.extract_attachment(index=2)
    dbc_contents = BytesIO(dbc_contents)
    dbc = dbc_load(
        dbc_contents,
        import_type='dbc',
        key="db",
    )
    nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", db=dbc, ignore_invalidation_bits=False)
```

**Comment by alho5** [comment]
Hi Daniel,
by running this code I get another error message.

> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-4-f828ab6c268c> in <module>
>       8     dbc = dbc_load(dbc_contents,
>       9                     import_type='dbc',
> ---> 10                     key="db")
>      11 
>      12     nMO_CAN = mdf_file.get_can_signal(name="AVL_RPM_ENG_CRSH", db=dbc, ignore_invalidation_bits=False)
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/canmatrix/formats/dbc.py in load(f, **options)
>     942                         signal.attributes[define] = signal.attributes[define][1:-1]
>     943 
> --> 944     db.enum_attribs_to_values()
>     945     for frame in db.frames:
>     946         if "_FD" in frame.attributes.get("VFrameFormat", ""):
> 
> ~/Documents/code/enviroments/asammdf-test/lib/python3.7/site-packages/canmatrix/canmatrix.py in enum_attribs_to_values(self)
>    1981                 for frame in self.frames:
>    1982                     if define in frame.attributes:
> -> 1983                         frame.attributes[define] = self.frame_defines[define].values[int(frame.attributes[define])]
>    1984 
>    1985         for define in self.signal_defines:
> 
> IndexError: list index out of range

**Comment by danielhrisca** [comment]
@alho5 
any updates?

**Comment by alho5** [comment]
Hi Daniel,
I am still not able to open the file with the attached dbc.
Best regards,
Alex

**Comment by danielhrisca** [comment]
@alho5 does it work with asammdf 5.17.3?

**Comment by danielhrisca** [comment]
Please reopen if you still have problems with the latest release
