### ISSUE TITLE
IndexError: list index out of range by reading mf4 file with attachements

### ISSUE THREAD

**Issue by alho5** [danielhrisca/asammdf#195]
# Python version
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.4'
'asammdf=5.8.4'

# Code 

  ## MDF version
  4.10 

  ## Code snippet
```Python
file = r'./raw/with_DBC_attachement.MF4'
with asammdf.MDF(file) as mdf_file:
    print(mdf_file.version)
    lst = list(mdf_file.attachments)
    nMO = mdf_file.get('iItfInput.n_mot')
    dbc = mdf_file.extract_attachment(index=2)
```
  
  ## Traceback

>  Traceback (most recent call last):
>   File ".\read_mf4_with_CANBusLog.py", line 25, in <module>
>     with asammdf.MDF(file) as mdf_file:
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\mdf.py", line 126, in __init__
>     self._mdf = MDF4(name, **kwargs)
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\mdf_v4.py", line 248, in __init__
>     self._read(mapped=True)
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\mdf_v4.py", line 462, in _read
>     self._process_can_logging()
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\mdf_v4.py", line 888, in _process_can_logging
>     dbc = load_can_database(at_name, attachment)
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\utils.py", line 1534, in load_can_database
>     key="db",
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\canmatrix\formats\dbc.py", line 944, in load
>     db.enum_attribs_to_values()
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\canmatrix\canmatrix.py", line 1983, in enum_attribs_to_values
>     frame.attributes[define] = self.frame_defines[define].values[int(frame.attributes[define])]
> IndexError: list index out of range

  
# Description

When I open the file "with_DBC_attachement.MF4" on my windows machine I get the error above. Opening the same file on my Mac is working fine. Opening other MDF files version 3 or version 4 without CANBusLogs and attachements is working fine also on my windows machine. Very strange to me. Have you any idea where to find the reason for that behavior? Thanks, and sorry for my many questions. I am new to python and programming in general.

**Comment by danielhrisca** [comment]
Hello Alexander, 

this looks like a canmatrix error. Make sure you have properly installed version 0.8 on both systems.

**Comment by alho5** [comment]
Hi Daniel,
also on my Windows machine I am using the canmatrix version 0.8. I have ASAMMDF lib installed in a virtual environment togehter with a ipython kernel... but not much more.

Tomorow I will try on a windows machine from one of my co-workers. 
Maybe I messed up some path variabels during the last upgrade to Python 3.7. I had some trouble during this update.

> ('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
>  '(AMD64)]')
> 'os=Windows-10-10.0.16299-SP0'
> 'numpy=1.16.4'
> 'asammdf=5.9.0'
> 'canmatrix=0.8'

### Code
```Python 
file = r'./MDF_import/raw/with_DBC_attachement.MF4'
with asammdf.MDF(file) as mdf_file:
    print(mdf_file.version)
    lst = list(mdf_file.attachments)
    nMO = mdf_file.get('iItfInput.n_mot')
    dbc = mdf_file.extract_attachment(index=2)
```
### Traceback

> Traceback (most recent call last):
>   File "c:/UserData/f31298/code/utils/MDF_import/read_mf4_with_CANBusLog.py", line 32, in <module>
>     with asammdf.MDF(file) as mdf_file:
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\mdf.py", line 126, in __init__
>     self._mdf = MDF4(name, **kwargs)
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\mdf_v4.py", line 248, in __init__
>     self._read(mapped=True)
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\mdf_v4.py", line 462, in _read
>     self._process_can_logging()
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\mdf_v4.py", line 888, in _process_can_logging
>     dbc = load_can_database(at_name, attachment)
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\asammdf\blocks\utils.py", line 1534, in load_can_database
>     key="db",
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\canmatrix\formats\dbc.py", line 944, in load
>     db.enum_attribs_to_values()
>   File "C:\UserData\f31298\code\enviroments\congdat-proc\lib\site-packages\canmatrix\canmatrix.py", line 1983, in enum_attribs_to_values
>     frame.attributes[define] = self.frame_defines[define].values[int(frame.attributes[define])]
> IndexError: list index out of range

**Comment by danielhrisca** [comment]
@alho5 
please try the latest development branch code it should not fail if canmatrix can't parse the database

**Comment by danielhrisca** [comment]
@alho5 can you check with the latest development branch code?

**Comment by alho5** [comment]
Hi Daniel,  I just execute the code snippet from above with your latest release and dosen't crash anymore! I will try to extract signals from the file on the weekend again.
Thanks,
Alex 

```
('python=3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) \n'
 '[Clang 6.0 (clang-600.0.57)]')
'python=/Users/alex/Documents/code/python/mdf-test/venv/bin/python'
os=Darwin-19.0.0-x86_64-i386-64bit
numpy=1.17.4
asammdf=5.14.5
4.10
[Finished in 51.254s]
```
