### ISSUE TITLE
Enhancement: "Finalize" bus logging data

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#196]
# Context
The MDF4.11 "bus logging" format supports the concept of "finalized" vs "unfinalized" data. 

The "unfinalized" concept allows for e.g. CAN loggers to efficiently record CAN data in the MDF format - without having to go through the slightly time-consuming step of "finalizing" each file. Finalization is relatively light and simple to do on the PC - whereas it greatly increases the embedded device complexity, e.g. when it comes to performance, enabling devices to power off safely or transferring files securely over-the-air.

# Enhancement suggestion
It would be fantastic if asammdf could **natively load unfinalized MDF4 files** - and finalize them during the loading time. An unfinalized file would take a bit longer to load then - but it would be significantly simpler, than forcing the user to finalize the data via a separate PC tool.

Ideally, the user would hardly notice if they were loading a finalized or unfinalized MDF4 in the GUI/API.

# Sample data
Below is a zip containing a sample of unfinalized MDF4 data - as well as the corresponding finalized version of same data:

[sample_data_unfinalized_finalized.zip](https://github.com/danielhrisca/asammdf/files/3244698/sample_data_unfinalized_finalized.zip)

# Implementation outline
The following steps would be involved in loading unfinalized data:

1) Allow unfinalized files to pass through the initial check
2) Parse unfinalized flags (Last DT block size, CG block cycle counters and number of bytes in VLSD CG blocks in our case)
3) Find the last DT block (which is also the only DT block in our sample, though perhaps not in general) and determine the size from either the end of file or beginning of next block.
4) Determine the number of cycles and the total size of the VLSD CG blocks. Iterate over the data in the DT block and keep track of how many records for each CG block are encountered, as well as how many bytes of VLSD data are stored for each VLSD CG block
5) Clear the flags in the ID block

We're of course happy to provide any details and clarification required. I hope you would find this relevant to add as well Daniel. This addition would make asammdf an extremely powerful tool for handling CAN 'bus logging' MDF data and I believe this would help expand the scope of tools which asammdf would natively support.

Thanks again for all your great work on the tool!

Best,
Martin

**Comment by danielhrisca** [comment]
Hello Martin,

this feature might take a lot of effort to implement, and at least for my usage it will have little to no benefit. As such, this will be a side topic and we'll see if I get the time to tackle it.

**Comment by danielhrisca** [comment]
I think we can close this now
