### ISSUE TITLE
Return group channel_group.comment when iterating over groups

### ISSUE THREAD

**Issue by cristi-neagu** [danielhrisca/asammdf#197]
Hello,

I'm trying to get the groups as pandas dataframes using `iter_groups()`, and associate them with their comment, which would indicate (in my case anyways) the raster of the group. I don't see an obvious way of doing that. I can iterate over the `group` member of the `MDF` object, but the `group` class itself has no way of returning a pandas dataframe.

The only way i can think of doing this is:

```
groups = {group.channel_group.comment : group_frame
          for group, group_frame in zip(mdfFile.groups, mdfFile.iter_groups())}
```

Is there a better way of doing this?

Thank you.

**Comment by danielhrisca** [comment]
You can use [get_group](https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.get_group)

```python
groups = {}
for i, group in enumerate(mdf.groups):
    groups[group.channel_group.comment] = mdf.get_group(i)
```
It's almost the same thing as your snippet.

**Comment by cristi-neagu** [comment]
Thank you for the reply. There doesn't seem to be a performance difference between the two. Closing this as it's not an actual issue.
