### ISSUE TITLE
Improvement to hdf5 export

### ISSUE THREAD

**Issue by cristi-neagu** [danielhrisca/asammdf#199]
Hello,

The mdf files i'm using have a text block under each channel group. This is the MDF Validator path:
`test.dat\Header Block\Data Group 1\Channel Group 1\Text Block`
Can the contents of this text block (key `tx_data`) be stored in the hdf5 file as attributes for the channel groups? Obviously, this makes sense only if `single_time_base=False`.

Thank you.

**Comment by cristi-neagu** [comment]
As further info, the text block in question is already present in the `MDF` object here:
`mdfFile.groups[0].channel_group.comment`

**Comment by danielhrisca** [comment]
Hello Cristi,

have a try with the development branch code

**Comment by cristi-neagu** [comment]
That works perfectly. Thank you.
