### ISSUE TITLE
Exporting to HDF5 when channel name contains '/' has undesired side effects

### ISSUE THREAD

**Issue by cristi-neagu** [danielhrisca/asammdf#202]
Hello,

As the title says, exporting to HDF5 channels that have '/' in the name will lead to weird behaviour. In my case, what happened was that h5py dropped everything after the '/', leading to duplicate dataset names, which threw an error. Perhaps there should be a check for this case. I added a simple replace after line https://github.com/danielhrisca/asammdf/blob/685fd99a8393f25be5392364513b36bd81b09e19/asammdf/mdf.py#L1207

`name = name.replace('/', '_')`

**Comment by danielhrisca** [comment]
@cristi-neagu 

did you try the new development branch code?

**Comment by cristi-neagu** [comment]
Hello,

Sorry for taking so long to respond to this. Yes, it's working as intended.

Thank you.
