### ISSUE TITLE
Exception when saving mf4

### ISSUE THREAD

**Issue by Nimi42** [danielhrisca/asammdf#203]
Hi there,

I'm on asammdf 5.9.2 and when I try to use the save function I "**ocasionally**" get exceptions.
 What I mean by that is, that all of my mdf3 files will work just fine and even some of my mf4 files do not cause any Problems but sometimes it will return with an exception during the writing process. So just loading and again Dumping the file as follows:

```Python
with MDF(data) as mdf:
     path = os.path.join(dst, str(filenumber))
     mdf.save(path, overwrite=True)
```

will cause an exception:

```Python
Traceback (most recent call last):
  File "C:/Users/mousavin/PycharmProjects/NOx/src/asd.py", line 16, in <module>
    mdf.save(path, overwrite=True)
  File "C:\Users\mousavin\AppData\Local\Continuum\miniconda3\envs\NOx\lib\site-packages\asammdf\blocks\mdf_v4.py", line 5713, in save
    write(bytes(block))
  File "C:\Users\mousavin\AppData\Local\Continuum\miniconda3\envs\NOx\lib\site-packages\asammdf\blocks\v4_blocks.py", line 1428, in __bytes__
    result = pack(fmt, *[getattr(self, key) for key in keys])
  File "C:\Users\mousavin\AppData\Local\Continuum\miniconda3\envs\NOx\lib\site-packages\asammdf\blocks\v4_blocks.py", line 1428, in <listcomp>
    result = pack(fmt, *[getattr(self, key) for key in keys])
AttributeError: 'ChannelArrayBlock' object has no attribute 'axis_conversion_0'
```

It seems like in depth knowledge about the MDF datastructure is needed to fix this bug,
so it's unlikely that I will fix the bug myself.

However, creating a scrambled Version of the original did work and trying to save the scrambled Version will create the same bug, so I can send you that file if need be.

cheers,
Nima

**Comment by danielhrisca** [comment]
Hello Nimi,

please send the scrambled file. It will help debugging a lot.

**Comment by danielhrisca** [comment]
@Nimi42 

the new code in the development branch should fix the issue

**Comment by danielhrisca** [comment]
@Nimi42 
any updates?

**Comment by Nimi42** [comment]
Ohh sry... works fine. I totally forgot about the issue.
