### ISSUE TITLE
HDF5 export fails

### ISSUE THREAD

**Issue by cristi-neagu** [danielhrisca/asammdf#204]
Hello,

HDF5 export fails here:
https://github.com/danielhrisca/asammdf/blob/a77964392170e83817f55ad6a28997048b673ce1/asammdf/mdf.py#L1197

With the following error:

```
 mdfFile.export(fmt='hdf5', filename=dstName, compression='gzip', use_display_names=False)
  File "E:\Programming\conda\envs\work\lib\site-packages\asammdf\mdf.py", line 1198, in export
    group.attrs[item] = self.header[item]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "E:\Programming\conda\envs\work\lib\site-packages\h5py\_hl\attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "E:\Programming\conda\envs\work\lib\site-packages\h5py\_hl\attrs.py", line 200, in create
    attr.write(data, mtype=htype2)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5a.pyx", line 383, in h5py.h5a.AttrID.write
  File "h5py\_proxy.pyx", line 63, in h5py._proxy.attr_rw
  File "h5py\defs.pyx", line 3405, in h5py.defs.H5Tconvert
  File "h5py\_conv.pyx", line 449, in h5py._conv.str2vlen
  File "h5py\_conv.pyx", line 113, in h5py._conv.generic_converter
  File "h5py\_conv.pyx", line 259, in h5py._conv.conv_str2vlen
ValueError: VLEN strings do not support embedded NULLs
```

Value contained in `self.header[item]` is ` 1U19`. `item` is `subject`. This is the raw data contained in the `subject` field, as reported by MDF Validator:
```
0x00 0x31 0x55 0x31 
0x39 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
0x00 0x00 0x00 0x00
```

I suspect the error is caused by that initial `0x00`, but i can't be sure.

**Comment by cristi-neagu** [comment]
I've had this error with a different file. Same thing, the `subject` header contains a `0x00`. Maybe replace it with a space? Not sure if that's the most appropriate response.

**Comment by cristi-neagu** [comment]
Replacing the line with `group.attrs[item] = str(self.header[item]).replace(chr(0), ' ')` seems to solve it for me.

**Comment by danielhrisca** [comment]
@cristi-neagu 

actually there was a typo when processing the header items and the \x00 bytes were not stripped correctly

**Comment by cristi-neagu** [comment]
Hello,

Same error. Doesn't seem to work.

**Comment by cristi-neagu** [comment]
`mdfFile.header.subject` looks like "ABC\x00DEF". The \x00 in there doesn't get stripped.

**Comment by danielhrisca** [comment]
@cristi-neagu 
try the new development branch code

**Comment by cristi-neagu** [comment]
Just to be clear, when i made the previous comment, i did try with the development version. 864454dc65c32cfe678d77e1f3235f5c14d12e56 doesn't fix the issue. It removes the nulls from the end of the string, but not the ones inside the string.

**Comment by danielhrisca** [comment]
> Just to be clear, when i made the previous comment, i did try with the development version. [864454d](https://github.com/danielhrisca/asammdf/commit/864454dc65c32cfe678d77e1f3235f5c14d12e56) doesn't fix the issue. It removes the nulls from the end of the string, but not the ones inside the string.

I know that only the start and end chars were stripped  previously, but the latest commit removes also embedded nulls

**Comment by cristi-neagu** [comment]
Just checked, it doesn't. I think you may have missed some files in this commit d7c0431d77c41fc047c6f6c2add4ae4950469dea

**Comment by danielhrisca** [comment]
🤦‍♂ I've added the modified file in the new commit

**Comment by cristi-neagu** [comment]
That makes more sense :) However, you might want to make the same change to https://github.com/danielhrisca/asammdf/blob/996f1b4eecfe82401d1dd86a46893fc6183683ea/asammdf/mdf.py#L1197

**Comment by cristi-neagu** [comment]
This still fails with an error in line 1197:

`TypeError: a bytes-like object is required, not 'str'`

That's why my fix was `group.attrs[item] = str(self.header[item]).replace(chr(0), ' ')` You have to convert the header from a bytes object to a string to do a replace. Unless bytes have a replace method of their own.

**Comment by danielhrisca** [comment]
@cristi-neagu 
please try the new release version

**Comment by danielhrisca** [comment]
please re-open if you still have problems
