### ISSUE TITLE
ValueError: seek out of range by reading mf4 file

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#205]
# Python version
_Please run the following snippet and write the output here_
('python=3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 '
 '64 bit (AMD64)]')

'os=Windows-10-10.0.17134-SP0'
'numpy=1.14.0'
'asammdf=5.7.0'

# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
from asammdf import MDF
from asammdf.blocks.utils import MdfException

try:

   mdf_data = MDF('my_file.mf4')
  
except MdfException as Mdf_err:
 sys.stdout.write('Error in mdf4 routine.')

  ## Traceback
  File "\Tools\anaconda3\lib\site-packages\asammdf\mdf.py", line 124, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "\Tools\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 248, in __init__
    self._read(mapped=True)
  File "\Tools\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 651, in _read
    event = EventBlock(address=addr, stream=stream, mapped=mapped)
  File "\Tools\anaconda3\lib\site-packages\asammdf\blocks\v4_blocks.py", line 3862, in __init__
    stream.seek(address)
ValueError: seek out of range

  
# Description

Hello Daniel,
i try to read a mf4-file (7 GB) and come up with the error above. I can open the file within ETAS MDA V7.2

**Comment by danielhrisca** [comment]
Hello @Lama09 ,

can you try with the latest development branch code?

**Comment by danielhrisca** [comment]
@Lama09 

can you open your file with MDFValidator to see if it is corrupted? This might explain the error

**Comment by danielhrisca** [comment]
@Lama09 
any upates?

**Comment by Lama09** [comment]
Hello Daniel, I'm very sorry for my late reply. It took a while to get the MDF Validator on my computer. Which Information do you need now? When I read the file (took about 2 hours), it says two errors occurred. See attached snapshot.

![image](https://user-images.githubusercontent.com/48772414/61349328-f8bee700-a863-11e9-992c-42b4052d3aa9.png)

**Comment by danielhrisca** [comment]
Well there is a problem with the file. Just as the error in mdfvaludator says, a link is corrupted and points to an address higher than the file size.

**Comment by Lama09** [comment]
Ok, this means your used measurement software is producing invalid mf4-Files? So fare I didn't had problems to import mf4-Files using asammdf. I will now struggle with my workflow.

**Comment by Lama09** [comment]
Sorry wanted to say, that our measurement software (ETAS INCA) is producing invalid mf4-Files?

**Comment by danielhrisca** [comment]
@Lama09 

please try the new development branch code

**Comment by danielhrisca** [comment]
> Sorry wanted to say, that our measurement software (ETAS INCA) is producing invalid mf4-Files?

Yes, that event block address is not valid.

**Comment by Lama09** [comment]
I was wondering if it will not be possible to check for validity and prevent your code from crashing?

**Comment by danielhrisca** [comment]
> I was wondering if it will not be possible to check for validity and prevent your code from crashing?

This the point fo the latest commits in the development branch. Give it a try

**Comment by Lama09** [comment]
Hello Daniel,
I am very sorry for my late response. I am very new to GitHuab and actually don't know how to get the development branch?

I tried the asammdf version (5.10.3) and still got this issue.

`anaconda3\lib\site-packages\asammdf\blocks\v4_blocks.py", line 3999, in __init__
    stream.seek(address)
ValueError: seek out of range`

**Comment by danielhrisca** [comment]
``pipi install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by Lama09** [comment]
Hello Daniel,
I installed the version 5.11.0.dev0 and got now the following TraceMessage:

asammdf - WARNING - Event address 1C0000020 is outside the file size 7516192768
Traceback (most recent call last):
  File "..\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-22f4399e0045>", line 4, in <module>
    temp = test.to_dataframe(channels=labels, raster=step_size,time_from_zero=True)
  File "..\anaconda3\lib\site-packages\asammdf\mdf.py", line 3432, in to_dataframe
    mdf = self.filter(channels)
  File "..\anaconda3\lib\site-packages\asammdf\mdf.py", line 1681, in filter
    for idx, fragment in enumerate(data):
  File "..\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1315, in _load_data

**Comment by danielhrisca** [comment]
I don't think it's the complete error traceback

**Comment by Lama09** [comment]
Hello Daniel,
sorry you are right. This error will not be catched by MdfException so far.

asammdf - WARNING - Event address 1C0000020 is outside the file size 7516192768
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "..\pycharm\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "..\pycharm\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "..\pycharm\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "..\pycharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/test.py", line 533, in <module>
    test(iniFile)
  File "E:/test.py", line 144, in test
    time_from_zero=True)  # export mdf-data to pandas data frame, define labels and step size
  File "..\anaconda3\lib\site-packages\asammdf\mdf.py", line 3432, in to_dataframe
    mdf = self.filter(channels)
  File "..\anaconda3\lib\site-packages\asammdf\mdf.py", line 1681, in filter
    for idx, fragment in enumerate(data):
  File "..\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1315, in _load_data
    new_data = decompress(new_data, 0, size)
zlib.error: Error -3 while decompressing data: incorrect header check

**Comment by danielhrisca** [comment]
@Lama09 
can you check again with the new release 5.11.0?

**Comment by Lama09** [comment]
Hello danielhrisca,
I checked it with version 5.13.1

_asammdf_ - WARNING - Event address 1C0000020 is outside the file size 7516192768
Traceback (most recent call last):
  File "..\post.py", line 533, in <module>
    post(iniFile)
  File "..\post.py", line 144, in post
    time_from_zero=True)  # export mdf-data to pandas data frame, define labels and step size
  File "..\site-packages\asammdf\mdf.py", line 3482, in to_dataframe
    only_basenames=only_basenames,
  File "..\site-packages\asammdf\mdf.py", line 3569, in to_dataframe
    for signal in signals
  File "..\site-packages\asammdf\mdf.py", line 3569, in <listcomp>
    for signal in signals
  File "..\site-packages\asammdf\signal.py", line 764, in interp
    s = np.interp(new_timestamps, self.timestamps, self.samples)
  File "<__array_function__ internals>", line 6, in interp
  File "..\site-packages\numpy\lib\function_base.py", line 1412, in interp
    return interp_func(x, xp, fp, left, right)
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (819934017,) and data type float64_

**Comment by danielhrisca** [comment]
Hello @Lama09 
at this point you have to consider how to handle your data. 

By default the data frame will contain the union of all time stamps found in the file (819_934_017 unique values in your case) and this can lead to huge memory requirements. 

To avoid memory errors you need to use the _raster_ argument

**Comment by Lama09** [comment]
Hello @danielhrisca,

I allready use the raster argument for the data export to pandas dataframe. This is how my code looks like.

`step_size = 1.e-5`
`data_frame = mdf_file.to_dataframe(channels=labels, raster=step_size, time_from_zero=True)`

**Comment by danielhrisca** [comment]
You are using a 10us raster. Try with a higher value

**Comment by Lama09** [comment]
Trying with a raster of 1.e-1s the import was working well. Unfortunately I will miss some of the accuracies of the measurement results. I investigate some vibrations with higher frequencies.

What I do wonder, why it is possible to read the complete mdf file but get memory issues when the data will be written to pandas data frame? Is there an opportunity to catch this numpy memor error an throw an MdfException?

**Comment by danielhrisca** [comment]
Hello @Lama09,

We do not load the complete file in memory. Also usually the data is stored with raw values in the mdf and the extracted data și converted with the associated channel conversion to get the physical values. This means an uint8 raw value can be expanded to a float64

**Comment by danielhrisca** [comment]
Some tips
use the _channels_ argument to extract only the relevant signals
use the _reduce_memory_usage_ argument

**Comment by danielhrisca** [comment]
Please reopen if necessary
