### ISSUE TITLE
Conbine different mdf to new one mdf

### ISSUE THREAD

**Issue by v162** [danielhrisca/asammdf#208]
# Python version
Python 3. 6 | asammdf 5.10.2 | MDF4

After review the method from asammdf, I have some question here.

Thanks for a fantastic tool!

I'm trying to use asammdf to concatenate multiple MDF files into a single file for analysis  conversion.
To concatenate the files, I use the following code:
path_1 = '2019-03-02_11-55_0145_01.mf4'
path_2 = '2019-03-02_11-55_0145_02.mf4'
path = [path_1, path_2]
mdf_obj = MDF.concatenate(path,time_from_zero=False)
mdf_obj.save('concentanate.mf4')

And here is the error after run:
       "asammdf.blocks.utils.MdfException: internal structure of file 1 is different"

Question:
        Why occur the problem? And how I resolve it?

Happy to hear your thoughts on this Daniel!

Best,
v162

**Comment by danielhrisca** [comment]
Hello @v162 ,

concatenate needs files with identical internal structure. Check out the channels in the channel groups, they should have the same names
![Screenshot from 2019-07-13 13-12-45](https://user-images.githubusercontent.com/20952040/61170296-fdd41b80-a56f-11e9-9e3b-02120c8ee528.png)

**Comment by v162** [comment]
Hello daniel:
         The GUI tool of check channels you show me just now, and where I can find, because I had check channel by debugging code that have some complecate. And the issue, as you say, it’s different for group in two mf4.But here some else method to resolve this problem?
Thank you.


发自我的iPhone

------------------ Original ------------------

**Comment by danielhrisca** [comment]
The GUI is included in the asammdf package.

```python
from asammdf.gui.asammdfgui import main
main()
```

**Comment by danielhrisca** [comment]
https://asammdf.readthedocs.io/en/master/gui.html

**Comment by v162** [comment]
Ok, thank you very much indeed.


发自我的iPhone

------------------ Original ------------------
