### ISSUE TITLE
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by mocher72** [danielhrisca/asammdf#209]
# Python version
_Please run the following snippet and write the output here_
 '[MSC v.1900 64 bit (AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.16.4'
'asammdf=5.10.2'
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
 
  from asammdf import MDF, MDF2
  mdf = MDF(x,'full','4.00')
  ## Traceback

  File "C:/Users/Sean/Documents/Python Scripts/asammdfecxp.py", line 33, in <module>
    mdf = MDF(x,'full','4.00')

TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given
  
# Description

Problem with the latest version of asammdf

If I use the earlier vesion installing this

conda install -c conda-forge/label/cf201901 asammdf

The code then works fine.

**Comment by danielhrisca** [comment]
Hello @mocher72 

your previous version must have been an old 4.x.y release.

The 5.x.y release code does not use the _memory_ argument anymore. Check out the latest docs asammdf.readthedocs.io/en/latest/api.html#mdf

**Comment by danielhrisca** [comment]
This might help https://github.com/danielhrisca/asammdf/releases/tag/5.0.0

**Comment by mocher72** [comment]
Ah, thanks for the quick feedback.
Still new to Python so deciphering error messages is still a challenge
Tried without the extra arguments and its working fine with the latest version. :)
