### ISSUE TITLE
Dask DataFrame export

### ISSUE THREAD

**Issue by nightm4re94** [danielhrisca/asammdf#211]
Hi and thank you for this useful tool.
Have you considered implementing dask DataFrame export analogous to the to_pandas()-method?
I quickly ran into memory issues with larger datasets processed with pandas, and I would like to skip the transformation step from pandas to dask.

**Comment by danielhrisca** [comment]
Hello Matthias,

I've never used dask. If you can give some pointers/ snippets we can get something working.

**Comment by nightm4re94** [comment]
The great thing about Dask is that it mimics the pandas API. Dask DataFrames are basically just lazy parallelized pandas DataFrames as shown in the figure below:
![dask vs. pandas dataframe](https://docs.dask.org/en/latest/_images/dask-dataframe.svg)

However, thinking about how the lazy DataFrame initialization with Dask works, I'm unsure whether it is even possible to initialize an empty DataFrame and then feed data into it. The intended usage is, as far as I've understood, to initialize DataFrames from existing data sources such as pandas DataFrames, HDF5 tables, csv, parquet,.... 
If Dask DataFrames cannot be filled with data after initialization, a simple wrapper of _from_pandas_ should suffice:

```python
from asammdf import MDF
from dask import dataframe as dd

pandas_df = MDF('myMeasureData.mdf').to_dataframe()
df = dd.from_pandas(pandas_df, npartitions=4)
```

I should've given this more thought before posting the request, but maybe one of you clever collaborators out there knows how to fulfill my request with more than just a wrapper.

**Comment by danielhrisca** [comment]
@nightm4re94 
please try the new [_iter_to_dataframe_ ](https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.iter_to_dataframe)method available in the development branch code. You can set the target dataframe size (the default is 200MB).

**Comment by nightm4re94** [comment]
I love it, will definitely try that out!

**Comment by danielhrisca** [comment]
@nightm4re94 does it work ?

**Comment by nightm4re94** [comment]
I'll be back at work next week and can check then. I had been assigned to some other tasks recently, but now I'm coming back to this. Thanks for providing support :)

**Comment by nightm4re94** [comment]
This resolves the issue I had.
Thank you!

**Comment by danielhrisca** [comment]
@nightm4re94 could you share the dask export code?

**Comment by MatinF** [comment]
We would be interested in the code as well if you’re able to share it

**Comment by nightm4re94** [comment]
Just to be clear: I did not actually manage to export the DataFrame chunks into dask dataframes since ```iter_to_dataframe``` already provides the functionality I was hoping for: lazily evaluating portions of the mdf file with DataFrames that fit in memory. Yet I should mention that iterating over all these chunks actually is veeeery slow. 
In fact, I don't even think  that there is a non-overblown approach to converting batches of pandas DataFrames into a single Dask DataFrame. 
As [this comment](https://github.com/dask/dask/issues/1651#issuecomment-456265273) points out, you would probably have to temporarily store your chunks on the hard drive to concatenate them into a dask DataFrame at a later point. 
All in all, I would say that all the conversion shenanigans are not worth it if you want a Dask DataFrame. Only an approach building the DataFrame from scratch , similarly to the [csv reader method](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_csv), would be feasible.

All in all, I came to the conclusion that it is best to process your MDF data not as DataFrames, but to keep your workflows as atomic as possible, processing the signals you need one at a time. Conversion to DataFrames was, in my case, not even needed in the end since I could just work with individual Signals.

**Comment by MatinF** [comment]
Thanks for the update on this. 

To explain our use case a bit more, we're looking to achieve the following:
1) We have large amounts of - potentially large - MDF4 log files stored on an S3 bucket
2) We wish to process a list of files in a simple and efficient way, while managing RAM
3) To do so, our intention was to use `dask` to e.g. load 20 x 50 MB MDF4 files while controlling RAM. The purpose would be to process the data on-the-fly for e.g. displaying in dashboards
4) To link up with S3, we intended to use `s3fs`, which also works well with dask

We did some tests today and found that below code does indeed work - and it's in principle what we're looking for:

```
import dask.bag as db
import s3fs
from asammdf import MDF

# local example MDF4 (works)
iterator = MDF("data.mf4").iter_to_dataframe()
b = db.from_sequence(iterator)

# s3fs example MDF4 (works)
fs = s3fs.S3FileSystem(anon=True)
with fs.open("general-editor-schemas/data.mf4", "rb") as f:
    iterator = MDF(f).iter_to_dataframe(f, chunk_ram_size=2097152)
    b = db.from_sequence(iterator)
```
However, the above seems to be very slow (~20s on my PC). It's a 10 MB file, which we're - for illustration - handling with ~2 MB RAM if I understand the `iter_to_dataframe` API correctly. 

I think we'll look a bit further into the reason for the high time consumption on this. Appreciate your inputs on this.
