### ISSUE TITLE
pyqtgraph version incompatibility

### ISSUE THREAD

**Issue by nightm4re94** [danielhrisca/asammdf#212]
# Python version
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit '                                           '(Intel)]') 
'os=Windows-10-10.0.17763-SP0'
'numpy=1.16.4'
'asammdf=5.10.3'

# Code 

  ## MDF version
4.10
  
# Description

When installing the latest version of pyqtgraph (0.10.0) via pip, I cannot use the plot feature anymore, neither in code nor in the standalone GUI. I always get [this message](https://github.com/danielhrisca/asammdf/blob/e731c077cbb20740339cb2452ce565d6947be76a/asammdf/gui/widgets/plot.py#L36), telling me I have an "old" version of pyqtgraph.

**Comment by danielhrisca** [comment]
Hello Matthias,

version 0.10.0 was released a long time ago (November 2016). You need to install the latest version from github

``pip install https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip``

**Comment by nightm4re94** [comment]
Thanks for pointing that out! 
Strange thing there hasn't been an official release of pyqtgraph in years, even though it is still in development...
