### ISSUE TITLE
GUI subplot

### ISSUE THREAD

**Issue by borisw37** [danielhrisca/asammdf#214]
'python=3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.17.0'
'asammdf=5.10.3'

In the GUI application Settings -> Sub-Plots -> Enable seems to have no effect.
With sub-plots enabled or disabled I get the same behavior:
Dragging a channel onto the field, selecting "plot", creates a new plot, plot title increments by one (Plot1, Plot2, ...). Previous plot disappears.

**Comment by danielhrisca** [comment]
Did you re-open the file or restart the app?

**Comment by borisw37** [comment]
Thank you for the quick reply. Your suggestion worked.
It seems that the "sub-plot" setting is only read at the startup of the application?
If it loads with "enabled" it stays enabled, if it loads disabled it is disabled till the app is restarted.

**Comment by danielhrisca** [comment]
When you open the sub-plot option is read at that time and it does not change for that particular opened file, even if you toggle the option in the menu.
