### ISSUE TITLE
Question\Enhancement request: Column wise concatenation of channels based on master channels. 

### ISSUE THREAD

**Issue by JuanInATrillion** [danielhrisca/asammdf#215]
Hi, I have many channels that have the same time master channel but output as separate groups. 

I'd like to perform column wise concatenation on these groups as well as groups that might be slightly offset in sample rate. If this is not enhancement that you believe is appropriate to build into this module do you have suggestions on how to perform this? Ultimately I want to create separate .mat files outputs based on a single mdf/mf4. 
Thank You. 
JR.

**Comment by danielhrisca** [comment]
You may want to use to_dataframe and provide the master channel as raster

**Comment by JuanInATrillion** [comment]
Thanks @danielhrisca . 
So I the groups are slightly off, a couple of samples. 
I currently have 2 groups that are slightly offset by a few cycles. I unfortunately cannot provide you a snippet of the data because is proprietary. 
Here is what I'm attempting: 
`t=pd.merge(mdfobj.get_group(101),mdfobj.get_group(102),left_on='time',right_on='time', how='outer',copy=False)
t.loc[:,byte_clnnames] = t.loc[:,byte_clnnames].applymap(lambda x:x.decode('utf-8')`
I'm trying this because doing raster is causing some ffill removing important values. 
When I perform the applymap the values are not being kept in place. I want to convert channels of datatype |S32,|S24, |S# to string so that I can then resample using pandas and perform forward fill. 
Any help is appreciate it, been stuck on this for a while.

**Comment by danielhrisca** [comment]
By default when interpolation non-float channels the previous value is repeated. Is this what you need?

**Comment by JuanInATrillion** [comment]
Hey Daniel, my apologies for the very late reply, yes this is exactly what I need. I have in some cases enumerations in HEX format that don't make sense to linear interpolate, likewise with Boolean type variables. It's essentially the bbfill OR ffill method in Pandas or neighrest neighbor interpolation type. It would be cool if you could write a method in the class to allow you to do this or implicitly do it for you based on data type.
