### ISSUE TITLE
Pressure test

### ISSUE THREAD

**Issue by ahao1995** [danielhrisca/asammdf#216]
I want to know something about pressure test. This Gui can analyse how many data and how size of file.Thank you.

**Comment by danielhrisca** [comment]
I don't understand what you want.

**Comment by ahao1995** [comment]
What is the maximum size of the file?1GB？or more？Do you have test this?

**Comment by danielhrisca** [comment]
Mdf versions 2 and 3 use 32 bit links so the fike size is limited to ~4GB. 
Mdf version 4 (.mf4) uses 64 links so the file size is virtually unlimited.

**Comment by ahao1995** [comment]
Thank you
