### ISSUE TITLE
Question: How to set channel group names

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#217]
Hello @danielhrisca,
is it possible to set names of group channels with appending of a group of signals to a mdf object?

Kind regards,
stlweb

**Comment by danielhrisca** [comment]
Hello @stlweb 

what mdf version ?

**Comment by stlweb** [comment]
Hi @danielhrisca , 
version 4.10 (4.11) would be good.

**Comment by danielhrisca** [comment]
```python
from asammdf import MDF, Signal

mdf = MDF()

mdf.append(Signal([], [], name='rahat'))

mdf.groups[-1].channel_group.acq_name = 'fancy name'
```
