### ISSUE TITLE
How do you give units?

### ISSUE THREAD

**Issue by Temp-tqtq** [danielhrisca/asammdf#221]
I read mdf and got the name (speed) and value.
How do you give units?
※py version3.6
for example km/h

**Comment by Temp-tqtq** [comment]
For example (km/h)

**Comment by danielhrisca** [comment]
```python
speed = mdf.get(speed_channel_name)
print(speed.unit)
```

**Comment by Temp-tqtq** [comment]
unit is blank
(unit = '')
I've decided on the unit
Problems during processing?

**Comment by danielhrisca** [comment]
The unit is not set in the file for this particular channel you are using. There is no error during processing
