### ISSUE TITLE
name and display name conflicts

### ISSUE THREAD

**Issue by BruceGrace** [danielhrisca/asammdf#222]
when parsing two CAN signal have same display name but different name. One display name will correspond to two different signal. using mdf.get() to get two signal will get the same results.
Can i just disable using display name to parse signal, will it cause some side-effect?
thx

**Comment by danielhrisca** [comment]
Have a look at the _group_ and _index_ arguments of the _get_ method. https://asammdf.readthedocs.io/en/latest/api.html

**Comment by danielhrisca** [comment]
@BruceGrace do you still have questions related to this issue?
