### ISSUE TITLE
pase inmemory dat error--split_data should be integer not numpy64

### ISSUE THREAD

**Issue by BruceGrace** [danielhrisca/asammdf#223]
when parsing a large inmemory data, an error --split_size should be integer not numpy64 occured. Can i just add a line in mdf_v3 line273 to make split_size integral?
thx~

**Comment by danielhrisca** [comment]
I'll push some fixes to the development branch next week

**Comment by danielhrisca** [comment]
@BruceGrace 
did you try the development branch code?

**Comment by BruceGrace** [comment]
hello,
      have you parsed EATS INCA temp dat file before?



在 2019-09-18 20:02:27，"Daniel Hrisca" <notifications@github.com> 写道：


Closed #223 via 80d855a.
