### ISSUE TITLE
error manipulating plot

### ISSUE THREAD

**Issue by troyness** [danielhrisca/asammdf#224]
python=3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 '
 'bit (AMD64)

os=Windows-10-10.0.14393-SP0

numpy=1.17.0
asammdf=5.10.3

Issue: An error message pops every time you click in the plot window.

![asammdf_error](https://user-images.githubusercontent.com/13243670/63705682-ae823b80-c7fb-11e9-9acd-c84e4749b15e.JPG)

**Comment by danielhrisca** [comment]
The latest development branch code should have this fixed

**Comment by danielhrisca** [comment]
please re-open if you still have problems
