### ISSUE TITLE
How offsets are calculated in record/vals - Offset values greater than signal_data length

### ISSUE THREAD

**Issue by SzczepekJakub** [danielhrisca/asammdf#227]
# Python version
```
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.16.4'
'asammdf=5.10.1'
```

  ## MDF version
  4.10

  ## Code snippet
                   for index, offset in enumerate(vals):
                 
                        (str_size,) = UINT32_uf(signal_data, offset)
                        offset += 4
                        values.append(signal_data[offset: offset + str_size])
  
  ## Traceback
```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\__main__.py", line 6, in <module>
    result = main()
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\read_mdf_data.py", line 102, in main
    main_inst.run()
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\mainLogic.py", line 113, in run
    self._main()
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\mainLogic.py", line 110, in _main
    self._read_files()
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\mainLogic.py", line 169, in _read_files
    mdf_pickle = self._read_mdf4(mdf_file, file_extension)
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\mainLogic.py", line 706, in _read_mdf4
    only_selected_buses=only_selected_buses)
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\extractPickleAll.py", line 158, in read_data
    kwargs.get('skip_data_bytes', False))
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\extractPickleAll.py", line 131, in _read_groups
    channels = self.mdf.select([(None, i, idx) for idx in idxs_to_process])
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\site-packages\asammdf\mdf.py", line 2865, in select
    ignore_invalidation_bits=True,
  File "D:\me2\mdf_extractor\src\aptiv\MDF_Extractor\site-packages\asammdf\blocks\mdf_v4.py", line 4601, in get
    (str_size,) = UINT32_uf(signal_data, offset)
struct.error: unpack_from requires a buffer of at least 4 bytes_
```
  
# Description

Due to signal structure change we have to remove some Ethernet frames and regenerate signal in new configuration and inject into MDF file. We are sure on 98% that binary payload of signal is correct. 
Source MDF - is extracted correctly, modyfied MDF crash on line:(str_size,) = UINT32_uf(signal_data, offset) (about 4593 line of code) due to len of signal_data is shorter that a few last offsets values in vals variable.

During investigation (basing of assumption that our injected payload is correct which we are pretty sure) we met that offsets in record variable doesn't refresh (even that signal is shorter 408 change to 402)

![Ticket](https://user-images.githubusercontent.com/47149212/63995698-c1498880-caf9-11e9-9666-731cccdc82c8.PNG)
Left screen source mdf right, after modification.

So my questions is:
1) Basing on what do you calculate offsets in vals ?
2) What we should modify into MDF to correct offset calculations, maybe we miss something. 

During investigation I will brake loop with problem when offset value exceed len of signal_data after that I have mismatch between timestamp length and data bytes so I trim timestamp length to data bytes length and inject that prepared payload to our decoder after that I received correct signal structure, but dec values isn't correct (which is probably expected) - so that allows me to think that injected binary payload is correct and problems are in offset calculation.

If you can help with that or have some ideas to solve this issue I will be grateful.
Due to policy I cannot share data with you :(.

**Comment by danielhrisca** [comment]
```python
# see size of each Ethernet frame
sizes = [len(frame) for frame in frames]

# the offsets will be the actual signal values
offsets = []
offset = 0
for size in sizes:
    offsets.append(offset)
    offset += size + 4

signal_data = []
# each frame bytes will be prepended by the size as UINT32
for size, frame in zip(sizes, frames):
    signal_data.append(struct.pack(f'<I{size}s', size, frame))
signal_data = b''.join(signal_data)
```

**Comment by SzczepekJakub** [comment]
Where is that located ?

**Comment by danielhrisca** [comment]
[Here](https://github.com/danielhrisca/asammdf/blob/development/asammdf/blocks/mdf_v4.py#L2981) it is optimized for speed for string channels, at the cost of wasted disk space. The code from the previous answer is not optimized for speed, and uses the minimal disk space

**Comment by SzczepekJakub** [comment]
Ok, thanks I will look what happened during offsets calculation, but do you have some idea (basing on attached screen) why last value in records is the same even that length of service change form 408 to 402 ?
![Ticket](https://user-images.githubusercontent.com/47149212/64091649-6e6a0e00-cd51-11e9-9782-8aab744c7119.PNG)

**Comment by danielhrisca** [comment]
What is the _record_ that you are printing?

From what I understood you modify the ethernet frame payload and try to update this in the MDF file on the channel's signal data (referenced by the _signal_data_addr_ field). Is this correct?

**Comment by SzczepekJakub** [comment]
It is correct,
in screen you have variable "record"
![image](https://user-images.githubusercontent.com/47149212/64149171-84e19980-ce25-11e9-9aa2-e8a844df0ab4.png)

From this variable you get the grp and values basing on parents.

```
                    if parent is not None:
                        if grp.record is None:
                            record = fromstring(data_bytes, dtype=dtypes)
                        else:
                            record = grp.record

                        vals = record[parent]
```
We suspect that in somehow in fromstring(data_bytes, dtype=dtypes) when eth data length change that operation returns the same last value 14566 in "record" (like you see on previous screen)

**Comment by danielhrisca** [comment]
The record should remain the same since your changes are only for the signal_data.

**Comment by SzczepekJakub** [comment]
Ok, so why last values in offset are gather than length of  signal_data and this for loop crash:
```
       for index, offset in enumerate(vals):
           (str_size,) = UINT32_uf(signal_data, offset)
```

![image](https://user-images.githubusercontent.com/47149212/64151082-ed327a00-ce29-11e9-8596-0f67fd4bfc75.png)

**Comment by danielhrisca** [comment]
Do you follow the steps:
1. update record bytes (this includes the new calculated offsets)
2. update referenced channel bytes (signal_data)
?

**Comment by SzczepekJakub** [comment]
What do you mean under the record bytes ?

**Comment by danielhrisca** [comment]
can you share a screenshot of the Ethernet.DataBytes channel done with MDFValidator ?

**Comment by SzczepekJakub** [comment]
Generally we need to know how values in vals variable are calculated, based on what ? All Ethernet headers on our side looks correct.

**Comment by SzczepekJakub** [comment]
![image](https://user-images.githubusercontent.com/47149212/64153663-992a9400-ce2f-11e9-9d0c-bb3a2a2146c6.png)

**Comment by danielhrisca** [comment]
It's really hard to modify your file. You have an unsorted data group (multiple channel groups in the same data group). The samples for each channel group are prepended by a record ID byte. 

The signal data referenced by Ethenet,DataBytes is one of the channel groups with no channels (for example channel group 8 in the screenshot). You have to modify the samples for this channel group inside the  data block referenced by the DataGroup. You additionally have to modify the samples for the channel group 7 (since you have lower cycles count by removing some frames, and also new offsets for the Ethenet.DataBytes).

**Comment by SzczepekJakub** [comment]
You probably mean offset in channels where we should have all correct (for eg. frame in channel 7 still exist but payload of that frame is shorter). We have problem with data_bytes offsets in eth frame data which are wrong calculated. 
Operation:
`(str_size,) = UINT32_uf(signal_data, offset)` returns ` struct.error: unpack_from requires a buffer of at least 4 bytes_` due to len(signal_data) > offset.
