### ISSUE TITLE
Proposition of default datetime modification

### ISSUE THREAD

**Issue by SzczepekJakub** [danielhrisca/asammdf#228]
# Python version
```
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.16.4'
'asammdf=5.10.1'
pprint("python=" + sys.version)
pprint("os=" + platform.platform())
```
  ## MDF version
4.10

  ## Code snippet
```
    def start_time(self, timestamp):

        if timestamp.tzinfo is None:
            self.time_flags = v4c.FLAG_HD_LOCAL_TIME
        else:
            self.time_flags = 0
            timestamp = timestamp.astimezone(timezone.utc)
```
 
# Description

When start time doesn't exist in MDF file you assign to this variable - time from now/time of extraction process. In most cases that generates problems on our side (due to we analyze data from the same day so we have mismatch in hours not days) because we do not detect that this time is missing in recording.

My proposition is change that in way:
If start time filed doesn't exist assign start time to datetime(1970, 1, 1) - start of unix time calculation, which is fully visible for user that start time was missing and something wrong with that. I think this will be easier for asam users to investigate why correct start time wasn't logged into MDF. 

Also if that wasn't possible is a monkey path on our side, but if you implement that solution I think it will be with benefits.

I will be waiting for your reply what do you think about that.

Thanks !

**Comment by danielhrisca** [comment]
If you create a measurement file from scratch then yes the current datetime is used, otherwise the original timestamp from the measurement is used. So if you create a measurement from scratch you should also take care to set the header start time accordingly

**Comment by SzczepekJakub** [comment]
Some times logging setup doesn't create start time (some issue in test system) - unexpected/obvious result, above "support" will be easier during validation of mdf files and I think this doesn't change much in your approach.

**Comment by danielhrisca** [comment]
@SzczepekJakub I've set the default time stamp to 1 Jan 1980

**Comment by SzczepekJakub** [comment]
Thanks a lot !!!
