### ISSUE TITLE
MDF4 get_group() breaks data

### ISSUE THREAD

**Issue by zariiii9003** [danielhrisca/asammdf#229]
# Python version
```
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.16.1'
'asammdf=5.10.4.dev0'
```
# Code 

  ## MDF version
  ``4.00``

  ## Code snippet
  ```
  from asammdf import MDF

  if __name__ == "__main__":
     mdf = MDF("path_to_file.MF4")
     df = mdf.get_group(5)
  ```
  
  ## Traceback
  ```
  Traceback (most recent call last):
  File "C:/myPath/main.py", line 5, in <module>
    df = mdf.get_group(5)
  File "myPath\venv\lib\site-packages\asammdf\mdf.py", line 3352, in get_group
    ignore_value2text_conversions=ignore_value2text_conversions,
  File "myPath\venv\lib\site-packages\asammdf\mdf.py", line 3423, in to_dataframe
    mdf = self.filter(channels)
  File "myPath\venv\lib\site-packages\asammdf\mdf.py", line 1699, in filter
    copy_master=False,
  File "myPath\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3954, in get
    _dtype = dtype(channel.dtype_fmt)
  ValueError: field '_level_1_structure._level_2_structure' occurs more than once
```

so i added the following code to the following code to MDF4 -> _read_channels() -> while ch_addr https://github.com/danielhrisca/asammdf/blob/88e2e67a18a77c4ee437907a3f67603397b6eac0/asammdf/blocks/mdf_v4.py#L798
```
            if channel.component_addr:
                channel.name += "_struct"
```
I mentioned this in my email to you. This fixes the duplicate channel names.
Now my Traceback is the following:
```
C:\myPath\venv\lib\site-packages\pandas\core\indexes\numeric.py:443: RuntimeWarning: invalid value encountered in equal
  return ((left == right) | (self._isnan & other._isnan)).all()
```
  I was looking for the reason for this. It looks like you create a new filtered mdf file here, when using ``get_group()``
https://github.com/danielhrisca/asammdf/blob/88e2e67a18a77c4ee437907a3f67603397b6eac0/asammdf/mdf.py#L3423

This new mdf has a fragmented data block. The first data_block fragment has a different total size and also a different samples_size than the following fragments.
![image](https://user-images.githubusercontent.com/52598363/64078976-b6e9e300-cce1-11e9-8351-ad8123662b02.png)

When i check the returned pandas dataframe the data is correct for the first ~6500 rows, then garbage follows.
If i use the get method to retrieve a single Signal from the original MDF object the data is okay.

The file is rather large (160MB). Please tell me if you need it to find the cause.

**Comment by danielhrisca** [comment]
Hello @zariiii9003 ,

I would really appreciate if you could sen the file

**Comment by zariiii9003** [comment]
I sent you a mail. Thank you for looking into this.

**Comment by danielhrisca** [comment]
@zariiii9003 

Please try the new development branch code.

**Comment by zariiii9003** [comment]
Hello Daniel,

same error regarding the duplicate name problem:

```
Traceback (most recent call last):
  File "C:/myPath/test_mdf_structure.py", line 63, in <module>
    df = mdf.get_group(5)
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3352, in get_group
    ignore_value2text_conversions=ignore_value2text_conversions,
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3432, in to_dataframe
    mdf = self.filter(channels)
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 1699, in filter
    copy_master=False,
  File "C:\myPath\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3956, in get
    _dtype = dtype(channel.dtype_fmt)
ValueError: field '_top_level_structure._lower_level_structure' occurs more than once
```

I'll try to create a smaller file that can reproduce the problem but does not include too much information.

**Comment by danielhrisca** [comment]
@zariiii9003 
how about now with the new commit?

**Comment by zariiii9003** [comment]
Excellent! The duplicate name error is gone.

But the data still is broken...
```
RuntimeWarning: invalid value encountered in equal
  return ((left == right) | (self._isnan & other._isnan)).all()
```
you should be able to reproduce this with the 160MB file i shared to you.

**Comment by zariiii9003** [comment]
So get_group() seems to work now. I guess commit 2c3f7c2d5eda348619ff649061a39d0093a6316a fixed the issue.

I have another question though: Is it possible to make this https://github.com/danielhrisca/asammdf/blob/6c165c560e6f18e4dbb89669caad004022d73981/asammdf/blocks/utils.py#L1074 optional? You compose the channel name from the structure name here. I would prefer the channel name to be equal to the signal name in the a2l file.

**Comment by danielhrisca** [comment]
I'm not sure how this could be done. Can you give an example?

**Comment by zariiii9003** [comment]
I replaced "name_" for "name" in this line https://github.com/danielhrisca/asammdf/blob/8289bc3ec9f35858010c74bf8ad6101abd1d0d01/asammdf/blocks/utils.py#L1080

Seems to do exactly what i want. But i did not check for any side effects. 
Thank you for the quick response btw :)

**Comment by danielhrisca** [comment]
> I replaced "name_" for "name" in this line
> 
> https://github.com/danielhrisca/asammdf/blob/8289bc3ec9f35858010c74bf8ad6101abd1d0d01/asammdf/blocks/utils.py#L1080
> 
> Seems to do exactly what i want. But i did not check for any side effects.

@zariiii9003 have  a try with the latest development branch code

```python
df = mdf.get_group(4, only_basenames=True)
```

**Comment by zariiii9003** [comment]
It does not seem to change anything. It is still structure name + signal name. No matter whether i set it to True or False

**Comment by danielhrisca** [comment]
You were right, the arguments was not forwarded to the components function call. Have a try with the new commit

**Comment by zariiii9003** [comment]
It works, thank you!

I'll keep this issue open for now, i have another file that causes this error:
```
C:\myPath\venv\lib\site-packages\numpy\lib\arraysetops.py:314: RuntimeWarning: invalid value encountered in not_equal
  mask[1:] = aux[1:] != aux[:-1]
Traceback (most recent call last):
  File "C:/myPath/drag_distance.py", line 26, in <module>
    df_bhs = mdf.get_group(idx, only_basenames=True)  # BhsDisp
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3381, in get_group
    only_basenames=only_basenames,
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3481, in to_dataframe
    only_basenames=only_basenames,
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3538, in to_dataframe
    copy_master=False,
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 2934, in select
    master[current_pos: next_pos] = self._mdf._master
ValueError: could not broadcast input array from shape (8924) into shape (8922)
```
But i'll try to find the cause myself first.

**Comment by danielhrisca** [comment]
Do you get this error with one of the files that you have sent?

**Comment by zariiii9003** [comment]
Actually yes, i just tried the file of the first post in here and it behaves the same. Do you still have it?

Some error is introduced at this step:
https://github.com/danielhrisca/asammdf/blob/f23dbaad9c3d4adda392d80578e4e495e97e3e29/asammdf/mdf.py#L3468

I think `mdf_4.append()` somehow gets the 'samples_byte_nr' wrong here:
https://github.com/danielhrisca/asammdf/blob/f23dbaad9c3d4adda392d80578e4e495e97e3e29/asammdf/blocks/mdf_v4.py#L3194

And `mdf_4.extend()` miscalulates the `cycles_nr` here:
https://github.com/danielhrisca/asammdf/blob/f23dbaad9c3d4adda392d80578e4e495e97e3e29/asammdf/blocks/mdf_v4.py#L3709

But these might just be some symptoms of another error somewhere else.

**Comment by danielhrisca** [comment]
Can try again with the development branch code?

**Comment by zariiii9003** [comment]
With the latest development code:

```
C:\myPath\venv\lib\site-packages\numpy\lib\arraysetops.py:314: RuntimeWarning: invalid value encountered in not_equal
  mask[1:] = aux[1:] != aux[:-1]
Traceback (most recent call last):
  File "C:/myPath/drag_distance.py", line 23, in <module>
    df = mdf.get_group(4)
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3381, in get_group
    only_basenames=only_basenames,
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3481, in to_dataframe
    only_basenames=only_basenames,
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 3538, in to_dataframe
    copy_master=False,
  File "C:\myPath\venv\lib\site-packages\asammdf\mdf.py", line 2934, in select
    master[current_pos: next_pos] = self._mdf._master
ValueError: could not broadcast input array from shape (8924) into shape (8922)

Process finished with exit code 1
```

**Comment by danielhrisca** [comment]
I've tried with the 3.5Mb and the 160MB files and I don't get errors

**Comment by zariiii9003** [comment]
Try get_group(5) on the 160MB file please.

**Comment by danielhrisca** [comment]
Hello @zariiii9003 ,

I think the latest commit fixes the problem. At least there is no error anymore

**Comment by zariiii9003** [comment]
Hello Daniel,

i think you forgot something here :)

https://github.com/danielhrisca/asammdf/blob/5af22f9dd82cac0b1bff1fb528f059877cc3680a/asammdf/mdf.py#L3471

**Comment by zariiii9003** [comment]
The resulting dataframe data seems to be garbage.

Try this and compare `get_group()` data and the `get()` data:

```
    idx = mdf.whereis("YWFSFGEGIPTFCIPIGZLREWPRQHXLJIB")[0][0]
    print(idx)
    df = mdf.get_group(idx, only_basenames=True)

    print(df["YWFSFGEGIPTFCIPIGZLREWPRQHXLJIB"].head(100))

    print(mdf.get("YWFSFGEGIPTFCIPIGZLREWPRQHXLJIB").samples)
```

The `get()` method gets the correct data.

**Comment by danielhrisca** [comment]
``YWFSFGEGIPTFCIPIGZLREWPRQHXLJIB`` is not found in the measurements

**Comment by zariiii9003** [comment]
It should be in the 160MB file.
Anyhow here is the result:

`get_group()`:
```
0.000000    1.843885e-40
0.001246    1.843885e-40
0.002291    1.843885e-40
0.003234    1.843885e-40
0.004135    1.843885e-40
                ...     
0.095239    1.843885e-40
0.096010    1.843885e-40
0.097247    1.843885e-40
0.098075    1.843885e-40
0.099230    1.843885e-40
```
`get()`:
```
Name: YWFSFGEGIPTFCIPIGZLREWPRQHXLJIB, Length: 100, dtype: float32
[0.00204496 0.00193558 0.00183286 ... 0.10831846 0.10901507 0.10948642]
```

**Comment by zariiii9003** [comment]
You're right, sorry. It should be `"XMTCKTWMXHZPUNTIWIYWAIXZZYHJJEM"` in your file.

```
    idx = mdf.whereis("XMTCKTWMXHZPUNTIWIYWAIXZZYHJJEM")[0][0]
    df = mdf.get_group(idx, only_basenames=True)

    print(df["XMTCKTWMXHZPUNTIWIYWAIXZZYHJJEM"].values)
    print(mdf.get("XMTCKTWMXHZPUNTIWIYWAIXZZYHJJEM").samples)
```

Output:
```
[1.84388e-40 1.84388e-40 1.84388e-40 ... 1.84388e-40 1.84388e-40
 1.84388e-40]
[0.00204496 0.00193558 0.00183286 ... 0.10831846 0.10901507 0.10948642]
```

**Comment by danielhrisca** [comment]
@zariiii9003 
please try again with the new development code

**Comment by zariiii9003** [comment]
Just tried it on several files and the data seems plausible now. Thank you for taking the time to solve this! This will make working with structure channels less of a pain in the ass.

Don't forget to remove this line before you merge it though. It causes an error message:
https://github.com/danielhrisca/asammdf/blob/c7d02ef8716fe8c5b5815ee427715341afba7af3/asammdf/mdf.py#L3471
