### ISSUE TITLE
If the MF4 file is too big, MF4 file cannot export mat file 

### ISSUE THREAD

**Issue by tingfenghanlei** [danielhrisca/asammdf#230]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)  
 'python=3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]'
pprint("os=" + platform.platform())
'os=Windows-10-10.0.17763-SP0'
try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass
'numpy=1.16.4'
try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
'asammdf=5.10.3'
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

**Comment by tingfenghanlei** [comment]
The MF4 file version is 4.10. I just use the GUI tool to transform the MF4 to mat file.

**Comment by danielhrisca** [comment]
Hello @tingfenghanlei ,

I don't think there is much I can do about this: all data has to be present in a dict when the file is written.

**Comment by tingfenghanlei** [comment]
ok, If the all big MF4 file  can't transform to mat file. Could you add a function that I input a file with some signals name and input the big MF4 file, then output the mat file only with these input signals ?

**Comment by danielhrisca** [comment]
You can do this using the API

```python
mdf = MDF(filename)
mdf.filter(channel_names).export('mat', filename + '.mat')
```

of from the GUI you have to first use the filter tab and afterwards load the generated file and export it.

**Comment by tingfenghanlei** [comment]
Thank you very much. If I have 3000 signals, I should read these signals, then I assign them to channel_names?  Then I can export mat file.

**Comment by tingfenghanlei** [comment]
Hello, I am so sorry to disturb you. 
mdf = MDF(filename)
mdf.filter(channel_names).export('mat', filename + '.mat')
this is used for channel export. but every channel have many signals. 
My requested is that I want to export mat file with some signals data.
Can you give me some suggestions? Thank you very much.

**Comment by danielhrisca** [comment]
I didn't understand what the problem is. Can explain in details what you mean? Maybr you can also put some screenshots to ilustrated the issues (using Vector MDFValidator)

**Comment by tingfenghanlei** [comment]
The MDF file has many channels, and every channels have many signals, but I only want to get some specific signals from the MDF file and export these signals in a mat file, but these specific signals may distributed in different channels.

**Comment by tingfenghanlei** [comment]
![image](https://user-images.githubusercontent.com/28851892/64922897-de26d100-d806-11e9-9845-8ee972460a7d.png)

**Comment by tingfenghanlei** [comment]
sorry, I think you are right.
`mdf = MDF(filename)
mdf.filter(channel_names).export('mat', filename + '.mat')`
this can solve my request. Thank you very much.
