### ISSUE TITLE
Improvement: Tabular window - partial load for large data sets

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#231]
Hi Daniel,

We've got a lot of users that are really happy with the Tabular display functionality in asammdf. It's extremely useful for quickly reviewing raw data - in particular with the filter options.

The only downside is that it does not "scale" with the file size. Often, the users will want to load MDF4 files that are e.g. 50 to 200 MB in size. This goes relatively fast in asammdf - but to load e.g. a 50 MB in the Tabular view, it takes around 30-45 seconds (see sample below):
[7F34B296_00000009_00000007.zip](https://github.com/danielhrisca/asammdf/files/3579237/7F34B296_00000009_00000007.zip)

The ideal behavior would be to have the Tabular view load e.g. the first 5 MB of a file - and then only load other parts of the file if the user scrolls down sufficiently and/or changes the filters. 

I realize we discussed this earlier, but I just wanted to at least mention that it's become a very popular functionality - and I believe it would be a great update.

Of course 100% up to you - happy to hear your thoughts on it.

Martin

**Comment by danielhrisca** [comment]
This is obviously a good idea, but it's not easy to implement.

**Comment by MatinF** [comment]
Seems your latest commit made for a speed improvement of ~90% - so I'm closing this issue :-) thanks again Daniel!
