### ISSUE TITLE
get really slow in newer versions

### ISSUE THREAD

**Issue by jcfschulz** [danielhrisca/asammdf#232]
# Description
As I am currently migrating from Python2 to Python3 I wanted to switch to a current asammdf version. However, I found that mdf.get is far slower. To look into this, i created a basic mf4 file with the [create.py](https://github.com/danielhrisca/asammdf/files/3584777/create.txt) attached and then read back with the attached [read.py](https://github.com/danielhrisca/asammdf/files/3584778/read.txt).

These are pretty drastic differences. Is this some bug or why is there such a difference in performance?

Results for Python2
`
'python=2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.16.3'
'asammdf=4.7.11'
('runtime', 0.125)
`

Results for Python3
`
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.16.3'
'asammdf=5.10.3'
runtime 35.11199998855591
`

**Comment by danielhrisca** [comment]
Hello @jcfschulz 

this is by design in the new version (see https://github.com/danielhrisca/asammdf/issues/137).

You should use select for better performance instead of calling _get_ multiple times
