### ISSUE TITLE
Dealing with MDF3 file and Error 'list index out of range'

### ISSUE THREAD

**Issue by mrmuyi** [danielhrisca/asammdf#233]
<img width="960" alt="MDF VALIDATOR PIC" src="https://user-images.githubusercontent.com/35884888/64481902-2cd9d700-d219-11e9-955a-86a5b81a7cd3.PNG">
# Python version 3.6.4
#ASAMMDF 5.10.0
```python
from asammdf import MDF
fn='rec_2136_2018-11-22-10_52_43.dat'
mdf = MDF(fn, version='3.30')
```
# Code 

  ## MDF version
  MDF 3.30
  ## Code snippet
  mdf = MDF(fn, version='3.30')
  
  ## Traceback
Traceback (most recent call last):
  File "D:/A_YPC/Mine_PY/00_MODULE/02 SPEC_MONITOR/usmdf190907.py", line 25, in <module>
    mdf = MDF(fn, version='3.30')
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python36\lib\site-packages\asammdf\mdf.py", line 124, in __init__
    self._mdf = MDF3(name, **kwargs)
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python36\lib\site-packages\asammdf\blocks\mdf_v3.py", line 196, in __init__
    self._sort()
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python36\lib\site-packages\asammdf\blocks\mdf_v3.py", line 3413, in _sort
    address = group.data_blocks[0].address
IndexError: list index out of range
  
# Description
Hello Daniel,
 when I deal wiht original CAN LOGGING data XXX.dat(MDF validator indicate the file version is MDF 3.30),  i got the error: list index out of range. .The original MDF data was unsorted MDF, and when I convert it to SORTED MDF(Using the device's software), it worked.
 I want to deal the data with original data not the converted data(consuming much time). Could you help me? I don't know if the ASAMMDF only deal with SORTED MDF or both SORTED&UNSORTED MDF.

**Comment by danielhrisca** [comment]
Hello @mrmuyi 

the library supports unsorted files.

To speed thing up , can you send the file for analysis?

**Comment by mrmuyi** [comment]
Daniel,
HI~
I am very happy to get your reply!
Attachment was the file(about 64MB), longing for your ananlysis and reply.
Best Regards!






At 2019-09-09 14:29:36, "Daniel Hrisca" <notifications@github.com> wrote:


Hello @mrmuyi

the library supports unsorted files.

To speed thing up , can you send the file for analysis?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易163邮箱发来的云附件
rec_2136_2018-11-22-10_52_43.rar (63.7M, 2019年9月24日 15:06 到期)
下载

**Comment by danielhrisca** [comment]
You can zip the file and send it to my email address daniel.hrisca@gmail.com

**Comment by danielhrisca** [comment]
@mrmuyi the attachment was not uploaded to the github issue

**Comment by mrmuyi** [comment]
@Daniel hello,

I had sent the attachment to your email address daniel.hrisca@gmail.com
Pls. check again, THX






At 2019-09-09 17:15:59, "Daniel Hrisca" <notifications@github.com> wrote:


@mrmuyi the attachment was not uploaded to the github issue

**Comment by danielhrisca** [comment]
@mrmuyi 

check out the latest development branch code (``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``)

**Comment by mrmuyi** [comment]
I have tried and the Error was solved! 
I am very much appreciated your efficient and excellent work!

**Comment by mrmuyi** [comment]
<img width="746" alt="EnSpdHSC1CAN1" src="https://user-images.githubusercontent.com/35884888/64670232-e1346100-d496-11e9-8301-545e12475ce0.PNG">

fn='rec_2136_2018-11-22-10_52_43.dat'
mdf = MDF(fn, version='3.30')
enspd=mdf.get('EnSpdHSC1:CAN1')#EnSpdHSC1:CAN1
print(enspd)

why I got enpty Dataframe
samples=[]
timestamps=[]
Actually the data was .PNG shows

**Comment by danielhrisca** [comment]
The file that you have send over e-mail has no samples:

![image](https://user-images.githubusercontent.com/20952040/64670532-22644b00-d46e-11e9-94a3-e4dc2ea876e1.png)
![image](https://user-images.githubusercontent.com/20952040/64670545-30b26700-d46e-11e9-96b3-b29b559357d5.png)

**Comment by mrmuyi** [comment]
The original unsorted MDF I email to you had no dg_data in Channel Group, I don't knon whether this format accord with ASAM standard. Actually the data point to  0x1962FC: right button on 'Data Group 1', then 'Open Hex View Window'.
<img width="960" alt="get" src="https://user-images.githubusercontent.com/35884888/64685349-6b8dbc80-d4b9-11e9-8d07-73147bde0dd1.PNG">
