### ISSUE TITLE
Missing [BUS_EVENT] flag in CAN_DataFrame sub channels

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#234]
Hi Daniel,

We found a minor "bug" in the conversion of raw bus logging MDF4 data via asammdf. 

**Expected behavior**
When loading an unfinalized/unsorted MDF4 in asammdf and then using the Convert tab to save it as a raw buslogging MDF4 file, we would expect that the CAN_DataFrame channel **and** member channels would have the `BUS_EVENT` flag set in `cn_flags`.

**Observed behavior**
What we see is that the CAN_DataFrame channel does have the BUS_EVENT flag set, but the member channels do not (see below pics). The result of this is that the file cannot be loaded in e.g. CANalyzer. If we manually set the flags of the member channels, the file loads correctly in CANalyzer.
![asammdf_BUS_EVENT_channel](https://user-images.githubusercontent.com/26184427/64678518-0797d380-d47a-11e9-87dd-35039888fa46.PNG)
![asammdf_BUS_EVENT_member_channel](https://user-images.githubusercontent.com/26184427/64678519-0797d380-d47a-11e9-8b0f-d5288a586bf6.PNG)

This was tested with the development branch GUI version 5.11.0.

I've attached a sample below with the current converted version and the corrected version:
[asammdf_converted.zip](https://github.com/danielhrisca/asammdf/files/3599607/asammdf_converted.zip)

**Comment by danielhrisca** [comment]
@MatinF 
can you try the new code?

**Comment by MatinF** [comment]
It's fixed now, thanks a lot Daniel - fast as always!
