### ISSUE TITLE
Problem finding attachments (dbc or arxml)

### ISSUE THREAD

**Issue by mikesmitti** [danielhrisca/asammdf#235]
# Python version
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.4'
'asammdf=5.10.3'
```
# Code 

  ## MDF version
  4.10

  ## Code snippet
 not traceable
  
  ## Traceback
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
WARNING:asammdf:Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._
I got an mf4 (mdf4) file with two databases (dbc and arxml) named as attachments.
If the the databases are not in exactly the same path as on the machine where the trace has been tlogged, I get the warning mentioned above. 
I did not find a way to change that yet.

**Comment by danielhrisca** [comment]
Hello @mikesmitti 

you have an external attachment so you must have the files in the correct paths to work properly.

**Comment by danielhrisca** [comment]
Hello Mike,

have a look at these methods
https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.extract_can_logging 
https://asammdf.readthedocs.io/en/latest/api.html#mdf4 (see _get_can_signal_)

You can use them to provide a CAN database

**Comment by mikesmitti** [comment]
Sorry for late repsonse, I will try it.
Best Regards.

**Comment by danielhrisca** [comment]
Please try again with the development branch code and share the error trace back if any

**Comment by danielhrisca** [comment]
ping @mikesmitti

**Comment by mikesmitti** [comment]
I will try it this week. Greetings

**Comment by mikesmitti** [comment]
Great job, it works!
Thank you for your help.
Best regards
