### ISSUE TITLE
arxml with cascaded dictio

### ISSUE THREAD

**Issue by mikesmitti** [danielhrisca/asammdf#236]
# Python version
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.4'
'asammdf=5.10.3'

  ## MDF version
 4.10

  ## Code snippet
In mdf_v4.py
line 573
if db:
                        try:
                            board_units = set(bu.name for bu in db.boardUnits)
                        except AttributeError:
                            board_units = set(bu.name for bu in db.ecus)
  
  ## Traceback
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.10.3-py3.7.egg\asammdf\blocks\mdf_v4.py", line 574, in _read
    board_units = set(bu.name for bu in db.ecus)
AttributeError: 'dict' object has no attribute 'ecus'
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._
I have an arxml database with a cascaded dictionary. I mean, it got a dictionary "xyz" in it, which contains the dictionaries asammdf is looking for. This causes an exception, since the dictionaries looked for are not in the place they should be.

I changed this line like this:
                    if db:
                        try:
                            board_units = set(bu.name for bu in db.boardUnits)
                        except AttributeError:
                            try: 
                                board_units = set(bu.name for bu in db.ecus)
                            except:
                                board_units = set(bu.name for bu in db["DictnameHere"].ecus)

This works but is no solution for wider use.

**Comment by danielhrisca** [comment]
Can you send the file to have a look over it?

**Comment by danielhrisca** [comment]
Looking through the [canmatrix](https://github.com/ebroecker/canmatrix) code I get the feeling that your file does not have the expected internal structure. Maybe you can raise an issue on their repo to see if this is the case.

**Comment by mikesmitti** [comment]
Thx, I ´ll do that.
Best regards

**Comment by mikesmitti** [comment]
Repsonse from CANMatrix can be found here:
https://github.com/ebroecker/canmatrix/issues/401#issuecomment-534869531

Best regards.
Michael
