### ISSUE TITLE
How to convert Numpy byte types in DataFrame column to string

### ISSUE THREAD

**Issue by JuanInATrillion** [danielhrisca/asammdf#237]
Hi @danielhrisca , I have 2 groups that are slightly off, a couple of samples.
I currently have 2 groups that are slightly offset by a few cycles. I unfortunately cannot provide you a snippet of the data because is proprietary.
Here is what I'm attempting:
`t=pd.merge(mdfobj.get_group(101),mdfobj.get_group(102),left_on='time',right_on='time', how='outer',copy=False) t.loc[:,byte_clnnames] = t.loc[:,byte_clnnames].applymap(lambda x:x.decode('utf-8')`
I'm trying this because doing raster is causing some ffill removing important values (not really sure how you are performing interpolating for non-numeric datatypes). 
When I perform the applymap the values are not being kept in place. I want to convert channels of datatype |S32,|S24, |S# to string but for some reason they are not being kept in place. 
 I'm doing this so that I can then resample using pandas and perform forward fill. 
Can you help me with this and/or help me understand what's happening with raster when the values are |S# types and/or integers. Some data values are more like categorical numeric variables that shouldn't be interpolated.

**Comment by danielhrisca** [comment]
@JuanInATrillion did it work?

**Comment by JuanInATrillion** [comment]
@danielhrisca I'm doing some debugging. Group 101 and Group 102 don't have the same # of channels but have the same number of cycles, so enumerating Group 101 or viceversa will work. 
**Pseudocode:** 
Essentially I'm creating close in cycle groups by +/- 20 cycles, using this code I found in [StackOverFlow](https://stackoverflow.com/questions/38622868/how-to-split-a-list-of-numbers-based-on-the-distance-of-consecutive-elements-in) then trying to figure out a way to merge them by Float64Index. 


I do have a question for you: why a 3 element tuple with None as first item in tuple in your channels list? (None,index,i) What is this doing and couldn't it be just (index,i)? Just curious.

**Comment by danielhrisca** [comment]
> I do have a question for you: why a 3 element tuple with None as first item in tuple in your channels list? (None,index,i) What is this doing and couldn't it be just (index,i)? Just curious.

Because this is the way to precisely chosse the desired channels (see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.select and https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.to_dataframe)

**Comment by JuanInATrillion** [comment]
My apologies @danielhrisca , I need to get familiar with all the functionality within your library.

**Comment by danielhrisca** [comment]
> My apologies @danielhrisca , I need to get familiar with all the functionality within asammdf.
> This might be another library specific question: If there are many channels with the same name even though they are called the same but are actually different does mdf.to_dataframe(channels=channels) just treats them as the same channel?
> In Groups 101, 102 RollingCounter exists as a channel name however, their actually specific to each message.

Each channel will be treated individually. If the name is repeating then a suffix will be appplied ``Speed``, ``Speed_1``, ``Speed_2`` ...


> Also, once I ffill by changing to string as you demonstrated using np.char.decode, how do you reconvert to bytes? Just np.char.encode back to latin-1 encoding?

Yes you just decode the bytes using the initial text encoding
