### ISSUE TITLE
GUI improvement idea: Show DBC conversion statistics

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#238]
Hi Daniel,

A suggestion for DBC conversion of log files:

A frequent challenge is that a user may convert a bus logging file with a large number of CAN IDs (sometimes several hundreds). They may use e.g. a J1939 DBC file to do this, but the DBC file only contains matches for e.g. 80% of the CAN IDs. 

In this case, it would be very useful to be able to see a bit of summary information about the conversion, e.g. something ala below:

```
Conversion successful!

MDF4 file name(s): [filename(s)]
DBC file name(s): [DBC filenames]

Summary:
- The signal extraction took [X] seconds to complete
- [X] of [Y] IDs in the MDF4 file were matched in the DBC and converted
- A total of [X] IDs and [Y] parameters are in the extracted output

Detailed information:

The following CAN IDs were matched in the DBC:
- [CAN ID X] --> [CAN ID name from DBC]
...

The following CAN IDs were not matched in the DBC:
- [CAN ID Y] 
...
```
The thinking would be to have this type of console output in the GUI (and perhaps as an optional print statement in the API). It could be shown on the right-hand side of the DBC conversion tab where there's currently quite a bit of excess space. 

It's not critical, but we've got a lot of users asking for this functionality :-)

Martin

**Comment by danielhrisca** [comment]
Hello Martin,

have a try with the development branch code

**Comment by danielhrisca** [comment]
@MatinF 
is there anything else to add related to this request?

**Comment by MatinF** [comment]
Hi Daniel, thanks the implementation you made is great, we use it already! Closing this :-)
