### ISSUE TITLE
Opening ATFX and DAT files with asammdf library

### ISSUE THREAD

**Issue by naseefo** [danielhrisca/asammdf#240]
I have conducted a field vibration measurement (device from Crystal Instruments) for which I have a data file containing acceleration responses in three directions. The resulting result folder has two files:

1. filename.atfx
2. filename-01.dat

Basically *.atfx file contains the meta information of the fields in the DAT file. Is it possible to read these files using this package in Python? Currently I am converting this into MAT file in its software and using suitable packages to decode it. Is there more straightfoward way with this library? Since this is used for MDF file which is supported by ASAM, I was wondering if this package also has the feature to open ATFX file.

**Comment by danielhrisca** [comment]
what happens if you try to open the file with the API?

```python
from asammdf import MDF
mdf = MDF('filename.dat')
```

**Comment by naseefo** [comment]
Hi Daniel!

I executed the following code in a test.py script file in Windows 64-bit / Python 3.7.0 (64-bit)

from asammdf import MDF
mdf = MDF('REC0001-2595008.dat')

I got the following error message:

Traceback (most recent call last):
  File ".\test.py", line 2, in <module>
    mdf = MDF('REC0001-2595008.dat')
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\mdf.py", line 115, in __init__
    raise MdfException(f'"{name}" is not a valid ASAM MDF file')
asammdf.blocks.utils.MdfException: "REC0001-2595008.dat" is not a valid ASAM MDF file

Regards,
Naseef

**Comment by danielhrisca** [comment]
``.dat`` is a common extension. I'm afraid this is not an ASAM MDF file, so you will have to look elsewhere. 

to be sure can you also share the output of this snippet?

```python
with open('REC0001-2595008.dat', 'rb') as f:
    print(f.read(64))
```

**Comment by naseefo** [comment]
```
with open('REC0001-2595008.dat', 'rb') as f:
    print(f.read(64))
```

@danielhrisca I executed the above code to read few lines as per you suggestion. This is the output 
that I have received:

`b'\xce\xcc\xa0\xb6\x01\x00\xac\xb6\x9b\x99\xa1\xb6gf\xaa\xb6\x01\x00\xa0\xb643\xa7\xb6gf\x9e\xb6\x9b\x99\xad\xb6\xce\xcc\xb4\xb6\xce\xcc\xa4\xb6\x01\x00\xac\xb6\x01\x00\xa4\xb6\xce\xcc\xb0\xb6\x01\x00\xa8\xb643\xb3\xb6gf\xa6\xb6'`

**Comment by danielhrisca** [comment]
This is not a MDF file for sure.

This what I get from the ASAM demo file:

``b'MDF     4.10    TGT 15.0\x00\x00\x00\x00\x9a\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'``
