### ISSUE TITLE
Converting binary string signal values to int, when .mdf file parsed using asammdf 5.11

### ISSUE THREAD

**Issue by akshathkapil** [danielhrisca/asammdf#241]
# Python version
_Please run the following snippet and write the output here_

**Output for asammdf version 4.6**
('python=3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.17.2'
'asammdf=4.6.0'

**Output for asammdf version 5.11**
('python=3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.17.1'
'asammdf=5.11.0'

  ## MDF version
  3.0

  ## Code snippet
from asammdf import MDF
filepath = r"my_file_path"
signal_obj = MDF(filepath)
signal = signal_obj.get("signal_name")
print(signal.samples)
  
  ## Traceback
No traceback
  
# Description
Signal values in binary string form in asammdf to be converted to uint in version 5.11.

_Please describe the issue here._

I have written our code previously using asammdf 4.6 in which when we get a signal from .mdf file, it returns the sample values as a numpy array of int. But in asammdf version 5.11 its returns a numpy array of binary strings which does not solve my usecase. Please, let me know if there is a function or a way in which I can convert my signal values to uint from the binary string ones in asammdf 5.11.

I have attached the two results from both the versions, I got after parsing my .mdf file.

![asammdf_4 6](https://user-images.githubusercontent.com/24757034/66185000-8cea5e80-e69b-11e9-8135-41c0f2a8cf27.PNG)
![asammdf_5 11](https://user-images.githubusercontent.com/24757034/66185001-8cea5e80-e69b-11e9-92b2-67ed5b390e12.PNG)

**Comment by danielhrisca** [comment]
```python
from asammdf import MDF
filepath = r"my_file_path"
signal_obj = MDF(filepath)
signal = signal_obj.get("signal_name", raw=True)
print(signal.samples)
print(signal.physical().samples)
```

**Comment by JulienGrv** [comment]
I think this issue can be marked as fixed now.
