### ISSUE TITLE
How to get message name from Vector CAN log for MDF3 and for MF4

### ISSUE THREAD

**Issue by JuanInATrillion** [danielhrisca/asammdf#242]
Hi as we've discussed earlier there might be groups that have the same signal name across groups, when merging groups into a single dataframe I want to able to find duplicate column names and append the message name to differentiate them from each other. 
I had done something like mdfObj.groups[101].channels.source.name is there a similar way to acquire the message name for MDF3 and MF4?
Thank you.

**Comment by danielhrisca** [comment]
Hello Juan,

is it not possible to use to_dataframe directly? if needed you can supply the channels argument to filter the important channels

**Comment by JuanInATrillion** [comment]
Hi Daniel, 
I'm not well versed in Python like yourself but here are the differences, I'm unsure as to how you are handling repeated signal names in the to_dataframe() method. 
![image](https://user-images.githubusercontent.com/35745046/66397677-528a0580-e9aa-11e9-9581-9055d0c5d4f4.png)

**Comment by danielhrisca** [comment]
The timestamps channels is used as the index for the data frame, and the union of all values is used (see https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L3498)

Then an UniqueDB object (https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L3505)  is used to generate new column names for the repeating channel names (https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L3591)

**Comment by JuanInATrillion** [comment]
Thanks Daniel!
