### ISSUE TITLE
Cannot read float list with get

### ISSUE THREAD

**Issue by DougRzz** [danielhrisca/asammdf#243]
# Python version
'python=3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.17763-SP0'
'numpy=1.16.4'
'asammdf=5.12.0'

## MDF version
4.10

# Code 

  
```python
from asammdf import MDF

mdf = MDF(MDFfilePath)

for groupNum in range(1000):
    for indexNum in range(1000):
        try:
            a = mdf.get_channel_metadata(group = groupNum, index =indexNum)
            if a.name != 't':
                print(a.name)
                print(groupNum)
                print(indexNum)
        except:
            pass
```
The snippet above successfully prints a list of all the channels, together with the group and index numbers of each channel that I expect to see in the MDF file.

When I use 'get' instead of 'get_channel_metadata' command, it only successfully retrieves data with strings in the samples. It doesn't successfully read the channels with a list of floats.
```python

for groupNum in range(1000):
    for indexNum in range(1000):
        try:
            a = mdf.get(group = groupNum, index =indexNum)
            if a.name != 't':
                print(a.name)
                print(groupNum)
                print(indexNum)
                print(a.samples)
        except:
            pass
```

## Code snippet
The snippet below gives an exception for the get command for valid group and index numbers.  
```python
mdf.get(group = 97, index = 43)
```
  
## Traceback
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\numexpr\necompiler.py in getArguments(names, local_dict, global_dict)
    743             try:
--> 744                 a = local_dict[name]
    745             except KeyError:

KeyError: 'x'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-223-fe82117d8d4a> in <module>
----> 1 sig = mdf4Loaded.get(group = 97, index =43)

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\asammdf\blocks\mdf_v4.py in get(self, name, group, index, raster, samples_only, data, raw, ignore_invalidation_bits, source, record_offset, record_count, copy_master)
   4870             if not raw:
   4871                 if conversion:
-> 4872                     vals = conversion.convert(vals)
   4873                     conversion = None
   4874 

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\asammdf\blocks\v4_blocks.py in convert(self, values)
   2670         elif conversion_type == v4c.CONVERSION_TYPE_ALG:
   2671             X = values
-> 2672             values = evaluate(self.formula)
   2673 
   2674         elif conversion_type in (v4c.CONVERSION_TYPE_TABI, v4c.CONVERSION_TYPE_TAB):

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\numexpr\necompiler.py in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)
    816         _names_cache[expr_key] = getExprNames(ex, context)
    817     names, ex_uses_vml = _names_cache[expr_key]
--> 818     arguments = getArguments(names, local_dict, global_dict)
    819 
    820     # Create a signature

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\numexpr\necompiler.py in getArguments(names, local_dict, global_dict)
    744                 a = local_dict[name]
    745             except KeyError:
--> 746                 a = global_dict[name]
    747             arguments.append(numpy.asarray(a))
    748     finally:

KeyError: 'x'
  
# Description

Unfortunately, it will be difficult to send you an example mf4 file.  Please can you offer me any advice on how I should investigate this issue further?

Thanks very much.

**Comment by danielhrisca** [comment]
Hello Doug,

can you insert this line :

```python
            print(self.formula)
```

before this line:
https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/v4_blocks.py#L2672

**Comment by danielhrisca** [comment]
I think the string formula for this channel contains _x_ instead of _X_

**Comment by DougRzz** [comment]
Hi Dan,  thanks for the quick response.

I get this formula printed: 
0.03125*x+0

'x' is not a channel that is in the mdf file.

**Comment by danielhrisca** [comment]
It should be written with a capital X

**Comment by DougRzz** [comment]
Ah.
This seems to work:

values = evaluate(self.formula.replace('x','X'))

Thanks for the help.  Can you see if the above would ever cause problems?

**Comment by danielhrisca** [comment]
It can cause problems only if a function name contains an _x_ in its name

**Comment by danielhrisca** [comment]
@DougRzz can you try the new development branch code? I've pushed fixes for this issue

**Comment by DougRzz** [comment]
@danielhrisca Thanks very much. That works well.  

I wasn't sure if the formulas has any functions which could contain a lower case x. So I created a regex to be a bit safer.  But if you think a straight-forward replace works then that would be better. 
 
My attempt..... line 2545 in v4_blocks.py
```python
        # Edit. Replace lower case x in formula to upper case
        regex = r"(\W|^)x(?=(\W|$))"  # non word character or beginning of line, lower case x, positive look-ahead of either a non-word character or end of line
        subst = r"\1X"
        self.formula = re.sub(regex, subst, self.formula, re.MULTILINE)
```
