### ISSUE TITLE
Release MDF from Memory - multiple large files

### ISSUE THREAD

**Issue by Mark0ne** [danielhrisca/asammdf#244]
# Python version
('python=3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 '
 'bit (Intel)]')
'os=Windows-10-10.0.14393-SP0'
'numpy=1.16.3'
'asammdf=5.12.0'

  ## MDF version
MDF version 3.3

  ## Code snippet
```
def main():
    import os.path
    import asammdf
    import math
    import numpy as np
    import sys, gc

    FileListManual = ['C:\\Some_1Gb_MDF_Files_01.dat',
                    'C:\\Some_1Gb_MDF_Files_02.dat',
                    'C:\\Some_1Gb_MDF_Files_03.dat',
                    'C:\\Some_1Gb_MDF_Files_04.dat',
                    'C:\\Some_1Gb_MDF_Files_05.dat',
                    'C:\\Some_1Gb_MDF_Files_06.dat',
                    'C:\\Some_1Gb_MDF_Files_07.dat',
                    'C:\\Some_1Gb_MDF_Files_08.dat',
                    'C:\\Some_1Gb_MDF_Files_09.dat',
                    'C:\\Some_1Gb_MDF_Files_10.dat',
                    'C:\\Some_1Gb_MDF_Files_11.dat',
                    'C:\\Some_1Gb_MDF_Files_12.dat',
                    'C:\\Some_1Gb_MDF_Files_13.dat',
                    'C:\\Some_1Gb_MDF_Files_14.dat',
                    'C:\\Some_1Gb_MDF_Files_15.dat',
                    'C:\\Some_1Gb_MDF_Files_16.dat',
                    'C:\\Some_1Gb_MDF_Files_17.dat',
                    'C:\\Some_1Gb_MDF_Files_18.dat',
                    'C:\\Some_1Gb_MDF_Files_19.dat',
                    'C:\\Some_1Gb_MDF_Files_20.dat']

    IntChannel = 'Speed'

    intVal = 0 #Integrator value - We intend to integrate speed over all 20 files.


    for fPath in FileListManual:
        
        df=asammdf.MDF(fPath)

        ChannelData = df.get(IntChannel).samples #Seems ok to use df.get(IntChannel).samples[i] also
        ChannelTime = df.get(IntChannel).timestamps #Really slows things down using df.get(IntChannel).timestamps[i]
        nSamples = ChannelTime.size #Total sample count

       
        #loop through all samples except index [0]. Index 1 to end.
        for i in range(1,nSamples):
            intVal = intVal +  (ChannelData[i-1] * (ChannelTime[i] - ChannelTime[i-1])) #PreviousValue * TimeDelta


        print("intVal at the end of this file is: " + str(intVal))

        #None of these seem to improve performance or prevent memory issue:
        del df
        del ChannelData
        del ChannelTime
        DontCare = gc.collect()
        
    return

if __name__ == "__main__":
    main()
```

  
  ## Traceback
Traceback (most recent call last):
  File "C:\MyFile.py", line 118, in <module>
    main()
  File "C:\MyFile.py", line 69, in main
    df=asammdf.MDF(fPath)
  File "...Python\Python37-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF3(name, **kwargs)
  File "...Python\Python37-32\lib\site-packages\asammdf\blocks\mdf_v3.py", line 188, in __init__
    self._file = mmap.mmap(x.fileno(), 0, access=mmap.ACCESS_READ)
OSError: [WinError 8] Not enough storage is available to process this command

#/Traceback
  
# Description

Apologies for my substandard Python code - I'm a bit new to this. AsamMdf seems a really cool project - really appreciating the speed of it.

I'm having trouble releasing the memory after I've finished with an MDF file.  This code will always process 2 files and then throw the attached exception. I've experimented starting the code on different files and it'll always fail on the 3rd file in the loop, not any specific file. I've tried a number of things to release the memory and I can't see any reference to other methods listed in the API.  I see your benchmark data is based around much smaller file sizes, so perhaps my file size (typically 1Gb) is larger than files you've been testing with.

Is there already a good solution for this?

**Comment by danielhrisca** [comment]
Hello  @Mark0ne ,

you can call ``df.close()`` after you finish processing a file.

From the error it looks like you are running low on free space on your C:/ drive. Maybe you should check it out

**Comment by Mark0ne** [comment]
Thanks for the quick response.
Had tried df.close() previously and had no joy.  Just tried again inserting df.close() above line: del df

Behaviour and Traceback message are unchanged.
Everything is running from C:   >200Gb Free.

**Comment by danielhrisca** [comment]
Can you run with a 64 bit Python?

**Comment by Mark0ne** [comment]
Yes, will try.

Have just stepped through df.close() if it helps:

MyFile.py Main()  Line111: df.close()
asammdf.blocks.mdfv3.close(), line 2142: if self._tempfile is not None:
asammdf.blocks.mdfv3.close(), line 2143: self._tempfile.close()
'tempfile'.close(), line 507: self._closer.close()
'tempfile'.close(), line 452: if not self.close_called:
'tempfile'.close(), line 453: self.close_called = True
'tempfile'.close(), line 454: self.file.close()
asammdf.blocks.mdfv3.close(), line 2144: if self._file is not None and not self._from_filelike:
asammdf.blocks.mdfv3.close(), line 2145: self._file.close()
MyFile.py Main()  Line112: print("Have Run df.close()")

**Comment by Mark0ne** [comment]
Tested on Python 3.6.6 64bit - Runs **without an issue**

.....So is there still a memory management problem with 32-bit ?  For the moment, I guess I'll just stick to 64.

Many thanks for all the help

**Comment by Mark0ne** [comment]
Is .iter_get() appropriate for the above application ?  I couldn't work out how to use it

**Comment by danielhrisca** [comment]
MDF.concatenate(FileList).get(IntChannel)

**Comment by danielhrisca** [comment]
or 
```python
import numpy as np
intVal = 0
for file in FileListManual:
    with MDF(file) as mdf:
        for ch_part in mdf.iter_get(IntChannel):
            intVal += np.sum(ch_part.samples[1:] * np.diff(ch_part.timestamps))
```

**Comment by danielhrisca** [comment]
I've [used a fix to the development branch. Can you check if it works on your 32 bit Python?

**Comment by danielhrisca** [comment]
Yes, I've made a screw-up . Please try the new fix

**Comment by Mark0ne** [comment]
Now works without a problem on Python 3.7.2 32bit.

Many thanks and thanks also for the code tips above - Really appreciate this.
