### ISSUE TITLE
File too big to read

### ISSUE THREAD

**Issue by tidumur** [danielhrisca/asammdf#245]
# Python version

* python version 3.6.8
* os
  * Windows 10
  * Ubuntu 18.04.3 LTS
* asammdf version 5.12.0
* numpy version 1.17.2

# Code 

## MDF version

Mdf file version 4.10

## Code snippet

```python

def getFullChannelList(mdfFile):
    infoPack = mdfFile.info()
    channelTab = []
    for i in range(infoPack['groups']-1):
        key = 'group ' + str(i)
        groupChannelsTab = []
        for j in range(infoPack[key]['channels count']):
            groupChannelsTab.append(mdfFile.iter_get(None,i,j,None,True))
        channelTab.append(groupChannelsTab)
    return channelTab

def trysimpleget(mdfFile):
    infoPack = mdfFile.info()
    tab = []
    for i in range(infoPack['groups'] - 1):
        for j in range(infoPack['group ' + str(i)]['channels count']):
            tab.append(mdfFile.get_channel_metadata(None,i,j))
    return tab

# bigMdfFile is a MDF file version 4.10, containing only one usefull group

tab = getFullChannelList(bigMdfFile)
display = True
for channel in tab:
    for thing in channel:
        pass

simpleTab = trysimpleget(bigMdfFile)
for channel in tab:
    print(channel)

```
  
## Traceback

 `Killed`
  
# Description

I'm trying to read a big MDF file containing a Video Document to print it in real time.

However the uncompressed file is to big to be read in one go (with a 16G RAM), and cutting the file in many subfiles would cause problems for real time processing.

Is there a way to get all data for a given timestamp without loading the whole dataset?

**Comment by danielhrisca** [comment]
Hello @tidumur 

were exactly does it crash? 

From your code you are _getFullChannelList_ returns a list of list or generators (returned by _iter_get_) so I this should not produce high RAM usage, and _trysimpleget_ just returns the Channel objects, which again should not cause problems.

**Comment by tidumur** [comment]
Hello,

It crashes when I try to parse the given generator, here when I print the channels in the second `for` loop

**Comment by danielhrisca** [comment]
```python
tab = getFullChannelList(bigMdfFile)
display = True

# tab is [  [generator ...] ...]
for channel in tab:
    # channel is [generator ...]
    for thing in channel:
        # thing is generator; consuming it should not produce errors since the
        # read fragment size is <=40MB
        pass
```

**Comment by tidumur** [comment]
It's OK when I just print the generator, but when I try to parse it to get to the datas, there is one `thing` that make the execution crash. I am probably not parsing it right but I can't seem to find the good way to do it.

```python
tab = getFullChannelList(bigMdfFile)
display = True
for channel in tab:
    for thing in channel:
        for element in thing :
            print(element)
```
I also have the problem when I try to open the file with the asammdf graphical interface : when I try to display any part of the big group it crashes the tool.

**Comment by danielhrisca** [comment]
please share the output of this snippet

```python
for i, group in enumerate(bigMdfFile.groups):
    print('====', i)
    print(group.data_blocks)
    print(group.channel_group)
```

**Comment by tidumur** [comment]
```
==== 0
[]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff79d203ad8>
==== 1
[]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff79d203ba8>
==== 2
[]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff79d203c78>
==== 3
[]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff79d203d48>
==== 4
[DataBlockInfo(address=0x19, block_type=0, raw_size=1237470, size=1237470, param=0)]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff79d203e18>
==== 5
[DataBlockInfo(address=0x12E20F, block_type=0, raw_size=46420956, size=46420956, param=0)]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff79d203ee8>
==== 6
[]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff78f91f048>
==== 7
[]
<asammdf.blocks.v4_blocks.ChannelGroup object at 0x7ff78f91f118>
```

**Comment by danielhrisca** [comment]
Please run again, to see the channel group info
```python
for i, group in enumerate(bigMdfFile.groups):
    print('====', i)
    print(group.data_blocks)
    print(group.channel_group.samples_byte_nr, group.channel_group.cycles_nr, group.channel_group.invalidation_bytes_nr)
```

**Comment by danielhrisca** [comment]
This doesn't look like such a big file (~50MB ??)

**Comment by tidumur** [comment]
Yes, it's a 54.6 MB file

```
==== 0
[]
38 0 0
==== 1
[]
0 0 0
==== 2
[]
38 0 0
==== 3
[]
0 0 0
==== 4
[DataBlockInfo(address=0x19, block_type=0, raw_size=1237470, size=1237470, param=0)]
38 32565 0
==== 5
[DataBlockInfo(address=0x12E20F, block_type=0, raw_size=46420956, size=46420956, param=0)]
46290696 32565 0
==== 6
[]
38 0 0
==== 7
[]
0 0 0
```

**Comment by danielhrisca** [comment]
> ==== 5
> [DataBlockInfo(address=0x12E20F, block_type=0, raw_size=46420956, size=46420956, param=0)]
> 46290696 32565 0

This is not ok. There is a raw data block of ~40MB, and the channel information is that there are 32565 cycles of 40MB each.

Can you send the file for analysis? you can scramble it using the GUI to hide sensitive information

**Comment by danielhrisca** [comment]
> ==== 4
> [DataBlockInfo(address=0x19, block_type=0, raw_size=1237470, size=1237470, param=0)]

An this is completely wrong: the block start address is inside the file header

**Comment by danielhrisca** [comment]
@tidumur 
I've made a fix. CANape does not complain but I think that the file does not comply with the MDF standard
