### ISSUE TITLE
run the asammdf.exe file, but there is not GUI out.

### ISSUE THREAD

**Issue by tingfenghanlei** [danielhrisca/asammdf#249]
When I run the  asammdf.exe file, there is no gui out. 

asammdf==5.13.1
PyQt5 ==5.13.0
PyQt5-sip = 4.19.18
python-dateutil==2.8.0

Thank you very much.

**Comment by danielhrisca** [comment]
Please run this and share the full error message

```python
from asammdf.gui.asammdfgui import main
main()
```

**Comment by tingfenghanlei** [comment]
Thank you very much. The error is that "Could not load the Qt platform plugin "windows" in "" even though it". And I solve it. 
Add this in to environment variable.
QT_QPA_PLATFORM_PLUGIN_PATH
C:\Python34\Lib\site-packages\PyQt5\plugins
