### ISSUE TITLE
Timestamp issue with some signals

### ISSUE THREAD

**Issue by choo2388** [danielhrisca/asammdf#252]
# Python version
_Please run the following snippet and write the output here_
```
('python=3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC '
 'v.1900 64 bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.17.2'
'asammdf=5.13.6'
```
# Code 

## MDF version
3.00

## Code snippet
```
dat = MDF(modifypath(path) + file, version='4.10')
signal_list=['VeTBNI_n_TurbineSpeed\ECM','Accel_Long\ES610 / AD:1','VeBRKI_Pct_BrakePedalPos\ECM' ]
dat = dat.filter(signal_list)

for sig in dat.iter_channels():
    print(sig.name)
    print('Samples: '+ str(len(dat.get(sig.name).samples)))
    print('Sample values: '+ str(dat.get(sig.name).samples[:10]))
    print('Timestamps: '+ str(len(dat.get(sig.name).timestamps)))
    print('First 10 Timestamp values: '+ str(dat.get(sig.name).timestamps[:10]))
    print('Last 10 Timestamp values: '+ str(dat.get(sig.name).timestamps[-10:]))
    print('\n')
```
## Traceback
None
  
# Description

I have been seeing issues with some signals whose timestamps are not returned properly. This issue does not seem to be common across all my dat files however, I seem to encounter this occasionally. 

I read in a dat file and filtered the signals that I am interested in. Shown below is a quick output where the time stamps for Accel and Turbine Speed seem correct and logical but BrakePedal seems to be totally incorrect. There are no errors being thrown out.

Separate question, did 'time' change to 'timestamps' recently? I had the issue since I was converting my dat signals to dataframe and encountered a keyerror.

Unfamiliar with scramble to send you the file. Can you please walk me through the process and also need your email if I need to send you the file.

Thank you!

![image](https://user-images.githubusercontent.com/47670397/67771915-8eefd500-fa2f-11e9-9bbb-69495e60c74a.png)

**Comment by danielhrisca** [comment]
Hello @choo2388 ,

to scramble the file you can use the graphical interface

![scramble](https://user-images.githubusercontent.com/20952040/67860733-474c7480-fb27-11e9-98e0-d5e5f078d931.gif)

**Comment by choo2388** [comment]
Hi Daniel,

I have the dat file ready to share. How do I share it with you (email)?
Thanks.

**Comment by danielhrisca** [comment]
Please use the e-mail address from my profile https://github.com/danielhrisca

**Comment by choo2388** [comment]
@danielhrisca : yes thats true it works when you open using asammdf gui or mda.

However if I open using python, there is some issue. Were you able to see any issues in jupyter notebook?

Thanks.

**Comment by danielhrisca** [comment]
The channel looks ok in the Jupyter notebook

![image](https://user-images.githubusercontent.com/20952040/67899853-d67b7b80-fb6b-11e9-8490-56e38ba4ba60.png)

**Comment by choo2388** [comment]
Great, thanks for checking Daniel. I have no idea why I was facing this issue.

I was able to get the correct output using a new install of python
