### ISSUE TITLE
asammdf.concatenate doesn't close files

### ISSUE THREAD

**Issue by s1512783** [danielhrisca/asammdf#253]
# Python version
```
('python=3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.17.3'
asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip
asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip
'asammdf=5.13.1'
```

# Code 

  ## MDF version
4.11

  ## Code snippet
```
from asammdf import MDF, Signal
import numpy as np
import os


# create dummy files and save them

timestamps = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=np.float32)

s_int32 = Signal(samples=np.array([-20, -10, 0, 10, 20], dtype=np.int32),
                 timestamps=timestamps,
                 name='Int32_Signal',
                 unit='i4')

file_list = []

for i in range(3):
    with MDF(version='4.10') as mdf4:
        signals = [s_int32]
        mdf4.append(signals, 'Created by Python')
        name = 'file%d.mf4' % i
        file_list.append(name)
        mdf4.save(name, overwrite=True)

# concatenate files
with MDF(version='4.11') as mdf4:
    mdf_concat = mdf4.concatenate(file_list)

# try deleting them
for f in file_list:
    os.remove(f)
```
  
  ## Traceback
File can't be deleted/moved by other processes:
```
Traceback (most recent call last):
  File "mdf_error.py", line 31, in <module>
    os.remove(f)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'file0.mf4'
```

# Description
I think that when I give a list of strings to `asammdf.concatenate`, it opens the files and doesn't give the user a way to close them.

My workflow is: 
1. Download files from the internet to a temporary folder
2. Get a list of locations of the downloaded files
3. Concatenate them with `asammdf.concatenate`
4. Process the concatenated file
5. Append results to database
6. Programatically delete the downloaded mdf files (and the entire temporary folder)

I pass data between MATLAB and Python to do that (each does a little bit of the processing), and when MATLAB tries to delete files in step 6, it can't, because Python still has them open.

I tried calling `.close()` on the concatenated mdf file. I tried passing a list of `asammdf.MDF` objects to `concatenate`. I tried closing the objects individually and then the concatenated file. None of those things helped.

Is there a way to somehow release the files while the Python interpreter is still running?

**Comment by danielhrisca** [comment]
@s1512783 
please check the development branch code. I've pushed a fixed for this issue

**Comment by s1512783** [comment]
@danielhrisca 
I can confirm that the issue has been resolved now. I tested with the short snippet I submitted above and inside my MATLAB-python framework and both work just fine. Thanks for the super quick response! 

I don't know how this works, should I close the issue or will you do it?
