### ISSUE TITLE
Problem with multiplexed CAN messages

### ISSUE THREAD

**Issue by mikesmitti** [danielhrisca/asammdf#257]
# Python version
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit '
'(Intel)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.4'
'asammdf=5.13.9'
# Code 

  ## MDF version
4.10
  ## Code snippet
-
  
  ## Traceback
 no traceback
  
# Description
I found an issue with multiplexed messages:
Let´s say, I have a message with 25 states of multiplexers (74 signals of voltage for example, the one missing is important later on), 3 in every message, plus the muxer-state. 
In the last muxer-state, I have only 2 good signals and 1 gets sent with the default value, lets say 100V, for signal no 75.

Now when opening a mf4 file with asmammdf, and looking for one of the signals, i get voltage values in a range I expect.
But every 25th value in this one signal is the default 100V value.

I used the select method for the reading.

In the same can system I got temperatures as well. Same topic, every 25th value is the default value within one signal.

I recorded the file with CANoe11 SP4.
Replaying the file shows now signs of "wrong" values.

Best regards,
mike

**Comment by danielhrisca** [comment]
It's hard to grasp what is going on. It would really help if you could send a scrambled file.

**Comment by mikesmitti** [comment]
Hello and thx for reply.
Sorry, it is another costumers project.

It is no new issue with 5-13-9, I had it already at least with 5-13-6.

**Comment by danielhrisca** [comment]
@mikesmitti does it work with asammdf 5.17.3?

**Comment by danielhrisca** [comment]
I think this is solved now. Reopen if you still have problems
