### ISSUE TITLE
only one plot appear  which means two or more supplot can not open at the same time.

### ISSUE THREAD

**Issue by zhoubo-lab** [danielhrisca/asammdf#258]
1: the version is 5.13.10
2: As the following figure show, the GUT is differetn with gitHub version.
3: ask help to fix it.
4: thanks very much.
[
![image](https://user-images.githubusercontent.com/57513154/68455415-4f4a9980-0236-11ea-9ff1-544defc5a6f5.png)
](url)

**Comment by danielhrisca** [comment]
Go to the menu and chrk the subplots box, then restart the application. After that each time you press the plot button a new subplot will be added

**Comment by zhoubo-lab** [comment]
Thank very much. It already work.
