### ISSUE TITLE
Question: data structures of given mdf file and accessing signaldata

### ISSUE THREAD

**Issue by white91wolf** [danielhrisca/asammdf#260]
Hey, i have a question about the data structure of the mdf(4) file i have. I'm a bit confused about the different ways of accessing the values / informations of each sensor.

In my understanding, there are 3 main datastructures / objects: group, channel, signal

On the one side i can access directly from the mdf file object the group and for each group different channels if there are some given. There are the meta data of the individual object - so far so good. But can i also access the signal of the channel or how are they related? 

I also got the point of the description on the page:

> The Signal represents a channel described by it’s samples and timestamps. It can perform arithmetic operations against other Signal or numeric types. The operations are computed in respect to the timestamps (time correct). The non-float signals are not interpolated, instead the last value relative to the current timestamp is used. samples, timestamps and name are mandatory arguments.

I get MDF4 files (version:  4.10)  from a DAQ system.

At the moment i access the values like this:

```
 for group in self._mdf.groups:
                print('cur group ',type(group).__name__)
                for channel in group.channels:  
                    print('-' * 80)
                    print('cur channel ',type(channel).__name__)
                    
                    print(channel.name)
                    print(' range: [%f, %f] %s' % (channel.min_raw_value,
                                                channel.max_raw_value,
                                                channel.unit))
                    if channel.source:
                        print('channel.source :' + type(channel.source).__name__)
                        print(channel.source.name + ':')
                    print(channel)
```

and the signal values:

```
for sig in self._mdf.iter_channels():
      print(sig.samples)
```

just some example code...

What is confusing me is the relationship between channel and signal. For example the signal contains a source and comment where a lot of informations are stored like in the channel.
I currently try to analyse the differences but maybe there are some references - i mean i got the documentation https://buildmedia.readthedocs.org/media/pdf/asammdf/master/asammdf.pdf - for example 2.3 for MDF4 class - but i don't get the deeper thought of the relation of the classes?

Example Channel:
```
<Channel (name: M08_AXIS, unit: gforce, comment: <CNcomment><TX></TX><common_properties><e name="module_fw">OSV-a01.15/b00.64,APPV-b00.73</e><e name="module_mid">7-3-6382178-602</e><e name="module_snr">991124</e><e name="sampling_rate">40000.000000</e></common_properties></CNcomment>, address: 0x598,
     conversion: <ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: None, address: 2208, fields: ['a:1.0', 'address:2208', 'b:0.0', 'block_len:96', 'comment:', 'comment_addr:0', 'conversion_type:1', 'flags:0', 'formula:', "id:b'##CC'", 'inv_conv_addr:0', 'links_nr:4', 'max_phy_value:0.0', 'min_phy_value:0.0', 'name:', 'name_addr:0', 'precision:0', 'ref_param_nr:0', 'referenced_blocks:None', 'reserved0:0', 'unit:', 'unit_addr:0', 'val_param_nr:2'])>,
     source: <SourceInformation (name: Sensor Information, path: , comment: <SIcomment><TX></TX><common_properties><e name="sensor_description">M08 Hebeachse</e><e name="sensor_snr">5611806</e><e name="sensor_type">8702B50</e></common_properties></SIcomment>, address: 0x660, fields: ['address:1632', 'block_len:56', 'bus_type:0', 'comment:<SIcomment><TX></TX><common_properties><e name="sensor_description">M08 Hebeachse</e><e name="sensor_snr">5611806</e><e name="sensor_type">8702B50</e></common_properties></SIcomment>', 'comment_addr:1688', 'flags:0', "id:b'##SI'", 'links_nr:3', 'name:Sensor Information', 'name_addr:1896', 'path:', 'path_addr:0', 'reserved0:0', "reserved1:b'\\x00\\x00\\x00\\x00\\x00'", 'source_type:0'])>,
     fields: address:1432, attachment:None, attachment_nr:0, bit_count:32, bit_offset:0, block_len:160, byte_offset:8, channel_type:0, comment:<CNcomment><TX></TX><common_properties><e name="module_fw">OSV-a01.15/b00.64,APPV-b00.73</e><e name="module_mid">7-3-6382178-602</e><e name="module_snr">991124</e><e name="sampling_rate">40000.000000</e></common_properties></CNcomment>, comment_addr:1944, component_addr:0, conversion:<ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: None, address: 2208, fields: ['a:1.0', 'address:2208', 'b:0.0', 'block_len:96', 'comment:', 'comment_addr:0', 'conversion_type:1', 'flags:0', 'formula:', "id:b'##CC'", 'inv_conv_addr:0', 'links_nr:4', 'max_phy_value:0.0', 'min_phy_value:0.0', 'name:', 'name_addr:0', 'precision:0', 'ref_param_nr:0', 'referenced_blocks:None', 'reserved0:0', 'unit:', 'unit_addr:0', 'val_param_nr:2'])>, conversion_addr:2208, data_block_addr:0, data_type:4, display_name:, dtype_fmt:<f4, flags:8, id:b'##CN', links_nr:8, lower_ext_limit:0.0, lower_limit:0.0, max_raw_value:50.0, min_raw_value:-50.0, name:M08_AXIS, name_addr:1592, next_ch_addr:2336, pos_invalidation_bit:0, precision:0, reserved0:0, reserved1:0, source:<SourceInformation (name: Sensor Information, path: , comment: <SIcomment><TX></TX><common_properties><e name="sensor_description">M08 Hebeachse</e><e name="sensor_snr">5611806</e><e name="sensor_type">8702B50</e></common_properties></SIcomment>, address: 0x660, fields: ['address:1632', 'block_len:56', 'bus_type:0', 'comment:<SIcomment><TX></TX><common_properties><e name="sensor_description">M08 Hebeachse</e><e name="sensor_snr">5611806</e><e name="sensor_type">8702B50</e></common_properties></SIcomment>', 'comment_addr:1688', 'flags:0', "id:b'##SI'", 'links_nr:3', 'name:Sensor Information', 'name_addr:1896', 'path:', 'path_addr:0', 'reserved0:0', "reserved1:b'\\x00\\x00\\x00\\x00\\x00'", 'source_type:0'])>, source_addr:1632, sync_type:0, unit:gforce, unit_addr:2304, upper_ext_limit:0.0, upper_limit:0.0)>

```
Example Signal:

```
<Signal M08_AXIS:
 	samples=[ 0.07386024  0.02537377  0.01359335 ...  0.02716956 -0.03724561  -0.03552165]
 	timestamps=[1.56881670e+09 1.56881670e+09 1.56881670e+09 ... 1.56881672e+09   1.56881672e+09 1.56881672e+09]
 	invalidation_bits=None
 	unit="gforce"
 	conversion=None
 	source=SignalSource(name='Sensor Information', path='', comment='<SIcomment><TX></TX><common_properties><e name="sensor_description">M08 Hebeachse</e><e name="sensor_snr">5611806</e><e name="sensor_type">8702B50</e></common_properties></SIcomment>', source_type=0, bus_type=0)
 	comment="<CNcomment><TX></TX><common_properties><e name="module_fw">OSV-a01.15/b00.64,APPV-b00.73</e><e name="module_mid">7-3-6382178-602</e><e name="module_snr">991124</e><e name="sampling_rate">40000.000000</e></common_properties></CNcomment>"
 	mastermeta="('Time', 1)"
 	raw=False
 	display_name=
 	attachment=()>
```

Hope i can get some enlightenment.

**Comment by danielhrisca** [comment]
The channels that you find in the internal structure of the MDF object are holding just the metadata.

When you call _get_ or _iter_channels_ the actual measured samples are extracted and Signal objects are returned. The Signal object are decoupled form the MDF object, meaning that if you modify them the change will not be made in the MDF object.

**Comment by white91wolf** [comment]
Thanks that what i was thinking,
I have another question: my java applications now needs to call this library to parse a lot of given mfd4 files. I searched a lot but doesnt found a good solution java native. So i wrote a java interface and implemented this on python side where i use the asammdf lib thanks to py4j. This works fine so far. but what would you recommend how to use the lib in java without too much overhead but maybe scaleable. i have now the problem, that i start the python process on java side and when i finished everything i close the connection and python should close. sometimes it does sometimes not. and then i cant convert a new one cause socket is used.
I also found jython but seems kinda dead and dont know how good this works with imports and dependencies of those imports.

**Comment by danielhrisca** [comment]
Hello @white91wolf 

I really don't know what to say. I've never used this java library 

Maybe you can use the  python_proxy_port argument in the JavaGateway (see https://www.py4j.org/py4j_java_gateway.html).

In the python script make sure to call _close_ on the opened MDF  objects
