### ISSUE TITLE
when I concatenate two dat files, it raise MdfException: wrong encoding "None" for string signal 

### ISSUE THREAD

**Issue by zhoubo-lab** [danielhrisca/asammdf#261]
the issue as :
encoding = signal.encoding
                print ('encoding = ',encoding) # here is I edit it to see encoding value = None, So rase a MdfException
                samples = signal.samples
                sig_dtype = samples.dtype
                print ('sig_dtype = ',sig_dtype) # here is I edit,
                if encoding == "utf-8":
                    data_type = v4c.DATA_TYPE_STRING_UTF_8
                elif encoding == "latin-1":
                    data_type = v4c.DATA_TYPE_STRING_LATIN_1
                elif encoding == "utf-16-be":
                    data_type = v4c.DATA_TYPE_STRING_UTF_16_BE
                elif encoding == "utf-16-le":
                    data_type = v4c.DATA_TYPE_STRING_UTF_16_LE
                else:
                    raise MdfException(f'wrong encoding "{encoding}" for string signal')

**Comment by danielhrisca** [comment]
hello @zhoubo-lab can you also share the full error message to see were exactly the error is triggered?

**Comment by zhoubo-lab** [comment]
Ok, as the following show: 

  File "<ipython-input-1-bb8357149393>", line 1, in <module>
    runfile('Z:/01_Ln/Ln_Python/Python_asammdf/zb_asammdf_concatenae_test.py', wdir='Z:/01_Ln/Ln_Python/Python_asammdf')

  File "C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "Z:/01_Ln/Ln_Python/Python_asammdf/zb_asammdf_concatenae_test.py", line 28, in <module>
    zb_list_file()

  File "Z:/01_Ln/Ln_Python/Python_asammdf/zb_asammdf_concatenae_test.py", line 23, in zb_list_file
    zb_import.concatenate(zb_crt_list, version='4.10', sync=True, add_samples_origin=True)

  File "C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 2147, in concatenate
    merged.append(signals, common_timebase=True)

  File "C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3672, in append
    raise MdfException(f'wrong encoding "{encoding}" for string signal')

MdfException: wrong encoding "None" for string signal

**Comment by danielhrisca** [comment]
@zhoubo-lab please try the development branch code

**Comment by zhoubo-lab** [comment]
Dear danielhrisca 
Branch code works. Thanks very much for the great fix. you are expert.
Just one consult： Are you the author of numpy and Pandas?  because I see that you Repositories have those two pkgs.

**Comment by danielhrisca** [comment]
😃 I'm not the author of numpy and pandas; I just have forks of those project and I've only send some fixes from time to time 
![image](https://user-images.githubusercontent.com/20952040/68649393-481fd600-052b-11ea-8373-0d484ea5a87e.png)

**Comment by zhoubo-lab** [comment]
understand.
