### ISSUE TITLE
Missing package in asammdf.exe

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#263]
# Code 

  ## MDF version
5.13.1
  
  ## Traceback
Traceback (most recent call last):
  File "c:\tools\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tools\anaconda3\Scripts\asammdf.exe\__main__.py", line 5, in <module>
  File "c:\tools\anaconda3\lib\site-packages\asammdf\gui\asammdfgui.py", line 7, in <module>
    from asammdf.gui.widgets.main import MainWindow
  File "c:\tools\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 10, in <module>
    import pyqtgraph as pg
ModuleNotFoundError: No module named 'pyqtgraph'
  
# Description

I use your standalone application asammdf.exe to view mf4-Files. Would it be possible to include the pyqtgraph package in to your stand alone application? Currently the application crashes because of the missing pyqtgraph package. I do start the application by double-click and wouldn't see the above trace messages. As workaround it is possible to install pyqtgraph in my side packages. There your application will find them and runs correct. 

_Please describe the issue here._

**Comment by danielhrisca** [comment]
I think you just need to install the _gui_ dependencies in your anaconda distribution

```
pip install asammdf[gui]
```

this should pull PyQt5, pyqtgraph and psutil

**Comment by Lama09** [comment]
Thanks for your quick response. What is the reason for not compiling the gui dependencies in to the executable?

**Comment by danielhrisca** [comment]
That exe is created automatically when the package is installed, and all it does is just start a python interpreter and call the specified function, it does not actually bundle the application and dependencies. You need to have the dependencies installed for it to work correctly

**Comment by Lama09** [comment]
Ok, maybe you can consider to do a stand alone application in the future. This is in my point of view, what the standard user would expect if an executable is provided.

**Comment by danielhrisca** [comment]
@Lama09 

you can get a stand alone build from here https://ci.appveyor.com/project/danielhrisca/asammdf/branch/master/job/ypvs3pixop8rf35i/artifacts
