### ISSUE TITLE
Channel name 'time' changes to 'timestamps'

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#264]
## MDF version
5.13.10

  ## Code snippet
 with MDF(file) as mdf_file:
                  data_frame = mdf_file.to_dataframe(channels=labels, raster=step_size,time_from_zero=True) 
  
  
# Description
I use the to_dataframe() function to export my data to a pandas dataframe. In an early version the channel name for time was 'time'. Now it changed to 'timestamps'. Would it be possible to control the name by flag? Otherwise I have to change a lot of my scripts.

_Please describe the issue here._

**Comment by danielhrisca** [comment]
Apparently there were problems that required this change https://github.com/danielhrisca/asammdf/commit/8df0cf04195c4ff47f1919e83a82f8245e440631

**Comment by Lama09** [comment]
Thanks for sharing the link. Unfortunately I'm not so familiar with the GitHub Repositories. I only can see the changes within the code, but the reason for this I can't find. What dos mean : …makes it compatible with AWS?

**Comment by danielhrisca** [comment]
> What dos mean : …makes it compatible with AWS?

_ don't have the reference anymore but some users had issues with the Amazon Web Services (AWS) cloud_
