### ISSUE TITLE
GUI: Signals disappear from plot (Gap handling for NAN/Inf)

### ISSUE THREAD

**Issue by hendrikp** [danielhrisca/asammdf#268]
# Python version
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51)

## MDF version
mdf file format 4.11
asammdf gui 5.13.11

# Description
When a signal channel contains NaN and/or inf those channels are not plotted with the GUI, When activating sample point display with '.' key the valid sample point appear. (when scrolling closly into the range of only valid numbers of that signal the line reappears. However as soon as one nan or inf appears in visible range it disappears again). 

+/-NaN and +/-Inf values should be handled as gaps for the plot.

**Comment by danielhrisca** [comment]
Hello Hendrick,

I will try this solution later https://stackoverflow.com/questions/34289128/none-values-in-pyqtgraph

**Comment by danielhrisca** [comment]
Hello Hendrick,

I've pushed a fix to the development branch. Please check if it works

**Comment by hendrikp** [comment]
I tried it out and it did not work, same behaviour as before. (asammdf5.13.14dev1)

**Comment by hendrikp** [comment]
Possibly also the autoscale functionality could be changed to ignore the nan/inf values as auto-scaling for those channels also didnt work.

**Comment by danielhrisca** [comment]
@hendrikp 

I've improved the fit and stack handling for signals that contain NaN and inf values
It could be useful to toggle the points, in this case you will always see the points even if the lines disappear
![image](https://user-images.githubusercontent.com/20952040/69477932-00376380-0df5-11ea-889c-295a39270d8e.png)
vs 
![image](https://user-images.githubusercontent.com/20952040/69477935-07f70800-0df5-11ea-84e5-be0590daea71.png)
