### ISSUE TITLE
search function of singal in setting is deleted. It is wised to be added.

### ISSUE THREAD

**Issue by zhoubo-lab** [danielhrisca/asammdf#269]
Dear Danielhrisca
(1): I update the version to the 5.13.15. But found the search function of singal in setting is deleted, which is very helpful function. 
Consultation: is it add this function in next release version?  because it is helpful and this function workwell in 5.13.11 version.

**Comment by danielhrisca** [comment]
Hello you can use the keyboard shortcut Ctrl. +F to search

**Comment by zhoubo-lab** [comment]
Thanks very much, It works
