### ISSUE TITLE
Remove autocompletion of the search window

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#274]
Hi @danielhrisca,

I want to remove the autocompletion of the search window. For big measurement, it freezes the window. Instead I suggest to let the user press enter or click a button to trigger the search.

**Comment by danielhrisca** [comment]
Hello Julien,

I proposed another solution: perform the search when Enter is pressed, instead of for each key press. I think it's better to avoid needing to make another click just to preform the search. 

Let me know if this solution works for you

**Comment by JulienGrv** [comment]
I like it a lot :)

**Comment by danielhrisca** [comment]
@JulienGrv 

you should try the new 5.14.5 release: loading the file in the GUI is a lot faster now for large channel count
