### ISSUE TITLE
How to generate NOVALUES?

### ISSUE THREAD

**Issue by mxcd** [danielhrisca/asammdf#276]
Hi,

I am having trouble with a file that is, loaded in NI DIAdem, showing socalled "NOVALUEs". These are points in time (having a single common time channel) that do not have a respective value matching to the one in the common time channel (see image)
These NOVALUEs can occur at any point of time in any channel.

Loading one of these channels with python gives me a channel that only contains the values that are not being shown as NOVALUES in DIAdem.

I could work with that for data evaluation, but I need to export it again with a common time channel. Problem is, that I can't get the `MDF4.append()` method to take Signals with different lengths while stating `common_timebase=True`.

How can I create the file accordingly?

Simply loading such a mf4 file and saving it again creates the desired result.

![NOVALUE_IMAGE](https://user-images.githubusercontent.com/7310764/70072244-e36e0d80-15f6-11ea-9cf5-b86eac44388f.PNG)

BTW: Trying to load one of these files in the GUI results in an error as well - depending on the outcome of this issue I might open another one
![mf4_load_error](https://user-images.githubusercontent.com/7310764/70072751-e3224200-15f7-11ea-8019-be4af5363b50.PNG)

**Comment by danielhrisca** [comment]
Hello Max,

the _common_timebase_ argument is used as an optimization. Just leave it to False and you should be fine appending the channels

**Comment by mxcd** [comment]
Hi @danielhrisca,
thanks for this information.
By doing so, values are being generated within the "gap" interpolation linear from gap start to gap end value.
Please try this MCVE (sorry for not attaching the data with the NOVALUES, but confidential...):

```
import numpy as np
from asammdf import MDF, Signal

timestamps1 = []
timestamps2 = []
values1 = []
values2 = []

for i in range(1000):
    if 200 < i < 400:
        pass # data gap will be here
    else:
        values1.append(np.sin(i/10))
        timestamps1.append(i / 10)

    values2.append(np.cos(i/10))
    timestamps2.append(i/10)


sig1 = Signal(samples=values1, timestamps=timestamps1, name="CH1")
sig2 = Signal(samples=values2, timestamps=timestamps2, name="CH2")

with MDF(version='4.10') as mdf4:
    mdf4.append([sig1, sig2], common_timebase=False)
    mdf4.save("out.mf4", compression=1, overwrite=True)

```

**Comment by danielhrisca** [comment]
This is totally correct. Append puts all the signals in a new channel group and by definition the channels in a channel group have a common master channel (usually the same time base).

**Comment by danielhrisca** [comment]
> BTW: Trying to load one of these files in the GUI results in an error as well - depending on the outcome of this issue I might open another one

This needs to be investigated. What asammdf version do you use?

**Comment by mxcd** [comment]
Why is it correct, that new value points are being generated to interpolate the missing ones? Is there any way to avoid this behavior?

**Comment by danielhrisca** [comment]
> Why is it correct, that new value points are being generated to interpolate the missing ones? Is there any way to avoid this behavior?

You have 2 options if you don't like desire the interpolation
1. call _append_ for each channel individually: this will take longer time and will result in a larger file size
2. take of grouping the channels based on their time and call _append_ with those subsets: in your screenshot (if you don't count the index and timestamps columns) you would group columns 1,2,7,8 together, and columns 3,4,5,6 together
