### ISSUE TITLE
to_dataframe with empty_channels="zeros" does not fill empty channels

### ISSUE THREAD

**Issue by MarcelWiedenmann** [danielhrisca/asammdf#279]
# Python version
Output of the provided snippet:
```
'python=3.8.0 (default, Nov  6 2019, 21:49:08) \n[GCC 7.3.0]'
'os=Linux-5.3.0-24-generic-x86_64-with-glibc2.10'
'numpy=1.17.4'
'asammdf=5.14.5'
```
# Code 

## MDF version
Any

## Code snippet
```python
from asammdf import MDF, Signal

with MDF() as mdf:
    mdf.append(Signal(timestamps=[], samples=[], name='empty'))
    mdf.append(Signal(timestamps=[2], samples=[2], name='non-empty'))
    df = mdf.to_dataframe(empty_channels='zeros')
    print(df)
```
## Traceback
```
Traceback (most recent call last):
  File "/home/marcel/.PyCharmCE2019.3/config/scratches/scratch.py", line 25, in <module>
    df = mdf.to_dataframe(empty_channels="zeros")
  File "/home/marcel/miniconda3/envs/debugasam/lib/python3.8/site-packages/asammdf/mdf.py", line 3714, in to_dataframe
    df[channel_name] = pd.Series(sig.samples, index=sig.timestamps)
  File "/home/marcel/miniconda3/envs/debugasam/lib/python3.8/site-packages/pandas/core/series.py", line 300, in __init__
    raise ValueError(
ValueError: Length of passed values is 1, index implies 0
```
# Description
Expected behavior of the above snippet would be to print something along the lines of:
```
            empty  non-empty
timestamps                  
0.0             0          2
```
That is, channels without samples should be filled with zeros. Instead it fails with the above error that suggests that the empty channel was not filled.

**Comment by MarcelWiedenmann** [comment]
Oh, additionally: Was the "zeros" option intended to work with non-numeric data such as strings or what should happen in such scenarios?

**Comment by danielhrisca** [comment]
Hello Marcel, please check the fix in the  development branch

> Oh, additionally: Was the "zeros" option intended to work with non-numeric data such as strings or what should happen in such scenarios?

"zeros" will create an np.array with the dtype of the channel

**Comment by MarcelWiedenmann** [comment]
Works - awesome, thanks!
