### ISSUE TITLE
to_dataframe "creates false data" when ChannelGroups don't start at the same time

### ISSUE THREAD

**Issue by MaximeLecuona** [danielhrisca/asammdf#281]
('python=3.6.8 (default, Apr 25 2019, 21:02:35) \n'
 '[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]')
'os=Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-redhat-7.4-Maipo'
'numpy=1.16.1'
'asammdf=5.14.5'
  ## MDF version
  version 4.10

  Hi,

So, I don't actually get an error, just a result that doesn't fit with what I need. 
I'm working with data logged across multiple networks, and they don't all wake up at the same time. So I could have a ChannelGroup with a time channel starting at 0.1s and another one with a time channel starting at 100s
When I use to_dataframe to resample my data, I would like to have the ability to get an output where the channels that weren't broadcasting for the first 100s are set to Nan for that period of time, and then are interpolated to the chosen raster.
Currently, they appear to have their first value set as a constant for the first 100s. (the only parameter I am setting in to_dataframe is the raster)

**Comment by danielhrisca** [comment]
Hello Maxime,

I've added the _interpolate_outwards_with_nan_ argument to the _to_dataframe_ and _iter_to_dataframe_ methods (the default is False). I'm don't really like the name of this argument, so it might change in the release code. 

Please give it a try to see if the functionality is correct

**Comment by MaximeLecuona** [comment]
I tried it, an get this error : to_dataframe() got an unexpected keyword argument 'interpolate_outwards_with_nan'

I tried updating my version of asammdf, but it looks like I already had the latest.

Thanks for getting back to me.

**Comment by danielhrisca** [comment]
Use the development branch code

**Comment by MaximeLecuona** [comment]
Hi, 

I just tested it, and it's exactly what I need. Thanks a lot
