### ISSUE TITLE
Merge mdf Files results with gaps 

### ISSUE THREAD

**Issue by white91wolf** [danielhrisca/asammdf#282]
# Python version
3.7.5

# Code 
filenames = ['file1.mf4', file2.mf4', file3.mf4', file4.mf4']
MDF.concatenate(filenames)

# Description
Hey I am facing the following problem. I have a lot of md(f)4 files which all contain 20 sec of many channels of sensor values at 40kHz Samplerate. Now i want to create some visual outputs of many minutes. Therefore i am "merging" or more like concatenate the mdf files. The strange thing is, that in the merged output mdf the samples arent right in time: between the samples of each file is a gap of the original file sample length?!
I checked if i have some errors in the original data but in matlab and the files individually everything is fine. Only after the merge the samples are off.

Matlab Output:
'1570202138.79905 sec'
'1570202138.79908 sec'
'1570202138.7991 sec' <-- last sample of first file
'1570202138.79913 sec' <-- first sample of new file
'1570202138.79915 sec'

python output after merge:
1570202138.79905
1570202138.799075
1570202138.7991 <-- last sample of first file
1570202158.799125 <-- first sample of new file
1570202158.79915

Like you can see the first sample of the new file is exactly 20 sec off.

![tollerTest_cut](https://user-images.githubusercontent.com/5691653/71100488-6b3a4700-21b5-11ea-8146-924ee136bcf4.png)

  ## MDF version
  4.1

**Comment by danielhrisca** [comment]
Please run this snippet

```python
filenames = ['file1.mf4', 'file2.mf4', 'file3.mf4', 'file4.mf4']
for file in filenames:
    mdf = MDF(file)
    print(file)
    print(mdf.header.start_time)
    
    timestamps = []
    for i, gp in enumerate(mdf.groups):
        master = mdf.get_master(i)
        if len(master):
            timestamps.append(master[0])
    if timestamps:
        print(min(timestamps))
    else:
        print('empty')
```

Also run the concatenate method with _sync=False_ (see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.concatenate)

```python
filenames = ['file1.mf4', 'file2.mf4', 'file3.mf4', 'file4.mf4']
MDF.concatenate(filenames, sync=False)
```

**Comment by white91wolf** [comment]
Thanks the sync flag seems to do the trick.

but here the output of your code (used only 3 files):

> .../file_2019-10-04T15_15_19Z.mf4
> 2019-10-04 15:15:19+00:00
> 1570202118.799125
> .../file_2019-10-04T15_15_39Z.mf4
> 2019-10-04 15:15:39+00:00
> 1570202138.799125
> .../file_2019-10-04T15_15_59Z.mf4
> 2019-10-04 15:15:59+00:00
> 1570202158.799125

python output of the merged mdfs:
1570202138.79905
1570202138.799075
1570202138.7991
1570202138.799125 <-- now fine without the 20sec gap
1570202138.79915

so its fine now. but for my understanding this seems to be a bug or where does the gap between the files come from?

**Comment by danielhrisca** [comment]
The recording software does not set the measurement header timestamp correctly, since I assume these measurements are parts of a continuous measurement split into multiple files. All the measurements should have the same header timestamp of ``2019-10-04 15:15:19+00:00``; instead the header timestamp is incremented by 20s for each measurement. 

The idea is that all the signal timestamps ( 1570202118.799125 for example) in a MDF file are relative to the header timestamp. In your case they seem to be relative to the first measurement's timestamp. 

For a fix try this snippet:

```python
filenames = ['file1.mf4', 'file2.mf4', 'file3.mf4', 'file4.mf4']
files = [MDF(file) for file in filenames]
for file in files[1:]:
    file.header.start_time = files[0].header.start_time
MDF.concatenate(filenames)
```

**Comment by white91wolf** [comment]
ahh okay. i get it. so sorry no bug. or more like a bug on the DAQ side. I will write the manufacture of our measurement hardware.

Thanks a lot for the info and support.

One little question. i have to evaluate like 70TB of data every 2 months and now i am trying to automate a lot of it.
first in matlab but here i get a lot of memory problems cause matlab can't handle it very good, even now where i am clearing every variable after i does not need it anymore. Now im switching to python and i even now see a huge performance increase to matlab. but maybe you have some tipps how i can get more performance out of it - maybe prealocate some ram for the merged mdf file - but i think you already doing that. at the moment im only ploting the samples and i read the https://asammdf.readthedocs.io/en/latest/tips.html but there is nothing i can use at the moment.
also like i mentioned i have a lot of file and the python script will have to run like weeks and here i hope i wont get any memory issues - maybe you know some things of your lib which i have to clear/delete manualy?

**Comment by danielhrisca** [comment]
I'll have to take a look at your processing scripts. Please send them the email address found on my profile page

**Comment by danielhrisca** [comment]
@white91wolf you can now use the _iter_to_dataframe_ method to get chunks as pandas data frames. This will certainly avoid any out of memory errors.

Another question for you: do you need dat from a file multiple times or do you only touch the file once in your data analysis scripts?

**Comment by white91wolf** [comment]
at the moment and i think this wont change i touch the files only once to load the data in memory and make different dsp operations.

and chunks (frames) do not really help i think i even concatenate / merge 15 Files at the moment. (Each file got 20 sec of sensor signal data)

as you might realised i have at the moment problems with using multicore in linux. if i fixed that i will check memory optimizion - but at the moment my script runs multiple days without any problems so i have a good feeling :)

**Comment by danielhrisca** [comment]
Once the files are concatenated do you read all the channels from the output file, or just a smaller subset?

Using the development branch code you could test the experimental column oriented storage for the mdf v.420 format. This can speed things up if you don't need all the channels

```python
out = MDF.concatenate(input_files_list, version='4.20')
# .. further processing 
```
