### ISSUE TITLE
ModuleNotFoundError: *No module named 'mfile'*

### ISSUE THREAD

**Issue by EbATpy** [danielhrisca/asammdf#283]
('python=3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.17.3'

Error description!
QGridLayoutEngine::addItem: Cell (2, 2) already taken
QMdiSubWindow::setSystemMenu: system menu is already set
Traceback (most recent call last):
  File "C:\Users\bz63yj\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf-5.14.3-py3.7.egg\asammdf\gui\widgets\file.py", line 92, in __init__
    from mfile import ERG, BSIG
ModuleNotFoundError: **No module named 'mfile'**

**Comment by danielhrisca** [comment]
Hello @EbATpy do you mean to open erg files?

**Comment by EbATpy** [comment]
Hello yes

**Comment by EbATpy** [comment]
from mfile import ERG, BSIG  is not found!

**Comment by danielhrisca** [comment]
I'm sorry to disappoint you. _mfile_ is an internal package that we use at work. It's not available on github or pypi

**Comment by EbATpy** [comment]
I wanted to convert CarMaker file to mdf file.

**Comment by danielhrisca** [comment]
Hello Sebastian,

use this Christmas present: https://github.com/danielhrisca/mfile

**Comment by EbATpy** [comment]
Thank you, I'll give it a try
