### ISSUE TITLE
record_id error for unsorted DataGroup in mdf_v4._sort

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#284]
Hi Daniel,

I have a segmentation fault with the newest version when reading an MDF file, so I decided to downgrade to the version 5.12.0, before the introduction of the C extensions, to get a trace and be able to debug.

Now, here is the issue trace I get with the version 5.12.0:

```console
Exception has occurred: KeyError
3840
  File "C:\git\asammdf\asammdf\blocks\mdf_v4.py", line 6273, in _sort
    rec_size = cg_size[rec_id]
  File "C:\git\asammdf\asammdf\blocks\mdf_v4.py", line 554, in _read
    self._sort()
  File "C:\git\asammdf\asammdf\blocks\mdf_v4.py", line 263, in __init__
    self._read(mapped=True)
  File "C:\git\asammdf\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\git\asammdf\bug.py", line 20, in <module>
    mdf = asammdf.MDF(path)
```

The error is raised while sorting an unsorted DataGroup that contains more than one ChannelGroup. When looking in MDF Validator, something bothers me with the channel groups in this data group:

- there is 2116 channel groups
- the 1st one has a record_id of 2115
- the 2110th one has a record_id of 1
- the 5 last channel groups (from 2111th to 2115th) have respectively a record_id of 2014, 2100, 2102, 2104, and 2109 and they are empty (no master channel, no data blocks, really empty).

All in all, things seem to be a bit mixed up here. Since I cannot read the measurement, I cannot scramble it so I will just send you some screenshots from MDF Validator per email.

If you need additional information or detail, please let me know.

Thanks and merry Christmas, Julien

**Comment by danielhrisca** [comment]
Hello Julien,

can we get back to investigating this issue? I've jsut released version 5.15.0 so please use this as a starting point.

Have  great 2020!

**Comment by JulienGrv** [comment]
Hi Daniel,

Happy new year! :) Looking forward this year to working with you again!

I just came back from holiday. The workaround you suggested in your email works so I am scrambling the file. I will send it to you per email.

**Comment by danielhrisca** [comment]
Hello Julien,

did you clarify why the file was corrupted?

**Comment by JulienGrv** [comment]
Hi Daniel,

It seems that the issue is solved inside the development branch. I am closing this ticket for now. Looking forward to 5.20 release!
