### ISSUE TITLE
something about mutli-file GUI plot

### ISSUE THREAD

**Issue by pyyoungman** [danielhrisca/asammdf#285]
Asammdf version:5.14.5 
how to compare  same name channel data from different file in one plot figure  by asammdf? i find i only plot data in single file,multi-file is nok?

**Comment by danielhrisca** [comment]
Hello @pyyoungman 

I plan to add this feature to the GUI. But for now you can only plot the channels from the opened MDF file

**Comment by pyyoungman** [comment]
> Hello @danielhrisca
> ok,thank you.I will pay close attention  to new release about this feature.
>

**Comment by danielhrisca** [comment]
I've pushed an initial implementation in the development branch. Let me know what you think about it
