### ISSUE TITLE
Resampling error: ValueError: array-shape mismatch in array 1

### ISSUE THREAD

**Issue by ij1214** [danielhrisca/asammdf#287]
# Python version
_Please run the following snippet and write the output here_
('python=3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 '
 'bit (Intel)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.17.3'
'asammdf=5.13.11.dev0'

# Code 

  ## MDF version
**3**

  ## Code snippet
  _please write here the code snippet that triggers the error_
mdf_obj = MDF(input_file_path, remove_source_from_channel_names=True)
**filtered_resampled = mdf_obj.resample(raster=0.1, time_from_zero=True)**
  
  ## Traceback
  _please write here the error traceback_
  Traceback (most recent call last):
  File "...datfiletest.py", line 84, in <module>
    filtered_resampled = mdf_obj.resample(raster=0.1, time_from_zero=True)
  File ...\venv\lib\site-packages\asammdf\mdf.py", line 2743, in resample
    mdf.append(sigs, common_timebase=True)
  File ...\venv\lib\site-packages\asammdf\blocks\mdf_v3.py", line 1879, in append
    samples = fromarrays(fields, dtype=types)
  File "...venv\lib\site-packages\numpy\core\records.py", line 639, in fromarrays
    raise ValueError("array-shape mismatch in array %d" % k)
ValueError: array-shape mismatch in array 1

# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._
Can't export input .dat file to matfile due to memoryerror so resampled first and still doesn't export due to above error

**Comment by danielhrisca** [comment]
Hello @ij1214 

please try out the fix found in the development branch code

**Comment by ij1214** [comment]
Hello,

Working now thank you! However, if I removed the line
`filtered_resampled = mdf_obj.resample(raster=0.1, time_from_zero=True)`
so I just export all the signals within the data file without resampling and exported it to a matfile:
```
mdf_obj = MDF(input_file_path, remove_source_from_channel_names=True)
mdf_obj.export('mat', filename=export_filename, use_display_names=True, oned_as='column',
                        single_time_base=True, time_from_zero=False, ignore_value2text_conversions=True) 
```
I am given the following traceback error:
Traceback (most recent call last):

>   File "...datfiletest.py", line 93, in <module>
>     single_time_base=True, time_from_zero=False, ignore_value2text_conversions=True) 
>   File "...venv\lib\site-packages\asammdf\mdf.py", line 848, in export
>     ignore_value2text_conversions=ignore_value2text_conversions,
>   File "...venv\lib\site-packages\asammdf\mdf.py", line 3220, in to_dataframe
>     df[channel_name] = pd.Series(sig.samples, index=sig.timestamps)
>   File "...venv\lib\site-packages\pandas\core\frame.py", line 3487, in __setitem__
>     self._set_item(key, value)
>   File "...venv\lib\site-packages\pandas\core\frame.py", line 3565, in _set_item
>     NDFrame._set_item(self, key, value)
>   File "...venv\lib\site-packages\pandas\core\generic.py", line 3381, in _set_item
>     self._data.set(key, value)
>   File "...venv\lib\site-packages\pandas\core\internals\managers.py", line 1072, in set
>     self.insert(len(self.items), item, value)
>   File "...venv\lib\site-packages\pandas\core\internals\managers.py", line 1207, in insert
>     self._consolidate_inplace()
>   File "...venv\lib\site-packages\pandas\core\internals\managers.py", line 937, in _consolidate_inplace
>     self.blocks = tuple(_consolidate(self.blocks))
>   File "...venv\lib\site-packages\pandas\core\internals\managers.py", line 1913, in _consolidate
>     list(group_blocks), dtype=dtype, _can_consolidate=_can_consolidate
>   File "C...venv\lib\site-packages\pandas\core\internals\blocks.py", line 3340, in _merge_blocks
>     new_values = new_values[argsort]
> MemoryError: Unable to allocate array with shape (100, 270580) and data type float64

This is using the same input data file. Is this merely just a memory issue with my system?

Thank you

**Comment by danielhrisca** [comment]
You have 3066 channels and the 612000 cycles in the channel group with the highest cycle count. With single_time_base set to True, in the best case (all uint8 channels) you would need at least 1.8GB of RAM for the samples alone .

So in the end it's just a matter of out of RAM error; if you set the raster to a reasonable value you can avoid this

**Comment by ij1214** [comment]
Cool no worries, thank you.
Lastly, is the fix applicable to python 2.7 by any chance (ie copy the changes made to fix the issue)? No worries if not.

**Comment by danielhrisca** [comment]
starting with release 5.0.0 you can only use Python >= 3.6 , so there is no.

**Comment by ij1214** [comment]
Cheers thank you!
