### ISSUE TITLE
About ASAMMDF 5.15.1 some advices for Update later

### ISSUE THREAD

**Issue by pyyoungman** [danielhrisca/asammdf#288]
# Python 3.7.5
two questions:
1.Comparison mode
Firstly,in Comparison mode,I think that multi-plot is vital function like single files mode;
Secondly,in Comparison mode,I think x-axis  synchronization in different files is also vital.For example,time start from no zero seconds in several data file.we need to synchronize different file data time start point by setting a offset;
2.some bugs: 
 1)Toggles dots_,this fuction have some erros;
 2) Insert computation,i don't rename calc variation like "ddd" and so on;

**Comment by danielhrisca** [comment]
> 1)Toggles dots_,this fuction have some erros;
> 2) Insert computation,i don't rename calc variation like "ddd" and so on;

Please give more details about those issues

**Comment by pyyoungman** [comment]
@danielhrisca 
Details about those issues

ok，As follow，I received some erro messages when I was using "toggle dots" and "Insert computation"
1)：“Toggle dots ”：Error messages:
Error: <class 'AttributeError'>	 
'Plot' object has no attribute 'update_lines'
Details: 2020-01-10, 08:42:57 -------------------------------------------------------------------------------- 'Plot' object has no attribute 'update_lines' -------------------------------------------------------------------------------- File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\gui\widgets\main.py", line 412, in toggle_dots self.comparison_plot.update_lines(with_dots=self.with_dots) 


2) “Insert computation ”：
when I add clac variation which is named as "ddd",there is Erro messages:
Error: <class 'TypeError'>	 
setToolTip(self, str): argument 1 has unexpected type 'Plot'

Details: 2020-01-10, 08:48:09 -------------------------------------------------------------------------------- setToolTip(self, str): argument 1 has unexpected type 'Plot' -------------------------------------------------------------------------------- File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\gui\widgets\plot.py", line 521, in computation_channel_inserted it = ChannelDisplay(sig.uuid, unit, sig.samples.dtype.kind, 3, self) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\gui\widgets\channel_display.py", line 57, in __init__ self.setToolTip(self._tooltip or self._name)

**Comment by danielhrisca** [comment]
@pyyoungman 
The two errors are now fixed in 5.16.5

**Comment by danielhrisca** [comment]
> Firstly,in Comparison mode,I think that multi-plot is vital function like single files mode;
> Secondly,in Comparison mode,I think x-axis synchronization in different files is also vital.For example,time start from no zero seconds in several data file.we need to synchronize different file data time start point by setting a offset;

I'm thinking about adding two new actions when right clicking the channels list:
* _Set start time stamp_ : will allow to set the first channel sample time stamp, this way you can "shift" the channel backwards of forwards in the time domain. The user thus has to input the new offset value 
* _Set time stamp to 0s_ : will act as a shortcut to set the start time stamp to 0s directly

**Comment by danielhrisca** [comment]
@pyyoungman 
please try the new development branch code

**Comment by pyyoungman** [comment]
hello，@danielhriscaI ,have tried the new development branch code，and these two actions about x-axis synchronization are very good. but I find one erro when i was testing new branch code:
<class 'AttributeError'>: 'Cursor' object has no attribute 'addMarker'
Why?

**Comment by pyyoungman** [comment]
@danielhrisca,there is a new idea about GUI. In mdi_area,it is easy to generate many sub-window,and i think that it will be a good action to generate sub-plot in one Plot_are are like some actions from matlibplot.

**Comment by danielhrisca** [comment]
> <class 'AttributeError'>: 'Cursor' object has no attribute 'addMarker'
> Why?

You need to install the new release candidate for pyqtgraph
``pip install -U pyqtgraph==0.11.0rc0``

**Comment by danielhrisca** [comment]
> @danielhrisca,there is a new idea about GUI. In mdi_area,it is easy to generate many sub-window,and i think that it will be a good action to generate sub-plot in one Plot_are are like some actions from matlibplot.

I don't have time for this right now, but I expect if to be a lot of work. It might never happen

**Comment by danielhrisca** [comment]
I don't think I will implement matplotlib lib subplots with dedicated axes because it complicates things too much. You can achieve most of the functionality with the current features

I will close this issue for now
