### ISSUE TITLE
unittest files

### ISSUE THREAD

**Issue by danielhrisca** [danielhrisca/asammdf#29]
This issue is used as storage for the test files
[test.demo.zip](https://github.com/danielhrisca/asammdf/files/3111848/test.demo.zip)

[test arrays.zip](https://github.com/danielhrisca/asammdf/files/1592123/test.arrays.zip)
[test arrays v3.zip](https://github.com/danielhrisca/asammdf/files/1594331/test.arrays.v3.zip)

**Comment by yahym** [comment]
What about considering something like [Git large file storage lfs](https://github.com/blog/1986-announcing-git-large-file-storage-lfs)

I think though `Git lfs` feature is not enabled by default in github for public repos - I tried it and ended with this error:
```
Git LFS: (0 of 14 files) 0 B / 622.66 KB
batch response: @yahym can not upload new objects to public fork yahym/asammdf
error: failed to push some refs to 'https://github.com/yahym/asammdf.git'
```

If we can enable it I think can be a better option of storing large files than storing them in an issue.

**Comment by jed-frey** [comment]
Based on [GitHub LFS](https://github.com/blog/1986-announcing-git-large-file-storage-lfs) pricing I've been looking at setting up a [Gitea](https://gitea.io/en-US/) server with LFS support on a DigitalOcean instance.

**Comment by danielhrisca** [comment]
Do you need the LFS git extensions to be able to clone the repo afterwards?

**Comment by jed-frey** [comment]
From my understanding only to get the LFS files. It should behave like a plain Git repo on machines without it.
