### ISSUE TITLE
cut function changes mf4 file content

### ISSUE THREAD

**Issue by m-tosch** [danielhrisca/asammdf#291]
`
('python=3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.17.4'
'asammdf=5.15.1'
`

**My code**
 ```Python
from asammdf import MDF

with MDF(r'input.MF4') as mdf:
    short = mdf.cut(start=6.0, stop=None, whence=1)
    short.save('output.mf4', overwrite=True, compression=0)
  ```
  
# Description

I'm trying to cut a .mf4 file and save the output. This works for my input file. However, the cut/output file contains errors and the structure seems to be different. (Unfortunately i can't upload the .mf4 file for policy reasons.)

This is the original mf4 file in the Vector Validator:
![input_mf4_vector](https://user-images.githubusercontent.com/22624685/72536550-bc079300-387a-11ea-8c9d-4cbae25f1c9f.png)

This is the cut mf4 file in the Vector Validator:
![output_mf4_vector](https://user-images.githubusercontent.com/22624685/72536560-c033b080-387a-11ea-9eee-f434e8bdea62.png)

**Comment by danielhrisca** [comment]
Hello Maximilian, 

please try the new development branch code. 

Don't worry about the difference in the data group count: you original file is unsorted, and sorting it removes some of the data groups

**Comment by m-tosch** [comment]
I switch to your newest the development branch code and executed the following snippet on the same mf4 file.
```python
from asammdf import MDF
with MDF(r'input.MF4') as mdf:
    short = mdf.cut(start=6.0, stop=None, whence=1)
```

I get this error

```
Traceback (most recent call last):
  File "c:/Users/XXXXXX/Desktop/cut.py", line 5, in <module>
    short = mdf.cut(start=6.0, stop=None, whence=1)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf-5.16.0.dev11-py3.7-win-amd64.egg\asammdf\mdf.py", line 551, in cut
    if master[-1] < start:
IndexError: index -1 is out of bounds for axis 0 with size 0
```

There now seems to be a missing error checking for the start and stop time arguments inside the cut function, no? (I tried out different ones for both, including 'None')

**Comment by danielhrisca** [comment]
Can you try again with the new code?

**Comment by m-tosch** [comment]
```
Traceback (most recent call last):
  File "c:/Users/XXXXXX/Desktop/cut.py", line 3, in <module>
    short = mdf.cut(start=6.0, stop=None, whence=1)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf-5.16.0.dev12-py3.7-win-amd64.egg\asammdf\mdf.py", line 518, in cut
    for j, sigs in enumerate(self._yield_selected_signals(group_index, groups=included_channels)):
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf-5.16.0.dev12-py3.7-win-amd64.egg\asammdf\blocks\mdf_v4.py", line 7897, in _yield_selected_signals
    count = 128 * 1024 * 1024 // record_size or 1
ZeroDivisionError: integer division or modulo by zero
```

**Comment by danielhrisca** [comment]
We're making progress :) Try the new code

**Comment by m-tosch** [comment]
It seems to be working now!

**My code**
```python
from asammdf import MDF
with MDF(r'input.MF4') as mdf:
   short = mdf.cut(start=6.0, stop=None, whence=1)
   short.save('output.mf4', overwrite=True, compression=0)
```

Vector Validator
![validator_new](https://user-images.githubusercontent.com/22624685/72611405-4c50e100-392a-11ea-9272-11db40b87ca2.png)

The errors are gone, however there is a new warning. It's in german, so i translated it to something equivalent :)
```
1 Invalid XML: '5.16.0.dev13' violates pattern restriction of '([0-9])+([.]([0-9])+)*( .+)?'.
 Analysis of the element '{http://www.asam.net/mdf/v4}tool_version' with the value '5.16.0.dev13' failed.
 	Meta Data Block 5: md_data output.mf4 0
```

I guess the warning is not sever, since it's just a (history) meta data block your asammdf tool writes to to indicate that it has processed this mf4 file, right?

**Comment by danielhrisca** [comment]
> It seems to be working now!
> 
> **My code**
> 
> ```python
> from asammdf import MDF
> with MDF(r'input.MF4') as mdf:
>    short = mdf.cut(start=6.0, stop=None, whence=1)
>    short.save('output.mf4', overwrite=True, compression=0)
> ```
> 
> **Vector Validator**
> 
> ![validator_new](https://user-images.githubusercontent.com/22624685/72611405-4c50e100-392a-11ea-9272-11db40b87ca2.png)
> 
> The errors are gone, however there is a new warning. It's in german, so i translated it to something equivalent :)
> 
> ```
> 1 Invalid XML: '5.16.0.dev13' violates pattern restriction of '([0-9])+([.]([0-9])+)*( .+)?'.
>  Analysis of the element '{http://www.asam.net/mdf/v4}tool_version' with the value '5.16.0.dev13' failed.
>  	Meta Data Block 5: md_data output.mf4 0
> ```
> 
> I guess the warning is not severe, since it refers to a (history) meta data block your asammdf tool writes to to indicate that it has processed this mf4 file, right?

Yes.

Please check if the concatenation is correct by verifying some of the signals

**Comment by m-tosch** [comment]
From what i can tell in the Validator it looks okay. We have a different tool that reads in mf4 files and displays/processes the content. I'll check with that when i have it in ~3 days. If that works i'll close this issue

**Comment by danielhrisca** [comment]
> From what i can tell in the Validator it looks okay. We have a different tool that reads in mf4 files and displays/processes the content. I'll check with that when i have it in ~3 days. If it works i'll close this issue.
> 
> Thanks!

What tool do you use?

**Comment by m-tosch** [comment]
A tool someone developed internally. Can't say
The content of the cut mf4 file looks alright though! 

I'll close this issue
