### ISSUE TITLE
mf4 file fail to load

### ISSUE THREAD

**Issue by pr0ximo** [danielhrisca/asammdf#292]
# Python version
3.7
  ## MDF version
4.1

  ## Code snippet
import asammdf

a = asammdf.MDF('test.mf4')

  ## Traceback

 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\asdf\.conda\envs\conda-env\lib\site-packages\asammdf\mdf.py", line 128, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\Users\asdf\.conda\envs\conda-env\lib\site-packages\asammdf\blocks\mdf_v4.py", line 334, in __init__
    self._read(mapped=True)
  File "C:\Users\asdf\.conda\envs\conda-env\lib\site-packages\asammdf\blocks\mdf_v4.py", line 585, in _read
    info, uses_ld = self._get_data_blocks_info(
  File "C:\Users\asdf\.conda\envs\conda-env\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2198, in _get_data_blocks_info
    id_string, _1, block_len = COMMON_SHORT_uf(stream, addr)
struct.error: unpack_from requires a buffer of at least 14812224 bytes for unpacking 16 bytes at offset 14812208 (actual buffer size is 13964024)
  
# Description
I have tried two separate files, and they do not work.  It will open in VISION Tool Suite

**Comment by danielhrisca** [comment]
Can you send me the scrambled file for analysis?

**Comment by pr0ximo** [comment]
Sorry I cannot send you the file as it has proprietary info unfortunately.

**Comment by danielhrisca** [comment]
Do see any errors when you open the file with Vector MDFValidator

**Comment by pr0ximo** [comment]
Sorry I am fairly new to the automotive industry.  Is that an APP?

**Comment by danielhrisca** [comment]
It's a freeware that you can download from www.vector.com

**Comment by pr0ximo** [comment]
I'll have to get back to this later. IT needs to install everything unfortunately... =(

**Comment by danielhrisca** [comment]
The error makes me think that you have a corrupted file. Maybe Vision does something that does not comply with the MDF standard

**Comment by pr0ximo** [comment]
If it helps, the file came from ATI Vision. I will see if I can get another .mf4 file from someone

**Comment by danielhrisca** [comment]
Sure thank you

**Comment by danielhrisca** [comment]
@pr0ximo any update?

**Comment by pr0ximo** [comment]
No sorry, don't know if i'll be able to get another.

**Comment by pr0ximo** [comment]
@danielhrisca I was able to generate my own .mf4 file and it works...  Sorry for the unnecessary alarm.  Not sure how the first one was generated...
