### ISSUE TITLE
How signal.samples of string convert to numbers.

### ISSUE THREAD

**Issue by MacsYan** [danielhrisca/asammdf#293]
# Python version  
python 3.7
```python

import asammdf
dat = r'C:\Users\chunshan.ma\Desktop\mdfreader-master\20191221_744-3412ET.1-DCT_S4 1.2T DCT T-6731_CST=-3 01_LIZENGKE01.dat'

mdf = asammdf.MDF(dat)
a = mdf.get('B_st').samples
print(a)

it is b'False' and b'True'
  
How I convert b'False' and b'True' to 0 and 1?

**Comment by danielhrisca** [comment]
Hello, I think that you need the raw samples

```python
a = mdf.get('B_st', raw=True)
print(a.samples)
b = a.physical()
print(b.samples)
```

**Comment by MacsYan** [comment]
Thank you very much.
It works well.
Another question I came across in using asammdf.
How can I know which signal's sample rate is syn or 10 ms, 100 ms.

**Comment by danielhrisca** [comment]
I'm not sure what you mean. Can you explain a bit more?

**Comment by MacsYan** [comment]
The sample rate of signal in ECU measurement can be divided into syn, 10ms, 100ms and others.
When engineer analyse .dat files in MDA software, they can know the sample rate of one signal by right click of signal.
How asmmdf show the sample rate of one signal?

**Comment by danielhrisca** [comment]
I think that there is more Metadata in the channel comment that holds this information. Can you send a file?

**Comment by MacsYan** [comment]
Can you give me one emal address?

**Comment by danielhrisca** [comment]
Please use the address from my profile

**Comment by MacsYan** [comment]
Thank you very much.
