### ISSUE TITLE
Behavior of the _validate_channel_selection function doesn't match the documented behavior.

### ISSUE THREAD

**Issue by jodergrosse** [danielhrisca/asammdf#294]
# Description

Behavior of the _validate_channel_selection function doesn't match the documented behavior. With suppress always set to True, a warning will never be issued.

https://github.com/danielhrisca/asammdf/blob/ea4635f41c36cdf7eb1c3d68b856cf43af8fb716/asammdf/blocks/mdf_v4.py#L2049

If I run the example mentioned in the get function no warning is issued.

https://github.com/danielhrisca/asammdf/blob/ea4635f41c36cdf7eb1c3d68b856cf43af8fb716/asammdf/blocks/mdf_v4.py#L6217-L6231

I suppose either the documentation or the code should be changed.

**Comment by danielhrisca** [comment]
Hello Johannes,

I don't know if the warning if worth keeping around; I'll probably remove it and update the docstring.

**Comment by jodergrosse** [comment]
Sounds good! 
I came across that while figuring out Signal selection with duplicates. Might save the next person a little bit of trouble.

**Comment by danielhrisca** [comment]
I've updated the functions
