### ISSUE TITLE
cut large mf4 file

### ISSUE THREAD

**Issue by m-tosch** [danielhrisca/asammdf#297]
`('python=3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit ' '(AMD64)]') 'os=Windows-10-10.0.17763-SP0' 'numpy=1.17.4' 'asammdf=5.15.1'`

## My code 
```python
from asammdf import MDF

with MDF(r'input.MF4') as mdf:
   short = mdf.cut(start=6.0, stop=None, whence=1)
   short.save('output.mf4', overwrite=True, compression=0)
```

  ## MDF version
  5.15.1 (development branch)
  
## Description
I'm still trying to cut a .mf4 file and save the output, see [Issue 291](https://github.com/danielhrisca/asammdf/issues/291). It works for small files but how would i go about cutting a large mf4 file (~2-16 GB)?

I saw that there is a related section in the [ documentation pdf](https://readthedocs.org/projects/asammdf/downloads/pdf/master/):

```
4.1 Chunked data access

asammdf optimizes memory usage by processing samples in fragments. The read fragment size was tuned based on
experimental measurements and should give a good compromise between execution time and memory usage.

You can further tune the read fragment size using the configure method, to favor execution speed (using larger fragment
sizes) or memory usage (using lower fragment sizes).
```

However, as i understand it you always have to read (in RAM) the whole file first when you want to cut it. Is there a better way to read data in chunks or maybe iterate over the file content and cut it while doing so to not have the whole file in RAM ?

**Comment by danielhrisca** [comment]
> However, as i understand it you always have to read (in RAM) the whole file first when you want to cut it. Is there a better way to read data in chunks or maybe iterate over the file content and cut it while doing so to not have the whole file in RAM ?

The file is not loaded completely in the RAM, only the channel metadata is. 

You code snippet will run regardless of the file size.

**Comment by m-tosch** [comment]
For two examples .mf4 files of 50MB and 80MB i see a RAM usage of ~55MB and ~100MB respectively when running the above snippet. Does this really only depend on the channel metadata?

**Comment by danielhrisca** [comment]
Try on a bigger file and see what happens

**Comment by m-tosch** [comment]
With a 800MB file the RAM usage increases to 3.5GB until my hardware maxes out. The program then just stops, no output file is saved. It just stops, it doesn't crash (seemingly inside the cut function).

**Comment by danielhrisca** [comment]
Can you also try with the development branch code?

**Comment by m-tosch** [comment]
Just did, with the newest development branch code. Same result. The execution stops somewhere inside the cut function (after maxing out on RAM?) and then returns without printing anything.

**Comment by danielhrisca** [comment]
This is strange .

Can you make sure that the developemtn code is really installed? ``print(asammdf.__version__)``

**Comment by m-tosch** [comment]
I'm running the latest dev branch code:

```
5.16.0.dev16
```

Still the same problem. RAM maxes out, program stops without error.

**Comment by danielhrisca** [comment]
I have an idea about what is going on but I need the file to analyze it.

**Comment by m-tosch** [comment]
I thought so. Unfortunately i'm not allowed to give it to you. 
But i'll see what if i can find a workaround, maybe scramble the content or an equivalent/different file.

**Comment by danielhrisca** [comment]
@m-tosch please try the new development branch code. If my assumption is right you should get an exception message

**Comment by m-tosch** [comment]
Running dev branch code
```
5.16.0.dev18
```
No exception message.

**Comment by danielhrisca** [comment]
Hello Maximilian,

do you still have this problem with the 5.19.4 release?

**Comment by m-tosch** [comment]
I have better hardware now with 16GB RAM, but running dev branch code
`5.19.8.dev0`
i now get a different behavior. The program eats up 12GB of RAM on the ~800MB .mf4 file. The resulting "cut" file is 1GB in size and somehow unusable with our other tools. It is not invalid, just unusable.

**Comment by danielhrisca** [comment]
@m-tosch please try with the new release 5.23.0

**Comment by danielhrisca** [comment]
ping @m-tosch try the new release 6.0.1

**Comment by danielhrisca** [comment]
@m-tosch can you try  development 6.3.0.dev36?
