### ISSUE TITLE
interpret mf4 using attached dbc

### ISSUE THREAD

**Issue by SubspaceBob** [danielhrisca/asammdf#298]
hi, is it possible for asammdf to recreate signals from mf4-files with only frame-logging enabled? The search path to the dbc is attached in the file. When i try i get Channel "_signal_name_" not found, but maybe i'm just doing it wrong.

**Comment by danielhrisca** [comment]
Hello @SubspaceBob 

if you have the DBC as an external attachment then you need to make sure that the path is correct (abs or relative path).

Otherwise you can still use the _get_can_signal_ method

```python
mdf = MDF(name)

sig = mfg.get_can_signal(signal_name, database=dbc_path)
```

**Comment by SubspaceBob** [comment]
Hi, thanks for response. 
Will try the get_can_signal method, but i would like to investigate the issue a bit more. The attachment path is correct. Ran os.path.isfile on at_block.file_name and it atleast says the file exists.

I would want to understand the method _process_can_logging, it compares message_name(channel_grp.acq_name) to "CAN_DataFrame", but it is 'CAN1', same as the grp.CAN_id. And most importantly, the channel_group.comment is empty string, using mdf validator I can see that the cg_md_comment start adress i 0x0000. 

So it skips setting message_id and grp.CAN_database to True and thus misses out on the fun part.

I guess it is expected that the cg_md_comment is not empty, I can see in the source code that this comment is needed for finding lot of properties. The mf4-file is created with CANalyzer 9.

Any ideas where to continue the fault tracing?

**Comment by SubspaceBob** [comment]
My last comment maybe wasn't that, clear, so i'll try again. For me, it seems that CANalyzer 9 does not provide sufficient info in the mf4 for asammdf to parse it. Has anyone else got this to work with CANalyzer or any other tool?

**Comment by danielhrisca** [comment]
@SubspaceBob can you send the file?

**Comment by SubspaceBob** [comment]
I just tested with CANalyzer12 and still have the same issue.

**Comment by dapperfu** [comment]
Does the MDF pass validation? https://www.asam.net/members/product-directory/detail/mdf-validator/

**Comment by danielhrisca** [comment]
@SubspaceBob please try the development branch code. I've refactored the bus logging  handling code

**Comment by danielhrisca** [comment]
ping @SubspaceBob

**Comment by danielhrisca** [comment]
re-open if still valid
