### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by jed-frey** [danielhrisca/asammdf#30]
From: *https://github.com/blog/1184-contributing-guidelines*

> Oftentimes open source projects place a CONTRIBUTING file in the root directory. It explains how a participant should do things like format code, test fixes, and submit patches. Here is a fine example from puppet and another one from factory_girl_rails. From a maintainer's point of view, the document succinctly communicates how best to collaborate. And for a contributor, one quick check of this file verifies their submission follows the maintainer's guidelines.

Development seems to be hitting a stride, a lot of the 'boring tedious' work is getting automated. Having some contributing guidelines would help new developers get started.

**Comment by danielhrisca** [comment]
Hello Jed,

I will work on this. I'm looking at other projects for examples, the aim being to follow the project goals specified in the README.

**Comment by danielhrisca** [comment]
Hello Jed,

please have a look over the contributing guide and give your opinion. Thank you!

**Comment by jed-frey** [comment]
Looks good.
