### ISSUE TITLE
How to get (more?) source information from signals. Please help me

### ISSUE THREAD

**Issue by s9mahueb** [danielhrisca/asammdf#300]
Hi all!
i am very new here and tried my very first stepts with python. The code is not nice for shure, but works ;-)

I want to do signal analysis in Matlab:
Step1 in python: Reading all signal names and signal sorces out of the mdf-file
Step2 in Matlab: Creating a user-dialog for choosing signals
Step3 in python: Export the chosen signals into .mat-file

My Problem: I can not get enough detailed information about the signal source name in order to get a unique signal identification.

In the mdf-file are 2 signals, named "Terminal30". But measured on own devices. And i am not allowed to change the signal naming ;-(

I can get this signal informartion, shown as Signal name,  sirgnal source name, group-number, and signal-index:
Terminal30 \ SC : (147, 2)
Terminal30 \ SC : (249, 2)

You see, "Terminal30 \ SC" shows the identification problem for me. The information is the same.

From a more professional tool i can get the information to the signals:

Here the first "Terminal30":
cn cn_tx_name           Terminal30
cp si_tx_path              Signal::SC
cs si_tx_name             SC
gn cg_tx_acq_name   SC_LV_VOLT
gp si_tx_path             Network
gs si_tx_name            SC-Measure-CAN_A

The same for second "Terminal30", but:
gs si_tx_name            SC-Measure-CAN_B

And there i see the necessary information: the "gs si_tx_name" which leads to "CAN_A" and "CAN-B".

But i am absolutly on the limit of my knowledge and have no idea how to get the "gs si_tx_name".

Can you please help me ?

Thank you very much in forward !!!!!!

Here the actually code for step1:

# coding: latin-1
 
channelist = ['Terminal30']

# channelistSource here empty, in order to get same signalnames from multible devices
channelistSource = ['']
 
listeUnitsAll = []
channelist4unitsAll = []
listeUnits = []
channelist4units = []
 
listeSourceAll = []
listeSource = []

from asammdf import MDF, Signal
import scipy.io as sio
 
print(r"C:\Test\test.mdf")
obj = MDF(r"C:\Test\test.mdf")
obj4Units = MDF(r"C:\Test\test.mdf")
# resample for reducing processing time (i thought its helping ... )
obj4Units = obj4Units.resample(raster=10000000000000000000000)

for Signal in obj4Units:
    listeUnitsAll.append(Signal.unit)
    channelist4unitsAll.append(Signal.name)
    listeSourceAll.append(Signal.source.name)
 
#Read Tuple of prechosen signalnames:
My_Name_Group = []
ci = -1
for c in channelist:
	ci = ci + 1
	Tuple_Group_Index = obj4Units.whereis(c)
	for i in range(0,len(Tuple_Group_Index)):
		TGI = Tuple_Group_Index[i]
		TGI = Tuple_Group_Index[i]
		Signal = obj4Units.get(group=TGI[0],index=TGI[1])
		if not channelistSource[ci] or Signal.source.name == channelistSource[ci]:
			#My_Name_Group.append([ None, TGI[1], TGI[0] ])
			My_Name_Group.append([ Signal.name, TGI[0] ])
			print(Signal.name +' \ ' + Signal.source.name + ' :')
			print(TGI)
			
#concert List into Tuple:
Tuple_Filter= tuple(My_Name_Group)
 
obj4Units.close
 
if not channelist:
    channelist = channelist4unitsAll[:]
 
listeUnitsAll.append('s')
listeSourceAll.append('')
channelist4unitsAll.append('time')
 
obj2 = obj.filter(Tuple_Filter, version=None)
obj3 = obj2.resample(raster=10000000000000000000000)
for Signal in obj3:
    listeUnits.append(Signal.unit)
    listeSource.append(Signal.source.name)
    channelist4units.append(Signal.name)
obj3.close
 
sio.savemat(r"E:\Test\MDF_import_channelnamesAll.mat", {'MDF_import_channelnamesAll':channelist4unitsAll})
sio.savemat(r"E:\Test\MDF_import_SourceAll.mat", {'MDF_import_SourceAll':listeSourceAll})
obj2.close

**Comment by danielhrisca** [comment]
See the _get_ method argument https://asammdf.readthedocs.io/en/latest/api.html#mdf4

You need to give the _source_ name

**Comment by s9mahueb** [comment]
Hi, 
thank you! Yes, with get-methode i also end up on the Signal-Object, which i already determined by use of whereis-methode. Or did i get you wrong? I cant find somthing like "CAN-A" or "CAN-B" for the signals. By looking into data, the signals are definatly different in value and time-shape.

Do you have any additionally idea ? Best regards !

Here the result for both signal (by source + group + index)

test = obj4Units.get(source='SC',group=147, index=2)
print(test)

Signal Terminal30:
	samples=[13.242]
	timestamps=[616437.95055258]
	invalidation_bits=None
	unit="V"
	conversion=None
	source=SignalSource(name='SC', path='Signal::SC', comment='<SIcomment><TX></TX><common_properties><e name="ChannelNo">7</e></common_properties></SIcomment>', source_type=1, bus_type=2)
	comment="voltage of terminal 30"
	mastermeta="('t', 1)"
	raw=False
	display_name=
	attachment=()>


test = obj4Units.get(source='SC',group=249, index=2)
print(test)
Signal Terminal30:
	samples=[13.242]
	timestamps=[616437.95055258]
	invalidation_bits=None
	unit="V"
	conversion=None
	source=SignalSource(name='SC', path='Signal::SC', comment='<SIcomment><TX></TX><common_properties><e name="ChannelNo">7</e></common_properties></SIcomment>', source_type=1, bus_type=2)
	comment="voltage of terminal 30"
	mastermeta="('t', 1)"
	raw=False
	display_name=
	attachment=()>

**Comment by danielhrisca** [comment]
Install the development branch code

```
pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip
```

and then use both the channel name and the source to identify the exact channel

```python
ch_from_CAN_A = mdf.get('Terminal30', source='SC-Measure-CAN_A')
print(ch_from_CAN_A)
ch_from_CAN_B = mdf.get('Terminal30', source='SC-Measure-CAN_B')
print(ch_from_CAN_A)
```

**Comment by s9mahueb** [comment]
Hi, thanks! Pip installation done, code tested.
And here the confusing result, again. 
The usage of the other tools information of "gs si_tx_name" = "SC-Measure-CAN_A"
`ch_from_CAN_A = mdf.get('Terminal30', source='SC-Measure-CAN_A')`
`print(ch_from_CAN_A)`
results in
`asammdf.blocks.utils.MdfException: Terminal30 with source SC-Measure-CAN_A not found`

Just the usage of the other tools information "cs si_tx_name" ="SC" leads to the Signal.
"SC" seems to be the value of `Signal.source.name`
`ch_from_CAN_A = mdf.get('Terminal30', source='SC')`
results in a signal, like on the end of my last post:

`Signal Terminal30:`
`samples=[13.242]`
`timestamps=[616437.95055258]`
`invalidation_bits=None`
`unit="V"`
`conversion=None`
`source=SignalSource(name='SC',path='Signal::SC',comment='<common_properties>7</common_properties>', source_type=1, bus_type=2)`
`comment="voltage of terminal 30"`
`mastermeta="('t', 1)"`
`raw=False`
`display_name=`
`attachment=()>`

I have no idea how to get onto this mysterious information in this "gs si_tx_name" ....

If i cant separate between the CAN-A/B Terminal30-Signal, it semms to be the end of my Matlab-Python-Plan, like the last step onto moon is missing ;-)

**Comment by danielhrisca** [comment]
Install Vector MDFValidator (here https://www.vector.com/int/en/search/?tx_solr%5Bfilter%5D%5B0%5D=categoryContent%3A7&tx_solr%5Bfilter%5D%5B1%5D=categoryStandard%3A54) and make some screenshots with the file identification block, channel group block and channel block 
![image](https://user-images.githubusercontent.com/20952040/73517054-0f451e00-4403-11ea-8d21-7d8f9440995a.png)
![image](https://user-images.githubusercontent.com/20952040/73517065-18ce8600-4403-11ea-87dd-03805030b24f.png)
![image](https://user-images.githubusercontent.com/20952040/73517080-271ca200-4403-11ea-87a2-41f408ed3502.png)

**Comment by s9mahueb** [comment]
Hi (Good Morning from Germany),
wow, we are so close to the solution. Installed, opened, made the shown screenshots and looked additionally into the **"Source Information". There it is !**

Is it possible to get this infomation by using file-object, group-number and channel-index ?

Here the screenshots 👍 
**of first Terminal 30**

![Screenshot_Block](https://user-images.githubusercontent.com/60480179/73520016-d86f0800-4402-11ea-881f-a6ad0e334614.jpg)

![1st Terminal30 Screenshot1](https://user-images.githubusercontent.com/60480179/73520019-d9079e80-4402-11ea-8e16-722cbbed5bce.jpg)

![1st Terminal30 Screenshot2](https://user-images.githubusercontent.com/60480179/73520020-d9079e80-4402-11ea-9610-047f2d6e3525.jpg)

![1st Terminal30 Screenshot3 - I can see the solution](https://user-images.githubusercontent.com/60480179/73520012-d7d67180-4402-11ea-94cd-6db2259ddd4c.jpg)

**of second Terminal 30**

![2nd Terminal30 Screenshot1](https://user-images.githubusercontent.com/60480179/73520013-d86f0800-4402-11ea-9ca3-6adfb5159946.jpg)

![2nd Terminal30 Screenshot2](https://user-images.githubusercontent.com/60480179/73520014-d86f0800-4402-11ea-961f-c80bdaef95e8.jpg)

![2nd Terminal30 Screenshot3 - I can see the solution](https://user-images.githubusercontent.com/60480179/73520015-d86f0800-4402-11ea-8b4c-b1f6ac88a810.jpg)

**Comment by danielhrisca** [comment]
The development branch code should work.

What is the output of this snippet?

```python
import asammdf
print(asammdf.__version__)
```

**Comment by s9mahueb** [comment]
Using:
Windows10 64bit
Python 3.7.4
 **via CMD installed (as all)**:   python -m pip install -I --no-deps httpsgithub.comdanielhriscaasammdfarchivedevelopment.zip

`import asammdf`
`print(asammdf.__version__)`
`5.11.0`

Tried again with direct Text-copy 'SC-Measure-CAN_A' from Vector. There was no typo.
`# coding: latin-1`
 
`from asammdf import MDF, Signal`
`import asammdf`
`import scipy.io as sio`

`mdf = MDF(r"C:\Test\test.mdf")`
`ch_from_CAN_A = mdf.get('Terminal30', source='SC-Measure-CAN_A')`
`print(ch_from_CAN_A)`

Same failure.
I already did the pyqtgraph package update, but message staying alive:
via CMD:  python -m pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip

**==> Did i use wrong CMD-commands, maybe?**

`asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch`
`pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip`
`asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch`
`pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip`
`Traceback (most recent call last):`
`  File "C:\Tooltest\batch.c", line 19, in <module>`
`    ch_from_CAN_A = mdf.get('Terminal30', source='SC-Measure-CAN_A')`
`  File "C:\Users\u16j17\AppData\Roaming\Python\Python37\site-packages\asammdf\blocks\mdf_v4.py", line 3885, in get name, group, index, source=source`
`  File "C:\Users\u16j17\AppData\Roaming\Python\Python37\site-packages\asammdf\blocks\mdf_v4.py", line 1991, in _validate_channel_selection`
`    raise MdfException(f"{name} with source {source} not found")`
**`asammdf.blocks.utils.MdfException: Terminal30 with source SC-Measure-CAN_A not found`**

**Comment by danielhrisca** [comment]
The update did not work for you. The latest development version is ``5.16.4.dev0``

**Comment by s9mahueb** [comment]
Hi, 
i learned now to install a special version.
Now its `5.16.4.dev0` and i can get the signal by source `'SC-Measure-CAN_A'`

`Signal Terminal30:`
`samples=[13.242]`
`timestamps=[616437.95055258]`
`invalidation_bits=None`
`unit="V"`
`conversion=None`
`source=SignalSource(name='SC',path='Signal::SC',comment='<common_properties>7</common_properties>', source_type=1, bus_type=2)`
`comment="voltage of terminal 30"`
`mastermeta="('t', 1)"`
`raw=False`
`display_name=`
`attachment=()>`

With this, the case is solved for knowing the source name. 🥇 👍 
My **really final question** is for the most common case: How can i get this "other" source name (the string  `'SC-Measure-CAN_A'`) by using signalname `'Terminal30'` **without knowing** of `'SC-Measure-CAN_A'.`

This is the point where i hang:
Via `mdf.whereis('Terminal30')` i get the groups+channelindex of the two signals. So i can access both signals.
Via `Signal.source.name` i get just `'SC'` for both sources.
I dont know how to get to the value `'SC-Measure-CAN_A'.` or `'SC-Measure-CAN_B'.` out of the related signals. 
It will be the same way like we found the information in the Vector-Tool, but how can i adress to this information?

**Comment by danielhrisca** [comment]
``SC-Measure-CAN_A`` is available in the channel group source name, not in the channel  source name. It will not show up in the Signal object returned by _get_

**Comment by s9mahueb** [comment]
Hi Daniel,
i tried-and-errored until now. Now i am absolutly burned out. 

**I do a count: "just" 7 lines code, the hardest 7 in my life ! Beer, i need beer ...** 

But i learned! 💯 x Thanks for your hints to reach the soltution!

`gr_address = mdf.groups[group_index]`
`cg_adress = gr_address['channel_group']`
`acq_source_addr = cg_adress['acq_source_addr']`
`stream = mdf._file`
`acq_name_addr = cg_adress.address`
`s_block = asammdf.blocks.v4_blocks.SourceInformation(address=acq_source_addr, stream=stream)`
`cg_source_name = s_block.name`
`print(cg_source_name )`
HERE IT IS : **SC-Measure-CAN_B**
