### ISSUE TITLE
Adjusting timestamp edges

### ISSUE THREAD

**Issue by JuicyPussy** [danielhrisca/asammdf#301]
- Python 3.7.2
- asammdf.__version__ '5.16.3'

I needed to adjust first and last timestamp of each signal, but to generalize the problem let's say I need to change data/timestamp of each signal and assemble mf4 back, preserving all other features like group names. Currently I
1. extract signals(except time signal, since one more will be created by default, during composing mf4) by groups from mf4, preserving group name (mdf.groups[ ].channel_group.comment)
2. applying custom logic to data/timestamps
3. composing new mf4 and appending group of signals >>> new_mdf.append(signals_list, common_timebase=True)
4. find newly created group and assigning group name/comment >>> new_mdf.groups[idx].channel_group.comment = group_names[idx]

This process is overcomplicated and I believe that there exists a better way to do that but I was not able to adjust signal's data/timestamps at place(without a need to compose new mdf file).

Thanks in advance!

**Comment by danielhrisca** [comment]
@JuicyPussy 
The library does not modify the input files inplace so your approach is the recommended one. 

You could get all low level but there are a lot of edge cases. 

What do you get when you do run this?

```python
for i, go in enumerate(mdf.groups):
    print(i, gp.data_blocks)
```

**Comment by JuicyPussy** [comment]
Output:
`0 [DataBlockInfo(address=0x738, block_type=0, raw_size=5208, size=5208, param=0, invalidation_block=None, block_limit=None)]
1 [DataBlockInfo(address=0x1D30, block_type=0, raw_size=4564, size=4564, param=0, invalidation_block=None, block_limit=None)]
2 [DataBlockInfo(address=0x31C0, block_type=0, raw_size=201528, size=201528, param=0, invalidation_block=None, block_limit=None)]
3 [DataBlockInfo(address=0x34A60, block_type=0, raw_size=4927, size=4927, param=0, invalidation_block=None, block_limit=None)]`

**Comment by danielhrisca** [comment]
In this case you could modify the original file relatively easy.

please run this as well

```python
for i, gp in enumerate(mdf.groups):
    master = mdf.masters_db[i]
    master_channel = gp.channels[master]
    print(i, gp.channel_group.metadata(), master_channel)
```

**Comment by JuicyPussy** [comment]
So in some cases we can change signals inplace in some ceses not, right? What is it up to?

**Comment by danielhrisca** [comment]
> So in some cases we can change signals inplace in some ceses not, right? What is it up to?

It means that in this case you have a plain data block and you can open the file in binary mode and modify the first and last timestamps without too much hassle. 

But again the _asammdf_ library will no modify the file inplace, you will have to do this independently.

**Comment by JuicyPussy** [comment]
I see, thanks a lot!
