### ISSUE TITLE
Suppress pyqtgraph warning by default

### ISSUE THREAD

**Issue by JuicyPussy** [danielhrisca/asammdf#302]
- Python 3.7.2
- asammdf.version '5.16.3'

Every time I import asammdf I'm getting
`asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip
asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip`

I have CLI application and don't use pyqtgraph(though it installed from pip repo). Sometimes I need to pipe stdout to file and don't want to see these warnings there. Currently I disable asammdf logger before importing module, but may be you will provide a better solution.

Thanks in advance!

**Comment by danielhrisca** [comment]
install the latest pyqtgraph release candidate

``pip install pyqtgraph==0.11.0rc0``

**Comment by JuicyPussy** [comment]
That works, thanks!
Could that job be automated by asammdf pip installer/updater(not to update asammdf and pyqtgraph separately)? Or may be raise that warning only on pyqtgraph usage?
Offtopic:
In case of contributing, is there a list of features to implement, or I can implement on my own features that I need and then ask for merge request?

**Comment by danielhrisca** [comment]
There are missing features mostly from the mdf v4 specifications. 

You are welcome to create PR's at any time, just make sure to make them on the development branch.
