### ISSUE TITLE
MDF.concatenate - Different Structure - IndexErrror

### ISSUE THREAD

**Issue by olekslev** [danielhrisca/asammdf#303]
# Python version
'python=3.7.3 (default, Oct 11 2019, 19:39:43) \n'
'asammdf=5.16.3'

# Code 

  ## MDF version
 4.10

  ## Code snippet
files = [ '/file1.mf4', './file3.mf4']
mdf_obj = MDF.concatenate(files)

  ## Traceback
  File "****mdf_maker.py", line 8, in <module>
    mdf_obj = MDF.concatenate(files)
  File "****lib/python3.7/site-packages/asammdf/mdf.py", line 1607, in concatenate
    if names != included_channel_names[i]:
IndexError: list index out of range

  
# Description

IndexError occurs by concatenation of 2 mdf files with different structure. Normally we have to raise asammdf.blocks.utils.MdfException.

Files description:
File1: file1.mf4
- Channel Group1: Signal1, Signal2

File2: file2.mf4
- Channel Group1: Signal1, Signal2
- Channel Group2: Signal3

Both files were created with example script from asammdf documentation page. Timestamp are same for all channels.

**Comment by danielhrisca** [comment]
@olekslev should be fixed in the development branch

**Comment by olekslev** [comment]
Thanks @danielhrisca for fast reply and fixing.
