### ISSUE TITLE
to_dataframe takes significantly longer when converting a mdf file with certain channels

### ISSUE THREAD

**Issue by cayox** [danielhrisca/asammdf#304]
# Python version
('python=3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.18.1'
'asammdf=5.17.1'
# Code 

  ## MDF version
  4.10

  ## Code snippet
  the to_dataframe function
  
  ## Traceback
  not getting any error it just takes significantly longer to convert with certain channels in MDF
  
# Description

We reading out a 35mb .mdf-file with your library and if we filter for certain channels our whole plotting process take about 10s.
However if we take the same file and repeat everthing except that we now filter for channels "DIN0" and "DIN1"(these channels just store data that can be eitehr 0 or 1), the whole process takes about 75s, which is way too long, especially for such a small file. We try to generate a sample file that we can send you. 
Do you have any clue what the problem could be ? It must be in the in the channels but we cant find the root of the problem.

Thank you very much

**Comment by danielhrisca** [comment]
Hello @cayox 

I can only suspect that the DINx channels have a larger cycles count.

What happens if you call _to_dataframe_ with _use_interpolation=False_ ?

**Comment by cayox** [comment]
> What happens if you call to_dataframe with use_interpolation=False ?
sadly that doesn't fix it

apperantly, after further testinga and trying the problem may be in the "time_as_date" parameter. running it "time_as_date = False" makes it run way faster!

here's a snippet of my code, but with that it still takes about 40s

`mdf_file = mdf_file.filter(channels=channels)

            # generates dataframe from .mdf-file
            mdf_data_chunk = mdf_file.to_dataframe(raster=None, time_from_zero=True,
                                                   empty_channels='skip', keep_arrays=False, use_display_names=False,
                                                   time_as_date=False, reduce_memory_usage=True, raw=True,
                                                   ignore_value2text_conversions=True, use_interpolation=True,
                                                   only_basenames=True, interpolate_outwards_with_nan=False)`

**Comment by cayox** [comment]
you were right the cycles count is significantly higher of the DIN channels (4295672) in comparison to the other channels (71663). So if i reduce the cycles count while measuring everything would be great ?

**Comment by JulienGrv** [comment]
But time_as_date is already set to False default-wise.

Sorry to interferebut I have also an issue using to_dataframe():

```console
[...]
  File "C:\Users\[...]\asammdf\mdf.py", line 3196, in to_dataframe
    for signal in signals
  File "C:\Users\[...]\asammdf\mdf.py", line 3196, in <listcomp>
    for signal in signals
  File "C:\Users\[...]\asammdf\signal.py", line 824, in interp
    s = self.samples[idx]
MemoryError: Unable to allocate 225. MiB for an array with shape (7600050,) and data type (numpy.record, [...]
```

**Comment by danielhrisca** [comment]
The problem with the DataFrame is that all the columns share the same index. This means that if you have a high cycles count channel, all the other channels will be expanded by interpolation or by filling NaN's to the same cycle count.

**Comment by cayox** [comment]
That solved it! Thank you very much for the fast response!

**Comment by danielhrisca** [comment]
@JulienGrv use the raster argument to avoid the memory error
