### ISSUE TITLE
Some Ideas About ASAMMDF 5.17.2 

### ISSUE THREAD

**Issue by pyyoungman** [danielhrisca/asammdf#305]
Hello,
About ASAMMDF 5.17.2
1.I find that Link sub-plots X-axis is only used in Cusor but not in Range.
2.when I was making attempt to drag computation var from one plot to generate new plot,there was one erro:
<class 'asammdf.blocks.utils.MdfException'>: Channel "{"name": "rl_cal", "computation": {"type": "arithmetic", "op": "+", "operand1": "rl_w_msg\\XCP:1", "operand2": 20.0}}" not found
so there are some question in dragging computation var

**Comment by danielhrisca** [comment]
@pyyoungman it should work with version 5.17.3

**Comment by pyyoungman** [comment]
@danielhrisca 
hello, above First question:Link sub-plots X-axis is not used in Range. Why?

**Comment by danielhrisca** [comment]
Only the cursors are synced currently. Syncing the range could be an improvement for a later release

**Comment by danielhrisca** [comment]
@pyyoungman 
I've added the sync of ranges in the development branch. Please give it a try

**Comment by danielhrisca** [comment]
Implemented in 5.18.0

**Comment by pyyoungman** [comment]
Hello,I try to change code to add multi _Plot in ine Plot,but there are some questions which i can not solve.After i change code,I find some erros about Cursor and Info show,thank you!











在 2020-02-22 21:27:33，"Daniel Hrisca" <notifications@github.com> 写道：

Implemented in 5.18.0
