### ISSUE TITLE
String values not displayed

### ISSUE THREAD

**Issue by chrism431** [danielhrisca/asammdf#309]
# Python version
'python=3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.4'
'asammdf=5.16.3'

# Code 

```
 signal.plot()
 signal.copy()
```
  
# Description

When using signal.copy(), String values are replaced by numeric values (0) and cannot be displayed/plotted. 
After copying the signal, the String values are no longer visible in ETAS MDA, but seem to be inside the MDF file (org_file.get('signal').samples == new_file.get('signal').samples), the samples have not been modified.

My use case is to merge two files with different time bases. To do this I want to edit the timestamps of the one "behind" the other file.

When simply using 

```
testmdf = MDF('example.mdf') 
exportmdf = testmdf.save(dst='export') 
```

and analyzing the file in MDA, the values are still correctly displayed. 

samples look like [b'String' b'String' ... b'String']

Using the GUI tool, the values are set to 0, too. 

Do I need to set something to handle Strings? 

UPDATE:
Using the GUI and examining the data in Tabular mode, I can see the String values. The same in MDA, I can see the Strings but not in the Plot. 

UPDATE2:
using ignore value2text conversions I can see the numeric values, but not the text. Is it possible to use the text?

**Comment by danielhrisca** [comment]
Hello Christoph,

this should work

```python
ch = mdf.get(name, raw=True)
print(ch.samples)
print(ch.physical().samples)
ch.plot()
```

**Comment by chrism431** [comment]
Hi Daniel,

thank you for the input. I got it working now. For anyone else trying to do the same (applying a time offset and stacking files with String values).

Maybe there is a more efficient way, but `.iter_channels()` doesn't seem to give me the option to get the signal in raw form, so I have to iterate with it and then use `.get(name,raw=True)` to get the signal from the name:

```
def add_time_offset(mdf,offset):
    mdf_mod = MDF()
    
    for signal in mdf.iter_channels():                                
        new_sig = mdf.get(signal.name, raw=True)

        # modify timestamps
        arr = np.array(new_sig.timestamps)
        arr = arr + offset

        new_sig.timestamps = arr
        mdf_mod.append(new_sig)
    return mdf_mod
```

**Comment by danielhrisca** [comment]
I would use this function

```python
def add_time_offset(mdf,offset):
    mdf_mod = MDF()

    for gp_index, gp in enumerate(mdf.groups):
        channels = [(None, gp_index, ch_index) for ch_index, ch in enumerate(gp.channels)]

        signals = mdf.select(channels, raw=True, copy_master=False)

        if signals:
            # this works because all the signals share the same timestamps object
            signals[0].timestamps += offset

            mdf_mod.append(signals, common_timebase=True)
            
    return mdf_mod
```
