### ISSUE TITLE
local variable 'total_size' referenced before assignment

### ISSUE THREAD

**Issue by fredrikjacobson** [danielhrisca/asammdf#310]
# Python version
```
('python=3.7.6 (default, Dec 30 2019, 19:38:28) \n'
 '[Clang 11.0.0 (clang-1100.0.33.16)]')
'os=Darwin-18.7.0-x86_64-i386-64bit'
'numpy=1.18.1'
asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip
asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip
'asammdf=5.16.3'
```
# Code 

  ## MDF version
  4.1

  ## Code snippet
 Open file with GUI
  
  ## Traceback
 Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/utils.py", line 235, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/asammdf/mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 344, in __init__
    self._read(mapped=True)
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 606, in _read
    total_size=total_size,
UnboundLocalError: local variable 'total_size' referenced before assignment

Details: 2020-02-15, 17:35:00 -------------------------------------------------------------------------------- Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/asammdf/gui/utils.py", line 235, in run self.output = self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.7/site-packages/asammdf/mdf.py", line 123, in __init__ self._mdf = MDF4(name, **kwargs) File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 344, in __init__ self._read(mapped=True) File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 606, in _read total_size=total_size, UnboundLocalError: local variable 'total_size' referenced before assignment -------------------------------------------------------------------------------- File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/main.py", line 649, in open self.open_file(event) File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/main.py", line 688, in open_file self._open_file(file_name) File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/main.py", line 665, in _open_file self, File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/file.py", line 158, in __init__ progress=progress, File "/usr/local/lib/python3.7/site-packages/asammdf/gui/utils.py", line 200, in run_thread_with_progress raise Exception(thr.error) 
  
# Description

When trying to open a MDF-file containing only events, an exception is thrown where total_size is unitialized in mdf4.py. This was working in 5.14.1. 

I suppose total_size needs to be initialized in the else block here
https://github.com/danielhrisca/asammdf/blob/d30e53a12f8edca83c03b05cab63d0d8555b0f98/asammdf/blocks/mdf_v4.py#L598-L608

**Comment by danielhrisca** [comment]
Hello Fredrik,

I've pushed a fix to the development branch.

**Comment by danielhrisca** [comment]
> I suppose total_size needs to be initialized in the else block here

Yes, that was the problem. Thank you!

**Comment by fredrikjacobson** [comment]
Excellent, keep up the good work 👍

**Comment by fredrikjacobson** [comment]
Hi, 

I'm sorry I did not get the time around testing the development branch. Appears there was another unitialized variable: ```inval_total_size = 0``` 

I've verified that after adding ``ìnval_total_size```it is working with "zero channel" MDF-files only containing events.
