### ISSUE TITLE
samples and timestamps length mismatch in asammdf 5.x but not in 3.x or 4.x

### ISSUE THREAD

**Issue by morbult** [danielhrisca/asammdf#312]
Hi Daniel,

python=3.6.8
asammdf=5.17.3
numpy=1.16.4

I have run into a problem with some MDF 3.00 files. I run the following code 

```python
import asammdf
mdf = asammdf.MDF('measurement.mdf')
mdf.get('ADONZJMONNUTOYGCVFLZYHMJTNMGETB')
```

and get the following error traceback

```
asammdf - ERROR - ADONZJMONNUTOYGCVFLZYHMJTNMGETB samples and timestamps length mismatch (128099 vs 256198)
NoneType: None
Traceback (most recent call last):

  File "<ipython-input-10-fe9c050a3aed>", line 1, in <module>
    mdf.get('ADONZJMONNUTOYGCVFLZYHMJTNMGETB')

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 2998, in get
    encoding=encoding,

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\signal.py", line 99, in __init__
    raise MdfException(message)

MdfException: ADONZJMONNUTOYGCVFLZYHMJTNMGETB samples and timestamps length mismatch (128099 vs 256198)
```

The file **does** work with asammdf versions 3.5.0 and 4.7.11 at least, but not with any of the 5.x versions that I've tried. I sent you one of these files by email.

**Comment by danielhrisca** [comment]
Hello Mattias,

the new code from the development branch should have the problem fixed

**Comment by morbult** [comment]
Fantastic!
I will test the other files tomorrow.
When do you think the next release will be?

**Comment by danielhrisca** [comment]
I think by the end of this week I could have the release published

**Comment by morbult** [comment]
A tested several other files and the issue is gone.
Thanks for great and quick help!
