### ISSUE TITLE
Load/save inconsistency with numpy.bool_ type

### ISSUE THREAD

**Issue by dxpke** [danielhrisca/asammdf#314]
# Python version
```python
('python=3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.18.1'
'asammdf=5.18.0.dev3'
```

# Code 

  ## Code snippet
```python
from asammdf import *
import numpy as np

with MDF() as mdf:
    mdf.append(
        Signal(
            name="Test", samples=np.array([False, True]), timestamps=np.array([0, 1])
        )
    )
    mdf.save("Test.mf4", overwrite=True)
    print(mdf.get("Test").samples)
    print(mdf.get("Test").samples.dtype)

print("---")

with MDF("Test.mf4") as mdf:
    print(mdf.get("Test").samples)
    print(mdf.get("Test").samples.dtype)
```

  ## Output
```python
[False  True]
bool
---
[0 1]
uint8
```
  
# Description

Saving an array with NumPy dtype bool gets correctly saved as one-bit value (I verified manually that bit_count is 1 in the MDF). But on load, the one-bit field gets imported as uint8. I'm not sure if this is intentional or not (since 1 bit does not necessarily implicate boolean "truthiness"). I found it curious that save/load would modify the datatype though, so I wanted to bring this to your attention.

**Comment by danielhrisca** [comment]
This should work

```python
from asammdf import *
import numpy as np

with MDF() as mdf:
    mdf.append(
        Signal(
            name="Test", samples=np.array([False, True]), timestamps=np.array([0, 1])
        )
    )
    mdf.save("Test.mf4", overwrite=True)
    print(mdf.get("Test").samples)
    print(mdf.get("Test").samples.dtype)

print("---")

with MDF("Test.mf4") as mdf:
    mdf.configure(single_bit_uint_as_bool=True)
    print(mdf.get("Test").samples)
    print(mdf.get("Test").samples.dtype)
```

**Comment by dxpke** [comment]
Dang, I totally missed that one. Thanks. Probably the best that can be done given that MDF does not allow to annotate whether it is "truthy" or not.

**Comment by dxpke** [comment]
Actually, my use case (saving a 1-bit signal that is not actually boolean) would be best solved by exporting uint8 (or any other) dtype with bit_count 1. Is there a way to do that? (That would also solve the import problem without the configure statement)

**Comment by danielhrisca** [comment]
The channel will still be extracted as uint8 since this is the smallest data type of numpy, but you can alter apply a bit mask if you look at the _bit_count_ attribute
```python
from asammdf import *
import numpy as np

with MDF() as mdf:
    mdf.append(
        Signal(
            name="Test", samples=np.array([False, True]), timestamps=np.array([0, 1])
        )
    )
    mdf.save("Test.mf4", overwrite=True)
    print(mdf.get("Test").samples)
    print(mdf.get("Test").samples.dtype)

print("---")

with MDF("Test.mf4") as mdf:
    print(mdf.get("Test").bit_count)
    print(mdf.get("Test").samples.dtype)
```

**Comment by dxpke** [comment]
The suggestion is not quite what I was looking for, but what works is setting the `bit_count` manually in the Signal constructor call before saving the MDF file. Now what complicates my use case is that the channel that I want to have exported with bit_count 1 is actually a member of a structure that gets decomposed automatically on mdf.append, so I cannot just pass the bit_count. I guess I'll just have to fix up the value in the MDF channel block manually. Thanks again!
