### ISSUE TITLE
review of incoming changes

### ISSUE THREAD

**Issue by danielhrisca** [danielhrisca/asammdf#32]
# Pyhton version 
all

# Platform information
all

# _asammdf_ version
3.0.0dev

# Description

There are some topics regarding the upcoming 3.0.0 release that I would like to get some feed-back before releasing the code, so please share your opinion

1. mdf versions 2 and 3 are similar enough that the classes _MDF2_ and _MDF3_ have been merged in the new _MDF23_ class found in the file _mdf_v2_v3.py_. I couldn't come with a better naming and it feels a bit odd. Maybe we can come up with a better name

2. _MDF_ objects are now iterable so you can write code like this:
    ```python
    mdf = MDF(filename)
    for signal in mdf:
        # do something
    ```
    There are two things to decide here:

    1. at the moment the iterator is configurable to yield _Signal_ objects or _pandas DataFrame_:
        ```python
        from asammdf import MDF, configure
        configure(iter_channels=True)
        mdf = MDF(filename)
        for signal in mdf:
            # do something with Signal objects
        configure(iter_channels=False)
        for dataframe in mdf:
            # do something with the whole channel group as pandas DataFrame
        ```
        Should we keep this option or stick to yielding only _Signal_ objects?
    2. when the iterator is configured to yield _Signal_ objects the master channels are not yielded. 
        Should we also yield the master channel?

**Comment by JulienGrv** [comment]
Hi Daniel!

Thank you for consulting us before committing changes. Here is my feedback for you:

1. I don't know the specifications for MDF v2 and v3 so my advices are more for the reflection:
It is of course good if you can refactor the code into one class if you know that the code is really most of the same. However, if it implies to put lots of conditions (if) in the code, it could also become very confusing especially for new contributors but I think you already thought about this.
Otherwise for the filename, if you use mdf_v2_v3, you can rename mdf4 to mdf_v4 if it makes things more consistent. You can also keep two files mdf2 and mdf3, and make MDF3 inherits from MDF2 class, it's interesting especially if MDF3 is more of an MDF2 extension and if you feel like that you will have different implementations for certain things between MDF2 and MDF3 (but since you feel like merging, maybe it's not the case).

2.
    1. to be honest, I don't like this configure thing.
    I would rather create two iterator functions: itersignals() and itergroups() just like itervalues() and iterkeys() for dictionaries. And I would then choose itersignals() as the default one for the `for signal in mdf:`.
    IMO, it is more sustainable, you can easily add new iterators in the future, and you can even change the default iterator because itersignals() and itergroups() will always remain.

    2. I would yield master channels as well. There are signals like every other channels.

**Comment by danielhrisca** [comment]
Hello Julien,

thank you for your input.

1. there are some differences regarding some blocks (for example CNBLOCK) and I feel that it makes more sense to use _if_ checks than to have MDF3 inherit from MDF2. _mdf_v2_v3.py_ looks consistent. I think the classes should also be renamed to something similar (_MDF_V4_, _MDF_V2_V3_)
2. 
    1. it looks more coherent than the _configure_ option. What about the rest of the options available in _configure_?
    2. I was 50-50 on this one

**Comment by JulienGrv** [comment]
1. Ok, I really no nothing about MDF v2 and MDF v3 so I follow you on this 👍 Yes renaming to MDF_V4 and MDF_V2_V3 makes sense but I feel you it is ugly :') On the other hand, it is the most logical decision so.

2.
    1. I think it is okay for the compacting and split options, since they are more like options for developers and could potentially evolve or change in the future. But the overwrite option, I will rather make it an argument of the save() function, because it's behaviour is clear and there is no reason to have it _separated_.

    2. I think Signals should be all of that, that can be plotted. Just like in CANape. If we skip master channels, I feel like it is less consistent. We can add an attribute in the Signal class that stores the type of the signal (channel, master channel, etc.) for the user to easily filter out the master channels when iterating over the signals. We can also have an option for the iterator, like itersignals(skip_masters=True), I like this last idea.

**Comment by danielhrisca** [comment]
1. it doesn't look pretty but it's better at least than _MDF23_. Initially the code for versions 2 and 3 was split in two files, but the similarity is two high to keep them separated (you can have a look at the code from the 2.8.1 release)
2. 
    
    1. The idea behind the _configure_ _overwrite_ option was to act like a global option, since the _save_ method already has an _overwrite_ argument which, when supplied, overrules the global option:
        ```python
        # configure just once
        configure(overwrite=True)
        mdf1.save(name)
        ...
        mdf1000.save(name)

        # instead of supplying the overwrite argument for every save call
        mdf1.save(name, overwrite=True) # or mdf1.save(name, True)
        ...
        mdf1000.save(name, overwrite=True)
        ```
        
    2. for me CANape hides the master channel. Anyway a configurable _itersignals_ method is a good idea.
        
        ![image](https://user-images.githubusercontent.com/20952040/34560757-d2c5a150-f14f-11e7-9d04-1241ee599856.png)
        ![image](https://user-images.githubusercontent.com/20952040/34560772-e7d014c2-f14f-11e7-81b5-0f5d366fa3d3.png)

**Comment by JulienGrv** [comment]
1. 👍

2.
    1. I did not know that the overwrite option was also available as an argument in the function. With that in my mind, I think the configure function is good like that.

    2. ok, in that case, we can default the argument skip_masters to True.

**Comment by danielhrisca** [comment]
In commit 6bf548842f6a10679ea2dac97ba28350d28d0939 I've switched back to having separate classes for each version: _MDF2_ just inherits from _MDF3_, thus basically sharing the same code.

**Comment by JulienGrv** [comment]
Is there a reason why you chose that MDF2 inherits MDF3 instead of MDF3 inheriting MDF2?

**Comment by danielhrisca** [comment]
From what I know CPython searches for object attributes in the class and if not found it goes to the base class to find it. This means you get a performance penalty (I haven't actually measured it) in the _MDF2_ class and no penalty for _MDF3_

**Comment by jed-frey** [comment]
You could also investigate mixins and consolidate common functions into a separate classes that all the MDF2-4 inherit from.

```
class Loader(object):

class Plot(object):

class Export(object):

class MDF2(Loader, Plot, Export):
```

**Comment by danielhrisca** [comment]
@jed-frey 
I did think of this and I honestly don't see an architecture that would prevent circular imports.

Let's take the _convert_ method. Supposed we have this in a _BaseMixin_ class that is inherited by the _MDFx_ classes. The goal is to be able to use the common interface class _MDF_ to handle different versions so the _convert_ must use the _MDF_ class. This would give the following import chain:
`` MDF -> MDFx -> BaseMixin -> MDF``

I do admit the current linking of the _MDFx_ attributes to the _MDF_ object is not pleasant. It would be great if we could come up with a better/pythonic solution (maybe I'm just to embedded and can't see a more obvious way to handle this).

**Comment by danielhrisca** [comment]
I'm working on optimizations that will impact both RAM usage and execution time. I'll let everybody know when the code will be pushed to have a look over it.

A glimpse of what is coming:

|Open file                                         |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 2.8.0 full mdfv4                          |     2098|     386|
|asammdf 3.0.0dev full mdfv4                       |     1843|     319|
|asammdf 2.8.0 low mdfv4                           |     1852|     221|
|asammdf 3.0.0dev low mdfv4                        |     1756|     154|
|asammdf 2.8.0 minimum mdfv4                       |     1361|      93|
|asammdf 3.0.0dev minimum mdfv4                    |      968|      77|


|Save file                                         |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 2.8.0 full mdfv4                          |      456|     391|
|asammdf 2.8.0 low mdfv4                           |      490|     233|
|asammdf 2.8.0 minimum mdfv4                       |     2124|     102|
|asammdf 3.0.0dev full mdfv4                       |      641|     324|
|asammdf 3.0.0dev low mdfv4                        |      597|     165|
|asammdf 3.0.0dev minimum mdfv4                    |       0*|      0*|


|Get all channels (36424 calls)                    |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 2.8.0 full mdfv4                          |      732|     394|
|asammdf 3.0.0dev full mdfv4                       |      727|     327|
|asammdf 2.8.0 low mdfv4                           |     6893|     230|
|asammdf 3.0.0dev low mdfv4                        |     6948|     163|
|asammdf 2.8.0 minimum mdfv4                       |     9028|     104|
|asammdf 3.0.0dev minimum mdfv4                    |     8895|      89|


|Convert file                                      |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 2.8.0 full v4 to v3                       |     4138|     757|
|asammdf 2.8.0 low v4 to v3                        |     4532|     318|
|asammdf 2.8.0 minimum v4 to v3                    |     7391|     140|
|asammdf 3.0.0dev full v4 to v3                    |     3272|     688|
|asammdf 3.0.0dev low v4 to v3                     |     3768|     249|
|asammdf 3.0.0dev minimum v4 to v3                 |     6378|     123|


|Merge files                                       |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 2.8.0 full v4                             |    12723|    1439|
|asammdf 2.8.0 low v4                              |    14116|     554|
|asammdf 2.8.0 minimum v4                          |    18160|     234|
|asammdf 3.0.0dev full v4                          |     9945|    1247|
|asammdf 3.0.0dev low v4                           |    11405|     372|
|asammdf 3.0.0dev minimum v4                       |       0*|      0*|

**Comment by danielhrisca** [comment]
The optimizations are integrated now for all mdf versions:

Benchmark environment

* 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
* Windows-10-10.0.14393-SP0
* Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
* 16GB installed RAM

Notations used in the results

* full =  asammdf MDF object created with memory=full (everything loaded into RAM)
* low =  asammdf MDF object created with memory=low (raw channel data not loaded into RAM, but metadata loaded to RAM)
* minimum =  asammdf MDF object created with memory=full (lowest possible RAM usage)

Files used for benchmark:

* 183 groups
* 36424 channels



|Open file                                         |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 3.0.0dev full mdfv3                       |      637|     271|
|asammdf 3.0.0dev low mdfv3                        |      551|     118|
|asammdf 3.0.0dev minimum mdfv3                    |      504|      77|
|asammdf 2.8.1 full mdfv3                          |      865|     323|
|asammdf 2.8.1 low mdfv3                           |      757|     170|
|asammdf 2.8.1 minimum mdfv3                       |      473|      82|
|asammdf 3.0.0dev full mdfv4                       |     1987|     309|
|asammdf 3.0.0dev low mdfv4                        |     1867|     145|
|asammdf 3.0.0dev minimum mdfv4                    |     1029|      77|
|asammdf 2.8.1 full mdfv4                          |     2076|     386|
|asammdf 2.8.1 low mdfv4                           |     1971|     221|
|asammdf 2.8.1 minimum mdfv4                       |     1419|      93|


|Save file                                         |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 3.0.0dev full mdfv3                       |      208|     271|
|asammdf 3.0.0dev low mdfv3                        |      270|     124|
|asammdf 3.0.0dev minimum mdfv3                    |      644|      89|
|asammdf 2.8.1 full mdfv3                          |      380|     325|
|asammdf 2.8.1 low mdfv3                           |      436|     176|
|asammdf 2.8.1 minimum mdfv3                       |     1076|      91|
|asammdf 3.0.0dev full mdfv4                       |      535|     313|
|asammdf 3.0.0dev low mdfv4                        |      566|     156|
|asammdf 3.0.0dev minimum mdfv4                    |     1910|      87|
|asammdf 2.8.1 full mdfv4                          |      482|     392|
|asammdf 2.8.1 low mdfv4                           |      544|     233|
|asammdf 2.8.1 minimum mdfv4                       |     2196|     102|


|Get all channels (36424 calls)                    |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 3.0.0dev full mdfv3                       |      713|     277|
|asammdf 3.0.0dev low mdfv3                        |     3646|     131|
|asammdf 3.0.0dev minimum mdfv3                    |     5130|      92|
|asammdf 2.8.1 full mdfv3                          |      699|     329|
|asammdf 2.8.1 low mdfv3                           |     3595|     182|
|asammdf 2.8.1 minimum mdfv3                       |     4853|      96|
|asammdf 3.0.0dev full mdfv4                       |      757|     313|
|asammdf 3.0.0dev low mdfv4                        |     7123|     151|
|asammdf 3.0.0dev minimum mdfv4                    |     9526|      85|
|asammdf 2.8.1 full mdfv4                          |      762|     394|
|asammdf 2.8.1 low mdfv4                           |     7077|     231|
|asammdf 2.8.1 minimum mdfv4                       |     9737|     105|


|Convert file                                      |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 3.0.0dev full v3 to v4                    |     3137|     652|
|asammdf 3.0.0dev low v3 to v4                     |     3624|     230|
|asammdf 3.0.0dev minimum v3 to v4                 |     5338|     142|
|asammdf 2.8.1 full v3 to v4                       |     3564|     756|
|asammdf 2.8.1 low v3 to v4                        |     4089|     336|
|asammdf 2.8.1 minimum v3 to v4                    |     5239|     167|
|asammdf 3.0.0dev full v4 to v3                    |     3335|     662|
|asammdf 3.0.0dev low v4 to v3                     |     3850|     224|
|asammdf 3.0.0dev minimum v4 to v3                 |     6837|     118|
|asammdf 2.8.1 full v4 to v3                       |     4230|     758|
|asammdf 2.8.1 low v4 to v3                        |     4857|     319|
|asammdf 2.8.1 minimum v4 to v3                    |     7945|     140|


|Merge files                                       |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 3.0.0dev full v3                          |     8045|    1200|
|asammdf 3.0.0dev low v3                           |     9718|     343|
|asammdf 3.0.0dev minimum v3                       |    12541|     222|
|asammdf 2.8.1 full v3                             |     8720|    1317|
|asammdf 2.8.1 low v3                              |    10322|     461|
|asammdf 2.8.1 minimum v3                          |    12337|     233|
|asammdf 3.0.0dev full v4                          |    10533|    1221|
|asammdf 3.0.0dev low v4                           |    12122|     345|
|asammdf 3.0.0dev minimum v4                       |    17795|     176|
|asammdf 2.8.1 full v4                             |    13492|    1438|
|asammdf 2.8.1 low v4                              |    14911|     554|
|asammdf 2.8.1 minimum v4                          |    19636|     233|

A code style clean-up is coming next since there were many changes made to the code base.

**Comment by danielhrisca** [comment]
I'm currently investigating using generators to help dealing with problematic files (for example huge files with thousands of channels I'm a single channel group). Initial code shows neglijabile impact to more common files so I think it makes sense to integrate this feature in this release as well.

**Comment by danielhrisca** [comment]
It looks like integer compacting will have to be dropped. Was anybody using this feature?

**Comment by JulienGrv** [comment]
I never used it

**Comment by danielhrisca** [comment]
The changes related to generator based file parsing have landed in the development branch. The code is unpolished on some parts, and there have been a lot of changes made.
It passes all current tests on Python 3 and fails with some weird error ok Python 2. I hope I will sort this out during the weekend.
It would be interesting to see how it performs with larger files (more than 4MB per data group ).
Please try it out and report the bugs found.

**Comment by danielhrisca** [comment]
The Python 2 errors have been fixed to the point that the curent CI tests are passing.

**Comment by danielhrisca** [comment]
The functionality has been implemented in the development branch. Some methods are not yet optimized to take advantage of the new split parsing of channel group samples (convert and filter are optimized now).
 
For now the splitting is done if the user sets a size by calling the _set_split_size_ method, or if the total channel group samples size is bigger than 4 MB.

It would be interesting to see how the new code works with big files

**Comment by danielhrisca** [comment]
The package level _configure_ function was removed. This means:
* splitting data on save for mdf version 4 is enabled by default
* each _MDFx_ class has a _configure_ method that can be used to set the read and write fragment size
* save overwrite behavior will only be set when calling the _save_ method

**Comment by danielhrisca** [comment]
3.0.0 is out!
Thanks to all involved!
