### ISSUE TITLE
ASAMDF How to fill an array with the list of the all Signal name and sample rate

### ISSUE THREAD

**Issue by lcn84dcr** [danielhrisca/asammdf#321]
# Python version
Python 3.7

  ## MDF version
ASAMMDF 5.18.2

_Please describe the issue here._

Hi to all.
I have a .dat file from Inca measurement. I use the following code for importing the file into a Python script for plotting and elaborate some Signal: mdf = MDF('measure.dat')
Supposing that in the measurement there're 5 Signal, I would like to create a numpy multimensional array of 5 raw X 2 column, where in the first column there're all the Signal name and in the second column there're the corresponding sample time. 
How can I do ? Thanks a lot for the help.

**Comment by danielhrisca** [comment]
try this

```python
import numpy as np
    import pandas as pd

    mdf = MDF('test.mf4')

    channel_names = []
    sampling_rates = []

    for i, group in enumerate(mdf.groups):
        master = mdf.get_master(i)
        master_index = mdf.masters_db.get(i, -1)
        if len(master) > 1:
            rate = np.mean(np.diff(master))
        else:
            rate = 0
        names = [
            ch.name
            for j, ch in enumerate(group.channels)
            if j != master_index
        ]
        rates = [rate for name in names]

        channel_names.extend(names)
        sampling_rates.extend(rates)

    df = pd.DataFrame(data={'channel name': channel_names, 'sampling rate [s]': sampling_rates})

    print(df)
```

**Comment by lcn84dcr** [comment]
Hi Daniel.
It's exactly what I asked. Thanka a lot!
