### ISSUE TITLE
miss understand mdf4 instance's attributes

### ISSUE THREAD

**Issue by ZJLi2013** [danielhrisca/asammdf#322]
# Python version
python 3.5

# Description

hey, guys, thanks for this project. I am trying it today. a lot confus. so I had a mf4 file about 200Mb, I don't know wha't inside right now.

so I tried two things:

1) 

```python
     reader = MDF4(my_file_name)
     channels = reader.groups[2]
     print(" chanels len: " , len(channels["channels"])) #577
    print("chanel_group len: " , len(channels["channel_group"])) #17
    print(" data_group len: " , len(channels["data_group"])) #10    
```

2) 

```python
    reader = MDF4(my_file_name)
    info_ = reader.info()
    print(info_.keys())  # 300 groups
    print(info_[keys[0]]) # more than 1000 channels
```

why the number of `groups` and `channels` is so different if reading by `info()` compared to  access its attributes directly ?

Thanks

**Comment by danielhrisca** [comment]
What asammdf version do you use?

**Comment by danielhrisca** [comment]
Some tips:
* always use the MDF class, depending on the file version it will also include the methods available in the MDF3 or MDF4 classes
* use the _whereis_ method to get see where a channel name is found in the measurement
* update to the latest asammdf version, from your code it looks like you are using an old version

**Comment by ZJLi2013** [comment]
> Some tips:
> 
> * always use the MDF class, depending on the file version it will also include the methods available in the MDF3 or MDF4 classes
> * use the _whereis_ method to get see where a channel name is found in the measurement
> * update to the latest asammdf version, from your code it looks like you are using an old version

thanks for helping, I misunderstood the attributes of  mdf4 object, now a problem now.
