### ISSUE TITLE
How to clean header of one dat?

### ISSUE THREAD

**Issue by MacsYan** [danielhrisca/asammdf#323]
I am sorry to bother you again.
I came across one problem when I use python packages asammdf.
I want to clean header of one dat with the python statements:

from asammdf import MDF

dat_path = r'D:\project\AI emission cleaning\data\718-3415ET.2 ECU DI 12\20190202.dat'
dat = MDF(dat_path)
dat.hearder = ''

How I save dat file with the header cleaned?
I used dat.save(dat_path,overwrite=True).
However the file name is changed and the header cleaned can't be saved.

Thank you for your kindly help.
```

**Comment by danielhrisca** [comment]
You have to use a _HeaderBlock_ object

```python
from asammdf import MDF
from asammdf.blocks.v2_v3_blocks import HeaderBlock

dat_path = r'D:\project\AI emission cleaning\data\718-3415ET.2 ECU DI 12\20190202.dat'
dat = MDF(dat_path)
dat.header=HeaderBlock()
dat.save(dat_path,overwrite=True)
```

**Comment by danielhrisca** [comment]
ping @MacsYan
