### ISSUE TITLE
Question: Iterating over channels from existing mdf and append to new mdf is much bigger then source mdf?

### ISSUE THREAD

**Issue by KeenMeron** [danielhrisca/asammdf#324]
```python
from asammdf import MDF

datpath = r'source.mdf'  # Type: mdf2.0 Size: 250MB
mdf = MDF(datpath)

with MDF(version='4.10') as mdf4:
    mdf.convert(version='4.10')
    mdf.save(r"saveDirectly.mdf", overwrite=True, compression=1) # Type: mdf4.10 Size: 160MB

    for channel in mdf.iter_channels():
        mdf4.append(channel)

    mdf4.save(r"iter_chans.mdf", overwrite=True, compression=1) # Type: mdf4.10 Size: 470MB
```
# Description
Hi, I have an issue with combining two .dat / .mdf files to one file. 

We are using Avl Concerto to view and plot .mdf files. In my Python script I read all the data of two files (.dat and .mdf), calculating an offset and shift the channels in one file to match the other one.

My routine is, to use mdf.iter_channels() to edit every single channel with the offset and save them all to one new list of channels.

I've figured out, that some channels aren't interpreted correctly after using iter_channels + appending the channel. 

**Example Samples:**  true or false / True or False / TRUE or FALSE ... -> interpretation isn't always correct. I've added a routine that changes the samples and convert them to 0 or 1.

Then I tried with a small code snippet (code example above) saving a source mdf 2.0 file directly to mdf 4.10 and saving over iter_channels -> append -> save.

**Directly saved file:** No wrong interpreted channels and the file is much smaller than the source file.
**Saving over iter_channels:** Wrong interpreted channels and the file is much much bigger and reading it is slower.

Is there any background for that occurrence? And how can I workaround this?

My steps are:

1. **Read** mdf file and dat file
2. **Get offset** between both through correlation
3. **Offset correction** in the dat file (iter_channels -> save offset corrected channel to new list of channels)
4. Iter_channels of mdf and channel list from 3. to **merge them to** one list and save it as **one file** 

Any advices? :)
Thank you!

**Comment by danielhrisca** [comment]
> **Saving over iter_channels:** Wrong interpreted channels and the file is much much bigger and reading it is slower.

Normally a channel group has multiple channels and a common time channel.
Appending single channels to the new MDF  file will create a new channel group for each append. This means that the common time channel is now repeated for each additional channel group. This is what causes the larger file size.

What do you mean by "wrong interpreted channels"? Can you print one together with its corrected version?

**Comment by KeenMeron** [comment]
Ok, thank you for the fast reply. 

Is there any way, to add an offset to a group of channels and save them to a new group? Or how can i avoid the repetion of the time channel?

I will try to get a better example.

**Comment by danielhrisca** [comment]
An easy solution is to use iter_groups

```python
from asammdf import MDF

datpath = r'source.mdf' 
mdf = MDF(datpath)

with MDF(version='4.10') as mdf4:
    mdf.convert(version='4.10')
    mdf.save(r"saveDirectly.mdf", overwrite=True, compression=1)
    
    for df in mdf.iter_groups():
        df.index = df.index + offset 
        mdf4.append(df)

    mdf4.save(r"iter_chans.mdf", overwrite=True, compression=1)
```

**Comment by KeenMeron** [comment]
Hi danielhrisca,

i tried following code, but my system gets really fast out of memory. 

My intention was to avoid adding every single channel with append to the MDF, to keep one time channel. 
The memory problem begins with the second-last line mdf4.append(channels).
It eats in less then a few seconds 10 GB memory. 

Is there a better way to add an offset to the time channel of a group of channels (..and merge them with a another mdf file)?

```python
from asammdf import MDF

datpath = r'source.mdf'

mdf = MDF(datpath)


def offsetCorrection(offset, channel):
    i = 0
    for _ in channel.timestamps:
        channel.timestamps[i] = channel.timestamps[i] + offset
        i = i + 1


with MDF(version='4.10') as mdf4:
    channelsWithOffset = []
    for channel in mdf.iter_channels():
        offsetCorrection(10.5, channel)
        channelsWithOffset.Append(channel)

    # for group in mdf.iter_groups():
        ## add offset to a group?

    mdf4.append(channelsWithOffset)

    mdf4.save(r"output.mf4", overwrite=True, compression=1)
```


Here is one Signal with TRUE / FALSE entries. If i open the source file and plot the Signal -> no problem. If i get the signal over iter_channels and append it to a new mdf, then i cant plot it anymore in Concerto. Then i have to add a for loop to check TRUE / FALSE entries and convert them to 1 / 0 before appending them to the new mdf.

(I've changed Signal Name and the timestamps in the print output)

`<Signal Test:
	samples=[b'FALSE' b'FALSE' b'FALSE' ... b'FALSE' b'FALSE' b'FALSE']
	timestamps=[0 1 2 ... 10e+03 10e+03 10e+03]
	invalidation_bits=None
	unit=""
	conversion=None
	source=None
	comment="ABCD"
	mastermeta="('time', 1)"
	raw=False
	display_name=Test
	attachment=()>

<Signal Test:
	samples=[b'FALSE' b'FALSE' b'FALSE' ... b'FALSE' b'FALSE' b'FALSE']
	timestamps=[0 1 2 ... 10e+03 10e+03 10e+03]
	invalidation_bits=None
	unit=""
	conversion=None
	source=SignalSource(name='Python', path='Python', comment='', source_type=4, bus_type=0)
	comment="ABCD"
	mastermeta="('time', 1)"
	raw=False
	display_name=Test
	attachment=()>`

**Comment by danielhrisca** [comment]
For the 

> Here is one Signal with TRUE / FALSE entries.

For this channel you need to get it as raw before appending it to the new file

```python
ch = mdf.get('TEST', raw=True)
mf4.append(ch)
```



> The memory problem begins with the second-last line mdf4.append(channels).
> It eats in less then a few seconds 10 GB memory.

Can you send the file? You may scramble it to protect sensitive information

**Comment by KeenMeron** [comment]
> 
> 
> An easy solution is to use iter_groups
> 
> ```python
> from asammdf import MDF
> 
> datpath = r'source.mdf' 
> mdf = MDF(datpath)
> 
> with MDF(version='4.10') as mdf4:
>     mdf.convert(version='4.10')
>     mdf.save(r"saveDirectly.mdf", overwrite=True, compression=1)
>     
>     for df in mdf.iter_groups():
>         df.index = df.index + offset 
>         mdf4.append(df)
> 
>     mdf4.save(r"iter_chans.mdf", overwrite=True, compression=1)
> ```

Ok thank you. I tried it with small mdf files (which i have generated out of csv files) and it works. 

But if i take the .dat file it says:
ValueError: array-shape mismatch in array 1
```
...\mdf_v4.py:4637: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  offsets = arange(len(sig), dtype=uint64) * (sig.itemsize + 4)
...\mdf_v4.py:4639: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  values = [full(len(signal), sig.itemsize, dtype=uint32), sig]
Traceback (most recent call last):
  File "..script.py", line 10, in <module>
    mdf4.append(df)
  File "...\mdf_v4.py", line 2859, in append
    self._append_dataframe(signals, source_info, units=units)
  File "...\mdf_v4.py", line 4643, in _append_dataframe
    data = fromarrays(values, dtype=types_)
  File "...\lib\site-packages\numpy\core\records.py", line 638, in fromarrays
    raise ValueError("array-shape mismatch in array %d" % k)
ValueError: array-shape mismatch in array 1
```

**Comment by KeenMeron** [comment]
> 
> 
> > Here is one Signal with TRUE / FALSE entries.
> 
> For this channel you need to get it as raw before appending it to the new file
> 
> ```python
> ch = mdf.get('TEST', raw=True)
> mf4.append(ch)
> ```
> 
> > The memory problem begins with the second-last line mdf4.append(channels).
> > It eats in less then a few seconds 10 GB memory.
> 
> Can you send the file? You may scramble it to protect sensitive information

The "raw" thing did it so far:

```python
from asammdf import MDF

datpath = r'Source.dat'
mdf = MDF(datpath)
offset = 100


def offsetCorrection(_offset, channel):
    i = 0
    for _ in channel.timestamps:
        channel.timestamps[i] = channel.timestamps[i] + _offset
        i = i + 1

def getSignalRaw():
    with MDF(version='4.10') as mdf4:
        for channel in mdf.iter_channels():
            rawChannel = mdf.get(channel.name, raw=True);
            offsetCorrection(100, rawChannel)
            mdf4.append(rawChannel)

        mdf4.save(r"Output.mf4", overwrite=True, compression=1)


if __name__ == "__main__":
    getSignalRaw()
```

Does the def getSignalRaw() make sense? I iterate over all channels, get the channel name to get the raw signal and add an offset. Then i append them to a new mdf file. The other problem still persists, that every channel is a group with own time channel.

**Comment by KeenMeron** [comment]
> Can you send the file? You may scramble it to protect sensitive information

I will try to get a not critikal .dat file, which i can send you.

**Comment by danielhrisca** [comment]
Ping @KeenMeron

**Comment by danielhrisca** [comment]
Ping @KeenMeron

**Comment by KeenMaron** [comment]
Hey danielhrisca, i changed my employer and i'm not working anymore with this topic. Sorry :/

**Comment by danielhrisca** [comment]
I see no other option but to close this issue

**Comment by acewalker** [comment]
Hi Daniel, I am facing the same issue. My 17 GB data file changes into 64 GB. I am doing arithmetic operations on 55 signals being logged at 10Khz of which four at 100 kHz. I should be expecting approximately 4Gb data increases provided I collected my data ~2 hrs.

Using the append function. Before appending I print the dictionary/object I created which is 33 MB/channel.
