### ISSUE TITLE
Plot Signals with NAN fails

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#325]
# Python version
('python=3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit ' '(AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'asammdf=5.19.1'

# Code 

  ## MDF version
  4.1

  ## Code snippet
  none - GUI Failure
  
  ## Traceback

[NA_value_problems.scrambled.zip](https://github.com/danielhrisca/asammdf/files/4320697/NA_value_problems.scrambled.zip)
[NA_value_problems.scrambled.zip](https://github.com/danielhrisca/asammdf/files/4320703/NA_value_problems.scrambled.zip)

2020-03-11, 21:02:07
--------------------------------------------------------------------------------
<class 'ValueError'>	 
All-NaN slice encountered
--------------------------------------------------------------------------------
  File "D:\Software\WPy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\plot.py", line 1623, in xrange_changed_handle
    self.trim()
  File "D:\Software\WPy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\plot.py", line 1578, in trim
    pos_max = np.nanargmax(samples, axis=1)
  File "<__array_function__ internals>", line 6, in nanargmax
  File "D:\Software\WPy-3710\python-3.7.1.amd64\lib\site-packages\numpy\lib\nanfunctions.py", line 551, in nanargmax
    raise ValueError("All-NaN slice encountered")
  
# Description

Ploting Signals with NA values failes. With asammdf 5.18, I can't reproduce the failure.

Furthermore with 5.18, the Signal with NANs is only displayed in dotted mode and measurement points are not connected to a line.

**Comment by stlweb** [comment]
[NA_value_problems.scrambled.zip](https://github.com/danielhrisca/asammdf/files/4320707/NA_value_problems.scrambled.zip)

**Comment by danielhrisca** [comment]
@stlweb please check the development branch

**Comment by stlweb** [comment]
it's working fine
