### ISSUE TITLE
error: TypeError: divmod expected 2 arguments, got 1

### ISSUE THREAD

**Issue by Eddiechiu** [danielhrisca/asammdf#33]
Hi, 
I have a problem using asammdf , hope you can help me~
When I open a.mf4 file like this:

`from asammdf import MDF`
`mdf = MDF('F110.mf4', version='4.10')`
`speed = mdf.get('Speed')`

it shows that:
  File "......\asammdf\mdf4.py", line 3574, in get
    pos_byte, pos_offset = divmod(ch_invalidation_pos)

TypeError: divmod expected 2 arguments, got 1

How can I do with it and why there is only one argument 'ch_invalidation_pos' in divmod?

Thank you very much and have a nice day~

**Comment by danielhrisca** [comment]
Hey,

please check if it is fixed in the latest development commit https://github.com/danielhrisca/asammdf/commit/1a70713ed64120f67731912eef3034e12b9c8f34

**Comment by Eddiechiu** [comment]
Thank you so much!
But there comes another error:

  File "....\asammdf\mdf4.py", line 3579, in get
    [bytes_[pos_byte] & mask for bytes_ in inval_bytes]

TypeError: unsupported operand type(s) for &: 'str' and 'int'

In my .mf4 file, In the 'Speed' channel, there are some points that only has time value and the speed value is missing. I think this may be the reason and how can I do with it?

**Comment by danielhrisca** [comment]
Please print the output of this:
```python
import asammdf
print(asammdf.__version__)
```
The file _mdf4.py_ was renamed to _mdf_v4.py_ in the development branch so you probably have a wrong installation.

**Comment by Eddiechiu** [comment]
The version is '2.8.1'.
I just use
`pip install asammdf`

**Comment by danielhrisca** [comment]
Use this to install the latest code from development branch

``pip install https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by Eddiechiu** [comment]
Many thanks! But it still doesn't work.

  File "......\asammdf\mdf_v4.py", line 3803, in get
    [bytes_[pos_byte] & mask for bytes_ in inval_bytes]

TypeError: unsupported operand type(s) for &: 'str' and 'int'

**Comment by danielhrisca** [comment]
I see that you have python 2.7 since the code work on Python 3.

I've made a change to make it compatible with python 2. 

Please install again.

**Comment by Eddiechiu** [comment]
AWESOME!
Thank you so much, it works~

**Comment by danielhrisca** [comment]
Great!

In this case I will close this issue.

**Comment by danielhrisca** [comment]
Hello,

I've made a lot of changes to the code base in the development branch. Could you please try the new code and check if it works correctly with your files?

**Comment by Eddiechiu** [comment]
Ok, no problem ! Thank you !
The mdf file is in my office PC, I will try the code as soon as possible.

**Comment by Eddiechiu** [comment]
Hi, daniel,
when I tried:
mdf = MDF('F44.mf4')
it results in:

  File "C:\Users\DQ\Anaconda3\lib\site-packages\asammdf\mdf_v4.py", line 176, in __init__
    self._read()

  File "C:\Users\DQ\Anaconda3\lib\site-packages\asammdf\mdf_v4.py", line 378, in _read
    data = next(data)

  File "C:\Users\DQ\Anaconda3\lib\site-packages\asammdf\mdf_v4.py", line 899, in _read_data_block
    size=size):

  File "C:\Users\DQ\Anaconda3\lib\site-packages\asammdf\mdf_v4.py", line 865, in _read_data_block
    view[position: position+uncompressed_size] = block['data']

ValueError: memoryview assignment: lvalue and rvalue have different structures

**Comment by danielhrisca** [comment]
Hello Derong,

would you mind running the latest developemnt code (https://github.com/danielhrisca/asammdf/commit/e195327e9afda7ce01eebb200503eba4873b0a1d) again with your file. 

There were many fixes applied, maybe your error also fixed.

**Comment by Eddiechiu** [comment]
T.T

  File ".....anaconda2\lib\site-packages\asammdf\mdf_v4.py", line 853, in _read_data_block
    view[position: position+uncompressed_size] = block['data']

ValueError: cannot modify size of memoryview object

**Comment by Eddiechiu** [comment]
should I just use:
pip install -U --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip

**Comment by danielhrisca** [comment]
That is the recommended way, but you can also overwrite the files by hand.

I will look into this error.

**Comment by danielhrisca** [comment]
--no-deps avoids breaking your packages (if you have Anaconda or WinPython; if you work on Linux there should be no problem)

**Comment by Eddiechiu** [comment]
how can I reset my asammdf to the last last version that it can correctly parse the mdf file ?
Thank you ~

**Comment by danielhrisca** [comment]
``pip install -I --no-deps asammdf``

this will install version 2.8.2 from PyPI

**Comment by danielhrisca** [comment]
Hello Derong,

I think I've fixed the problem with the latest code in development.
You can execute 
``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``
to bring the new code and verify the fix, and if you would like to switch back to the 2.8.2 release code you can execute
``pip install -I --no-deps asammdf``

**Comment by Eddiechiu** [comment]
Hi, daniel

the last version turns out to be:
<img width="741" alt="11111111" src="https://user-images.githubusercontent.com/16081098/35672191-ada4c420-0778-11e8-8742-4b1eeeea8669.PNG">
The time span of the black curve is wrong, it's too short. The sampling rates of these signals are different.

It should be like this:
<img width="799" alt="22222222" src="https://user-images.githubusercontent.com/16081098/35672127-7da637cc-0778-11e8-974a-8e4568154d02.PNG">

Thank you anyway~

**Comment by danielhrisca** [comment]
1. what memory option do you use to load the file?
2. can you check if the master channel of the channel group holding the "compacted" channel is a virtual master?

**Comment by danielhrisca** [comment]
It seems that the problem was with the handling of virtual master channels.
Please check again the code from development.
Thank you for your time!

**Comment by Eddiechiu** [comment]
1. I didn't choose any memory option, I just use:
mdf = MDF('mdfFile.mf4')
data = mdf.get('channelName')
plot(data.timestamps, data.samples)

2. I only know the master channel of each channel group is 'time', which is the time channel. I don't know how to check whether the held "compacted" channel is a virtual master. Can I check it by asammdf ?
