### ISSUE TITLE
asammdf - WARNING - Different channel order in channel group

### ISSUE THREAD

**Issue by masoomk87** [danielhrisca/asammdf#330]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 '
 'bit (Intel)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.17.2'
'asammdf=5.14.1'
```
# Code 
import glob
import os
import numpy as np
import pandas as pd
from asammdf import MDF, Signal
from scipy.interpolate import interp1d
#import MyPlotLib as MyPlots
import matplotlib.pyplot as plt

# Directory where all the INCA .dat files are present
dir = r'C:\Project\'
os.chdir(dir)
DatFiles = []
FinalList = []

# Add all the .dat files to a list
for file in glob.glob("*.dat"):
    DatFiles.append(dir + '\\' + file)

# Read the signals that we are interested in for analysis purpose
sigfilepath = r'C:\Project\BigDataSignals.xlsx'
signal_list = pd.read_excel(sigfilepath, sheet_name='Results')  # Ye ek data-frame hai
x = signal_list.values
c = 1
# Read all the datfiles and make an mdf object for them
for files in DatFiles:
    # MDF object banao
    mdf = MDF(files, reduce_memory_usage=True)
    print(files)
    # Read all the signals in the .dat file being read. This will be used for comparison with signals in the excel file
    SignalsInDat = []
    k = mdf.channels_db
    count = 1
    for s in k:
        if s.find("\\") > -1 or s.find("/") > -1 or s.find("ETKC") > -1 or s.find("$") > -1:
            nothing = 1
        else:
            SignalsInDat.append(s)
    # Compare the signals in the .dat files from our list (excel), and make a final list of signals to read
    SignalsToRead = []
    for sigs in x:
        if (sigs[0] in SignalsInDat) == 1:
            SignalsToRead.append(sigs[0])

    if len(SignalsToRead) == len(x):
        valid = 1
        # Read only those signals which are common to excel and .dat file
        mdf = mdf.filter(SignalsToRead)
        mdf = mdf.resample(0.1)
        FinalList.append(mdf)
        del mdf

# Concatenate all the signals of the MDF file in mdf_merged object
mdf_merged = MDF.concatenate(FinalList)
del FinalList
  ## MDF version
  3.00

  ## Code snippet
  mdf_merged = MDF.concatenate(FinalList)
  
  ## Traceback
asammdf - WARNING - Different channel order in channel group 1 of file 7. Data can be corrupted if the there are channels with the same name in this channel group
asammdf - WARNING - Different channel order in channel group 1 of file 8. Data can be corrupted if the there are channels with the same name in this channel group
asammdf - WARNING - Different channel order in channel group 1 of file 9. Data can be corrupted if the there are channels with the same name in this channel group
asammdf - WARNING - Different channel order in channel group 1 of file 10. Data can be corrupted if the there are channels with the same name in this channel group
asammdf - WARNING - Different channel order in channel group 1 of file 11. Data can be corrupted if the there are channels with the same name in this channel group
asammdf - WARNING - Different channel order in channel group 1 of file 12. Data can be corrupted if the there are channels with the same name in this channel group
asammdf - WARNING - Different channel order in channel group 1 of file 13. Data can be corrupted if the there are channels with the same name in this channel group
Traceback (most recent call last):
  File "C:\Python374\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-bb1d726154c3>", line 57, in <module>
  
# Description

I am trying to read a bunch of mdf files that I recorded as a part of test program. I have created my code to read the signals that I am interested in, and they are taken from an excel file. So, eventually I append the mdf objects with the desired signals in - FinalList

The problem comes when I try to concatenate them, I get an exception that the channel order is not correct, and hence the objects can not be concatenated. I checked and saw that the signal order was different in some objects, after invoking - mdf = mdf.filter(SignalsToRead), probably because it was different in the source file

Is there a way to circumvent this problem, i.e., make the concatenation go through even though the channel order is different ?

**Comment by danielhrisca** [comment]
you could try this

```python
channels = mdf.select(SignalsToRead)
new_mdf = MDF()
new_mdf.append(channels)
new_mdf= new_mdf.resample(0.1)
FinalList.append(new_mdf)
```

**Comment by masoomk87** [comment]
Nice, thanks a lot :) This helped me a lot. However, I am stuck with another problem. Since the size of my arrays get quite big this way, I get a memory error - **MemoryError: Unable to allocate array with shape (6651076,) and data type float64**

Any interesting ways to circumvent this problems, like compressing the datatype to uint8 for the entire mdf object ?

**Comment by danielhrisca** [comment]
I hope the error occurs when you append the channels and not when you call _select_

In this case you may interpolate the signals before appending

```python
import numpy as np
new_timebase = np.arange(start, stop, 0.1)

channels = mdf.select(SignalsToRead)
interpolated_channels = []
while channels:
    channel = channels.pop(0)
    new_channels.append(channel.interp(new_timebase))
    channel = None
new_mdf = MDF()
new_mdf.append(channels, common_timebase=True)
FinalList.append(new_mdf)
```

**Comment by masoomk87** [comment]
The error does not occur while appending. The append process is successfully completed, and I am able to concatenate all the MDF objects

        channels = mdf.select(SignalsToRead)
        new_mdf = MDF()
        new_mdf.append(channels)
        new_mdf.resample(0.1)
        FinalList.append(new_mdf)
        del new_mdf

# Concatenate all the signals of the MDF file in mdf_merged object
`        channels = mdf.select(SignalsToRead)
        new_mdf = MDF()
        new_mdf.append(channels)
        new_mdf.resample(0.1)
        FinalList.append(new_mdf)
        del new_mdf

# Concatenate all the signals of the MDF file in mdf_merged object
mdf_merged = MDF.concatenate(FinalList)
del FinalList
plt.plot(mdf_merged.get('VarX').samples)`

For the first attempt, the plot goes fine, but it throws memory error expception when I try to replot any other variable again, from **mdf_merged** object

**Comment by danielhrisca** [comment]
```python
from asammdf.gui.plot import plot
sigs = mdf_merged.select(["Varx", "Vary"])
plot(sigs)
```

**Comment by masoomk87** [comment]
I realized that I had been using the 32 bit version of Python, and that is why I am running into memory problems. But now I installed 64 bit, and the out of memory problems are gone :)
