### ISSUE TITLE
the "time" signal is gone?

### ISSUE THREAD

**Issue by coppolajj** [danielhrisca/asammdf#331]
# Python version
'python=3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.17763-SP0'
'numpy=1.16.5'
'asammdf=5.19.6'
'pandas=0.25.1'

# Code 

  ## MDF version
3.00

  ## Code snippet
```
start = mdf.get('time').timestamps[0]
stop = mdf.get('time').timestamps[-1]
```
  
  ## Traceback
IndexError: index 0 is out of bounds for axis 0 with size 0
  
# Description
For awhile I've been using the above code snippet to get the beginning and ending time stamps of an mdf file, but now it appears that "time" is no longer is signal.  I *think* this popped up when I updated to 5.19.6 (just updated to 5.19.7 and still get the same error).  Any ideas why this might be happening?  If the change was intentional, any recommendation for getting the start and stop times?

Thx!

**Comment by danielhrisca** [comment]
Please print the signal returned by the get call

**Comment by coppolajj** [comment]
```
print(mdf.get('time'))
<Signal time:
	samples=[]
	timestamps=[]
	invalidation_bits=None
	unit=""
	conversion=None
	source=None
	comment=""
	mastermeta="('time', 1)"
	raw=False
	display_name=
	attachment=()>
```

**Comment by danielhrisca** [comment]
What about
```
for gp in mdf:
  print(gp.channel_group.cycles_nr)
```

**Comment by coppolajj** [comment]
```
for gp in mdf.groups:
  print(gp.channel_group.cycles_nr)

0
0
0
0
0
0
0
1939
19391
155122
7756
77562
3878
38781
310244
310244
100761
100760
302282
0
1
0
0
0
0
0
0
0
0
0
0
0
```

**Comment by danielhrisca** [comment]
Your first channel group has no samples hence the 0 length time channel.

You may have a look in this function to extract the min and max timestamp https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/utils.py#L1314

**Comment by coppolajj** [comment]
Thanks for the quick reply!  Sure enough, I tried some other datasets and had no problems with my original code snippet.  I'll update my script to use the following from `master_using_raster`:

```
t_min = []
t_max = []
for group_index in mdf.virtual_groups:
    group = mdf.groups[group_index]
    cycles_nr = group.channel_group.cycles_nr
    if cycles_nr:
        master_min = mdf.get_master(
            group_index, record_offset=0, record_count=1,
        )
        if len(master_min):
            t_min.append(master_min[0])
        master_max = mdf.get_master(
            group_index, record_offset=cycles_nr - 1, record_count=1,
        )
        if len(master_max):
            t_max.append(master_max[0])

if t_min:
    t_min = np.amin(t_min)
    t_max = np.amax(t_max)
```
...although it would probably be easier to just call `master_using_raster` and grab the first and last values, but when I try something like `mrT = master_using_raster(mdf, 0.1, endpoint=False)` I get `NameError: name 'master_using_raster' is not defined.`  Is there any tricks to using `master_using_raster`?

Thx!

**Comment by danielhrisca** [comment]
``from asammdf.blocks.utils import master_using_raster``

**Comment by coppolajj** [comment]
This works perfect! Thanks you!
