### ISSUE TITLE
Error when click on plot window

### ISSUE THREAD

**Issue by mdiego1595** [danielhrisca/asammdf#332]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

Hi,
using python 64bit, when I click on the plot window with both right and left mouse buttons, this error occurs:

Error: <class 'AttributeError'>	 
'Cursor' object has no attribute 'addMarker'

Details: 2020-03-22, 12:11:59
--------------------------------------------------------------------------------
<class 'AttributeError'>	 
'Cursor' object has no attribute 'addMarker'
--------------------------------------------------------------------------------
  File "c:\users\dmauri\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\plot.py", line 1729, in _clicked
    self.cursor1 = Cursor(pos=pos, angle=90, movable=True)
  File "c:\users\dmauri\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\cursor.py", line 13, in __init__
    self.addMarker("^", 0)

 Thank you

**Comment by danielhrisca** [comment]
I think you should update the pyqtgraph package

https://pypi.org/project/pyqtgraph/0.11.0rc0/

**Comment by mdiego1595** [comment]
Thank you Daniel, the problem was fixed.

**Comment by dglent** [comment]
> I think you should update the pyqtgraph package
> 
> https://pypi.org/project/pyqtgraph/0.11.0rc0/

* I'd like to inform that the new release of pyqtgraph has a new method to paint the ticks of the y axis: setTextPen(). 
The axis.setPen() doesn't paint the tick labels any more:
https://github.com/pyqtgraph/pyqtgraph/commit/c95ab570b11cd749bc54d6ae5fa3991d91f6c252#diff-e662f41d6136de719cdbe71c25d7f0e6

**Comment by danielhrisca** [comment]
Thank you for the heads-up Dimitrios!
