### ISSUE TITLE
"Exception: Signal plotting requires pyqtgraph or matplotlib" in Jupyter Notebooks

### ISSUE THREAD

**Issue by dapperfu** [danielhrisca/asammdf#333]
# Python version

```python
'python=3.8.0 (default, Oct 28 2019, 16:14:01) \n[GCC 9.2.1 20191008]'
'os=Linux-5.3.0-42-generic-x86_64-with-glibc2.29'
'numpy=1.18.2'
'asammdf=5.19.6'
```
# Code 

  ## MDF version

  N/A

  ## Code snippet

    s_uint8.plot()
  
  ## Traceback

```python
/projects/asammdf/asammdf/signal.py in plot(self, validate)
    167             from .gui.plot import plot
    168 
--> 169             plot(self, validate=True)
    170             return
    171 

/projects/asammdf/asammdf/gui/plot.py in plot(signals, title, validate)
     58     else:
     59         logging.warning("Signal plotting requires pyqtgraph or matplotlib")
---> 60         raise Exception("Signal plotting requires pyqtgraph or matplotlib")
```

# Description

Following the 'Working with Signal' example in Jupyter Notebooks this error comes up.

https://github.com/SimulinkDevOps/Jupyter_MDF_Analysis/blob/development/quarantine/export_test/81_-_Working_with_Signal.ipynb

https://github.com/SimulinkDevOps/Jupyter_MDF_Analysis/blob/development/quarantine/export_test/pdf/81_-_Working_with_Signal.pdf

**Comment by dapperfu** [comment]
Current workaround is to comment out the raise in the exception in Signal:

https://github.com/danielhrisca/asammdf/blob/master/asammdf/signal.py#L173

**Comment by danielhrisca** [comment]
That raise is a left over from a debugging session. I will remove it

**Comment by danielhrisca** [comment]
Issue fixed in the development branch
