### ISSUE TITLE
Feature request: Add Conversion Referenced Block to GUI stastics window

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#335]
Hello,
in my opinion, displaying signal conversion information in the statistic window could improve analysis of signals. When using a huge amount of signals in a large measurement file (lots of measured signals), it's necessary to navigate to the signals under channels an double click it (a great feature) which needs lots of time. 
What do you think about this feature @danielhrisca . 

Thanks

**Comment by danielhrisca** [comment]
Are you talking about adding conversion info here?
![image](https://user-images.githubusercontent.com/20952040/77426076-71574980-6ddc-11ea-851e-d146b20b7c24.png)

**Comment by stlweb** [comment]
That was my idea, otherwise a new window with all signals of a plot yould be a possibility

**Comment by danielhrisca** [comment]
I'm trying to understand why you would need it. Is it to see the raw values?

**Comment by stlweb** [comment]
I'd like to have the informations for value 2 text conversion (as seen under Conversion --> Referenced blocks) without double click on signals in the channels frame for one or all plottet signals. 
![grafik](https://user-images.githubusercontent.com/46781881/77432026-d0698e00-6ddd-11ea-930c-84d290a5bdd6.png)

**Comment by stlweb** [comment]
This would make the work easier when handling files with a huge amount of signals

**Comment by danielhrisca** [comment]
I think the problem right now is that there is no way to switch between raw and physical values in the plot. Maybe this would be a better approach than adding the conversion information

**Comment by stlweb** [comment]
That was the reason of my idea, cause either i plot with signal conversion , but the plot is a straigth line or without conversion signal changes are plotted but only raw values are visible. I'm still using the workaorund to switch conversion and add an numeric window, but with adding new signals or multiple plots this is not a pretty solution.

**Comment by danielhrisca** [comment]
@stlweb 
please try out the development branch code.

You will notice new shortcuts in the menu 

![image](https://user-images.githubusercontent.com/20952040/77537104-328dc600-6ea6-11ea-82bb-c01cc08559cb.png)

**Comment by stlweb** [comment]
after updating to teh dev-branch i got following error after start plotting:

2020-03-25, 14:17:34
--------------------------------------------------------------------------------
<class 'TypeError'>	 
__init__() got an unexpected keyword argument 'textPen'
--------------------------------------------------------------------------------
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\file.py", line 2145, in _create_window
    self.add_window((ret, signals))
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\file.py", line 1638, in add_window
    plot.add_new_channels(signals)
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\plot.py", line 1212, in add_new_channels
    channels = self.plot.add_new_channels(channels)
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\plot.py", line 2096, in add_new_channels
    axis = FormatedAxis("right", pen=color, textPen=color)
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\formated_axis.py", line 10, in __init__
    super().__init__(*args, **kwargs)

**Comment by danielhrisca** [comment]
You need to update pyqtgraph https://pypi.org/project/pyqtgraph/0.11.0rc0/

**Comment by stlweb** [comment]
After updating pyqtgraph I got a new error (tested with diferent files and signals):

<class 'TypeError'>: __init__() got an unexpected keyword argument 'textPen'
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\file.py", line 2635, in keyPressEvent
    self.search()
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\file.py", line 862, in search
    self.add_window(["Plot", sorted(names)])
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\file.py", line 1645, in add_window
    plot.add_new_channels(signals)
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\plot.py", line 1216, in add_new_channels
    channels = self.plot.add_new_channels(channels)
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\plot.py", line 2096, in add_new_channels
    axis = FormatedAxis("right", pen=color, textPen=color)
  File "d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\asammdf\gui\widgets\formated_axis.py", line 10, in __init__
    super().__init__(*args, **kwargs)

<class 'TypeError'>: __init__() got an unexpected keyword argument 'textPen'

**Comment by dglent** [comment]
Are you sure that you have installed the 0.11.0rc0 version ?

```python
>>> import pyqtgraph
>>> pyqtgraph.__version__
'0.11.0rc0'
>>>

**Comment by stlweb** [comment]
An reinstallation of pyqtgraph solved the problem. 

Thats what i need!!!

Could you also format the numeric values in physical mode to decimal (actually float format is shown) 

![grafik](https://user-images.githubusercontent.com/46781881/77642218-99ba8180-6f5d-11ea-8fd0-0526b162b4bb.png)

Much Thanks

**Comment by danielhrisca** [comment]
@stlweb I think the new code will be what you expected. You can also use the Ctrl+H and Ctrl+B to change the integer format

**Comment by danielhrisca** [comment]
re-open if necessary

**Comment by stlweb** [comment]
Hello @danielhrisca,
the new feature is great, but I recognized, that the mode scaled samples doesn't work for loaded configurations :(

**Comment by danielhrisca** [comment]
> the new feature is great, but I recognized, that the mode scaled samples doesn't work for loaded configurations :(

Does this mean that you want to store the signal scaled/raw mode set by the user when a configuration is saved?

**Comment by danielhrisca** [comment]
@stlweb please try the new development code
