### ISSUE TITLE
Issue with the marker feature on GUI tool

### ISSUE THREAD

**Issue by rohithrpai** [danielhrisca/asammdf#338]
# Python version 
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  'asammdf=5.19.8'
  'numpy=1.17.2'
  'os=Darwin-18.7.0-x86_64-i386-64bit'
 ('python=3.7.4 (default, Aug 13 2019, 15:17:50) \n'
'[Clang 4.0.1 (tags/RELEASE_401/final)]')

  
  ## Traceback
  Error: <class 'AttributeError'>	 
'Cursor' object has no attribute 'addMarker'

Details: 2020-03-25, 17:10:01
--------------------------------------------------------------------------------
<class 'AttributeError'>	 
'Cursor' object has no attribute 'addMarker'
--------------------------------------------------------------------------------
  File "/anaconda3/lib/python3.7/site-packages/asammdf/gui/widgets/plot.py", line 1729, in _clicked
    self.cursor1 = Cursor(pos=pos, angle=90, movable=True)
  File "/anaconda3/lib/python3.7/site-packages/asammdf/gui/widgets/cursor.py", line 13, in __init__
    self.addMarker("^", 0)

  
# Description
I can't really share the mdf file. (proprietary data)

The marker option is not working on the GUI tool

**Comment by danielhrisca** [comment]
Do you have pyqtgraph 0.11.0rc0?

**Comment by danielhrisca** [comment]
@rohithrpai see #332
