### ISSUE TITLE
GUI:Comparsion mode is simple without Multiple windows 

### ISSUE THREAD

**Issue by pyyoungman** [danielhrisca/asammdf#339]
hello，now I think comparision mode is simple，we can‘t add new Plot or Numeric window.What are your ideas about this feature ?

**Comment by pyyoungman** [comment]
![Uploading 图片.png…]()

**Comment by pyyoungman** [comment]
![图片](https://user-images.githubusercontent.com/58065281/77618567-89140680-6f71-11ea-957c-80a81f6a64fb.png)

**Comment by pyyoungman** [comment]
![test](https://user-images.githubusercontent.com/58065281/77618888-0a6b9900-6f72-11ea-8fb9-d0dbb1570659.PNG)

**Comment by danielhrisca** [comment]
My first impression is that this would complicated thing a lot. I can't make any promise of this being implemented.

**Comment by pyyoungman** [comment]
Ok,I have ever tried to change your code to get multiwindow in comparison mode .it is not difficult to realize basic functions,however，there are some questions about cusor and some bugs from  different time length of multi files.i find it is a big challenge to stack  axes in one Plot in pyatgraph. stacking axes is better than stacking lines.because when we   use this feature "stacking",we don't see all y axis of different signal. "subplot" feature in matplotlib is a good benchmark. If you have   spare time later,you can have a try. i believe there will be a good feature.

**Comment by danielhrisca** [comment]
![image](https://user-images.githubusercontent.com/20952040/78567079-d1141280-7828-11ea-8e4b-444631cf41c3.png)
You can use this at the moment

**Comment by danielhrisca** [comment]
> i find it is a big challenge to stack axes in one Plot in pyatgraph

I understand now what you mean, and it really is not easy to do.

**Comment by danielhrisca** [comment]
@pyyoungman I've added the possibility to use multiple windows in the comparison mode. Have a try with the development branch code

**Comment by pyyoungman** [comment]
@danielhrisca hello,I have a try with the new development branch code about comparison mode.the basic idea is right by using MdiAreaWidget.but I find some bugs as follows:
1.No response：the action to change layout of sub-plots in MdiAreaWidget.（in a grid,vertically.....）;
2.We can't know which file the var is from in var info window;
3.When we add a Neurmic or Tabular,we  see only one var in window;
4.It is also impossible that  mang sub-plots are added in one plot ;

**Comment by danielhrisca** [comment]
@pyyoungman  thank you for the feed-back. 
Points 1 to 3 are fixed now 

![asammdf_development](https://user-images.githubusercontent.com/20952040/79135898-bdccee00-7db8-11ea-997e-5cb3c267522c.gif)

Point 4 will not be implemented as it will complicate thing too much

**Comment by pyyoungman** [comment]
@danielhrisca 
Hello,I have tested the devploment branch code.now I find a bug about Numeric window.
Because of different time length, when I move the cursor,there are some erro messages:
Error: <class 'IndexError'>	 
index 260 is out of bounds for axis 0 with size 260

Details: 2020-04-14, 15:37:48
--------------------------------------------------------------------------------
<class 'IndexError'>	 
index 260 is out of bounds for axis 0 with size 260
--------------------------------------------------------------------------------
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\gui\widgets\numeric.py", line 106, in _timestamp_changed
    self._update_values(stamp)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\asammdf\gui\widgets\numeric.py", line 184, in _update_values
    value = sig.samples[idx]

**Comment by pyyoungman** [comment]
@danielhrisca 
1.Fisrt Pic: about sub-plot in one plot 2.Second Pic:aboutNumeric Erros
![multi-view-capture](https://user-images.githubusercontent.com/58065281/79199001-e6132600-7e66-11ea-92a9-f6626eb3d6fd.PNG)
![erro test](https://user-images.githubusercontent.com/58065281/79199021-ee6b6100-7e66-11ea-8eba-749fdde83b87.png)
![multi-view-capture](https://user-images.githubusercontent.com/58065281/79199104-0c38c600-7e67-11ea-8aa6-9593026311db.PNG)

**Comment by danielhrisca** [comment]
Try the new development code for the Numeric problem fix.

Like I said the matlab style subplots will introduce too much complexity; I do not plan to implement this at the moment.

**Comment by pyyoungman** [comment]
@danielhrisca ,OK,I know there are many problems in matlab style subplots.I hope you can try it in the future.I have ever tried to realize it in 5.17.3,but I met many challenges so I give up.

**Comment by danielhrisca** [comment]
implemented in release [5.20.0](https://github.com/danielhrisca/asammdf/releases/tag/5.20.0)
