### ISSUE TITLE
Error selecting a signal from an MDF4

### ISSUE THREAD

**Issue by parkertomatoes** [danielhrisca/asammdf#34]
# Python version 
3.6.0

# Platform information
Windows 10 Enterprise

# _asammdf_ version
2.8.1

# Description
I tried to use the following code with an MDF4 file I can't share
```
from asammdf import MDF, Signal, configure
import numpy as np
configure(integer_compacting=True)
configure(split_data_blocks=True, split_threshold=10*1024)
with MDF(r"file.mdf") as mdf:
  s = mdf.get("CHANNEL_NAME")```
```

This returned the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\H215374\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf.py", line 832, in select
    signal = self.get(group=group, index=index, data=data)
  File "C:\Users\H215374\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf4.py", line 3574, in get
    pos_byte, pos_offset = divmod(ch_invalidation_pos)
TypeError: divmod expected 2 arguments, got 1
```

Error seems pretty straightforward - couldn't find a version of Python whose docs allow one argument for divmod(). So, I wonder if this line is covered by unit tests.

Thanks, and thank you for your hard work on this library!

**Comment by danielhrisca** [comment]
Hello,

Please use the development branch code. This issue has been fixed there already.

**Comment by danielhrisca** [comment]
Actually you are now the second person this week to have a file with this feature, while I have never seen one in years of dealing with measurements data. 

What is the program that generated this file?

**Comment by parkertomatoes** [comment]
Wow, that was a crazy fast response. Thanks!

I received the file from a customer, so i couldn't say what tool generated it.

**Comment by danielhrisca** [comment]
You can see he program information with this
``mdf.identification['program_identification']``

**Comment by parkertomatoes** [comment]
I take that back, code returns 'Concerto', which appears to be an AVL product

**Comment by danielhrisca** [comment]
Thank you!
