### ISSUE TITLE
Quick comment regarding black and isort formatting

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#349]
Hi Daniel,

I saw you started using black and isort for formatting in the development branch and I'd like to make a quick comment on that.
I myself use black and isort for all my projects and I'd like to recommend to **first run isort** to sort imports in categories and **then black** for overall formatting. Reason being that isort and black creates different formatting for imports and I think that it is best to stick to only the one from black.
I know that the formatting of imports with black is less compact and aesthetically pleasant but there are reasons behind it that you can find by reading comments on the black GitHub page: one is that it reduces the possibility of merge conflicts.
Besides, based on my personal experience, it is also less confusing for users. People often run black from their code editor command panel, but don't necessarily run isort, which then breaks the previous imports formatting of isort.

**Comment by JulienGrv** [comment]
One more thing: you can tweak isort settings to produce same formatting as black does.

**Comment by danielhrisca** [comment]
Thank you Julien! I've swapped the order and will run isort before black
