### ISSUE TITLE
UnboundLocalError: local variable 'record' referenced before assignment

### ISSUE THREAD

**Issue by parkertomatoes** [danielhrisca/asammdf#35]
# Python version 
3.6.0

# Platform information
Windows 10 Enterprise

# _asammdf_ version
3.0.0.dev0

# Description
Loading an MDF4 file with the following code:
```
from asammdf import MDF, Signal, configure
import numpy as np
with MDF(r"filename.mf4") as mdf:
  s = mdf.get("CHANNEL_NAME")
```

I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\H215374\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf_v4.py", line 3801, in get
    inval_bytes = record['invalidation_bytes']
UnboundLocalError: local variable 'record' referenced before assignment
```

**Comment by danielhrisca** [comment]
I can't try it myself since I'm on my mobile, but you could try something similar to line 3309 to prepare the record. My guess is your channel is not properly byte aligned and the branch at line 3369 was executed bypassing the record preparation part.

**Comment by parkertomatoes** [comment]
It doesn't appear to call into _get_not_byte_aligned_data(). The broken channel is type CHANNEL_TYPE_VIRTUAL, which makes it skip over 3309, if that helps.

**Comment by danielhrisca** [comment]
Thank you for investigating this. I will have a fix ready in a couple of hours.

**Comment by danielhrisca** [comment]
Hello,

can you give this commit a try: https://github.com/danielhrisca/asammdf/commit/7c36b1cec22bdbe6085b1d37dc90e33e88dcfaeb?

**Comment by parkertomatoes** [comment]
That appears to fix it for me. Selecting the signal doesn't error and I can read a few timestamps now.

Thanks!
