### ISSUE TITLE
Cannot close (and delete) MDF file

### ISSUE THREAD

**Issue by ltomb** [danielhrisca/asammdf#350]
# Python version
('python=3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.17.4'
'asammdf=5.19.16'

  ## MDF version
3.3 and 4.10 for sure

  ## Code snippet
 import asammdf
 a=asammdf.MDF("C:/Users/ltombari/Dati/temp/ME173-14749_MinInstTorque_ID_9.dat");
 a.close;

 # Description
My problem is that after I have opened an MDF file, even if i call the .close method, I cannot delete the file from the disk because it says that "the file is open in Python". I only manage to do that if I close the python editor and the script. 
Am I missing something??

**Comment by danielhrisca** [comment]
hello @ltomb 

you are not actually calling the close method

```python
import asammdf
a = asammdf.MDF("C:/Users/ltombari/Dati/temp/ME173-14749_MinInstTorque_ID_9.dat")
a.close() # call it
```

**Comment by ltomb** [comment]
thank you so much @danielhrisca
