### ISSUE TITLE
Question: to_dataframe display name vs. standard channel name

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#351]
# Python version
Python 3.6.4
numpy=1.17.1
asammdf=5.19.16

Hello Daniel
I'm using the methode _to_dataframe_ for quite a long time without thinking to much about it. Now I had an issue by exporting selected channels to a pandas DataFrame, where I realized that I don't understand the settings for display name correct. Therfore the following questions.

- Does effect the parameter `use_display_names=True` the format of the channels from the channels list? I would expect to provide the display name if it is True and otherwise the standard channel name (channel\\device). I always just provide the display name and the channels will be exported despite the setting of the parameter use_display_names.
- I now came along with a *.dat file where the exported column name of the pandas DataFrame is the standard channel name (channel\\device). Is it possible that the display name is equal to the standard channel name or is the *.dat file a older format where display names are not supported?
- What will be the best practices to know which format the column names within the DataFrame will have?

- On a few other mf4 files I got the problem. That the function to_dataframe returns an empty DataFrame. So no columns are created within the DataFrame. By reading the files using your GUI and also MDA V7.2.11 I recon that the selected channels exist but are empty. How can something like this be happen? Is it possible to create a warning within to_dataframe for issues like this?

BR
Lama

**Comment by danielhrisca** [comment]
```python 

mdf = MDF(file_name, remove_source_from_channel_names=True, use_display_names=True)
df = mdf.to_dataframe(empty_channels="zeros") # default is "skip"
```

**Comment by Lama09** [comment]
Hello Daniel,
many thanks for your answer. I wasn't aware of the parameter 'remove_source_from_channel_names'  and used the 'use_display_names' only within to_dataframe(). What does 'remove_source_from_channel_names'  do? I could not found a explanation within your API documentation. What is the best practise to use the parameter "use_display_names" within MDF() or to_dataframe()? Your write that deactivating this parameter " can decrease the loading times very much" If I use the parameter "use_display_name" within MDF() and to_dataframe() the outptut is again the long format of the channel name

Can I rely on the default that empty_channels will be skiped within the to_dataframe()?

With your recommanded parameter setting,s the issue regarding the channel name is solved.

**Comment by danielhrisca** [comment]
_remove_source_from_channel_names_ splits the channel name on ``\`` see [here](https://github.com/danielhrisca/asammdf/blob/bc03c1a32b7d91bb1b75c38e88c44bf2c633ab71/asammdf/blocks/mdf_v4.py#L769) and keeps the first part.

_use_display_names_ will trigger the parsing of the CNBLOCK XML comment to search for the _display name_ tag. This operation is expensive and this is why is it skipped by default. See [here](https://github.com/danielhrisca/asammdf/blob/bc03c1a32b7d91bb1b75c38e88c44bf2c633ab71/asammdf/blocks/v4_blocks.py#L579). It is usefull for example if you use Etas devices were the channel names are set to some generic name ``TH01, ... TH08`` and the actual useful name is stored as displya name ``CapacitorTemp, .. CoilTemp``

As you see the two arguments are completely unrelated.

> Can I rely on the default that empty_channels will be skiped within the to_dataframe()?

Yes.
