### ISSUE TITLE
GUI: Quick search for channels missing

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#352]
Python 3.6.4
numpy=1.17.1
asammdf=5.19.16

Hello Daniel,
I installed the latest asammdf Version and realized, that the quick search is missing or not activated. Do I need to activate the quick search within the settings? I know about the Advanced search option, but do like the quick search very much.

BR
Lama

**Comment by Lama09** [comment]
The following error mesage I got, if I do work with plot window.

2020-04-18, 00:44:50
--------------------------------------------------------------------------------
<class 'AttributeError'>	 
'Cursor' object has no attribute 'addMarker'
--------------------------------------------------------------------------------
  File "c:\users\..\lib\site-packages\asammdf\gui\widgets\plot.py", line 1729, in _clicked
    self.cursor1 = Cursor(pos=pos, angle=90, movable=True)
  File "c:\users\..\lib\site-packages\asammdf\gui\widgets\cursor.py", line 13, in __init__
    self.addMarker("^", 0)

**Comment by danielhrisca** [comment]
> I installed the latest asammdf Version and realized, that the quick search is missing or not activated. Do I need to activate the quick search within the settings? I know about the Advanced search option, but do like the quick search very much.

I've removed the quick search because it was not fitting so nicely when there were long names



> File "c:\users..\lib\site-packages\asammdf\gui\widgets\plot.py", line 1729, in _clicked
> self.cursor1 = Cursor(pos=pos, angle=90, movable=True)
> File "c:\users..\lib\site-packages\asammdf\gui\widgets\cursor.py", line 13, in **init**
> self.addMarker("^", 0)

For this you need to install pyqtgraph 0.11.0.rc0 https://pypi.org/project/pyqtgraph/0.11.0rc0/

**Comment by Lama09** [comment]
Hello Daniel,
many thanks for your answers. Ok, than I have to go with the detailed search.

I think within setup.py the version of pyqtgraph needs to be adapted. I personally afraid of using development versions, due to some side effects, but I did install pyqtgraph 0.11.0.rc0. Unfortunately a nother error ocours.

<class 'TypeError'>	 
ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
--------------------------------------------------------------------------------
  File "c:\...\lib\site-packages\asammdf\gui\widgets\file.py", line 1632, in add_window
    plot.add_new_channels(signals)
  File "c:\...\lib\site-packages\asammdf\gui\widgets\plot.py", line 579, in add_new_channels
    if len(channel.samples) and np.all(np.isnan(channel.samples)):

**Comment by danielhrisca** [comment]
@Lama09 
can you try the new development code?

**Comment by Lama09** [comment]
Hello Daniel,
I installed the version 5.20.0 today to test your fix. Producing the error above, I was accidentally open a bytes channel to the plot window. Unfortunatly I could not test within the new version because of the following issue. This also occur on time dependent channels happen.

2020-04-23, 22:03:34
--------------------------------------------------------------------------------
<class 'TypeError'>	 
__init__() got an unexpected keyword argument 'textPen'
--------------------------------------------------------------------------------
  File "c:...\lib\site-packages\asammdf\gui\widgets\file.py", line 714, in search
    self.add_window(["Plot", signals])
  File "c:...\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 424, in add_window
    plot.add_new_channels(signals)
  File "c:...\lib\site-packages\asammdf\gui\widgets\plot.py", line 1289, in add_new_channels
    channels = self.plot.add_new_channels(channels)
  File "c:...\lib\site-packages\asammdf\gui\widgets\plot.py", line 2206, in add_new_channels
    axis = FormatedAxis("right", pen=color, textPen=color)
  File "c:...\lib\site-packages\asammdf\gui\widgets\formated_axis.py", line 10, in __init__
    super().__init__(*args, **kwargs)

**Comment by danielhrisca** [comment]
Do you really have pyqtgraph 0.11.0rc0?

**Comment by Lama09** [comment]
I'm sorry you are right. I missed the pyqtgraph 0.11.0rc0 package. I know we discussed this issue already some time bevor.I still would be more convinced of the necessary packages would be bundled within the asammdf.exe, or at least you add the packages to the `install_requires[]` list of your setup.py file.

**Comment by danielhrisca** [comment]
for the GUI part you can use this command to install the dependencies

```
pip install -U asammdf[gui]
```

**Comment by Lama09** [comment]
I cam along with another issue but can't say how a produced it.

2020-05-04, 22:07:25
--------------------------------------------------------------------------------
<class 'RuntimeError'>	 
wrapped C/C++ object of type PlotDataItem has been deleted
--------------------------------------------------------------------------------
  File "c:\tools\anaconda3\lib\site-packages\pyqtgraph\GraphicsScene\GraphicsScene.py", line 174, in mouseMoveEvent
    self.sendHoverEvents(ev)
  File "c:\tools\anaconda3\lib\site-packages\pyqtgraph\GraphicsScene\GraphicsScene.py", line 243, in sendHoverEvents
    items = self.itemsNearEvent(event, hoverable=True)
  File "c:\tools\anaconda3\lib\site-packages\pyqtgraph\GraphicsScene\GraphicsScene.py", line 440, in itemsNearEvent
    if hoverable and not hasattr(item, 'hoverEvent'):
