### ISSUE TITLE
Exception handling for corrupted mf4 file

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#354]
Python=3.6.4
asammdf=5.19.16

Hello Daniel,
I encountered the following problem while reading a corrupted mf4 file. Because the exception handling fails my application could not catch MdfException correct. 

Expected "##FH" block @0xd130380 but found "b'\x00\x00\x00\x00'"
Exception ignored in: <bound method MDF.__del__ of <asammdf.mdf.MDF object at 0x00000224D1FB2860>>
Traceback (most recent call last):
  File "C:\..\Python\py36_4\lib\site-packages\asammdf\mdf.py", line 164, in __del__
    self.close()
AttributeError: 'MDF' object has no attribute 'close'

![image](https://user-images.githubusercontent.com/48772414/80149357-d312fb00-85b6-11ea-85dd-c0f858f15beb.png)

**Comment by danielhrisca** [comment]
Please try the development branch code

**Comment by Lama09** [comment]
Hallo Daniel I tried with the following configuration.
Python=3.6.4
asammdf=5.20.1

Unfortunately the exception handling still fails on this corrupted file.

asammdf - ERROR - Expected "##FH" block @0xd130380 but found "b'\x00\x00\x00\x00'"
NoneType: None

**Comment by danielhrisca** [comment]
What do you expect to happen?

**Comment by Lama09** [comment]
I like to have a more clean way to handle this issue. Currently the code is writing this error message to the console.

asammdf - ERROR - Expected "##FH" block @0xd130380 but found "b'\x00\x00\x00\x00'"
NoneType: None

This error message will be created before I can catch a MdfException within my code. I therefore was wondering what kind of type is asammdf-ERROR? I be able to catch this error by the MdfException and alslo get the error message form above on to the variable `Mdf_err.args[0]`.But the message itself is already appeared from somewhere else on the console.
