### ISSUE TITLE
Channel "..." not found, control behavior if a subset of Channels found

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#355]
Python 3.6.4
asammdf 5.19.16

I use the following code to export channels to a pandas DataFrame

`with MDF(file,remove_source_from_channel_names=True, use_display_names=True) as mdf_file:`
`df = mdf_file.to_dataframe(Label,time_from_zero=False)`

and encounter the following behavior. If the complete list of Labels not found as channels, a MdfException will raised with the following message.

Channel "Label[0]" not found

If a subset of the channels be found no MdfException will be raised. Is there any flag to change this behavior?

**Comment by danielhrisca** [comment]
The idea is to first create a valid list of channels

```python
with MDF(file, remove_source_from_channel_names=True, use_display_names=True) as mdf_file:
    names = [name for name in Label if name in mdf_file]
    df = mdf_file.to_dataframe(names, time_from_zero=False)
```

**Comment by Lama09** [comment]
Hello Daniel,
many thanks for this hint. That for sure makes much more sense.
Unfortunately the returned list names is in my case empty, despite that if I apply the Label list directly I will get all channels within the dataframe. So therfore the `If name in mdf_file` methode is not working. Does the mdf_file object provide a list of available channels and how can I access them?

**Comment by danielhrisca** [comment]
See here https://github.com/danielhrisca/asammdf/blob/development/asammdf/mdf.py#L357

**Comment by Lama09** [comment]
I'm very sorry the `if name in mdf_file` methode is working. I was using a wrong file while debugging. In my case I like to skip the mf4-file as soon there is one of the channels missing. Therefore I used the following approach.

label_set = set(Labels.tolist()) #user define channels 
mf4_Label_set = set(mdf_file.channels_db) #existing channles within mf4-file
if label_set.issubset(mf4_Label_set) is True:
    df = mdf_file.to_dataframe(Labels.tolist(),time_from_zero=False)
else:

label_cur = mf4_Label_set.intersection(label_set)
label_dif = label_set.difference(label_cur)  # get set of missing labels
message = 'The following Labels could not be found within data file: '
for val in label_dif:
     message = '%s%s%s%s' % (message, '"', val, '" ')
raise MdfException(message)
