### ISSUE TITLE
get_can_signal: "local variable '_can_id' referenced before assignment"

### ISSUE THREAD

**Issue by tobiasandorfer** [danielhrisca/asammdf#356]
Hello Daniel,

first of all thank you very much for all the work you put into this amazing projekt!
Working with mdf files in python was a gamechanger for my work!

# Python version
'python=3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.17763-SP0'
'numpy=1.16.5'
'asammdf=5.20.1'

  ## MDF version
  5.20.1

  ## Code snippet
File: mdf_v4.py Line:7990 (the picture showes my fix, commenting out the last key)
![image](https://user-images.githubusercontent.com/64536839/80599396-265bd200-8a2b-11ea-8d4b-122f8c009522.png)

  
  ## Traceback
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
    

  File "C:\ProgramData\Anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7990, in get_can_signal
    if can_id in self.bus_logging_map["CAN"][_can_id]:
**UnboundLocalError: local variable '_can_id' referenced before assignment**
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/svn/01_Python/02_Script/mdf.py", line 291, in <module>
    for result in results:
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
UnboundLocalError: local variable '_can_id' referenced before assignment
PS C:\svn\01_Python>

# Description

When I use the get_can_signal and try the CAN1.Message_Name.Signal_Name
the described error (Traceback) occurred

![image](https://user-images.githubusercontent.com/64536839/80600421-a9c9f300-8a2c-11ea-928b-6572156933f8.png)

**Comment by danielhrisca** [comment]
Hello Tobias,

thank you for pointing out the problem. I've pushed the fix to the development branch.

**Comment by tobiasandorfer** [comment]
Hello @danielhrisca ,

I found two additional problems in this funktion, i hope its ok two report in the closed issue:
1. If you try the <Message_Name>.<Signal_Name> method for the name Parameter, there is an Error (line: 8009). I commented out the line and changed what must have been a copy paste fault i think:
 
![image](https://user-images.githubusercontent.com/64536839/83415319-34808200-a41f-11ea-8bc1-9ef82096e403.png)

with the changed line it works.

2. If you try CAN_DataFrame_<Message_Id>.<Signal_Name> there is an Error in the CANMATRIX lib.
The Issue here is, that the funktion "db.frame_by_id" does not accept integer value but needs an object with "id" and "extended"

Here is my quick and dirty try to make it work, and it actualy did:

![image](https://user-images.githubusercontent.com/64536839/83416145-8675d780-a420-11ea-99be-3fca417a392d.png)

Thanks for all the Work!

Greez Tobias

**Comment by tobiasandorfer** [comment]
in addition:

when using the CAN<ID>.CAN_DataFrame_<Message_Id>.<Signal_Name> methode,
in line 7950 the ".group("id") is missing and it also needs the fix for the db.frame_by_id funktion


![image](https://user-images.githubusercontent.com/64536839/83417563-8b3b8b00-a422-11ea-993b-301c36bbc62c.png)
