### ISSUE TITLE
Memory option for fast MDF loading

### ISSUE THREAD

**Issue by ltomb** [danielhrisca/asammdf#358]
# Python version
('python=3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.17.4'
'asammdf=5.19.16'

  ## MDF version
any

  ## Code snippet
 import asammdf
 f=asammdf.MDF("C:/Users/ltomb/Dati/temp/test_10GB.MDF");

# Description
I have very large MDFs (~10 GB) from which I only need to export a few channels. I found out that in older asammdf versions there was an option (memory) for memory optimization, but I am not sure it works anymore in version 5.19.16.
So my question is: is there a way to load only the channel list, without the raw data, in order to speed up the process? Today for a 10 GB file I spend 3000 s only to create the MDF object.

**Comment by danielhrisca** [comment]
Hello @ltomb 

this took 3000s ?

```python
mdf = MDF(file_name)
```

**Comment by danielhrisca** [comment]
Since 5.0.0 the file is opened in a mode similar to _memory=low_ in the 4.x.y releases. This means the raw data is not read.

**Comment by ltomb** [comment]
> 
> 
> Hello @ltomb
> 
> this took 3000s ?
> 
> ```python
> mdf = MDF(file_name)
> ```

Yes. Consider I am calling the library from matlab. Can this have any impact?

**Comment by danielhrisca** [comment]
It should not take some much.

Can you use MDFValidator to check the file? Is it unsorted? Do you have CAN bus logging in that file?

**Comment by ltomb** [comment]
> 
> 
> It should not take some much.
> 
> Can you use MDFValidator to check the file? Is it unsorted? Do you have CAN bus logging in that file?

I will try to use MDF validator on those files and let you know.
Meanwhile, if you want to have a look, i have made some statistics on the files I am importing (about 600 files). Attached you can find a graph file dimension vs reading time (reading time = time to run _mdf = MDF(file_name)_).
As you can see there are two different trends in the reading time.

![MDF_reading_time](https://user-images.githubusercontent.com/43569791/80690415-11387f00-8acf-11ea-80db-65779ad34ba3.PNG)

**Comment by danielhrisca** [comment]
Local or remote files? 

Can you share one of the files? It could really help the analysis

**Comment by ltomb** [comment]
They are all local files. Unfortunately I cannot share them.

**Comment by danielhrisca** [comment]
In MDFValidator it is easy to see if a file is unsorted by checking if the record ID size is not 0 (it can also have multiple channel groups like bellow)
![image](https://user-images.githubusercontent.com/20952040/80692272-059e8580-8ada-11ea-9a1a-d59f99ee15d2.png)

If this is the case then the file need to be sorted first, which can take some time. To accelerate this I've written a C-extension module; please check if you have the ``.pyd`` file in your asammdf installation folder

![image](https://user-images.githubusercontent.com/20952040/80692745-b60c8980-8ada-11ea-8215-5ea3bddbc950.png)

**Comment by danielhrisca** [comment]
> unfortunately I cannot share them.

Just to make sure, are you aware that you can scramble the file to anonymize  the textual contents? This will mangle all texts like comments, channel names, text blocks.

**Comment by ltomb** [comment]
hi @danielhrisca 
after some more testing it looks like the issue is on the computer i was using: retrying to import the same MDF on another computer took a decent amount of time.
