### ISSUE TITLE
how to generate str signals to mdf

### ISSUE THREAD

**Issue by Luffy-Hll** [danielhrisca/asammdf#359]
'python=3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.16.4'
'asammdf=5.20.0'
# Code 
from asammdf import MDF, Signal
import numpy as np

s1 = np.array(['a', 'b', 'c', 'd', 'e'])
s2 = np.array([-1, -2, -3, -4, -5])
s3 = np.array([0.1, 0.04, 0.09, 0.16, 0.25])
t = np.array([0.001, 0.002, 0.003, 0.004, 0.005])
names = ['Positive', 'Negative', 'Float']
units = ['+', '-', '.f']
info = {}
s1 = Signal(samples=s1, timestamps=t, unit='+', name='Positive')
s2 = Signal(samples=s2, timestamps=t, unit='-', name='Negative')
s3 = Signal(samples=s3, timestamps=t, unit='flts', name='Floats')

mdf = MDF()
mdf.append([s1, s2, s3])
mdf.save('demo_str.mf4',overwrite=True)

  ## Traceback
Traceback (most recent call last):

  File "<ipython-input-19-811e03d62203>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/tool/tool/test str.py', wdir='C:/Users/Administrator/Desktop/tool/tool')

  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/tool/tool/test str.py", line 19, in <module>
    mdf.append([s1, s2, s3])

  File "D:\ProgramData\Anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2717, in append
    s_type, s_size = fmt_to_datatype_v4(sig_dtype, sig_shape)

  File "D:\ProgramData\Anaconda3\lib\site-packages\asammdf\blocks\utils.py", line 565, in fmt_to_datatype_v4
    raise MdfException(message)

MdfException: Unknown type: dtype=<U1, shape=(5,)
  
# Description
Thanks for asammdf, it's really powerful.

I want to transfer csv data to mdf format, but always warning 'Unknown type: dtype=object'. If I filter out all string signals, it works.
And I do a test as above, write as the demo instruction just change s1 to string. The warning is shown as above. 
My question: if transfer signals to mdf format, does it support string signals or how to do it?

Thanks in Advance!

**Comment by danielhrisca** [comment]
Hello @Luffy-Hll 

this is how you can add string channels

```python
from asammdf import MDF, Signal
import numpy as np

mdf = MDF()

cycles = 20
t = np.arange(cycles)
sigs = []
for i in range(10):
    sig = [
        "Channel {} sample {}".format(i, j).encode("utf-8") for j in range(cycles)
    ]
    sig = Signal(
        np.array(sig),
        t,
        name="Channel_{}".format(i),
        unit="unit_{}".format(i),
        comment="String channel {}".format(i),
        raw=True,
        encoding='utf-8',
    )
    sigs.append(sig)
mdf.append(sigs, common_timebase=True)

mdf.save(r'strings.mf4')
```

**Comment by danielhrisca** [comment]
And on your exact example

```python
from asammdf import MDF, Signal
import numpy as np

s1 = np.array([b'a', b'b', b'c', b'd', b'e'])
# or
s1 = np.array(
   [string.encode('utf-8') for string in ['a', 'b', 'c', 'd', 'e']]
)
s2 = np.array([-1, -2, -3, -4, -5])
s3 = np.array([0.1, 0.04, 0.09, 0.16, 0.25])
t = np.array([0.001, 0.002, 0.003, 0.004, 0.005])
names = ['Positive', 'Negative', 'Float']
units = ['+', '-', '.f']
info = {}
# you need to also set the encoding for the string channels
s1 = Signal(samples=s1, timestamps=t, unit='+', name='Positive', encoding='utf-8')
s2 = Signal(samples=s2, timestamps=t, unit='-', name='Negative')
s3 = Signal(samples=s3, timestamps=t, unit='flts', name='Floats')

mdf = MDF()
mdf.append([s1, s2, s3])
mdf.save('demo_str.mf4',overwrite=True)
```

**Comment by Luffy-Hll** [comment]
Thanks for your quick reply.
 I tried, no error report but I didn't find all the string signals when I use MDA(v7.2.3) to open mdf file.  strange...

**Comment by Luffy-Hll** [comment]
When I open the transfered mdf file with MDA(8.3.3), I can find the string signals. 
Maybe MDA(v7) not support string signals like we created. 
Thanks very much.
