### ISSUE TITLE
MDF4's save() doesn't handle spaces correctly

### ISSUE THREAD

**Issue by parkertomatoes** [danielhrisca/asammdf#36]
# Python version 
3.6.0

# Platform information
Windows 10 Enterprise

# _asammdf_ version
3.0.0dev

# Description
All text after a space is stripped from the destination passed to save() in the MDF4 class. 

Specifically, I have a series of MDF files from a customer that following a naming pattern like "MYFILE [1].mf4", "MYFILE [2].mf4". I am reading them (works fine), updating them (works fine), and saving them. The actual save operation completes successfully, but they are all saved as "MYFILE.mf4", and the file gets overwritten each subsequent save.

EDIT: This only appears to happen if the extension is excluded (.e.g. mdf.save("MYFILE [1]")). If dst includes ".mf4" the spaces are handled correctly.

**Comment by danielhrisca** [comment]
Hello,

are you using the latest development code or are you still on the commit https://github.com/danielhrisca/asammdf/commit/7c36b1cec22bdbe6085b1d37dc90e33e88dcfaeb?
I would suggest to use thata commit for now as there are many changes with the latest code.

Could you please post the code snippet that you use for the file saving step?

**Comment by parkertomatoes** [comment]
I installed 3.0.0.dev0 via pip on 1/26 and manually patched commit 7c36b1c.

The issue appears to be a little narrower than I originally described. The file name needs to include a period and an extension-like suffix before the space. Below is the smallest amount of code I could reproduce the issue with:

```
from asammdf import MDF

with MDF("input.mf4") as mdf:
  mdf.save("output.123 [2]")
```

saves "output.mf4" instead of "output.123 [2].mf4"

**Comment by danielhrisca** [comment]
The issue came from the use of ``os.path.splitext`` in the file name processing.

I've created a new branch, based on https://github.com/danielhrisca/asammdf/commit/7c36b1cec22bdbe6085b1d37dc90e33e88dcfaeb,  that has this fixed:

https://github.com/danielhrisca/asammdf/tree/pre_generator

**Comment by parkertomatoes** [comment]
Thanks for the speedy fix! I pulled and installed the pre_generator branch, but it fails with the following:
```
Traceback (most recent call last):
  File "issue36.py", line 1, in <module>
    from asammdf import MDF
  File "C:\Users\H215374\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\__init__.py", line 4, in <module>
    from .mdf_v2 import MDF2
  File "C:\Users\H215374\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf_v2.py", line 6, in <module>
    from .mdf_v3 import MDF3
  File "C:\Users\H215374\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\mdf_v3.py", line 2875
    if not dst.endswith(('mdf', 'MDF'))
                                      ^
SyntaxError: invalid syntax
```

development branch fails the same way. Feel free to close this issue though if the code I provided no longer reproduces.

**Comment by danielhrisca** [comment]
Yes I know there were some silly typos; sorry for this.

Please download the code again. It is fixed now

**Comment by parkertomatoes** [comment]
Works just fine now. Thanks for your hard work!
