### ISSUE TITLE
Time as date in plot

### ISSUE THREAD

**Issue by GordonBloe** [danielhrisca/asammdf#360]
Hello all!

(I'm new to Github and Python, so I can't fill the recommended formular. I think it is not that important for my queation:)

Is there a way to change the time on the x-axis of the Plot, from seconds to "Time as date"?

So far, thanks for the program :)

**Comment by danielhrisca** [comment]
Hello @GordonBloe 
I'll have a look at this. At the moment you can only see the seconds.

**Comment by danielhrisca** [comment]
@GordonBloe please try the new development branch code

![xaxis](https://user-images.githubusercontent.com/20952040/81099756-13a63900-8f14-11ea-97ec-1998c324edf9.gif)

**Comment by GordonBloe** [comment]
Wow that was pretty fast! Now I only have to figure out how to implement the code :D
(I used the .exe before)
