### ISSUE TITLE
Question - Listing channel names the correct way

### ISSUE THREAD

**Issue by RobertMouncer** [danielhrisca/asammdf#361]
Hello!
Not an issue, but a question.
Is it possible to create a list with the channel names without using __getattribute__? I read through the documentation and couldn't find any attributes that would return a list of channel names.
Here's what I have implemented at the moment
```
list = []
for key in mdf.__getattribute__('channels_db'):
    list.append(key)
```
Or

```
list = [*mdf.__getattribute__('channels_db')]

```

An additional question:
When using `to_dataframe()` is it possible to prevent time being renamed to timestamp?

**Comment by danielhrisca** [comment]
Hello Robert,

This is easier

```python
names = list(mdf.channels_db)
```

**Comment by RobertMouncer** [comment]
Thank you @danielhrisca.

Could you also answer my additional question or would you like me to post a more detailed explaination?

**Comment by danielhrisca** [comment]
I think it is easy to rename the time (data frame index) to what you need

```python
df = mdf.to_dataframe()
df.index.rename('time', inplace=True)
```
