### ISSUE TITLE
Missing data after .to_dataframe() call, interference in plotting signals with matplotlib.pyplot and mdf4

### ISSUE THREAD

**Issue by RobinSaam** [danielhrisca/asammdf#362]
# Python version 3.8
```python
from asammdf import MDF
import matplotlib.pyplot as plt

data = MDF(filename)
pandas = data.to_dataframe()

#plot1
plt.plot(pandas["ESP_v_Signal"].index, pandas["ESP_v_Signal"].values)
plt.show()

pandas = data.get_group(1)

#plot2
plt.plot(pandas["ESP_v_Signal"].index, pandas["ESP_v_Signal"].values)
plt.show()

#plot3
plt.plot(pandas["ESP_v_Signal"].values)
plt.show()

#plot4
plt.plot(data.get("ESP_v_Signal").timestamps, data.get("ESP_v_Signal").samples)
plt.show()

#plot5
plt.plot(data.get("ESP_v_Signal").samples)
plt.show()


```
# Code 

  ## MDF version
  MDF4 File: 4.10 
  MDF3 File: 3.30
  
# Description

Hello guys! My problem is that I want to extract the data out of a mdf file. After that I convert them to a pandas dataframe object with .to_dataframe()-function.
	
My mdf file consist of two groups with a sample rate of 100Hz and 1000Hz. If I chose a *.mdf4 file all of the date after around 100s will be the same as the previous. Example: speed at 80s: 0 km/h, all the values after that point in time will be 0 km/h as well even do the measurement goes on for 30 minutes or so (see Photos/MDF4 File/plot1). The correct output would be Photos/MDF4 File/plot3 or plot5. With Vector Canape I get the same results as plot3 and plot5. If I then extract the samples with data.get(signal)
the values will not be 10 km/h and represent the actual value at that time. 

Also I get that weird interference at plot 2 and 4. 

If I do the same with a *.mdf3 file, I will not get that “error” at all with the same approach.

# Photos
# MDF4 File
Plot3 and Plot5 should be the output for the rest as well.
# plot1 complete view
![plot1_complete](https://user-images.githubusercontent.com/64897406/81164648-f8c5da00-8f90-11ea-9e27-c408df5cf1ef.png)
# plot1 zoomed view
![plot1_zoom](https://user-images.githubusercontent.com/64897406/81164651-f95e7080-8f90-11ea-9720-06897c11ece0.png)
# plot2 complete view
![plot2](https://user-images.githubusercontent.com/64897406/81164653-f9f70700-8f90-11ea-86b1-c1aeea852666.png)
# plot3 complete view
![plot3](https://user-images.githubusercontent.com/64897406/81164655-fb283400-8f90-11ea-9aa9-12ffe7865a3f.png)
# plot4 complete view
![plot4](https://user-images.githubusercontent.com/64897406/81164642-f794ad00-8f90-11ea-8813-11c90ecdda80.png)
# plot5 complete view
![plot5](https://user-images.githubusercontent.com/64897406/81164647-f82d4380-8f90-11ea-8efc-4f91546a3bcd.png)

# MDF3 File
# plot1 complete view
![mdf3_plot1_complete](https://user-images.githubusercontent.com/64897406/81165547-6d4d4880-8f92-11ea-99b4-f2fa5db46335.png)
# plot2 complete view
![mdf3_plot2](https://user-images.githubusercontent.com/64897406/81165535-6b838500-8f92-11ea-9712-533d4e715868.png)
# plot3 complete view
![mdf3_plot3](https://user-images.githubusercontent.com/64897406/81165539-6c1c1b80-8f92-11ea-8a34-087733952152.png)
# plot4 complete view
![mdf3_plot4](https://user-images.githubusercontent.com/64897406/81165542-6cb4b200-8f92-11ea-91b5-4c8509047dc1.png)
# plot5 complete view
![mdf3_plot5](https://user-images.githubusercontent.com/64897406/81165544-6cb4b200-8f92-11ea-8905-19ce9d44f10e.png)

**Comment by danielhrisca** [comment]
can you run this first
```python
mdf = MDF(filename)
for i, gp in enumerate(mdf.groups):
    print(i, mdf.get_master(i))
```

**Comment by RobinSaam** [comment]
0 [-1.41525000e-01 -1.31525000e-01 -1.21525000e-01 ...  4.02530848e+03
  4.02531848e+03  4.02532848e+03]
1 [0.00000e+00 1.00000e-02 2.00000e-02 ... 4.02545e+03 4.02546e+03
 4.02547e+03]

This is the output for the mdf4 file, each containing nearly 400.000 values.

**Comment by danielhrisca** [comment]
what is you asammdf version?

```python
import asammdf
print(asammdf.__version__)
```

**Comment by RobinSaam** [comment]
5.19.1

**Comment by danielhrisca** [comment]
I'm afraid I'm unable to reproduce the error with my synthetic file. 

Can you scramble and send the file for analysis? See https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.scramble

**Comment by RobinSaam** [comment]
I send you an e-mail with the link to a repository.

**Comment by danielhrisca** [comment]
Thank you for the file Robin. I was able to find the error source quickly.
