### ISSUE TITLE
comparison mode some bugs

### ISSUE THREAD

**Issue by pyyoungman** [danielhrisca/asammdf#363]

**Comment by pyyoungman** [comment]
hello,I find two bugs about comparison mode in asammdf 5.20.2.
1.when i add new var i can't select old plot window to add line;
2.this action to drag var is disable between two plot window;

**Comment by danielhrisca** [comment]
Can you check with the development branch code?

**Comment by pyyoungman** [comment]
hello,I have checked the development,Why are there no any changes about the above bugs?
![test result](https://user-images.githubusercontent.com/58065281/81356541-ff289300-9103-11ea-9ccb-85cc5872186b.png)
![test result2](https://user-images.githubusercontent.com/58065281/81356563-0cde1880-9104-11ea-879a-4ae9ba125ec4.png)
