### ISSUE TITLE
add samples origin option 

### ISSUE THREAD

**Issue by mdiego1595** [danielhrisca/asammdf#364]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

When I merge some mdf files with "add samples origin" option set to TRUE, the resulting file does not have time gaps (if I merge one mdf file that start at 9 a.m. and finish at 11 a.m. and the second file starts at 5 p.m. and finish at 7 p.m. the time gap between 11 a.m. and 5 p.m. must be canceled in the resulting file) but in reality the resulting files has these time gaps.

How can I fix the issue?

Thank you

**Comment by danielhrisca** [comment]
@mdiego1595 _add_samples_origin_ just creates a new channel that can later be used to see from which original file the current sample came from.

for the gap between the files you will need to set the _sync_ argument to False (see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.concatenate)
