### ISSUE TITLE
Timezone parsed as uint16 failing for negative values

### ISSUE THREAD

**Issue by christian-steiniche** [danielhrisca/asammdf#365]
It seems that timezone is parsed as uint16 (H), which fails for negative timezones.

Should likely be `FMT_HEADER_BLOCK = "<4sI9Q2h4B2Q"` (not sure if both fields are int16 or just the timezone)

```
m = asammdf.MDF4("tz_minus_1.MF4")
m.header.tz_offset
```

https://github.com/danielhrisca/asammdf/blob/69615ff0c4c17ce31c3c68cf443691d4df8ab1ce/asammdf/blocks/v4_constants.py#L633

Br
Christian

**Comment by danielhrisca** [comment]
Hello Christian,

you were right, the two values were signed. Please check the development branch code.

**Comment by christian-steiniche** [comment]
Hi Daniel

Thanks for the quick response and the great project.
