### ISSUE TITLE
4

### ISSUE THREAD

**Issue by gitMesa** [danielhrisca/asammdf#366]
Hey,

When i try to load one .mdf that is generated/simulated by our software

``time data '15: 5:2020 9: 7:00' does not match format '%d:%m:%Y %H:%M:%S'``

I traced this error back to this line:

```python
timestamp = datetime.strptime(timestamp, "%d:%m:%Y %H:%M:%S")``
```

from [v2_v3_blocks.py @ line 2759](https://github.com/danielhrisca/asammdf/blob/69615ff0c4c17ce31c3c68cf443691d4df8ab1ce/asammdf/blocks/v2_v3_blocks.py#L2759).

Locally I've replaced the code with this:

```python
try:
    timestamp = datetime.strptime(timestamp, "%d:%m:%Y %H:%M:%S")
except:
    timestamp = datetime.now()
```
and it works. But this is not a good solution because this only works for me.

I cannot change the way the timestamp is simulated/exported in our generated mdf. I tried.
Is there any way to maybe force timestamp? or change the format to what asammdf expects before calling ``mdf = MDF(filepath)``?

Thanks.

**Comment by danielhrisca** [comment]
The datetime format is dictated by the MDF standard so you have to change your software to follow the proper format.

**Comment by gitMesa** [comment]
Understood. Thanks.
