### ISSUE TITLE
Memoryerror while importing large automotive .DAT extension files

### ISSUE THREAD

**Issue by akdas79** [danielhrisca/asammdf#367]
# Python version : 3.7 64bit
_Please run the following snippet and write the output here_

'python=3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.18.1'
'asammdf=5.20.5

  ## MDF version
3.00

  ## Code snippet
import tkinter as tk
from tkinter import filedialog as fd
from asammdf import MDF
from matplotlib import pyplot as plt
typeStr = '*.dat'
root = tk.Tk()
root.wm_attributes('-topmost', 1)
root.withdraw()
files = fd.askopenfilenames(parent=root,filetypes=[("Measurement MF4 file",typeStr)])
for file in files:
    mdf = MDF(file,compression='blosc')
    mdf.resample(1)
data = mdf.to_dataframe()
data
  
  ## Traceback

  MemoryError                               Traceback (most recent call last)
<ipython-input-1-f6760c9df6cc> in <module>
     11     mdf = MDF(file,compression='blosc')
     12     mdf.resample(1)
---> 13 data = mdf.to_dataframe()
     14 data

~\Anaconda3\lib\site-packages\asammdf\mdf.py in to_dataframe(self, channels, raster, time_from_zero, empty_channels, keep_arrays, use_display_names, time_as_date, reduce_memory_usage, raw, ignore_value2text_conversions, use_interpolation, only_basenames, interpolate_outwards_with_nan)
   3347                         if reduce_memory_usage:
   3348                             sig.samples = downcast(sig.samples)
-> 3349                         df[channel_name] = pd.Series(sig.samples, index=sig.timestamps)
   3350 
   3351             if self._callback:

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
   2936         else:
   2937             # set column
-> 2938             self._set_item(key, value)
   2939 
   2940     def _setitem_slice(self, key, value):

~\Anaconda3\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
   2998 
   2999         self._ensure_valid_index(value)
-> 3000         value = self._sanitize_column(key, value)
   3001         NDFrame._set_item(self, key, value)
   3002 

~\Anaconda3\lib\site-packages\pandas\core\frame.py in _sanitize_column(self, key, value, broadcast)
   3611 
   3612         if isinstance(value, Series):
-> 3613             value = reindexer(value)
   3614 
   3615         elif isinstance(value, DataFrame):

~\Anaconda3\lib\site-packages\pandas\core\frame.py in reindexer(value)
   3592 
   3593             if value.index.equals(self.index) or not len(self.index):
-> 3594                 value = value._values.copy()
   3595             else:
   3596 

MemoryError: Unable to allocate 3.40 GiB for an array with shape (7124426,) and data type |S512
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

I have tried to import a file size of 1GB but I am constantly getting a memory error; if i try a much small file size of 15Mb then everything seems to be working.

**Comment by danielhrisca** [comment]
Hello @akdas79 

does it work if you set the _reduce_memory_usage_ argument to True?

```python
df = mdf.to_dataframe(reduce_memory_usage=True)
```

**Comment by akdas79** [comment]
Hello danielhrisca,

I have already tried reduce_memory_usage but unfortunately it didn't work .

**Comment by danielhrisca** [comment]
> MemoryError: Unable to allocate 3.40 GiB for an array

You should buy a new memory stick :) 

I will see what can be done

**Comment by danielhrisca** [comment]
@akdas79 

please try the development branch code ``pip install -I https://github.com/danielhrisca/asammdf/archive/development.zip --no-deps``

**Comment by akdas79** [comment]
Thanks for sharing this but I have got the following errors again .....

I do have 8gb ram so do u think this is not enough ??
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-1-54c2cfaf43d3> in <module>
     10 for file in files:
     11     mdf = MDF(file)
---> 12 data = mdf.to_dataframe(reduce_memory_usage=True)
     13 plt.figure(figsize=(12,8))
     14 data['ASMod_tWallFld_[4]\XETK:1'].plot()

~\Anaconda3\lib\site-packages\asammdf\mdf.py in to_dataframe(self, channels, raster, time_from_zero, empty_channels, keep_arrays, use_display_names, time_as_date, reduce_memory_usage, raw, ignore_value2text_conversions, use_interpolation, only_basenames, interpolate_outwards_with_nan)
   3289                 signals = [
   3290                     signal.interp(master, self._integer_interpolation)
-> 3291                     for signal in signals
   3292                 ]
   3293 

~\Anaconda3\lib\site-packages\asammdf\mdf.py in <listcomp>(.0)
   3289                 signals = [
   3290                     signal.interp(master, self._integer_interpolation)
-> 3291                     for signal in signals
   3292                 ]
   3293 

~\Anaconda3\lib\site-packages\asammdf\signal.py in interp(self, new_timestamps, interpolation_mode)
    805                 kind = self.samples.dtype.kind
    806                 if kind == "f":
--> 807                     s = np.interp(new_timestamps, self.timestamps, self.samples)
    808 
    809                     if self.invalidation_bits is not None:

<__array_function__ internals> in interp(*args, **kwargs)

~\Anaconda3\lib\site-packages\numpy\lib\function_base.py in interp(x, xp, fp, left, right, period)
   1410         fp = np.concatenate((fp[-1:], fp, fp[0:1]))
   1411 
-> 1412     return interp_func(x, xp, fp, left, right)
   1413 
   1414 

MemoryError: Unable to allocate 54.4 MiB for an array with shape (7124426,) and data type float64

**Comment by danielhrisca** [comment]
I think you can further improve the memory usage by extracting only the needed channels
```python
interesting_channels = ['Channel 1', 'Channel 2', ] # ....
df = mdf.to_dataframe(channels, raster=1, reduce_memory_usage=True)
```

The bulk of the memory usage comes from some channels that have a value to text conversion. If you can use the raw values then another optimization would be

```python
interesting_channels = ['Channel 1', 'Channel 2', ] # ....
df = mdf.to_dataframe(channels, raster=1, reduce_memory_usage=True, ignore_value2text_conversions=True)
```

**Comment by akdas79** [comment]
I have tried your second option with both limited channel & all channels :+1: 

df = mdf.to_dataframe(raster=1, reduce_memory_usage=True, ignore_value2text_conversions=True)

Combination of all three parameters-- raster, memory usage and ignore value2text  has really worked well compare to previous occasions where I have to restart system multiple times due to significant level of memory usage!!

Thank you very much for your swift response in resolving this issue.

**Comment by tingfenghanlei** [comment]
Dear, both, I have see your comments, but I still don't know how to change the code.
Before I use 
      `mdf = MDF(MF4)`
Then have MemoryError.
Could you tell me where to add this line code?
`mdf = mdf.to_dataframe(raster=1, reduce_memory_usage=True, ignore_value2text_conversions=True)`
Thanks very much

**Comment by akdas79** [comment]
for file in files:
    mdf = MDF(file)
    data = mdf.to_dataframe(raster=1,reduce_memory_usage=True, ignore_value2text_conversions=True)

**Comment by tingfenghanlei** [comment]
Thank you. But I test in my local, I also have error like the following:
`Traceback (most recent call last):
  File "C:/2019/14selfLeaning/08readTxt_improved/TestGUI.py", line 67, in convertMF4
    mdf1 = MDF(MF4)
  File "C:\.conda\envs\python36\lib\site-packages\asammdf\mdf.py", line 121, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\.conda\envs\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 365, in __init__
    self._read(mapped=True)
  File "C:\.conda\envs\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 743, in _read
    self._process_bus_logging()
  File "C:\.conda\envs\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9322, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\.conda\envs\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9455, in _process_can_logging
    samples_only=True,
  File "C:\.conda\envs\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6026, in get
    vals = vals.copy()
MemoryError: Unable to allocate 65.4 GiB for an array with shape (1929, 36389368) and data type uint8`
@danielhrisca  Do you know how to deal with it, I think my problems is different from @akdas79 .
Thanks firstly.

**Comment by danielhrisca** [comment]
@tingfenghanlei can you share the file? The array shape is strange, since the CAN messages have a maximum payload of 64 bytes (CAN-FD).

**Comment by tingfenghanlei** [comment]
@danielhrisca I really want to share this measurement with you, but our company has a firewall and can't upload any files(May be only screenshots). How could I help you get more message to solve this problem in other way?

**Comment by tingfenghanlei** [comment]
@danielhrisca  I use the CANape to load the measurement again, then it can convert to mat successfully, it is amazing, and I do not know the reason.

**Comment by danielhrisca** [comment]
> @danielhrisca I really want to share this measurement with you, but our company has a firewall and can't upload any files(May be only screenshots). How could I help you get more message to solve this problem in other way?

what about creating a split archive and send it using multiple e-mails?

**Comment by tingfenghanlei** [comment]
> 
> 
> > @danielhrisca I really want to share this measurement with you, but our company has a firewall and can't upload any files(May be only screenshots). How could I help you get more message to solve this problem in other way?
> 
> what about creating a split archive and send it using multiple e-mails?

The content of our email needs to be less than 10M, and the measurement is more than 3GB, I do not think this method works.

**Comment by danielhrisca** [comment]
> The content of our email needs to be less than 10M, and the measurement is more than 3GB, I do not think this method works.

You can get a good size reduction if the measurement file does not use internal compressed blocks

![image](https://user-images.githubusercontent.com/20952040/82825741-6d1adb80-9eb4-11ea-9bce-24f287b0321a.png)

**Comment by tingfenghanlei** [comment]
> 
> 
> > The content of our email needs to be less than 10M, and the measurement is more than 3GB, I do not think this method works.
> 
> You can get a good size reduction if the measurement file does not use internal compressed blocks
> 
> ![image](https://user-images.githubusercontent.com/20952040/82825741-6d1adb80-9eb4-11ea-9bce-24f287b0321a.png)

After the compression is completed, there are more than 500M. The root reason may be that the configuration on the car has some problems so that the recorded the measurement has some problems.

**Comment by lcn84dcr** [comment]
Hi Daniel.
I've an issue similar to the one discussed here. I'm using Python 3.7 and ASAMMDF 5.18.2.
I need to import a large .dat file, with a signal VarP1 acquired to high sample rate. I would like to import and plot it, but in correspondance of the command PRESS1=mdf.get(VarP1), the following error appear:
"site-packages\asammdf\blocks\mdf_v3.py", line 2921, in get
"<_array_function_internals>", line 6, in concatenate
MemoryError: Unable to allocate 1.35 GiB for an array with shape <181690747,> and data type float64

I also tryed by changing the code in this way:
PRESS1=(mdf.get(VarP1)).astype(np_type=np.float32)
but the same error appear.
I don't understand why the error refers to float64 even if I import the signal by converting it in float32 with astype.

Could you please help me ?
Thanks

**Comment by danielhrisca** [comment]
@lcn84dcr you simply don't have enough free memory to extract to extract the channel

Until you do a memory upgrade you can use the _iter_get_ method to iterate in chuncks

**Comment by lcn84dcr** [comment]
Thanks Daniel. But why even if I use the command astype for importing the signal as float32, the error that I receive says that I'm trying to allocate float64 data ?
Thanks
