### ISSUE TITLE
Segmentation fault in mdf_v4.py

### ISSUE THREAD

**Issue by clynamen** [danielhrisca/asammdf#368]
For some .mf4 file (that I cannot attach) I get a segmentation fault (asammdf-5.26.0):

```
Current thread 0x00007f6e4dd63740 (most recent call first):
  File "/asammdf/blocks/mdf_v4.py", line 9239 in _sort
  File "/asammdf/blocks/mdf_v4.py", line 733 in _read
  File "/asammdf/blocks/mdf_v4.py", line 365 in __init__
  File "/asammdf/mdf.py", line 121 in __init__
```

the bug does not appear in asammdf-5.19.16.
the bug appears from asammdf-5.20.0 

Since I cannot attach the .mf4 file, I will later add more info while debugging this problem

**Comment by danielhrisca** [comment]
Hello Vincenzo,

can you check if this comment applies to your case? https://github.com/danielhrisca/asammdf/issues/358#issuecomment-621709898

**Comment by danielhrisca** [comment]
ping @clynamen
