### ISSUE TITLE
Use different modes full, low, medium for MDF version 4.xx

### ISSUE THREAD

**Issue by shyamdb** [danielhrisca/asammdf#373]
Hello,

I am using asammdf for system testing. I have a very large mdf file woth version 4.00, i am loading that file. It works completely fine. But, it takes very long to load the file and start processing it. I was going through the source code of asammdf. I found something like this in case of version MDF4:

#####################
mdf file name (if provided it must be a real file name) or file-like object

if full the data group binary data block will be memorised in RAM
if low the channel data is read from disk on request, and the metadata is memorized into RAM
if minimum only minimal data is memorized into RAM
###########################

I want to know how to use these parameters full, low and medium while loading the file. Does it make loading faster?

Asammdf works even for the files of size 150+ GB. But it is taking too long to load a file. I want to reduce the file loading time.

**Comment by shyamdb** [comment]
@danielhrisca 
Here in my case, the very first step take the longest. After that, it goes blazingly fast. But it takes almost 8-9 minutes to perform following step to load a 45 GB file.

loadedmdf = MDF(filename)

Can you please help how to use "full", "minimum" and "low" in case of MDF version 4?

Or may be some other way to load the file faster?

**Comment by danielhrisca** [comment]
Hello @shyamdb 

you should update to version 5.20.6 first.

The memory options have been dropped since 5.0.0 and the 4.x.y branch is not developed anymore.

**Comment by shyamdb** [comment]
Hello @danielhrisca 

I think you misunderstood it. I mean MDF version 4.xx. 

I didn't mean the asammdf version.

I am already using asammdf 5.20

**Comment by danielhrisca** [comment]
> I am already using asammdf 5.20

there is no _memory_ option in this version. The metadata is read from the file, but the raw samples are read on demand from the file, when needed.



> But it takes almost 8-9 minutes to perform following step to load a 45 GB file.

Is the file unsorted? If so it may take some time to sort it first.

**Comment by shyamdb** [comment]
@danielhrisca 

How to check if the file is unsorted?

**Comment by danielhrisca** [comment]
Place a print [here](https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/mdf_v4.py#L9120) . If it reaches this line then the group is unsorted

**Comment by shyamdb** [comment]
@danielhrisca 

Ok i will do it. In the meanwhile,

1. if it is an unsorted mdf file, is there any way to load an unsorted file faster? (Because my file can go 500-600+ GB or even up to 1 TB) It will be very useful to have some solution for this.

2. What is "low", "minimum" and "full" in loading MDF4? Has it any impact on performance? How to use it?

**Comment by danielhrisca** [comment]
> * if it is an unsorted mdf file, is there any way to load an unsorted file faster? (Because my file can go 500-600+ GB or even up to 1 TB) It will be very useful to have some solution for this.

I've never seen files so big, but I can imagine it would take a lot o time to process. It would be nice if you could share such a file

> * What is "low", "minimum" and "full" in loading MDF4? Has it any impact on performance? How to use it?

That's what I'm trying to tell you: the "low", "minimum" and "full" memory options were used in the 4.x.y releses. Since 5.0.0 this was removed; the behavior now is similar to the "low" option in 4.x.y

**Comment by shyamdb** [comment]
@danielhrisca 
![Screenshot_20200617-195811_Chrome](https://user-images.githubusercontent.com/50797250/84932707-ffd62100-b0d4-11ea-82d6-e94dad5a077c.jpg)

Here i am seeing these parameter values but i could not understand how to use this with the parameter name. Is it a mistake in documentation or i didn't get the way of using it? 

Can you please help me to understand how to use them? 

Also, as i mentioned before, is there a way to load an unsorted mdf file faster or read the data only if and when requested? (Like load_measured_data parameter in earlier versions)

**Comment by danielhrisca** [comment]
Are you looking at the latest documentation? https://asammdf.readthedocs.io/en/latest/api.html#mdf

**Comment by shyamdb** [comment]
> Are you looking at the latest documentation? https://asammdf.readthedocs.io/en/latest/api.html#mdf

Yes i am seeing in the latest documentation only. If you go to the API section MDF4, it is mentioned there.

**Comment by shyamdb** [comment]
> Are you looking at the latest documentation? https://asammdf.readthedocs.io/en/latest/api.html#mdf

@danielhrisca 
Please check:

https://asammdf.readthedocs.io/en/latest/api.html#mdf4

**Comment by danielhrisca** [comment]
That was an error in the docstring.

Anyway you should always use the MDF class.

**Comment by shyamdb** [comment]
Is there any way to load the unsorted file faster? Or using parallel processing or something like that?

**Comment by danielhrisca** [comment]
I'm afraid not. I could profile on the file if you could share it, to improve the loading time

**Comment by shyamdb** [comment]
@danielhrisca 

Hi, i checked putting print statement in sorting method, but it did not get executed. That means, it is not an unsorted file, right? 

As it is a sorted file, is there a way to make the loading faster?

Also, i would like to share the file with you, but my company policies don't allow me to share the files.

**Comment by danielhrisca** [comment]
Even it is scrambled?

**Comment by shyamdb** [comment]
How to check if it is scrambled using asammdf?

**Comment by danielhrisca** [comment]
You would use this method https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.scramble to anonymize the text information(comments, channel names)

**Comment by shyamdb** [comment]
@danielhrisca 

Thanks for the infos. But, won't it put an overhead in timing? Because first i need to scramble the file and then again load it and process it, right?

Won't it take longer than loading directly?

Or is there a way to use it efficiently?

**Comment by shyamdb** [comment]
@danielhrisca 

Also, 

Once the file is scrambled, how to access the channels if the names are anonymized?

With the group index or display name ??

**Comment by danielhrisca** [comment]
It would probably take some time, but the idea is if the scrambled file can be shared, since it can only be interesting only for its internal structure (mdf blocks). So it is very useful for me for performance profiling but it does not give information about your project, and ECU variables.

**Comment by shyamdb** [comment]
@danielhrisca 

Ok, i will check and let you know. 

In the meanwhile, is there a significant role of "callback" argument in loading the file?

What kind of functions i can call there? Any example? Is it possible to read the signal value then and there itself?? Parallel to the loading?

**Comment by danielhrisca** [comment]
Please run this and send the output file ``info.txt``

```python
mdf = MDF(filename)
with open('info.txt', 'w') as f:
    for i, gp in enumerate(mdf.groups):
        f.write('='*10 + '\n')
        f.write(f'Group {i}: cycles={gp.channel_group.cycles_nr} bts={gp.channel_group.samples_byte_nr} channels={len(gp.channels)}\n')
        for blk in gp.data_blocks:
            f.write(str(blk) + '\n')
        f.write('\n'*3)
```

**Comment by danielhrisca** [comment]
ping @shyamdb
