### ISSUE TITLE
Change int samples to string samples and save the new signal to a new mf4 file

### ISSUE THREAD

**Issue by celoreck** [danielhrisca/asammdf#374]
Hi Daniel! First of all, your library is amazing, it is helping me a lot.

I have a problem by generating a new mf4 file with the signals samples in STRING format.
Below is my application step by step:

1. I concatenate the data from 3 .mf4 files. Each file has 30007 rows, so the final file has 90021 rows.
2. In some signals from the original files, the samples are an array of STRINGS, for example: ['String_1' 'String_2' 'String_3' ... 'String_30007'].
3. By concatenating the 3 files, those samples become an INT number, such as: [1 2 3 ... 90021].
4. I created a function that correlates the INT number with its respective STRING value and returns an array of STRINGS from the concatenated file. The array of strings is done and works correctly and as output I have: ['String_1' 'String_2' 'String_3' ... 'String_90021'].
5. The problem is by replace the INT array of the concatenated file [1 2 3 ... 90021] by the STRING array ['String_1' 'String_2' 'String_3' ... 'String_90021'] in the respective signal and generate a new mf4 file.

I tried to replace and also create a new signal and save it to a new mf4 file, but it always returns an error:

timestamps = [1 2 3 ... 90021]
b = ['String_1' 'String_2' 'String_3' ... 'String_90021']
s_uint10 = Signal (samples = np.array (b, dtype = np.dtype ('U25')),
                 timestamps = timestamps,
                 raw = False,
                 name = 'Uint8_Signal',
                 unit = '-')

MdfException: Unknown type: dtype = <U25, shape = (90021,)

I'm stuck here, I don't know if the best thing to do is replace the array on the original signal or create a new signal with the same settings, just changing the INT array to STRING array. Is there any way to solve this?

Thank you.
Marcelo.

**Comment by danielhrisca** [comment]
how do you concatenate?

this should take care of preserving the value to string conversion
```python
mdf = MDF.concatenate([mdf1, mdf2, mdf3])
```

**Comment by celoreck** [comment]
I concatenate just as you mentioned, using:
`mdf = MDF.concatenate([mdf1, mdf2, mdf3])`

But by concatenate a become the following error:
`MdfException: internal structure of file 3 is different; different channels`

I didn't change nothing between the creation of each file, they have the same labels number, same variables name, same raster, so I don't understand why this happen. If the structure is changed between 2 files, is there any way to reorder that or concatenate all files using the the structure of the first file?

Let me explain on important thing about my application: Each one of this mf4 files is created every 10 minutes since the car is moving. If the car isn't moving (engine off), our software finalize the file, so this last file will not have 10 min of data (lets take a file with 3 minutes for example). When the car engine starts running again, a new file will be created, so at the end we will have something like this:
`array_of_files [ mdf1 mdf2 mdf3 mdf4 mdf5]
array_of_files_lenght [10min 10min 3min 10min 10min}` 

I noticed that this error happen when I try to concatenate this "smaller-sized" file (3 min file) with the next file (10 min file), just as follows:
mdf = MDF.concatenate([10min_file1 10min_file2 10min_file3]) -- WORKS WELL
mdf = MDF.concatenate([10min_file1 10min_file2 10min_file3 3min_file4]) -- WORKS WELL
mdf = MDF.concatenate([10min_file1 10min_file2 10min_file3 3min_file4 10min_file15]) -- ERROR

Do you know the possible cause of this error and how to fix it?


I would like to do the INT to STRING conversion also, because I need to make some adjustments in some signals, so if you have some tips in this topic I would appreciate.

**Comment by danielhrisca** [comment]
Is is possible to send me a 10min and a 3 min file? (as it is or scrambled)

**Comment by celoreck** [comment]
Yes, I will send the two mf4 files to your e-mail, I tried to attach it here but it didn't work.

As I checked, both have the same number of groups and channels in each group:
Channel Group 1 - Channels number = 11
Channel Group 2 - Channels number = 2
Channel Group 3 - Channels number = 2
Channel Group 4 - Channels number = 2
Channel Group 5 - Channels number = 2
Channel Group 6 - Channels number = 23
Channel Group 7 - Channels number = 143
Channel Group 8 - Channels number = 10
Channel Group 9 - Channels number = 10

**Comment by danielhrisca** [comment]
@celoreck 
please try the development branch code

**Comment by danielhrisca** [comment]
@celoreck closing this based on your e-mail feedback

**Comment by celoreck** [comment]
Hi Daniel, how are you?

I’m using your library and it’s works fine. I have a simple questions this time: by concatenating some files , if I have a GAP of signas in between by setting sync=True. I noticed that in this GAP the signal value stays the same of the least value. Is there a way to put all signals to 0 (zero) during this GAP, that is, during the time that no signals are available?

Thanks once again!
Marcelo Reck

Enviado do meu iPhone

Em 22 de jun de 2020, à(s) 13:40, Daniel Hrisca <notifications@github.com> escreveu:

﻿

Closed #374<https://github.com/danielhrisca/asammdf/issues/374>.
