### ISSUE TITLE
How to deal with Motorola data type signals?

### ISSUE THREAD

**Issue by mrmuyi** [danielhrisca/asammdf#375]
# Python version
Python 3.6
asammdf 5.11
```python
# coding: utf-8

from asammdf import MDF, Signal

mdf = MDF('rec_2019-01-10_13_34_20_sorted_Mot.dat',version='3.30')
speed = mdf.get('VehSpdAvgDrvnHSC1:CAN1')
#print(mdf.get_group(579))#mdf.info()
print(speed.samples)
```
  
# Description
The 'VehSpdAvgDrvnHSC1:CAN1' Data Type was Unsign Motorola, and parse the data result was not right. While dealing the Data Type was Intel, the result was right. How to correctly get the right data dealing with the Motorola type signal.
I also send the original file to your email.

**Comment by liverpoolilove** [comment]
Excuse me, have you solved your problem?

**Comment by danielhrisca** [comment]
@liverpoolilove @mrmuyi 

the development branch code can handle the problem now:

![image](https://user-images.githubusercontent.com/20952040/86564261-95dfc780-bf6e-11ea-8e8a-fcbaa02fae54.png)

**Comment by mrmuyi** [comment]
Thanks, the issue solved!

**Comment by mrmuyi** [comment]
> Excuse me, have you solved your problem?

YES!
