### ISSUE TITLE
Use attachment dbc to parse mdf. Does it only support mf4?

### ISSUE THREAD

**Issue by liverpoolilove** [danielhrisca/asammdf#377]
Problem Description:
I use asammdf GUI's can logging this function, open the dat file, load the dbc file, the prompt is as follows:
Summary:
-X of XXX IDs in the MDF4 file were matched in the DBC and converted
-XXX unknown IDs in the MDF4 file

downloaded the example:

`# extract info from meta header - e.g. to get correct start time of a file
session_start = mdf.header.start_time
delta_seconds = mdf.select(["CAN_DataFrame.BusChannel"])[0].timestamps[0]
split_start = session_start + timedelta(seconds=delta_seconds)
split_start_str = split_start.strftime("%Y%m%d%H%M%S")

mdf_filter = mdf.filter(["CAN_DataFrame.ID", "CAN_DataFrame.DataBytes"])
mdf.save(Path(path_out, "filtered"), overwrite=True)
`

It's all about mdf version 4.0! Does it only support mf4? But my mdf version is 3.30!

**Comment by danielhrisca** [comment]
@liverpoolilove can you send me the file? I haven't seen a pure CAN bus logging measurement in the mdf 3 format. In MDF 4 there are certain flags that mark the bus logging

**Comment by danielhrisca** [comment]
ping @liverpoolilove
