### ISSUE TITLE
missing options in mdf.iter_groups()

### ISSUE THREAD

**Issue by Dauhl** [danielhrisca/asammdf#381]
I am using mdf.iter_groups() to iterate over a mdf file. This method uses get_group which has several options. However in iter_groups on options are passed forward. Could you please add options to iter_groups? For my application the time_from_zero option is especially important.

So far I just copied the lines by hand, but with every update I would have to do this step again.

Thanks!

**Comment by danielhrisca** [comment]
@Dauhl please try the development branch code

**Comment by danielhrisca** [comment]
ping @Dauhl
