### ISSUE TITLE
General Question: Plotting of more than one signal

### ISSUE THREAD

**Issue by mikesmitti** [danielhrisca/asammdf#385]
Hello,

maybe I miss some information, but I did not find any on how to plot more than one signal in a single plot.

The signal.plot() works fine but I would like to costumize my plots in some kind or another.
For example:
- multiple signals in one plot.
- create a predefined coordinate system
- colours of plots, legends for plots, headings,...
- automatize the procedure (e.g. fit the diagram to a signal programatically) 
- safe the diagram to a file (jpg, png,...)

Do you have any information or examples on the topics? 
A signal.plotmultiple() so to say.

Do you have a recommended workflow (with commands from asammdf) to achieve this goal?

Best regards,
Mike

**Comment by danielhrisca** [comment]
For starters have a look at this function https://github.com/danielhrisca/asammdf/blob/master/asammdf/gui/plot.py#L16

**Comment by mikesmitti** [comment]
Thank you for the information, this works fine so far.

One further question:

How can I save the generated plot to a image-file (e.g. jpg or png)?

Best regards

**Comment by danielhrisca** [comment]
Right click on the plot and "Export"

**Comment by mikesmitti** [comment]
Sorry, my question was a little unspecific.

I mean, how to save it programmatically to an image-file, instead of ploting it to the screen

Best regards

**Comment by danielhrisca** [comment]
> I mean, how to save it programmatically to an image-file, instead of ploting it to the screen

This is not implemented

**Comment by MatinF** [comment]
We have an API example that uses the asammdf API to load data, DBC convert it, create a signal plot and then save that plot:
https://github.com/CSS-Electronics/api-examples/blob/master/examples/asammdf-basics/asammdf_basics.py

**Comment by mikesmitti** [comment]
I am sorry, the link is not working.

Best regards

**Comment by MatinF** [comment]
I've updated the link now

**Comment by mikesmitti** [comment]
Thank you
