### ISSUE TITLE
Time vector close to infinity

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#386]
# Python version
python=3.6.5
asammdf=5.20.6
# Code 

  ## MDF version
3.00

  ## Code snippet
with MDF(file,remove_source_from_channel_names=True, use_display_names=True) as mdf_file:

      df = mdf_file.to_dataframe(Labels.name.tolist(),time_from_zero=False) 
      time_as_date = pd.to_datetime(mdf_file.header.start_time) + pd.to_timedelta(df.index, unit='s')
  
  ## Traceback
C:\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:47: RuntimeWarning:
overflow encountered in multiply
Traceback (most recent call last):
  File "C:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-33c15c2d36eb>", line 1, in <module>
    time_as_date = pd.to_datetime(mdf_file.header.start_time) + pd.to_timedelta(df.index, unit='s')
  File "C:\anaconda3\lib\site-packages\pandas\core\tools\timedeltas.py", line 97, in to_timedelta
    return _convert_listlike(arg, unit=unit, errors=errors, name=arg.name)
  File "C:\anaconda3\lib\site-packages\pandas\core\tools\timedeltas.py", line 140, in _convert_listlike
    value = sequence_to_td64ns(arg, unit=unit, errors=errors, copy=False)[0]
  File "C:\anaconda3\lib\site-packages\pandas\core\arrays\timedeltas.py", line 960, in sequence_to_td64ns
    data = (base * m + (frac * m).astype(np.int64)).view("timedelta64[ns]")
  File "C:\anaconda3\lib\site-packages\pandas\core\indexes\numeric.py", line 401, in astype
    arr = astype_nansafe(self.values, dtype=dtype)
  File "C:\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 868, in astype_nansafe
    raise ValueError("Cannot convert non-finite values (NA or inf) to integer")
ValueError: Cannot convert non-finite values (NA or inf) to integer
  
# Description
Hello Daniel
It looks like that the imported *.dat-file is corrupted. At least the first value of the time vector is close to infinity. This is what the index vector looks like.
array([1.70000000e+308, 5.87123151e-001, 5.97029651e-001, 6.07004151e-001,
       6.17037151e-001, 6.26997651e-001, 6.37165651e-001, 6.47008651e-001,
       6.57015151e-001, 6.67047651e-001, 6.77018651e-001, 6.87067151e-001,
       6.96984651e-001, 7.07019151e-001])

Unfortunatly the value[0] is just close to infinity. Therefore the following will not work.
df = df.replace([np.inf, -np.inf], np.nan)
df.isnull().values.any()

Is there any way to check this within your MDF class? Your help is much appreciated.

**Comment by Lama09** [comment]
Hello Daniel,

I encountered this issue now on another file. But this time at the end of the time vector. So the length of the time vector will exceed the measurement length. The upcoming time values will by inf. This time the measurement file is not corrupted. I checked it with MDFValidator and got no erros. I also could open it with the MDA-Viewer and TurboLab. Open the file with the asammdf-Viewer and create a plot window it will crash. See the traceback below.

![image](https://user-images.githubusercontent.com/48772414/87792814-b0eee900-c844-11ea-8984-58a1d1d09a42.png)

--------------------------------------------------------------------------------
<class 'ValueError'>	 
could not broadcast input array from shape (34185) into shape (33050)
--------------------------------------------------------------------------------
  File "c:\anaconda3\lib\site-packages\asammdf\gui\widgets\file.py", line 712, in search
    self.add_window(["Plot", signals])
  File "c:\anaconda3\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 314, in add_window
    raw=True,
  File "c:\anaconda3\lib\site-packages\asammdf\mdf.py", line 2456, in select
    master[current_pos:next_pos] = sig

**Comment by danielhrisca** [comment]
I need the file to do analysis otherwise I cânt sau what is wrong

**Comment by Lama09** [comment]
I'm afraid this this will become a problem due to security reason. Is there any other opportunity. Or can I somehow help to debug?

**Comment by danielhrisca** [comment]
Even if you scramble the file first?

**Comment by Lama09** [comment]
Hello Daniel,
how can this be accomplished?

**Comment by danielhrisca** [comment]
Using the GUI in the scramble tab:

**Comment by Lama09** [comment]
Ok, I could run the functionality. How can I provide the files?

After the scramble I was runing the MDF-Validator on one of the scrambled file. It is now producing a lot of erros while it wasn't on the original file.
During the scramble process on file two. The GUI chrashed:

Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 266, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\anaconda3\lib\site-packages\asammdf\mdf.py", line 106, in __init__
    raise MdfException(f'File "{name}" does not exist')
asammdf.blocks.utils.MdfException: File "E:\Temp\test.scrambled.dat" does not exist


Details: 2020-07-20, 23:16:52
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 266, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\anaconda3\lib\site-packages\asammdf\mdf.py", line 106, in __init__
    raise MdfException(f'File "{name}" does not exist')
asammdf.blocks.utils.MdfException: File "E:\Temp\test.scrambled.dat" does not exist

--------------------------------------------------------------------------------
  File "c:\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 838, in _open_file
    self,
  File "c:\anaconda3\lib\site-packages\asammdf\gui\widgets\file.py", line 159, in __init__
    progress=progress,
  File "c:\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 231, in run_thread_with_progress
    raise Exception(thr.error)

A scrambled file was still created.

**Comment by danielhrisca** [comment]
The MDFValidator errors are normal after the text scrambling. I am only interested in the internal file structure so this is fine. 

Can you send it to my email? (see profile)

**Comment by danielhrisca** [comment]
Hello @Lama09 

I've added the method _cleanup_timestamps_ to the _MDF_ class. You can use it to specify the allowed time range (using _minimum_ and _maximum_ arguments) and the allowed exponent for the exponential notation of the time stamp values (_exp_min_ and _exp_max_ arguments). _NaN_ and _inf_ values are automatically discarded. 

See the [_cleanup_timestamps_ documentation](https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.cleanup_timestamps)

```python

from asammdf import MDF

mdf = MDF('time_infinity_scrambled1.mf4')
mdf2 = mdf.cleanup_timestamps(1e-15, 1e15)
mdf2.save('time_infinity_scrambled1_clean.mf4')
```

**Comment by Lama09** [comment]
Hello Daniel,
many thanks for this new feature. Could you just explain, why this has not been an issue in the past? I also wounder, if that could be a default configuration of the mdf-Class? Or what would be the disadvantage of doing it like that?

When do you plan to realase Version 5.22.0? I'm currently don't like to use the development branch within my python configuration.

**Comment by danielhrisca** [comment]
This is a very time consuming function since it needs to read all recorded data. Most files do not need  it so it does not make sense to make it the default.

**Comment by Lama09** [comment]
Thanks for this information. So again what curres this issues with the infinity time vector? Is there something wrong with the mf4 file itself? If you recommand not to use this methode as default, how can I programticly check if a file will produce this infinity issue? Otherwise I will be forced to use your method by default and will get the mentioned time consuming problem.

**Comment by danielhrisca** [comment]
You can't tell from the file structure. Only by looking at the actual time values you can see the implausible data

**Comment by Lama09** [comment]
Hello @danielhrisca,
I'm very sorry for my late response. First of all I would like to let you know, that for the files where I encountered this problem, your function `cleanup_timestamps()` is working well.👍

By running the function  `cleanup_timestamps()` I will get the following warning.

```
C:\Tools\anaconda3\envs\py38\lib\site-packages\asammdf\blocks\utils.py:1496: RuntimeWarning: divide by zero encountered in log10
  exps = np.log10(t)
```

Would it be possible to check the time vector within your class for the infinity issue and raise a warning? Maybe based on python max and min float value.
`len(data.loc[(data.index<sys.float_info.min) | (data.index>sys.float_info.max)])`

Otherwise I would have to use the the function  `cleanup_timestamps()` by default. Here you pointed out, that this might be a performance issue.

If I try to access labels using your asammdf GUI, the following issues occurred.

**New plot window**

```
 2020-10-02, 10:48:27
--------------------------------------------------------------------------------
<class 'ValueError'>	 
could not broadcast input array from shape (2338) into shape (1170)
--------------------------------------------------------------------------------
  File "c:\tools\anaconda3\lib\site-packages\asammdf\gui\widgets\file.py", line 783, in search
    self.add_window(["Plot", signals])
  File "c:\tools\anaconda3\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 319, in add_window
    raw=True,
  File "c:\tools\anaconda3\lib\site-packages\asammdf\mdf.py", line 2470, in select
    master[current_pos:next_pos] = sig
```

**New numeric window**

```
2020-10-02, 10:49:56
--------------------------------------------------------------------------------
<class 'ValueError'>	 
Length mismatch: Expected 325073 rows, received array of length 325162
--------------------------------------------------------------------------------
  File "c:\tools\anaconda3\lib\site-packages\asammdf\gui\widgets\file.py", line 787, in search
    self.add_window(["Tabular", signals])
  File "c:\tools\anaconda3\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 274, in add_window
    time_from_zero=False,
  File "c:\tools\anaconda3\lib\site-packages\asammdf\mdf.py", line 3383, in to_dataframe
    interpolate_outwards_with_nan=interpolate_outwards_with_nan,
  File "c:\tools\anaconda3\lib\site-packages\asammdf\mdf.py", line 3578, in to_dataframe
    df.set_index(master, inplace=True)
  File "c:\tools\anaconda3\lib\site-packages\pandas\core\frame.py", line 4594, in set_index
    f"Length mismatch: Expected {len(self)} rows, "
```
