### ISSUE TITLE
I am using asammdf in NiFi execute script. Syntax error: no viable alternative at input "V{gap}"

### ISSUE THREAD

**Issue by RadhaSwathi** [danielhrisca/asammdf#388]
Syntax error: no viable alternative at input "V{gap}" Line No 453

**Comment by danielhrisca** [comment]
I have no idea what NiFi. 

Please share the complete error traceback message

**Comment by RadhaSwathi** [comment]
Failed to process session due to javax.script.ScriptException: SyntaxError: no viable alternative at input '"V{gap}"' in librarypath\asammdf\blocks\mdf_v3.py at line number 453 at column number 43: org.apache.nifi.processor.exception.ProcessException: javax.script.ScriptException: SyntaxError: no viable alternative at input '"V{gap}"' in

**Comment by danielhrisca** [comment]
What asammdf version do you use?

**Comment by RadhaSwathi** [comment]
I am using ''5.21.0" version of asammdf.

**Comment by danielhrisca** [comment]
Could it be that the Apache NiFi cannot handle Python 3.6 syntax?

**Comment by RadhaSwathi** [comment]
I am not an expert in Apache NIFI, it could be possibility. I did some web search about the error and found out Apache NiFi uses Jython and has some constraints.
https://stackoverflow.com/questions/25200629/error-no-viable-alternative-at-input-for-python
Found smilar error here.

**Comment by danielhrisca** [comment]
From what I know jython is python 2.7 only. 

You may try to install version 4.17.2 https://pypi.org/project/asammdf/4.7.12/. That is the last version that supports python 2.7, but it is well behind the current code.
