### ISSUE TITLE
Problems with processing time based on data merging technique

### ISSUE THREAD

**Issue by masoomk87** [danielhrisca/asammdf#391]
# Python version
_Please run the following snippet and write the output here_
('python=3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 ' 'bit (AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.18.2'
'asammdf=5.19.10'
```
## Code snippet
  **Technique A**
        
        channels = mdf.select(SignalsToRead)
        new_mdf = MDF()
        new_mdf.append(channels)
        FinalList.append(new_mdf)
        mdf_merged = MDF.concatenate(FinalList)

mdf_merged.save(r"C:\Logs\outy.mf3", overwrite=True)

   **Technique B **
       Inside a for loop
       {
        start = time.time()
        mdf = mdf.filter(SignalsToRead)
        mdf = mdf.resample(0.1)
        FinalList.append(mdf)
        }
mdf_merged.save(r"C:\Logs\plmhev60\outy.mf3", overwrite=True)


## Traceback
No errors
  
# Description

I have some question regarding the way I am merging several mf3 (.dat) files. With Technique A, the appending operation takes around 13 seconds / 600 MB, and the merging operation for (5) files takes around 477 seconds. The size of the output file is around 7 GB

Using Technique B, the appending operation takes < 2 seconds / 600 MB, and the merging operation for (5) files takes around 4,5 seconds. The size of the output file is 400 MB

I am forced to used Technique A, because with technique B i get an error about incorrect channel order on some files. This probably happens that the channel order changes when I add some additional signals in recording some of the files

So, my question is that is it possible to bring down the time for appending, merging and saving the file to the disk using Technique A ? or can I use any alternates..

_Please describe the issue here._

**Comment by danielhrisca** [comment]
How long does this take?

```python
FinalList = []
	for mdf in inpu_mdfs:
	channels = mdf.select(SignalsToRead)
	new_mdf = MDF()
	for ch in channels:
		new_mdf.append(ch)
	FinalList.append(new_mdf)
mdf_merged = MDF.concatenate(FinalList)
```

**Comment by masoomk87** [comment]
Thanks a lot. This really helped to bring down the execution times

Now its 4 seconds / 600MB (for syn and append), and merging takes < 2 seconds :) 


`FinalList = []
        for mdf in inpu_mdfs:
        channels = mdf.select(SignalsToRead)
        new_mdf = MDF()
        for ch in channels:
            new_mdf.append(ch)
        new_mdf = new_mdf.resample(0.1)
        FinalList.append(new_mdf)
        del new_mdf`
mdf_merged = MDF.concatenate(FinalList)

**Comment by masoomk87** [comment]
Can you please also tell me why the approach worked ? Instead of adding channels directly by using `new_mdf.append(channels)`, why did the execution speed improved by adding the channels using for loop ?

**Comment by danielhrisca** [comment]
In the first case you had signal coming from multiple channel groups, with different sampling rates. When appeding, a new channel group is created, and by definition all the signals in a channel group have the same sampling; this means the initial signals would be interpolated and many new samples would be generated in the process.

Appending each signal by itself will skip the interpolation, at the expense of an increased file size caused by the time channels for each new channel group.

**Comment by masoomk87** [comment]
Ok. Thanks for the explanation

Yes, I noticed that if I resample the early enough in Technique A, the results are also quick

## Code snippet
  **Technique A**
        mdf = mdf.resample(0.1)
        channels = mdf.select(SignalsToRead)
        new_mdf = MDF()
        new_mdf.append(channels)
        FinalList.append(new_mdf)
mdf_merged = MDF.concatenate(FinalList)`
