### ISSUE TITLE
how to save plotter configuration ?

### ISSUE THREAD

**Issue by gaetanrocq** [danielhrisca/asammdf#393]
hello,
i'm using the last 5.21 version but i'm looking for the function of configuration management as described in the documentation :

- Load configuration : restores channels tree and all sub-plot windows from a saved configuration file
- Save configuration : saves all sub-plots (channels, colors, common axis and enable state) and channel tree

is there an option to activate ?
it could be very helpful to be able to switch from several acquisitions without to have to reselect all channels each time.

thank a lot for your help.

**Comment by danielhrisca** [comment]
@gaetanrocq 
please try the development branch code

![image](https://user-images.githubusercontent.com/20952040/89770917-24b0a880-db08-11ea-9d93-d3bd9ab8cda2.png)

**Comment by gaetanrocq** [comment]
thank you,
I successfully installed 5.22.0.dev9 version but i've such error when try to use it, any idea ? :

_Successfully installed asammdf-5.22.0.dev9

C:\Users\u197375>asammdf
Traceback (most recent call last):
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\u197375\AppData\Local\Programs\Python\Python38-32\Scripts\asammdf.exe\__main__.py", line 4, in <module>
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\site-packages\asammdf\gui\asammdfgui.py", line 8, in <module>
    from asammdf.gui.widgets.main import MainWindow
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 32, in <module>
    from .file import FileWidget
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\site-packages\asammdf\gui\widgets\file.py", line 39, in <module>
    from .attachment import Attachment
ModuleNotFoundError: No module named 'asammdf.gui.widgets.attachment'_

**Comment by danielhrisca** [comment]
I forgot to commit the new files. You need to get the development code again

**Comment by gaetanrocq** [comment]
great it works, thk you.
it seems that there's an issue with chnannel type compatibility.
I've error when trying to save configuration with several types of channels 

_👍 Error: <class 'TypeError'>	 
Object of type int32 is not JSON serializable

_Details: 2020-08-10, 14:59:01_
--------------------------------------------------------------------------------
<class 'TypeError'>	 
Object of type int32 is not JSON serializable
--------------------------------------------------------------------------------
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\site-packages\asammdf\gui\widgets\file.py", line 830, in save_channel_list
    json.dumps(self.to_config(), indent=4, sort_keys=True)
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "c:\users\u197375\appdata\local\programs\python\python38-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '_

**Comment by gaetanrocq** [comment]
Hello,
some quick proposals for plotter usage optimization:
**- Subplot handling:**
-> same subplot channel lists width when subplots X axis are linked in order to have real X synchronisation.
-> subplot channels list adaptation in order to be able to read channel full names
-> all subplot channels have common Y axis by default (or a way to force it fast without to check all box one by one)
-> possibility to change not only line color but also width, line type.

**- a 'full screen' mode** (with keybord shortcut) could be great in order to have the best view of  the subplots:
-> whipe channels list
-> subplots automatic sizing (fullfil the screen)
-> subplot channels list adaptation in order to be able to read channel full names

**- subplot configuration saving:** 
we often need to look at the same channels but on lots of different files.
the goal is then to make the configuration and the acquisition file independent.
-> save position of subplots (verticaly, cascade, ...)
-> when a saved configuration is used, keep number of subplots, position, tile type, channels list identical to the saved version, even if channels aren't available with an other acquisition file. If channels aren't available, just display the name but without value and no line in the graphical area.

**Comment by danielhrisca** [comment]
> -> same subplot channel lists width when subplots X axis are linked in order to have real X synchronisation.

I suppose this only works for tiled windows. I think we could adjust the list width to be the same as the current active plot



> -> all subplot channels have common Y axis by default (or a way to force it fast without to check all box one by one)

It is relativele easy to do this: 
1. click the channel selection list
2. CTRL+A
3. right click and select "Add to common Y axis"

-> possibility to change not only line color but also width, line type.
this might impact performance, I'll have to check



> -> save position of subplots (verticaly, cascade, ...)

the sub-plots geometry is now saved and restored in the latest development branch code



> -> when a saved configuration is used, keep number of subplots, position, tile type, channels list identical to the saved version, even if channels aren't available with an other acquisition file. If channels aren't available, just display the name but without value and no line in the graphical area.

also in the development branch, empty signals will be used for the Numeric and Plot windows, and NaN columns for the Tabular window

**Comment by danielhrisca** [comment]
> Object of type int32 is not JSON serializable

this should also be fixed in the development branch

**Comment by gaetanrocq** [comment]
Hello,
>_-> same subplot channel lists width when subplots X axis are linked in order to have real X synchronisation._
>I suppose this only works for tiled windows. I think we could adjust the list width to be the same as the current active plot

Yes you're right, it could be great. If possible, set as minimum width the size of bigger channel name.
in this way, X axis will really be synchronized.

CTRL+A to"Add to common Y axis" Could be a solution thanks.
Could it be possible to automatically 'add to common Y' a new selected channel when added in a plotter where all channels are already linked ? In order to avoid to check this option for all new channels ?

>_-> possibility to change not only line color but also width, line type._
>this might impact performance, I'll have to check

Thanks, it was just because with lot of channels it's sometime difficult to differentiate with color only. 

>Object of type int32 is not JSON serializable
>this should also be fixed in the development branch

It works thanks !

the sub-plots geometry with channels list seems to be well saved , thanks a lot.

Other proposals coming during usage:
-> have the possibility of 3 drawing modes : line, dot and stairs in order to see when signals are updated
-> is it possible to reduce plotter's title bar in order to let more place for graphic area ? globally, reduce the lost space in order to be able to view more channels on different sub-plots (one sub-plot per phisycal unit)
![Image sans titre](https://user-images.githubusercontent.com/69457616/90163341-41621000-dd96-11ea-9f28-79265bfd8ded.png)

-> have the possibility to modify each channel by applying mathematical functions (offset, gain, filter, gradient, ...), be able to change and save paramters in order to avoid  to create new channel each time we would like adjust it. (as 'Insert computation' function does but for each channel). Save such modification parameters in the configuration.
-> add this functionnality by using right click on a selected channel to avoid it's name research in a list.

thanks a lot.

**Comment by danielhrisca** [comment]
> Yes you're right, it could be great. If possible, set as minimum width the size of bigger channel name.
> in this way, X axis will really be synchronized.

This will not happen since there are cases were the channel names are very long



> -> have the possibility of 3 drawing modes : line, dot and stairs in order to see when signals are updated

This is hard to do because of how the  signals are culled before plotting

> Hello,
> 
> > _-> same subplot channel lists width when subplots X axis are linked in order to have real X synchronisation._
> > I suppose this only works for tiled windows. I think we could adjust the list width to be the same as the current active plot
> 
> Yes you're right, it could be great. If possible, set as minimum width the size of bigger channel name.
> in this way, X axis will really be synchronized.
> 
> CTRL+A to"Add to common Y axis" Could be a solution thanks.
> Could it be possible to automatically 'add to common Y' a new selected channel when added in a plotter where all channels are already linked ? In order to avoid to check this option for all new channels ?
> 
> > _-> possibility to change not only line color but also width, line type._
> > this might impact performance, I'll have to check
> 
> Thanks, it was just because with lot of channels it's sometime difficult to differentiate with color only.
> 
> > Object of type int32 is not JSON serializable
> > this should also be fixed in the development branch
> 
> It works thanks !
> 
> the sub-plots geometry with channels list seems to be well saved , thanks a lot.
> 
> Other proposals coming during usage:
> -> have the possibility of 3 drawing modes : line, dot and stairs in order to see when signals are updated
> -> is it possible to reduce plotter's title bar in order to let more place for graphic area ? globally, reduce the lost space in order to be able to view more channels on different sub-plots (one sub-plot per phisycal unit)
> ![Image sans titre](https://user-images.githubusercontent.com/69457616/90163341-41621000-dd96-11ea-9f28-79265bfd8ded.png)
> 
> -> have the possibility to modify each channel by applying mathematical functions (offset, gain, filter, gradient, ...), be able to change and save paramters in order to avoid to create new channel each time we would like adjust it. (as 'Insert computation' function does but for each channel). Save such modification parameters in the configuration.
> -> add this functionnality by using right click on a selected channel to avoid it's name research in a list.
> 
> thanks a lot.

There is only so much vertical space available. I'll try to see if something can be done

**Comment by danielhrisca** [comment]
> Yes you're right, it could be great. If possible, set as minimum width the size of bigger channel name.
> in this way, X axis will really be synchronized.

The splitter handles are now connected between the synced sub plots

**Comment by danielhrisca** [comment]
You can now toggle the sub window frame 

![image](https://user-images.githubusercontent.com/20952040/90176024-06210a80-ddb1-11ea-896f-e83b5d0cdd6b.png)

on:
![image](https://user-images.githubusercontent.com/20952040/90175973-f1dd0d80-ddb0-11ea-81c7-8043e88d9558.png)

off:
![image](https://user-images.githubusercontent.com/20952040/90175993-fa354880-ddb0-11ea-9867-b03e7b56d9fc.png)

**Comment by danielhrisca** [comment]
> -> have the possibility to modify each channel by applying mathematical functions (offset, gain, filter, gradient, ...), be able to change and save paramters in order to avoid to create new channel each time we would like adjust it. (as 'Insert computation' function does but for each channel). Save such modification parameters in the configuration.

the computed channels are stored in the configuration file already



> -> add this functionnality by using right click on a selected channel to avoid it's name research in a list.

I've added a new entry in the right click menu, for pre-selecting the channel name

**Comment by danielhrisca** [comment]
> **- a 'full screen' mode** (with keybord shortcut) could be great in order to have the best view of the subplots:
> -> whipe channels list
> -> subplots automatic sizing (fullfil the screen)
> -> subplot channels list adaptation in order to be able to read channel full names

I've added full screen mode using the ``F8`` key

**Comment by gaetanrocq** [comment]
saving configuration is ok now, thanks
