### ISSUE TITLE
(Feature Request?): Remove Channel from MDF File

### ISSUE THREAD

**Issue by white91wolf** [danielhrisca/asammdf#396]
Hey daniel,

i just checked the examples and the API but couldn't find anything for my current problem.
I have a huge amount of signal data and want to reduce this. So i calculate a threshold value for each channel. Each of my mdf files is 20 secs long and if one channel isn't over the threshold value the channel should be removed or each value set to zero or something like that. Removing would be better for the data reduction aspect but i fear the concatenate function wont work after removing channels afterwards, cause the files don't match in the channel structure anymore.

i mean i could access the group and there the channels and delete those out of the channel list like:
```
curMDF = MDF(filepath)
curGroup = curMDF.groups[0]
del curGroup.channels[2]
```

So is there something i could use at the moment or is this something which has to be implemented?
I mean i could create a new mdf file for each of my originals with the edited channels but i don't think this would be really handy nor performant.

greetings

**Comment by danielhrisca** [comment]
It's not clear to me what you want to do. How would it help to set the channel values to 0?

**Comment by white91wolf** [comment]
sorry thats not clear.
i hope if all values will be 0 it should be easier to compress algorithms.. At the moment we also zip the mdf files.

i currently testingt the idea of deleting the channels in the channellist of the group and save the mdf file. but it seems that doesnt deletes the signaldata? Also i will get trouble as soon i want to concatanete the files or?

**Comment by danielhrisca** [comment]
What mdf version are the input files?

**Comment by white91wolf** [comment]
i added some infos in my post before

**Comment by danielhrisca** [comment]
Do you have zipped data blocks in your files?
```python
mdf = MDF(filename)
print(mdf.groups[0].data_blocks)
```

**Comment by white91wolf** [comment]
` DataBlockInfo(address=0xAA2FD8, block_type=0, raw_size=36864, size=36864, param=0, invalidation_block=None, block_limit=None),`

No not jet but i have seen the compression parameter for the save method which will save about 8MB on my ~28MB Files. If its is what you wanted to meantion.

**Comment by danielhrisca** [comment]
> No not yet but i have seen the compression parameter for the save method which will save about 8MB on my ~28MB Files. If its is what you wanted to meantion.

Yes, compression=2 will be the best for file size, but slower then compress=1

**Comment by danielhrisca** [comment]
> i currently testingt the idea of deleting the channels in the channellist of the group and save the mdf file. but it seems that doesnt deletes the signaldata?

Only the medata is loaded in the MDF object, so the actual signal bytes are still kept on disk. To really remove the channel and its samples you have to ``filter`` the file.

**Comment by white91wolf** [comment]
So you have an idea how to even save more data with my calculated thresholds?
I mean im sure i cant remove the channels right now cause i will concatanete the files afterwards when the signals have to be analyzed. Like i got out of the API/Doc:

`Raises: | MdfException:if there are inconsistencies between the files`

So maybe its the way to go to set all values to zero - for beneftis on compression side maybe even inside the MDF save method.

Do you have an idea? Im currently testing but now im getting an invalid MDF after saving. My steps:

curMDF = MDF(filePath)
index = 0
channels = [
                (None, gp_index, ch_index)
                for gp_index, channel_indexes in curMDF.included_channels(index)[
                    index
                ].items()
                for ch_index in channel_indexes
            ]  # stolen from the iter_channels method

selectedChannels = curMDF.select(channels)
curSignal = channels[1]
curSignal.samples[:] = [0] * (len(curSignal.samples))

after saving i get 
![grafik](https://user-images.githubusercontent.com/5691653/89884673-2642a500-dbca-11ea-976f-b42571ebbdff.png)

in the Vector MDF Validator

**Comment by white91wolf** [comment]
> 
> 
> > i currently testingt the idea of deleting the channels in the channellist of the group and save the mdf file. but it seems that doesnt deletes the signaldata?
> 
> Only the medata is loaded in the MDF object, so the actual signal bytes are still kept on disk. To really remove the channel and its samples you have to `filter` the file.

**Comment by white91wolf** [comment]
> e MDF object, so the actual signal bytes are still kept on disk. To really remove the channel and its samples you have to `filter` the file.

Sorry missclicked..

so wow this method seems to be what i need except the part of the later concatenating of multiple files. So my idea is to filter it and then add the filtered signals with just zero values?

**Comment by danielhrisca** [comment]
The filter will onyl remove the signals.

I think this is what you want is to call select with all the channels for each channel group, make your check and set the samples to 0 when needed, and afterwards append the signals to a new MDF.

**Comment by white91wolf** [comment]
Nice the filter method is nice. but i really removes everything of the excluded channels. So as feared the concatenate will raise an exception. But i think i can work with that and add the channels with just a zero signal.

Maybe it would nice to get the feature in the concatenate method with a flag or so to be able to handle such files - in each file iteration check if there are some differences in the group/channel structure and extend it if necessary and set a default value (maybe also a parameter?) for the whole channel before and even after if there are new files without the channels.

But that helps a lot thanks

**Comment by white91wolf** [comment]
Sorry for asking but how the heck can i add a generated signal or signals to an existing group? The append method (https://asammdf.readthedocs.io/en/master/_modules/asammdf/blocks/mdf_v4.html#MDF4.append) is adding a new data group. So the structure is again different and it woulndt be possible to concate - even worse that the timestamps would saved redundant.

I think i have to create the mdf file complettly new even filter wont help cause of that. so i have to extract each signal and add it to a new MDF Object, where i have to copy all the meta infos and so on... thats kinda ugly to handle but i cant think of any other solution

**Comment by danielhrisca** [comment]
The `Signal` objects returned by _get_ and _select_ are decoupled from the raw data blocks.

**Comment by white91wolf** [comment]
> 
> 
> The `Signal` objects returned by _get_ and _select_ are decoupled from the raw data blocks.

That explains the corrupt file after my sample changings. So can you give me an idea how to handle my sample override?

**Comment by danielhrisca** [comment]
pandas might be a good idea maybe:
```python
mdf = MDF(infile)
out = MDF()

for df in mdf.iter_groups():
    # make the checks on the columns
    # set "wrong" columns to 0
    ...
    out.append(df)

out.save('correct.mf4', compression=2)
```

**Comment by white91wolf** [comment]
> 
> 
> pandas might be a good idea maybe:
> 
> ```python
> mdf = MDF(infile)
> out = MDF()
> 
> for df in mdf.iter_groups():
>     # make the checks on the columns
>     # set "wrong" columns to 0
>     ...
>     out.append(df)
> 
> out.save('correct.mf4', compression=2)
> ```
