### ISSUE TITLE
header.start_time is missing fractional seconds

### ISSUE THREAD

**Issue by johnml1135** [danielhrisca/asammdf#397]
Do the MDF files only have the start_date/time down to the second?  When a file is converted from BLF to MDF in CANape, it appears to lop off the fractional seconds of the start time.  Is that true?  If the fractional seconds is there, it is being misunderstood by asammdf.  (possibly could be treating ms as ns).

**Comment by danielhrisca** [comment]
Hello @johnml1135 

I think you have a MDF file with version lower than 3.20

```python
mdf = MDF(file)
print(mdf.version)
```

Before version 3.20 the start time resolution was 1s
