### ISSUE TITLE
Full screen mode fitting

### ISSUE THREAD

**Issue by gaetanrocq** [danielhrisca/asammdf#398]
>- a 'full screen' mode (with keybord shortcut) could be great in order to have the best view of the subplots:
>-> whipe channels list
>-> subplots automatic sizing (fullfil the screen)
>-> subplot channels list adaptation in order to be able to read channel full names

>I've added full screen mode using the F8 key

Fullscreen mode is great but it doesn't optimize the subplots. A free space remains at the bottom.

![fullscreen](https://user-images.githubusercontent.com/69457616/90388046-841e3380-e087-11ea-8e14-d255456b5a07.jpg)

When F8 is activated, some functions doesn't work:
'toggle dots'
all 'tile mode', Ctrl+H, Ctrl+V, Ctrl+T, Ctrl+C

**Comment by danielhrisca** [comment]
I think if you tile the sub windows again they will fill all the space. 

The functionality is not polished enough at the moment.

**Comment by gaetanrocq** [comment]
Ok, I tried but it doesn't work. It seem's that tile functions don't work in full screen mode.

I saw that you added the possibilty to remove the channel list (great) but only by the mouse.
Could it be possible to add a shortcut as L for 'List' to do it automaticaly (and fit the subplots)?
Thanks

**Comment by danielhrisca** [comment]
@gaetanrocq please try the development branch code

**Comment by gaetanrocq** [comment]
Tile option works now in fullscreen mode, thanks.
It remains 2 problems: 
- if we're Vertically tiled and I ask for fullscreen, then the sub-plots don't fit, they're to small -> need to tile again to fit the screen.
- In the same way , if we're in fullscreen with fitted sub-plots, then coming back in normal view, the sub-plots are too big and generate a scrollbar. We need to tile again.

Could it be possible to fit automatically screen when coming to or from fullscreen mode  ?

**Comment by danielhrisca** [comment]
@gaetanrocq 
I've added automatic tiling when stitching the full screen mode, and the "Shift+L" shortcut for toggling the channels list

**Comment by gaetanrocq** [comment]
it works well, thanks !
