### ISSUE TITLE
Grid option behavior

### ISSUE THREAD

**Issue by gaetanrocq** [danielhrisca/asammdf#399]
On development version (22.0.dev17) Grid option doesn't work properly.
If there's no grid and then push 'G', X/Y grid appears,
if push 'G' again X grid remains, then push 'G' again X/Y grid appears.
It will not be possible to switch off grid option.
I expected a circular rotation like : no grid -> X/Y grid -> X grid -> Y grid -> no grid

When X grid is On, Y zoom doesn't work anymore (right click of the mouse).
Only X zoom work.

**Comment by danielhrisca** [comment]
This should work now

**Comment by gaetanrocq** [comment]
it's fine now, thanks
