### ISSUE TITLE
Hi, I tried the export to csv function and I get the error "generator' object is not subscriptable". the MDF4 file has a data channel group.

### ISSUE THREAD

**Issue by livias** [danielhrisca/asammdf#40]
Please write here the output of printing ``sys.version``

# Platform information
Please write here the output of printing ``platform.platform()``

# _asammdf_ version
Please write here the output of printing ``asammdf.__version__``

# Description
Please describe the issue here.

**Comment by danielhrisca** [comment]
Hello,

I'll have a look in a couple of hours. 

Could you also show the error trace back? (I should include this in the issue template as well)

**Comment by livias** [comment]
Hi Daniel,
cycles_nr = len(data[0]) // grp['channel_group']['samples_byte_nr']
TypeError: 'generator' object is not subscriptable



    On ‎Monday‎, ‎February‎ ‎12‎, ‎2018‎ ‎04‎:‎37‎:‎59‎ ‎PM‎ ‎EET, Daniel Hrisca <notifications@github.com> wrote:  
 
 
Hello,

I'll have a look in a couple of hours.

Could you also show the error trace back? (I should include this in the issue template as well)

**Comment by danielhrisca** [comment]
Hello,

please try the code in the _development_ branch https://github.com/danielhrisca/asammdf/commit/1dbac73b62715463bb74ad5a770ef272d9e6a65a

**Comment by danielhrisca** [comment]
Hello,

this issue should be fixed in the new release code.

Please upgrade _asammdf_:

``pip install -U --no-deps asammdf``

and see if it works for you.

**Comment by livias** [comment]
Solved, thank you.
