### ISSUE TITLE
You can now toggle the sub window frame

### ISSUE THREAD

**Issue by gaetanrocq** [danielhrisca/asammdf#400]
You can now toggle the sub window frame 

![image](https://user-images.githubusercontent.com/20952040/90176024-06210a80-ddb1-11ea-896f-e83b5d0cdd6b.png)

on:
![image](https://user-images.githubusercontent.com/20952040/90175973-f1dd0d80-ddb0-11ea-81c7-8043e88d9558.png)

off:
![image](https://user-images.githubusercontent.com/20952040/90175993-fa354880-ddb0-11ea-9867-b03e7b56d9fc.png)

_Originally posted by @danielhrisca in https://github.com/danielhrisca/asammdf/issues/393#issuecomment-673657042_

**Comment by gaetanrocq** [comment]
This function is great. Graphic areas are well optimized !
Only problem is that it is no longer possible to use it when channel list is closed.
Could it be possible to add it in 'Settings' tab with a shortcut ?

Same remark concerning 'load configuration' and 'save configuration' buttons.
They're no longer available when channel list is closed.
Maybe add them in 'File' tab could be usefull.
It seems logical because when we work with acquisitions we always do 2 things:
 - 1 -> choose the data flie(s)
 - 2 -> choose or edit a configuration in order to analyse these datas

We could first choose a configuration and apply several data files or the opposite.
Acquisition datas and configurations are two separate things.
Thanks a lot !

**Comment by danielhrisca** [comment]
@gaetanrocq please try the development branch code

**Comment by gaetanrocq** [comment]
perfect !
