### ISSUE TITLE
Export function doesn't work in version 5.22.0.dev17

### ISSUE THREAD

**Issue by gaetanrocq** [danielhrisca/asammdf#402]
hi, nothing happen when trying to use export function from MF4 to mat file. (no .mat file, no error)
Strangely, it's working well with 5.19.3 version

tried with this file:
[dhsrgesrg.zip](https://github.com/danielhrisca/asammdf/files/5104823/dhsrgesrg.zip)

**Comment by danielhrisca** [comment]
Maybe you don't have scipy or hdf5storage installed

**Comment by gaetanrocq** [comment]
.mat conversion seems to work now with scipy, thanks.
