### ISSUE TITLE
[GUI] Color of the individual Y-axis not updated

### ISSUE THREAD

**Issue by Carlos-DM** [danielhrisca/asammdf#403]
# Python version
```
('python=3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.1'
'asammdf=5.21.0'
```

# Description
In the GUI, when creating a plot, it is possible to change the color of a channel. However, the color of the individual Y-axis of that channel (if enabled to be shown) is not changed. It is shown in the color that asammdf first decided to draw that channel.
![image](https://user-images.githubusercontent.com/70007398/90863614-a4a00380-e38f-11ea-9831-f7a09f32dbfb.png)

**Comment by danielhrisca** [comment]
I think this is solved in the development branch code

**Comment by danielhrisca** [comment]
@Carlos-DM this is fixed now in development

**Comment by Carlos-DM** [comment]
> @Carlos-DM this is fixed now in development

Thanks a lot. :-)
