### ISSUE TITLE
Function "get_can_signal" payload conversion is not working in specific case

### ISSUE THREAD

**Issue by tobiasandorfer** [danielhrisca/asammdf#409]
# Python version
'python=3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.17763-SP0'
'numpy=1.16.5'
'asammdf=5.22.0'

  ## MDF version
  _V4

  ## Code snippet  
![image](https://user-images.githubusercontent.com/64536839/92710395-0bde2180-f358-11ea-8f82-7191fd537a82.png)

# Description

Hello Daniel, 

first thanks for the amazing work!
When I use the "get_can_signal" funktion in asammdf version 5.22.0 the conversion (factor and offset) is not working.
I followed the code to the point of the screenshot in the posted code snippet.

In my case the CAN signal I tryed the "get_can_signal" function on has a value description shown in the screenshot, so the "if signal.values:" part of the code is active. 
You lost me with what is happening there :-) but when i force the "else:" part the conversion with factor and offset workes, also the init values are worked out of the return vals.
Could it be as easy as copying line 153 up to 150?

I think it is awesom that the "get_can_signal" function is now calculating the physical values of a CAN signal since this is my usecase most of the time. But in some cases i actually need the raw value. It would be very nice if the function "get_can_signal" would get a "raw=True/False" parameter just like the "get_signal" funktion.

many thanks and greetings
Tobias

**Comment by danielhrisca** [comment]
Hello Tobias,

is it possible to send the dbc file?

**Comment by tobiasandorfer** [comment]
Hello Daniel,

unfortunately i cant send the dbc file since it is a Automotive OEM file from our customer.

But I think you are right to suspect the error in the dbc file.
I made a test with a dbc File from our Lab that I created my self and there it works as expected
I´ll try to spot a differenc in both dbc files and let you know what I come up with.








Von: Daniel Hrisca <notifications@github.com>
Gesendet: Freitag, 11. September 2020 12:40
An: danielhrisca/asammdf <asammdf@noreply.github.com>
Cc: Andorfer Tobias EC632 <Tobias.Andorfer@draexlmaier.com>; Author <author@noreply.github.com>
Betreff: Re: [danielhrisca/asammdf] Function "get_can_signal" payload conversion is not working in specific case (#409)


Hello Tobias,

is it possible to send the dbc file?

**Comment by tobiasandorfer** [comment]
Hello Daniel,


For me it look like a value table makes the difference.
When I added a value table to my Test.


“Ok 10 minutes later I realize…. :-)”


no surprise :-) cause then you go down this road

[cid:image001.png@01D68845.EAED9CD0]


Could it be that you look for the factor and offset given by the mdf file itself?
When actiulally the values form the dbc file would be needed?

[cid:image002.png@01D68846.12F82970]


Greetings Tobias

Von: Daniel Hrisca <notifications@github.com>
Gesendet: Freitag, 11. September 2020 12:40
An: danielhrisca/asammdf <asammdf@noreply.github.com>
Cc: Andorfer Tobias EC632 <Tobias.Andorfer@draexlmaier.com>; Author <author@noreply.github.com>
Betreff: Re: [danielhrisca/asammdf] Function "get_can_signal" payload conversion is not working in specific case (#409)


Hello Tobias,

is it possible to send the dbc file?

**Comment by danielhrisca** [comment]
please print the ``signal`` variable to see how it looks

**Comment by tobiasandorfer** [comment]
![image](https://user-images.githubusercontent.com/64536839/92926383-3a352d00-f43c-11ea-9841-e3906ed07fee.png)

**Comment by danielhrisca** [comment]
can you also show the Value description tab from the signal pop-up window?

**Comment by tobiasandorfer** [comment]
![image](https://user-images.githubusercontent.com/64536839/92927127-68ffd300-f43d-11ea-8a11-9299a49404e9.png)
(table is not matchin the signal i just picked one for testing)

**Comment by danielhrisca** [comment]
I'm not sure how to handle this signal: 
* there is obviously a conversion formula from the raw value (voltage in mV) to the physical value (voltage in V)
* After this we have the value to text table conversion; If we furter try to use the conversion table we would most likely get "Unknown" values since it is less likely that the voltage value will be exactly equal to the table values.

**Comment by tobiasandorfer** [comment]
Until now i had 2 usecases:

1.	I need a physical value for statistical analysis and I dont want the values form the conversion table to mess up the calculation > so I need the values from the conversion table replaced with “nan” (I did that in a postprossessing after loading the signal)

2.	I want to check some state from the conversion table (but still use numpy funktions) > I used the raw parameter from the get() function (In this case it was a signal oriented mdf file, not a CAN frame format)


For my first usecase I was calculating the factor and offset to the values from the conversion table like this, so i can change them into "nan" afterwards:
![image](https://user-images.githubusercontent.com/64536839/92930776-cfd3bb00-f442-11ea-91f4-59dabd248dea.png)

I guess it would be more efficient to singel out the values from the conversion table before and then apply factor and offset to the rest of the "physical" values.

**Comment by danielhrisca** [comment]
Please try the development branch code

**Comment by tobiasandorfer** [comment]
I think you are right regarding the partial conversion

I get an error with the dev branch:
![image](https://user-images.githubusercontent.com/64536839/92933789-fa277780-f446-11ea-96e5-b41d3aa53766.png)

**Comment by danielhrisca** [comment]
Put conv=from_dict(conv) just before the error line

**Comment by tobiasandorfer** [comment]
works :-) 

![image](https://user-images.githubusercontent.com/64536839/92934638-052ed780-f448-11ea-915b-8a25aedec953.png)

thank you for the time and effort!!!

**Comment by danielhrisca** [comment]
What is wrong with the current `raw` argument?

**Comment by tobiasandorfer** [comment]
there is no raw argument in the "get_can_signal" function right now

![image](https://user-images.githubusercontent.com/64536839/92938800-57262c00-f44d-11ea-9328-e14f77bfa016.png)

**Comment by tobiasandorfer** [comment]
mdf_v4.py at least, thats the only one I use :-)

**Comment by danielhrisca** [comment]
I see, I have no problem if you go ahead and submit a PR
