### ISSUE TITLE
Cannot find channel's name with '\\'

### ISSUE THREAD

**Issue by dglent** [danielhrisca/asammdf#41]
Hello,

I read a mdf3 file (.dat) from inca
I have the dictionary with the channels and when i want to get a channel it is impossible to find it because of the slashes in the name.
eg:
{'ACC\\CCP:1': [(4, 1)], 'Pwt\\CCP:1': [(7, 1)], 'GearCord\\CCP:1': [(8, 1)], '$EVENT_COMMENTS': [(9, 1)], '$PAUSE_COMMENTS': [(10, 1)], '$SNAPSHOT': [(11, 1)]}

mdffile.get(''ACC\\CCP:1') cannot be found as it searches for 'ACC' and not for 'ACC\\CCP:1'

https://github.com/danielhrisca/asammdf/blob/ff38f5ae069e3a4ca00e6d0583eaa3d0ee01419a/asammdf/mdf_v3.py#L591

**Comment by danielhrisca** [comment]
Hello Dimitrios,

I've made a few fixes in the development branch. Please check if it fixes your problem.

**Comment by danielhrisca** [comment]
Starting with this commit https://github.com/danielhrisca/asammdf/commit/a715c5c92a28cf733ff41550ac197231c879be0a, for MDF version 3 the channels_db will contain the full name including the source path (backslash and everything after it) but also the short name without the it.

 The display name gets the same treatment (for example using an ETAS thermocouples device with Vector CANape the channel names were always _THxx_ and the user defined name was stored in the display name field).

**Comment by dglent** [comment]
I copy only the file mdf_v3.py of the development branch in my system.
I have this error:
line 3403, in get
    display_name=display_name,
TypeError: __init__() got an unexpected keyword argument 'display_name'

**Comment by danielhrisca** [comment]
You should copy all files or  execute
``pip install -I --no-deps https://GitHub.com/danielhrisca/asammdf/archive/development.zip``

**Comment by dglent** [comment]
I installed the development branch and it is ok now
Thanks

**Comment by danielhrisca** [comment]
The fix in now included in the 3.1.0 release
