### ISSUE TITLE
Add Source Path in Channel Name

### ISSUE THREAD

**Issue by wakille** [danielhrisca/asammdf#411]
Hey there,

it would be nice if I could use the source path as part of the channel name when exporting data. I need it because I have channels with the same names but meassured on different busses. To be able to seperate them it would be very useful to have the source path. 

Even if you are not planing to include this feature, could you please give me a code snippet how to change the lib code so I can realize this feature ? 

Thanks a lot!

**Comment by danielhrisca** [comment]
can you share the channel info dialog? (double click the channel in the selection tree)

example:
![image](https://user-images.githubusercontent.com/20952040/93180087-4fad9e00-f73f-11ea-8469-98baf967c811.png)

**Comment by danielhrisca** [comment]
ping @wakille
