### ISSUE TITLE
Method save not working when adding display_names to channels

### ISSUE THREAD

**Issue by wakille** [danielhrisca/asammdf#414]
# Python version
('python=3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.19.1'
'asammdf=5.22.0'

# Code 

  ## MDF version
'4.10'

  ## Code snippet
for signal in found_signals[signal_id]:
    group_index, channel_index = signal[2]
    mdf_obj.groups[group_index].channels[channel_index].display_name = signal_names[signal_id]
mdf_obj.save(join(path, file_name), True)

  
  ## Traceback
 Traceback (most recent call last):
  File "XXX/DataFileMF4.py", line 151, in <module>
    mdf.filter_and_save(search, names, "XXX\\MessFiles", False)
  File "XXX/DataFileMF4.py", line 46, in filter_and_save
    mdf_obj.save(join(path, file_name), True)
  File XXX\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 8614, in save
    address = channel.to_blocks(
  File "XXX\venv\lib\site-packages\asammdf\blocks\v4_blocks.py", line 954, in to_blocks
    display_name_element.text = display_name or ""
AttributeError: 'NoneType' object has no attribute 'text'
  
# Description
 I filter the signals of a mdf file and try to apply some display name to these signals, but when I save the file, this error occures. The signals dont have a display_name before.

**Comment by danielhrisca** [comment]
@wakille please try the development branch code

**Comment by wakille** [comment]
Ok, thanks. I cant try the development branch at the moment, but I applied the fix by hand. Now it is possible to execute the method, but the attribute display_name is not safed. If I reload the mdf, the display_name is ""

**Comment by danielhrisca** [comment]
Do you load the saved file or the original file?

**Comment by wakille** [comment]
I filter the orignal file, add the display names and save it to a new file. If I load the new_file, the display names arent there

**Comment by danielhrisca** [comment]
did you provide the argument for loading the display names? By default it is off.

```python
mdf = MDF(filename, use_display_names=True)
```
