### ISSUE TITLE
Method save does not update obj.name

### ISSUE THREAD

**Issue by wakille** [danielhrisca/asammdf#415]
# Python version
('python=3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.19.1'
'asammdf=5.22.0'

# Code 

  ## MDF version
'4.10'

  ## Code snippet
data_file_filtered = self.data_file.filter(filter_signals)
data_file_filtered.save(join(path, file_name), True)
print(data_file_filtered.name)

Output: new.mf4

  
# Description
 I filter the signals of a mdf file and save the filtered object, the name attribute does not update. It keeps the path 'new.mf4' and I have to reload the file with MDF(new_path) to update this attribute. In my opinion it should update the name attribute, if I save the obj.

**Comment by danielhrisca** [comment]
@wakille I'll do this only for files created from scratch

**Comment by danielhrisca** [comment]
@wakille it should work now
