### ISSUE TITLE
Wrong samples

### ISSUE THREAD

**Issue by 0815us3r** [danielhrisca/asammdf#416]
# Python version
'python=3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.17763-SP0'
'numpy=1.19.1'
'asammdf=5.21.0'

  ## Code snippet
mdf_obj = asammdf.blocks.mdf_v4.MDF4(name=filepath, version='4.10')
current_obj = mdf_obj.get_can_signal('current',database=dbc)
  

# Description
with Version 5.21.0 I'm recieving the right samples of the signal
with Version 5.22.0 I'm reciving wrong samples

**Comment by danielhrisca** [comment]
@0815us3r can you try with the development branch code?

some details would also be welcomed: 
* a print of the values returned with the two asammdf versions
* the print of the Signal object loaded by canmatrix here https://github.com/danielhrisca/asammdf/blob/3f86782c34bc2aa472a12692fa4c9df20d69e798/asammdf/blocks/bus_logging_utils.py#L141

```python 
    print(signal)
    print(vals)
```

**Comment by danielhrisca** [comment]
ping @0815us3r

**Comment by danielhrisca** [comment]
@0815us3r please try with version 6.0.0
