### ISSUE TITLE
Incorrect decoding using asammdf.mdf.MDF.extract_can_logging

### ISSUE THREAD

**Issue by romans-safonovs** [danielhrisca/asammdf#417]
# Python version
python=3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
os=Windows-10-10.0.17763-SP0
numpy=1.19.2
asammdf=5.22.0

# Code 

  ## MDF version
  4.10

  ## Code snippet
  ```python
  from asammdf import MDF

  mdf4_path = 'path/to/mdf4_file.mf4'
  dbc_path = 'path/to/dbc_file.dbc'

  mdf4 = MDF(mdf4_path)
  mdf4 = mdf4.extract_can_logging([dbc_path])
  ```
  
# Description
We have discovered an issue when decoding data using `asammdf.mdf.MDF.extract_can_logging`. If a DBC file contains any *values* for a certain signal (end up in `signal.values`), then `asammdf.blocks.bus_logging_utils.extract_signal` will construct the `conv` dictionary using `signal.values`, but `conv` will be redefined immediately after by `conv = {'a': 1.0, 'b': 0.0}`:
```python
...
if signal.values:
    conv = {}

    for i, (val, text) in enumerate(signal.values.items()):
        conv[f'upper_{i}'] = val
        conv[f'lower_{i}'] = val
        conv[f'text_{i}'] = text

    conv = {'a': 1.0, 'b': 0.0}

else:
    conv = {'a': float(signal.factor), 'b': float(signal.offset)}
...
```
This results in signals that have *values* in their DBC file (`VAL_`) not being decoded correctly - without translation to text and correct factor or offset.

**Comment by danielhrisca** [comment]
Please try the development branch code

**Comment by romans-safonovs** [comment]
Thank you for swift response! I have tried it and get correct results, the issue is solved. Any idea on when will this be available on PyPi?

**Comment by danielhrisca** [comment]
new release 5.23.0
