### ISSUE TITLE
 xlsxwriter not found; export to Excel unavailable

### ISSUE THREAD

**Issue by livias** [danielhrisca/asammdf#42]
# Python version
_Please write here the output of printing ``sys.version``_ 3.6.3

# Platform information
_Please write here the output of printing ``platform.platform()``_

# _asammdf_ version
_Please write here the output of printing ``asammdf.__version__``_3.1.0

# Code 

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _pleaase write here the error traceback_
  
# Description
_Please describe the issue here._

**Comment by danielhrisca** [comment]
_xlsxwriter_ is not a hard dependency.

You just have to install it from PyPI:

``pip install xlsxwriter``

What about issue #40? Is it fixed with _asammdf 3.1.0_?

**Comment by livias** [comment]
Thanks. Issue #40 is ok now.

**Comment by livias** [comment]
No error at xlsx conversion, but the files are empty/no data.

**Comment by danielhrisca** [comment]
Hello livias,

can you elaborate a bit? 
I guess you have installed _xlsxwriter_, and after the conversion you get empty xlsx files?

**Comment by livias** [comment]
Hi, 
Yes, installed. With different mdf4 files, to csv was ok [but with Tab delimiter instead of ;], but to xlsx results and empty file with one sheet named "sheet 1".

**Comment by danielhrisca** [comment]
Hello,

there was a bug indeed in the excel export option.

 

> xlsx results and empty file with one sheet named "sheet 1"

It should be fixed with this commit in the development branch https://github.com/danielhrisca/asammdf/commit/f3a048027674ffce8fac16f5c176007df52e9cda. Please check if it works for you as well.

> csv was ok [but with Tab delimiter instead of ;]

The _csv_ delimiter is set to _";"_ and in my test this is used instead of TAB

**Comment by livias** [comment]
Thanks for rapid answer and solution. I'll check it now.

Indeed, but the csv has to be post-processed to read the data, i.e. Convert text-> Column. So maybe it should be TAB delimiter...

**Comment by livias** [comment]
A question not quite related to this issue, but I don't know where to put it..sorry.
Is asammdf supporting MDF4 compressed data? Thanks

**Comment by danielhrisca** [comment]
> Is asammdf supporting MDF4 compressed data?

Short answer: yes

 A good place to start is the documentation http://asammdf.readthedocs.io/en/master/intro.html#features

Regarding the delimiter I've removed the _";"_ delimiter and now comma is used by default (don't remember why I've set it in the first place). You can open the csv files with LibreOffice or Excel and the columns will be properly displayed

**Comment by livias** [comment]
I updated to 3.2.0 and the result is the same, empty xlsx file.

**Comment by livias** [comment]
And the csv has ; as a delimiter.
It should be asammdf 3.2.0 version, isn't it?

**Comment by danielhrisca** [comment]
pip install -I --no-deps https://GitHub.com/danielhrisca/asammdf/archive/development.zip

3.2.0 means that you are using the latest release from master

Latest development is 3.2.1dev

**Comment by livias** [comment]
Thanks!

Trimis din Yahoo Mail pe Android 
 
  Pe vin., mar. 2, 2018 la 18:07, Daniel Hrisca<notifications@github.com> a scris:   
pip install -I --no-deps https://GitHub.com/danielhrisca/asammdf/archive/development.zip

3.2.0 means that you are using the latest release from master

Latest development is 3.2.1dev

**Comment by livias** [comment]
Well done!  Thank you for your responsiveness. I hope to use asammdf so no effort is useless!

**Comment by danielhrisca** [comment]
Thank you for pointing out the bugs.

**Comment by livias** [comment]
Regarding the license agreement, how can asammdf can be used in other applications?
Thanks.Livia

Trimis din Yahoo Mail pe Android 
 
  Pe lun., mar. 5, 2018 la 15:00, Daniel Hrisca<notifications@github.com> a scris:   
Thank you for pointing out the bugs.

**Comment by danielhrisca** [comment]
When I initially chose the license I did not look thoroughly. What I meant was more towards the LGPL3 license: use the library freely and share back the changes you make. I will change the license tonight.
