### ISSUE TITLE
Question: Support for Vector System Variables etc.

### ISSUE THREAD

**Issue by mikesmitti** [danielhrisca/asammdf#420]
Hi there,

are Vector system variables, environment variables etc supported?
How to get access to them? (do i have to create a .dbc? ...)
Do you have an example?

Thanks and best regards,
Mike

**Comment by danielhrisca** [comment]
Aren't those saved as regular channels in the output file?

**Comment by mikesmitti** [comment]
Actually I don´t know, but I found this article:

https://kb.vector.com/entry/520/


I tried to process systemvariables the same way like CAN Signals and that did not work as expected -> I did not get a plot.

asammdf 5.21.00
mdf 4.10

Functions:
Mdf(file)
extract_can_logging(dbc...)
select(systemvariables)
plot(signals2plot)

Do I have an error here, for processing the variables?
I have to use the extract_can_logging, since the dbc aren´t in the same place as saved in the mf4-file.

Best regards

**Comment by danielhrisca** [comment]
In my files the sysvars are stored as regular channels:

![image](https://user-images.githubusercontent.com/20952040/94117043-6f864580-fe54-11ea-95de-6538a363b05f.png)

but the channel name and the sysvar names are not really consistent

![image](https://user-images.githubusercontent.com/20952040/94117332-c12ed000-fe54-11ea-99e1-bc1f7f65741d.png)

**Comment by mikesmitti** [comment]
Good, I got similar results.

I tried to do some plotting with the original file:
signal = self._mf4file.select("SYS_varx")
plot(signal)

there I get a MdfException
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.21.0-py3.7-win32.egg\asammdf\blocks\mdf_v4.py", line 1765, in _validate_channel_selection
    raise MdfException(f'Channel "{name}" not found')
asammdf.blocks.utils.MdfException: Channel "S" not found

Sounds reasonable to me, since the Sysvars are in no dbc
Did you try plotting a SysVar? Does that work?

However, after using extract_can_logging() the systemvariables seem to be lost.
Sounds reasonabel, too , since the variables are not in a dbc.

**Comment by danielhrisca** [comment]
the argument to the `select` method is a list

you can do 

```python
signal = mdf.get("SYS_varx")
```

or

```python
signal = self._mf4file.select(["SYS_varx"])
```

**Comment by mikesmitti** [comment]
Thank you, that works in the first case. 

But doing so with the data generated by the extract_can_logging() generates the exception as mentioned above.
It is reasonable, since the singals are in no dbc.

Is there any possibility to copy the Systemvariables with this method?

In my case, to use both signals and variables, i would have to distinguish between signals and variables and look either in the original data for the variables or in the extract_can_logging data for the signals

**Comment by danielhrisca** [comment]
one quick solution would be to concatenate the files

```python
mdf = MDF(filename)
can_extract= mdf.extract_can_logging([dbc])

complete = MDF.stack([mdf, can_extract])

ch1 = complete.get('SYS_varx')
ch2 = complete.get(some_bus_signal)

```

**Comment by mikesmitti** [comment]
Thx, that works for now.

Is there any plan to implement copying of systemvariables with extract_can_logging?
Or, prefered by me, to integrate the dbc, arxml, etc in the Mdf() Method?

I do the extract_can_logging(), because the databases are not in the same path as during logging of the file.
Then I don´t find any signal with the select() method. It raises the exception as mentioned above.
With the extract_can_logging() it works. 

Best regards

**Comment by mikesmitti** [comment]
For my understanding:
When using the stack-method, the file keeps in memory until i save it to hard-disk.
When processing huge files, it is good practice to save the stacked files to disk and then reopen the stacked file.
May save memory?

Best regards

**Comment by danielhrisca** [comment]
This is not what happens: we keep only the metadata in memory. The channel samples are always streamed to disk.
