### ISSUE TITLE
Support for non-sequential value-to-text signal conversion

### ISSUE THREAD

**Issue by hudsonft** [danielhrisca/asammdf#425]
# Python version
```
('python=3.6.9 (default, Jul 16 2020, 14:41:49) \n'
 '[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]')
'os=Darwin-18.7.0-x86_64-i386-64bit'
'numpy=1.19.0'
'asammdf=5.21.0'
```

# Code 

  ## MDF version
  4.10

  ## Code snippet
```python
 In [33]: from asammdf import MDF, Signal

In [34]: mdf = MDF(version= "4.10")

In [35]: conversion = {
    ...:  'text_3': "enum_three",
    ...:  'val_3': 3,
    ...:  'text_1': "enum_one",
    ...:  'val_1': 1,
    ...:  'text_0': "enum_zero",
    ...:  'val_0': 0}

In [36]: new_signal = Signal(
    ...:     samples=np.array([0, 1, 2, 3], dtype=np.uint64),
    ...:     timestamps=np.array([0.0, 0.1, 0.2, 0.3]),
    ...:     name="my_enumerated_signal",
    ...:     conversion = conversion
    ...: )

In [37]: mdf.append(new_signal)
Out[37]: 0

In [38]: mdf.save("my_new_mdf.mf4")
Out[38]: PosixPath('my_new_mdf.mf4')

In [39]: loaded_mdf = MDF("my_new_mdf.mf4")

In [40]: loaded_mdf.get("my_enumerated_signal")
Out[40]:
<Signal my_enumerated_signal:
	samples=[b'enum_zero' b'enum_one' b'' b'']
	timestamps=[0.  0.1 0.2 0.3]
	invalidation_bits=None
	unit=""
	conversion=None
	source=<asammdf.blocks.source_utils.Source object at 0x1192f1c78>
	comment=""
	mastermeta="('time', 1)"
	raw=False
	display_name=
	attachment=()>
  ```
# Description
The example above demonstrates that the value-to-text conversion mode (CONVERSION_TYPE_TABX) only supports continuous enumerations: the converted value given for samples corresponding to raw values 2 and 3 are both `b''`, while I would expect this to be the case only for raw value 2 (since 3 is included in the conversion dict). 

 At first glance the relevant code is [here](https://github.com/danielhrisca/asammdf/blob/c3ea7216eae150e86156e6d4c7dcfeb98507ccc7/asammdf/blocks/conversion_utils.py#L313-L317) and [here](https://github.com/danielhrisca/asammdf/blob/c3ea7216eae150e86156e6d4c7dcfeb98507ccc7/asammdf/blocks/conversion_utils.py#L223-L225). Is this expected behavior? Is the constraint for continuous enumeration values inherent in the mdf spec?

It would be useful for me to be able to use non-continuous enumerations, I am willing to contribute the fix if someone can confirm that this my desired behavior is valid. I don't see how it it could break any existing code to support discontinuous enums so backwards compatibility shouldn't be an issue. 

Thanks!
(edited for spelling)

**Comment by danielhrisca** [comment]
Hello @hudsonft you should have continuously increasing dict keys `text_X`. So in your case the last keys should be `val_2` and `text_2`

**Comment by hudsonft** [comment]
Hi @danielhrisca, thanks for the quick response! My application has non-continuous enumerations, so I would benefit from being able to use non-continuously increasing dict keys (thus this ticket). Or are you alluding to some reason that asammdf _should not_ support non-continuous enumerations? I don't know of any constraints on continuity for MDF signals so I am confused by this constraint on conversions in asammdf. Apologies if I missed something in the asammdf spec or documentation about this, and thanks for your time.

**Comment by hudsonft** [comment]
Looks good, thanks for the help.

**Comment by yangyixizg** [comment]
Thank you, finally find the confirmation that the value-text-pairs have to be continuously increased.
I am using the tabular value to text conversion, conversion_type 7. In my case, I have enums which are not continuously increasing, so I had to add the 'missing' value-text-pairs to my enums to show my results in the mf4 file correctly.
