### ISSUE TITLE
API entries refactoring proposition

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#426]
Hi Daniel,

I would like to suggest here a refactoring for the API entries. If you agree with them, I will do the implementation.

# whereis

I think `get()` should do only one thing and not evolve into a channel finder, which started to happen with the introduction of the argument `source`. I propose that `whereis()` takes care of this.

Before: whereis(channel)
After: whereis(cn_name, acq_name=None, acq_source=None)

# get

Now that `whereis()` is taking care of finding a channel for the user, we can remove the `source` argument from `get()`.

Before: get(name=None, group=None, index=None, raster=None, samples_only=False, data=None, raw=False, ignore_invalidation_bits=False, source=None, record_offset=0, record_count=None)
After: get(name=None, group=None, index=None, raster=None, samples_only=False, data=None, raw=False, ignore_invalidation_bits=False, record_offset=0, record_count=None)

> other functions like select(), filter() and so on will also see the argument `source` go away.

-------

These changes make things like this feasible:

```python
from asammdf import MDF

mdf = MDF("my_file.mf4")
occurences = mdf.whereis("my_channel_name", acq_name="my_ecu_name")
nb_occurences = len(occurences)
if nb_occurences == 1:
    cg_idx, cn_idx = occurences[0]
    signal = mdf.get(group=cg_idx, index=cn_idx) 
else:
    raise ValueError(f"{nb_occurences} channel{'s' if nb_occurences > 1 else ''} found (expected 1)")
```

**Comment by danielhrisca** [comment]
Hello Julien,

I have to see how  this impacts the code base.

**Comment by JulienGrv** [comment]
Ok, let me know as soon as you decided

**Comment by danielhrisca** [comment]
@JulienGrv what do you think about the current state?

**Comment by JulienGrv** [comment]
Hi @danielhrisca 

I'd prefer to have acq_source and acq_name instead of source in whereis(). Eventually group could be specified as well. It's just because people may have signal with identical names but in different groups or from different acquisition source so I thought it would be nice that whereis() helps the user to find his signal in an easy and reliable way instead of putting this in get(), filter(), ... which I think could become messy in the long term.

**Comment by JulienGrv** [comment]
Ultimately, the _validate_channel_selection() will become useless inside get() as whereis() must be used to avoid ambiguous channel name. I don't like the idea that we get() returns the first found channel in case of ambiguity. In fact, I know users of asammdf who thought they were using the correct channel because they ignore the multiple occurences warning. I think it would be best to raise an exception and suggest users should use whereis().

**Comment by JulienGrv** [comment]
I am aware that it is a major changes, that's why I am suggesting this now before you release version 6.

**Comment by danielhrisca** [comment]
> the _validate_channel_selection() will become useless inside get()

I think the function is still needed since most users will not use `whereis` 



> I don't like the idea that get() returns the first found channel in case of ambiguity. In fact, I know users of asammdf who thought they were using the correct channel because they ignore the multiple occurences warning. I think it would be best to raise an exception and suggest users should use whereis() beforehand.

Let's see how this goes. I've changed the code such that an exception will be triggered if the selection is ambiguous.

**Comment by JulienGrv** [comment]
Thank you for this addition!

I am confident that this is the safest way. asammdf is used for data science (KPI, and so on) so returning a random channel could potentially have bad consequences if the user overlooks or ignores the warning.

**Comment by danielhrisca** [comment]
Anything else to add here?

**Comment by JulienGrv** [comment]
Please see pull request #446
