### ISSUE TITLE
Provide an Anaconda package on conda-forge

### ISSUE THREAD

**Issue by fkohlgrueber** [danielhrisca/asammdf#43]
Hi,

I'm using `conda` for managing the dependencies of my projects and would like to ask if you'd be interested in providing a conda package of `asammdf`. I'm relatively new to creating conda packages, but it seems like the process is pretty straight-forward if the package is on PyPI already (see [here](https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html)). Having `asammdf` available on [conda forge](https://conda-forge.org/#page-top) and being able to install it by a simple `conda install asammdf -c conda-forge` would be great!

What do you think? I could start working on this, but I wanted to ask for your opinions first.

Thanks in advance!

**Comment by danielhrisca** [comment]
Hello Felix,
 
I have no experience with Anaconda and conda packages. 

Let's see if we can make this work.

**Comment by danielhrisca** [comment]
I've started to build some conda packages using Ubuntu (easier then under windows).

**Comment by danielhrisca** [comment]
The rst description looks bad but the packages are now available.

Could you try an install to verify if they are ok?

https://anaconda.org/daniel.hrisca/asammdf

**Comment by fkohlgrueber** [comment]
I just checked it using Python 3.6 on Windows x64 and it works perfectly! Thanks very much. 

Having it available on conda-forge would be even better. Could you submit your recipe to conda-forge (see [here](https://conda-forge.org/#add_recipe))?

**Comment by danielhrisca** [comment]
Waiting for the recipe to be merged:

https://github.com/conda-forge/staged-recipes/pull/5251

**Comment by danielhrisca** [comment]
The package is now available on conda forge.

Great support from @isuruf !

**Comment by fkohlgrueber** [comment]
Great, thanks a lot!
