### ISSUE TITLE
Insert Computation results in wrong datatype

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#431]
[Asammdf_Bugreport_Computation.scrambled.zip](https://github.com/danielhrisca/asammdf/files/5438899/Asammdf_Bugreport_Computation.scrambled.zip)

# Python version
('python=3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.18362-SP0'
d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
d:\software\wpy-3710\python-3.7.1.amd64\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)
'numpy=1.17.2'
'asammdf=5.23.1'

# Code 

  ## MDF version
4.10

# Description

Hello,
adding e.g. a multiplication leads to wrong calculated values.

**Comment by danielhrisca** [comment]
Hello @stlweb 

please try the development branch code

**Comment by stlweb** [comment]
With the development version, it worked fine.
Thanks
