### ISSUE TITLE
CAN Signal Creation

### ISSUE THREAD

**Issue by puregame** [danielhrisca/asammdf#435]
I would like to save a MF4 file using CAN data imported from another source, is there any way currently to create or modify a Signal object to store imported CAN data from external sources?

If not is this on the roadmap?

Thank you

**Comment by danielhrisca** [comment]
Hello Matthew,

there is a bit of work to add a signal from CAN logging: there is a strict naming rule for the field names and also the channel source has to be set up correctly

```python
import numpy as np
from asammdf import MDF, Signal
from asammdf.blocks.source_utils import Source
import asammdf.blocks.v4_constants as v4c

DTYPE = np.dtype(
    [
        ("CAN_DataFrame.BusChannel", "<u1"),
        ("CAN_DataFrame.ID", "<u4"),
        ("CAN_DataFrame.IDE", "<u1"),
        ("CAN_DataFrame.DLC", "<u1"),
        ("CAN_DataFrame.DataLength", "<u1"),
        ("CAN_DataFrame.DataBytes", "(8,)u1"),
        ("CAN_DataFrame.Dir", "<u1"),
        ("CAN_DataFrame.EDL", "<u1"),
        ("CAN_DataFrame.BRS", "<u1"),
        ("CAN_DataFrame.ESI", "<u1"),
    ]
)

arrays = [
    np.ones(5, dtype='u1'),
    np.arange(5, dtype='<u4'),
    np.zeros(5, dtype='u1'),
    np.full(5, 8, dtype='u1'),
    np.full(5, 8, dtype='u1'),
    np.frombuffer(b'DEADBEEF' * 5, dtype='(8,)u1'),
    np.ones(5, dtype='u1'),
    np.ones(5, dtype='u1'),
    np.ones(5, dtype='u1'),
    np.ones(5, dtype='u1'),
]

source=Source(
    name="",
    path="CAN_DEVICE",
    comment="",
    source_type=v4c.SOURCE_BUS,
    bus_type=v4c.BUS_TYPE_CAN,
)

sig = Signal(
    samples=np.core.records.fromarrays(arrays, dtype=DTYPE),
    timestamps=np.arange(5),
    name='CAN_DataFrame',
    source=source,
)


mdf = MDF()
mdf.append(sig)
mdf.save(r'test_can.mf4', overwrite=True)
```

**Comment by puregame** [comment]
Thank you, that is getting me a lot closer.

Now if I take the MDF and attempt to process it with a .dbc file using `extract_can_logging` it doesn't seem to work as it gives an empty .mdf out. I also noticed that opening these files with asammdfgui the "CAN logging" tab is greyed out.

Opening an example beside my output file the only significant differences I can tell are in the channel metadata.

Metadata of CAN ID for proper CAN .mf4 file: 
![image](https://user-images.githubusercontent.com/6061458/98622378-5c7de680-22d7-11eb-94e1-2ae37b09b1e5.png)

Metadata of CAN ID for my CAN .mf4 file:
![image](https://user-images.githubusercontent.com/6061458/98622397-6acc0280-22d7-11eb-9471-a1a3e5c58ccc.png)

Is this metadata likely to be causing these issues? If so can it be modified to make the .DBC processing work?

Thanks!

**Comment by puregame** [comment]
I found the issue, the problem was the `source` did not end up being correct after save. When appending the data to the mdf object use:

`mdf.append(sig, source_info=source)`
