### ISSUE TITLE
Measurement File Comment: Only Default Comment is Read

### ISSUE THREAD

**Issue by a543c23** [danielhrisca/asammdf#438]
# Python version
('python=3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.19.4'
'asammdf=5.23.1'
# Code 

  ## MDF version
  3.0 + 4.1

  ## Code snippet
  N/A
  
  ## Traceback
  N/A
  
# Description
Task: Convert MDF 3.0 file to MDF 4.1 with compression.

Result:
When opening the original MDF 3.0 file, the measurement comment is read, but only the part "Default Comments" (in ETAS MDA terminology).
Exporting basically works, but in the exported file, all of the comments are missing.
When opening the exported MDF 4.1 file, the measurement comment reads like follows:
``<HDComment>
<TX></TX>
<common_properties>
   <e name="author"></e>
   <e name="department"></e>
   <e name="project"></e>
   <e name="subject"></e>
</common_properties>
</HDComment>``

**Comment by danielhrisca** [comment]
Please give a concrete example (screenshots of MDFValidator or asammdf GUI) . I don't use ETAS and don't know what specific handling they use

**Comment by a543c23** [comment]
Thanks for the suggestion of using MDFValidator. I checked into it again. I created a test MDF 3.0 file, converted it to MDF4.1 with asammdf and can conclude the following:

1) Original MDF 3.0 File Comment Fields read out as follows:
a) Fields in MDA:
![image](https://user-images.githubusercontent.com/74541034/99285503-e4b03e80-2837-11eb-8339-44e17f143169.png)
b) Fields in MDFValidator:
![image](https://user-images.githubusercontent.com/74541034/99285818-55eff180-2838-11eb-8f9f-0befccaeb4f6.png)
c) Fields in asammdf:
![image](https://user-images.githubusercontent.com/74541034/99285932-79b33780-2838-11eb-8fcf-cb890c433d49.png)

2) Converted MDF 4.1 Fields:
a) Fields in MDA:
![image](https://user-images.githubusercontent.com/74541034/99286200-d0b90c80-2838-11eb-9bf1-f3932eb3f68d.png)
b) Fields in MDFValidator:
![image](https://user-images.githubusercontent.com/74541034/99286256-e6c6cd00-2838-11eb-96b5-2278d611f768.png)
c) Fields in asammdf:
![image](https://user-images.githubusercontent.com/74541034/99286315-f9d99d00-2838-11eb-8f5e-8afb279a0980.png)

So it seems that the header properties are not translated into mdf 4.1 format.

**Comment by danielhrisca** [comment]
Should work now with the development branch code

**Comment by a543c23** [comment]
Thank you for quickly implementing the changes! :-) I tested it with the same file.
The result is as follows:

1) Original MDF 3.0 File Comment Fields read out as follows:
a) Fields in MDA:
![image](https://user-images.githubusercontent.com/74541034/99285503-e4b03e80-2837-11eb-8339-44e17f143169.png)
b) Fields in MDFValidator:
![image](https://user-images.githubusercontent.com/74541034/99285818-55eff180-2838-11eb-8f9f-0befccaeb4f6.png)
c) Fields in asammdf:
![image](https://user-images.githubusercontent.com/74541034/99549256-be1a1100-29b9-11eb-80eb-5911f9c80a24.png)

2) Converted MDF 4.1 Fields:
a) Fields in MDA:
![image](https://user-images.githubusercontent.com/74541034/99549427-ebff5580-29b9-11eb-8f3f-2aac29da284a.png)
b) Fields in MDFValidator:
![image](https://user-images.githubusercontent.com/74541034/99549535-0c2f1480-29ba-11eb-8d1c-4c1b420b84cc.png)
c) Fields in asammdf:
![image](https://user-images.githubusercontent.com/74541034/99549584-194c0380-29ba-11eb-88eb-c20ea36074fe.png)

It seems that User Comment and Default Comment are yet missing.

I checked how the user and default comment looks in correct MDF 4.1 file:
![image](https://user-images.githubusercontent.com/74541034/99550260-cfafe880-29ba-11eb-98d8-fe4d5b28a681.png)

**Comment by danielhrisca** [comment]
can you show the comment block from the initial mdf file?  (hd_txblock @ 0x0221)

**Comment by a543c23** [comment]
Ah, sorry, I slipped that.
Yes, sure:
![image](https://user-images.githubusercontent.com/74541034/99552621-81e8af80-29bd-11eb-84da-87bf8a719cbd.png)

**Comment by danielhrisca** [comment]
ok, I think the new code covers everything

**Comment by a543c23** [comment]
Thanks again for the quick fix. Now it works like a charm:

MDF 4.1 file view in:

a) MDA:
![image](https://user-images.githubusercontent.com/74541034/99557830-64b6df80-29c3-11eb-9937-18f551499f00.png)
b) MDFValidator:
![image](https://user-images.githubusercontent.com/74541034/99557976-8912bc00-29c3-11eb-8636-5ab1a025849d.png)
c) asammdf:
![image](https://user-images.githubusercontent.com/74541034/99557894-75675580-29c3-11eb-80b5-e579edc727fd.png)
