### ISSUE TITLE
Creat a signal and append it in the existing file

### ISSUE THREAD

**Issue by dglent** [danielhrisca/asammdf#44]
# Python version
'3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]'

# Platform information
'Windows-7-6.1.7601-SP1'

# _asammdf_ version
'3.1.0'

# Code 

  ## Code snippet
mdffile = asammdf.MDF('recordFile.dat')
# take for exemple samples and timestamps from an existing signal
sams = mdffile.get('TS155_bo').samples
samt = mdffile.get('TS155_bo').timestamps
sig1 = asammdf.Signal(sams, samt, name='newSignal')
>>>sig1
Signal(name=newSignal, samples=array([1, 1, 1, ..., 1, 1, 1], dtype=uint8), timestamps=array([   3.1090906 ,    3.1205086 ,    3.1292956 , ...,  245.62956445,
        245.6399234 ,  245.64957463]), unit=, conversion=None, comment=, raw=False)
>>> mdffile.append(sig1)
  
  ## Traceback
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    mdffile.append(sig1)
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\mdf_v3.py", line 1111, in append
    timestamps = signals[0].timestamps
AttributeError: 'numpy.uint8' object has no attribute 'timestamps'
  
# Description
I wanted to create a new signal from scratch and append it in an existing MDF3 file and then save it (replace the original .dat file or create a new one...)
What would be the right way to do this ?

Thanks in advance

**Comment by danielhrisca** [comment]
Hello Dimitrios,

please check out the documentation for the _append_ method:
http://asammdf.readthedocs.io/en/latest/api.html#mdf3

The _signals_ argument should be a list, not a _Signal_ object. You should have written:

```python
mdffile.append([sig1, ])
```

**Comment by dglent** [comment]
Oops, i didn't pay attention, thanks !
