### ISSUE TITLE
Export to CSV dialog is not working

### ISSUE THREAD

**Issue by dyaraev** [danielhrisca/asammdf#441]
Hello,

I encountered an issue when I tried to export CAN logging data to CSV. The dialog did not open and the action produced the following error:

```
QMdiSubWindow::setSystemMenu: system menu is already set
  File "/Users/d.yaraev/.python-env/mdf/lib/python3.7/site-packages/asammdf/gui/widgets/file.py", line 1401, in extract_can_csv_logging
    raster = self.export_raster.value()
```

I was able to fix the issue locally by making a change on line #1401:

https://github.com/danielhrisca/asammdf/blob/c3ea7216eae150e86156e6d4c7dcfeb98507ccc7/asammdf/gui/widgets/file.py#L1401

`raster = self.export_raster.value()` => `raster = self.export_raster_can.value()`

Could you check if it is a bug.

--
LG Dmitry

**Comment by danielhrisca** [comment]
Hello Dmitry,

thanks for reporting. I think this is already fixed in the development branch.

**Comment by dyaraev** [comment]
Hi Daniel,

thank you for such a instant answer. Should I then close the issue?

--
LG Dmitry

**Comment by danielhrisca** [comment]
I'll close it on the next release

**Comment by danielhrisca** [comment]
release 6.0.0 is available
