### ISSUE TITLE
Tabular view resets when scrolling down

### ISSUE THREAD

**Issue by mindfuucker** [danielhrisca/asammdf#442]
# Python version
Using a pre-compiled Windows version from [CSS electronics](https://www.csselectronics.com/screen/page/asammdf-gui-api-mdf4/language/en). 
# Code 

  ## MDF version
  MDF4

  
# Description

When holding "down" or "page down" on the keyboard the selected row seems to reset back to top after about 40 rows. 
Tested with the MDF4 sample data from CSS electronics and with our own data. 
![image](https://user-images.githubusercontent.com/5075692/100251068-a3f2ac80-2f3e-11eb-9a27-f98f715adcf7.png)

**Comment by danielhrisca** [comment]
@mindfuucker you should use only the scroll bar until for now to work around this problem. I will fix this for the 6.0.0 release

**Comment by danielhrisca** [comment]
@mindfuucker can you run the development branch code or do you only use the precompiled binary?

**Comment by mindfuucker** [comment]
@danielhrisca Thank you for possibly fixing this problem.

I am just an end-user with a Github account who never heard of this project until yesterday. When CSS electronics decides to re-compile the project, then I'll try it out.

**Comment by danielhrisca** [comment]
@mindfuucker precompiled build available for testing https://ci.appveyor.com/project/danielhrisca/asammdf/build/artifacts

**Comment by danielhrisca** [comment]
release 6.0.0 is available
