### ISSUE TITLE
arxml file not being found

### ISSUE THREAD

**Issue by Qutadah** [danielhrisca/asammdf#443]
I am not able to load the arxml file that i want to read mf4 file with. It is arxml version 1

**Comment by danielhrisca** [comment]
You should make an issue on the [canmatrix project repo](https://github.com/ebroecker/canmatrix). This library is used to load arxml files

**Comment by Qutadah** [comment]
ok thank you, the thing is it cannot be seen by the explorer when looking for the arxml at all, do you still think i should open an issue there?

Thanks

**Comment by danielhrisca** [comment]
> ok thank you, the thing is it cannot be seen by the explorer when looking for the arxml at all, do you still think i should open an issue there?

I did not understand your first message. You should not make an issue on the canmatrix project.

Now the way to use the arxml files is to load the mf4 file first, then go to the "CAN Logging" tab and load the arxml in the database section, allowing to to extract the CAN signals

![image](https://user-images.githubusercontent.com/20952040/100453112-142a3b00-30c3-11eb-9636-47b8ad935a5d.png)

**Comment by Qutadah** [comment]
Hi, yes i did that, i was able to see the DBC files i have, but arxml no, please check as datatypes say  (.dbc or .axml), I had to convert my arxml to dbc so that the GUI would see it and able to import it. I think its a bug in the source code.

Thanks :)

**Comment by danielhrisca** [comment]
You are right there was a typo in the file type filter. Fixes in development branch and will be available in release 6.0.0

**Comment by Qutadah** [comment]
ok thanks ! I like the GUI btw ;) Saved alot of time here...
