### ISSUE TITLE
TypeError: data type '<f1' not understood

### ISSUE THREAD

**Issue by morbult** [danielhrisca/asammdf#444]
Hi again Daniel,

I now got a problem with several mdf 4.11 files which I cannot even initialise. They can however be opened with other softwares, at least in ETAS MDA and Vector MDF Validator. In MDF Validator I only get this warning, `no XSD files for this MDF version (411), used next matching version 410`, but otherwise no problem.

I run `asammdf.MDF(file)` and get `TypeError: data type '<f1' not understood` and this traceback

```
Traceback (most recent call last):

  File "<ipython-input-17-1e9cf5cc7812>", line 1, in <module>
    asammdf.MDF(file)

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 130, in __init__
    self._mdf = MDF4(name, **kwargs)

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 394, in __init__
    self._read(mapped=True)

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 603, in _read
    ch_addr, grp, stream, dg_cntr, ch_cntr, mapped=mapped

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 963, in _read_channels
    channel.channel_type,

TypeError: data type '<f1' not understood
```

Unfortunately I can't send you a file because I am not able to scramble due to this error.

python=3.7.9
asammdf=5.23.1
numpy=1.19.2

**Comment by danielhrisca** [comment]
Can you scramble using the code from here https://github.com/ratal/mdfreader/issues/189#issuecomment-711626428?

**Comment by morbult** [comment]
I will try but the line `copy(name, dst)` does not work because copy is undefined. Where does the function come from?

**Comment by danielhrisca** [comment]
I think it should be shutil.copy

**Comment by danielhrisca** [comment]
import shutil

**Comment by morbult** [comment]
Yes I used shutil.copy and sent you the file just now. Thanks!

**Comment by danielhrisca** [comment]
Should work now with the development branch code. Thank you for the file!

**Comment by morbult** [comment]
Thanks! I will check later that it works. 

When do you think the next version will be released?

**Comment by morbult** [comment]
Yep, the development branch works so the issue can be closed. Thanks for quick help!
