### ISSUE TITLE
Unable to add cg_flags while writing mdf4 file

### ISSUE THREAD

**Issue by dhruv0509** [danielhrisca/asammdf#448]
# Python version
python=3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
os=Windows-10-10.0.18362-SP0
numpy=1.19.2

  ## MDF version
  asammdf=5.23.1

  ## Code snippet
  
  ## Traceback
  
# Description
How to add cg_flags property such as '1024 [BUS_EVENT]' while writing mdf4 file?

**Comment by danielhrisca** [comment]
What exactly is your use case?

You could for example set the flags after appeding

```python
from asammdf import Signal, MDF
import asammdf.blocks.v4_constants as v4c

mdf = MDF()
mdf.append(Signal([1,3,5], [0.1, 0.2, 0.3], name="mysig"))
mdf.groups[-1].channel_group.flags = v4c.FLAG_CG_BUS_EVENT # this is actually equal to 2
mdf.groups[-1].channels[-1].flags = v4c.FLAG_CN_BUS_EVENT # this is 1024

mdf.save('out.mf4')
```

**Comment by dhruv0509** [comment]
@danielhrisca, Yes After exploring the API, I came to know this solution. I was searching it in sample examples, but i was not able to find it.

Thank you so much. It helped!
