### ISSUE TITLE
I want get group name

### ISSUE THREAD

**Issue by Agnon1573** [danielhrisca/asammdf#449]
I want to get the name of the group. How can I get it？

**Comment by JulienGrv** [comment]
Are you talking about the acquisition name or the acquisition source?
Anyway, this is how you can do this, let's say for group 3:

```python
from pathlib import Path
from asammdf import MDF

path = Path("my_file.mf4")
mdf = MDF(path)
my_group = mdf.groups[3]
print(my_group.channel_group.acq_name)  # acquisition name
print(my_group.channel_group.acq_source.name)  # acquisition source name
print(my_group.channel_group.acq_source.path)  # acquisition source path
```

**Comment by Agnon1573** [comment]
Thank you very much. Do you have a description of these method properties？I have no place to find these instructions！

**Comment by danielhrisca** [comment]
@Agnon1573 you can start here https://asammdf.readthedocs.io/en/latest/v4blocks.html#asammdf.blocks.v4_blocks.ChannelGroup
