### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by Salsapareille** [danielhrisca/asammdf#45]
# Python version
'3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]'

# Platform information
'Windows-7-6.1.7601-SP1'

# _asammdf_ version
3.1.0
  
# Description
Sorry press the enter to quickly...
I am a newbie in GitHub and I am not sure this is the correct way to ask a question. Sorry if it is not.

I just discovered asammdf and could read some signals from my mf4 files (4.11). I like it, great module!
I was just wondering how I could get more information from the signals (like source information, etc...)?

Background: our mf4-files contains bus protocols of same type of ECUs from different networks. Each ECU works with the same DBC. The MF4-files also contains same signal name (for example MSG_Motor::angle_MT) but from different sources (CAN1, CAN2... CAN6).

Is there any possibility to get these information from the MF4 with asammdf?

Thanks!

**Comment by danielhrisca** [comment]
Hello,

did you mean to file this issue? You have provided nothing except for the issue title.

**Comment by danielhrisca** [comment]
Hello,

currently there is no dedicated method for this and _Signal_ object returned by the _get_ method does not have the source information.

What you can do now, if you know the channel's group and index (for example using the method _whereis_ , see http://asammdf.readthedocs.io/en/master/api.html)and you have opened the file with the options _full_ or _low_, it to access the source information block:

```python
source = mdf.group[group_index]['channel_sources'][channel_index]
```
Granted this is does not look so nice.

If you use the option _minimum_ then you have to jump another hurdle to get the source, and it get a bit uglier 

```python
import asammdf
source_address = mdf.group[group_index]['channel_sources'][channel_index]
stream = mdf._file
source = asammdf.v4_blocks.SourceInformation(
    address=source_address,
    stream=stream,
)
```

I think the best way to handle this in the future is to add this information to the _Signal_ object returned by the _get_ method.

**Comment by Salsapareille** [comment]
Hello,

thanks for your tip.
Using the v4_blocks.TextBlock, I was capable to extract for example the acquisition name of a channel group:
```python
acq_name_addr = data.groups[group_index]['channel_group']['acq_name_addr']
stream = data._file
t_block = asammdf.v4_blocks.TextBlock(address=acq_name_addr, stream=stream)
acq_name = t_block['text'].decode('utf-8').strip('\0')
```
I must admit this is not what I was imaging to do to get source information, but at least this is working.
It would be surely nicer to get these information directly from the Signal object or from a Group object.

Thank you very much for your help!

**Comment by danielhrisca** [comment]
This will definitely be a topic on the to do list for the next releases.

**Comment by danielhrisca** [comment]
@Salsapareille 

with the new code from **development** branch you have easier access to the source information in case of mdf version 4 files:

```python
sig = mdf.get(channel_name)
# works for all memory options
acq_name = sig.source.path
```

**Comment by Salsapareille** [comment]
Cool.
I will have a look this week-end
Thanks!


Von: Daniel Hrisca [mailto:notifications@github.com]
Gesendet: Freitag, 9. März 2018 17:06
An: danielhrisca/asammdf <asammdf@noreply.github.com>
Cc: Baillard Olivier (ED/ENT2) <Olivier.Baillard@de.bosch.com>; Mention <mention@noreply.github.com>
Betreff: Re: [danielhrisca/asammdf] How to get source information from groups, signals (#45)


@Salsapareille<https://github.com/salsapareille>

with the new code from development branch you have easier access to the source information in case of mdf version 4 files:

sig = mdf.get(channel_name)

# works for all memory options

acq_name = sig.source.path

**Comment by Simsalabim1234** [comment]
Hi @danielhrisca 
unfortunately
sig = mdf_file.get(<signal_name>) 
fails when multiple signals with the same name are in the mf4 file.

In the asammdf GUI there is a column "source_path"  where each signal has an entry. Is there a possibility to get this information also for each signal when using the CLI? Currently I somehow need to put in the required informations (multiple same named signals yes/no and mapping of source_path to source_name) manually, but there has to be a way to retrieve this information I guess?
