### ISSUE TITLE
Bug when call MDF.to_dataframeI(channels=[])

### ISSUE THREAD

**Issue by Yuanli-Liu** [danielhrisca/asammdf#455]
# Python version
```python
'python=3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]'
'os=Linux-5.8.14-amd64-desktop-x86_64-with-glibc2.10'
'numpy=1.19.2'
'asammdf=6.0.1'
```
# Code 

  ## MDF version
4.10

  ## Code snippet
```python
from asammdf import MDF

mdf = MDF("test.mf4")

mdf.to_dataframe(channels=[])
```
# Description
If you pass an empty list to parameter `channels` of function `to_dataframe()`, the program will run all the time and take up more and more memory

**Comment by danielhrisca** [comment]
You have many channels with different sampling rates. Try using a raster value (raster=0.1 for example)

**Comment by Yuanli-Liu** [comment]
Thanks, it works! But I don't understand why it doesn't just return an empty pd.DataFrame() or raise an exception.

**Comment by danielhrisca** [comment]
what asammdf version did you use?

With 6.1.2 I get an empty dataframe

**Comment by danielhrisca** [comment]
Please update to 6.1.2 and you will get an empty dataframe
