### ISSUE TITLE
mdf.cut() Feature leads to different results between v5 and v6

### ISSUE THREAD

**Issue by tobi1492** [danielhrisca/asammdf#458]
# Python version

ASAMMDF 5.23.1:
----------------------
'python=3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.2'
'asammdf=5.23.1'

ASAMMDF 6.1.2:
----------------------
'python=3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.2'
'asammdf=6.1.2'

# Code 

ssignal = 'dummy'

mdfCut = mdf.cut(startTime, endTime)
objSignal = mdfCut .get(ssignal)
npArraySignal = objSignal .samples

# Description

Hello,
I found an issue between asammdf 5.23.1 and all asammdf >6.0.0 versions.
If you load an measurement file and cut it with startTime and endTime, at asammdf >6.0.0 the boundary values are interpolated

Testvector:
t    |   y
0   |   5
1   |   6
2   |   8
3   |   8
4   |   7
5   |   6

mdfCut = mdf.cut(0.5, 3.5)
objSignal = mdfCut .get('Testvector')
npArraySignal = objSignal .samples

Result npArraySignal of asammdf 5.23.1:
t        y
0.5  | **5**
1   |   6
2   |   8
3   |   8
3.5  | **8**

Result npArraySignal of asammdf >6.0.0:
t        y
0.5  | **5.5**
1   |   6
2   |   8
3   |   8
3.5  | **7.5**

So the y values of the boundary values are interpolated at the boundaries and not Zero-Order-Hold anymore. Inputs between version 5.23.1 and >6.0.0 are the same. In both version include_ends is set to true.

I think both results could be okay. In our use-case, the 5.23.1 version is the correct result. But with version >6.0.0 I can't get the same result vector like at 5.23.1.

Best Regards,
Tobias

**Comment by danielhrisca** [comment]
Hello @tobi1492 
what is the dtype of the input signal?

```python
// before cutting
print(mdf.get(''Testvector', raw=True).samples.dtype)
```

**Comment by tobi1492** [comment]
Hi Daniel,
thanks for your quick response.
Datatype is uint16.

**Comment by danielhrisca** [comment]
I can't reproduce it

```python
from asammdf import MDF, Signal
import numpy as np

s = Signal(np.arange(10, dtype='u2'), np.arange(10), name="s")

print(s.cut(1.6, 3.4))

mdf = MDF()

mdf.append(s)

print(mdf.cut(1.6, 3.4).get('s'))

```

with the output
```
<Signal s:
        samples=[1 2 3 3]
        timestamps=[1.6 2.  3.  3.4]
        invalidation_bits=None
        unit=""
        conversion=None
        source=None
        comment=""
        mastermeta="None"
        raw=True
        display_name=
        attachment=()>

<Signal s:
        samples=[1 2 3 3]
        timestamps=[1.6 2.  3.  3.4]
        invalidation_bits=None
        unit=""
        conversion=None
        source=None
        comment=""
        mastermeta="('time', 1)"
        raw=False
        display_name=
        attachment=None>

```

**Comment by tobi1492** [comment]
okay, give me one moment, I try to create an testfile + script for you. I have to prepare the mf4 file, that I can share it to you.

**Comment by tobi1492** [comment]
[share.zip](https://github.com/danielhrisca/asammdf/files/5781094/share.zip)

I have uploaded an dat file and the python code.
if you run it once with the 5.23.1 and then with 6.1.2, you will see a difference at the first and last value of the vector.

**Comment by danielhrisca** [comment]
So the new behavior comes from this snippet https://github.com/danielhrisca/asammdf/blob/master/asammdf/signal.py#L846
If the raw samples are integer and the channels has a conversion then we check if the physical samples after conversion are integer or float. If they are float then we make a linear interpolation.

**Comment by tobi1492** [comment]
Hm, okay thanks for the information.
For our use-case, the behaviour is wrong. For other use-cases, it could be right. But nevertheless, I think you should provide both options, like this:
mdfNew = mdf.cut(70, 72, include_ends=True, ends_interpolation=False)

For me, it was a bit confusion, because you set at mdf cut function an interpolation_mode = self._integer_interpolation to 0.
But I don't get the logic, why you overwrite it in signal.py then to interpolation=1. From interpolation to no-interpolation, it makes sense e.g. for text values. But for requesting no-interpolation to get interpolated values it's a bit strange to explain.

**Comment by danielhrisca** [comment]
The idea was that if there was a conversion that produced a float output then the raw value followed some "analogic" signal, for which linear interpolation makes more sense. 

For "logical" signals (error flags, system states) the conversion is either missing or it is some kind of value to text conversion. For this case linear interpolation does not make sense.

**Comment by tobi1492** [comment]
Hm okay, I understand.
Any chance/plans to make it configurable in an upcoming version?

**Comment by tobi1492** [comment]
Wow! 👍 👍 👍 

By the way, the lib is awesome and thanks for your quick support/response.

**Comment by danielhrisca** [comment]
I've also added the integer interpolation user selection in the GUI
