### ISSUE TITLE
Adding Signal to specified group

### ISSUE THREAD

**Issue by inflameRuRu** [danielhrisca/asammdf#460]
Hello Dear developers,
Firstly, happy new year 2021!
I'm a new asammdf user, and I want to add a signal to the specified group. The function 'extend' seems could implement my       request. So, i tried it as the example showed in the source code, it doesn't work, however.
Then I write a new function in the mdf_v4.py.  but the results are changed during writing into MDF as my expected. (It seems using the timestamps to write). This function basically reference the 'extend' function.
I hope you could give some help.

  My Python and asammdf info as following:
  ('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit '
   '(AMD64)]')
  'os=Windows-10-10.0.17763-SP0'
  'numpy=1.16.4'
  'asammdf=5.9.2'

Snippet 

**FUNCTION**

def add_to_grp(self,signal,grp,source_info="Python",acquistition_name="CAN"):

        cycles_nr = len(signal.timestamps)
        sam = len(signal.samples)
        print (cycles_nr,sam)
        t = signal.timestamps
        offset = 0
        fields = []
        types = []
        field_names = UniqueDB()
        #gp = self.groups[grp]
        source_block = SourceInformation()
        source_block.name = source_block.path = source_info
        sig = signal
        samples = sig.samples
        sig_dtype = samples.dtype
        sig_shape = samples.shape
        names = sig_dtype.names
        name = signal.name

        if names is None:
            sig_type = v4c.SIGNAL_TYPE_SCALAR
            if sig_dtype.kind in "SV":
                sig_type = v4c.SIGNAL_TYPE_STRING
        else:
            if names in (v4c.CANOPEN_TIME_FIELDS, v4c.CANOPEN_DATE_FIELDS):
                sig_type = v4c.SIGNAL_TYPE_CANOPEN
            elif names[0] != sig.name:
                sig_type = v4c.SIGNAL_TYPE_STRUCTURE_COMPOSITION
            else:
                sig_type = v4c.SIGNAL_TYPE_ARRAY

        if sig_type == v4c.SIGNAL_TYPE_SCALAR:
            # compute additional byte offset for large records size
            s_type, s_size = fmt_to_datatype_v4(sig_dtype, sig_shape)
            byte_size = max(s_size // 8, 1)
            offset += byte_size
            if sig_dtype.kind == "u" and signal.bit_count <= 4:
                s_size = signal.bit_count
            if signal.stream_sync:
                channel_type = v4c.CHANNEL_TYPE_SYNC
                if signal.attachment:
                    at_data, at_name = signal.attachment
                    attachment_addr = self.attach(
                        at_data, at_name, mime="video/avi", embedded=False
                    )
                    data_block_addr = attachment_addr
                else:
                    data_block_addr = 0

                sync_type = v4c.SYNC_TYPE_TIME
            else:
                channel_type = v4c.CHANNEL_TYPE_VALUE
                data_block_addr = 0
                sync_type = v4c.SYNC_TYPE_NONE

            kwargs = {
                "channel_type": channel_type,
                "sync_type": sync_type,
                "bit_count": s_size,
                "byte_offset": offset,
                "bit_offset": 0,
                "data_type": s_type,
                "data_block_addr": data_block_addr,
                "flags": 0,
            }

            ch = Channel(**kwargs)
            ch.unit = signal.unit
            ch.name = signal.name
            ch.source = source_block
            name = signal.name      

            # conversions for channel
            if signal.raw:
                ch.conversion = conversion_transfer(signal.conversion, version=4)

            # source for channel
            source = signal.source
            new_source = SourceInformation(
                        source_type=source.source_type, bus_type=source.bus_type
                    )
            new_source.name = source.name
            new_source.path = source.path
            new_source.comment = source.comment
            ch.source = new_source
            self.groups[grp].channels.append(ch)
            entry = (grp,len(self.groups[grp].channels)-1)
            field_name = field_names.get_unique_name(name)

            self.groups[grp].signal_data.append(ch.data_block_addr)
            self.groups[grp].channel_dependencies.append(None)
            self.channels_db.add(ch.display_name, entry)
            self.channels_db.add(ch.name, entry)

            fields.append(samples)
            types.append(('field_name',sig_dtype, sig_shape[1:]))

        if signal:
            samples = fromarrays(fields,dtype=types)
            print ('expected samples are: {}.'.format(samples))    #goes here still seems OK
        del fields
        del types
        del signal
        stream = self._tempfile
        stream.seek(0, 2)
        addr = stream.tell()
        size = len(samples) * samples.itemsize

        samples.tofile(stream)
----------------------
**SCRIPT**

    from asammdf import MDF4,Signal
    import numpy as np
    mdf = MDF4('delete1.mf4')
    x = mdf.get('CameraErrorType')
    print (x)
    w = [5]*len(x.samples)
    y = x.replace('test_sig',np.array(w))
    mdf.add_to_grp(y,0,x.source.path)
    mdf.save('delete3.mf4',overwrite=True)
    mdf2 = MDF4 ('delete3.mf4')
    x = mdf2.get('test_sig')
    print (x)
----------------
**OUTPUT**

    log:
       <Signal CameraErrorType:
	        samples=[0 0 0 ... 0 0 0]
	        timestamps=[660.00370692 660.00409163 660.02366617 ... 719.98677542 719.98714517
         719.98788017]
	       invalidation_bits=None
	       unit=""
	       conversion=None
	       source=SignalSource(name='xxx', path='xxx', comment='', source_type=4, bus_type=0)
	       comment=""
	       mastermeta="('time', 1)"
	       raw=False
	       display_name=
	attachment=()>

    expected samples are: [(5,) (5,) (5,) ... (5,) (5,) (5,)].                                                           #still the expected samples.
    <Signal test_sig:
	    samples=[1082433543 1082433544 1082433584 ...          0          0          0]          #was changed, don't know why.
	    timestamps=[660.00370692 660.00409163 660.02366617 ...   0.           0.
       0.        ]
	    invalidation_bits=None
	    unit=""
	    conversion=None
	    source=SignalSource(name='xxx', path='xxx', comment='', source_type=4, bus_type=0)
	    comment=""
	    mastermeta="('time', 1)"
	    raw=False
	    display_name=
	    attachment=()>

**Comment by danielhrisca** [comment]
Hello @inflameRuRu 
You cannot add channels to an existing group. The method ``extend`` is only used for adding new samples to an existing group.

Is is really important to add to an existing group? Why not just append the new signal to the MDF object?

**Comment by inflameRuRu** [comment]
@danielhrisca 
hello Daniel, 
the background is that, we will re-simulation(re-using) the MDF file, and the reading mechanism is to read an entire group once. So if the signal is not in the group(```append``` will create a new group), we can not read it, and it is huge effort to change the reading mechanism(frozen already), we can only do some trick on the MDF alternatively. Now the block is write to file..
sorry missing the  last part of the function ```add_to_grp```

```self.groups[grp].data_blocks.append(
                DataBlockInfo(
                    address=addr,
                    block_type=v4c.DT_BLOCK,
                    raw_size=size,
                    size=size,
                    param=0,
                )
            )
        del samples
```

**Comment by danielhrisca** [comment]
I think this workflow should work:

```python
mdf = MDF(filename)
out = MDF()

for gp_index, group in enumerate(mdf.groups):
    gps = mdf.included_channels(group_index)

    # get virtual groups
    channel_list = []
    for gp_index, channels in gps[group_index].items():
        for ch_index in channels:
            channel_list.append((None, gp_index, ch_index))
        
    signals = mdf.select(channel_list, raw=True)
    if gp_index == my_index:
        # create the new sig
        # ... 
        signals.append(sig)
        
    out.append(signals)
    
out.save(new_file)
out.close()
mdf.close()
```

**Comment by inflameRuRu** [comment]
@danielhrisca 
YES, that's the another solution. but as you know, we normally have 100000+ signals, 1000+ groups in one MDF, this way i think will take much more time. 
thanks for your quick answer, Daniel!
thanks a lot!

**Comment by danielhrisca** [comment]
I there is no channel dependency between the channel groups then you could try to only replace the target group

```python
mdf = MDF(filename)

# add a signal to group "group_index"

gps = mdf.included_channels(group_index)

# get virtual groups
channel_list = []
for gp_index, channels in gps[group_index].items():
    for ch_index in channels:
        channel_list.append((None, gp_index, ch_index))
    
signals = mdf.select(channel_list, raw=True)
# create the new sig
# ... 
signals.append(sig)
    
mdf.append(signals)
mdf.groups.pop(group_index)
    
mdf.save(new_file)
mdf.close()
```

The group data is stored as records (rows) of samples for each time stamp. Appending a data block with just the samples of the new channel will not work:
* first the number of cycles for the new channel must match exactly the number of samples in the existing group
* second you need to load the existing data blocks and insert the new column in the existing records 
     
For example adding _NewS_ of type uint32 (4 bytes per sample) to the existing group that contains the channels _Time, S1 and S2_ will look like this

```
Existing data block layout
|  timestamp - 8 bytes | S1 - 2 bytes | S2 - 3 bytes | timestamp - 8 bytes | S1 - 2 bytes | S2 - 3 bytes |....


New data block layout
|  timestamp - 8 bytes | S1 - 2 bytes | S2 - 3 bytes | NewS - 4 bytes | timestamp - 8 bytes | S1 - 2 bytes | S2 - 3 bytes | NewS - 4 bytes | ....
```

**Comment by inflameRuRu** [comment]
@danielhrisca 
thanks a lot for your hints again, i will try it and close this ticket
