### ISSUE TITLE
Error in GUI with cut MF4 files or ones with renamed signals

### ISSUE THREAD

**Issue by axtschmied** [danielhrisca/asammdf#461]
# Python version
```
('python=3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit '
'(AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.5'
'asammdf=6.1.2'
```

# Code 

## MDF version
4.10

## Code snippet
```python
mdf = MDF(mdf_file)
for group in mdf.groups:
    for signal in group.channels:
        signal.name = ...
```

## Traceback
```
Error: <class 'TypeError'>         
list indices must be integers or slices, not NoneType

Details: 2021-01-08, 16:58:15
--------------------------------------------------------------------------------
<class 'TypeError'>      
list indices must be integers or slices, not NoneType
--------------------------------------------------------------------------------
  File "c:\python38\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 464, in add_window
    parent = events[event.parent]
```
  
# Description
Hello,
I got the above error message in the GUI, after trying to plot any signal from a measurement that had signals renamed with the code snippet above. Also I got the same error message after cutting an MF4 file using the GUI and trying to plot signals from the cut measurement. (I can send an example file for the latter.)

I can still process the files with scripts, and plotting from a script with the `Signal` class's `plot` method still works, but the plotting from the GUI does not work. (The files can be opened in the GUI, just plotting does not work.)

**Comment by danielhrisca** [comment]
Can you verify with the development branch code?

**Comment by axtschmied** [comment]
Hello,
the same happens with version 6.2.0.dev3 (I tried both renaming and cutting).

**Comment by danielhrisca** [comment]
Please share a complete script that you run before opening the file in the GUI

**Comment by danielhrisca** [comment]
@axtschmied I've found a file that can reproduce the error. Please try again with the development branch code

**Comment by axtschmied** [comment]
With version 6.2.0.dev5 it is working.

Thank you!
