### ISSUE TITLE
Interpolation method

### ISSUE THREAD

**Issue by Noam2710** [danielhrisca/asammdf#463]
Hey, I'm trying to export a MDF file to pandas dataframe with last-value interpolation using this code 

```
mdf = MDF(file_path)
mdf.configure(integer_interpolation=0)
df = mdf.to_dataframe(channels=exist_columns,time_from_zero=False, time_as_date=True ,reduce_memory_usage=True, use_interpolation=True)
```

Afterward, I'm checking the number of unique values for each signal, and it looks that the number of unique values doesn't change without _repeat previous sample_ interpolation, but when I configure ```use_interpolation = False``` the number of unique values for each signal decrease (which makes sense).
To conclude, it seems that the _repeat previous sample_ interpolation doesn't work.

```exist_columns``` is just a list of signals.

Any ideas?
Thanks.

**Comment by danielhrisca** [comment]
> Afterward, I'm checking the number of unique values for each signal, and it looks that the number of unique values doesn't change without _repeat previous sample_ interpolation, but when I configure `use_interpolation = False` the number of unique values for each signal decrease (which makes sense).

How do you determine this? Do you check the dataframe lenght?

**Comment by Noam2710** [comment]
The length is the same.
However, the _linear_ interpolation method should create new values for each signal while _repeat the previous sample_ doesn't.
For this reason, we should see more unique values for each signal using linear interpolation, which doesn't happen.

**Comment by danielhrisca** [comment]
May it be that you have the same timestamps in all the channel groups?
In this case the interpolation has no effect.

**Comment by Noam2710** [comment]
We see that the interpolation has an effect. However, there is the same effect for both interpolation methods.

**Comment by danielhrisca** [comment]
I need more details

**Comment by Noam2710** [comment]
Which details do you need?

**Comment by danielhrisca** [comment]
Some dataframe output

**Comment by danielhrisca** [comment]
ping @Noam2710

**Comment by danielhrisca** [comment]
@Noam2710 see https://github.com/danielhrisca/asammdf/issues/478

**Comment by danielhrisca** [comment]
final ping @Noam2710
