### ISSUE TITLE
gui error 

### ISSUE THREAD

**Issue by tianyanqing00** [danielhrisca/asammdf#465]
class 'AttributeError'>: 'SymbolAtlas' object has no attribute 'symbolMap'
QGraphicsGridLayout::removeAt: invalid index -1
QGridLayoutEngine::addItem: Cell (3, 1) already taken
  File "/home/ubuntu/anaconda3/envs/py37/lib/python3.7/site-packages/asammdf/gui/widgets/file.py", line 1226, in _create_window
    self.add_window((ret, signals))
  File "/home/ubuntu/anaconda3/envs/py37/lib/python3.7/site-packages/asammdf/gui/widgets/mdi_area.py", line 487, in add_window
    plot = Plot([], events=events, with_dots=self.with_dots, origin=origin)

**Comment by danielhrisca** [comment]
What asammdf and pyqtgraph versions?
Does it work with the development branch?

**Comment by tianyanqing00** [comment]
asammdf version 6.0.1 
pyqtgraph  version 0.11.1

**Comment by tianyanqing00** [comment]
It does not work with the development branch

**Comment by danielhrisca** [comment]
I don't think that you have properly installed the development branch code.

Until 6.2.0 is released you should downgrade pyqtgraph to 0.11.0
