### ISSUE TITLE
Error appending/extending signal data

### ISSUE THREAD

**Issue by hilbichin** [danielhrisca/asammdf#467]
# Python version
_Please run the following snippet and write the output here_
('python=3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 '
 'bit (Intel)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.19.5'
'asammdf=5.20.6'

# Code 
## Dummy data for demo
```python
TMP_VALUES = [
    {"name": "RequestData_H", "ts": 13.624956, "val": 269692419},
    {"name": "RequestData_L", "ts": 13.624956, "val": 2202191872},
    {"name": "ResponseData_H", "ts": 13.626134, "val": 805306368},
    {"name": "ResponseData_L", "ts": 13.626134, "val": 0},
    {"name": "RequestData_H", "ts": 13.627849, "val": 553665723},
    {"name": "RequestData_L", "ts": 13.627849, "val": 2147499904},
    {"name": "RequestData_H", "ts": 13.628123, "val": 570425407},
    {"name": "RequestData_L", "ts": 13.628123, "val": 2147483733},
    {"name": "ResponseData_H", "ts": 13.629505, "val": 57541507},
    {"name": "ResponseData_L", "ts": 13.629505, "val": 0},
    {"name": "RequestData_H", "ts": 13.633209, "val": 52560771},
    {"name": "RequestData_L", "ts": 13.633209, "val": 1431655765},
    {"name": "ResponseData_H", "ts": 13.634368, "val": 269705731},
    {"name": "ResponseData_L", "ts": 13.634368, "val": 2202191872},
    {"name": "RequestData_H", "ts": 13.635524, "val": 805306453},
    {"name": "RequestData_L", "ts": 13.635524, "val": 1431655765},
    {"name": "ResponseData_H", "ts": 13.636715, "val": 553665723},
    {"name": "ResponseData_L", "ts": 13.636715, "val": 2147499904},
    {"name": "ResponseData_H", "ts": 13.637227, "val": 570425407},
    {"name": "ResponseData_L", "ts": 13.637227, "val": 2147483648},
]

TMP_GRP_LOOKUP = {
    "RequestData_H": 0,
    "RequestData_L": 1,
    "ResponseData_H": 2,
    "ResponseData_L": 3,
}
```
## Dummy Code to Reproduce
```python
mdf = MDF(version="4.10")
t_start = datetime.now()
mdf.header.abs_time = int(pd.Timestamp(t_start).timestamp() * 10**9)
for idx, val in enumerate(TMP_VALUES):
    if idx < 4:
        new_signal = Signal(
            samples=np.array([val["val"]]),
            timestamps=np.array([val["ts"]]),
            name=val["name"],
        )
        mdf.append(new_signal)
    else:
        mdf.extend(
            TMP_GRP_LOOKUP[val["name"]],  # group ID
            # [master channel (time), value channel]
            # the Nones hold the place of a invalidation bit arrays. See asammdf docs for more info
            [(np.array([val["ts"]]), None), (np.array([val["val"]]), None)],
        )
for ch in mdf.iter_channels():  # <- This breaks on the fourth channel!
    pass
    # import pdb;pdb.set_trace() # see comments below for strange channel data
```
  ## MDF version
mdf = MDF(version="4.10"), note file is never written

  ## Code snippet
See above
  
  ## Traceback
venv37\lib\site-packages\asammdf\mdf.py:1942: in iter_channels
    channels = self.select(channels, copy_master=copy_master)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <asammdf.mdf.MDF object at 0x14BB7ED0>, channels = [(None, 3, 1)]
record_offset = 0, raw = False, copy_master = True
ignore_value2text_conversions = False, record_count = None, validate = False

    def select(
        self,
        channels,
        record_offset=0,
        raw=False,
        copy_master=True,
        ignore_value2text_conversions=False,
        record_count=None,
        validate=False,
    ):
        """ retrieve the channels listed in *channels* argument as *Signal*
        objects

        .. note:: the *dataframe* argument was removed in version 5.8.0
                  use the ``to_dataframe`` method instead

        Parameters
        ----------
        channels : list
            list of items to be filtered; each item can be :

                * a channel name string
                * (channel name, group index, channel index) list or tuple
                * (channel name, group index) list or tuple
                * (None, group index, channel index) list or tuple

        record_offset : int
            record number offset; optimization to get the last part of signal samples
        raw : bool
            get raw channel samples; default *False*
        copy_master : bool
            option to get a new timestamps array for each selected Signal or to
            use a shared array for channels of the same channel group; default *True*
        ignore_value2text_conversions (False) : bool
            valid only for the channels that have value to text conversions and
            if *raw=False*. If this is True then the raw numeric values will be
            used, and the conversion will not be applied.

            .. versionadded:: 5.8.0

        validate (False) : bool
            consider the invalidation bits

            .. versionadded:: 5.16.0

        Returns
        -------
        signals : list
            list of *Signal* objects based on the input channel list

        Examples
        --------
        >>> from asammdf import MDF, Signal
        >>> import numpy as np
        >>> t = np.arange(5)
        >>> s = np.ones(5)
        >>> mdf = MDF()
        >>> for i in range(4):
        ...     sigs = [Signal(s*(i*10+j), t, name='SIG') for j in range(1,4)]
        ...     mdf.append(sigs)
        ...
        >>> # select SIG group 0 default index 1 default, SIG group 3 index 1, SIG group 2 index 1 default and channel index 2 from group 1
        ...
        >>> mdf.select(['SIG', ('SIG', 3, 1), ['SIG', 2],  (None, 1, 2)])
        [<Signal SIG:
                samples=[ 1.  1.  1.  1.  1.]
                timestamps=[0 1 2 3 4]
                unit=""
                info=None
                comment="">
        , <Signal SIG:
                samples=[ 31.  31.  31.  31.  31.]
                timestamps=[0 1 2 3 4]
                unit=""
                info=None
                comment="">
        , <Signal SIG:
                samples=[ 21.  21.  21.  21.  21.]
                timestamps=[0 1 2 3 4]
                unit=""
                info=None
                comment="">
        , <Signal SIG:
                samples=[ 12.  12.  12.  12.  12.]
                timestamps=[0 1 2 3 4]
                unit=""
                info=None
                comment="">
        ]

        """

        self._link_attributes()

        virtual_groups = self.included_channels(
            channels=channels, minimal=False, skip_master=False
        )

        output_signals = {}

        for virtual_group, groups in virtual_groups.items():
            cycles_nr = self._mdf.virtual_groups[virtual_group].cycles_nr
            pairs = [
                (gp_index, ch_index)
                for gp_index, channel_indexes in groups.items()
                for ch_index in channel_indexes
            ]

            if record_count is None:
                cycles = cycles_nr - record_offset
            else:
                if cycles_nr < record_count + record_offset:
                    cycles = cycles_nr - record_offset
                else:
                    cycles = record_count

            signals = []

            current_pos = 0

            for idx, sigs in enumerate(
                self._yield_selected_signals(
                    virtual_group,
                    groups=groups,
                    record_offset=record_offset,
                    record_count=record_count,
                )
            ):
                if not sigs:
                    break
                if idx == 0:
                    next_pos = current_pos + len(sigs[0])

                    master = np.empty(cycles, dtype=sigs[0].timestamps.dtype)
>                   master[current_pos:next_pos] = sigs[0].timestamps
E                   ValueError: could not broadcast input array from shape (6) into shape (5)
  
# Description

The error I'm actually getting in my system is with modified code and non-dummy data. However, I think the error seen in iter_channels() is the same root cause, so I've pasted dummy code + a small snipped of my real data to reproduce here. I've run this with a lot of other data from the real data set and most of the time everything works as expected. Not exactly sure what it is about this data in particular.

Aside from the actual numpy error on the last channel in the generator, there is an additional important point. Below is the channel data seen with a breakpoint iterating through the channels. Notice that channel 1 and 3 data is as expected, but channel 2 samples 4 and 5 do not match the dummy data as written. Then the error comes when iterating to channel 4.

(Pdb) ch
<Signal RequestData_H:
        samples=[269692419 553665723 570425407  52560771 805306453]
        timestamps=[13.624956 13.627849 13.628123 13.633209 13.635524]
        invalidation_bits=None
        unit=""
        conversion=None
        source=<asammdf.blocks.source_utils.Source object at 0x140A1A50>
        comment=""
        mastermeta="('time', 1)"
        raw=False
        display_name=
        attachment=()>

(Pdb) c
> c:\teslagit\canlogutils\venv37\lib\site-packages\te_streaming\mdf.py(142)open()
-> import pdb;pdb.set_trace()
(Pdb) ch
<Signal RequestData_L:
        samples=[         2202191872          2147499904          2147483733
 7410573605158081877 4623865735655433582]
        timestamps=[13.624956 13.627849 13.628123 13.633209 13.635524]
        invalidation_bits=None
        unit=""
        conversion=None
        source=<asammdf.blocks.source_utils.Source object at 0x1423B240>
        comment=""
        mastermeta="('time', 1)"
        raw=False
        display_name=
        attachment=()>

(Pdb) c
> c:\teslagit\canlogutils\venv37\lib\site-packages\te_streaming\mdf.py(143)open()
-> pass
(Pdb) ch
<Signal ResponseData_H:
        samples=[805306368  57541507 269705731 553665723 570425407]
        timestamps=[13.626134 13.629505 13.634368 13.636715 13.637227]
        invalidation_bits=None
        unit=""
        conversion=None
        source=<asammdf.blocks.source_utils.Source object at 0x1423B1B0>
        comment=""
        mastermeta="('time', 1)"
        raw=False
        display_name=
        attachment=()>

(Pdb) c
FAILED

**Comment by danielhrisca** [comment]
When you extend the groups you are not using the same ``dtype`` 

```python
mdf = MDF(version="4.10")
t_start = datetime.now()
mdf.header.abs_time = int(pd.Timestamp(t_start).timestamp() * 10**9)
for idx, val in enumerate(TMP_VALUES):
    if idx < 4:
        new_signal = Signal(
            samples=np.array([val["val"]]),
            timestamps=np.array([val["ts"]]),
            name=val["name"],
        )
        mdf.append(new_signal)
        print(val["name"], new_signal.samples.dtype)
    else:
        print
        mdf.extend(
            TMP_GRP_LOOKUP[val["name"]],  # group ID
            # [master channel (time), value channel]
            # the Nones hold the place of a invalidation bit arrays. See asammdf docs for more info
            [(np.array([val["ts"]]), None), (np.array([val["val"]]), None)],
        )
        print(val["name"], np.array([val["val"]]).dtype)
```

```
RequestData_H int32
RequestData_L int64
ResponseData_H int32
ResponseData_L int32

RequestData_H int32
RequestData_L int64
RequestData_H int32
RequestData_L int64

ResponseData_H int32
ResponseData_L int32
RequestData_H int32
RequestData_L int32

ResponseData_H int32
ResponseData_L int64
RequestData_H int32
RequestData_L int32

ResponseData_H int32
ResponseData_L int64
ResponseData_H int32
ResponseData_L int64
```

**Comment by hilbichin** [comment]
That's it, thanks. It's interesting that on my linux machine all of these values are int64 rather than a mix of int32 and int64. This was reported to me as a bug from a windows user, when the same data succeeds on linux. Anyway looks like a numpy quirk rather than a problem with asammdf.
