### ISSUE TITLE
"ignore_value2text_conversion=False", problem if value description has values 0 and 1

### ISSUE THREAD

**Issue by tobiasandorfer** [danielhrisca/asammdf#471]
# Python version
('python=3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.19.5'
'asammdf=6.1.2'
# Code 

  ## MDF version
4.10
file had frame based data

  ## Code snippet
                        
I use the "get_can_signal" funktion from mdf_v4 class:

mdf_sig_obj = self.mdf_obj.get_can_signal(name=query_bus + "." + signal_split[1] + "." + signal_split[2],
                                                                  database=DB_TEST,
                                                                  ignore_value2text_conversion=False,
                                                                  raw=False
                                                                  )
  

The error occurs with the setting: ignore_value2text_conversion=False,

  ## Traceback

Traceback (most recent call last):
  File "c:/svn/python/drxhelper/drx_framemdf/drx_framemdf/framemdf.py", line 436, in <module>
    print(fmdf.get_signal("H-CAN.BMS_01.BMS_IstSpannung"))
  File "c:/svn/python/drxhelper/drx_framemdf/drx_framemdf/framemdf.py", line 227, in get_signal
    mdf_sig_obj = self.mdf_obj.get_can_signal(name=query_bus + "." + signal_split[1] + "." + signal_split[2],
  File "C:\Users\AT00031723\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 8203, in get_can_signal
    extracted_signals = extract_mux(
  File "C:\Users\AT00031723\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\bus_logging_utils.py", line 336, in extract_mux
    np.isclose(samples, max_val)
  File "<__array_function__ internals>", line 5, in isclose
  File "C:\Users\AT00031723\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\numeric.py", line 2287, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
  
# Description

The reason for the traceback described error ist because 

The values for "samples" around line 336 ..."invalidation_bits":(np.isclose(...
 look like this [b'Minus' b'Minus' b'Minus' ... b'Minus' b'Minus' b'Minus']

bus_logging_utils.py:
![image](https://user-images.githubusercontent.com/64536839/105394397-cd1d7980-5c1d-11eb-898e-d5952d49e138.png)

after some more research i found the reason way this particular signal was not proper canged to "nan" vals
(just like the vals in blue marking) was because of the value description in my dbc file for this signal being exactly 0 and 1 (0="Minus",1="Plus)

if i change the value description to different values there was no error.

i dont understand the code in this part all to much, but I think somewhere in the code below could be a problem when the value description is 0 and or 1 the same as "a" and "b"

bus_logging_utils.py:
![image](https://user-images.githubusercontent.com/64536839/105395327-e4a93200-5c1e-11eb-9236-badf5a0be4a3.png)

v4_blocks.py
![image](https://user-images.githubusercontent.com/64536839/105395408-fab6f280-5c1e-11eb-8eb9-c66713cc6264.png)

as always its a pity i can't provide you with my CAN file to simulate the problem quick, but i think if you make your own test dbc file with a value description of 1 and 0 you should be able to get the same error on any mf4 file.

Thanks for the great work and affort!
Greetings Tobias

**Comment by danielhrisca** [comment]
Hello Tobias, please try the development branch code

**Comment by tobiasandorfer** [comment]
Hi Daniel,

now its not crashing but the signal is to small by factor 4 (standart factor for this signal is 0.25) for correct value signal must be 4x
also 4x 255.875 = 1023.5 what should be a value that has a description and therefore should be listed as "non" by my setting of 
ignore_value2text_conversion=True right?


![image](https://user-images.githubusercontent.com/64536839/105415627-45456880-5c39-11eb-9d35-b25155380024.png)

**Comment by danielhrisca** [comment]
Now it should work

**Comment by tobiasandorfer** [comment]
Yes now it works perfekt
Thanks for the quick and early fix! :-)
