### ISSUE TITLE
gcc fails since 6.1.0 + segmentation fault

### ISSUE THREAD

**Issue by pmayd** [danielhrisca/asammdf#472]
# Python version
Docker python:3.7-slim

# Error
```BASH
$ python -m unittest discover
xls is not supported
xlsx is not supported
The MDF source path differs from the found KMatrix, but the version is the same. Source path: _V8.16.00F_, KMatrix: MLBevo_Gen2_Fx_Cluster_KMatrix_V8.16.00F_20180608_SE.yml.
......INFO: Found 4 mdf file(s) in /builds/project-0/mdf_converter/test/resources/multiple.
INFO: Starting conversion of mdf_1.mf4.
INFO: Conversion of mdf_1.mf4 has finished.
INFO: Starting conversion of mdf_0.mf4.
INFO: Conversion of mdf_0.mf4 has finished.
INFO: Starting conversion of mdf_3.mf4.
INFO: Conversion of mdf_3.mf4 has finished.
INFO: Starting conversion of mdf_2.mf4.
INFO: Conversion of mdf_2.mf4 has finished.
INFO: 4 out of 4 MDF were converted. Please inspect the logs under /builds/project-0/mdf_converter/test/test_target/logs for more details.
.INFO: Found 1 mdf file(s) in /builds/project-0/mdf_converter/test/resources.
INFO: Starting conversion of Dauerlaufaufzeichnung_2017-12-08_16-25-42.MF4.
/bin/bash: line 40:  1040 Segmentation fault      python -m unittest discover
ERROR: Job failed: exit code 1
FATAL: exit code 1
```

# Description

Since 6.1.0 the package can no longer be installed with `pip install asammdf` for Docker image python 3.7-slim since gcc throws an error. This can be fixed by updating gcc within the Docker image. 

However, doing so will result in an error during my test cases throwing a segmentation fault during test execution. I dont have any error message, but before 6.1.0. my testsuite runs without any problems, no need to update gcc and no crash during execution of the python code. So there must be some changes in either asammdf or one of its dependencies that causes both gcc and python to fail. We use asammdf in a mdf converter that reads in an MDF and convert the MDF to parquet.

**Comment by danielhrisca** [comment]
Hello Michael

Did you try with the development branch code?

**Comment by pmayd** [comment]
Not yet, used the official release that comes with pip install asammdf>6

**Comment by JulienGrv** [comment]
The GCC error could be related to the compilation of the C extensions.

Try to install the development branch using pip inside your container and write here the error trace that GCC is throwing.

To install the development branch using pip: `pip install git+https://github.com/danielhrisca/asammdf.git@development`

**Comment by JulienGrv** [comment]
And following the version 6.1.0 that you successfully installed after updating GCC, you were using the C extensions code instead of Python code. Hence this could  explain why your unit test are failing as well.

**Comment by danielhrisca** [comment]
@pmayd can you share one your files? There is the possibility to scramble the text blocks before sending it

**Comment by pmayd** [comment]
It's more about the Signal names. If there is a possibility to hide the channel names I can share the file yes

**Comment by danielhrisca** [comment]
That is what cramble does see https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.scramble

**Comment by danielhrisca** [comment]
[Here](https://github.com/danielhrisca/asammdf/issues/386#issuecomment-661143440) you can see how the scrambled file looks like

**Comment by danielhrisca** [comment]
@pmayd @rfrowe @NicolaSabino

I think the new development branch code fixes the segfault. Please try it

**Comment by rfrowe** [comment]
@danielhrisca This seems to have fixed it. My repro script from #475 no longer fails.
