### ISSUE TITLE
Edit CAN signal values for certain timestamps in a mf4 file

### ISSUE THREAD

**Issue by tepezcuintle** [danielhrisca/asammdf#474]
# Python version
('python=3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit ' '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.19.5'
'asammdf=6.1.2'

# MDF version
v4.11
  
# Description

Hello,

I am trying to edit a mf4 file, so the values of a defined CAN signal are modified for certain timestamps (for example, set the first values of "VehicleSpeed" to 0 kph). I tried this:

    mdf4 = MDF("source_file.mf4")
    mdf4_decoded = mdf4.extract_bus_logging({"CAN": ["CAN_database.dbc"]})
    
    for sig in mdf4_decoded .iter_channels():
        if sig.name == "VehicleSpeed":
            sig[0] = 0.0

    mdf4.save("target_file_path.mf4")

When I debug, I see that 'sig.Values' are being changing during the iteration, but this does not modified the mdf4 object. There is any approach to do this properly?

Thank you in advance.

**Comment by danielhrisca** [comment]
Hello @tepezcuintle please read this https://asammdf.readthedocs.io/en/latest/tips.html#data-coupling

**Comment by tepezcuintle** [comment]
Thank you @danielhrisca for your quick answer. I didn't read the documentation carefully, but now it is clear to me why this is not working. 

I will try with a different approach, and trying to build a new MDF object from scratch, taking the original MDF object as a template, and addind Signal objects with the desired CAN Signal values. Please, let me know if you have any suggestion, which could help me, otherwise I will close the issue.

Thank you!

**Comment by danielhrisca** [comment]
That's the only way I see
