### ISSUE TITLE
Forward  fill using to_dataframe()

### ISSUE THREAD

**Issue by vaasu070** [danielhrisca/asammdf#478]
I am using `asammdf `library to read MDF files. I want to extract few signals into a dataframe without interpolation and at the same time it should forward fill(holding back previous values) for the timestamps where there is no value in the original signal.

I have looked into the documentation here. But I have not found anything, which could do the above.

Currently I am using `to_dataframe `with `use_interpolation `option set to False and using `fillna `to forward and backward fill. The problem here is executing both the lines is taking more time.

And what I have also observed is that `to_dataframe `with `use_interpolation `set to `False `will take more time to run than when `use_interpolation `is set to `True`.

```
df_mfdb = data.to_dataframe(
        channels=signalsExist, reduce_memory_usage=True, time_from_zero=False, use_interpolation=False)

df_mfdb = df_mfdb.fillna(method="ffill").fillna(
        method="bfill", downcast='infer')
```
Is there anyway I can use just asammdf function to achieve above this in as less time as possible?

**More info about my  setup:**
('python=3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.5'
'asammdf=5.20.6'

**Comment by danielhrisca** [comment]
With `use_interpolation=True` float columns will always use linear interpolation, integer columns will use whatever is configured for them (see `configure` method) and other column types will use forward fill.

**Comment by vaasu070** [comment]
> With `use_interpolation=True` float columns will always use linear interpolation, integer columns will use whatever is configured for them (see `configure` method) and other column types will use forward fill.

which means I cannot forward fill the float values?

**Comment by danielhrisca** [comment]
Yes

Linear interpolation for float signals is the obvious option from my point of view? What would be the reason for repeating the previous value in this case?

**Comment by vaasu070** [comment]
> Yes
> 
> Linear interpolation for float signals is the obvious option from my point of view? What would be the reason for repeating the previous value in this case?

When interpolated new data points are created. The clients we are working for prefer to the see the recorded values than seeing the values which are not at all recorded. It gives wrong idea.

**Comment by danielhrisca** [comment]
with the development branch code you can call `configure` to setup the way float channels are interpolated

```python
mdf = MDF(fff)
mdf.configure(integer_iterpolation=0, float_interpolation=0)

```

**Comment by JulienGrv** [comment]
Hi @danielhrisca, would it be possible to set the default float interpolation to 0 too? I think that for the user, it is less confusing to have an identical default for integer and float.

**Comment by danielhrisca** [comment]
Hello Julien, 

For this one I think I'll just keep the old behavior since I believe it make the most sense. Anyone interested can read the documentation and use the configuration option to enable other behavior.

**Comment by JulienGrv** [comment]
Fair enough! Thank you for the quick reply
