### ISSUE TITLE
FEATURE: Handle multiple logfile sources in concatenation

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#481]
Hi Daniel,

**Use case context**
We've had a number of CANedge users that are recording data across multiple CANedge devices (hence separate MF4 log files) - but wish to analyze the data in one file in asammdf. Examples include users that are logging from 4 x CAN channels in parallel, or e.g. logging data from two separate engines on a ship.

**Current options**
Some users currently deploy the below - slightly convoluted - work flow:

1) Create two versions of the DBC file: One for device 1 and one for device 2
2) In each DBC file, add a "prefix" to the relevant messages and signals, e.g. `Dev1_` and `Dev2_`
3) DBC decode the MF4 log files from each device separately, creating two decoded MF4 log files
4) Concatenate these MF4 files from each device into a single MF4 file 

The result is OK - the final MF4 contains messages and signals that are separated for each of the devices. However, the flow is rather cumbersome.

**Proposed solution 1 [complex]**
In the asammdf Batch processing mode, add an option for separating log files by a custom group name. This could e.g. work by moving the "loading" of log files into the right hand side view and enable the user to create a new widget with a few details, including a "group prefix" field where the user can add a custom string. 

The idea would be that if a user loads e.g. 5 files into widget 1, he can add a prefix stating `Dev1_` in this group - and similarly, he could add 5 files into widget 2 and add a prefix `Dev2_` for this group. When the user then hits concatenate, the result will be a file with the usual structure, but where there are 'duplicate' channel groups with the prefix in front.

For example, if the user loads a raw bus logging file, the end result could be as below:
![image](https://user-images.githubusercontent.com/26184427/106714269-e3eba500-65fb-11eb-97b0-4dc8db0027f9.png)

The challenge with doing this for raw log files will perhaps be that it adds too much complexity to subsequent code processing. Further, it's a bit TBD how the DBC decoded MF4 log file should look based on this - and how to ensure that the original dev1/dev2 prefixes are transitioned to the new file as well (as otherwise there would not be much of a point to it).

**Proposed solution 2 [simpler]**
As an alternative, the user might be able to simplify the current workflow via the 'Bus logging' view (both single file and batch processing). Here, you could add a single field called "prefix", which lets the user add a custom string prefix to the resulting DBC decoded messages and signal names. 

This way the user can greatly reduce the work effort vs. the current options as he no longer needs to modify his DBC file. Rather, the prefixing is done as part of the asammdf DBC decoding. In terms of code it would be relatively "simple" as it would just be a renaming of the channel group and signal names. However, by doing this, the user can now DBC decode a file from each device using prefixes `Dev1_` and `Dev2_`.The resulting files can then be concatenated using existing functionality, creating a merged log file.

There may be other solutions, but would be interested in your thoughts on the above.

Martin

**Comment by danielhrisca** [comment]
Hello Martin,

6.3.0.dev25 has option 2

**Comment by MatinF** [comment]
Hi Daniel, thanks for this update! It seems to work as intended based on my initial tests, so that's really cool! I'll try and do some more tests, but so far it looks good

**Comment by MatinF** [comment]
Do you have an API example snippet as well of how to use this approach?

**Comment by danielhrisca** [comment]
I've just added the ``prefix`` argument to `extract_bus_logging`

**Comment by MatinF** [comment]
OK thanks for this Daniel! Let me know once you have a release build ready, then I'm happy to do a full test round

**Comment by danielhrisca** [comment]
@MatinF 

please try the new bus channel filtering

![image](https://user-images.githubusercontent.com/20952040/117106140-02db0e00-ad88-11eb-8054-41a75495e743.png)

**Comment by MatinF** [comment]
Hi Daniel I think this works nicely!

**Comment by MatinF** [comment]
Hi Daniel,

I tried this out some more recently in the latest dev version, but I encounter a challenge. 

Specifically, I perform the below steps:
1) I have two log MF4 log files with raw CAN data. The files are recorded by two different CANedge CAN bus data loggers
2) Through asammdf, I DBC decode each of the log files and add a prefix ala "_logger1" and "_logger2" in the decoding
3) The resulting output files have these prefixes in front of the channels with decoded signals as intended
4) As a final step, I would like to be able to create a single "combined" MF4 log file, where I join the data from the two log files. The purpose of this would be to be able to e.g. create parallel plots of data across multiple devices within the GUI

The problem is that when I try to do the above steps, I get an error during the concatenation of the DBC decoded data as below:

```
Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\utils.py", line 402, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\mdf.py", line 2018, in concatenate
    f"internal structure of file {mdf_index} is different; different channels"
asammdf.blocks.utils.MdfException: internal structure of file 1 is different; different channels


Details: 2021-11-16, 08:06:16
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\utils.py", line 402, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\mdf.py", line 2018, in concatenate
    f"internal structure of file {mdf_index} is different; different channels"
asammdf.blocks.utils.MdfException: internal structure of file 1 is different; different channels

--------------------------------------------------------------------------------
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\batch.py", line 638, in concatenate
    progress=progress,
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\utils.py", line 366, in run_thread_with_progress
    raise Exception(thr.error)
```

I expect the prefix causes asammdf to consider the channel structure to be incompatible between the two log files. However, the intention would be that the final concatenated file should have the "common quantity" of channel groups across the two log files, hence the prefix should not be an issue in this regard (as the intention is indeed to separate the channel groups by device).

Specifically, this is how the channel group structure looks for the two files I'm trying to combine:


![image](https://user-images.githubusercontent.com/26184427/141938278-2bf0707c-2118-4eeb-a0b7-29406a1a06e0.png)

![image](https://user-images.githubusercontent.com/26184427/141938318-f9eb856d-4ef1-45cc-94de-59f7ab6a2102.png)

The expected output would be a new combined log file that would then still have the same two channel groups (TSC1 CAN 1 and TSC1 CAN 2), but where each group would contain a longer list of signals, with prefixes indicating which signals come from which device.

Hope this makes sense, else let me know.

**Comment by danielhrisca** [comment]
What you are searching for is the `stack` method. Having the channels in combined in the same channel group is not possible since the timestamps are not guaranteed to be identical in the decoded files.

**Comment by MatinF** [comment]
Thanks for the inputs Daniel. I tried stacking the decoded log files, though the result is as below:
![image](https://user-images.githubusercontent.com/26184427/141944230-526c47cb-8444-45db-a58f-39ec1fa3d72b.png)

While close to what I describe, the challenge with this output is that the information related to the original Channel Group names is lost entirely during the stacking. This is problematic for two reasons:

1) User will want to know what CAN ID (or PGN) the signals are grouped by, as this is often used for navigation between channels
2) Further, users will need to know which Bus Channel the data is from. For example, in this particular use case, both logger 1 and logger are recording 2 parallel CAN networks. Each CAN network contains the same messages and signals - so to correctly distinguish the "source" of a signal, it is necessary to retain the Channel Group information

**Possible solution**
When stacking the channel groups, replace the `stacked from channel group X of folder Y` with `stacked from CAN 1 - message "X" ...` - i.e. the original channel group information. I think this change would suffice if it's possible.
