### ISSUE TITLE
Error installing on ubuntu

### ISSUE THREAD

**Issue by razqq** [danielhrisca/asammdf#484]
Hey, I'm trying to install asammdf in Python 3.7 on Ubuntu 18.04.5 LTS and I get the following error. 
I tried multiple things, I downgraded pip from 21.0.1 to 18.0 as someone facing a similar issue sugested, I installed python3-dev and I also tried to install it manually by running `sudo python setup.py install` but nothing seems to work.
```
asammdf/blocks/cutils.c:1:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for asammdf
Failed to build asammdf
ERROR: Could not build wheels for asammdf which use PEP 517 and cannot be installed directly
```

**Comment by JulienGrv** [comment]
Hi razqq, could you provide more information like the command you used. The only thing I can tell right now is that the compiler could not find the Python.h header file which is for sure very strange.

**Comment by danielhrisca** [comment]
maybe your should specify python 3

```
python3 -m pip install asammdf
```

**Comment by razqq** [comment]
I'm trying to install the package from a script with the command
`subprocess.run(["python3.7","-m","pip","install","--upgrade","--no-cache-dir","--user","asammdf"])`
but I get the error I showed earlier. I also tried to install it in terminal with `python3.7 -m pip install asammdf`, I upgraded wheel and setuptools but I get the same error.

**Comment by JulienGrv** [comment]
Maybe the path to include is missing in your PATH?

**Comment by JulienGrv** [comment]
I found [this](https://stackoverflow.com/questions/8282231/i-have-python-on-my-ubuntu-system-but-gcc-cant-find-python-h) on StackOverflow. Maybe that helps.

**Comment by razqq** [comment]
@JulienGrv thank you for the help. I followed the link you provided and `sudo apt-get install libpython3.7-dev` seems to have fixed it. Problem solved.

**Comment by danielhrisca** [comment]
Thanks @JulienGrv
