### ISSUE TITLE
IndexError in to_dataframe after calling extract_bus_logging with ignore_invalid_signals=True

### ISSUE THREAD

**Issue by sziem** [danielhrisca/asammdf#485]
# Python version
'python=3.8.7 (default, Jan 27 2021, 15:30:59) \n[GCC 10.2.0]'
'os=Linux-5.10.13-2-MANJARO-x86_64-with-glibc2.32'
'numpy=1.20.1'
xls is not supported
xlsx is not supported
'asammdf=6.2.0'

# Code 

  ## MDF version
'4.10'

  ## Code snippet
  
    mf4_fname = "test.mf4"
    dbc_fnames = ["test.dbc", "test2.dbc"]
  
    with asammdf.MDF(mf4_fname) as mdf_in:
        mdf_out = mdf_in.extract_bus_logging({"CAN": dbc_fnames}, ignore_invalid_signals=True)
    df = mdf_out.to_dataframe(time_from_zero=False, use_interpolation=False)
  
  ## Traceback
  ```
  ...
  File "/home/sziem/.cache/pypoetry/virtualenvs/messschrieb-converter-3-IWTSPr-py3.8/lib/python3.8/site-packages/asammdf/mdf.py", line 3835, in to_dataframe
    sig.samples = sig.samples[idx]
IndexError: index 11200 is out of bounds for axis 0 with size 11194
python-BaseException
  ```
# Description

I got this Error, when calling `to_dataframe` after using `extract_bus_logging` with `ignore_invalid_signals==True`.  

It occurs for all my files.  Unfortunately, I am not at liberty to share them.

**Comment by danielhrisca** [comment]
Just checked with 6.2.0 and the development branch code and I can't reproduce the problem

**Comment by danielhrisca** [comment]
Did you try the development branch code?

**Comment by sziem** [comment]
Thanks for the prompt reply.

I have rerun the script with the development branch code (`asammdf.__version__ == '6.3.0.dev2'`) and the error still occurs.

It seems to have something to do with the option 
`extract_bus_logging(..., ignore_invalid_signals=True)`
in combination with 
`to_dataframe(use_interpolation=False)`

If I set either `ignore_invalid_signals=False` or `use_interpolation=True` the script runs OK.

**Comment by danielhrisca** [comment]
@sziem can you please retry with the latest development branch code?

**Comment by danielhrisca** [comment]
ping @sziem
