### ISSUE TITLE
MemoryError while reading a .mf4 file with 32 bit python

### ISSUE THREAD

**Issue by robotiktok** [danielhrisca/asammdf#487]
# Python version
('python=3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.20.1'
'asammdf=5.23.1'

# Code 

  ## MDF version
 'mdf.version =  4.10'

  ## Code snippet
from asammdf.blocks.mdf_v4 import MDF4
	mdf = MDF4(file)
	can_data_byte_samples = mdf.get("CAN_DataFrame.DataBytes").samples  

  ## Traceback
  File "blabla", line 123, in read_from_mdf
    samples = mdf.get("CAN_DataFrame.DataBytes").samples
  File "blabla_path\asammdf\blocks\mdf_v4.py", line 6065, in get
    vals, timestamps, invalidation_bits, encoding = self._get_scalar(
  File "blabla_path\asammdf\blocks\mdf_v4.py", line 7055, in _get_scalar
    signal_data, with_bounds = self._load_signal_data(
  File "blabla_path\asammdf\blocks\mdf_v4.py", line 1062, in _load_signal_data
    data, with_bounds = self._load_signal_data(
  File "blabla_path\asammdf\blocks\mdf_v4.py", line 1050, in _load_signal_data
    data, with_bounds = self._load_signal_data(
  File "blabla_path\asammdf\blocks\mdf_v4.py", line 1044, in _load_signal_data
    data = b"".join(data)
MemoryError  

# Description
Hi Daniel, I get a MemoryError if I try to read a .mf4 file using 32 bit python and the file is read without errors using 64 bit python. I tried to read the file using cut(), filter(), select(), iter_get() functions and setting read_fragment_size attribute even to 1 but it didn't help. VectorMDFValidater shows some warnings which I don't quite understand (see below).
Can you help me with this issue?
p.s. unfortunately I'm not able to share the origin file and code.

**Comment by robotiktok** [comment]
MDFValidator warning as text:

Global option to restrict number of data blocks active and limit (= 10000) exceeded. For performance reasons from now on only 2 data blocks per DL block will be loaded for this file.

I couldn't upload the screenshot.

**Comment by danielhrisca** [comment]
That section of code is not well optimized and it reads all the data referenced by that channel. I'm afraid the only option right now is to execute your scripts with a 64 bit python

**Comment by robotiktok** [comment]
Thanks for your feedback Daniel. Yes I could solve this issue using 64 bit python.
The ticket can be closed.
