### ISSUE TITLE
Importing asammdf gives RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by danielzmod** [danielhrisca/asammdf#491]
# Python version
```python
('python=3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.17.5'
xls is not supported
xlsx is not supported
yaml is not supported
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
'asammdf=6.2.0'
```
# Code 

  ## MDF version
 -

  ## Code snippet
  import asammdf
  
  ## Traceback
 RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
  
# Description
When importing asammdf i  get this runtime error. Is it supposed to be like this? Is there something in my dependencies thats wrong?

Steps to reproduce:
Create a new virtual enviroment with Python 3.7.6.
Inside the virtual enviroment run
```
pip install numpy==1.17.5
pip install asammdf
```

Then run 
```python
import asammdf
```

**Comment by JulienGrv** [comment]
Hi @danielzmod,

I think I saw this error once and I fixed the issue by reinstalling asammdf: `pip install --force-reinstall asammdf`

**Comment by danielzmod** [comment]
Hi @JulienGrv,
Thanks for your answer!
It did the trick! I don't understand why tho. Do you?

Easily recreated by creating a new virtual enviroment. 

Create a new virtual enviroment with Python 3.7.6.
Inside the virtual enviroment run
```
pip install numpy==1.17.5
pip install asammdf
```

Then run 
```python
import asammdf
```

**Comment by JulienGrv** [comment]
How do you create the virtual environment? With venv?

**Comment by danielzmod** [comment]
> How do you create the virtual environment? With venv?

Correctly! I downloaded python 3.7.6 then created a virtual enviroment using venv.
