### ISSUE TITLE
UnboundLocalError: local variable 'masters' referenced before assignment

### ISSUE THREAD

**Issue by pebel76260** [danielhrisca/asammdf#497]
# Python version
'''
'python=3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.3'
asammdf=6.2.0
'''
# Code 

  ## MDF version
mf4

  ## Code snippet

mdf_obj_red = mdf_obj.cut(0, 2)
mdf_obj = mdf_obj.filter(["Signal1"])
for i, df_ in enumerate(mdf_obj.iter_to_dataframe(raster=0.1)):
    df = df.append(df_)

  ## Traceback

File "C:\PythonEnv\lib\site-packages\asammdf\mdf.py", line 3087, in iter_to_dataframe
    np.searchsorted(masters[group_index], start).flatten()[0] - 1, 0
UnboundLocalError: local variable 'masters' referenced before assignment
  
# Description
Seems only to appear, if  mdf_obj.filter() was executed previously.

**Comment by danielhrisca** [comment]
Hello @pebel76260 
It should be fixed in the development branch
