### ISSUE TITLE
The GUI sometimes crashes when deleting signals from plots

### ISSUE THREAD

**Issue by axtschmied** [danielhrisca/asammdf#499]
# Python version
```
('python=3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.5'
'asammdf=6.2.0'
```

# MDF version
4.10
  
# Description
Sometimes the GUI crashes, when I delete one or multiple signals from a plot. When it happens, the GUI closes immediately, I get no error message.

It happens very randomly, sometimes I delete many signals and this problem does not occur, other times the first deletion causes the GUI to crash. So far I haven't found a relation to any setting of the plot (e.g. visibility of signals, common axis, computations).

I will experiment more with deleting signals, and update this bug report, when I know more.

**Comment by danielhrisca** [comment]
Hello @axtschmied 
I've made some changes in the development branch, maybe you can give them a try

**Comment by axtschmied** [comment]
Hello Daniel,
thank you for the quick reply. I experimented a bit more with the 6.2.0 version, and found the following: If I create a plot from a single signal, that does not have any data in it, and then delete the signal immediately, the GUI crashes (almost) every time (I think there were some occasions when it did not).

By the way, now I also checked the console output after the crash, but there was nothing, except for `QGraphicsGridLayout::removeAt: invalid index -1`, but that appears every time I delete a signal, not just when the crash happens.

I tried the same method with version 6.3.0.dev15, and I still could cause some crashes, but less frequently.

**Comment by danielhrisca** [comment]
> Hello Daniel,
> thank you for the quick reply. I experimented a bit more with the 6.2.0 version, and found the following: If I create a plot from a single signal, that does not have any data in it, and then delete the signal immediately, the GUI crashes (almost) every time (I think there were some occasions when it did not).

Thank you Daniel, this really helped to reproduce and investigate. Please try out the new code

**Comment by axtschmied** [comment]
I tried out version 6.3.0.dev18, and I could not reproduce the issue. Thank you for your effort.

I will give feedback, if I experience problems during further use.

**Comment by axtschmied** [comment]
Hello Daniel,
I don't know, if this error is related to the original topic of this thread, but I got the following error message in version 6.3.0.dev18, when trying to delete a calculated signal from a plot:

```
Error: <class 'TypeError'>         
disconnect() failed between 'individual_axis_changed' and all its connections

Details: 2021-04-13, 11:16:42
--------------------------------------------------------------------------------
<class 'TypeError'>      
disconnect() failed between 'individual_axis_changed' and all its connections
--------------------------------------------------------------------------------
  File "c:\python38\lib\site-packages\asammdf\gui\widgets\list.py", line 49, in keyPressEvent
    item_widget.disconnect_slots()
  File "c:\python38\lib\site-packages\asammdf\gui\widgets\channel_display.py", line 263, in disconnect_slots
    self.individual_axis_changed.disconnect()
```

The GUI did not crash, I just got this error message, and I couldn't do anything with the signal after that. All other signals remained usable.

I think you don't need anything special to reproduce this, just insert a calculated signal and try to delete it.

**Comment by danielhrisca** [comment]
Hello @axtschmied 6.3.0dev22 has this fixed
