### ISSUE TITLE
Cannot get Signal when load_measured_data=False

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#5]
When trying to get a signal of an MDF4 file read with the option load_measured_data=False, the returned signal is a different one and its samples and timestamps are empty.

```python
>>> import asammdf
>>> mdf = asammdf.MDF('test.MF4', load_measured_data=False)
>>> signal = mdf.get('signal_XXXX')
>>> print(signal)
Signal { name="signal_YYYY":       s=[]    t=[]
        unit="" conversion=None }
```

I undertook some research and found out in the get method that the if statement on line 726 in mdf4.py does not pass because the ch_data_addr is 0, which should not be 0. So the problem seems to be located near there.

```python
     [...]
725  ch_data_addr = channel['data_block_addr']
726  if ch_data_addr:
727      file_stream.seek(ch_data_addr, SEEK_START)
         [...]
```

**Comment by danielhrisca** [comment]
Please print the _channel_ before the _if_ (line 726)

**Comment by JulienGrv** [comment]
Did it, output is:

```python
{'id': b'##CN', 'reserved0': 0, 'block_len': 160, 'links_nr': 8, 'next_ch_addr': 120884864, 'component_addr': 0, 'name_addr': 120885024, 'so
urce_addr': 0, 'conversion_addr': 0, 'data_block_addr': 0, 'unit_addr': 0, 'comment_addr': 120885160, 'channel_type': 0, 'sync_type': 0, 'da
ta_type': 2, 'bit_offset': 0, 'byte_offset': 2618, 'bit_count': 16, 'flags': 20, 'pos_invalidation_bit': 0, 'precision': 255, 'reserved1': 0
, 'attachment_nr': 0, 'min_raw_value': 0.0, 'max_raw_value': 0.0, 'lower_limit': -32768.0, 'upper_limit': 32767.0, 'lower_ext_limit': 0.0, '
upper_ext_limit': 0.0}
```

**Comment by danielhrisca** [comment]
The next thing would be to print _channel.address_ and verify with MDFValidator if the channel at that address has a nonzero signal data link:

![image](https://user-images.githubusercontent.com/20952040/28815369-d9e793ec-76a9-11e7-9a95-562fe6e4513a.png)

**Comment by JulienGrv** [comment]
We have a proxy at our work and I can't upload an image but I can tell you the cn_data field of that signal is 0x0000

**Comment by JulienGrv** [comment]
IMHO the address lies in the data group, not the channel. I will send you screenshots of MDFValidator per email.

**Comment by danielhrisca** [comment]
Latest commit should have fixed this issue https://github.com/danielhrisca/asammdf/commit/ae8c6ada66fcbc8ebc71547a994726661472da40

Also new methods have been added: _get_master_data_ and _get_channel_data_. You can use them to access only the master channel data or only some channel's data. The _get_ method still works the same and uses the new methods under the cover.

**Comment by JulienGrv** [comment]
Now it runs but when I get, it returns the signal of a different channel that the one I give as input for get()

**Comment by danielhrisca** [comment]
_read_channels should return ch_cntr, which should be used to update ch_cntr at line 276. can't edit the file on mobile otherwise I would patch this now

**Comment by JulienGrv** [comment]
You are right, just did a test a few minutes ago, everything is working fine now! Very nice work! You definitely deserve more kudos for this module! Its runs fast and I think I will start using it for my projects. I will keep you posted per email :)

**Comment by danielhrisca** [comment]
Hello Julien,

glad to hear it works for you.
I've just made an update that greatly improves performance if you have data
lists.

Another trick that may be useful in your case would be to skip loading the
SourceInformation blocks (should lower the RAM usage and execution time a
lot).

Could you run a small bench with your sample file, similar to the one found
in the benchmarks folder? I'm curious to see the load time and RAM usage.

Thank you!

**Comment by danielhrisca** [comment]
Hi again,

with the last commit if you use load_measured_data=False then the Source
Information loading is skipped.

On my system this leads to 16% lower load time and 13% lower RAM usage.
