### ISSUE TITLE
Memory Error with the mdf.to_dataframe() method with .mf4 files

### ISSUE THREAD

**Issue by eric17py** [danielhrisca/asammdf#501]
'python=3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) \n[GCC 7.3.0]'
'os=Linux-4.15.0-112-generic-x86_64-with-debian-stretch-sid'
'numpy=1.18.1'

  ## MDF version
'asammdf=6.2.0'

  ## Code snippet
mdf0 = MDF(file_path, memory='minimum')
df0 = mdf0.to_dataframe()  # **debuger says: Here the error occurs**
  
  ## Traceback
MemoryError: Unable to allocate 2.03 GiB for an array with shape (397, 685090) and data type float64
or
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)  

# Description
I could share the conveter python file, but not the data.

**_Please describe the issue here._**

Firstly, im using asammdf since one year now and never had issues with it till now. Im using it as a converter to csv-filse with the mdf.to_dataframe() method. Usually i got .mdf-files (with different sizes up to 2 gb) and i never had memory problems.

Now i got new .mf4-files and my whole programm crashs with the written errors. The RAM raise till 16 GB and then the programm stops with SIGKILL. 
I tried to make the file smaller with the gui of asammdf. I cut the lengths or select just a few channels. When I minimized it enough, then i dont get error anymore, but its just writing NANs into the csv.

Sidefact: The mdf.export() method is working also with the new (.mf4) files. 

So, Im not absolutely sure, if its an asammdf problem, cause the error occurs with pandas, but with the MDF.to_dataframe() method. And what i really dont understand, that it gives me nans after minimizing the file.

Is it a known problem or is it new? Any suggestions?

**Comment by danielhrisca** [comment]
> I could share the conveter python file, but not the data.

The file would really help to solve thsi quickly. Maybe you can privately share the scrambled file?

**Comment by eric17py** [comment]
yes, i could sent it to your email adress, if its ok?

**Comment by danielhrisca** [comment]
Sure, if it is small enough. If not send me an email and I will give you access to a folder on Google drive

**Comment by danielhrisca** [comment]
I've tried the latest development branch code with your file and I get no error.
