### ISSUE TITLE
TypeError when running the resample command

### ISSUE THREAD

**Issue by tremy78** [danielhrisca/asammdf#502]
# Python version

'python=3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.18.5'
'asammdf=6.2.0'

# Code 

  ## MDF version
  file version: 4.10

  ## Code snippet
 mdf.resample(raster=0.01)
  
  ## Traceback
  File "<ipython-input-87-d1cf0150170b>", line 1, in <module>
    mdf.resample(raster=0.01)

  File "C:\Users\GRL4SO\Anaconda3\lib\site-packages\asammdf\mdf.py", line 2548, in resample
    MDF._transfer_channel_group_data(mdf.groups[dg_cntr].channel_group, cg)

TypeError: list indices must be integers or slices, not NoneType
  
# Description

I try to resample the data in order to have a fixed timestep.
I followed the documentation but I can't find a way to make to work.
If someone had the same issue or knows a way to bypass it, it would help me.

**Comment by danielhrisca** [comment]
Hello @tremy78 can you check first if this still occurs with the development branch code?
