### ISSUE TITLE
Problem with signal search in Comparison mode

### ISSUE THREAD

**Issue by axtschmied** [danielhrisca/asammdf#506]
# Python version
```
('python=3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.5'
'asammdf=6.2.0'
```

# MDF version
4.10
  
# Description
If the MF4 file opened last does not contain the pattern (wildcard or regex) that you search for in Comparison mode in the GUI, no result is shown in the list box. The number of open files does not matter.

If the files are opened in a different order, so the last one contains signal(s) matching the search pattern, the results from all files are shown correctly, even if the same file (not containing any matching signals) is open as well.

**Comment by danielhrisca** [comment]
Hello @axtschmied 6.3.0.dev23 has this fixed
