### ISSUE TITLE
NMEA 2000 PGN decoding

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#507]
Hi Daniel,

_I'm adding this here as well for reference._

I tried using asammdf with some NMEA 2000 decoding, but I think there may be a small error in the DBC decoding for J1939.

Specifically, I'm trying to decode a CAN ID, 0xDF11923. This CAN ID should be translated into a "J1939 PGN" (same as NMEA 2000 PGN) of 0x1F119. However, in asammdf it seems to be interpreted as 0xF119. I think the problem is that the 'data page' (DP) bit is set to 0 instead of 1 in the conversion (an error I also previously made in some other cases.  I've sent you a log file, but let me know if it should be resent.

Let me know if you get the chance to review what might cause this and whether it's in asammdf or canmatrix.

**Comment by danielhrisca** [comment]
Hello Martin,

the code that extracts the PGN from the CAN ID is only using the first 24 bits of the CAN ID 

https://github.com/danielhrisca/asammdf/blob/d165a27499308871abd959fd91d34ce6f10a2ece/asammdf/mdf.py#L4134-L4139

so 0xDF11923 is seen as 0xF111923

what would be the correct way to handle it?

**Comment by MatinF** [comment]
Hi Daniel, it should take outset in the full 29 bit can ID when deriving the PGN. See our intro to J1939 PGN section below:

https://www.csselectronics.com/screen/page/simple-intro-j1939-explained/language/en

Further, our J1939 DBC page also has a link for a google sheet where you can enter a 29 bit can id to get the j1939 PGN - it also shows a breakdown of the logic behind the extraction:

https://www.csselectronics.com/screen/product/j1939-dbc-file-pgn-spn/language/en

**Comment by danielhrisca** [comment]
@MatinF please try the 6.3.0.dev24 code

**Comment by MatinF** [comment]
Hi Daniel,

This seems to do the trick, great!

One semi-related observation:

1) In this particular dataset, we have multiple 29-bit CAN IDs that map to the same 18-bit PGNs. The result current in asammdf is that the DBC-decoded signal outputs become "combined" across multiple CAN IDs, which is rarely the intention.

2) In other cases I've seen, a user may be recording two identical CAN buses across two bus channels. When attempting to decode the data, the signal outputs will also be combined as the bus channel information is lost.

**Suggestion**
I think an ideal way to solve both of the above would be to adjust the logic of how channel groups are formed. Instead of forming them purely based on the CAN ID or PGN, the channel groups would be formed as follows:

`Channel group X ([Bus Channel]: [CAN_ID] [Message_Name])`

Example:

Today, the decoding would produce the following:

`Channel group 0 (0x1F112 VesselHeading)`

While the new method for the same dataset could produce the following:

```
Channel group 0 (1: 0x9F11202 VesselHeading)
Channel group 1 (2: 0x9F11202 VesselHeading)
Channel group 2 (1: 0x9F11223 VesselHeading)
```

So essentially, instead of grouping by e.g. PGN alone, you would group based on the full 29 bit CAN ID _and_ the bus channel. 

I believe the above change would generally produce the intended result, and you'd avoid plots like the below:
![image](https://user-images.githubusercontent.com/26184427/115137213-056a0380-a025-11eb-8e48-d735f4268069.png)

Let me know your thoughts :-)
