### ISSUE TITLE
installation conflict in conda with py-xgboost

### ISSUE THREAD

**Issue by jontis** [danielhrisca/asammdf#51]
**$ conda install -c conda-forge asammdf** 
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - asammdf
  - py-xgboost
Use "conda info <package>" to see the dependencies for each package.

**$ conda info py-xgboost**
Fetching package metadata ...........

py-xgboost 0.60 py27np112h0aae3cd_0
-----------------------------------
file name   : py-xgboost-0.60-py27np112h0aae3cd_0.tar.bz2
name        : py-xgboost
version     : 0.60
build string: py27np112h0aae3cd_0
build number: 0
channel     : defaults
size        : 51 KB
arch        : x86_64
date        : 2017-03-27
md5         : 78cf04ef47f34508262d0eb196d7ff3c
noarch      : None
platform    : linux
url         : https://repo.continuum.io/pkgs/free/linux-64/py-xgboost-0.60-py27np112h0aae3cd_0.tar.bz2
dependencies:
    libxgboost 0.60 hdfa14d8_0
    numpy 1.12.1
    python >=2.7,<2.8
    scikit-learn
    scipy

py-xgboost 0.60 py35np112h32b46d2_0
-----------------------------------
file name   : py-xgboost-0.60-py35np112h32b46d2_0.tar.bz2
name        : py-xgboost
version     : 0.60
build string: py35np112h32b46d2_0
build number: 0
channel     : defaults
size        : 52 KB
arch        : x86_64
date        : 2017-03-27
md5         : 0342614790aa32e1b6619c9d9e785992
noarch      : None
platform    : linux
url         : https://repo.continuum.io/pkgs/free/linux-64/py-xgboost-0.60-py35np112h32b46d2_0.tar.bz2
dependencies:
    libxgboost 0.60 hdfa14d8_0
    numpy 1.12.1
    python >=3.5,<3.6
    scikit-learn
    scipy

py-xgboost 0.60 py36np112h54d5342_0
-----------------------------------
file name   : py-xgboost-0.60-py36np112h54d5342_0.tar.bz2
name        : py-xgboost
version     : 0.60
build string: py36np112h54d5342_0
build number: 0
channel     : defaults
size        : 52 KB
arch        : x86_64
date        : 2017-03-27
md5         : 5989503e497979acea3f51f9f18e7afb
noarch      : None
platform    : linux
url         : https://repo.continuum.io/pkgs/free/linux-64/py-xgboost-0.60-py36np112h54d5342_0.tar.bz2
dependencies:
    libxgboost 0.60 hdfa14d8_0
    numpy 1.12.1
    python >=3.6,<3.7
    scikit-learn
    scipy

**Comment by danielhrisca** [comment]
*asammdf* requires numpy>= 1.13.1 because of issue #7 

I'll try to see if there is an alternative workaround

**Comment by danielhrisca** [comment]
I've managed to get the code in this branch https://github.com/danielhrisca/asammdf/tree/lower_numpy_requirement to work with numpy 1.12.1 but I want to make more tests before including this in the base code.

**Comment by jontis** [comment]
I have numpy 1.14.1?
$ conda list | grep numpy
numpy                     1.14.1           py36h3dfced4_1

**Comment by danielhrisca** [comment]
If you have numpy 1.14 how come you also have py-xgboost? It requires version 1.12.1 exactly

**Comment by jontis** [comment]
My bad, I uninstalled xgboost to allow installation of asammdf and forgot. In my opinion, keep your code and they adapt to newer numpy.

**Comment by danielhrisca** [comment]
I'll keep that branch for reference in case it is needed.
