### ISSUE TITLE
'MDF3' object has no attribute '_raise_on_mutiple_occurences'

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#516]
# Python version
'python=3.8.5'
'numpy=1.20.3'
'asammdf=6.2.0'

# Code 

  ## MDF version
  _please write here the file version (3.30)

  ## Code snippet
 data = mdf_file.to_dataframe(labels,time_from_zero=False,time_as_date=time_as_date)
  
  ## Traceback
Traceback (most recent call last):
  File "C:\pycharm\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\anaconda3\envs\py38\lib\site-packages\asammdf\mdf.py", line 3672, in to_dataframe
    mdf = self.filter(channels)
  File "C:\anaconda3\envs\py38\lib\site-packages\asammdf\mdf.py", line 1587, in filter
    gps = self.included_channels(channels=channels)
  File "C:\anaconda3\envs\py38\lib\site-packages\asammdf\blocks\mdf_v3.py", line 3717, in included_channels
    group, idx = self._validate_channel_selection(name)
  File "C:\anaconda3\envs\py38\lib\site-packages\asammdf\blocks\mdf_common.py", line 125, in _validate_channel_selection
    if self._raise_on_mutiple_occurences:
AttributeError: 'MDF3' object has no attribute '_raise_on_mutiple_occurences'
  
# Description

This problem will not occur using the asammdf graphical Viewer. There I'm be able to access the selected labels. This error occured after an update of the asammdf package. It seems to be affected by the group where the labels come from.

BR
Matthias

**Comment by danielhrisca** [comment]
Hello Matthias,

I think this is fixed in the development branch

**Comment by Lama09** [comment]
Hello Daniel,

many thanks for your quick response. Unfortunately I don't got the Microsoft Visual C++ 14.0 compiler on my system. Installing the development branch will fail.

BR
Matthias

**Comment by danielhrisca** [comment]
do you use 32 or 64 bit python?

**Comment by danielhrisca** [comment]
You can use this wheel 

[asammdf-6.3.0.dev31-cp38-cp38-win_amd64.whl.zip](https://github.com/danielhrisca/asammdf/files/6521829/asammdf-6.3.0.dev31-cp38-cp38-win_amd64.whl.zip)

**Comment by JulienGrv** [comment]
Hi @Lama09, 

you can use the wheel provided by @danielhrisca but why not try installing the windows build tools for C/C++? It's really not difficult and you may need it for other things. Here is a link for you to find the windows build tools you need depending on your Python version: https://wiki.python.org/moin/WindowsCompilers

But since I know you're using Python version 3.8, let me give you directly the link to the build tools you need: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019
