### ISSUE TITLE
Virtual Type Channels are not working correctly 

### ISSUE THREAD

**Issue by dhruv050992** [danielhrisca/asammdf#518]
I have seen issue with Channel Type = 6 (Virtual Channels), the values are not parsed correctly, I guess every time code is using index 0 instead of incremental index.

**Comment by danielhrisca** [comment]
Hello, can you provide a demo file or a code snippet?

**Comment by dhruv050992** [comment]
Hi Daniel,
As per ASAM MDF documentation regarding Virtual Channels:
"the physical value must be calculated by feeding the zero-based record index to the conversion rule".

But for the file I am checking, its always constant, instead of increment.

**Comment by danielhrisca** [comment]
Seems to work with the development branch code and the ASAM demo files that contain virtual channels. Can you install the development code and try with your file?

**Comment by dhruv050992** [comment]
I ran with the development branch, still getting "zero (0)" value in VirtualChannelLinearConversion File

**Comment by danielhrisca** [comment]
That's how it looks with 6.3.0.dev41

![image](https://user-images.githubusercontent.com/20952040/124082933-f7d5ee80-da55-11eb-9b2b-a5ab992271ef.png)
