### ISSUE TITLE
UnicodeDecoderError in reading version in md.py

### ISSUE THREAD

**Issue by livias** [danielhrisca/asammdf#52]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _pleaase write here the error traceback_
  
# Description
version = file_stream.read(4).decode('ascii').strip(' \0')

UnicodeDecodeError: 'ascii' codec can't decode byte 0x8c in position 3: ordinal not in range(128)

**Comment by danielhrisca** [comment]
Hello,

please post the output of this snippet (assuming you have Python 3:
```python
with open(mdf_file, 'rb') as mdf:
    for i in range(8):
        line = mdf.read(8)
        print([hex(v) for v in line], line)
```

**Comment by danielhrisca** [comment]
Looks like a zip or xlsx file
https://en.m.wikipedia.org/wiki/List_of_file_signatures

**Comment by livias** [comment]
it is a mdf3 file

**Comment by livias** [comment]
yesterday was correctly read

**Comment by danielhrisca** [comment]
I think it's a zip file. 

Your first 8 bytes are:

> ['0x50', '0x4b', '0x3', '0x4', '0x14', '0x0', '0x0', '0x0'] 

and here is an example of a zip archive:

![image](https://user-images.githubusercontent.com/20952040/37153342-16aba1be-22e5-11e8-89ee-e648277aee5e.png)

**Comment by danielhrisca** [comment]
According to this it's a zip file how initial name was "_rels/.rel"

**Comment by danielhrisca** [comment]
Sorry the intial name has 11 bytes : "_rels/.rels"

**Comment by livias** [comment]
I will check the path to file. Yesterday was everything fine.

**Comment by danielhrisca** [comment]
I've included an initial check for the MDF magic header (in the development branch) so this will reject all invalid files.

**Comment by livias** [comment]
Thanks.

Trimis din Yahoo Mail pe Android 
 
  Pe mar., mar. 13, 2018 la 10:50, Daniel Hrisca<notifications@github.com> a scris:   
I've included an initial check for the MDF magic header (in the development branch) so this will reject all invalid files.
