### ISSUE TITLE
GUI: Export CSV doesn't work as expected

### ISSUE THREAD

**Issue by Kerby92** [danielhrisca/asammdf#523]
# Python version
('python=3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.20.3'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=6.2.0'

## MDF version
4.1.0
  
# Description
The issue is related to the GUI. I have a mf4-File generated by CarMaker.
Opening the file works fine, all available channels are visible.
The issue is related to the conversion method. When converting to .csv, the GUI allows you to define "parameters" like

- Delimiter
- Escape Char
- Quote Char
- Quoting

but changing one of these had no impact on the result CSV file.

Let's see one example. The configuration on my side looks like the following:
![grafik](https://user-images.githubusercontent.com/70330878/123606209-f5c52300-d7fc-11eb-8bc8-5f97bb33a02a.png)

The result (viewed by Notepad++) looks like the following:
![grafik](https://user-images.githubusercontent.com/70330878/123604506-2efc9380-d7fb-11eb-9f39-4a23887ba0ad.png)

Am I doing something wrong or is this an issue?

**Comment by danielhrisca** [comment]
@Kerby92 please try the new development code (6.3.0.dev40)

**Comment by Kerby92** [comment]
@danielhrisca I'm not so much experienced with handling development code from GitHub.
How should I install your additions/ your dev-code? I know, I could just replace the 4 files, but I would like to know,
how one should update to a dev-version through pip or anything else (like setup.py)? I'm working with visual code
and AsamMDF-6.2.0 is installed in the path "C:\Users\user\AppData\Roaming\Python\Python39\site-packages".

If it is long to explain, a suitable link explaining it would be helpful, too.

**Comment by Kerby92** [comment]
Hey @danielhrisca,
I was able to install your dev version (6.3.0.dev40) by using the following command:

`pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip`

but for some reason I get the following error from my PowerShell:

```
PS C:\Users\kbodi\AppData\Roaming\Python\Python39\Scripts> .\asammdf.exe
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kbodi\AppData\Roaming\Python\Python39\Scripts\asammdf.exe\__main__.py", line 4, in <module>
  File "C:\Users\kbodi\AppData\Roaming\Python\Python39\site-packages\asammdf\__init__.py", line 14, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Users\kbodi\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v2.py", line 4, in <module>
    from .mdf_v3 import MDF3
  File "C:\Users\kbodi\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v3.py", line 38, in <module>
    from ..signal import Signal
  File "C:\Users\kbodi\AppData\Roaming\Python\Python39\site-packages\asammdf\signal.py", line 10, in <module>
    from .blocks import v2_v3_blocks as v3b
  File "C:\Users\kbodi\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v2_v3_blocks.py", line 13, in <module>
    from numexpr3 import evaluate as evaluate3
ModuleNotFoundError: No module named 'numexpr3'
```

I assumed that the package "numexpr3" is missing and was trying to install it with

`pip install numexpr3`

but this led to a bunch of errors. When reading about numexpr3, it was explained on some locations that no one is really working on numexpr3 anymore. Is this really a requirement for your AsamMDF dev version (6.3.0.dev40) and am I doing something wrong?

Here is a snippet of the long error message after trying to install numexpr3:

`
ERROR: Command errored out with exit status 1: 'c:\program files\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kbodi\\AppData\\Local\\Temp\\pip-install-bomw7a41\\numexpr3_837e8ecb4ea043a9a384f829670751f0\\setup.py'"'"'; __file__='"'"'C:\\Users\\kbodi\\AppData\\Local\\Temp\\pip-install-bomw7a41\\numexpr3_837e8ecb4ea043a9a384f829670751f0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kbodi\AppData\Local\Temp\pip-record-7bn9hoq0\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\kbodi\AppData\Roaming\Python\Python39\Include\numexpr3' Check the logs for full command output.
`

**Comment by danielhrisca** [comment]
The are some algebraic conversions that require functions only available in num3xpr3.hoever those are rare and numexpr3 should be set as a nice to have dependency. I will push a new commit in this regard

**Comment by Kerby92** [comment]
I guess, numexpr3 is not compatible with python 3.9.0, but haven't tried it with older python versions.
