### ISSUE TITLE
v2_v3_blocks.py "time data %r does not match format %r"

### ISSUE THREAD

**Issue by Wave89** [danielhrisca/asammdf#527]
# Python version
'python=3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.21.0'

# Code 
timestamp = '30: 6:2021 11:21:00'

  ## MDF version
3.30 and 4.10

  ## Code snippet
 bugfix could be: datetime.strptime('30: 6:2021 11:21:00'.replace(': ',':'), "%d:%m:%Y %H:%M:%S")
  
  ## Traceback
 datetime.strptime('30: 6:2021 11:21:00', "%d:%m:%Y %H:%M:%S")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Anaconda3\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\Anaconda3\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '30: 6:2021 11:21:00' does not match format '%d:%m:%Y %H:%M:%S'
  
# Description

quick fix for time interpretation

**Comment by danielhrisca** [comment]
I think we should first see were the wrong timestamp string is coming from, otherwise any strange/not conformant string will require a custom handling to parse correctly. Which tool created the file?
