### ISSUE TITLE
mdf_v3.py

### ISSUE THREAD

**Issue by Wave89** [danielhrisca/asammdf#528]
# Python version
'python=3.8.3 (default, Jul 2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.21.0'
# Code 

  ## MDF version
  mdf is 3.30
  mf4 = mdf.convert('4.10') 

  ## Code snippet
solution could be
  mdf_v3.py line 3765
  if groups == {}:
            channels = []
        else:
            channels = groups[index]
  
  ## Traceback
Exception has occurred: KeyError
114
  File "C:\00_sbx\mat2mf4\asammdf\asammdf\blocks\mdf_v3.py", line 3769, in _yield_selected_signals
    channels = groups[index]
  File "C:\00_sbx\mat2mf4\asammdf\asammdf\mdf.py", line 537, in convert
    for idx, sigs in enumerate(
  File "C:\00_sbx\mat2mf4\MF4Creator.py", line 29, in <module>
    mf4 = mdf.convert('4.10')
  
# Description
if groups is empty it runs to an error.

**Comment by danielhrisca** [comment]
I think this is already fixed in the development branch
can you check?
