### ISSUE TITLE
Is it possible to append a bool signal ?

### ISSUE THREAD

**Issue by dglent** [danielhrisca/asammdf#53]
# Python version
('python=3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit '
 '(Intel)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.13.3'
'asammdf=3.2.1'
# Code 
the existing signal ter15st has logical type in inca: 
>>> mdffile.get('Ter15st')
Signal(name=Ter15st\CCP:1, samples=array([1, 1, 1, ..., 1, 1, 1], dtype=uint8), timestamps=array([   3.1090906 ,    3.1205086 ,    3.1292956 , ...,  245.62956445,
        245.6399234 ,  245.64957463]), unit=-, conversion={'id': b'CC', 'block_len': 62, 'range_flag': 0, 'min_phy_value': 0.0, 'max_phy_value': 0.0, 'unit': b'-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'conversion_type': 0, 'ref_param_nr': 2, 'b': 0.0, 'a': 1.0}, comment=Terminal 15 status
Terminal 15 status, raw=False)
  ## Code snippet
simt = timestamps array copied form an existing signal
siml = list of values (1, 0) copied from an existing signal
>>> sl = np.asarray(siml, dtype=bool)
>>> sig = asammdf.Signal(sl, simt, name='NewSignal')
>>> sig
Signal(name=NewSignal, samples=array([ True,  True,  True, ...,  True,  True,  True], dtype=bool), timestamps=array([   3.1090906 ,    3.1205086 ,    3.1292956 , ...,  245.62956445,
        245.6399234 ,  245.64957463]), unit=, conversion=None, comment=, raw=False)
>>> len(sl)
24222
>>> len(simt)
24222
>>> mdffile.append([sig,])
  
  ## Traceback
Traceback (most recent call last):
  File "<pyshell#48>", line 1, in <module>
    mdffile.append([sig,])
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\mdf_v3.py", line 1356, in append
    signal.samples.shape,
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\utils.py", line 359, in fmt_to_datatype_v3
    raise MdfException(message.format(fmt, shape))
asammdf.utils.MdfException: Unknown type: dtype=bool, shape=(24222,)_
  
# Description
Is it possible to append a bool type signal ?
The goal would be to show the signal in the viewer MDA as logical type (graph at the bottom)

Thanks in advance

**Comment by danielhrisca** [comment]
Hello,

please give this a try https://github.com/danielhrisca/asammdf/commit/c747f5ec0fdca2bc6330b58ec8f537837a65598f

**Comment by dglent** [comment]
I could write the new signal with dtype bool and save the file.
However, in inca is displayed as 'unsigned int    (8 bits)' and not as a Logical signal.

Then i tried to read the saved file with error:

>>> sl = np.asarray(sims, dtype=bool)
>>> sl
array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)
len(s
>>> l)
>>> len(sl)
24222
>>> sig = asammdf.Signal(sl, simt, name='NewSignal')
>>> sig
Signal(name=NewSignal, samples=array([ True,  True,  True, ...,  True,  True,  True], dtype=bool), timestamps=array([   3.1090906 ,    3.1205086 ,    3.1292956 , ...,  245.62956445,
        245.6399234 ,  245.64957463]), unit=, conversion=None, comment=, raw=False)
>>> mdffile.append([sig,])
>>> mdffile.save()
'CutOut04.dat.mdf'
>>> mdf3file = asammdf.MDF('CutOut04.dat.mdf')
Traceback (most recent call last):
  File "<pyshell#28>", line 1, in <module>
    mdf3file = asammdf.MDF('CutOut04.dat.mdf')
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\mdf.py", line 78, in __init__
    self._mdf = MDF3(name, memory)
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\mdf_v3.py", line 188, in __init__
    self._read()
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\mdf_v3.py", line 869, in _read
    new_ch.comment = get_text_v3(address, stream)
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\utils.py", line 123, in get_text_v3
    text_bytes = stream.read(size)
ValueError: read length must be positive or -1
>>>

**Comment by danielhrisca** [comment]
Hello Dimitros,

the latest commit from development should save the boolean signals as single bit channels. This means INCA should see them as logical channels.

**Comment by dglent** [comment]
I tried with another dat file, i have the same issue when opening the file by INCA; it sees the signal as 'unsigned int (8 bits)'. However i don't have any problem to read the saved file. When i read the saved file, the NewSignal has not any more a logical signal type but a 'uint8'

>>> mdfafile = asammdf.MDF('Test.dat')
>>> mdfafile.append([sig,])
>>> mdfafile.save()
'Test.dat.mdf'
>>> mdfaafile = asammdf.MDF('Test.dat.mdf')
>>> mdfaafile.get('NewSignal')
Signal(name=NewSignal, samples=array([1, 1, 1, ..., 1, 1, 1], dtype=uint8), timestamps=array([   3.1090906 ,    3.1205086 ,    3.1292956 , ...,  245.62956445,
        245.6399234 ,  245.64957463]), unit=, conversion=None, comment=, raw=False)
>>> sig
Signal(name=NewSignal, samples=array([ True,  True,  True, ...,  True,  True,  True], dtype=bool), timestamps=array([   3.1090906 ,    3.1205086 ,    3.1292956 , ...,  245.62956445,
        245.6399234 ,  245.64957463]), unit=, conversion=None, comment=, raw=False)

**Comment by danielhrisca** [comment]
It should be fixed with the latest commit. Let me know if it works

**Comment by dglent** [comment]
It is still displayed as 'unsigned int (8 bits)'.

**Comment by danielhrisca** [comment]
```python
from asammdf import MDF, Signal
import numpy as np

mdf = MDF(version='3.30')

sig = Signal(
    np.array([0,0,1,1], dtype=bool),
    np.arange(4),
    name="Logic",
)

mdf.append([sig])
mdf.save('test.mdf', overwrite=True)

mdf = MDF('test.mdf')

print(mdf.get("Logic", samples_only=True).dtype)
```

for me it prints **bool**

![image](https://user-images.githubusercontent.com/20952040/37295166-2442800c-2620-11e8-877b-f808445198b9.png)

I assumed INCA treats single bit channels as logical.

**Comment by dglent** [comment]
Sorry but i updated the devel version with pip install <package> and it seems that this doesn't update all the files (i suppose because the version is the same).
After uninstalling the installed version with pip uninstall and installing it again i have the latest version of the development branch and the Logical type is well defined.

It works as expected now

Thanks

**Comment by danielhrisca** [comment]
In _asammdf 3.3.2_ the default _get_ behaviour for single bit channels is _uin8_ instead of _bool_

You will have to use the _configure_ method to get _bool_:

```python
from asammdf import MDF, Signal
import numpy as np

mdf = MDF(version='3.30')
mdf.configure(single_bit_uint_as_bool=True)

sig = Signal(
    np.array([0,0,1,1], dtype=bool),
    np.arange(4),
    name="Logic",
)

mdf.append([sig])
mdf.save('test.mdf', overwrite=True)

mdf = MDF('test.mdf')

print('Default:', mdf.get("Logic", samples_only=True).dtype)

mdf.configure(single_bit_uint_as_bool=True)
print('As bool:', mdf.get("Logic", samples_only=True).dtype)

```

prints 
```
Default: uint8
As bool: bool
```

**Comment by dglent** [comment]
I updated to 3.4.0. (Great feature the gui !)
I tested and it works. I didn't modify anything. I don't apply the configure method and still the signal is recognized as 'bool' in inca but it is uint8 in the print output (as the example above).

However, you suggest to apply the 'configure(single_bit_uint_as_bool=True)' in any case ?

**Comment by danielhrisca** [comment]
Configure the book option if you want to get a numpy book array when you call the _get_ method.

Check out the latest development GUI script. You can now use keyboard shortcuts to fit and stack channels and you can also get statistics using a single cursor or a range
