### ISSUE TITLE
AttributeError: 'MDF4' object has no attribute 'flags'

### ISSUE THREAD

**Issue by hh-h** [danielhrisca/asammdf#532]
# Python version

('python=3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) \n'
 '[Clang 6.0 (clang-600.0.57)]')
'os=macOS-10.15.7-x86_64-i386-64bit'
'numpy=1.21.0'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=6.2.2'

# Description

MDF v4 doesn't have flags attributes, probably a typo, checked 6.2.0 and 6.2.2 from master
see https://github.com/danielhrisca/asammdf/blob/31d0c2a9c9c013c3fec667d52339788e241444fa/asammdf/blocks/mdf_v4.py#L9614 and https://github.com/danielhrisca/asammdf/blob/31d0c2a9c9c013c3fec667d52339788e241444fa/asammdf/blocks/mdf_v4.py#L9647

# Traceback
```
Traceback (most recent call last):
  File ".../mf4/p.py", line 3, in <module>
    MDF("bg/canlog_19504_20210708_170111.mf4")
  File ".../venvs/mf4/lib/python3.9/site-packages/asammdf/mdf.py", line 204, in __init__
    self._mdf = MDF4(name, channels=channels, **kwargs)
  File ".../venvs/mf4/lib/python3.9/site-packages/asammdf/blocks/mdf_v4.py", line 390, in __init__
    self._read(mapped=False)
  File ".../venvs/mf4/lib/python3.9/site-packages/asammdf/blocks/mdf_v4.py", line 503, in _read
    self._finalize()
  File ".../venvs/mf4/lib/python3.9/site-packages/asammdf/blocks/mdf_v4.py", line 9650, in _finalize
    if self.flags & v4c.FLAG_DL_EQUAL_LENGHT:
AttributeError: 'MDF4' object has no attribute 'flags'
```

**Comment by danielhrisca** [comment]
@hh-h can you check with the development branch code?

**Comment by hh-h** [comment]
Yesterday I wrote the reply and forgot to send it. 😞 

Unfortunately, it was a broken file, the correct version works fine even with the PyPI version (6.2.0) as well as from the development branch.

So, feel free to close, since you fixed the AttributeError exception.
