### ISSUE TITLE
'MDF4' object has no attribute '_raise_on_mutiple_occurences'

### ISSUE THREAD

**Issue by pebel76260** [danielhrisca/asammdf#533]
# Python version
'python=3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.19041-SP0'
'numpy=1.20.2'
'asammdf=6.2.0'

# Code 

  ## MDF version
4.10

  ## Code snippet
mdf_obj_ = mdf_obj.filter([var])
'var has duplicates in file'
  
  ## Traceback

    mdf_obj = mdf_obj.filter(signalNamesList)
  File ".[...]\lib\site-packages\asammdf\mdf.py", line 1587, in filter
    gps = self.included_channels(channels=channels)
  File "[...]\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7542, in included_channels
    group, idx = self._validate_channel_selection(name)
  File "[...]\lib\site-packages\asammdf\blocks\mdf_common.py", line 125, in _validate_channel_selection
    if self._raise_on_mutiple_occurences:
AttributeError: 'MDF4' object has no attribute '_raise_on_mutiple_occurences'

**Comment by pebel76260** [comment]
Duplicate...

**Comment by Nuteen** [comment]
Would you mind sharing how you managed to solve this problem？

**Comment by danielhrisca** [comment]
> Would you mind sharing how you managed to solve this problem？

Do not use the MF4 class directly, you have to use the MDF class

**Comment by Nuteen** [comment]
I have already done it like “mdf = MDF(mf4_file_path)”,is this what you meant?

**Comment by Nuteen** [comment]
> > Would you mind sharing how you managed to solve this problem？
> 
> Do not use the MF4 class directly, you have to use the MDF class

I have already done it like “mdf = MDF(mf4_file_path)”,is this what you meant?

**Comment by danielhrisca** [comment]
You should not get the attribute error with the latest release
