### ISSUE TITLE
KeyError: 'mapped' bei: asammdf.blocks.v4_blocks.SourceInformation(address=acq_source_addr, stream=stream)

### ISSUE THREAD

**Issue by s9mahueb** [danielhrisca/asammdf#536]
# Python version
('python=3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.20.2'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=6.2.0'

  ## MDF version
4.1

  ## Code snippet
```python
channelist = ['Accel','Brk2']
channelistSource = ['','']

listeNamesAll = []
listeUnitsAll = []
listeSourceAll = []
listeSourceGroupAll = []
 
listeNames = []
listeUnits = []
listeSource = []
listeSourceGroup = []
 
from asammdf import MDF, Signal
import asammdf
import scipy.io as sio
 
print(r"C:\Users\u16j17\Desktop\1.MF4")
obj = MDF(r"C:\Users\u16j17\Desktop\1.MF4")
obj4Units = MDF(r"C:\Users\u16j17\Desktop\1.MF4")
obj4Units = obj4Units.resample(raster=10000000000000000000000)
 
My_Name_Group_All = []
for Signal in obj4Units:
	signal_name = Signal.name
	Tuple_Group_Index = obj4Units.whereis(signal_name)
	for i in range(0,len(Tuple_Group_Index)):
		TGI = Tuple_Group_Index[i]
		SignalSub = obj4Units.get(group=TGI[0],index=TGI[1])
		if not [ SignalSub.name, TGI[0] ] in My_Name_Group_All:	
			My_Name_Group_All.append([ SignalSub.name, TGI[0] ])
			#print(SignalSub.name +' \ ' + SignalSub.source.name)
			#print(TGI)
			#ChannelGroup-Source-Name ermitteln:
			group_index = TGI[0]
			gr_address = obj.groups[group_index]
			cg_adress = gr_address['channel_group']
			acq_source_addr = cg_adress['acq_source_addr']
			stream = obj._file
			#print(acq_source_addr)
			if acq_source_addr == 0:
				#Falls Adress-Eintrag in si_md_comment nicht exisitiert:
				cg_source_name = ''
			else:	
				s_block = asammdf.blocks.v4_blocks.SourceInformation(address=acq_source_addr, stream=stream)
				cg_source_name = s_block.name
 
			listeNamesAll.append(Signal.name)
			listeUnitsAll.append(SignalSub.unit)
			listeSourceAll.append(SignalSub.source.name)
			listeSourceGroupAll.append(cg_source_name)
```
  
  ## Traceback
```python
Traceback (most recent call last):
  File "D:\batch.py", line 52, in <module>
    s_block = asammdf.blocks.v4_blocks.SourceInformation(address=acq_source_addr, stream=stream)
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v4_blocks.py", line 5680, in __init__
    mapped = kwargs["mapped"]
KeyError: 'mapped'
```

## Description

Ich sende dir eine gescrambelte Beispieldatei zu.

Der Code hat schon einmal auf anderen Daten funktioniert. Ich bekomme jetzt obige Fehlermeldung. Betrifft dieses Problem evtl. auch die dat-Dateien (v3) ? Bitte hilf mir bei der Problembehebung.

Vielen Dank im Voraus und Grüße.
Martin

**Comment by danielhrisca** [comment]
Hello Martin,

you can try this

```python
s_block = asammdf.blocks.v4_blocks.SourceInformation(address=acq_source_addr, stream=stream, mapped=False)
```

but normally you can check the channel group source directly and you don't need to parse it again from the file

```python
cg_source_name  = "" if gr_address['channel_group'].acq_source is None else gr_address['channel_group'].acq_source.name
```

**Comment by s9mahueb** [comment]
Hello Daniel,

thanks for the code. I have just basic-skills in programming, so its shure that there is a better way ;)

For the first version i get a new error:

    s_block = asammdf.blocks.v4_blocks.SourceInformation(address=acq_source_addr, stream=stream, mapped=False)
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v4_blocks.py", line 5709, in __init__
    tx_map = kwargs["tx_map"]
KeyError: 'tx_map'

Can we solve the tx_map-error?

For the second version i have replaced the if-else-content by your code. The error message is still the same.

Best regards,
Martin
