### ISSUE TITLE
mdf v3: Can get Units directly via Signal.unit, but Signal.unit is empty by getting the Signal with get-Method

### ISSUE THREAD

**Issue by s9mahueb** [danielhrisca/asammdf#538]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.20.2'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=6.2.0'
```
# Code 

  ## MDF version
  v3.3 (converted with INCA from Version 4.1)
The original 4.1-file shows not this behaviour / is working fine
Another (original) v3.0 file has this problem too.

  ## Code snippet
```python
from asammdf import MDF, Signal
import asammdf
 
obj = MDF(r"C:\mdfV3k3.dat")
MDFversion = obj.version
obj4Units = MDF(r"C:\mdfV3k3.dat")
 
My_Name_Group_All = []
for Signal in obj4Units:
	print('Test1 Name:' + Signal.name)
	print('Test1 (OK):' + Signal.unit)
	Tuple_Group_Index = obj4Units.whereis(signal_name)
	for i in range(0,len(Tuple_Group_Index)):
		TGI = Tuple_Group_Index[i]
		SignalSub2 = obj4Units.get(group=TGI[0],index=TGI[1])
		print('Test2 Name:' + SignalSub.name)
		print('Test2 Unit (notOK):' + SignalSub.unit)
		SignalSub3 = obj4Units.get(Signal.name)
		print('Test3 Name:' + SignalSub.name)
		print('Test3 Unit(notOK):' + SignalSub.unit)
```

# Result:

Test1 Name:TuRPM\CAN1
Test1 (OK):**rpm**
Test2 Name:TuRPM\CAN1
Test2 Unit (**notOK**):
Test3 Name:TuRPM\CAN1
Test3 Unit(**notOK**):

# Description

Hello Daniel,

I can get the signal unit directly via Signal.unit. But this does not work for Signals getting with the get-Method. The Signal.unit from get-Method is empty for mdf V3 files. V4 file units are working fine. I need this option for eqal-named Signals from different Sources and want to use the get-Method. I have no explanation why Signal.unit is/should be empty.
Please help me, i am out of my ideas.

Best regards,
Martin

**Comment by danielhrisca** [comment]
Hello @s9mahueb I think the latest development code (6.3.0.dev47) fixes this problem

**Comment by s9mahueb** [comment]
Hello Daniel, by 
python -m pip install --user asammdf==6.3.0.dev47
i get 
ERROR: No matching distribution found for asammdf==6.3.0.dev47
Is it rachable by another source?
Best regards, Martin

**Comment by s9mahueb** [comment]
Hi Daniel, the issue is still showing empty units. Best regards, Martin
