### ISSUE TITLE
get() returns wrong signal data for MDF4 format

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#55]
Hi everyone,

Since version 2.8.1, get() returns wrong signal data for a given name (i.e data from another signal I guess).

The issue is still in the development branch but like I said the issue is there since version 2.8.1. The issue was introduced after my fix in PR #23.

After the introduction of my fix in PR #23, it had somehow an impact on the _prepare_record function, so that now the returned parents from _prepared_record is wrong.

The fix that I made in _read_channels() (see PR #23) changed the order in grp['channel_dependencies']. This one was wrong before. To make a long story short, since it was a recursive function, we had to append the composition channel before doing another call to _read_channels(). Indeed, channel_dependencies have to be append in the same order as for the channels list since we use the channel index to find the corresponding dependency_list in grp['channel_dependencies'] later on when the get function is called.

Let's consider this small MDF tree:

- CH0: composition channel
  - CH1: composition channel
    - CH2: channel
    - CH3: channel

Before my fix (so in version 2.8.0), the get method was working (only for signals that were luckily without a dependency_list) and the grp['channels_dependencies'] would look like this:
[None, None, [CH2, CH3], [CH1]]
After my fix, this is how it looks like:
[[CH1], [CH2, CH3], None, None]

So now, the channels_dependencies are in the right order, but the data returned using get are wrong.

I did some investigation and my initial assumption is that the problem relies in the _prepare_record() function. I might be wrong but I think the order in which we loop over the channels in sortedchannels may be wrong, so that in the end we have wrong parent and wrong offset calculation.

It would be nice if someone can help with this issue since I am myself lacking some understandings regarding this _prepared_record function.

Best, Julien.

**Comment by danielhrisca** [comment]
Hello Julien,

there was indeed a problem with reading nested structures. 

The latest development commit should allow to read them correctly now, however saving and appending nested structures is not yet working. I will look into this later.

Please confirm with your files that at least reading is ok.

Here is the file that I've used for testing:

[struct.zip](https://github.com/danielhrisca/asammdf/files/1857441/struct.zip)

and the code snippet:

```python
from asammdf import MDF, Signal
import numpy as np

mdf = MDF()

arr = [
    np.arange(10, dtype=np.float64),
    np.arange(10, dtype=np.float64),
    np.arange(10, dtype=np.float64),
    np.arange(10, dtype=np.float64),
]

types = [
    ('S1', np.float64),
    ('S2', np.float64),
    ('S3', np.float64),
    ('S4', np.float64),
]

sig1 = np.core.records.fromarrays(arr, dtype=types)

arr = [
    -np.arange(10, dtype=np.float64),
    -np.arange(10, dtype=np.float64),
    -np.arange(10, dtype=np.float64),
    -np.arange(10, dtype=np.float64),
]

types = [
    ('T1', np.float64),
    ('T2', np.float64),
    ('T3', np.float64),
    ('T4', np.float64),
]

sig2 = np.core.records.fromarrays(arr, dtype=types)

sigs = [
    Signal(
        sig1,
        np.arange(10),
        name='Comp1',
    ),
    Signal(
        sig2,
        np.arange(10),
        name='Comp2',
    ),
]


mdf.append(sigs)
mdf.save('struct.mf4')

mdf = MDF('struct.mf4')

print(mdf.get('Comp1'))
```
that prints
```python
<Signal Comp1:
	samples=[( 0.,  0., (-0., -0., -0., -0.),  0.,  0.)
 ( 1.,  1., (-1., -1., -1., -1.),  1.,  1.)
 ( 2.,  2., (-2., -2., -2., -2.),  2.,  2.)
 ( 3.,  3., (-3., -3., -3., -3.),  3.,  3.)
 ( 4.,  4., (-4., -4., -4., -4.),  4.,  4.)
 ( 5.,  5., (-5., -5., -5., -5.),  5.,  5.)
 ( 6.,  6., (-6., -6., -6., -6.),  6.,  6.)
 ( 7.,  7., (-7., -7., -7., -7.),  7.,  7.)
 ( 8.,  8., (-8., -8., -8., -8.),  8.,  8.)
 ( 9.,  9., (-9., -9., -9., -9.),  9.,  9.)]
	timestamps=[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
	unit=""
	conversion=None
	source=None
	comment=""
	mastermeta="('Time', 1)"
	raw=False
	display_name=>
```

**Comment by danielhrisca** [comment]
To be more exact the _\_prepare_record_ method was ok, but the recursive call to _\_read_channels_ in case of structure was overwriting the _composition_ local variable.

**Comment by danielhrisca** [comment]
The code snippet creates 2 disjoint structures and I used HxD to modify some addresses so that the second structure would appear as nested in the first one

Initial file:
![image](https://user-images.githubusercontent.com/20952040/38052202-1d5e8b4e-32d9-11e8-81ac-625050dbed87.png)

and final modified one:
![image](https://user-images.githubusercontent.com/20952040/38052224-2f8c6d22-32d9-11e8-872e-f3a77fca4dda.png)

**Comment by JulienGrv** [comment]
Reading is still not working with current development. I already tried this with the returned composition.
I really do think the error arises in _prepare_record().

**Comment by danielhrisca** [comment]
Is it possible to send your file via email? If not I'll try to replicate the exact structure from your first post

**Comment by JulienGrv** [comment]
I cannot send you the file unfortunately. Can you tell me why your are sorting the channels in _prepare_record() (line 1436)? Generally speaking, maybe you can provide me with some hints about this function.

As I understand, offset is calculated depending on the previous channel, isn't it? So they need to be looped in the same order as we see the channels in MDF Validator or?

**Comment by danielhrisca** [comment]
The sorting is done to be able to process the data block using a numpy recarray

The channels are first ordered ascending (see method __lt__ of Channel class). If the channel's start bit is lower then the channel is "smaller", and if they have the same start bit then the one with a higher bit count is "smaller".

The idea is that normally, in case of overlapping channels, you should be able to extract a channel from it's parent, the parent being the "smaller" channel.

For simple data groups (no overlapping channels; all channels properly byte aligned and standard C type size) all channels will be their own parents.

A not byte aligned channel is flagged if it partially overlaps with the current parent but it also extends a bit to higher bit position in the record
```
        first parent  second                    current parent
bit0|-----------------|--------------------| ....   |----------------------|
                                                            |------------------------|  not byte aligned channel
                                                        |----------------|                       this is not flagged since it can be extracted from the parent
```
Parents are always 8byte multiples, and are the fields of the recarray that is used to process the samples.

This algorithm is not perfect but 99% of the time it works OK and all channels have a parent, and in case of more exotic bit size channels there should not be so many channels without a parent.

**Comment by JulienGrv** [comment]
In my case I have a channel and when I print it's parent, I am surprised that it is another channel that is different then the one I had before that I fixed the appending of ret_composition in grp['channel_dependencies']. So somehow, fixing this appending has broken the behaviour of _prepare_record().

Thank you for your explanation, I will investigate a little bit today this issue.

**Comment by danielhrisca** [comment]
I've replicated your example:
![image](https://user-images.githubusercontent.com/20952040/38076236-af20fcf6-333d-11e8-85c2-bfa3a150ba52.png)
 with this code snippet and the latest development commit:

```python
from asammdf import MDF, Signal
import numpy as np

mdf = MDF()

arr = [
    np.arange(10, dtype=np.float64),
    np.arange(10, 20, dtype=np.float64),
]

types = [
    ('S1', np.float64),
    ('S2', np.float64),
]

sig1 = np.core.records.fromarrays(arr, dtype=types)

arr = [
    sig1,
]

types = [
    ('Comp2', sig1.dtype),
]

sig2 = np.core.records.fromarrays(arr, dtype=types)

sigs = [
    Signal(
        sig2,
        np.arange(10),
        name='Comp1',
    ),
]


mdf.append(sigs)
mdf.save(r'struct_julien.mf4', overwrite=True)

mdf = MDF(r'struct_julien.mf4')

print(mdf.get('Comp1'))

values = mdf.get('Comp1')

print(values['Comp2']['S1'])
print(values['Comp2']['S2'])
```
and it looks correct to me:
```python
<Signal Comp1:
	samples=[((0., 10.),) ((1., 11.),) ((2., 12.),) ((3., 13.),) ((4., 14.),)
 ((5., 15.),) ((6., 16.),) ((7., 17.),) ((8., 18.),) ((9., 19.),)]
	timestamps=[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
	unit=""
	conversion=None
	source=None
	comment=""
	mastermeta="('Time', 1)"
	raw=False
	display_name=>

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
```

**Comment by JulienGrv** [comment]
I have a much more complex MDF4 file to be honest, I don't know if you will be able to reproduce it. The thing I can tell you is that the parent of the channel I am trying to get has the same byte_offset, bit_offset and bit_count value.

**Comment by danielhrisca** [comment]
That should not be a problem if both channels have the same data type. Could you share some MDFValidator screenshots?

**Comment by danielhrisca** [comment]
That should not be a problem if both channels have the same data type. Could you share some MDFValidator screenshots?

Another error cause could be that the structure members are retrieved by name, so if you have repeating names in the file the first occurrence will be used.

**Comment by danielhrisca** [comment]
The previous comment is not completely true: the members are retrieved by name and by group index. This means the there could be a problem if the member occurs earlier in the same group.

**Comment by JulienGrv** [comment]
Okay so I found out that the signal data returned when I get() are the parent signal data. So the error is that the parent of the signal I try to get should be the signal itself I guess.
Regarding what you said the signal I try to get has only one occurrence in the whole file, as well as for its parent.

**Comment by danielhrisca** [comment]
Please try the latest commit from development as it should insure the correct data type.

**Comment by JulienGrv** [comment]
Awesome, this is working with the line you added regarding the type:

```python
else:
    data_type = channel['data_type']
    channel_dtype = array([], dtype=get_fmt_v4(data_type, bits))
    if vals.dtype != channel_dtype.dtype:
       vals = vals.astype(channel_dtype.dtype)
```

I feel so stupid I did not see that only the negative value are causing the issue by comparing the signal and its parent.

Daniel, thank you very much!

**Comment by JulienGrv** [comment]
I suggest you do a release as soon as you can since this is a pretty major issue. Thank you again!

**Comment by danielhrisca** [comment]
I'm waiting a bit for _canmatrix_ to release a new version on PyPI because the current one is broken. This package is used to handle CAN bus logging measurements.
