### ISSUE TITLE
Unable to view signals(i.e. channels) from v6.2 to v6.3

### ISSUE THREAD

**Issue by Nishdel101** [danielhrisca/asammdf#550]
'python=3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.18363-SP0'
'numpy=1.21.0'
'asammdf=6.3.0'

  ## MDF version
  4.10

 ##code snippet
  mdfFile = asammdf.MDF4(original_name=r"C:\<path>.mf4")
print(mdfFile.info())

  ## Traceback
Exception ignored in: <function MDF4.__del__ at 0x00000251C68BAC10>
Traceback (most recent call last):
  File "C:\WPy64-3950\python-3.9.5.amd64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 440, in __del__
    self.close()
  File "C:\WPy64-3950\python-3.9.5.amd64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 5996, in close
    if self.original_name.suffix.lower() in (".bz2", ".gzip", ".mf4z", ".zip"):
AttributeError: 'str' object has no attribute 'suffix'
{'version': '4.10', 'program': 'amdf630', 'comment': '', 'groups': 0}
  
# Description

In version 6.2.0 i was able to use the .info() function and view the number of groups ( and channel names ) from the same file. however , now in version 6.3.0 it shows that I have 0 groups, and I also cannot extract channel data as I could before.
Also I do not think the examples and documentation has been updated for the latest version as now quite a few of the old methods are not recognized.

**Comment by danielhrisca** [comment]
> ##code snippet
> mdfFile = asammdf.MDF4(original_name=r"C:<path>.mf4")
> print(mdfFile.info())

You should not use the ``original_name`` argument, and also you should not use the MDF4 or MDF3 classes directly, instead use the MDF class like this

```python
mdfFile = asammdf.MDF(r"C:<path>.mf4")
print(mdfFile.info())
```

**Comment by Nishdel101** [comment]
Thank you , it worked now. Am able to view the info as before
