### ISSUE TITLE
GUI Display faults

### ISSUE THREAD

**Issue by Nishdel101** [danielhrisca/asammdf#551]
# Python version
'python=3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit '
'(AMD64)]')
'os=Windows-10-10.0.18363-SP0'
'numpy=1.21.0'
'asammdf=6.3.0'

  ## MDF version
4.10
  
# Description

 I can view the signals values via "plot, numeric or tabular" 
 However for some of the signals , the only the numeric  method to view the values works . The plot and tabular method do not show any values in this case even tho the plot does show the correct signal waveform.

![tabular](https://user-images.githubusercontent.com/67369744/127487747-c044b8ef-f5ac-497c-8b20-4634e20d4fad.PNG)
![numeric](https://user-images.githubusercontent.com/67369744/127487751-1c0fd053-6313-4160-8d03-357376955a53.PNG)
![plot warning](https://user-images.githubusercontent.com/67369744/127487753-854f584f-9329-4c03-b959-49a85695fe72.PNG)
![plot](https://user-images.githubusercontent.com/67369744/127487756-332b5fb9-ada4-4358-b60b-c4ee0dfa8e19.PNG)

**Comment by danielhrisca** [comment]
The channel has a value to text conversion rule. For the value 53 there is no text associated, so the default value is used, which is the empty string.

To view the raw values press "Alt+R"

**Comment by Nishdel101** [comment]
Thanky you !.
The same problem occurs when using the library to extract data(without the gui). For some signals i am able to extract the values whereas for some signals the output i get is usually " b' ' " or " b 'SNA' ". 
Is there a way that I can extract these raw values ( without the use of the  gui ) ?

**Comment by danielhrisca** [comment]
see https://github.com/danielhrisca/asammdf/issues/547

**Comment by Nishdel101** [comment]
Thank you so much ! Im able to extract the values as intended. :)

**Comment by Nishdel101** [comment]
Just checked . The "Alt + R " method does not work when in the tabular display mode in the GUI

**Comment by danielhrisca** [comment]
> Just checked . The "Alt + R " method does not work when in the tabular display mode in the GUI

Yes this command only works with the Plot window
