### ISSUE TITLE
GUI Feature Request: Quick Channel Filtering

### ISSUE THREAD

**Issue by zariiii9003** [danielhrisca/asammdf#552]
# Description

Hello Daniel,

could you add a QLineEdit in between the "Natural Sort" ComboBox and the channel list? The QLineEdit could have a QCompleter for channel name suggestions. The valueChanged signal should filter the channels in the channel list below via a [wildcard pattern matching ](https://docs.python.org/3/library/fnmatch.html).

![image](https://user-images.githubusercontent.com/52598363/127615518-fd20adb2-2693-4bc5-89be-5a852d6372fb.png)

**Comment by danielhrisca** [comment]
Hello @zariiii9003 

this was available in the past but it is really problematic to use with long channel names and it is also slow with large channel count. The suggested way is to use the search dialog (CTRL+F)

**Comment by zariiii9003** [comment]
@danielhrisca I see, thank you for your reply
