### ISSUE TITLE
Very different file sizes by version-conversion (Original file vs. asammdf.exe vs. append signal/save) 

### ISSUE THREAD

**Issue by s9mahueb** [danielhrisca/asammdf#553]
# Python version
```python
('python=3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.20.2'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=6.3.1.dev2'
```
# Code 

  ## MDF version
4.10

  ## Code snippet 1
```python
#coding: latin-1 
from asammdf import MDF, Signal
import asammdf
 
compressionVal = 1
newVersion = "4.10"
obj = MDF(r"C:\File.mf4")
obj2 = MDF(version = newVersion)
for Signal in obj:
    obj2.append(Signal)
obj2.save(r"C:\FileNew.dat", overwrite=True, compression=compressionVal)
obj2.close
obj.close
```
  
# Description

Hi Daniel,

i had an look onto the file sizes and saw that they are very different and partly very large. (by the 15MB file i send to you)

Here the overview for conversion into 4.1:
Original file (v4.1 version) : 15MB
asammdf.exe, compression=1 : 6,5MB
asammdf.exe, compression=2 : 5,7MB
The code above, compression=1: 36,5MB
The code above, compression=2: 31,9MB

And also the conversion into 3.3:
asammdf.exe : 15MB
The code above : 55,6MB

(The backround is, that i normaly have to work with 250MB files and there i reach 500-800MB per file.)

Do you know a reasen for the different sizes? Can you help me to reach at least the original-filesize or the size from asammdf.exe, please ?

Best regards,
Martin

**Comment by danielhrisca** [comment]
> Original file : v4.1, 15MB

> asammdf.exe, v4.1, compression=1 : 6,5MB
> asammdf.exe, v4.1, compression=2 : 5,7MB

The exe uses the function `convert` that processes channel groups. In a channel group all the channels share a common time channel known as the `master` channel. 

> The code above, compression=1: 36,5MB
> The code above, compression=2: 31,9MB

In your code you create a new channel group for each channel this leads to a lot of wasted space because of data duplication of the master channel

**Comment by s9mahueb** [comment]
Ok thank you! You are right, this sounds not like the best solution. So i have to wait for #545 (my Problem with conversion-Method).

Best regards!
