### ISSUE TITLE
Ignore invalid signals results in signal value change instead of removal

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#555]
Version: 6.3.1
Test data and DBC: [test-data.zip](https://github.com/danielhrisca/asammdf/files/6916282/test-data.zip)

**Observation**
When decoding attached files without using "ignore invalid signals", the 1-bit signals TimeValid and TimeConfirmed correctly change from 0 to 1 in the log file sample as shown below:
![image](https://user-images.githubusercontent.com/26184427/127849400-11b05b66-7e20-4b6f-886a-ec5b755390cd.png)

However, when enabling "ignore invalid signals", both signals are still included - yet they are 0 throughout the log file:
![image](https://user-images.githubusercontent.com/26184427/127849624-fd45e83f-e9fe-40a0-953f-3158ba9dc66c.png)

**Ideal behavior** 
I suggest the following changes:
1) Ignore invalid signals only has an effect for J1939 data (as it's not necessarily used similarly in other CAN protocols)
2) Ignore invalid signals only has effect for 2+ bit signals as per below table - this is how it is outlined in the J1939 protocol:
![IMG_4229](https://user-images.githubusercontent.com/26184427/127850213-7243af80-23b1-4f24-93dd-4914f545df50.JPG)

3) Ignore invalid signals removes a signal entirely if the signal is constantly an invalid value throughout the log file. However, if the signal has alternating values, some of which are in the invalid range, the signal remains included (not 100% sure on this one, so happy to hear inputs)

I would at least suggest changing the current behavior where the values that are considered "invalid" are set to 0 as this will in particular cause confusion for low-bit signals.

Martin

**Comment by AutomationSavant** [comment]
I have this exact same issue, it took a couple of hours to figure out it was that check box
