### ISSUE TITLE
python AttributeError: module 'asammdf.blocks.v4_constants' has no attribute 'DATA_TYPE_UNSIGNED'

### ISSUE THREAD

**Issue by yhatley** [danielhrisca/asammdf#557]
# Python version
python=3.9.2
os=Windows-10-10.0.18362-SP0
numpy=1.20.1
asammdf=6.3.1

# Code 

  ## MDF version
  version 4

  ## Code snippet
m = asammdf.MDF(r'abc.mf4')

  ## Traceback
 AttributeError                            Traceback (most recent call last)
<ipython-input-3-d8f355643774> in <module>
----> 1 m = asammdf.MDF(r'abc.mf4')
c:\users\username\appdata\local\programs\python\python39\lib\site-packages\asammdf\mdf.py in __init__(self, name, version, channels, **kwargs)
    234                 self._mdf = MDF3(name, channels=channels, **kwargs)
    235             elif version in MDF4_VERSIONS:
--> 236                 self._mdf = MDF4(name, channels=channels, **kwargs)
    237             elif version in MDF2_VERSIONS:
    238                 self._mdf = MDF2(name, channels=channels, **kwargs)
c:\users\username\appdata\local\programs\python\python39\lib\site-packages\asammdf\blocks\mdf_v4.py in __init__(self, name, version, channels, **kwargs)
    415                         self._file = mmap.mmap(x.fileno(), 0, access=mmap.ACCESS_READ)
    416                         self._from_filelike = False
--> 417                         self._read(mapped=True)
    418
    419                         self._file.close()
c:\users\username\appdata\local\programs\python\python39\lib\site-packages\asammdf\blocks\mdf_v4.py in _read(self, mapped)
    623                 # Read channels by walking recursively in the channel group
    624                 # starting from the first channel
--> 625                 self._read_channels(
    626                     ch_addr, grp, stream, dg_cntr, ch_cntr, mapped=mapped
    627                 )
c:\users\username\appdata\local\programs\python\python39\lib\site-packages\asammdf\blocks\mdf_v4.py in _read_channels(self, ch_addr, grp, stream, dg_cntr, ch_cntr, channel_composition, mapped)
   1066
   1067                 channel.dtype_fmt = dtype(
-> 1068                     get_fmt_v4(
   1069                         channel.data_type,
   1070                         channel.bit_offset + channel.bit_count,
c:\users\username\appdata\local\programs\python\python39\lib\site-packages\asammdf\blocks\utils.py in get_fmt_v4(data_type, size, channel_type)
    452         if size > 64 and data_type in (
    453             v4c.DATA_TYPE_UNSIGNED_INTEL,
--> 454             v4c.DATA_TYPE_UNSIGNED,
    455         ):
    456             fmt = f"({size // 8},)u1"
AttributeError: module 'asammdf.blocks.v4_constants' has no attribute 'DATA_TYPE_UNSIGNED'
 
# Description

Attribute DATA_TYPE_UNSIGNED is accessed if the data size>64, but it is not defined in v4_constants.py.
DATA_TYPE_UNSIGNED_MOTOROLA is defined instead.

Best regards,

**Comment by danielhrisca** [comment]
I've pushed a fix to development

**Comment by yhatley** [comment]
Thank you!
