### ISSUE TITLE
Multiple xml + .dbc file support ?

### ISSUE THREAD

**Issue by Nishdel101** [danielhrisca/asammdf#560]
# Python version
'python=3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit '
'(AMD64)]')
'os=Windows-10-10.0.18363-SP0'
'numpy=1.21.0'
'asammdf=6.3.0'

  ## MDF version
4.10

##Code snippet

mdf = MDF(r"C:\xxx.mf4")
database_path=r"C:\xxx.arxml"
#adding the database file
can_signal= mdf.get_can_signal('xyz_signal', database=database_path, ignore_invalidation_bits=False, data=None, raw=False, ignore_value2text_conversion=True)
print(can_signal)

##Error

in get_can_signal
raise MdfException(f'No logging from "{signal}" was found in the measurement')

MdfException: No logging from "xyz_signal" was found in the measurement
  
# Description
I have some channels which are quite possibly not present in one xml file but in another .dbc file or .xml file. Is it possible to import from both of them at the same time simultaneously , within your module ?
Or is there something im doing wrong above ? As i am able to view the very same signal in software like CANape

**Comment by Nishdel101** [comment]
When i run  mdf.info(), i get output that look like this -

name="CAN_DataFrame" type=VALUE', 'channel 2': 'name="CAN_DataFrame.DataBytes" type=VLSD', 'channel 3': 'name="CAN_DataFrame.DataLength" type=VALUE', 'channel 4': 'name="CAN_DataFrame.DLC" type=VALUE', 'channel 5': 'name="CAN_DataFrame.BRS" type=VALUE', 'channel 6': 'name="CAN_DataFrame.EDL" type=VALUE', 'channel 7': 'name="CAN_DataFrame.Dir" type=VALUE', 'channel 8': 'name="CAN_DataFrame.IDE" type=VALUE', 'channel 9': 'name="CAN_DataFrame.ID" type=VIRTUAL', 'channel 10': 'name="CAN_DataFrame.BusChannel" type=VIRTUAL'}, 'group 628': {'cycles': 761, 'comment': '<CGcomment>\r\n\t<TX></TX>\r\n\t<common_properties>\r\n\t\t<e name="MessageID" ci="1">2520908169</e>\r\n</common_properties>\r\n</CGcomment>', 'channels count': 11, 'channel 0': 'name="time" type=MASTER', 'channel 1': 'name="CAN_DataFrame" type=VALUE', 'channel 2': 'name="CAN_DataFrame.DataBytes" type=VLSD', 'channel 3': 'name="CAN_DataFrame.DataLength" type=VALUE', 'channel 4': 'name="CAN_DataFrame.DLC" type=VALUE', 'channel 5': 'name="CAN_DataFrame.BRS" type=VALUE', 'channel 6': 'name="CAN_DataFrame.EDL" type=VALUE', 'channel 7': 'name="CAN_DataFrame.Dir" type=VALUE', 'channel 8': 'name="CAN_DataFrame.IDE" type=VALUE', 'channel 9': 'name="CAN_DataFrame.ID" type=VIRTUAL', 'channel 10': 'name="CAN_DataFrame.BusChannel" type=VIRTUAL'}, 



I am instead trying to search for the signal names which are not represented here

**Comment by danielhrisca** [comment]
@Nishdel101 maybe you could use ``MDF.extract_bus_logging`` (see https://asammdf.readthedocs.io/en/master/api.html#asammdf.mdf.MDF.extract_bus_logging) with your databases and check out the output file for "xyz_signal"

**Comment by Nishdel101** [comment]
Ahh yess thanks it worked . 
I had tried that before but think I made a mistake in reading it after extracting . 


What exactly is the difference between get_can_signal and extract_bus_logging ?
