### ISSUE TITLE
read .mf4 file

### ISSUE THREAD

**Issue by vaibhavsm123** [danielhrisca/asammdf#561]
asammdf.blocks.utils.MdfException: "test_file.mf4" is not a supported MDF file; "6.0" file version was found

getting error for reading .mf4 file using asammdf.MDF

**Comment by danielhrisca** [comment]
> asammdf.blocks.utils.MdfException: "test_file.mf4" is not a supported MDF file; "6.0" file version was found
> 
> getting error for reading .mf4 file using asammdf.MDF

most likely the file is not a valid Measurement Data File (MDF) (not much info from your issue description)

run this and share the output
```python
with open(file, 'rb') as f:
  print(f.read(64))
```

**Comment by vaibhavsm123** [comment]
Hi,

got this output after running your code --->   b'dSPACE Interchange Data File Rev 6.0    \x00\x00 \x00\x00\x00\x06\x00\x00\x00o\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

**Comment by danielhrisca** [comment]
That file has nothing to do with the MDF format
