### ISSUE TITLE
Color does not update on right Y axis signal plot

### ISSUE THREAD

**Issue by MartinAl1337** [danielhrisca/asammdf#565]
# Description

This problem occurs when wanting to update the color of a decoded CAN signal in a plot. The color on the right Y axis does not update with the current color of the CAN signal. Attached is an image showing this after the color has been changed, but the Y axis of that signal remains the same. (In this case the signal is now green, but the Y axis on the right remains orange)
![Y axis singal color does not update](https://user-images.githubusercontent.com/89657214/131890575-dbeb3275-5f25-49ef-8ae9-0e4d728e76b9.PNG)

**Comment by danielhrisca** [comment]
I think you meant the right axis , please try the development branch code

**Comment by MartinAl1337** [comment]
Yes. Sorry for the mistake. I just updated it on my original issue.
