### ISSUE TITLE
Uppercase .MF4 files are not shown in GUI open file

### ISSUE THREAD

**Issue by jmtatsch** [danielhrisca/asammdf#567]
## MDF version
  6.4.4

GUI - > File -> Open (a folder with measurement files as they come from CANape) -> no files are shown for filter 'All files'
Once the extension is changed to .mf4 they show up.

Maybe this can be made case agnostic?

**Comment by danielhrisca** [comment]
![image](https://user-images.githubusercontent.com/20952040/132745270-2e781be3-fc87-4399-bee7-e327ac967efd.png)

Seems to work

**Comment by jmtatsch** [comment]
Hmm, seems to be a platform problem then, I am on Ubuntu 20.04.3 LTS

![Screenshot from 2021-09-10 10-52-54](https://user-images.githubusercontent.com/3080674/132828014-93a8b360-7f8d-43ce-beaa-d769e3964519.png)
![Screenshot from 2021-09-10 10-53-32](https://user-images.githubusercontent.com/3080674/132828015-834eae5d-199d-4308-9fbd-b32f56f255a3.png)

**Comment by danielhrisca** [comment]
this a Qt problem for Linux (see https://stackoverflow.com/questions/34858220/qt-how-to-set-a-case-insensitive-filter-on-qfiledialog)

please try the latest development branch code

**Comment by jmtatsch** [comment]
That fixes it for me.
Thank you very much for this package and your support.
