### ISSUE TITLE
Error with converting "multiple occurrences"

### ISSUE THREAD

**Issue by Hadrovic** [danielhrisca/asammdf#568]
# Python version
'python=3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.18363-SP0'
'numpy=1.21.2'
'asammdf=6.4.4'

  ## Code snippet
```
from asammdf import MDF
def mf4converter(number,form):
    with MDF('data'+number+'.mf4') as mdf_file:
     signals = mdf_file.select(['MO_Fahrer_bremst'],
                                raw=True,
                                copy_master=True)
with MDF(version='4.10') as mf4_file:
        mf4_file.append(signals)
        export_filename = 'data'+number+'.csv'
        mf4_file.export(fmt=form,
                      filename=export_filename,
                      single_time_base=True,
                      raster=None,
                      time_from_zero=True,
                      empty_channels='skip',
                      reduce_memory_usage=False)
mf4converter('1','csv')
```

asammdf - ERROR - Multiple occurrences for channel "MO_Fahrer_bremst": ((373, 12), (385, 12), (386, 12), (387, 12), (388, 12), (389, 12), (390, 12)). Provide both "group" and "index" arguments to select another data group
NoneType: None
Traceback (most recent call last):
  File "C:/Users/Hadrovic/PycharmProjects/test_project/converting.py", line 25, in <module>
    mf4converter('1','csv')
  File "C:/Users/Hadrovic/PycharmProjects/test_project/converting.py", line 4, in mf4converter
    signals = mdf_file.select(['MO_Fahrer_bremst'],
  File "C:\Users\Hadrovic\.conda\envs\twopedal\lib\site-packages\asammdf\mdf.py", line 2694, in select
    virtual_groups = self.included_channels(
  File "C:\Users\Hadrovic\.conda\envs\twopedal\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7718, in included_channels
    group, idx = self._validate_channel_selection(name)
  File "C:\Users\Hadrovic\.conda\envs\twopedal\lib\site-packages\asammdf\blocks\mdf_common.py", line 90, in _validate_channel_selection
    raise MdfException(message)
asammdf.blocks.utils.Mdf

Exception: Multiple occurrences for channel "MO_Fahrer_bremst": ((373, 12), (385, 12), (386, 12), (387, 12), (388, 12), (389, 12), (390, 12)). Provide both "group" and "index" arguments to select another data group

Any ideas on how to solve this problem? Thank you alot.

**Comment by danielhrisca** [comment]
The error message is pretty clear: that channel name appears multiple times in the file. You can see the all the occurrences as the (data group index , channel index) pairs. To disambiguate you need to call the ``get`` method with one of those pairs (see the documentation https://asammdf.readthedocs.io/en/latest/api.html#mdf4)

As an alternative you can configure the MDF object to use the first occurrence using this snippet (again see the same documentation page)

```python
mdf.configure(raise_on_multiple_occurences=False)
ch = mdf.get("MO_Fahrer_bremst") # returns channel index 12 from data group 373 
```

**Comment by JulienGrv** [comment]
'''python
from pathlib import Path

from asammdf import MDF

path = Path("my_mdf_file.mf4")
channels = ("name1", "name2", "name3")
source_name = "ECU1"

with MDF(path, channels=channels) as mdf:
    occurrences = [
        (None, gp_idx, cn_idx)
        for name in channels
        for gp_idx, cn_idx in mdf.whereis(name, source_name=source_name)]
        signals = mdf.select(occurrences)
'''
