### ISSUE TITLE
Can't save mf4-file with canopen timestamps.

### ISSUE THREAD

**Issue by Fossiebaer** [danielhrisca/asammdf#570]
('python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit '
 '(Intel)]')
'os=Windows-2012ServerR2-6.3.9600-SP0'
'numpy=1.21.1'
xls is not supported
xlsx is not supported
'asammdf=6.4.4'
# Code 

  ## MDF version
  4.10

  ## Code snippet
from asammdf import MDF, Signal
import numpy as np

cycles = 100
mdf = MDF(version='4.10')
noon = 12 * 60 * 60 * 1000
firstday = 13149 # 2020-01-01
t = np.arange(cycles, dtype=np.float64)

values = np.zeros((cycles,), dtype=[('ms', 'u4'),('days', 'u2')])

index = 0;
for i in range(firstday, firstday + cycles):
  values[index]['ms'] = noon
  values[index]['days'] = i
  index = index + 1

sig = Signal(values, t, name='CANOE_Time')

mdf.append(sig, comment='Test for CANOE Time')
print(mdf.get('CANOE_Time')) # works, but prints 'days'%64
mdf.save('test.mf4')
  
  ## Traceback
  Traceback (most recent call last):
  File "canoetime.py", line 26, in <module>
    mdf.save('test.mf4')
  File "d:\venus\produktion_lenert_ergdatpy_p4\python\Python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9209, in save
    sdata = self._load_signal_data(group=gp, index=j)
  File "d:\venus\produktion_lenert_ergdatpy_p4\python\Python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1123, in _load_signal_data
    for info in info_blocks:
TypeError: 'int' object is not iterable
  
# Description

I try to generate a signal with canopen timestamps. Appending the signal to the MDF-Object works fine. Even reading the signal back from the MDF-Object works but the result is a bit strange as the 'days'- value seems to be 'days' % 64. This also happens if I read a mf4-file written by jBeam with correct canopen timestamps. But that's not a problem for now. 
The real problem arises when I try to save the MDF-Object to a mdf-file. Then the above error is raised.

Am I missing something here? Do I need to provide additional information to generate a correct canopen time signal?

Thank you in advance for your efforts.

Best Regards
Oliver Lenert

**Comment by danielhrisca** [comment]
Hello Oliver, I've pushed fixes in the development branch

**Comment by Fossiebaer** [comment]
Hello Daniel, works like a charm. Thank you very much for the really fast response and solution.
