### ISSUE TITLE
Extract raw can messages from mdf

### ISSUE THREAD

**Issue by dkuschmierz** [danielhrisca/asammdf#572]
Hi, 

currently I am working on a project where I need to extract the raw CAN messages from a recorder mdf.
Unfortunately I cannot see an example how to do this and there is no way to export the data. Can somebody show me a snippet how to extract raw can signals from a mdf?

**Comment by danielhrisca** [comment]
Hello,

what exactly are you trying to obtain. Usually the CAN bus logging is recoded as a structure with teh name `CAN_DataFrame`
 (see https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L4155)
