### ISSUE TITLE
Get values from channel returns empty byte string array 

### ISSUE THREAD

**Issue by pebel76260** [danielhrisca/asammdf#575]
'python=3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'
'os=Windows-10-10.0.19041-SP0'
'numpy=1.20.2'
'asammdf=7.0.0.dev7'

---
When reading some channels of an MF4 file, only empty string bytes are returned. Crosschecks in Matlab and Famos show that there should be values. What could be the reason for this? (min, max attr says 'not numeric object', dtype: |S4). What could be a workaround?

Thanks in advance.

**Comment by danielhrisca** [comment]
Maybe this will help https://github.com/danielhrisca/asammdf/issues/547

**Comment by pebel76260** [comment]
This helped... Thank you!
