### ISSUE TITLE
The unit is not stored in the Signal with MDF3 format

### ISSUE THREAD

**Issue by dglent** [danielhrisca/asammdf#58]
# Python version
('python=3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit '
 '(Intel)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.13.3'
'asammdf=3.3.0'
# Code 

  ## Code snippet
```python
import asammdf
import numpy as np
mdf = asammdf.MDF3()
sig = asammdf.Signal(np.array([0,10,15,20]), np.array([0,1,2,3]), name='S3', unit='Km/h')
>>>sig
<Signal S3:
	samples=[ 0 10 15 20]
	timestamps=[0 1 2 3]
	unit="Km/h"
	conversion=None
	source=None
	comment=""
	mastermeta="None"
	raw=False
	display_name=>

mdf.append([sig])
>>>mdf
<asammdf.mdf_v3.MDF3 object at 0x032C73F0>
mdf.get('S3')
<Signal S3:
	samples=[ 0 10 15 20]
	timestamps=[ 0.  1.  2.  3.]
	unit=""
	conversion=None
	source=SignalSource(name='Channel inserted by Python Script', path='', comment='Module number=0 @ address=0', source_type=0, bus_type=0)
	comment=""
	mastermeta="('Time', 1)"
	raw=False
	display_name=>
  ```
  ## Traceback
  No traceback
  
# Description
With MDF3 format, the unit is not stored in the signal.
With MDF4 it works fine.

**Comment by danielhrisca** [comment]
You should not use the _MDFx_ classes, but instead use the generic _MDF_ class since it adds new methods (like _cut_, _filter_ ...).

**Comment by danielhrisca** [comment]
Thank you for reporting the issue in the first place.

Why do you  choose to use MDF v3 instead of MDF v4 files?

**Comment by dglent** [comment]
There is no any particular reason. I have worked with MDF3 lately because the files was in MDF3 format (inca .dat). But for other thinks i work with MDF4 as it is the newest
