### ISSUE TITLE
Slow reading from External Hard Driver

### ISSUE THREAD

**Issue by sirlagg** [danielhrisca/asammdf#582]
I am working on a data analysis of multiple files stored in an external hard drive. Files are large (1-7GB). I was using mdfreader before and have recently migrated to asammdf, and I am finding a more similar behaviour when working with the local hard drive files, but a huge difference when loading from the external drive.

For instance: just loading a 5GB file, and getting the samples for one signal.

asammdf: 329.76s
mdfreader (with no_data_loading = True): 6.42s

However, running with the file in the local hard drive:

asammdf: 14.22s
mdfreader: 3.79s

Is it there any way to improve this difference?

**Comment by danielhrisca** [comment]
which asammdf version do you use? can you share a snippet of your processing script?

**Comment by danielhrisca** [comment]
I see no reason for the slowdown. I could really use a sample file (you can scramble it to protect textual data like channels names, comments) to investigate

**Comment by danielhrisca** [comment]
so it looks like it only affects mdf v3 files

**Comment by danielhrisca** [comment]
This is what I get with the test files from a slow USB flash drive


|Open file                                         |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 7.0.0.dev31 mdfv3                         |      327|     183|
|mdfreader 4.1 mdfv3                               |     1706|     493|
|mdfreader 4.1 no_data_loading mdfv3               |      703|     244|
|mdfreader 4.1 compress mdfv3                      |     1323|     360|
|asammdf 7.0.0.dev31 mdfv4                         |     1044|     196|
|mdfreader 4.1 mdfv4                               |     4143|     523|
|mdfreader 4.1 no_data_loading mdfv4               |     3065|     310|
|mdfreader 4.1 compress mdfv4                      |     4027|     395|


|Get all channels (36424 calls)                    |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 7.0.0.dev31 mdfv3                         |     4037|     184|
|mdfreader 4.1 mdfv3                               |       53|     493|
|mdfreader 4.1 nodata mdfv3                        |    11917|     280|
|mdfreader 4.1 compress mdfv3                      |      200|     361|
|asammdf 7.0.0.dev31 mdfv4                         |     6612|     196|
|mdfreader 4.1 mdfv4                               |       58|     523|
|mdfreader 4.1 nodata mdfv4                        |    17790|     342|
|mdfreader 4.1 compress mdfv4                      |      211|     399|

**Comment by danielhrisca** [comment]
I've pinpointed the performance bottleneck but I don't have a quick solution. I will let you know when it will be ready. Thanks for bringing this to my attention

**Comment by danielhrisca** [comment]
@sirlagg A good night sleep can do wonders. Please try out the development branch code

**Comment by sirlagg** [comment]
@danielhrisca could you please let me know how I can install that branch? Is it just drag'n'drop the asammdf folder into my installation folder?

**Comment by danielhrisca** [comment]
``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by sirlagg** [comment]
Yes, well done! :D

**Comment by danielhrisca** [comment]
> Yes, well done! :D

Thanks for bringing this to my attention
