### ISSUE TITLE
Index out of bounds, but only for certain mf4 files.

### ISSUE THREAD

**Issue by WilcoBrink** [danielhrisca/asammdf#585]
# Python version
('python=3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19043-SP0'
'numpy=1.21.2'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=6.4.4'

  ## MDF version
4.11

  ## Code snippet
```
from asammdf import MDF

databases = {
    "CAN": [("test_data.dbc", 0)],
}

#mdf = MDF("mdf_correct.MF4")
mdf = MDF("mdf_faulty.MF4")
translated_file = mdf.extract_bus_logging(database_files=databases, 
                                        version="4.11", 
                                        ignore_invalid_signals=False, 
                                        consolidated_j1939=False, 
                                        ignore_value2text_conversion=True)
```
  
  ## Traceback
```
Traceback (most recent call last):
  File "c:\SVNlocal\LoggerConverter\mdf_dbc_test.py", line 11, in <module>
    translated_file = mdf.extract_bus_logging(database_files=databases,
  File "C:\Compilers\Python39\lib\site-packages\asammdf\mdf.py", line 4050, in extract_bus_logging
    out = self._extract_can_logging(
  File "C:\Compilers\Python39\lib\site-packages\asammdf\mdf.py", line 4197, in _extract_can_logging
    bus_data_bytes = data_bytes[idx]
IndexError: index 476624 is out of bounds for axis 0 with size 476624
```
  
# Description
When trying to extract CAN signals from multiple mf4 files, a few of them cause an 'Index out of bounds' error. All files come from the same source and I can't find a difference between a working and faulty file using MDFValidator. By adding some print statements to mdf.py I have noticed however that a different number of groups and fragments are reported when comparing a working and faulty file.
![image](https://user-images.githubusercontent.com/5835039/137279716-270c277d-2e27-4592-849e-87efff304e48.png)

In a working file it is reported as:
```
dbc test_data.dbc
group 0
fragment 0
fragment 1
fragment 2
fragment 3
fragment 4
fragment 5
fragment 6
fragment 7
fragment 8
group 1
group 2
group 3
group 4
group 5
group 6
group 7
```
And in a faulty file as:
```
dbc test_data.dbc
group 0
fragment 0
fragment 1
```
Once again, in MDFValidator I can't find a difference in the file-structure between the files and both show 8 data groups. Scrambled versions of the files are emailed to you, I can't provide the dbc as it's proprietary.

**Comment by danielhrisca** [comment]
The files are correct, there was a problem with the file finalization code, were the blocks were truncated by mistake

**Comment by WilcoBrink** [comment]
An hour ago an update of installed python modules was performed and somewhere between development branch versions 7.0.0.dev31 & 7.0.0.dev36 the exact same issue seems to have returned.

I did notice another two commits on the dev branch that seems to be related to the amount of bytes in data channels, but using the latest commit results in the error "ModuleNotFoundError: No module named 'asammdf.blocks.cutils'". In the asammdf/blocks/ folder I did find a cutils file, but it seems to actually be c-code instead of python.

**Comment by WilcoBrink** [comment]
An hour ago an update of installed python modules was performed and somewhere between development branch versions 7.0.0.dev31 & 7.0.0.dev36 the exact same issue seems to have returned.

I did notice another two commits on the dev branch that seems to be related to the amount of bytes in data channels, but using the latest commit results in the error "ModuleNotFoundError: No module named 'asammdf.blocks.cutils'". In the asammdf/blocks/ folder I did find a cutils file, but it seems to actually be c-code instead of python.

**Comment by danielhrisca** [comment]
It looks like you don't have the VC++ compiler setup. You need to install this (https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) and select the C++ development 
![image](https://user-images.githubusercontent.com/20952040/140067981-8906d77c-90d6-4a47-b08d-d98150c2d3e3.png)

**Comment by danielhrisca** [comment]
how did you update the asammdf code?

**Comment by WilcoBrink** [comment]
> how did you update the asammdf code?

My coworker maintains the python setup, he has now used the latest commit from the development branch and compiled the cutils module. But even then I get the exact same index-out-of-bounds error.

**Comment by danielhrisca** [comment]
I'm using your "faulty" file; with the development branch code I can load and use it without errors. Please double check that you install the development branch code

**Comment by WilcoBrink** [comment]
I've just checked and my coworker has checked out the latest commit on the development branch and used the setup.py file to compile the c-code. I am using the exact same two files I've sent you, but without success.

**Comment by danielhrisca** [comment]
if you run this snippet is the folder the correct one with the updated code?

```python
import asammdf
print(asammdf.__path__)
```

**Comment by WilcoBrink** [comment]
That snippet gives this path: `['C:\\Compilers\\Python39\\lib\\site-packages\\asammdf']`, which is indeed where I placed the new version.

**Comment by WilcoBrink** [comment]
By now I've tried multiple commits of the dev branch and multiple versions of the build tools, but they all result in the same error. Maybe there is an import difference in other installed modules, in my case the installed versions are:
aenum==3.1.0
allure-pytest==2.9.43
allure-python-commons==2.9.43
altgraph==0.17
asammdf @ https://github.com/danielhrisca/asammdf/archive/development.zip
atomicwrites==1.4.0
attrs==21.2.0
bitstruct==8.11.1
boto3==1.19.9
botocore==1.22.9
can-j1939==2.0.2
canmatrix==0.9.3
cffi==1.15.0
click==8.0.1
colorama==0.4.4
comtypes==1.1.10
cryptography==3.4.7
cycler==0.11.0
docx2pdf==0.1.7
et-xmlfile==1.1.0
filelock==3.0.12
future==0.18.2
gcovr==5.0
imageio==2.10.1
importlib-metadata==4.6.1
imutils==0.5.4
iniconfig==1.1.1
jedi==0.18.0
Jinja2==3.0.1
jmespath==0.10.0
kiwisolver==1.3.2
lxml==4.6.3
lz4==3.1.3
MarkupSafe==2.0.1
matplotlib==3.4.3
MouseInfo==0.1.3
mypy-extensions==0.4.3
networkx==2.6.3
nose==1.3.7
numexpr==2.7.3
numpy==1.21.3
opencv-python==4.5.3.56
openpyxl==3.0.7
packaging==21.2
pandas==1.3.1
parso==0.8.2
pathlib2==2.3.6
pefile==2021.5.24
pii-crypt==1.0.6
Pillow==8.4.0
pluggy==1.0.0
psutil==5.8.0
pudb==2021.1
py==1.10.0
PyAutoGUI==0.9.53
pycodestyle==2.7.0
pycparser==2.20
PyGetWindow==0.0.9
Pygments==2.9.0
pyinstaller==4.4
pyinstaller-hooks-contrib==2021.2
PyMsgBox==1.0.9
pynput==1.7.3
pyparsing==2.4.7
pyperclip==1.8.2
PyRect==0.1.4
PyScreeze==0.1.28
pytest==6.2.5
python-can==4.0.0.dev0
python-dateutil==2.8.2
python-docx==0.8.11
pytweening==1.0.4
pytz==2021.1
PyWavelets==1.1.1
pywin32==227
pywin32-ctypes==0.2.0
pywinauto==0.6.8
s3transfer==0.5.0
scikit-image==0.18.2
scipy==1.7.1
six==1.16.0
svn==1.0.1
tifffile==2021.11.2
toml==0.10.2
tqdm==4.61.2
typing-extensions==3.10.0.2
urllib3==1.26.6
urwid==2.1.2
windows-curses==2.2.0
wrapt==1.12.1
xlrd==2.0.1
zipp==3.5.0

**Comment by WilcoBrink** [comment]
I've just made a new discovery. The [functioning commit](https://github.com/danielhrisca/asammdf/tree/e2b6969fefc24473f4f4195338466b50ec5ca436) that I've used before only seems to work when it hasn't been built (just dragging the asammdf folder into the python site-packages folder). As soon as I build the module and place it in the site-packages folder the same IndexError reappears.

**Comment by JeremyLebon** [comment]
Hi,

I'm also getting the same errors on certain mf4 -files. I'm non stop logging with a CAN edge device. 

The error that I get:

> index 476624 is out of bounds for axis 0 with size 476624

python 3.7
os=Windows
pandas=1.3.4
numpy=1.21.3
asammdf=6.4.4

Sample code
> mdf =  asammdf.MDF(path +'/'+ x, version='4.11')
> extracted = mdf.extract_bus_logging(database_files=databases, ignore_invalid_signals=False, ignore_value2text_conversion =False)
>df = extracted.to_dataframe(time_as_date=True)

**Comment by danielhrisca** [comment]
I've tried reading the file with CANape and I get an error. It is possible that the file is corrupted.

![image](https://user-images.githubusercontent.com/20952040/140473776-0e23ef27-67f4-43a2-8125-c083d2f3591f.png)

**Comment by WilcoBrink** [comment]
> Hi,
> 
> I'm also getting the same errors on certain mf4 -files. I'm non stop logging with a CAN edge device.
> 
> The error that I get:
> 
> > index 476624 is out of bounds for axis 0 with size 476624
> 
> python 3.7 os=Windows pandas=1.3.4 numpy=1.21.3 asammdf=6.4.4
> 
> Sample code
> 
> > mdf =  asammdf.MDF(path +'/'+ x, version='4.11')
> > extracted = mdf.extract_bus_logging(database_files=databases, ignore_invalid_signals=False, ignore_value2text_conversion =False)
> > df = extracted.to_dataframe(time_as_date=True)

My data also comes from a CANedge device. It is quite odd that the IndexError has the exact same index for both of us, the chance that we have the same data is near impossible.

> I've tried reading the file with CANape and I get an error. It is possible that the file is corrupted.
I've just checked my files with CANalyzer, they are loaded without any errors.

**Comment by danielhrisca** [comment]
Please try again with the new development code (7.0.0.dev38)

**Comment by WilcoBrink** [comment]
> Please try again with the new development code (7.0.0.dev38)

For me this newest versions works correctly, I'll wait for a reply from @JeremyLebon before closing the issue.

**Comment by JeremyLebon** [comment]
The newest version (7.0.0.dev38) also solve the problem. Thanks @danielhrisca  for the quick fix!

@WilcoBrink  
> "the chance that we have the same data is near impossible."

yeah, that should be very crazy :)  (Logging 200Mb/h of CAN data )
