### ISSUE TITLE
pip install fails in new virtual environment.

### ISSUE THREAD

**Issue by jed-frey** [danielhrisca/asammdf#6]
```wheel``` is required for ``bdist_wheel``.

Installing in a 'clean' virtual environment fails on the ```bdist_wheel```

    pip install wheel

Before installing asammdf seems to fix the issue.

**Comment by jed-frey** [comment]
error: invalid command 'bdist_wheel'
      
      ----------------------------------------
      Failed building wheel for asammdf
      Running setup.py clean for asammdf

Replicating:

Tested on Ubuntu 16.04.

    Linux m6700 4.8.0-32-generic #34~16.04.1-Ubuntu SMP Tue Dec 13 17:03:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    Python 3.5.2


Create a brand new venv:

    python3 -mvenv venv
    source venv/bin/activate

Remove pip cache, if you ever use a venv with wheel installed it'll cache the result making this not fail.

    rm -rf ~/.cache/pip/

Install ```asammdf```

    pip install asammdf 

If you run ```pip install wheel``` first everything works fine.

**Comment by danielhrisca** [comment]
I've added the _wheel_ requirement in _setup.py_ in the development branch.

This will get merged in the next release.
