### ISSUE TITLE
Sampling rate different: when using ETAS MDA and Asamdf MDF

### ISSUE THREAD

**Issue by xuu6wx** [danielhrisca/asammdf#60]
('python=3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) '
 '[MSC v.1900 64 bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.14.2'
'asammdf=3.3.1'

Hello, difference was found when using ETAS MDA and Asamdf MDF to read a .dat file. The sampling time is different, MDA at 0.010s as set when be recorded, but MDF at abt. 0.009s and 0.001s jumping.
Donnot know WHY?
![image](https://user-images.githubusercontent.com/36852949/38787834-0bda05e0-4163-11e8-855c-dce06d5ac6e0.png)

Part of the data:
	ETAS MDA			 ASAMMDF MDF 	
	time	UPmpP_pUnFil		time	UPmpP_pUnFil
0	0.072471607	5007		0	5007
1	0.082392079	5056		0.072471607	5007
2	0.092392554	5020		0.082392079	5056
3	0.102425032	4983		0.092392554	5020
4	0.112441508	4946		0.102425032	4983
5	0.122393982	4910		0.112441508	4946
6	0.132394457	5020		0.122393982	4910
7	0.142442935	5056		0.132394457	5020
8	0.152475413	5020		0.133610515	5020
9	0.162395885	4983		0.142442935	5056
10	0.17239636	4946		0.152475413	5020
11	0.18247684	4934		0.162395885	4983
12	0.192445314	5032		0.17239636	4946
13	0.202397788	5056		0.18247684	4934
14	0.212398264	5020		0.192445314	5032
15	0.222478743	4983		0.202397788	5056
16	0.232463218	4946		0.212398264	5020
17	0.24238369	4934		0.222478743	4983
18	0.252416168	5032		0.232463218	4946
19	0.262480646	5056		0.233679276	4946
20	0.272449121	5007		0.24238369	4934
21	0.282401594	4971		0.252416168	5032
22	0.29240207	4934		0.262480646	5056
23	0.30248255	4946		0.272449121	5007
24	0.312483025	5032		0.282401594	4971
25	0.322387497	5044		0.29240207	4934
26	0.332403973	5007		0.30248255	4946
27	0.342484453	4971		0.312483025	5032
28	0.352452927	4922		0.322387497	5044
29	0.362405401	4946		0.332403973	5007
30	0.372405877	5044		0.333620031	5007
31	0.382486356	5044		0.342484453	4971
32	0.392470831	4995		0.352452927	4922
33	0.402391303	4959		0.362405401	4946
34	0.41240778	4922		0.372405877	5044
35	0.42248826	4971		0.382486356	5044
36	0.432440733	5044		0.392470831	4995
37	0.442393207	5032		0.402391303	4959
38	0.452409683	5007		0.41240778	4922
39	0.462442161	4959		0.42248826	4971
40	0.472474638	4922		0.432440733	5044
41	0.48239511	4983		0.433656791	5044
42	0.492411587	5056		0.442393207	5032

**Comment by danielhrisca** [comment]
Hello,

I suspect that you have a mf4 file and that the invalidation bytes are not handled correctly.

Please run the following snippet and  share the printed output:

```python
from asammdf import MDF

file = r''

mdf = MDF(file)
print(mdf.version)

for group_index, channel_index in mdf.whereis('UPmpP_pUnFil'):
    channel_group = mdf.groups[group_index]['channel_group']
    print(group_index, channel_group['invalidation_bytes_nr'])
```

**Comment by danielhrisca** [comment]
Did you get any progress with the issue?

**Comment by xuu6wx** [comment]
Hello, Daniel

Thanks for the reminding~

I’m in an biz-trip these weeks. I’ll try and share you the progress once I’m back to office.

Have a nice day!

Best regards,

Yujiang XU
RBCD/EGT

Tel. +86 510 8533-3512 | Mobile +86 151 61532911

**Comment by xuu6wx** [comment]
Hello, Daniel

I tried as you suggested, and its output looked like below.

Thank you!


Best regards,

Yujiang XU
RBCD/EGT

Tel. +86 510 8533-3512 | Mobile +86 151 61532911

**Comment by danielhrisca** [comment]
@xuu6wx any updates?

**Comment by danielhrisca** [comment]
Please re-open if needed.
