### ISSUE TITLE
Question: Signals with the same name in different groups

### ISSUE THREAD

**Issue by RobertMouncer** [danielhrisca/asammdf#603]
I have used `extract_bus_logging` to decode a can mdf.
The dbc required to decode has multiple signals with the same name but the CAN frame names are different. 
How can I discover which frame a signal is from?

```python
from asammdf import MDF
dbc_file = '<path>.dbc'
mf4_file = '<path>.MF4'
can = MDF(mf4_file).extract_bus_logging({'CAN': [(dbc_file, 0)]})
can.whereis('T9') 
# ((19, 3), (37, 3))
```

Using `can.info()['group 19']` or `can.info()['group 37']` seems like a very longwinded way of discovering what the CAN frame names (or channel groups) are called, what is the best way to do this?

I've seen question #511 but I have a slightly different requirement.

**Comment by danielhrisca** [comment]
What does this output?

```python
from asammdf import MDF
dbc_file = '<path>.dbc'
mf4_file = '<path>.MF4'
can = MDF(mf4_file).extract_bus_logging({'CAN': [(dbc_file, 0)]})
can.whereis('T9') 
# ((19, 3), (37, 3))
print(can.groups[19].channels[3].display_names)
print(can.groups[37].channels[3].display_names)
```

**Comment by RobertMouncer** [comment]
```
...
>>> can.whereis('T9')
((19, 3), (37, 3))
>>> print(can.groups[19].channels[3].display_names)

>>> print(can.groups[37].channels[3].display_names)

>>>
```
Output is blank.

**Comment by danielhrisca** [comment]
With the development branch code you should be able to access the signal using this notation:

``<CAN_bus>.<message_name>.<signal_name>``

for example

``CAN1.ABS.WheelSpeed``

**Comment by RobertMouncer** [comment]
But if I only have access to the signal name, in your case `WheelSpeed`, and there are multiple occurances of `WheelSpeed`. Is there a way of getting a list of the `message_name`'s?

If there is no way of doing this, I can implement a workaround 😄 

Thank you for responding 👍

**Comment by danielhrisca** [comment]
This functionality is not available so you need to roll your own implementation
