### ISSUE TITLE
ERROR - Multiple occurrences for channel after calling MDF()

### ISSUE THREAD

**Issue by chrism431** [danielhrisca/asammdf#607]
# Python version
_Please run the following snippet and write the output here_
('python=3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit '
 '(AMD64)]')
>>> pprint("os=" + platform.platform())
'os=Windows-10-10.0.18362-SP0'
>>>
>>> try:
...     import numpy
...     pprint("numpy=" + numpy.__version__)
... except ImportError:
...     pass
...
'numpy=1.21.4'
>>> try:
...     import asammdf
...     pprint("asammdf=" + asammdf.__version__)
... except ImportError:
...     pass
...
'asammdf=6.4.4'
# Code 

  ## MDF version
  _MDF4, synchronized with asammdf

  ## Code snippet
  self.org_mdfs[position] = MDF(mdf) <= CRASH
  self.org_mdfs[position].configure(raise_on_multiple_occurrences=False)
  
  ## Traceback
 asammdf - ERROR - Multiple occurrences for channel "CAN_DataFrame.BusChannel": [(189, 14), (189, 26)]. Provide both "group" and "index" arguments to select another data group
NoneType: None
Traceback (most recent call last):
  File "get_data.py", line 285, in <module>
    get_data(None)
  File "get_data.py", line 261, in get_data
    handler.add_mdf(os.path.join(dirpath, filename),idx)
  File "get_data.py", line 30, in add_mdf
    self.org_mdfs[position] = MDF(mdf)
  File "C:\Python38\lib\site-packages\asammdf\mdf.py", line 236, in __init__
    self._mdf = MDF4(name, channels=channels, **kwargs)
  File "C:\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 419, in __init__
    self._read(mapped=True)
  File "C:\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 811, in _read
    self._process_bus_logging()
  File "C:\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 10233, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 10289, in _process_can_logging
    bus_ids = self.get(
  File "C:\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6280, in get
    gp_nr, ch_nr = self._validate_channel_selection(name, group, index)
  File "C:\Python38\lib\site-packages\asammdf\blocks\mdf_common.py", line 130, in _validate_channel_selection
    raise MdfException(message)
asammdf.blocks.utils.MdfException: Multiple occurrences for channel "CAN_DataFrame.BusChannel": [(189, 14), (189, 26)]. Provide both "group" and "index" arguments to select another data group
  
# Description
With some (MDF4) files, after calling MDF(_path_), I get the "multiple occurances" error without calling 'get' or 'select'. It only appears on some files even though all are synchronized using an asammdf script. 

I cannot view the channels using the GUI because it shows the same error message after loading it.

**Comment by chrism431** [comment]
Update: I reran the sync script (also with asammdf), and the error initially appears in MDF.stack(mdf[]) but the MDF gets saved anyway, to the duplicate signals are carried over to the final MDF.
I implemented a quick workaround on my side to skip the affected signals as they aren't needed in the final evaluation. 

Would it be possible to add a switch for duplicate signals in the MDF() function? To use only the first occurence for example.

**Comment by danielhrisca** [comment]
try this with the development branch code

```python
from asammdf import MDF, set_global_option

set_global_option("raise_on_multiple_occurrences", False)

# ... your code here
```

**Comment by chrism431** [comment]
Thank you for the response and the fix. It did the trick, I can import the file and use it as intended.

**Comment by chrism431** [comment]
Sorry for hijacking this issue: in the dev branch, MDF.stack() is not working. It seems to just quit after calling without any error.

**Comment by danielhrisca** [comment]
> Sorry for hijacking this issue: in the dev branch, MDF.stack() is not working. It seems to just quit after calling without any error.

please open a new issue if it still occurs with 7.0.0
