### ISSUE TITLE
iter_groups() reports an error

### ISSUE THREAD

**Issue by nahidpervez** [danielhrisca/asammdf#61]
# Python version
'python=3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 '
 '64 bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.14.0'
'asammdf=3.2.1'
# Code 

  ## Code snippet
from asammdf import MDF
obj = MDF("/filename.dat")
it = obj.iter_groups()
next(it)
  ## Traceback

Traceback (most recent call last):

  File "<ipython-input-140-bc1ab118995a>", line 1, in <module>
    next(it)

  File "C:\Users\NPERVEZ2\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 1222, in iter_groups
    master.append(self.get_master(i, data=data_bytes))

  File "C:\Users\NPERVEZ2\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf_v3.py", line 3123, in get_master
    data_bytes, offset = fragment

ValueError: not enough values to unpack (expected 2, got 1)
  
# Description
group iterator reports an error. 

is there a way to extract a subset of signals of a group as pandas dataframe without interpolation?

**Comment by danielhrisca** [comment]
Hello,

this issue has already been reported and fixed (see issue #56 ).

Regarding the subset question, if this (https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.filter.html) is not suitable then you could try the following:

```python
df = MDF(filename).filter(signal_list).export('pandas')
#or
df = next(MDF(filename).filter(signal_list).iter_groups())
```
Have a look at the docs for asammdf 3.3.1 http://asammdf.readthedocs.io/en/master/api.html#mdf

**Comment by danielhrisca** [comment]
You can also use the _select_ method:

```python
df = MDF(filename).select(signal_list, dataframe=True)
```

**Comment by nahidpervez** [comment]
Thanks a lot! exactly what i was looking for.
