### ISSUE TITLE
How to remove specific data group in existed MDF4 files ?

### ISSUE THREAD

**Issue by jkljkjkjk** [danielhrisca/asammdf#614]
Hi there

we have loads of MDF4 files, but now we want to delete one group of data. 

My original thinking is firstly to use mdf.channels_db['signal'] function to get the group number for this signal, and then try to leave out all signals in that group, and append other signals which are not in that group to a new MDF file, but this costs much time and not reasonable.

so i am wondering if there is a function that can remove a certain group and then save the rest into a new MDF file？

thanks a lot

**Comment by danielhrisca** [comment]
Assuming you have a simple file structure you can just pop the group, but do not use the MDF object after that

```python
mdf = MDF(original)
# find out which group index to remove
# ...
mdf.groups.pop(group_index)

# from this point just save the mdf object, no other operation should be made
mdf.save("smaller_file.mf4")
```

**Comment by jkljkjkjk** [comment]
Hi Daniel

That DOES work!

thank you very much !

**Comment by jkljkjkjk** [comment]
Hello Daniel

Here is another question.

is there any way to split specific groups with channels out of the original MF4 and save these groups into a new MF4 file?

Thanks

**Comment by JulienGrv** [comment]
Let's say you want group 2 and 5:

```python
from asammdf import MDF

group_idxs = [2, 5]

with MDF("my_mdf") as mdf:
    occurrences = [
        (None, gp_idx, cn_idx)
        for _, (gp_idx, cn_idx) in mdf.channels_db.items()
        if gp_idx in group_idxs
    ]
    filtered_mdf = mdf.filter(occurrences)

filtered_mdf.save("my_mdf_filtered")
```

**Comment by JulienGrv** [comment]
Alternatively, you could just pop all the groups except group 2 and 5

**Comment by jkljkjkjk** [comment]
Hi there

Thanks a lot, I will try it out 🙂

**Comment by jkljkjkjk** [comment]
Hi there

I got another question, hope you can provide suggestions:

is there any method to edit the comment of attachment? We have simulation tool and the attachment comment is one of parameters. background is we've popped some groups in MDF files and generator a new MDF file, but the attachment comment has changed and blocks our simulation tool, so I have to change the comment back to what it is in original file.

thanks

**Comment by jkljkjkjk** [comment]
By the way, any way to delete specific channels like using pop to delete certain groups?

thx

**Comment by danielhrisca** [comment]
Once you go into details you should maybe use the `filter` method, this way all the necessary information is transfered

**Comment by jkljkjkjk** [comment]
> Once you go into details you should maybe use the `filter` method, this way all the necessary information is transfered

Yes you are right, but now we have too many channels (signals) in one group, and we need to delete 40% channels in this group, also, the important thing is there are some other groups that should be totally filtered as well. 

thing is like now I have No.1 2 3 4 5 groups in total, and I have to filter number 1 whole group and 40% channels of group 2 into a new MDF file. that's the problem

**Comment by JulienGrv** [comment]
There must be one or more criteria on which you determine if a channel must be deleted or not. Only by knowing this we can precisely help you, otherwise we can only make suggestions

**Comment by jkljkjkjk** [comment]
> There must be one or more criteria on which you determine if a channel must be deleted or not. Only by knowing this we can precisely help you, otherwise we can only make suggestions

Yep, we are a huge amount of signals (more than 250k) from different software modules, and they have part of the same area in the name structure, so it's possible to filter them with the name, but I don't know how to delete them

**Comment by JulienGrv** [comment]
So now we know that you can possibly filter the signals based on their name. Maybe you could do something like:

```python
with MDF("my_mdf.mf4") as mdf:
    # search channels that contains the string "substring"
    names = mdf.search("substring")
    occurrences = [
        (None, gp_idx, cn_idx)
        for name in names
        for (gp_idx, cn_idx) in mdf.whereis(name)
    ]
    filtered_mdf = mdf.filter(occurrences)

filtered_mdf.save("my_mdf_filtered.mf4")
```

See search documentation [here](https://asammdf.readthedocs.io/en/latest/_modules/asammdf/mdf.html#Mdf.search).

**Comment by jkljkjkjk** [comment]
> 

Hi mate

thank you very much for your response. Yes this is a good way to filter the signals that you want and save them in another MDF file. And basically this can solve my problem. However now we met some issues and we have to delete specific signals but keep the rest, since each MDF file is very huge like 8GB, and also the signals that have to be deleted only account for 10% of the total, that is why I am searching for a method to delete these 10% channels (signals) rather than filter the 90% signals which should be remained, because filter these 90% signals takes much time and not efficient for a batch of MDF files (thousands of TB).

thanks a lot, anyway I will try again to filter the signals that should be remained, and check if the time consuming is acceptable

**Comment by danielhrisca** [comment]
If you aim to save some space by removing the 10% unwanted signals, then your only option is to filter the measurement. 

For example if there is at least one requires signal in a channel group, using pop to modify the MDF object would only remove the metadata for the other channel group signals, but the raw data blocks will remain the same.

**Comment by jkljkjkjk** [comment]
> If you aim to save some space by removing the 10% unwanted signals, then your only option is to filter the measurement.
> 
> For example if there is at least one requires signal in a channel group, using pop to modify the MDF object would only remove the metadata for the other channel group signals, but the raw data blocks will remain the same.

Hi Daniel

Got the point! We met some compliance requirement and have to delete pointcloud information in existed MDF files, and these parts of information should be erased, that's the background. The method "filter" aims to keep those signals that you want, which is opposite to my demand, filter wanted signals takes tooooo much time in my cases.

Now it's clear for me, filter is actually the only option although it does not suit my cases.

By the way, does the function 'mdf.groups[i]' only erase group metadata as well and the raw data for that group is still remained in MDF file?

thank you Daniel

**Comment by danielhrisca** [comment]
> By the way, does the function 'mdf.groups[i]' only erase group metadata as well and the raw data for that group is still remained in MDF file?

this removes the all the metadata and the raw data blocks for that channel group but _ONLY_ in the newly saved file, not in the original file

**Comment by jkljkjkjk** [comment]
Perfect !  Thank you very much, appreciate!!!

**Comment by TicaNet** [comment]
> Alternatively, you could just pop all the groups except group 2 and 5
> 
> ```python
> from asammdf import MDF
> 
> group_idxs = [2, 5]
> 
> with MDF("my_mdf") as mdf:
>     mdf.groups = [mdf.groups[idx] for idx in group_idxs]
>     mdf.save("my_mdf_filtered")
> ```

yes., that works basically for me also. But I need to filter by string (with wildcards), eg. 'speed*'.
then store it in pandas dataframe with df=mdf.to_dataframe() with excluded 'speed*' signals.
