### ISSUE TITLE
Documentation Page is missing Content

### ISSUE THREAD

**Issue by marcel0799** [danielhrisca/asammdf#615]
The Documentation Page is not working for me. After Choosing a Subsection, there is content in the Page. If this isnt a global issue just let me know.

**Comment by danielhrisca** [comment]
@marcel0799 I'm working on a fix for 7.0.1.

In the mean time you can use the development branch documentation https://asammdf.readthedocs.io/en/development/api.html

**Comment by marcel0799** [comment]
Thanks !

**Comment by danielhrisca** [comment]
working now
