### ISSUE TITLE
How to operate zipped MF4 file?

### ISSUE THREAD

**Issue by jkljkjkjk** [danielhrisca/asammdf#622]
Hi Daniel

My understanding of the feature MDF(zipfile.ZipFile('data.zip')) is to directly read zipped MDF file and extract information that is wanted. 

There is an error called "TypeError: expected str, bytes or os.PathLike object, not ZipFile " when I use 
mdf = MDF(zipfile.ZipFile('data.zip'))           to read zipped MDF file for further signal extraction.

Could you please give some hint of this failure? is this kind of dependency lost or my understanding of this feature is wrong ?

Thank you very much

**Comment by danielhrisca** [comment]
Just give the zip path to the MDF object

```python
mdf = MDF('data.zip')
```

**Comment by jkljkjkjk** [comment]
Perfect! that works! Thanks a lot.
