### ISSUE TITLE
MDF 4.20: Wrong values for LdBlock.ld_equal_sample_count

### ISSUE THREAD

**Issue by Mscht** [danielhrisca/asammdf#624]
# Python version
('python=3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19043-SP0'
'numpy=1.21.5'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.0.2'

# Code 

  ## MDF version
  4.20

  ## Code snippet
 ```
import numpy as np
from asammdf import MDF, Signal

count = 600000
timestamps = np.arange(count, dtype=np.float64)

s1 = Signal(samples=np.arange(count, dtype=np.int32),
            timestamps=timestamps,
            name='A')
s2 = Signal(samples=np.arange(count, dtype=np.int32),
            timestamps=timestamps,
            name='B')

with MDF(version='4.20') as mdf4:
    signals = [s1, s2]
    mdf4.append(signals, comment='Created by Python')
    mdf4.save('my_new_file.mf4', overwrite=True)
```
  
# Description

Hello there,
you propably have a misunderstanding of the 4.20 standard concerning the LDBLOCK. If the "equal sample count" flag is set, the attribute "dl_equal_sample_count" contains the number of records (the samples for one signal for column-oriented storage) - not the number of total bytes uncompressed. Note: This is different to quite the same attribute of the DLBLOCK.

As always it is not easy to get some reference files or a good validation. I noticed that the Vector MDF Validator marks the content only sometimes as error: In the example the DvBlock of "time" is marked as error, but the two DvBlocks of "A" and "B" are not marked as error what is wrong in my opinion.

**Comment by danielhrisca** [comment]
@Mscht 

the support for 4.20 is not so well tested since, as you have pointed out, there is very limited supported in the commercial tools (market leaders).

I've pushed a fix in the development branch.

**Comment by Mscht** [comment]
The fix looks good.
I think there is another issue. When using the field ld_time_values, the GUI does not read in data. Maybe the fact, that ld_equal_sample_count > actual sampels in the single DvBlock auf channel A and B has to do with it. 
Do not wonder: The file is not created with your lib. ;-)
Example: [example.zip](https://github.com/danielhrisca/asammdf/files/7762943/example.zip)
Let me know if this is my mistake.

**Comment by danielhrisca** [comment]
There was a bug in my code. Now the example file loads correctly

**Comment by Mscht** [comment]
Thank you, looking into it!
