### ISSUE TITLE
Modify comment of attachment in MDF

### ISSUE THREAD

**Issue by jkljkjkjk** [danielhrisca/asammdf#625]
Hello there

There is an video attachment when MDF file is recorded. 

Just wondering if any feature is available for editing the comment of attachment embedded in MDF?

Thanks a lot

**Comment by danielhrisca** [comment]
```python
mdf = MDF(filename)
mdf.attachments[0].comment = 'new comment'
```

**Comment by jkljkjkjk** [comment]
thanks a lot, happy new year 🙂
