### ISSUE TITLE
Signal bit count modified when original bit count isn't standard  

### ISSUE THREAD

**Issue by david32** [danielhrisca/asammdf#627]
# Python version
```
('python=3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 ' 'bit (AMD64)]')
'os=Windows-10-10.0.19042-SP0'
'numpy=1.22.0'
'asammdf=7.0.3.dev3'
```

# MDF version
Version 4

# Origin

There isn't a particular code that is to blame,  its the way the size of the code is decided (its based on the size of the variable which is used in the numpy array).
after calling:
```
def fmt_to_datatype_v4(
    fmt: dtype[Any], shape: tuple[int, ...], array: bool = False
) -> tuple[int, int]:
    """convert numpy dtype format string to mdf version 4 channel data
    type and size`
``` 
The size of the signal is modified.

  
# Description

When working on a file with a channel that has a signal with a non-standard amount of bytes (that doesn't perfectly fit uint8/16/32/64) writing this signal into a new Signal object results in the signal values being extended to to nearest high fitting variable.
So 3 byte signal: 0x54 0x45 0xFF  turns to 0x54 0x45 0xFF 0x00

To recreate:
Have an MDF file with 1 channel  which contains 3 signals:
timestamp | 1 byte | 4 bytes | 3 bytes.

call:
`filtered = orgFile.filter([(None, 0 , 0), (None, 0 , 1) ,(None, 0 , 2), (None, 0 , 3)] , "4.10")
filtered.save(f"D:\MDF4_Test\my_mdf_filtered_1.mf4")`

In the saved file: 
Original on the left!
![image](https://user-images.githubusercontent.com/2933880/147939885-a3b41ae1-d936-42c8-a066-50a529a6d150.png)

Original on top:
![image](https://user-images.githubusercontent.com/2933880/147940037-0830909e-975e-4c74-9cdd-187c2dfb00b6.png)
(Timestamp is also modified but that is another issue I'm looking in to)

**Comment by danielhrisca** [comment]
This is completely expected since preserving the original bit count is complex and performance impacting. Some disk space is wasted this way but the main focus is the performance.
