### ISSUE TITLE
use latest asammdf in python 3.10

### ISSUE THREAD

**Issue by vignesRectifier** [danielhrisca/asammdf#628]
# Python version
``python -3.10``
  
# Description

from virtual environment having python 3.10, i could only install 5.19.16 version (conda install asammdf) . could please help me  to install latest asammdf in my virtual environment.

when i tried to install by specifying the version like conda install assammdf==6.4.4, i got the following error

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by JulienGrv** [comment]
Hi, could you provide us with a tracelog or a Screenshot as there is not enough information here to help you with

**Comment by vignesRectifier** [comment]
Thank you for your reply. i am unable to add the image. so please find the steps i followed to install asammdf.
Create a virtual environment using  **conda create --name pyV python=3.10** then **conda install asammdf**
Here instead of installing the latest version, i am getting **older version 5.19.16**
i want to use the latest asammdf version in this virtual environment.

**CMD prompt Results:**

(pyV) C:/>**conda install asammdf**
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\

  added / updated specs:
    - asammdf


The following NEW packages will be INSTALLED:

  **asammdf            conda-forge/noarch::asammdf-5.19.16-py_0**
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  brotli             conda-forge/win-64::brotli-1.0.9-h8ffe710_6
  brotli-bin         conda-forge/win-64::brotli-bin-1.0.9-h8ffe710_6
  canmatrix          conda-forge/noarch::canmatrix-0.8-py_0
  cchardet           conda-forge/win-64::cchardet-2.1.7-py310h8a704f9_2
  ......

**Comment by JulienGrv** [comment]
Could you try: `conda install -c conda-forge asammdf`

**Comment by vignesRectifier** [comment]
Thank you for your quick reply, but i am still getting old version of asammdf. 
**Cmd ouptut:**

(pyV1) C:\Users\>**conda install -c conda-forge asammdf**
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\

  added / updated specs:
    - asammdf


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    yaml-0.2.5                 |       h8ffe710_2          62 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          62 KB

The following NEW packages will be INSTALLED:

  asammdf            **conda-forge/noarch::asammdf-5.19.16-py_0**
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0

**Comment by vignesRectifier** [comment]
I guess this is our problem, canmatrix is one of the depedency of asammdf which doesnt support 3.10 python.  

(pyV1) C:\Users>**conda create --name pyV2 python=3.10 asammdf==6.4.4**
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
asammdf==6.4.4 -> python[version='>=3.6']
asammdf==6.4.4 -> **canmatrix** -> python[version='!=3.0,!=3.1,!=3.2,!=3.3,!=3.4|2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.9,<3.10.0a0|>=3.10,<3.11.0a0|>=3.5,<3.6.0a0|3.4.*|>=3.5|>=3.7.1,<3.8.0a0|2.7.*|>=3.6']
python=3.10

**Comment by JulienGrv** [comment]
You nailed it.

**Comment by vignesRectifier** [comment]
Thank you for your time.. for now i shall proceed with python 3.8 as the python 3.9 also gives the same dependency issue.
will update here if we have any updates. 
kindly let me know if there are any other possibilities to proceed with 3.10.
Have a nice day..

**Comment by JulienGrv** [comment]
The solution is simple, add support for python 3.10 in canmatrix. It could be that it works without any changes. You can add it yourself or open an issue and kindly ask maintainers of canmatrix to do it.

**Comment by vignesRectifier** [comment]
Thank you..

**Comment by vignesRectifier** [comment]
Hi, one update, i had look at the recipe file meta.yaml of asammdf 6.4.4 in which this is the hard coded version for one of the dependency  - **cchardet ==2.1.5** and this doesnt support 3.10.  

Source link :: https://anaconda.org/conda-forge/asammdf/6.4.4/download/noarch/asammdf-6.4.4-pyhe74cb21_0.tar.bz2
 
**meta.yaml file:**

....
  run:
    - canmatrix
    **- cchardet ==2.1.5**
    - lxml
    - lz4
    - matplotlib
    - natsort
    - numexpr
    - numpy >=1.16.1
    - pandas
    - python >=3.6
    - wheel
...

**Comment by JulienGrv** [comment]
ok so try this:

```bash
conda create --name env_name pip python=3.10
conda activate env_name
pip install asammdf
```

**Comment by JulienGrv** [comment]
As a conda environment.yml configuration:

```yaml
name: env_name
dependencies:
  - pip
  - python=3.10
  - pip:
      - asammdf
```

**Comment by JulienGrv** [comment]
I added support for Python 3.10 in canmatrix: <https://github.com/ebroecker/canmatrix/pull/619>

**Comment by vignesRectifier** [comment]
Thank you for the active support.. kindly consider removing the hard coded version dependency **cchardet ==2.1.5** in the next release of asammdf to anaconda platform. 
please let me know if any new release is already planned to be released in anaconda in near future.

**Comment by danielhrisca** [comment]
@vignesRectifier 7.0.3 will probably work in conda (see https://github.com/conda-forge/asammdf-feedstock/pull/142)

**Comment by danielhrisca** [comment]
The new version is ready in conda forge https://anaconda.org/conda-forge/asammdf/files

**Comment by vignesRectifier** [comment]
@danielhrisca  and @JulienGrv  Thank you.. i could able to download latest 7.0.3 in python 3.10. 
Found a new error after installing it. i couldnt import asammdf and it shows below error during import.

>>> import asammdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\x\.conda\envs\pyV4\lib\site-packages\asammdf\__init__.py", line 17, in <module>
    from .mdf import MDF, SUPPORTED_VERSIONS
  File "C:\Users\x\.conda\envs\pyV4\lib\site-packages\asammdf\mdf.py", line 42, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Users\x\.conda\envs\pyV4\lib\site-packages\asammdf\blocks\mdf_v2.py", line 9, in <module>
    from .mdf_v3 import MDF3
  File "C:\Users\x\.conda\envs\pyV4\lib\site-packages\asammdf\blocks\mdf_v3.py", line 49, in <module>
    from .cutils import get_channel_raw_bytes
ModuleNotFoundError: No module named 'asammdf.blocks.cutils'
>>>

**Comment by JulienGrv** [comment]
The C module was not found. Are you sure the installation went without errors? Usually you get at least a warning during installation saying that the C module could not be compiled

**Comment by JulienGrv** [comment]
Please share a traceback or a screenshot of your installation

**Comment by vignesRectifier** [comment]
Please find the cmd ouptut..

(pyV1) C:\Users\x>conda create --name pyV4 python=3.10 asammdf
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\x\.conda\envs\pyV4

  added / updated specs:
    - asammdf
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asammdf-7.0.3              |     pyhe74cb21_0         499 KB  conda-forge
    chardet-4.0.0              |  py310h5588dad_2         228 KB  conda-forge
    isa-l-2.30.0               |       h8ffe710_4         161 KB  conda-forge
    libblas-3.9.0              |5_hd5c7e75_netlib         197 KB  conda-forge
    libcblas-3.9.0             |5_hd5c7e75_netlib          95 KB  conda-forge
    liblapack-3.9.0            |5_hd5c7e75_netlib         2.7 MB  conda-forge
    msys2-conda-epoch-20160418 |                1           3 KB  conda-forge
    nomkl-1.0                  |       h5ca1d4c_0           4 KB  conda-forge
    numexpr-2.8.0              |py310h32c9954_100         126 KB  conda-forge
    python-isal-0.11.1         |  py310he2412df_1         111 KB  conda-forge
    xlrd-2.0.1                 |     pyhd8ed1ab_3          92 KB  conda-forge
    yaml-0.2.5                 |       h8ffe710_2          62 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.3 MB

The following NEW packages will be INSTALLED:

  asammdf            conda-forge/noarch::asammdf-7.0.3-pyhe74cb21_0
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  .....


Proceed ([y]/n)? y


Downloading and Extracting Packages
msys2-conda-epoch-20 | 3 KB      | ################################################################################################################## | 100%
numexpr-2.8.0        | 126 KB    | ################################################################################################################## | 100%
libcblas-3.9.0       | 95 KB     | ################################################################################################################## | 100%
isa-l-2.30.0         | 161 KB    | ################################################################################################################## | 100%
xlrd-2.0.1           | 92 KB     | ################################################################################################################## | 100%
yaml-0.2.5           | 62 KB     | ################################################################################################################## | 100%
nomkl-1.0            | 4 KB      | ################################################################################################################## | 100%
python-isal-0.11.1   | 111 KB    | ################################################################################################################## | 100%
chardet-4.0.0        | 228 KB    | ################################################################################################################## | 100%
libblas-3.9.0        | 197 KB    | ################################################################################################################## | 100%
liblapack-3.9.0      | 2.7 MB    | ################################################################################################################## | 100%
asammdf-7.0.3        | 499 KB    | ################################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by JulienGrv** [comment]
It seems like there is a problem with the anaconda package. My recommendation is to do the installation with pip instead until the anaconda package has been fixed (what I told you in my previous comments).

```bash
conda create --name env_name pip python=3.10
conda activate env_name
pip install asammdf
```

**Comment by vignesRectifier** [comment]
okay thank you. kindly update here regarding stable release in anaconda

**Comment by danielhrisca** [comment]
There are now compiled wheels on the conda forge. Please try again to install

**Comment by vignesRectifier** [comment]
will update shortly... thanks for the update and active support

**Comment by vignesRectifier** [comment]
@danielhrisca  thanks for the update... import issue resolved...
