### ISSUE TITLE
Asammdf 7.0.3 GUI channel export problem

### ISSUE THREAD

**Issue by jenicekhartigu** [danielhrisca/asammdf#632]
# Code 
  ## Python version
  Python 3.7.7 64-bit

  ## MDF version
  File is version 4.10
  
# Description
  I want export two channels with same name (BMS_01_BZ) from large mdf4 file for testing
  Channels name are same but the devices on which the signals are measured are different ( CAN-Monitoring:1 / FLX Monitoring A:1)
  So if i checked both channels for export, in selected area are overwrited and i see only one channel.

  So can you please help me how i can solve this or it is some internal bug ?  

![Asammf problem 2 channels](https://user-images.githubusercontent.com/47743548/148530679-eb2ceebd-2487-47d9-99e6-7f62e9c4d0eb.png)

**Comment by danielhrisca** [comment]
Only the unique names are found in the second list, but the output should contain both selected channels. Please confirm this

**Comment by jenicekhartigu** [comment]
Yes, both channels were imported, so its just GUI issue, thank for fast reply.
