### ISSUE TITLE
Feature request: show path in search window

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#634]
Hi,
the new search window is nice with group and index information. In my case of measurement analysis it would be great, if the path (and may be source) would be displayed.  This would be usefull for analysis of vehicle measurements of multiple busses / bussystems.

Thanks to all who are developing this tool!!!

**Comment by danielhrisca** [comment]
I've added the initial work for this. The source information detection needs to be refined

**Comment by danielhrisca** [comment]
@stlweb please check the development branch code

**Comment by stlweb** [comment]
Sorry for beeing late. I had some trouble to build the dev branch, because of admin restriction of the IT department (C++ dependencies are not available). So I couldn't test your work.

**Comment by danielhrisca** [comment]
You can install 7.0.4 from PyPi
