### ISSUE TITLE
j1939 - Signals with different source addresses (SA) in their CAN ID are merged together when have the same PGN.

### ISSUE THREAD

**Issue by fbcom** [danielhrisca/asammdf#636]
Hi, I really like your library and started to make myself familiar with some internals of it. I tried to read out signals separated by their source address and noticed that the source address, which is encoded in the last 8 bit of the CAN ID in j1939 messages, is ignored during the parsing of MF4 files.

An example of why this is problematic:

Imagine a car with four tires. Each tire has its own air pressure sensor. Each of the sensors has its own assigned source address and is connected independently of the other 3 sensors to the CAN BUS. Because the sensors are all build the same way (they are the same hardware) they share the same PGN. However, because of the different source addresses, the last 8 bits of their CAN ID is different. When a sensor sends its data to the CAN in j1939 format, the CAN ID is submitted as well. This allows commercial tools like Canalizer from Vector to distinguish between the different Sensors.

However, the library merges j1939 signals based only on the PGN (another part of the CAN ID), because of this, it becomes impossible to identify which measurement value came from which of the four air pressure sensors in the above example. This greatly reduces the usefulness of the library when extracting signal data from j1939 messages. One can simply not be sure what the source of the measurement was.

Would it be possible to not merge signals that have the same PGN but different source addresses? It would be an idea for example if the signals kept the same name but had a postfix "-123" indicating the source address, which is a numeric byte value (0-255).

**Comment by danielhrisca** [comment]
Hello Florian,

did you try ``consolidated_j1939=False`` ? (see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.extract_bus_logging)

**Comment by fbcom** [comment]
Hi Daniel, thank you!

It seems that this feature splits the signals by channel group (signal.group_index). Do you know how the channel group relates to the source address of the signal? I wasn't quite able to see that when stepping with the debugger through the source code during extraction.

When parsing multiple MF4 files individually, I'd like to be sure that the signal with the same source address always ends up with the same group_index.

**Comment by danielhrisca** [comment]
Using the development branch code you can see some information in the channel group comment and source
![image](https://user-images.githubusercontent.com/20952040/149474004-95a7720d-f49b-4004-9b45-fcdbe71658a5.png)
![image](https://user-images.githubusercontent.com/20952040/149473923-a022e6f7-84b0-4980-8479-f0706a7c4748.png)

And also in the search dialog:
![image](https://user-images.githubusercontent.com/20952040/149474081-725166d4-02d9-446d-8e10-decf5ed40740.png)
