### ISSUE TITLE
Installation on Apple M1 Silicon

### ISSUE THREAD

**Issue by dadebue** [danielhrisca/asammdf#639]
I'm trying to install asammdf with pip on Python 3.8 on my MacBook Pro 2021 (M1 Pro Chip on macOS Monterey 12.1)

The installation fails because of multiple errors. The first one being:
`In file included from erasure_code/aarch64/ec_aarch64_dispatcher.c:29:`
`/var/folders/yh/q11mmnrx4bj7m21b0l255mg40000gn/T/tmpmnogoka1/include/aarch64_multibinary.h:34:10: fatal error:`
`asm/hwcap.h' file not found`
`#include <asm/hwcap.h>`
`^~~~~~~~~~~~~`
`1 error generated.`

After that there are a bunch of other errors. I've added the full log as an attachment.

I've already adressed the issue to the original python-isal library. They have already added a suggestion how the issue could be solved for asammdf:
https://github.com/pycompression/python-isal/issues/107

What do you think about the suggestion?

BR
Marco

**Comment by danielhrisca** [comment]
Hello Marco,

please try the release 7.0.7

**Comment by dadebue** [comment]
Yes it's working now 😊
