### ISSUE TITLE
How to procced to merge signals from several MDF4-Files into one single MDF4-File?

### ISSUE THREAD

**Issue by LCFN-Maier** [danielhrisca/asammdf#641]
('python=3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.21.5'
'asammdf=5.13.11'
# Code 

comment: please see attached file "request_ASAMMDF.txt" for full code

locals()[famos_dat_name] = MDF.concatenate(full_file_paths, version = '4.10', sync=False)

Traceback (most recent call last):

  File "C:\Users\Z637249\AppData\Local\Temp\ipykernel_9464\2263732332.py", line 1, in <module>
    locals()[famos_dat_name] = MDF.concatenate(full_file_paths, version = '4.10', sync=False)

  File "c:\app\python37\lib\site-packages\asammdf\mdf.py", line 2028, in concatenate
    raise MdfException(f"internal structure of file {mdf_index} is different")

MdfException: internal structure of file 2 is different
  
# Description

Hello.
First of all I have to say that I am a newbie in Python. So it may be that with me also some Python-fundamentals still need to be improved 😉
I hope I could summarize my issues in short terms: 
How to procced to merge signals from several MDF4-Files into one single MDF4-File?
What is needed to make internal structure of MDF-files not different?
In details:
I get MDF files from a measurement system called "Famos".
A measurement, labeled e.g. "F000567560051" consists of 15 measured channels.
All channels of a measurement, e.g. "I_Aktor" , "I_Drossel" are sampled simultaneously with the same sampling rate. I.e. all their timestamps are identical. Other measurements, e.g. "F000567560059" run the same way, i.e. the timestamps should be identical then too.
The measurement system stores each channel separately in a .mf4 file, MDF version 4.10.
Files with channels belonging to one measurement get the same prefix, e.g. "F000567560051".
What works so far:
1. success: open the mf4 files of only one measurement, e.g. "F000567560051".
2. success: plot all channels of a measurement separately
3rd success: Create a .mf4 file / object which contains the name of the prefix, e.g. "F000567560059".
		… [some code]
		locals()[famos_dat_name] = MDF( Version = "4.10")
		# value of famos_dat_name is e.g. „F000567560059“
		… [some more code]
		Console:
		>>> type(F000567560059)
		Out[10]: asammdf.mdf.MDF
4. success, but does it make sense?: collect all channels. => I get a list of dataframes which contains the measurements Channels.

What I actually want to do is:
5. no success: store all channels of a measurement together in only one .mf4 file. I.e. 
F000567560059.mf4 should contain the 15 channels from the files F000567560059###I_Aktor_raw.mf4 to F000567560059###U_Versorgung_raw.mf4.
    line 88 doesn't work of course, since wrong code, yields:
    asammdf.blocks.utils.MdfException: "samples", "timestamps" and 
    "name" are mandatory for Signal class __init__: samples={samples}
    timestamps={timestamps}
    name={name}
Do I need / does it work to iterate over every single dataframe in collected_signals to create single MDF-Signals step by step?

Any help is highly appreciated.

Translated from German with www.DeepL.com/Translator (free version)

[request_ASAMMDF.txt](https://github.com/danielhrisca/asammdf/files/7986575/request_ASAMMDF.txt)
[Famos_ASAM_MDF.zip](https://github.com/danielhrisca/asammdf/files/7986608/Famos_ASAM_MDF.zip)

**Comment by danielhrisca** [comment]
You should use the ``stack`` method instead of the ``concatenate`` method.

It's really weird that Famos generates a separate file for each measured signal. Maybe there is a configuration option to save them together in a single file.

**Comment by LCFN-Maier** [comment]
Dear Daniel.
Thank you very much. This worked:
locals()[famos_dat_name] = MDF.stack(full_file_paths, version = '4.10', sync=False)

## check
conc_df = locals()[famos_dat_name].to_dataframe()

Afterwards, I read this big MDF-File's dataframe => and as desired get its channels ( 62 in total) as a single big dataframe. COOL :-)

Check with console:
>>> conc_df
             I_Aktor  I_Aktor_0  ...     Temp_2  U_Versorgung_2
timestamps                       ...                           
0.00000     0.069573   0.069573  ...  46.511628       27.018861
0.00005     0.065269   0.065269  ...  46.511628       27.021913
0.00010     0.066661   0.066661  ...  46.511628       27.021913
0.00015     0.069831   0.069831  ...  46.511628       27.021913
0.00020     0.093790   0.093790  ...  46.511628       27.006653
             ...        ...  ...        ...             ...
20.94235    0.047434   0.047434  ...  46.731368       26.970030
20.94240    0.047434   0.047434  ...  46.731368       26.970030
20.94245    0.047434   0.047434  ...  46.731368       26.970030
20.94250    0.047434   0.047434  ...  46.731368       26.970030
20.94255    0.047434   0.047434  ...  46.731368       26.970030

[418852 rows x 62 columns]

**Comment by LCFN-Maier** [comment]
PS: Its left to the colleagues how Famos stores the Channels. I'll try to store it in a single file directly.

Chears.
