### ISSUE TITLE
Signals in plot not in alphabetic order

### ISSUE THREAD

**Issue by axtschmied** [danielhrisca/asammdf#649]
# asammdf version
7.0.7

# Code 
  ## MDF version
  4.10
  
# Description
Hello,
when I add multiple signals to a plot at the same time, their order is mixed up, they do not appear in alphabetic order, but rather in a seemingly random order. The alphabetic order (based on the signals' name) would be desired in my opinion, because that would guarantee e.g. that elements of an array follow in the correct order.

This issue does not seem to happen in numeric and table windows.

**Comment by danielhrisca** [comment]
@axtschmied please try the development branch code

**Comment by axtschmied** [comment]
Hello, unfortunately I still see the same behavior with the development branch code.

**Comment by danielhrisca** [comment]
Can you post a screenshot?
The sorting only works when you create a new Plot, not when you load a display file

**Comment by axtschmied** [comment]
Selecting signals for a new plot (the signals are in alphabetical order in the final selection independent of the order I added them in):

![asammdf_1](https://user-images.githubusercontent.com/28358038/152951045-8e75afba-e846-4c5e-a0b5-41ed7b745840.PNG)

In the newly created plot window they are not in the same order:

![asammdf_2](https://user-images.githubusercontent.com/28358038/152951049-70daf7ec-e70c-4327-9b16-96d9e2ce8933.PNG)

**Comment by danielhrisca** [comment]
ok, try again

**Comment by axtschmied** [comment]
Now it is working, thank you.
