### ISSUE TITLE
loading an mf4 file give divide by zero:

### ISSUE THREAD

**Issue by MontyTHall** [danielhrisca/asammdf#65]
I'm getting a divide by zero loading this file.  I can use turbo lab's mf4 and it load's w/o issues - however, it's incredibly complex to use.  Here's the output, appeantly size = 0.

C:\Python27\python.exe C:/Users/xzcjml/PycharmProjects/untitled/main.py
Traceback (most recent call last):
  File "C:/Users/xzcjml/PycharmProjects/untitled/main.py", line 14, in <module>
    for g in mdf.iter_groups():
  File "C:\Python27\lib\site-packages\asammdf\mdf.py", line 2183, in iter_groups
C:\Users\xzcjml\Documents\dSPACE\ControlDeskNG\5.3\Project_001\Experiment_001\Measurement Data\rec1_011.mf4
4.10
    master.append(self.get_master(i, data=fragment))
  File "C:\Python27\lib\site-packages\asammdf\mdf_v4.py", line 4763, in get_master
    parents, dtypes = self._prepare_record(group)
  File "C:\Python27\lib\site-packages\asammdf\mdf_v4.py", line 1668, in _prepare_record
    if ca_block['byte_offset_base'] // size > 1 and \
ZeroDivisionError: integer division or modulo by zero

Process finished with exit code 1

**Comment by danielhrisca** [comment]
Hello,

it appears that you have a channel array with a bit count <8 which is not correct as far as I am aware.

Please install _asammdf 3.4.0_ and at line 1667 in mdf_v4.py (https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf_v4.py#L1667) insert this snippet

```python
try:
    1//size
except:
    print(new_ch)
```

**Comment by MontyTHall** [comment]
The mf4 was generated with dSPACE control desk.  I can read the file w/
mdfreader, thought I think it has issues too.    How do you get a list of
signals, and the time steps?

Thanks,

M


<Channel (name: Model Root/slave/Control/TSTR/TSTR Component/Relative
Lane/O_TTC1, unit: , comment:
<CNcomment><TX></TX><names><display></display></names><common_properties><e
name="format" type="string">%g</e></common_properties></CNcomment>,
address: 0x2278, conversion: <ChannelConversion (name: Identical, unit: ,
comment: <CCcomment xmlns="http://www.asam.net/mdf/v4"><TX>Default scaling
generated by SDF Parser</TX><common_properties><e name="format"
type="string">%g</e></common_properties></CCcomment>, formula: , referenced
blocks: {}, address: 0x0, fields: {'id': b'##CC', 'reserved0': 0,
'block_len': 80, 'links_nr': 4, 'name_addr': 3656, 'unit_addr': 3696,
'comment_addr': 3728, 'inv_conv_addr': 0, 'conversion_type': 0,
'precision': 0, 'flags': 0, 'ref_param_nr': 0, 'val_param_nr': 0,
'min_phy_value': 0.0, 'max_phy_value': 0.0})>, source: <SourceInformation
(name: , path: Platform_3, comment: , address: 0x0, fields: {'id': b'##SI',
'reserved0': 0, 'block_len': 56, 'links_nr': 3, 'name_addr': 0,
'path_addr': 8488, 'comment_addr': 0, 'source_type': 0, 'bus_type': 0,
'flags': 0, 'reserved1': b'\x00\x00\x00\x00\x00'})>, fields: {'id':
b'##CN', 'reserved0': 0, 'block_len': 160, 'links_nr': 8, 'next_ch_addr':
8176, 'component_addr': 8336, 'name_addr': 8392, 'source_addr': 8528,
'conversion_addr': 3936, 'data_block_addr': 0, 'unit_addr': 0,
'comment_addr': 8616, 'channel_type': 0, 'sync_type': 0, 'data_type': 0,
'bit_offset': 0, 'byte_offset': 4357, 'bit_count': 1, 'flags': 56,
'pos_invalidation_bit': 0, 'precision': 0, 'reserved1': 0, 'attachment_nr':
0, 'min_raw_value': 0.0, 'max_raw_value': 1.0, 'lower_limit': 0.0,
'upper_limit': 1.0, 'lower_ext_limit': 0.0, 'upper_ext_limit': 1.0})>

**Comment by danielhrisca** [comment]
You have to call _get_ on the _MDF_ object and you will get a _Signal_ (http://asammdf.readthedocs.io/en/master/api.html#signal):

```python
mdf = MDF(file_name)
channel = mdf.get('Model Root/slave/Control/TSTR/TSTR Component/Relative Lane/O_TTC1')
print(channel.samples)
print(channel.timestamps)
```

If you know the list of channels you can also use the _select_ method (see here http://asammdf.readthedocs.io/en/master/api.html#mdf).

**Comment by danielhrisca** [comment]
Please have a try with the code from the development branch https://github.com/danielhrisca/asammdf/tree/development

```
pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip
```

**Comment by danielhrisca** [comment]
@MontyTHall 
did the fix work for you?
