### ISSUE TITLE
Time axis range saved into configuration?

### ISSUE THREAD

**Issue by axtschmied** [danielhrisca/asammdf#650]
# asammdf version
7.0.7

# Code 
  ## MDF version
  4.10
  
# Description
Hello,
since I updated to version 7.0.7 from 6.3.2 I noticed, that when I save a configuration in the GUI, and then load it for a different measurement, the time axis of the plots created from the configuration is also set to the range the configuration was saved with, so it is not based on the beginning and end of the currently open measurement (like in the previous version).

It might be useful in some situations to restore the time axis range as well, but in my opinion it is rather annoying, because different measurements usually start and end at different time stamps.

My question is, whether there is a particular reason for changing the old behavior. Maybe it would be useful to hear others' opinion about this. I personally liked the old behavior better, when the time axis range was always set based on the current measurement's time stamps.

**Comment by danielhrisca** [comment]
@axtschmied please try the development branch code

**Comment by axtschmied** [comment]
Hello, this is fixed on the development branch. Thank you.
