### ISSUE TITLE
Signal units are not displayed when exporting from MDF4

### ISSUE THREAD

**Issue by capiscott** [danielhrisca/asammdf#653]
# Python version 3.9

self.df = asammdf.mdf.MDF(self.file_path).to_dataframe()

  ## MDF version
MDF4

  ## Code snippet

self.df = asammdf.mdf.MDF(self.file_path).to_dataframe()
self.df = asammdf.mdf.MDF(self.file_path).export(csv)  

  ## Traceback
No error
  
# Description

When trying to load the signals from the MDF4 files the timestamp and the values are displayed properly, and it is easy to handle them using an export to csv or using a dataframe for additional operations with them.
However to access to the signal units it is rather complicated and since it may happen measurement files have the signals with the same name and different sources the required loops get complex.

Is there any way to export the signals with their units? It is not clear for me if this is a bug or a feature, therefore I created the issue.

I tried the GUI, the commands above, and I could only find the units using mdf.get("MySignal").unit, however as stated before the name might be repeated coming from different sources.

**Comment by danielhrisca** [comment]
it is not possible to include the units in the pandas DataFrame

**Comment by capiscott** [comment]
Thanks for the clarification. I was thinking of an additional field to the Dataframe, before the values of the signals.

In any case is it possible to have this information in the csv export? See file attached. 

[measurement_sample.txt](https://github.com/danielhrisca/asammdf/files/8023805/measurement_sample.txt)

The target is to have a measurement converted from MDF4 into something like the file attached. I managed with the GUI to have it but, the units are missing.

Thanks for your support!

**Comment by danielhrisca** [comment]
@capiscott try the development branch
