### ISSUE TITLE
Performance Warning loading large .mf4-files

### ISSUE THREAD

**Issue by carDev100** [danielhrisca/asammdf#654]
# Python version
python version: Python 3.9.5 (default, Jul  5 2021, 13:54:33) [GCC 9.2.0] on linux
platform: Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-glibc2.17
numpy version: 1.22.1
asammdf version: 7.0.7
# Code 

  ## MDF version
  4.00

  ## Code snippet
  mf4_obj=MDF(datafile)
  df_tmp = pd.DataFrame()
  df_tmp = mf4_obj.to_dataframe(raster=0.1, time_from_zero=False, reduce_memory_usage=True, ignore_value2text_conversions = False)
  
  ## Traceback
 lib/python3.9/site-packages/asammdf/mdf.py:4268: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col] = series
  
# Description
Hello,
first of all I want to thank you very much for your time and effort creating and maintaining asammdf!

While reading large .mf4-files, I get a performance warning and long loading time if "ignore_value2text_conversions" is set to False. 
If "ignore_value2text_conversions" is set to True, no performance warning is shown.

Do you have an idea how to mitigate this issue?

**Comment by danielhrisca** [comment]
> While reading large .mf4-files, I get a performance warning and long loading time if "ignore_value2text_conversions" is set to False.
> If "ignore_value2text_conversions" is set to True, no performance warning is shown.

Do you need the textual values (scaled values) or the numeric values (raw values) for those signals? The textual DataSeries are probably very inefficient , I don't think there is a workaround
