### ISSUE TITLE
missing datatype or skipping the channel

### ISSUE THREAD

**Issue by jazi007** [danielhrisca/asammdf#657]
# Python version
_Please run the following snippet and write the output here_
```
('python=3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]')
'os=Windows-10-10.0.19042-SP0'
'numpy=1.22.2'
'asammdf=7.0.7'
```
# Code 

  ## MDF version
 `4.10`

  ## Code snippet
  _please write here the code snippet that triggers the error_
```python
asammdf.MDF("myfile.mf4")
```
  
  ## Traceback
  _please write here the error traceback_
```
  File "lib\site-packages\asammdf\mdf.py", line 304, in __init__
    self._mdf = MDF4(name, channels=channels, **kwargs)
  File "lib\site-packages\asammdf\blocks\mdf_v4.py", line 387, in __init__
    self._read(mapped=True)
  File "lib\site-packages\asammdf\blocks\mdf_v4.py", line 595, in _read
    self._read_channels(
  File "lib\site-packages\asammdf\blocks\mdf_v4.py", line 1079, in _read_channels
    get_fmt_v4(
  File "lib\site-packages\asammdf\blocks\utils.py", line 582, in get_fmt_v4
    return fmt
UnboundLocalError: local variable 'fmt' referenced before assignment
```
  
# Description

Issue is in function `get_fmt_v4` :
```
channel.data_type = {int} 62
channel.bit_offset = {int} 0
channel.bit_count = {int} 16
channel.channel_type = {int} 0
```
looks like the datatype 62 is not defined in asammdf. I don't have the MDF spec so can't say if it's a valid or invalid datatype.

But in this case we may add `else` and raise an error for the concerned channel with an error logging and go for next one ? 

The WA I found is just to set `fmt = f"({size},)u1"` and parsing is fine. not nice but worked

**Comment by danielhrisca** [comment]
You can see the currently defined data types [here](https://github.com/danielhrisca/asammdf/blob/1507f100bddc86c5f037db2770ec39e42bdfc306/asammdf/blocks/v4_constants.py#L9)

**Comment by jazi007** [comment]
works thanks a lot
