### ISSUE TITLE
Error when append a signal in a mf4 file

### ISSUE THREAD

**Issue by dglent** [danielhrisca/asammdf#66]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit '
 '(Intel)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.13.3'
'asammdf=3.4.0'
```
# Code 

  ## MDF version
4.10

  ## Code snippet
sig = asammdf.Signal(samples, times, name='NSIGNAL')
>>> sig
<Signal NSIGNAL:
	samples=[0 0 0 ..., 0 0 0]
	timestamps=[  4.33278000e-02   1.46902900e-01   2.50719500e-01 ...,   5.55888950e+02
   5.55988988e+02   5.56078259e+02]
	unit=""
	conversion=None
	source=None
	comment=""
	mastermeta="None"
	raw=True
	display_name=>
mdf.append([sig,])
  
  ## Traceback
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    mdf.append([sig,])
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\asammdf\mdf_v4.py", line 2366, in append
    seek(0, 2)
  File "C:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
ValueError: seek of closed file
  
# Description
Crash when trying to append a signal in a mf4 file.
Is this a Python issue ? https://bugs.python.org/issue29245

**Comment by danielhrisca** [comment]
Hello Dimitrios,

what memory option did you use to create the _mdf_ object?

**Comment by danielhrisca** [comment]
This works:

```python
from asammdf import MDF, Signal

for memory in ('full', 'minimum', 'low'):
    mdf = MDF(memory=memory)
    sig = Signal([1,2,3], [4,5,6], name='sss')
    mdf.append([sig,])
```

this gives the same error since the context manager calls the _close_ method which closes the temporaryfile

```python
from asammdf import MDF, Signal

for memory in ('full', 'minimum', 'low'):
    with MDF(memory=memory) as mdf:
        sig = Signal([1,2,3], [4,5,6], name='sss')
    mdf.append([sig,])
```

**Comment by dglent** [comment]
I don't give any option for the memory
It seems that is full  by default
>>>mdf.memory
'full'

**Comment by danielhrisca** [comment]
Did you use the context manager? Did you call _close_ before the _append_?

**Comment by dglent** [comment]
No, i don't use context manager neither i call _close_
I use the same code for MDF3 and i don't have any problem.
I open the file eg mdffile = asammdf.MDF('file.mf4')
Then i do some calculations with the signals
Then i create a new signal and i append it to the mdffile
Something is different between the behaviour of MDF3 and MDF4 in the above steps

**Comment by danielhrisca** [comment]
Please check the latest development code. This issue should be fixed

**Comment by dglent** [comment]
I applied the above fix and it works fine now
Thanks !
