### ISSUE TITLE
No file exported with format parameter of export command for MAT files

### ISSUE THREAD

**Issue by hhalaby** [danielhrisca/asammdf#662]
# Python version
'python=3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.22.2'
'asammdf=7.0.7'
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  4.10

  ## Code snippet
 `mdf_test.export(fmt='mat', filename=Path(r'D:\F005D010_v7.mat'), compression=True, format='7.3')`
  
  ## Traceback
  Nothing is printed
  
# Description

Exporting an MDF file to a MAT file while specifying format parameter doesn't seem to change or do anything.

with format='4' and format='5', the export command outputs a .mat file that says `MATLAB 5.0 MAT-file Platform`
with format='7.3', the export command doesn't even output a file and nothing is printed.

Scrambled test file is uploaded. Please make sure to notify me if any personal data are found in the file and to delete the file.

Any ideas?

Extra bonus: trying to read the generated MAT files with scipy.io.loadmat(matfile) fails with `TypeError: buffer is too small for requested array` but I guess that's unrelated ?

**Comment by danielhrisca** [comment]
Do you have hdf5stirage installed?

**Comment by hhalaby** [comment]
I did not have hdf5storage installed. I installed it and tried again. 

- format='4' and format='5' are still giving the same mat file that says `MATLAB 5.0 MAT-file Platform`.
- format='7.3' now outputs a file but throws the error below.

Can I safely use the output file? If not, is there a parameter to specify to avoid this?

Thanks a lot for your time.

Error with format='7.3':

> Traceback (most recent call last):
>   File "C:\python397\lib\code.py", line 90, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
>   File "C:\venvs\src_dataviz\lib\site-packages\asammdf\mdf.py", line 1731, in export
>     savemat(
>   File "C:\venvs\src_dataviz\lib\site-packages\hdf5storage\__init__.py", line 1676, in savemat
>     writes(mdict=mdict, filename=file_name,
>   File "C:\venvs\src_dataviz\lib\site-packages\hdf5storage\__init__.py", line 1316, in writes
>     lowlevel.write_data(f, grp, targetname, data,
>   File "C:\venvs\src_dataviz\lib\site-packages\hdf5storage\lowlevel.py", line 114, in write_data
>     m.write(f, grp, name, data, type_string, options)
>   File "C:\venvs\src_dataviz\lib\site-packages\hdf5storage\Marshallers.py", line 601, in write
>     raise NotImplementedError( \
> NotImplementedError: Cant write non-ASCII numpy.bytes_.

**Comment by hhalaby** [comment]
@danielhrisca Hello Daniel
I have pinpointed the issue to the exact signal causing the problem. Its a signal that contains the following text at every timestamp: `display mode in °C`. 

The issue is with the degree symbol ` ° ` which is non-ASCII.

What is in your opinion the best way to handle this? Is there any quick conversion possible? I am even open to a quick method to delete the degree symbol or any non-ASCII symbol entirely from the entire MDF file prior to conversion to MAT.

Thank you for your help.

**Comment by hhalaby** [comment]
Apologies for not answering your suggestion. I had changed projects and companies in the meantime unfortunately.
