### ISSUE TITLE
mdf_file.iter_groups() problem

### ISSUE THREAD

**Issue by jenicekhartigu** [danielhrisca/asammdf#665]
# Python version
'python=2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]'
'os=Windows-10-10.0.19041'
'numpy=1.16.6'
No handlers could be found for logger "canmatrix.formats"

'asammdf=4.7.12' !

# Code 
            iGroupIndex = 0
            for group in mdf_file.iter_groups():
                sDevice = ''
                iChannelIndex = 0
                #mdfversioncheck
                if (re.match('4\.\d\d', mdf_version)):
                    sDevice = "\\" + mdf_file.get(group = iGroupIndex, index = 1).source.path
                print(group.keys())
                
                keys = list(group.keys())
                for key in keys:
                    #validationstatement
                    bInvalidSignal = False
                    #stringname
                    sChannelName = mdf_file.get(group = iGroupIndex, index = iChannelIndex).name
                    #wholesignal
                    sigChannel = mdf_file.get(group = iGroupIndex, index = iChannelIndex)
                    #### Some validation logic ####
                        lModelChannelsNames.append([str(sChannelName), int(iGroupIndex), int(iChannelIndex)])
                        
                    iChannelIndex += 1
                    
                iGroupIndex += 1
  ## MDF version
  mdf 4.10
            
  
  ## Traceback
MDF ============================================================================
name: files\2022-02-23__13-24-57_Mode1_MeasurementAnalysis.mf4
version: 4.10
memory: full
read fragment size: 0
write fragment size: 4194304

GROUP ==========================================================================
sorted: True
data location: 2
data block type: 0
param: 0
data size: []
.......
 Traceback (most recent call last):
  File "c:\_internal.py", line 61, in getMeasurementData
    for group in mdf_file.iter_groups():
  File "C:\Python27\lib\site-packages\asammdf\mdf.py", line 2415, in iter_groups
    yield self.get_group(i)
  File "C:\Python27\lib\site-packages\asammdf\mdf.py", line 3019, in get_group
    self.get(group=i, index=j, data=fragment, samples_only=True)[0]
  File "C:\Python27\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4560, in get
    i
IndexError: list index out of range
  
# Description
Hi Daniel,

I have problem with iter_groups() when the iteration reach exact singal, it drop with this traceback.

I need iterate file by groups and for each group by signals, to keep names of signals ,indexes of group and indexes of signal for new mdf file. Because occasionaly i can have same signal names but they are measured on different devices.

I can acces group and get informations from group directly via:
            sDevice = mdf_file.get(group = 29, index = 1).source.path

Have you any help for resolve this problem or some advices which i can try to do it better ?

**Comment by danielhrisca** [comment]
asammdf 4.x.y is not developed anymore. You should switch to Python 3.7+ to be able to use the latest version
