### ISSUE TITLE
GUI shows UTC time instead of PC time in 7.0.7

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#669]
**Expected behavior**
When displaying the absolute time & date in the GUI, the usual behavior in previous asammdf versions has been to display the **PC time**, which makes it easy to interpret the data regardless of where it was recorded. 

**Actual behavior**
In asammdf 7.0.7 and more recent dev versions, the time is instead displayed as UTC. It would be great to fix this so it is again PC time.

**Comment by danielhrisca** [comment]
Hello Martin,

were is this visible?

**Comment by MatinF** [comment]
It's visible in the tabular display when showing absolute date and time - see e.g. attached log file where you should be able to see that it shows in UTC in 7.0.7, while older versions would show localized PC time. 

[00000008-5F11686D.zip](https://github.com/danielhrisca/asammdf/files/8333763/00000008-5F11686D.zip)

**Comment by danielhrisca** [comment]
@MatinF the development branch seems to display it correctly now 

![image](https://user-images.githubusercontent.com/20952040/187861375-c0dea48b-7f79-455a-bf34-78239140e3e5.png)
![image](https://user-images.githubusercontent.com/20952040/187861451-4e9e71dc-8b3c-49ec-b26e-fc3f47f66ef1.png)

**Comment by MatinF** [comment]
Hi Daniel, it looks like it's not yet fixed in the dev version.

The timestamps are currently not localized by PC time, but rather shown in their original form. In the log file example you have, this means the date and time is shown in UTC (GMT+0.00). In earlier versions of asammdf, the date and time would be localized so that in the case of Denmark I'd see "+02:00" next to each timestamp and the timestamps in your picture would be 10:56:12.

Hope clear

**Comment by danielhrisca** [comment]
@MartinF please check the development branch for the time stamp localization in the tabular windows

**Comment by MatinF** [comment]
Thanks a lot, this is resolved for me in the latest dev version!

I think the main outstanding prior to a new release for us after this is the J1939 invalid signals issue
