### ISSUE TITLE
Cant export to csv.

### ISSUE THREAD

**Issue by martenlindblad** [danielhrisca/asammdf#68]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
('python=3.6.5 (default, Apr 25 2018, 14:23:58) \n'
 '[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]')

pprint("os=" + platform.platform())
'os=Darwin-17.5.0-x86_64-i386-64bit'

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass
'numpy=1.14.3'

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
'asammdf=3.4.3'
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)
3.00

  ## Code snippet
  _please write here the code snippet that triggers the error_
 mdf.export('csv')

  ## Traceback
  _please write here the error traceback_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/asammdf/mdf.py", line 1294, in export
    master.samples -= master.samples[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
  
# Description
_Please describe the issue here._
Can't export to csv.

**Comment by danielhrisca** [comment]
Hello Mårten,

please check if the fix is working (development branch https://github.com/danielhrisca/asammdf/commit/6d41565cbc044a77372e82a212659a4de83605a3)
