### ISSUE TITLE
Copying value from Tabular Display results in low-res scientific notation (7.0.7)

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#680]
I've DBC decoded some data from our CANmod.gps module in asammdf and I'm now reviewing the epoch timestamp in the tabular display. In doing so, I'm looking to copy a value from the tabular display into my browser:
![image](https://user-images.githubusercontent.com/26184427/160988620-7c70756b-a7c3-494b-a8ca-9954acda11a9.png)

However, in doing so, the value I copy is instead the below:
1.616771e+09

This is a problem as the precision above is not sufficient. Is it possible to modify this so that the original format of the number is retained, rather than the scientific notation?

**Comment by danielhrisca** [comment]
@martin please try the development branch
