### ISSUE TITLE
Reading Channel Causes Crash

### ISSUE THREAD

**Issue by lkuza2** [danielhrisca/asammdf#685]
# Python version
('python=3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19043-SP0'
'numpy=1.22.3'
ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.0.7'

# Code 

  ## MDF version
  4.10

  ## Code snippet
```
    data = MDF(mf4_file)
    sig = data.get('MIPI_CSI2_Frame.DataBytes')  # type: Signal Error occurs here
    real_sam = sig.samples  # type: ndarray
    offset = real_sam[0].size - 25
```
 OR   
```
    it_data = data.iter_get(name='MIPI_CSI2_Frame.DataBytes', samples_only=True, raw=True)
    next(it_data) # error occurs here
```
  
  ## Traceback
```
Traceback (most recent call last):
  File "C:\Users\xxxx\PycharmProjects\MF4Convert\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7442, in _get_scalar
    vals = extract(signal_data, 1, vals - vals[0])
SystemError: <built-in function __import__> returned a result with an error set

Process finished with exit code -1073741819 (0xC0000005) 
```
# Description

File is very large ~3.5GB, trying to read data from the mentioned channel using either the iteration method or Signal methods causes an error.  A similar file ~1.7GB in size reads fine.  Both load into the asammdf tool just fine, including the file causing the crash, however the file causing the crash causes the same error I have above whenever i try to export data with the GUI.

Reading a different channel in this file does not result in the error.

The machine im using has 32GB of RAM and plenty of storage space.

**Comment by danielhrisca** [comment]
Hello @lkuza2 
please insert the following print just before this line https://github.com/danielhrisca/asammdf/blob/1507f100bddc86c5f037db2770ec39e42bdfc306/asammdf/blocks/mdf_v4.py#L7442

```python
                    print(len(signal_data),  (vals-vals[0])[-1])
```

**Comment by lkuza2** [comment]
@danielhrisca

Putting the following print before line 7442 gives the following output:

`3744170100 3740009911`

Let me know how else I can help :)

**Comment by danielhrisca** [comment]
That's a lazy way to write the file (I suppose it has a single data block of 3.5GB). How big is a frame? I think there is a .DataLenght singal that holds this info

**Comment by lkuza2** [comment]
@danielhrisca 
Unfortunately I don't get to control how the file is written :(

It is written with raw YUV data for each frame (1184x884).  Each sample of the signal is a different frame.  There pretty much isn't any other data in the file.

The DataLength for each frame is 4160185

**Comment by danielhrisca** [comment]
So the data length looks consistent. How much RAM do you have on the system?

**Comment by lkuza2** [comment]
@danielhrisca 
"The machine im using has 32GB of RAM and plenty of storage space."

**Comment by danielhrisca** [comment]
I'll prepare a version with some debug prints . Did you already try the development branch code?

**Comment by lkuza2** [comment]
I just downloaded the latest version of the development branch to try it out (7.1.0dev31).  I get the same exit code and crash: 1073741819 :(  This is using the signal sample method

**Comment by lkuza2** [comment]
Just tried the latest version of the development branch as of this comment, and still the same issue unfortunately :(

**Comment by danielhrisca** [comment]
Just make sure, please delete the asammdf folders from site-packages and install again

**Comment by lkuza2** [comment]
Haha, that's actually exactly what I did because I was paranoid it would use old code.

**Comment by danielhrisca** [comment]
It there anything printed before the crash?

**Comment by lkuza2** [comment]
Nothing printed before the crash still.

**Comment by danielhrisca** [comment]
Can you send the file for analysis?

**Comment by lkuza2** [comment]
Can I use the scramble method to scramble the data?

**Comment by danielhrisca** [comment]
That will only scramble the text blocks, not the raw channel data. The idea is to preserve the internal file structure

**Comment by lkuza2** [comment]
Let me see if I can get it uploaded.  If so, it would have to be private, unshared, and deleted whenever the testing by you is completed, if that is okay?

**Comment by danielhrisca** [comment]
Of course, I can give you access to a Google drive folder. You can find my email iny profile

**Comment by lkuza2** [comment]
Ill actually upload it to our Google Drive and share the link to your Google account and delete it once you are done, if that is okay?

**Comment by lkuza2** [comment]
I sent it to you. Let me know if there is more I can help with.  Thank you :)

**Comment by danielhrisca** [comment]
I've had a look at the file. I'm not sure if the file is not written correctly or if there is a problem in my code.

The signal ``xxx.DataBytes`` is a VLSD signal. This means that the actual data is found in separate data blocks, and this channel only holds the offsets in that data block were the corresponding sample is found. In the referenced data block, at the address pointed by ``xxx.DataBytes`` we will find an uint32 header that holds the bytes count for the current sample. 

When extracting the actual bytes we can do two things:
1. use the offsets to read the uint32 header and then the actual sample bytes
2. assume that the data block does not have gaps (contiguous headers and samples) and ignore the offsets. Instead start from the beginning of the data block and iteratively read the uint32 headers and then the sample 

Currently the first approach is used, which should be the error proof way to go about; if the data block is not contiguous then this method would still work, while the second method would crash or produce garbage data.

Coming now to your file at sample number 646 of the 900 frames the header suddenly returns a size of 1065007615 instead of 4160185. So we start to read way beyond the correct memory space and finally crash. If I switch the code to use the second method then everything is ok.

You can also do this on your side by changing https://github.com/danielhrisca/asammdf/blob/1507f100bddc86c5f037db2770ec39e42bdfc306/asammdf/blocks/mdf_v4.py#L7442 with this line

```python
                    vals = extract(signal_data, 1, None)
```

**Comment by lkuza2** [comment]
I honestly wouldn't be surprised at all if the files were written incorrectly.  That is super strange that the size suddenly jumps like that.  I tried a few more files written from the same source (the larger ~3.5GB ones, like i said the smaller ~1.5GB ones work fine) and they all crash similarly, meaning it was not a one off thing.

Using the change given, I can confirm the data is read correctly from the file without crashing.  However, like you said, method one should be the preferred and correct method.  

I am not sure how else to help other than confirm that the change does fix the issue for this type of file.

**Comment by david32** [comment]
> Coming now to your file at sample number 518 of the 900 frames the header suddenly returns a size of 1065007615 instead of 4160185. So we start to read way beyond the correct memory space and finally crash.

Well, in get_channel_raw_bytes is using Py_ssize_t as  a variable for byte offset and count. Which should be fine as the system is 64-bit. yet its very odd that the byte count changes exactly when a 32-bit signed integer would overflow (after 516 iterations) .

Adding to that, the smaller files do work.

Perhaps this direction could be looked at.

**Comment by lkuza2** [comment]
@david32 I also had the gut feeling when this originally errored out that there was an overflow/underflow occurring.  But, however, like you said, my Python environment is 64bit and my machine is 64bit, so that is strange that it would be using 32 bit integers.  The only thing I can think is that the C extensions are being built with a 32bit compiler on my machine?  I am not sure how I would be able to check that.

**Comment by danielhrisca** [comment]
I tend to believe that the error comes from my C extension code.

**Comment by danielhrisca** [comment]
@lkuza2 finally it was bug in the C extension code where I was using an int32 value for the offsets, thus crashing on signal data blocks longer then ~2GB

**Comment by lkuza2** [comment]
@danielhrisca That was it.  I just tried the latest development branch and the file read without crash and correctly.  Amazing work and thank you :)

**Comment by danielhrisca** [comment]
I would have takes ages to debug without your file. Thank you very much!

**Comment by danielhrisca** [comment]
> Well, in get_channel_raw_bytes is using Py_ssize_t as a variable for byte offset and count. Which should be fine as the system is 64-bit. yet its very odd that the byte count changes exactly when a 32-bit signed integer would overflow (after 516 iterations) .
> 
> Adding to that, the smaller files do work.
> 
> Perhaps this direction could be looked at.

Good insight. Sorry I've missed it when you posted it
