### ISSUE TITLE
v7.0.7 - suggest to enable 'sub windows' as default

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#686]
I suggest making the 'sub windows' property the default state in asammdf, thus allowing users to drag & drop multiple plots onto the gray area to create multi-panel views. I believe this may have been the default in previous versions, but it seems to not be the case in 7.0.7.

**Comment by danielhrisca** [comment]
It was always off by default but I don't see why it could not enabled

**Comment by MatinF** [comment]
OK I may have missed it then - would be great to have it enabled by default
