### ISSUE TITLE
MDF.py Line 4385 AttributeError upon extracting bus log 

### ISSUE THREAD

**Issue by AFBecan** [danielhrisca/asammdf#687]
# Python version
The code that reported AttributeError due to mdf.py line 4385 is as below
```python
import asammdf
logfile = ["00002081.mf4"]
dbc = ["CSS-Electronics-SAE-J1939-DEMO.dbc"]

mdf = asammdf.MDF.concatenate(logfile)
mdf_scaled = mdf.extract_bus_logging(dbc)

mdf_scaled.export("csv", filename="scaled", single_time_base=True)
```
 ## Attribute Error
```python
----> mdf_scaled = mdf.extract_bus_logging(dbc)
-> 4385 [if database_files.get("CAN", None):]()
AttributeError: 'list' object has no attribute 'get'
```
# Description

This code snippet is from CSS Electronics website's DBC Convert & Plot CAN Data video clip. I have so far used this only in VS Code, I have not used other compilers yet. Due to the code being old, the variable mdf_scaled had to be called via extract_bus_logging, which has replaced extract_can_logging as shown in the video. If the mdf.py script has to call a _get_ function, then what is the alternative way to export the **logfile** together with **dbc** to generate an output of decoded measurements?

**Comment by danielhrisca** [comment]
The was an API change with the recent asammdf versions. Now you need to provide a dict

**Comment by danielhrisca** [comment]
@AFBecan see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.extract_bus_logging

**Comment by AFBecan** [comment]
> @AFBecan see https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.extract_bus_logging

I resolved it.
