### ISSUE TITLE
Unexpected output on console (neither error nor warning) while reading MF4 file.

### ISSUE THREAD

**Issue by gdu2003** [danielhrisca/asammdf#69]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```

('python=3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit '
 '(AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.14.3'
'asammdf=3.5.0'

# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

>print(MDF4(mdf_file).version)
Expected CG, SD, DL, DZ or CN block at 0x602b008 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b068 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b0c8 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b128 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b188 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b1e8 but found id="b'##AT'"
4.00

  ## Code snippet
  _please write here the code snippet that triggers the error_
>asam_mdfdata = MDF4(mdf_file)
  
  ## Traceback
  _please write here the error traceback_
There is no error traceback.
  
# Description
_Please describe the issue here._
After reading the file: Following things gets printed in console
>asam_mdfdata = MDF4(mdf_file)
Expected CG, SD, DL, DZ or CN block at 0x602b008 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b068 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b0c8 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b128 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b188 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b1e8 but found id="b'##AT'"

Even if i use asammdf.MDF module to read MF4 file , i still get same output on console

>test = asammdf.MDF(name = mdf_file)
Expected CG, SD, DL, DZ or CN block at 0x602b008 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b068 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b0c8 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b128 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b188 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b1e8 but found id="b'##AT'"

**Comment by gdu2003** [comment]
Did that, see the new output below:

>asammdf.MDF(mdf_file)

Expected CG, SD, DL, DZ or CN block at 0x602b008 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b068 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b0c8 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b128 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b188 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b1e8 but found id="b'##AT'"
<Channel (name: VIDEO_TIMECODE, unit: s, comment: <CNcomment><TX>Time offset in seconds into the attached video file</TX><names><display>VIDEO_TIMECODE\LEFTSIDE</display></names><raster>0.000100</raster></CNcomment>, address: 0x9df008, conversion: <ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: {}, address: 0x6fe1b0, fields: {'max_phy_value': 0.0, 'id': b'##CC', 'unit_addr': 0, 'precision': 0, 'links_nr': 4, 'ref_param_nr': 0, 'reserved0': 0, 'val_param_nr': 0, 'flags': 0, 'block_len': 80, 'conversion_type': 0, 'inv_conv_addr': 0, 'name_addr': 0, 'min_phy_value': 0.0, 'comment_addr': 0})>, source: <SourceInformation (name: , path: LEFTSIDE, comment: , address: 0x9defd0, fields: {'id': b'##SI', 'bus_type': 0, 'path_addr': 5522304, 'links_nr': 3, 'reserved0': 0, 'flags': 0, 'source_type': 2, 'block_len': 56, 'reserved1': b'\x00\x00\x00\x00\x00', 'name_addr': 0, 'comment_addr': 0})>, fields: {'id': b'##CN', 'pos_invalidation_bit': 0, 'sync_type': 1, 'unit_addr': 5522576, 'component_addr': 0, 'max_raw_value': 0.0, 'precision': 48, 'bit_offset': 0, 'bit_count': 64, 'upper_limit': 0.0, 'byte_offset': 8, 'lower_ext_limit': 0.0, 'min_raw_value': 0.0, 'channel_type': 4, 'reserved1': 0, 'block_len': 160, 'source_addr': 10350544, 'comment_addr': 5522344, 'data_block_addr': 100839816, 'data_type': 4, 'conversion_addr': 7331920, 'name_addr': 5522264, 'attachment_nr': 0, 'links_nr': 8, 'lower_limit': 0.0, 'next_ch_addr': 0, 'flags': 0, 'reserved0': 0, 'upper_ext_limit': 0.0})>

Out[61]: <asammdf.mdf.MDF at 0x2d47a9e8>

>asammdf.MDF4(mdf_file)

Expected CG, SD, DL, DZ or CN block at 0x602b008 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b068 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b0c8 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b128 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b188 but found id="b'##AT'"
Expected CG, SD, DL, DZ or CN block at 0x602b1e8 but found id="b'##AT'"
<Channel (name: VIDEO_TIMECODE, unit: s, comment: <CNcomment><TX>Time offset in seconds into the attached video file</TX><names><display>VIDEO_TIMECODE\LEFTSIDE</display></names><raster>0.000100</raster></CNcomment>, address: 0x9df008, conversion: <ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: {}, address: 0x6fe1b0, fields: {'max_phy_value': 0.0, 'id': b'##CC', 'unit_addr': 0, 'precision': 0, 'links_nr': 4, 'ref_param_nr': 0, 'reserved0': 0, 'val_param_nr': 0, 'flags': 0, 'block_len': 80, 'conversion_type': 0, 'inv_conv_addr': 0, 'name_addr': 0, 'min_phy_value': 0.0, 'comment_addr': 0})>, source: <SourceInformation (name: , path: LEFTSIDE, comment: , address: 0x9defd0, fields: {'id': b'##SI', 'bus_type': 0, 'path_addr': 5522304, 'links_nr': 3, 'reserved0': 0, 'flags': 0, 'source_type': 2, 'block_len': 56, 'reserved1': b'\x00\x00\x00\x00\x00', 'name_addr': 0, 'comment_addr': 0})>, fields: {'id': b'##CN', 'pos_invalidation_bit': 0, 'sync_type': 1, 'unit_addr': 5522576, 'component_addr': 0, 'max_raw_value': 0.0, 'precision': 48, 'bit_offset': 0, 'bit_count': 64, 'upper_limit': 0.0, 'byte_offset': 8, 'lower_ext_limit': 0.0, 'min_raw_value': 0.0, 'channel_type': 4, 'reserved1': 0, 'block_len': 160, 'source_addr': 10350544, 'comment_addr': 5522344, 'data_block_addr': 100839816, 'data_type': 4, 'conversion_addr': 7331920, 'name_addr': 5522264, 'attachment_nr': 0, 'links_nr': 8, 'lower_limit': 0.0, 'next_ch_addr': 0, 'flags': 0, 'reserved0': 0, 'upper_ext_limit': 0.0})>

Out[62]: <asammdf.mdf_v4.MDF4 at 0x42653dd8>

It is not causing any issue in reading MF4 file i am getting all the Signals.

**Comment by danielhrisca** [comment]
@gdu2003 
can you check if the latest _development_ code works correctly?

**Comment by danielhrisca** [comment]
Please re-open if there are still errors.
