### ISSUE TITLE
MDF concatenation silently introduces additional samples which errors if signals are extracted from the concatenated file.

### ISSUE THREAD

**Issue by muendlein** [danielhrisca/asammdf#694]
# Python version

Python 3.9
asammdf 7.07

# Code 

  ## MDF version
 4.1

  ## Code snippet
My code more or less looks like this which works fine for most of the files however in certain cases when concatenating two files additional samples (only a few) are silently introduced which error out when accessing the signals.
```
mdf_1 = MDF(path1, channels=some_channels).filter(some_channels)
mdf_2 = MDF(path2, channels=some_channels).filter(some_channels)

mdf_concat =  MDF.concatenate([mdf_1 , mdf_2])
signal = mdf_concat.select([some_channels[0]])     # This triggers an error
```

An error is triggered at https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L2983 due to a shape mismatch.
In particular `master[current_pos:next_pos]` has the expected concatenated size while `sigs[0].timestamps` has additional samples which obviously triggers an error.

```
master = np.empty(cycles, dtype=sigs[0].timestamps.dtype)
-> master[current_pos:next_pos] = sigs[0].timestamps
```

It should be noted that during concatenating no error is thrown, only when the data is accessed later on. As I cannot disclose the files/and their structure I am looking for some guidance towards the origin of the additional samples during concatenation.

Issue looks similar to
https://github.com/danielhrisca/asammdf/issues/467

**Comment by danielhrisca** [comment]
what about if you save the concatenated file to the disk, and then reload it?

**Comment by muendlein** [comment]
> what about if you save the concatenated file to the disk, and then reload it?

@danielhrisca  Saving and reloading the concatenated file won't trigger an error later on however the data appears to be corrupted. In particular the additional samples are fully present now, most timestamp are NaT and for valid timestamps the corresponding data does not have the correct values.

**Comment by danielhrisca** [comment]
@muendlein please check with the development branch
