### ISSUE TITLE
ValueError: array-shape mismatch in array 5 

### ISSUE THREAD

**Issue by RobertMouncer** [danielhrisca/asammdf#695]
# Python version
_Please run the following snippet and write the output here_
```
('python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.22.3'
'asammdf=7.1.0.dev41'

```
# Code 

  ## MDF version
`4.11`

  ## Code snippet
```
  from asammdf import MDF
  mdf_files = [path_MDF]*4
  mdf = MDF.concatenate(mdf_files)
```
  
  ## Traceback
  ```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 3, in test_concat
  File "\venv\lib\site-packages\asammdf\mdf.py", line 2329, in concatenate
    for idx, signals in enumerate(
  File "\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7933, in _yield_selected_signals
    self.get(
  File "venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6438, in get
    vals, timestamps, invalidation_bits, encoding = self._get_structure(
  File "\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6680, in _get_structure
    vals = fromarrays(arrays, dtype=types)
  File "venv\lib\site-packages\numpy\core\records.py", line 676, in fromarrays
    raise ValueError(f'array-shape mismatch in array {k} ("{name}")')
ValueError: array-shape mismatch in array 5 ("CAN_DataFrame.DataBytes")
```
  
# Description

I will send you the scambled file via email. 
I am concatenating multiple files together but this one file fails. I was previously using asammdf version 7.0.2 but saw that the issue was resolved in #685 after updating to the development branch, a different issue was hit.

**Comment by RobertMouncer** [comment]
@danielhrisca I have had this issue with another file if you would like me to send it to you to help with the issue.

**Comment by danielhrisca** [comment]
@RobertMouncer do you get the error with all your files? or jest the one you have send?

**Comment by RobertMouncer** [comment]
@danielhrisca I have only ever seen this issue on 2 files. 10's (if not 100's) of thousands of these files have been generated and I've only had this issue with 2 files recently.

**Comment by danielhrisca** [comment]
The file is definitely corrupted. I will get in touch with the CSS guys

**Comment by RobertMouncer** [comment]
@danielhrisca Thank you. I have been intouch with them already. They suspected corruption but they couldn't say for certain, I'm glad you could confirm it. Thank you very much for looking into it. Much appreciated. 
Big fan of the library as always <3

**Comment by danielhrisca** [comment]
Can I send the file to CSS?

**Comment by RobertMouncer** [comment]
@danielhrisca 
See my last comment. 
I have already sent them the file, They suspected it was corruption but wasn't 100% sure. If they are requesting the file again, please do send it :)
Cheers.

**Comment by danielhrisca** [comment]
I wanted to be 100% that I have your permission to distribute the file. It is very important to have this otherwise nobody would send files for analysis anymore

**Comment by MatinF** [comment]
Hi guys, just a quick comment here from CSS: 

I believe either this problem is related to SD card corruption (as discussed separately Robert). Alternatively, it can be an issue if you are using an old MF4 converter to decompress the data. I suggest double checking if the problem persists with the latest mdf2finalized 1.2.0 - if yes, then the problem is most likely with SD card corruption. I do not believe this is an issue related to asammdf.
