### ISSUE TITLE
Cannot load J1939 .dbc file into asammdf without Division by Zero error

### ISSUE THREAD

**Issue by jd-salazar** [danielhrisca/asammdf#699]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
Output:
('python=3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 '
 'bit (AMD64)]')

'os=Windows-10-10.0.22000-SP0'

'numpy=1.22.3'

ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.0.7'

# Code 

I'm using GUI.

  ## MDF version
>>> print(MDF(file).version)
===== 2022.05.10 14:05:16 =====
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'MDF' is not defined

  ## Code snippet
I'm using GUI.
  
  ## Traceback
Error: <class 'ZeroDivisionError'>	 
division by zero

Details: 2022-05-10, 14:03:55
--------------------------------------------------------------------------------
<class 'ZeroDivisionError'>	 
division by zero
--------------------------------------------------------------------------------
  File "C:\Users\JavierSalazar\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\gui\widgets\batch.py", line 225, in extract_bus_logging
    delta = 100 / count

  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

I can't load a .dbc file into asammdf. I am using the J1939 .dbc file that CSS Electronics sells.

**Comment by danielhrisca** [comment]
In the batch mode you also have to provide some MDF files to be process with the given DBC files

**Comment by danielhrisca** [comment]
Can you share a minimal file?
