### ISSUE TITLE
Problem with changing samples of one channel with samples of another one

### ISSUE THREAD

**Issue by jurezic** [danielhrisca/asammdf#700]
versions: Python  - 3.8.5
              asammdf==5.14.3

code:

file_mdf = MDF(mypath)
first_channel = file_mdf.get(first)
second_channel = file_mdf.get(second)

first.samples = second.samples #after this line when I print out the first channels samples, they come out as having values of second  

file_mdf.save()

The issue:
After saving the file and opening it up again, the values of the first channel are unchanged although while printing them before saving they were different (same as second one).
Any ideas?

**Comment by danielhrisca** [comment]
see https://asammdf.readthedocs.io/en/latest/tips.html#data-coupling

**Comment by jurezic** [comment]
Thank you for a quick response!

From what I can see from the link, actually asammdf does not provide us a way to change raw data in mdf file?

Thanks in advance!

**Comment by danielhrisca** [comment]
The raw data cannot be changed. You need to create a new file with your changed channels
