### ISSUE TITLE
MDF.cut sometimes produces an error or corrupts the output data

### ISSUE THREAD

**Issue by BenWhetton** [danielhrisca/asammdf#704]
# Python version
'python=3.9.9 (main, Apr 28 2022, 15:20:21) \n[GCC 10.3.0]'
'os=Linux-5.13.0-41-generic-x86_64-with-glibc2.31'
'numpy=1.22.3'
'asammdf=7.0.7'
I have also tried asammdf from the tip of the development branch 

# Code

  ## MDF version
4.11

  ## Code snippet
```
from pathlib import Path
from asammdf import MDF
import matplotlib.pyplot as plt

channels = ["FxDyno", "FyDyno", "FzDyno", "MzDyno"]
mdf1 = MDF(name="issue704.mf4", channels=channels)

mdf = mdf1.cut(start=1, stop=7)
FxDyno = mdf.select(["FxDyno"])[0]
plt.plot(FxDyno.timestamps)
plt.show()
```
  
  ## Traceback
N/A
  
# Description
After using `MDF.cut`, the samples and timestamps for all channels contain corrupted data after approximately 249500 samples. This is easy to see in the timestamp plot in the above code snippet.

This doesn't happen with start = 1, stop = 6.

A different bug occurs with start = 0, stop = 5 with this traceback:
```
  File "<my_script>", line 12, in <module>
    FxDyno = mdf.select(["FzDyno"])[0]
  File "/home/engine/projects/experiment-auto-gcode/venv-3.9/lib/python3.9/site-packages/asammdf/mdf.py", line 2983, in select
    master[current_pos:next_pos] = sigs[0].timestamps
ValueError: could not broadcast input array from shape (600318,) into shape (500001,)
```
I'll send the original data file by email.

**Comment by danielhrisca** [comment]
@BenWhetton please try the development branch code

**Comment by BenWhetton** [comment]
This now seems to be fixed on the development branch. I tested another much bigger file too and it works fine. Good work!

Do you have a plan for when to merge the development branch into master? Are you waiting to complete some other features?
