### ISSUE TITLE
GPS plots: Make "Latitude" and "Longitude" signals be pre-filled by default

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#706]
If possible, a nice addition for the (great) GPS plot would be that the Latitude and Longitude fields are pre-filled.

In a simplistic version, this could assume that the names of these two signals are indeed `Latitude` and `Longitude`, which will be the case in most DBC files in my experience. 

In a more sophisticated version, a search could be made for the signal names `Latitude` and `Longitude` in the signal list and make it so that they are pre-filled if they are available in the signal list, otherwise not.

It's a small change, but it would make it more smooth when doing a lot of GPS plots.

**Comment by danielhrisca** [comment]
@MatinF please try the development branch

**Comment by MatinF** [comment]
Hi Daniel, the dev version works for Latitude, but it adds Latitude also for Longitude:
![image](https://user-images.githubusercontent.com/26184427/170009817-3a61c6f5-0add-4e8c-8711-a36312f0dcbb.png)

**Comment by david32** [comment]
Kind of weird, but I have seen files with GPS_x and GPS_y
perhaps then:
`target = "latitude|gps_x"` 
or something like that?

**Comment by danielhrisca** [comment]
> Kind of weird, but I have seen files with GPS_x and GPS_y perhaps then: `target = "latitude|gps_x"` or something like that?

wouldn't that be ``latitude|gps_y`` ?

**Comment by danielhrisca** [comment]
@MatinF @david32 check out the development branch code
