### ISSUE TITLE
Creating a MDF instance from a file-like object 

### ISSUE THREAD

**Issue by chobeat** [danielhrisca/asammdf#71]
Hello,

I just began using asammdf and I'm wondering if it's possible to load data from a file-like object in the proper pythonic way. The default constructor for MDF accepts just a file name and I'm not sure if there's a way to deal with file-like objects.

**Comment by danielhrisca** [comment]
Hello Simone,

so far this is not implemented. What is your use case?

**Comment by chobeat** [comment]
I have the content of an MDF file already in memory (coming from Kafka) and I need to parse it and convert it. Clearly I can write down the file and load it again but it's unnecessarily slow and it's evidently an anti-pattern. With other formats I just convert the content to a file-like object with BytesIO or StringIO and feed it to the parsing library.

**Comment by danielhrisca** [comment]
This is a valid point. I'll have a look at this tonight.

**Comment by chobeat** [comment]
thanks, let me know if I can help

**Comment by danielhrisca** [comment]
Hello Simone,

please have a try with the referenced commit: it should accept BytesIO objects

**Comment by chobeat** [comment]
Ok, tested and it seems to work as intended. Thank you very much

**Comment by danielhrisca** [comment]
Very nice! Re-open this issue if you find problems.

**Comment by kasuteru** [comment]
Correct me if I'm wrong, but it looks like this commit does not call `close()` on the file if opened by string any more? Previously, this was handled by using with XX as file_stream?
