### ISSUE TITLE
CAN.Message.Signal channel name missing when using extract_bus_logging()

### ISSUE THREAD

**Issue by ptoews** [danielhrisca/asammdf#713]
When using the "Extract Bus Signals" functionality in the GUI to extract CAN signals, the resulting MDF file contains channels named "CANX.MessageName.SignalName". However, when using `mdf.extract_bus_logging()`, the resulting mdf does not contain these channels, only the channels consisting of signal names. Is it possible to have these channels in this case as well?

Tested this with version 7.0.0 and 7.0.7.

**Comment by danielhrisca** [comment]
The same API function is used in the GUI. Check out the arguments

**Comment by ptoews** [comment]
I did, I couldn't find one for this.

https://github.com/danielhrisca/asammdf/blob/1507f100bddc86c5f037db2770ec39e42bdfc306/asammdf/mdf.py#L4286-L4294

Prefix is a fixed value, so that doesn't help.

**Comment by ptoews** [comment]
I also checked the code where the GUI calls this method:

https://github.com/danielhrisca/asammdf/blob/1507f100bddc86c5f037db2770ec39e42bdfc306/asammdf/gui/widgets/file.py#L1579-L1586

I added a print to show me the actual argument values that are used when I convert using the GUI, and used them as they are for a manual conversion. The GUI conversion gave me the full channel names, the manual conversion didn't.

To clarify, the GUI conversion gives me additional entries in the `channels_db` attribute, which map to the same group/channel index as the shorter entry (signal name only, which exists as well).

Sadly, I cannot publish the MDFs I'm using but I will see if I can find public ones for a reproducible example.

**Comment by danielhrisca** [comment]
With the development branch code I get identical files with the GUI and API, and both short and long names are available

![image](https://user-images.githubusercontent.com/20952040/171559469-ff7e1ffc-30bb-4fc7-9924-71567bb6cf58.png)

**Comment by danielhrisca** [comment]
Please try the development branch updates

**Comment by ptoews** [comment]
Yes that fixed it. Thanks!
