### ISSUE TITLE
Cam

### ISSUE THREAD

**Issue by dmbelo** [danielhrisca/asammdf#72]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description
_Please describe the issue here._

**Comment by danielhrisca** [comment]
Is this a "wrong window"?

**Comment by dmbelo** [comment]
Please delete - this was a mistake.
