### ISSUE TITLE
is it possible to give a warning about which channel/signal's datatype is wrong, skip the dataframe with wrong data type channel and continue without exiting?

### ISSUE THREAD

**Issue by shuyuan-wang** [danielhrisca/asammdf#723]
When runing the following script under python 3.8, asammdf 7.0.7, windows 10, it produces error:
```
mdf = MDF('***`.MF4')
for group in mdf.iter_groups():
    if group.shape[0] > 0:
        group = group.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
```
The error shows is:
![image](https://user-images.githubusercontent.com/104115572/174508476-5341fcc0-4542-4437-b3be-19b67a9da407.png)
![image](https://user-images.githubusercontent.com/104115572/174508174-ece9af2c-5974-4d82-ba34-1e0b26cbfcd1.png)

Is it possible to give a warning about which channel/signal's datatype is wrong, skip the dataframe with the errorneous channel and continue without exiting? It would be a great help.

**Comment by danielhrisca** [comment]
I think that your problem is solved in the development branch

**Comment by shuyuan-wang** [comment]
I tried it, it fixed the exit issue, but here comes another problem. With the same mf4 file, it gives ValueError: itemsize ccannot be zero in type
![29e70124b995b0f7ee34cb830cddd7d](https://user-images.githubusercontent.com/104115572/174581103-8fde627d-ac30-4e2c-b994-354cff9e75a7.jpg)

**Comment by danielhrisca** [comment]
Can you send the file?

**Comment by danielhrisca** [comment]
You can see it in my profile page

**Comment by shuyuan-wang** [comment]
Sent

**Comment by danielhrisca** [comment]
@shuyuan-wang try the new development branch code
