### ISSUE TITLE
Is it possible to get channel group using CAN ID/ message id?

### ISSUE THREAD

**Issue by shuyuan-wang** [danielhrisca/asammdf#724]
Is it possible to get channel group using CAN ID/message id, not index from zero? no matter it is hex or decimal?

**Comment by danielhrisca** [comment]
have a look in `mdf.bus_logging_map["CAN"]` maybe it can help

**Comment by danielhrisca** [comment]
The second picture is from a decoded measurement were a DBC was used to extract the signals front he raw CAN bus data

**Comment by shuyuan-wang** [comment]
is it possible to get the mapping of decoded message index and can id?

**Comment by danielhrisca** [comment]
> is it possible to get the mapping of decoded message index and can id?

again the DBC file has this information
