### ISSUE TITLE
asammdf show wrong values for unfinished file

### ISSUE THREAD

**Issue by mala-gh** [danielhrisca/asammdf#727]
# Python version
('python=3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19043-SP0'
'numpy=1.22.4'
ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.0.7'

# Code 

  ## MDF version
  4.20

  ## Code snippet
  Opening the file in the gui shows wrong values
  
  ## Traceback
  n.a.
  
# Description

I am writing records to a mdf-file with a self developed application (not using asammdf) and then use the gui to view the results.
The file is unfinished, so the cycle_count in the DG is wrong (= 0) and the length of the DT block is wrong aswell (= length of DT header, but not header+data).
My data does not have a record id and consists of 1 float32 master time channel and one uint8 signal.
When i write 8 samples of these records and load it into asammdf-gui everything works fine. 
When I write 200 samples, the time and signal1 show wrong values (even in the first 8 samples).
I am not sure, if the MDF file is faulty or there is an issue in the interpretation in asammdf.
[output.zip](https://github.com/danielhrisca/asammdf/files/8984836/output.zip)

**Comment by danielhrisca** [comment]
Hello @mala-gh 

you are botching the file write somehow :

![image](https://user-images.githubusercontent.com/20952040/175785582-64c0c5c1-f0f8-4d91-b99d-0d6ed4c54bbd.png)

I've highlighted the `signal1` bytes in the DTBLOCK. The green part is ok, but at the 10-th sample there is a `0xOD` byte inserted, then the blue highlight looks like the expected samples, but they are shifted with 1byte.

**Comment by mala-gh** [comment]
Thanks, it was the windows quirk of converting \n to \r\n while writing files. Solved with fopen("file.mdf4", "w**b**").

**Comment by danielhrisca** [comment]
Always work in binary mode with mdf files. Can you share some details about your application?

**Comment by mala-gh** [comment]
I am working on a library to write mdf4 files on a microcontroller to capture data while the program on the controller is executing.
The program itself for me will be a piece of automotive system controller connected to a vehicle model.

So the typical microcontroller restrictions apply: 
- limited amount of RAM -> only a chunk of the mdf file can be kept in memory, no heap allocation
- writing data to SD card will probably include some lag -> chunked writing
- system is started and stopped by power supply -> there is no guarantee, that the file can be finished before power is lost

Until now I developed the mdf writer on a windows machine and will now port it to a STM32F4 discovery board.
