### ISSUE TITLE
GUI reports a error when add acursor

### ISSUE THREAD

**Issue by CSG2019** [danielhrisca/asammdf#728]
Hello , 
I just installed the asammdf gui and I tried to import a mdf file, then add the signal into the GUI, but there is a error happened as below, could you please help me to understand how to fix it? thank you.
![image](https://user-images.githubusercontent.com/53852255/175803474-a1510a51-e993-4cac-99ac-8474374bec3b.png)

**Comment by danielhrisca** [comment]
You have an old pyqtgraph version. Update to 0.12.4

**Comment by CSG2019** [comment]
Thank you, after updating this library, it can work.
