### ISSUE TITLE
Error reading .mf4 file

### ISSUE THREAD

**Issue by dmbelo** [danielhrisca/asammdf#73]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```

```
('python=3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.14.2'
'asammdf=3.5.0'
```

# Code 

  ## MDF version
  4.1

  ## Code snippet
```
import asammdf
mdf = asammdf.MDF('test.mf4')
```
  
  ## Traceback
```
ParseError                                Traceback (most recent call last)
c:\python36\lib\site-packages\IPython\core\interactiveshell.py in safe_execfile(self, fname, exit_ignore, raise_exceptions, shell_futures, *where)
   2525                 py3compat.execfile(
   2526                     fname, glob, loc,
-> 2527                     self.compile if shell_futures else None)
   2528             except SystemExit as status:
   2529                 # If the call was made with 0 or None exit status (sys.exit(0)

c:\python36\lib\site-packages\IPython\utils\py3compat.py in execfile(fname, glob, loc, compiler)
    186     with open(fname, 'rb') as f:
    187         compiler = compiler or compile
--> 188         exec(compiler(f.read(), fname, 'exec'), glob, loc)
    189
    190 # Refactor print statements in doctests.

~\Desktop\uvalde_tl2\run.py in <module>()
      1 import asammdf
      2
----> 3 mdf = asammdf.MDF('test.mf4')

c:\python36\lib\site-packages\asammdf\mdf.py in __init__(self, name, memory, version, callback)
     96                     self._mdf = MDF3(name, memory, callback=callback)
     97                 elif version in MDF4_VERSIONS:
---> 98                     self._mdf = MDF4(name, memory, callback=callback)
     99                 elif version in MDF2_VERSIONS:
    100                     self._mdf = MDF2(name, memory, callback=callback)

c:\python36\lib\site-packages\asammdf\mdf_v4.py in __init__(self, name, memory, version, callback)
    340         if name:
    341             self._file = open(self.name, 'rb')
--> 342             self._read()
    343
    344         else:

c:\python36\lib\site-packages\asammdf\mdf_v4.py in _read(self)
    487                         else:
    488                             comment = channel_group.comment.replace(' xmlns="http://www.asam.net/mdf/v4"', '')
--> 489                             comment_xml = ET.fromstring(comment)
    490                             can_msg_type = comment_xml.find('.//TX').text
    491                             if can_msg_type is not None:

c:\python36\lib\xml\etree\ElementTree.py in XML(text, parser)
   1313         parser = XMLParser(target=TreeBuilder())
   1314     parser.feed(text)
-> 1315     return parser.close()
   1316
   1317

ParseError: no element found: line 1, column 0
```
  
# Description
I'm unable to read a .mf4 file that is has been exported using the Kvaser toolchain. The it's a message based MDF file, works just find in CANalyzer as well as Vector MDF Validator. 

I've tried to debug the error, and it seems that while parsing the data groups, the following line of code returns and emptry string rather than an xml string:

```
comment = channel_group.comment.replace(' xmlns="http://www.asam.net/mdf/v4"', '')
```
Any idea what might be going on? Here's what the data group in question looks like:

![image](https://user-images.githubusercontent.com/7279509/41173735-d780c21a-6b0c-11e8-8447-0db61e8ebc86.png)

**Comment by dmbelo** [comment]
Thanks Daniel - that seems to have worked. I now get a warning message that seems appropriate:

`Unable to get CAN message infomration since channel group @0x61c8 has no metadata`

BTW - there's a typo in there: should be "information ".

**Comment by dmbelo** [comment]
As a separate question, and excuse my ignorance since I'm fairly new at dealing with CAN: Using asammdf is there a way to load a DBC file in order to retrieve a message by name? Seems like it assumes that DBC file is somehow part of the mf4 file?

**Comment by danielhrisca** [comment]
Thank you for the heads-up.

Could you also show the MDFValidator screenshot of the channel group's SourceInformation?

Even better, is it possible to send the file via e-mailed? There are thing to learn from it.

**Comment by danielhrisca** [comment]
The DBC should be references as an attachment, embedded or external. I see that your file does not have one (first attachment link in the header block is null). If it were available as attachment, asammdf would be able to read the database file using canmatrix and make the signals available to the _get_ method

I'm not sure how Kvaser handles this.

**Comment by danielhrisca** [comment]
@dmbelo have you tried the latest development code? ([_get_can_signal_](https://asammdf.readthedocs.io/en/development/api.html#mdf4) to be more precise)

**Comment by danielhrisca** [comment]
Please re-open if needed
