### ISSUE TITLE
Import fails with Python 3.10

### ISSUE THREAD

**Issue by morbult** [danielhrisca/asammdf#730]
I use conda on Windows 10 to manage my Python environments and I am not able to install asammdf with Python 3.10.

To reproduce, create a fresh environment like this

```
conda activate
conda create -n py310 -c conda-forge python=3.10 asammdf
```

On my computer, that installs the following packages

```
The following NEW packages will be INSTALLED:

  asammdf            conda-forge/noarch::asammdf-7.0.3-pyhe74cb21_0
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  brotli             conda-forge/win-64::brotli-1.0.9-h8ffe710_7
  brotli-bin         conda-forge/win-64::brotli-bin-1.0.9-h8ffe710_7
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.6.15-h5b45459_0
  canmatrix          conda-forge/noarch::canmatrix-0.8-py_0
  certifi            conda-forge/win-64::certifi-2022.6.15-py310h5588dad_0
  chardet            conda-forge/win-64::chardet-5.0.0-py310h5588dad_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  fonttools          conda-forge/win-64::fonttools-4.33.3-py310he2412df_0
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_1
  future             conda-forge/win-64::future-0.18.2-py310h5588dad_5
  intel-openmp       conda-forge/win-64::intel-openmp-2022.1.0-h57928b3_3787
  isa-l              conda-forge/win-64::isa-l-2.30.0-h8ffe710_4
  jpeg               conda-forge/win-64::jpeg-9e-h8ffe710_2
  kiwisolver         conda-forge/win-64::kiwisolver-1.4.3-py310h476a331_0
  lcms2              conda-forge/win-64::lcms2-2.12-h2a16943_0
  lerc               conda-forge/win-64::lerc-3.0-h0e60522_0
  libblas            conda-forge/win-64::libblas-3.9.0-15_win64_mkl
  libbrotlicommon    conda-forge/win-64::libbrotlicommon-1.0.9-h8ffe710_7
  libbrotlidec       conda-forge/win-64::libbrotlidec-1.0.9-h8ffe710_7
  libbrotlienc       conda-forge/win-64::libbrotlienc-1.0.9-h8ffe710_7
  libcblas           conda-forge/win-64::libcblas-3.9.0-15_win64_mkl
  libdeflate         conda-forge/win-64::libdeflate-1.12-h8ffe710_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libiconv           conda-forge/win-64::libiconv-1.16-he774522_0
  liblapack          conda-forge/win-64::liblapack-3.9.0-15_win64_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h1d00b33_2
  libtiff            conda-forge/win-64::libtiff-4.4.0-h2ed3b44_1
  libwebp            conda-forge/win-64::libwebp-1.2.2-h57928b3_0
  libwebp-base       conda-forge/win-64::libwebp-base-1.2.2-h8ffe710_1
  libxcb             conda-forge/win-64::libxcb-1.13-hcd874cb_1004
  libxml2            conda-forge/win-64::libxml2-2.9.14-hf5bbc77_2
  libxslt            conda-forge/win-64::libxslt-1.1.35-h34f844d_0
  libzlib            conda-forge/win-64::libzlib-1.2.12-h8ffe710_1
  lxml               conda-forge/win-64::lxml-4.9.1-py310he2412df_0
  lz4                conda-forge/win-64::lz4-4.0.0-py310h7b86b54_2
  lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.5.2-py310h79a7439_0
  mkl                conda-forge/win-64::mkl-2022.1.0-h6a75c08_874
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  natsort            conda-forge/noarch::natsort-8.1.0-pyhd8ed1ab_0
  numexpr            conda-forge/win-64::numexpr-2.8.0-mkl_py310h13231c8_2
  numpy              conda-forge/win-64::numpy-1.23.0-py310h8a5b91a_0
  openjpeg           conda-forge/win-64::openjpeg-2.4.0-hb211442_1
  openssl            conda-forge/win-64::openssl-3.0.4-h8ffe710_2
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pandas             conda-forge/win-64::pandas-1.4.3-py310hf5e1058_0
  pillow             conda-forge/win-64::pillow-9.1.1-py310h767b3fd_1
  pip                conda-forge/noarch::pip-22.1.2-pyhd8ed1ab_0
  pthread-stubs      conda-forge/win-64::pthread-stubs-0.4-hcd874cb_1001
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.10.5-hcf16a7b_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-isal        conda-forge/win-64::python-isal-0.11.1-py310he2412df_1
  python_abi         conda-forge/win-64::python_abi-3.10-2_cp310
  pytz               conda-forge/noarch::pytz-2022.1-pyhd8ed1ab_0
  pyyaml             conda-forge/win-64::pyyaml-6.0-py310he2412df_4
  setuptools         conda-forge/win-64::setuptools-63.1.0-py310h5588dad_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sqlite             conda-forge/win-64::sqlite-3.39.0-h8ffe710_0
  tbb                conda-forge/win-64::tbb-2021.5.0-h2d74725_1
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.3.0-pyha770c72_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  unicodedata2       conda-forge/win-64::unicodedata2-14.0.0-py310he2412df_1
  vc                 conda-forge/win-64::vc-14.2-hb210afc_6
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_6
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xlrd               conda-forge/noarch::xlrd-2.0.1-pyhd8ed1ab_3
  xlsxwriter         conda-forge/noarch::xlsxwriter-3.0.3-pyhd8ed1ab_0
  xlwt               conda-forge/noarch::xlwt-1.3.0-py_1
  xorg-libxau        conda-forge/win-64::xorg-libxau-1.0.9-hcd874cb_0
  xorg-libxdmcp      conda-forge/win-64::xorg-libxdmcp-1.1.3-hcd874cb_0
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1
  yaml               conda-forge/win-64::yaml-0.2.5-h8ffe710_2
  zlib               conda-forge/win-64::zlib-1.2.12-h8ffe710_1
  zstd               conda-forge/win-64::zstd-1.5.2-h6255e5f_2
```

I activate the fresh environment and start the Python interpreter

```
conda activate py310
python
```

Importing asammdf gives this error

```python
>>> import asammdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Anaconda3\envs\py310\lib\site-packages\asammdf\__init__.py", line 17, in <module>
    from .mdf import MDF, SUPPORTED_VERSIONS
  File "C:\Users\user\Anaconda3\envs\py310\lib\site-packages\asammdf\mdf.py", line 42, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Users\user\Anaconda3\envs\py310\lib\site-packages\asammdf\blocks\mdf_v2.py", line 9, in <module>
    from .mdf_v3 import MDF3
  File "C:\Users\user\Anaconda3\envs\py310\lib\site-packages\asammdf\blocks\mdf_v3.py", line 49, in <module>
    from .cutils import get_channel_raw_bytes
ModuleNotFoundError: No module named 'asammdf.blocks.cutils'
```

**Comment by morbult** [comment]
I realised there is a problem specifically with version 7.0.3 of asammdf. The import works if you use a later version

```
conda create -n py310 -c conda-forge python=3.10 "asammdf>7.0.3"
```

Then I get _conda-forge/win-64::asammdf-**7.0.4**-py310he2412df_0_ instead and the issue with `asammdf.blocks.cutils` seems to be solved. The question is why conda selects asammdf 7.0.3 when 7.0.4 exists...

Since 7.0.4 is currently the latest (and the only working) conda package for Python 3.10, it's worth mentioning that it doesn't work with numpy 1.21, it fails with `ImportError: numpy.core.multiarray failed to import`, even though numpy 1.21 satisfies the requirements. numpy 1.22 and 1.23 seems to work fine.

**Comment by angellopinedo** [comment]
I am using python 3.9.12 and asammdf version 7.0.4 and I'm still getting the original `ModuleNotFoundError: No module named 'asammdf.blocks.cutils'` message. I have the same issue with asammdf version 7.1.0. Any idea what is causing this issue?
`# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
aiohttp                   3.8.1            py39h2bbff1b_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.05                  py39_0  
anaconda-client           1.9.0            py39haa95532_0  
anaconda-navigator        2.1.4            py39haa95532_0  
anaconda-project          0.10.2             pyhd3eb1b0_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
asammdf                   7.0.4            py37hcc03f2d_0    <unknown>
astroid                   2.6.6            py39haa95532_0  
astropy                   5.0.4            py39h080aedc_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0             pyhd3eb1b0_0  
automat                   20.2.0                     py_0  
autopep8                  1.6.0              pyhd3eb1b0_0  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0            py39h196d8e1_0  
beautifulsoup4            4.11.1           py39haa95532_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
bitarray                  2.4.1            py39h2bbff1b_0  
bkcharts                  0.2              py39haa95532_0  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.0               h19a0ad4_0  
bokeh                     2.4.2            py39haa95532_0  
boto3                     1.21.32            pyhd3eb1b0_0  
botocore                  1.24.32            pyhd3eb1b0_0  
bottleneck                1.3.4            py39h080aedc_0  
brotli                    1.0.9                ha925a31_2  
brotlipy                  0.7.0           py39h2bbff1b_1003  
bzip2                     1.0.8                he774522_0  
ca-certificates           2022.3.29            haa95532_1  
cachetools                4.2.2              pyhd3eb1b0_0  
canmatrix                 0.8                        py_0    <unknown>
certifi                   2021.10.8        py39haa95532_2  
cffi                      1.15.0           py39h2bbff1b_1  
cfitsio                   3.470                he774522_6  
chardet                   4.0.0           py39haa95532_1003  
charls                    2.2.0                h6c2663c_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py39haa95532_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
clyent                    1.2.2            py39haa95532_1  
colorama                  0.4.4              pyhd3eb1b0_0  
colorcet                  2.0.6              pyhd3eb1b0_0  
comtypes                  1.1.10          py39haa95532_1002  
conda                     4.12.0           py39haa95532_0  
conda-build               3.21.8           py39haa95532_2  
conda-content-trust       0.1.1              pyhd3eb1b0_0  
conda-env                 2.6.0                haa95532_1  
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    1.8.1            py39h8cc25b3_0  
conda-repo-cli            1.0.4              pyhd3eb1b0_0  
conda-token               0.3.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
console_shortcut          0.1.1                         4  
constantly                15.1.0             pyh2b92418_0  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              3.4.8            py39h71e12ea_0  
cssselect                 1.1.0              pyhd3eb1b0_0  
curl                      7.82.0               h2bbff1b_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.29.28          py39hd77b12b_0  
cytoolz                   0.11.0           py39h2bbff1b_0  
daal4py                   2021.5.0         py39h8cb3d55_0  
dal                       2021.5.0           haa95532_796  
dask                      2022.2.1           pyhd3eb1b0_0  
dask-core                 2022.2.1           pyhd3eb1b0_0  
dataclasses               0.8                pyh6d0b6a4_7  
datashader                0.13.0             pyhd3eb1b0_1  
datashape                 0.5.4            py39haa95532_1  
debugpy                   1.5.1            py39hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
distributed               2022.2.1           pyhd3eb1b0_0  
docutils                  0.17.1           py39haa95532_1  
entrypoints               0.4              py39haa95532_0  
et_xmlfile                1.1.0            py39haa95532_0  
executing                 0.8.3              pyhd3eb1b0_0  
filelock                  3.6.0              pyhd3eb1b0_0  
flake8                    3.9.2              pyhd3eb1b0_0  
flask                     1.1.2              pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.10.4               hd328e21_0  
frozenlist                1.2.0            py39h2bbff1b_0  
fsspec                    2022.2.0           pyhd3eb1b0_0  
future                    0.18.2           py39haa95532_1  
gensim                    4.1.2            py39hd77b12b_0  
giflib                    5.2.1                h62dcd97_0  
glob2                     0.7                pyhd3eb1b0_0  
google-api-core           1.25.1             pyhd3eb1b0_0  
google-auth               1.33.0             pyhd3eb1b0_0  
google-cloud-core         1.7.1              pyhd3eb1b0_0  
google-cloud-storage      1.31.0                     py_0  
google-crc32c             1.1.2            py39h2bbff1b_0  
google-resumable-media    1.3.1              pyhd3eb1b0_1  
googleapis-common-protos  1.53.0           py39h2eaa2aa_0  
greenlet                  1.1.1            py39hd77b12b_0  
grpcio                    1.42.0           py39hc60d5dd_0  
h5py                      3.6.0            py39h3de5c98_0  
hdf5                      1.10.6               h7ebc959_0  
heapdict                  1.0.1              pyhd3eb1b0_0  
holoviews                 1.14.8             pyhd3eb1b0_0  
hvplot                    0.7.3              pyhd3eb1b0_1  
hyperlink                 21.0.0             pyhd3eb1b0_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha925a31_3  
idna                      3.3                pyhd3eb1b0_0  
imagecodecs               2021.8.26        py39ha1f97ea_0  
imageio                   2.9.0              pyhd3eb1b0_0  
imagesize                 1.3.0              pyhd3eb1b0_0  
importlib-metadata        4.11.3           py39haa95532_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
incremental               21.3.0             pyhd3eb1b0_0  
inflection                0.5.1            py39haa95532_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intake                    0.6.5              pyhd3eb1b0_0  
intel-openmp              2021.4.0          haa95532_3556  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.9.1            py39haa95532_0  
ipython                   8.2.0            py39haa95532_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
isort                     5.9.3              pyhd3eb1b0_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.0.4              pyhd3eb1b0_1  
itsdangerous              2.0.1              pyhd3eb1b0_0  
jdcal                     1.4.1              pyhd3eb1b0_0  
jedi                      0.18.1           py39haa95532_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jmespath                  0.10.0             pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
jpeg                      9e                   h2bbff1b_0  
jq                        1.6                  haa95532_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.4.0            py39haa95532_0  
jupyter                   1.0.0            py39haa95532_7  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.9.2            py39haa95532_0  
jupyter_server            1.13.5             pyhd3eb1b0_0  
jupyterlab                3.3.2              pyhd3eb1b0_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.10.3             pyhd3eb1b0_1  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keyring                   23.4.0           py39haa95532_0  
kiwisolver                1.3.2            py39hd77b12b_0  
lazy-object-proxy         1.6.0            py39h2bbff1b_0  
lcms2                     2.12                 h83e58a3_0  
lerc                      3.0                  hd77b12b_0  
libaec                    1.0.4                h33f27b4_1  
libarchive                3.4.2                h5e25573_0  
libcrc32c                 1.1.1                ha925a31_2  
libcurl                   7.82.0               h86230a5_0  
libdeflate                1.8                  h2bbff1b_5  
libiconv                  1.17                 h8ffe710_0    <unknown>
liblief                   0.11.5               hd77b12b_1  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.19.1               h23ce68f_0  
libspatialindex           1.9.3                h6c2663c_0  
libssh2                   1.10.0               hcd4344a_0  
libtiff                   4.2.0                hd0e1b90_0  
libwebp                   1.2.2                h2bbff1b_0  
libxml2                   2.9.12               h0ad7f3c_0  
libxslt                   1.1.34               he774522_0  
libzopfli                 1.0.3                ha925a31_0  
llvmlite                  0.38.0           py39h23ce68f_0  
locket                    0.2.1            py39haa95532_2  
lxml                      4.8.0            py39h1985fb9_0  
lz4-c                     1.9.3                h2bbff1b_1  
lzo                       2.10                 he774522_2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markdown                  3.3.4            py39haa95532_0  
markupsafe                2.0.1            py39h2bbff1b_0  
matplotlib                3.5.2           py37h604114d_200    <unknown>
matplotlib-base           3.5.1            py39hd77b12b_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mccabe                    0.6.1            py39haa95532_1  
menuinst                  1.4.18           py39h59b6b97_0  
mistune                   0.8.4           py39h2bbff1b_1000  
mkl                       2021.4.0           haa95532_640  
mkl-service               2.4.0            py39h2bbff1b_0  
mkl_fft                   1.3.1            py39h277e83a_0  
mkl_random                1.2.2            py39hf11a4ad_0  
mock                      4.0.3              pyhd3eb1b0_0  
mpmath                    1.2.1            py39haa95532_0  
msgpack-python            1.0.2            py39h59b6b97_1  
msys2-conda-epoch         20160418                      1  
multidict                 5.1.0            py39h2bbff1b_2  
multipledispatch          0.6.0            py39haa95532_0  
munkres                   1.1.4                      py_0  
mypy_extensions           0.4.3            py39haa95532_1  
navigator-updater         0.2.1                    py39_1  
nbclassic                 0.3.5              pyhd3eb1b0_0  
nbclient                  0.5.13           py39haa95532_0  
nbconvert                 6.4.4            py39haa95532_0  
nbformat                  5.3.0            py39haa95532_0  
nest-asyncio              1.5.5            py39haa95532_0  
networkx                  2.7.1              pyhd3eb1b0_0  
nltk                      3.7                pyhd3eb1b0_0  
nose                      1.3.7           pyhd3eb1b0_1008  
notebook                  6.4.8            py39haa95532_0  
numba                     0.55.1           py39hf11a4ad_0  
numexpr                   2.8.1            py39hb80d3ca_0  
numpy                     1.22.3           py39h503c56f_2    <unknown>
numpy-base                1.21.5           py39hca35cd5_1  
numpydoc                  1.2                pyhd3eb1b0_0  
olefile                   0.46               pyhd3eb1b0_0  
openjpeg                  2.4.0                h4fc8c34_0  
openpyxl                  3.0.9              pyhd3eb1b0_0  
openssl                   1.1.1n               h2bbff1b_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.2            py39hd77b12b_0    <unknown>
pandocfilters             1.5.0              pyhd3eb1b0_0  
panel                     0.13.0           py39haa95532_0  
param                     1.12.0             pyhd3eb1b0_0  

Note: you may need to restart the kernel to use updated packages.paramiko                  2.8.1              pyhd3eb1b0_0  
parsel                    1.6.0            py39haa95532_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_1  
pathspec                  0.7.0                      py_0  
patsy                     0.5.2            py39haa95532_1  
pep8                      1.7.1            py39haa95532_0  

pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39hdc2b20a_0  
pip                       21.2.4           py39haa95532_0  
pkginfo                   1.8.2              pyhd3eb1b0_0  
plotly                    5.9.0                      py_0    <unknown>
pluggy                    1.0.0            py39haa95532_1  
powershell_shortcut       0.0.1                         3  
poyo                      0.5.0              pyhd3eb1b0_0  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prompt_toolkit            3.0.20               hd3eb1b0_0  
protego                   0.1.16                     py_0  
protobuf                  3.19.1           py39hd77b12b_0  
psutil                    5.8.0            py39h2bbff1b_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py                        1.11.0             pyhd3eb1b0_0  
py-lief                   0.11.5           py39hd77b12b_1  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycodestyle               2.7.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py39h2bbff1b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.4.6            py39haa95532_0  
pycurl                    7.44.1           py39hcd4344a_1  
pydispatcher              2.0.5            py39haa95532_2  
pydocstyle                6.1.1              pyhd3eb1b0_0  
pyerfa                    2.0.0            py39h2bbff1b_0  
pyflakes                  2.3.1              pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyhamcrest                2.0.2              pyhd3eb1b0_2  
pyjwt                     2.1.0            py39haa95532_0  
pylint                    2.9.6            py39haa95532_1  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.4.0            py39hbd8134f_1  
pyodbc                    4.0.32           py39hd77b12b_1  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py39hd77b12b_6  
pyreadline                2.1              py39haa95532_1  
pyrsistent                0.18.0           py39h196d8e1_0  
pysocks                   1.7.1            py39haa95532_0  
pytables                  3.6.1            py39h56d22b6_1  
pytest                    7.1.1            py39haa95532_0  
python                    3.9.12               h6244533_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.15.1             pyhd3eb1b0_0  
python-kaleido            0.2.1              pyhd8ed1ab_0    <unknown>
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lsp-black          1.0.0              pyhd3eb1b0_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.2.4              pyhd3eb1b0_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-snappy             0.6.0            py39hd77b12b_3  
pytz                      2021.3             pyhd3eb1b0_0  
pyviz_comms               2.0.2              pyhd3eb1b0_0  
pywavelets                1.3.0            py39h2bbff1b_0  
pywin32                   302              py39h2bbff1b_2  
pywin32-ctypes            0.2.0           py39haa95532_1000  
pywinpty                  2.0.2            py39h5da7b33_0  
pyyaml                    6.0              py39h2bbff1b_1  
pyzmq                     22.3.0           py39hd77b12b_2  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt                        5.9.7            vc14h73c81de_0  
qtawesome                 1.0.3              pyhd3eb1b0_0  
qtconsole                 5.1.1              pyhd8ed1ab_0    <unknown>
qtpy                      2.0.1              pyhd3eb1b0_0  
queuelib                  1.5.0            py39haa95532_0  
regex                     2022.3.15        py39h2bbff1b_0  
requests                  2.27.1             pyhd3eb1b0_0  
requests-file             1.5.1              pyhd3eb1b0_0  
rope                      0.22.0             pyhd3eb1b0_0  
rsa                       4.7.2              pyhd3eb1b0_1  
rtree                     0.9.7            py39h2eaa2aa_1  
ruamel_yaml               0.15.100         py39h2bbff1b_0  
s3transfer                0.5.0              pyhd3eb1b0_0  
scikit-image              0.19.2           py39hf11a4ad_0  
scikit-learn              1.0.2            py39hf11a4ad_1  
scikit-learn-intelex      2021.5.0         py39haa95532_0  
scipy                     1.7.3            py39h2f0f56f_0    <unknown>
scrapy                    2.6.1            py39haa95532_0  
seaborn                   0.11.2             pyhd3eb1b0_0  
send2trash                1.8.0              pyhd3eb1b0_1  
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                61.2.0           py39haa95532_0  
sip                       4.19.13          py39hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
smart_open                5.1.0              pyhd3eb1b0_0  
snappy                    1.1.9                h6c2663c_0  
sniffio                   1.2.0            py39haa95532_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcollections         2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.3.1              pyhd3eb1b0_0  
sphinx                    4.4.0              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.1.5            py39haa95532_1  
spyder-kernels            2.1.3            py39haa95532_0  
sqlalchemy                1.4.32           py39h2bbff1b_0  
sqlite                    3.38.2               h2bbff1b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.13.2           py39h2bbff1b_0  
sympy                     1.10.1           py39haa95532_0  
tabulate                  0.8.9            py39haa95532_0  
tbb                       2021.5.0             h59b6b97_0  
tbb4py                    2021.5.0         py39h59b6b97_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.0.1            py39haa95532_0  
terminado                 0.13.1           py39haa95532_0  
testpath                  0.5.0              pyhd3eb1b0_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2021.7.2           pyhd3eb1b0_2  
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.11               h2bbff1b_0  
tldextract                3.2.0              pyhd3eb1b0_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     1.2.2              pyhd3eb1b0_0  
toolz                     0.11.2             pyhd3eb1b0_0  
tornado                   6.1              py39h2bbff1b_0  
tqdm                      4.64.0           py39haa95532_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
twisted                   22.2.0           py39h2bbff1b_0  
twisted-iocpsupport       1.0.2            py39h2bbff1b_0  
typed-ast                 1.4.3            py39h2bbff1b_1  
typing-extensions         4.1.1                hd3eb1b0_0  
typing_extensions         4.1.1              pyh06a4308_0  
tzdata                    2022a                hda174b7_0  
ujson                     5.1.0            py39hd77b12b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.9           py39haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
w3lib                     1.21.0             pyhd3eb1b0_0  
watchdog                  2.1.6            py39haa95532_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39haa95532_1  
websocket-client          0.58.0           py39haa95532_4  
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py39haa95532_0  
win_inet_pton             1.1.0            py39haa95532_0  
win_unicode_console       0.5              py39haa95532_0  
wincertstore              0.2              py39haa95532_2  
winpty                    0.4.3                         4  
wrapt                     1.12.1           py39h196d8e1_1  
xarray                    0.20.1             pyhd3eb1b0_1  
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                3.0.3              pyhd3eb1b0_0  
xlwings                   0.24.9           py39haa95532_0  
xz                        5.2.5                h62dcd97_0  
yaml                      0.2.5                he774522_0  
yapf                      0.31.0             pyhd3eb1b0_0  
yarl                      1.6.3            py39h2bbff1b_0  
zfp                       0.5.5                hd77b12b_6  
zict                      2.0.0              pyhd3eb1b0_0  
zipp                      3.7.0              pyhd3eb1b0_0  
zlib                      1.2.12               h8cc25b3_2  
zope                      1.0              py39haa95532_1  
zope.interface            5.4.0            py39h2bbff1b_0  
zstd                      1.4.9                h19a0ad4_0  `

**Comment by danielhrisca** [comment]
@morbult I've re-rendered the recipe and now the compiled wheels for python 3.10 are also available
