### ISSUE TITLE
Memory leak occurs on loading external attachments

### ISSUE THREAD

**Issue by akloeker** [danielhrisca/asammdf#731]
# Python version
```
('python=3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC '
 '10.3.0]')
'os=Linux-5.13.0-39-generic-x86_64-with-glibc2.31'
'numpy=1.23.0'
'asammdf=7.1.0'
```

# Code 

  ## MDF version
  4.1

  ## Code snippet
  ```python
  signals = []
  for k in range(x):
      with MDF(mdf_file) as mdf:
          signals[k] = {}
          signals[k]['data'] = np.array(mdf.get_group(v_idx).astype(float).tolist())
          signals[k]['time'] = mdf.get_master(v_idx)
  ```
  
# Description

When loading an MDF file containing large external attachements, it seems that there occurs a memory leak. This error becomes noticable when loading multiple MDF files in a loop until the script crashes due to a memory overflow. A `tracemalloc` snapshot indicates that the `data` variable in [mdf_v4.py#L6328](https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/mdf_v4.py#L6328) occupies more memory in every iteration. At first glance the error probably seems to be, that the `open()` statement in [mdf_v4.py#L6328](https://github.com/danielhrisca/asammdf/blob/master/asammdf/blocks/mdf_v4.py#L6328) is neither called within a `with` context nor closed at any point, so that the loaded data never gets released.

This error can als be observed with Python version 3.9 and asammmdf version 7.0.7.

**Comment by danielhrisca** [comment]
@akloeker please try the development branch
