### ISSUE TITLE
Export all data groups in chronological order?

### ISSUE THREAD

**Issue by hendrikcodes** [danielhrisca/asammdf#747]
## Code snippet

from asammdf import MDF, Signal
mdf_obj = MDF('myMDFFile.mf4')
pd = mdf_obj.get_group([group[0] for group in mdf_obj.whereis("MySignalName")][0], time_as_date= True)  
print(pd)
  
## Description

Hi,

I would like to convert all data groups into one dataframe in chronological order.
I'm currently only able to search for a signal and get the matching data group as an output.
For my purpose it would be great to have the data groups listed in chronological order in a dataframe.

Thanks for your help!

**Comment by danielhrisca** [comment]
See `mdf.to_dataframe`
