### ISSUE TITLE
CAN signals loaded as strings

### ISSUE THREAD

**Issue by axtschmied** [danielhrisca/asammdf#748]
# Python version
```
'python=3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]'
'os=Windows-10-10.0.19042-SP0'
'numpy=1.23.1'
'asammdf=7.1.1'
```

# MDF version
 4.10

# Description
The values of CAN signals are loaded as strings instead of numeric values. Signals measured via XCP do not seem to be affected, even if they are measured over CAN as well. This behavior is okay for enumeration-like signals, but not just those, but all CAN signals become strings. This results in scripts failing, and the GUI displaying values incorrectly, see image.

![asammdf](https://user-images.githubusercontent.com/28358038/183580212-879d1a59-1145-4d9b-a79e-bcfabc134482.PNG)
(blue: XCP signal, orange: CAN signal - should be the same as the XCP signal, green: another CAN signal)

If I add the `ignore_value2text_conversions=True` argument to e.g. the `select` function, then the raw values are loaded (this time not as strings), even if `raw=False`.

**Comment by danielhrisca** [comment]
@axtschmied I can't understand what might be wrong here. Maybe you can send a file

**Comment by eblis** [comment]
Are you converting to dataframe, or not ?
Could it be related to https://github.com/danielhrisca/asammdf/issues/770 ?

**Comment by danielhrisca** [comment]
@axtschmied please try release 7.3.16

**Comment by axtschmied** [comment]
Hello, thanks, it is working.
