### ISSUE TITLE
Incorrectly read strings

### ISSUE THREAD

**Issue by mw25** [danielhrisca/asammdf#752]
# Python version
('python=3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]')
'os=Windows-10-10.0.19042-SP0'
'numpy=1.23.2'
'asammdf=7.1.2.dev4'

# Code 

  ## MDF version
  4.10

  ## Code snippet
  `df = self.mdf.to_dataframe(channel_list, time_from_zero=False, empty_channels="zeros", use_interpolation=False)`
   
## Traceback
  None

  
# Description

In some of my files the strings are not displayed correctly. 
More precisely, more characters beyond the zero terminator are displayed.

For both the bad and the good files the MDF Validtor shows a warning (and after scrambling it added a few more). This doesn't seem to have any effect:
`Property 14: Sync type NONE must only be used with type VALUE, VLSD or MLSD!`

Here is the comparison between a good and a bad file:

| | bad strings | good strings |
|---|---|---|
|asammdf GUI| ![image](https://user-images.githubusercontent.com/67997227/185340775-9d8612a1-bb24-4384-8825-120cf97fcce5.png) | ![image](https://user-images.githubusercontent.com/67997227/185340821-627b7f1a-f09c-468f-89bb-52c84822db39.png) |
|debugger| ![image](https://user-images.githubusercontent.com/67997227/185341412-02bfc6ea-da59-43f7-ad90-2947e8505ae8.png)| ![image](https://user-images.githubusercontent.com/67997227/185342071-52c37604-e008-43a0-a633-75d578b94d83.png) |
| |![image](https://user-images.githubusercontent.com/67997227/185341720-6b9aa999-937a-44c6-9938-b281e9c0c6f8.png)||
|raw data|![image](https://user-images.githubusercontent.com/67997227/185348013-d83cf2a4-74e1-4833-be6b-6407b611707f.png)|![image](https://user-images.githubusercontent.com/67997227/185347717-0af46aaa-df20-4bf9-a7c3-4eb3b0cd0696.png)|

 
In the correct case the bytes between the strings are ignored (00 00 07 00 00) in the other case not (00 00 00 30 00 6C 02 33 0D 00 00).

The only difference I can see is the numpy data type of the array: once bytes_ (|S7) and once object_.

Does that mean anything to you? Could this have something to do with asammdf or rather a faulty export?

Thank you very much.

(You should have received the files by mail.)

**Comment by danielhrisca** [comment]
@mw25 please try the development branch code (version `7.2.0.dev2`)

**Comment by mw25** [comment]
It works perfectly.
Thanks for the quick fix.
