### ISSUE TITLE
ModuleNotFoundError: No module named 'asammdf.blocks.cutils'

### ISSUE THREAD

**Issue by 113haoyuansu** [danielhrisca/asammdf#757]
# Python version
I use Python 3.10. A similar problem occurred using ASAMMDF 7.1.0. Due to this problem, I changed to 3.9 and 3.8 but the problem still exists.
 ## MDF version
The programe cannot run properly.

  ## Code snippet
  When running asammdfgui.Py with PyCharm Community Edition 2022.2.1.
  ## Traceback
Traceback (most recent call last):
  File "D:\Work\Python\asammdf-7.1.0\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b4636ee9d6ad>", line 1, in <cell line: 1>
    runfile('D:/Work/Python/asammdf-7.1.0/asammdf/gui/asammdfgui.py', wdir='D:/Work/Python/asammdf-7.1.0/asammdf/gui')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Work/Python/asammdf-7.1.0/asammdf/gui/asammdfgui.py", line 13, in <module>
    from asammdf.gui.utils import excepthook
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Work\Python\asammdf-7.1.0\asammdf\__init__.py", line 17, in <module>
    from .mdf import MDF, SUPPORTED_VERSIONS
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Work\Python\asammdf-7.1.0\asammdf\mdf.py", line 42, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Work\Python\asammdf-7.1.0\asammdf\blocks\mdf_v2.py", line 9, in <module>
    from .mdf_v3 import MDF3
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Work\Python\asammdf-7.1.0\asammdf\blocks\mdf_v3.py", line 49, in <module>
    from .cutils import get_channel_raw_bytes
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'asammdf.blocks.cutils'  
# Description
 When running asammdfgui.Py with PyCharm Community Edition 2022.2.1.
I checked the problem and it should be the error message Pycharm got when calling cutils.c in the Blocks folder. Is there a problem with Pycharm software?
I have one more small suggestion, using version 7.1.0. Could you add index button search for similar keywords when loading signal pages? Because sometimes there are more than 1000 signals recorded in the data, it is difficult to find.
![image](https://user-images.githubusercontent.com/110374867/186626144-e161723d-43c7-4c26-9c1a-5b4da699b299.png)

**Comment by danielhrisca** [comment]
@113haoyuansu how did you install `asammdf` ?

for the search you should use the search dialog (Ctrl+F)

**Comment by 113haoyuansu** [comment]
@danielhrisca Thanks!
I think I figured out what the problem is. When I download the code from Github to my computer and run it, "No Module named 'asammdf.block.cutils'" appears. It is my own mistake, I use pip install asammdf after everything is normal.
The search dialog cannot search for keywords, it must be the name of the entire signal. 
![image](https://user-images.githubusercontent.com/110374867/186794530-b25d2148-8f99-4ddc-81da-5f58d2ff7cb1.png)
![image](https://user-images.githubusercontent.com/110374867/186795085-729b6426-3193-4fb3-95c5-14f55eea4873.png)

**Comment by danielhrisca** [comment]
`ESC_*` as marked in the search dialog you can use wildcards

**Comment by 113haoyuansu** [comment]
Thanks  a lot! @danielhrisca

**Comment by saideepthik** [comment]
Hello Everyone!
i'm having similar issue, but could not resolve it in conda :( 
(base) C:\Users\YYYYY\Documents\workspace\asammdf\examples>conda install -c conda-forge asammdf
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\YYYYY\Anaconda3

  added / updated specs:
    - asammdf


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asammdf-7.0.3              |     pyhe74cb21_0         499 KB  conda-forge
    canmatrix-0.8              |             py_0         174 KB  conda-forge
    natsort-8.2.0              |     pyhd8ed1ab_0          36 KB  conda-forge
    openssl-1.1.1s             |       hcfcfb64_0         5.9 MB  conda-forge
    ucrt-10.0.22621.0          |       h57928b3_0         1.2 MB  conda-forge
    xlwt-1.3.0                 |             py_1          83 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.9 MB

The following NEW packages will be INSTALLED:

  asammdf            conda-forge/noarch::asammdf-7.0.3-pyhe74cb21_0 None
  canmatrix          conda-forge/noarch::canmatrix-0.8-py_0 None
  isa-l              conda-forge/win-64::isa-l-2.30.0-h8ffe710_4 None
  natsort            conda-forge/noarch::natsort-8.2.0-pyhd8ed1ab_0 None
  python-isal        conda-forge/win-64::python-isal-1.1.0-py39ha55989b_1 None
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39 None
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 None
  xlwt               conda-forge/noarch::xlwt-1.3.0-py_1 None

The following packages will be UPDATED:

  conda              pkgs/main::conda-22.9.0-py39haa95532_0 --> conda-forge::conda-22.9.0-py39hcbf5309_2 None
  vs2015_runtime     pkgs/main::vs2015_runtime-14.27.29016~ --> conda-forge::vs2015_runtime-14.32.31332-h1d6e394_9 None

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2022.10.11~ --> conda-forge::ca-certificates-2022.9.24-h5b45459_0 None
  certifi            pkgs/main/win-64::certifi-2022.9.24-p~ --> conda-forge/noarch::certifi-2022.9.24-pyhd8ed1ab_0 None
  openssl              pkgs/main::openssl-1.1.1s-h2bbff1b_0 --> conda-forge::openssl-1.1.1s-hcfcfb64_0 None


Proceed ([y]/n)? y


Downloading and Extracting Packages
xlwt-1.3.0           | 83 KB     | ############################################################################ | 100%
natsort-8.2.0        | 36 KB     | ############################################################################ | 100%
openssl-1.1.1s       | 5.9 MB    | ############################################################################ | 100%
ucrt-10.0.22621.0    | 1.2 MB    | ############################################################################ | 100%
asammdf-7.0.3        | 499 KB    | ############################################################################ | 100%
canmatrix-0.8        | 174 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

(base) C:\Users\YYYYY\Documents\workspace\asammdf\examples>python mf4_demo.py
Traceback (most recent call last):
  File "C:\Users\YYYYY\Documents\workspace\asammdf\examples\mf4_demo.py", line 3, in <module>
    from asammdf import MDF, Signal
  File "C:\Users\YYYYY\Anaconda3\lib\site-packages\asammdf\__init__.py", line 17, in <module>
    from .mdf import MDF, SUPPORTED_VERSIONS
  File "C:\Users\YYYYY\Anaconda3\lib\site-packages\asammdf\mdf.py", line 42, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Users\YYYYY\Anaconda3\lib\site-packages\asammdf\blocks\mdf_v2.py", line 9, in <module>
    from .mdf_v3 import MDF3
  File "C:\Users\YYYYY\Anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 49, in <module>
    from .cutils import get_channel_raw_bytes
ModuleNotFoundError: No module named 'asammdf.blocks.cutils'

Some help much appreciated!

**Comment by danielhrisca** [comment]
Go to pypi, download the 7.0.3 wheel that fits your python version, extract the archive and manually copy the cutils.pyd to your conda asammdf/blocks folder

**Comment by danielhrisca** [comment]
what python version do you have?

**Comment by saideepthik** [comment]
Python 3.9.15

**Comment by danielhrisca** [comment]
you need to extract this wheel https://files.pythonhosted.org/packages/04/fe/89ec11f669a7d6e4d7e36ad83920e2309c1491738c40b858fb449a9a506e/asammdf-7.0.3-cp39-cp39-win_amd64.whl

! keep in mind that you need 64 bit Python

**Comment by saideepthik** [comment]
Wow! its working finally after consuming hell of time, it's better to post always when we get stuck somewhere!

@danielhrisca Thank you so much, and i would like to know what went wrong and why is this file missing from the library while installing through conda if you can elaborate for future knowledge!

FYI:
Python 3.9.15 (main, Nov 23 2022, 09:27:34) [MSC v.1916 64 bit (AMD64)] on win32
What i did to resolve it;
copied the pyd file as suggested into this folder and everything works!
C:\Users\YYYYY\Anaconda3\Lib\site-packages\asammdf\blocks

**Comment by danielhrisca** [comment]
I have no idea what happened, the conda package contains `cutil.pyd` 
![image](https://user-images.githubusercontent.com/20952040/203820332-3082a2b4-8f15-4120-9330-2f8900fdcda7.png)

**Comment by GodwinGeorge** [comment]
I have the same issue.
ModuleNotFoundError: No module named 'asammdf.blocks.cutils'.
I installed on asammdf on conda via jupyter notebook. Used !pip install asammdf. checked my python version -Python 3.9.16.  I'm able to see cutils in local directory under blocks. Also replaced the cutils file with asammdf 7.0.3 still have the issue!
