### ISSUE TITLE
insufficient number of digits under cut feature

### ISSUE THREAD

**Issue by LucaProv** [danielhrisca/asammdf#759]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._
Hallo,
I'm completely new on the platform and with few experience on asammdf. Hope to open issue correctly.
Im encountering an issue when I try to export data from a big file
 When I use “modify&Export” tab I’d like to use the CUT option (in my mind is used to select a specific timeframe). Unfortunately my data set reach a time of 7170198 seconds. But I can only digit 6 number into cut tab.
I've also try to export in .csv starting from graph but I got an error.
Any help or suggestion is appreciated
Thanks
![Screenshot (173)](https://user-images.githubusercontent.com/112390718/187184036-c06e39b9-6648-4a55-86e2-8356b4aee09d.png)

**Comment by danielhrisca** [comment]
@LucaProv please try the development branch code

> I've also try to export in .csv starting from graph but I got an error.

The right click menu functionality might not work correctly (it is the default implementation from pyqtgraph)

**Comment by LucaProv** [comment]
thanks @danielhrisca 
I was able to understand file to be modified but, after that, I don't know how to use it wit development code.
sorry for that
is there any other release after 7.0.2 that I could try?

**Comment by danielhrisca** [comment]
```
pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip
```

**Comment by LucaProv** [comment]
Thenks again @danielhrisca .
I'm stll have trouble (after installation of visual studio/C++ etc. process end with error before creating the build of asammdf.

 C:\Users\lab-enginetb\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Non Š possibile aprire il file inclusione: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for asammdf
Failed to build asammdf
ERROR: Could not build wheels for asammdf, which is required to install pyproject.toml-based projects

Surely I made something wrong but I cannot move forward.
Thanks a lot for patence and support

**Comment by danielhrisca** [comment]
did you install the build tools ? https://aka.ms/vs/17/release/vs_BuildTools.exe

![image](https://user-images.githubusercontent.com/20952040/187665503-b12c1f69-a223-42b9-b9c0-b84212a3dcaa.png)

**Comment by LucaProv** [comment]
Yes, I had.
Your file updated some component but error is the same ☹
When installed do I have to select any specific component or the standard installation is ok?

Da: Daniel Hrisca ***@***.***>
Inviato: mercoledì 31 agosto 2022 13:11
A: danielhrisca/asammdf ***@***.***>
Cc: Luca Provini ***@***.***>; Mention ***@***.***>
Oggetto: Re: [danielhrisca/asammdf] insufficient number of digits under cut feature (Issue #759)


CAUTION: This email originated from outside of the organization. Do not click links, open attachments, or reply unless you recognize the sender and know the content is safe. Contact HY Tech Assist<https://hyg.onelogin.com/login2> if you need assistance.

did you install the build tools ? https://aka.ms/vs/17/release/vs_BuildTools.exe

[image]<https://user-images.githubusercontent.com/20952040/187665503-b12c1f69-a223-42b9-b9c0-b84212a3dcaa.png>

**Comment by LucaProv** [comment]
@danielhrisca finally I was able to create e build :-)
last question(hopefully): after process said "Successfully installed asammdf-7.2.0.dev2", whichis next step?
I'll have to look for an executable with an interface or I have to use it in a different manner?
Thanks a lot

**Comment by danielhrisca** [comment]
``pip install asammdf[gui,decode,export]``

then you can execute the file found in you ``CPython installation folder\Scripts\asammdf.exe``

For example I use a WinPython distrubution located on the C drive so I need to run this file
``c:\WPy64-31050\python-3.10.5.amd64\Scripts\asammdf.exe``
