### ISSUE TITLE
Mismatch in Channel_Index infomation extracted by providing Channel name  with respect to other lib

### ISSUE THREAD

**Issue by karthi19** [danielhrisca/asammdf#77]
# Python version
('python=3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC '
 'v.1900 64 bit (AMD64)]')
'os=Windows-10-10.0.10240-SP0'
'numpy=1.14.1'
'asammdf=3.2.1

# Code 

  ## MDF version
*.MF4 file (Version 4.10 )

  ## Code snippet
  gr_ind = data.channels_db['channel_xxx']
  
# Description
While reading the group & index value of a particular channel 
Group values seems to be correct 
Index values seems to be different 
e.g: I should get 40 as the index but i am getting 41 
We use our internal tool for group & index extraction using  Vector Mdf4Lib 
If required i can share you the file which i used .
Thanks in advance !

**Comment by danielhrisca** [comment]
Also check if mdflib starts counting from index 1 instead of 0, and if the master channel is included in the indexing

**Comment by karthi19** [comment]
Hello Daniel Hrisca,

Thank for the quick reply !

As of now I have no idea about the structure composition I’ll come back to you once after exploring it.

If required I can send you the *.mf4 file which I used.

Thank you !

Best regards,

Lakshmanan Karthick

**Comment by danielhrisca** [comment]
Sure, you can send the file using the profile email signature

**Comment by danielhrisca** [comment]
Please re-open if needed
