### ISSUE TITLE
When entering the gps window for the second time, the map does not work

### ISSUE THREAD

**Issue by xukegithub** [danielhrisca/asammdf#773]
# Python version
('python=3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.23.3'
'asammdf=7.1.1'
# Code 

  ## MDF version
v4.11

  
# Description
When entering the gps window for the second time, the map does not work

Then before "self.map = L.map(self.mapWidget)",  
add this line "pyqtlet2.leaflet.core.Evented.mapWidget = None"
it's ok

**Comment by MatinF** [comment]
@xukegithub Is it correctly understood that you're able to resolve the plot issue by adding the extra line in the code? If so, that would be a really nice update to resolve this issue.

**Comment by xukegithub** [comment]
@MatinF  Yes, adding this line of code can solve it.
You can try

**Comment by danielhrisca** [comment]
> Then before "self.map = L.map(self.mapWidget)",
> add this line "pyqtlet2.leaflet.core.Evented.mapWidget = None"

It does not run on my side. I get an exception

```

File "D:\02__PythonWorkspace\asammdf\asammdf\gui\widgets\file.py", line 1481, in _create_window
    self.add_window((window_type, signals))
  File "D:\02__PythonWorkspace\asammdf\asammdf\gui\widgets\mdi_area.py", line 964, in add_window
    return self._add_gps_window(names)
  File "D:\02__PythonWorkspace\asammdf\asammdf\gui\widgets\mdi_area.py", line 1457, in _add_gps_window
    gps = GPS(latitude_channel, longitude_channel)
  File "D:\02__PythonWorkspace\asammdf\asammdf\gui\widgets\gps.py", line 65, in __init__
    self.map.setView([50.1364092, 8.5991296], zoom)
  File "D:\02__PythonWorkspace\__venvs\daxil\lib\site-packages\pyqtlet2\leaflet\map\map.py", line 104, in setView
    self.runJavaScript(js)
  File "D:\02__PythonWorkspace\__venvs\daxil\lib\site-packages\pyqtlet2\leaflet\core\evented.py", line 78, in runJavaScript
    self.mapWidget.page.runJavaScript(js)

```

**Comment by xukegithub** [comment]
my code
`       pyqtlet2.leaflet.core.Evented.mapWidget = None
        self.map = L.map(self.mapWidget)
        self.map.setView([self.latitude, self.longitude], zoom)
`
Exception is the first time you enter this interface or the second time it happens？

**Comment by danielhrisca** [comment]
@xukegithub @MatinF the development branch code works now with multiple GPS windows

**Comment by xukegithub** [comment]
@danielhrisca 

Sorry, I forgot to say that the environment is development branch

**Comment by MatinF** [comment]
Great, I think this works! (my maps are grey due to a separate dependency issue as discussed previously)

Will be great to have this included in the next release!

One minor observation: If creating multiple plots, the lower bar time sync seems to work, but the plot marker is not actually synced between the two plots. I think this is such a minor issue that I wouldn't bother too much with it. I'm probably one of the only people who is actively recording multiple GNSS position plots in the same MF4 log files (as part of some GNSS antenna evaluation tests) :-) 

![image](https://user-images.githubusercontent.com/26184427/193207819-e4f40f46-6e79-4ddb-b944-9b55b96670e7.png)

**Comment by danielhrisca** [comment]
With the fix it is still not possible to have two GPS windows active at the same time.

However you can close a GPS window and create a new working GPS windows; previously any other GPS window created after the first one would have been greyed out..

**Comment by MatinF** [comment]
In my tests it's working fine with multiple GPS windows open simultaneously 
![image](https://user-images.githubusercontent.com/26184427/193276287-e36dcff2-525d-41b2-956e-a8566cc0b47e.png)

**Comment by MatinF** [comment]
This has been resolved in the latest version from what I can see, suggest closing
