### ISSUE TITLE
'New record' referenced before assignment

### ISSUE THREAD

**Issue by cube2022** [danielhrisca/asammdf#774]
Python-Version: 3.9
Asammdf Version: 7.1.1 
File: mdf_v3.py

I always get the error "local variable 'new record' referenced before assignment in line 1734 in append new-record.append(None).
Is this a general problem or is something wrong with my configuration?

Regards

**Comment by danielhrisca** [comment]
> Is this a general problem or is something wrong with my configuration?

just a bug in the code, nothing wrong on your side

**Comment by danielhrisca** [comment]
@cube2022 please try the development branch code
