### ISSUE TITLE
How to Convert the Byte Type to the String Type during export

### ISSUE THREAD

**Issue by BigCat20196** [danielhrisca/asammdf#781]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.23.4'
'asammdf=7.1.1'
```
# Code 
```
import numpy as np
from asammdf import MDF, Signal
cycles = 100
sigs = []

mdf = MDF()
t = np.arange(cycles, dtype=np.float64)

sig = ["String channel sample {}".format(j).encode("utf-8") for j in range(cycles)]
sig = Signal(
    np.array(sig),
    t,
    name="Channel_string",
    comment="String channel",
    encoding="utf-8",
)
sigs.append(sig)

mdf.append(sigs, comment="arrays", common_timebase=True)
df = mdf.export(fmt='csv', filename='output_demo.csv', single_time_base=True, raster=0.1)
```

  ## MDF version
4.10

  ## Code snippet
  _please write here the code snippet that triggers the error_
  ```
# output_demo.csv
timestamps,Channel_string
0.0,b'String channel sample 0'
0.1,b'String channel sample 0'
0.2,b'String channel sample 0'
0.30000000000000004,b'String channel sample 0'
0.4,b'String channel sample 0'
0.5,b'String channel sample 0'
...

pandas output:
"b'String channel sample 0'"
"b'String channel sample 0'"
"b'String channel sample 0'"
"b'String channel sample 0'"
"b'String channel sample 0'"
...
```
  ## Traceback
  _please write here the error traceback_
  
# Description
Hi team, I am a beginner in data processing and am trying to read `mf4` files with `asammdf` and convert them to `csv`. The above code comes from the [sample](https://github.com/danielhrisca/asammdf/blob/master/examples/mf4_demo.py#L61) in this repo. It is a data in byte format exported and saved to the CSV. When I open csv again, I get a "b'String channel sample 0'" format, which is not I expected, and I want to get "String channel sample 0" format.

Is there a way to set the export format in the `mdf.export()` function or to load string data in the `mdf.append` ? Sorry, I do not know the mdf format.

The current workaround is to extract the value in the middle of "b'xxxx'" by `re`, but this is cumbersome and ugly. If there's a better way, please kindly let me know.

Appreciate if you can help  this !

**Comment by danielhrisca** [comment]
@BigCat20196 
please have a try with the development branch code

**Comment by BigCat20196** [comment]
Hi @danielhrisca, thanks for your quick reply !

The development branch code has the same issue. The format of the exported data cannot be set. One available way is to open csv again and use pandas to clean the data.

An appropriate solution has been found, so close this issue.

**Comment by thanoletsios** [comment]
Hello, unfortunately I am facing the same issue, but I did not found an appropriate solution yet. Could you explain to me how to get rid of the byte-strings and get the actual datatype in each pandas.DataFrame? Thank you so much!
