### ISSUE TITLE
No text can be seen after insert comment

### ISSUE THREAD

**Issue by xukegithub** [danielhrisca/asammdf#783]
# Python version

('python=3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 '
'bit (AMD64)]')
'os=Windows-10-10.0.19042-SP0'
'numpy=1.23.3'
'asammdf=7.1.1'

# Description
hello,
I'm not sure if it's the reason I'm using the error, I don't see any text after I insert comments。
"Alt + I" I also operated

![comments](https://user-images.githubusercontent.com/29155523/199638425-a25b23b9-84ef-44d2-bb04-7b04a3e67b49.png)

**Comment by danielhrisca** [comment]
For the moment this is not working

**Comment by danielhrisca** [comment]
@xukegithub please try out the development branch code

**Comment by xukegithub** [comment]
OK, I'll try it, thank you

**Comment by xukegithub** [comment]
![screenshot-20221124-155514](https://user-images.githubusercontent.com/29155523/203725026-7a6a14b7-ad68-4e96-9895-d4ae68b8b144.png)

thank you very much!
