### ISSUE TITLE
Asamdf file format

### ISSUE THREAD

**Issue by elon1992** [danielhrisca/asammdf#784]
@danielhrisca 
I am trying to read mdf4 file having ethernet data using asammdf, where i only have one data group and around 50 channel group, and in each channel group i am having 6 channels. Moreover, i printed out the data from data group block for my specific channel name using .whereis(). 

And how can i link the recorded data from a datablock to a respective channel group and a channel? if you could show in code where have you done that. Could you please explain that by calling the specefic channel name it prints out that specific channel sample drom the datablock of data group- how is it done or if could show in code where and how the linking is done.
could you please explain the format of the data group i.e how the recorded data is saved? is it like first the mdf datgroup header then ethernet frame, then ip frame format and in it the data?, is this true?

i really need your help.

Thank you

**Comment by danielhrisca** [comment]
Install MDF validator from Vector, it will show you the internal structure of the file. Also in the menu you will get the PDF with the specifications for MDF v3; the data group blocks records concept is identical.

For you frame channels you will see that there is a pointer to signal data blocks. This means that the actual frames are stored separately, and in the data group record you will just have the position offset (as integer) of the current sample in the referenced signal blocks.

![image](https://user-images.githubusercontent.com/20952040/201070231-19520e91-9f7d-4b1c-a4f3-e7bbb6562172.png)

The raw data in the referenced signal data blocks is structured as:
[Uint32 <size> value header][<size> bytes of actual data]

**Comment by elon1992** [comment]
> Install MDF validator from Vector, it will show you the internal structure of the file. Also in the menu you will get the PDF with the specifications for MDF v3; the data group blocks records concept is identical.
> 
> For you frame channels you will see that there is a pointer to signal data blocks. This means that the actual frames are stored separately, and in the data group record you will just have the position offset (as integer) of the current sample in the referenced signal blocks.
> 
> ![image](https://user-images.githubusercontent.com/20952040/201070231-19520e91-9f7d-4b1c-a4f3-e7bbb6562172.png)
> 
> The raw data in the referenced signal data blocks is structured as: [Uint32 value header][ bytes of actual data]

Thank you for the reply.

But i do not have signal data pointer in any channel group. Like asammdf creates alink between channel and its respective data in the data block, if you could please expalin me ho it is done or you can show me the code where it is done.

The raw data in the referenced signal data blocks is structured as:
[Uint32 value header][ bytes of actual data]
 is the the samples that we are getting using whereis() method. Moreover if possible could you please tell me the number of bytes  for [Uint32 value header][ bytes of actual data]. for eg 
i printed out the samples from a specefic channel using whereis(). 
it will be printed as <Signal channel_name: samples[[0 128 82 23 56 89 45 26 ...  225 62 233 45]
[.......]]
timestamps=[..........]
then all args that is returned after using Signal class

so in here is the values for sample that is showing here is the actual payload or there is also some header bytes. If yes, could you please tell me how much in bytes as i want to have any actual recorded payload with no headers or length bytes,etc.

Thank you
