### ISSUE TITLE
Logging camera data as MF4

### ISSUE THREAD

**Issue by blurrycontour** [danielhrisca/asammdf#785]
I am trying to save the webcam feed as MF4 file. So, I guess I'd have to save it frame by frame. I have a timestamp for every frame and also compression format (probably JPEG) and other metadata for every frame. What would be the best approach for this?

**Comment by danielhrisca** [comment]
There is no specification for this kind of logging. You could get some inspiration from the internal structure of the CAN bus logging (see here https://github.com/danielhrisca/asammdf/files/4328945/OBD2-DBC-MDF4.zip).

**Comment by homohapiens** [comment]
Thanks for sharing that. Is there some class to replicate the data structure of a CAN bus. I tried to do it with python Dataframes and it's not the same. But maybe I did it wrong. 
CAN bus channels also contain conversion and source channels. How to add those channels via asammdf?

**Comment by blurryContour** [comment]
Thanks for sharing that. Is there some class to replicate the data structure of a CAN bus. I tried to do it with python Dataframes and it's not the same. But maybe I did it wrong.
CAN bus channels also contain conversion and source channels. How to add those channels via asammdf?

**Comment by danielhrisca** [comment]
the limitation now is that when appending structure channels we always use the scaled samples (not the raw values) so there is no way to specify conversion rules for the structure fields.
