### ISSUE TITLE
Feature: Save display file with multiple windows

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#787]
The ability to save a display configuration is very useful for quickly opening up previous analyses/views.

However, it would be great if it would be possible to not only store 1 plot window - but that the display configuration stores the full 'grid' of plot windows with the correct sizing, focus area, plot coloring, zoom level (for GNSS plots) etc. This would enable almost a 'dashboard' style view in asammdf with minimal effort.

**Comment by danielhrisca** [comment]
Hello Martin,

the GPS zooming and location are not stored, but the display configuration files contain all the windows

**Comment by MatinF** [comment]
Hi Daniel,

I tested in latest dev. here is my plot view:

![image](https://user-images.githubusercontent.com/26184427/202720425-e0748c32-ef93-4e15-97ff-9d1344b69ed3.png)

When I save this as a display config, close the plots and open the display config, I do indeed get multiple windows now - but the focus seems off. It would be OK with the focus not being saved, but it would be nice if then at least the 'default' focus is selected when the display is loaded, so that the entire plots are displayed:

![image](https://user-images.githubusercontent.com/26184427/202720637-0000039b-4855-48c5-b437-e888e5546a4c.png)
