### ISSUE TITLE
Create new folder when executing .save function if it does not exist

### ISSUE THREAD

**Issue by fizcris** [danielhrisca/asammdf#79]
# Python version

```
('python=3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) '
 '[MSC v.1900 64 bit (AMD64)]')
'os=Windows-7-6.1.7601-SP1'
'numpy=1.14.2'

```
# Code 

  ## MDF version
'asammdf=4.0.0.dev'

  ## Code snippet

`
fileOutName = '.\\processed files\\TEST.MF4'
outputFile.save(dst=fileOutName, overwrite=True,compression=2)
`
  
  ## Traceback

> FileNotFoundError: [Errno 2] No such file or directory: '.\\processed files\\TEST.MF4'

# Description
It would be nice if the .save() function would be able to create a folder if it does not exists to store the output file inside.

**Comment by danielhrisca** [comment]
I will have an implementation in a few houra

**Comment by danielhrisca** [comment]
It should work now with the development branch code

**Comment by fizcris** [comment]
Comfirmed, it works as expected.
