### ISSUE TITLE
Unable to plot byte sample signals in Canape

### ISSUE THREAD

**Issue by sridhar-eswaran** [danielhrisca/asammdf#790]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19044-SP0'

'numpy=1.23.4'

'asammdf=7.1.1'
```
# Code 

  ## MDF version
 '4.10'

  ## Code snippet
```python

# channel_list -> List of signals to extract from a large MF4 file

mdf = MDF(mdf_file_path, channels=channel_list, use_display_names=False)

mdf_signal_list = []
for signalname in channels: 
        data = mdf.get(signalname)
        mdf_signal_list.append(data) 

with MDF(version='4.10') as MDF_CONSTRUCTOR:
        MDF_CONSTRUCTOR.append(mdf_signal_list,comment='mdf_file_name')
        MDF_CONSTRUCTOR.save('mdf_subset_path', overwrite=True)
```
  

  ## Traceback
No Error
  
# Description
From the original file, I can view the ACCStatus signal as plot in both Canape and asammdf GUI
![image](https://user-images.githubusercontent.com/62509359/203564275-06d2e22a-d0b3-4366-b9f2-4a8b6fe97c62.png)

But from the subset MF4 file, I am unable to plot (in both tools)
![image](https://user-images.githubusercontent.com/62509359/203565100-6f4190ef-cdbc-47e9-b4cf-7be05c94443b.png)

I can view them as table/ numeric 
![image](https://user-images.githubusercontent.com/62509359/203565317-4173a8b5-422e-4833-b5a8-e21808dd922d.png)

Sample signals exported as pkl are shared in the link [https://drive.google.com/file/d/1HVFwdkuJN3XC1nQ8wofgKE6hXHNNdmK7/view?usp=sharing](url)
Can you help me with this? Is this a limitation or am I doing something wrong?
Appreciate your help.
[Thanks]

**Comment by danielhrisca** [comment]
You are appending the scaled values. Use this instead to preserve the raw values and the channel conversion

```python
# channel_list -> List of signals to extract from a large MF4 file

mdf = MDF(mdf_file_path, channels=channel_list, use_display_names=False)
mdf.save('mdf_subset_path.mf4', overwrite=True)
mdf.close()

```

**Comment by sridhar-eswaran** [comment]
Thank you very much for your input. It is working after passing the 'raw=True' argument to the 'get' method.

```python
for signalname in channels: 
        data = mdf.get(signalname,raw=True)
```
