### ISSUE TITLE
7.2.0 unable to decode J1939 data with data length < 8 

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#801]
[data-length-below-8-j1939-decoding.zip](https://github.com/danielhrisca/asammdf/files/10277627/data-length-below-8-j1939-decoding.zip)

The latest version of asammdf seems to have a problem with decoding J1939/NMEA style data with data lengths below 8. While in principle the J1939 standard requires a data length of 8 bytes, there was previously a fix for this niche case in asammdf. 

Specifically, in the attached data, the ideal behavior would be to process "the part of the payload" that is possible to decode based on the DBC file. This should e.g. include the signal EngineSpeed for the CAN ID `0x0CF00400`. 

It would be great to retain the ability to decode this type of niche combination of J1939 with payloads below 8 bytes.

**Comment by danielhrisca** [comment]
The current code goes back at least 2 years. The check is made to see if the `DataBytes` dimension is at least as big as the message size specified in the DBC.

**Comment by danielhrisca** [comment]
See https://github.com/danielhrisca/asammdf/blob/fda5d791ac0a78943eb3dcf8899811cdcda34b82/asammdf/blocks/bus_logging_utils.py#L345

**Comment by MatinF** [comment]
I am quite sure we looked at this in an older version and that it was temporarily resolved in one of the 6.x.x builds. 

As a general rule, I think it can be the case that there may be a DBC file that specifies signal decoding rules for up to 8 bytes of data - yet a sensor may cut the payload length to e.g. 4 bytes or 6 bytes in case the message does not have any valid data for the remaining bytes. 

In such a case, the ideal behavior would be to decode the data available, i.e. use the available signal decoding information to extract signals from the available 4 or 6 bytes - and ignore the signals that cannot be decoded from the rest due to the missing payload bytes.

But it of course depends - if supporting this edge case causes a lot of complexity it may not be worth it.

**Comment by MatinF** [comment]
Suggest we postpone this part for now to avoid introducing other issues
