### ISSUE TITLE
Add support for loading data partially according to integer or boolean arrays

### ISSUE THREAD

**Issue by Illviljan** [danielhrisca/asammdf#806]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC '
 'v.1929 64 bit (AMD64)]')
'os=Windows-10'
'numpy=1.23.4'
'asammdf=7.1.0'
```
  
# Description

It is currently possible to load partial data using the `mdf.get` method:
https://github.com/danielhrisca/asammdf/blob/fda5d791ac0a78943eb3dcf8899811cdcda34b82/asammdf/blocks/mdf_v4.py#L6427-L6428

This allows loading a range of data in similar fashion to `np.array([1,2,3,4])[record_offset:record_count]` which saves some RAM if you only need a certain range.

It would be nice to extend the function to also support filtering the data using 
* integer arrays, `np.array([0, 1, 2, 8, 9], dtype=int)`.
* boolean arrays, `np.array([0, 1, 0, 1], dtype=bool)`.

This would allow quite advanced filtering without having to load all the data to RAM.

For inspiration h5py supports these and quite a bit of numpy's fancy indexing:
https://docs.h5py.org/en/stable/high/dataset.html?highlight=indexing#fancy-indexing

**Comment by danielhrisca** [comment]
To tell the truth my head hurts just by thinking on how to implement this

**Comment by Illviljan** [comment]
Seems h5py converts boolean arrays to integer arrays using `np.nonzero`.
https://github.com/h5py/h5py/blob/b3697ab2ced3342b3462fc3dcd1a11f26af74f1c/h5py/_hl/selections.py#L189-L196

One way of handling integer arrays could be to just split the integer arrays when it doesn't follow the `[record_offset:record_count]` format, then mdf.get can be used as normal:
```python
a = np.array([1, 2 ,3, 4, 7, 8, 9])

# Split integer arrays when it doesn't follow the [record_offset:record_count] format:
b = np.split(a, np.where(np.diff(a) != 1)[0] + 1)
Out[33]: [array([1, 2, 3, 4]), array([7, 8, 9])]

# Loop through the split arrays:
for i, v in enumerate(b):
    record_offset = v[0]
    record_count = v[-1]
    print(f"{i=}: {record_offset=}, {record_count=}")
    
i=0: record_offset=1, record_count=4
i=1: record_offset=7, record_count=9
```

For looping like this can become very slow though and I think h5py does this part in cython.
