### ISSUE TITLE
Error while reading channels with dependencies (flag: 17) but no reference_channel for MDF4

### ISSUE THREAD

**Issue by nahidpervez** [danielhrisca/asammdf#81]
# Python version
```
'python=3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) \n'
 '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
'os=Darwin-17.6.0-x86_64-i386-64bit'
'numpy=1.14.3'
'asammdf=3.3.1'
```
# Code 

  ## MDF version
```4.1```

  ## Code snippet
```obj.get('MoFMode_qntPostInj2Max_T',27,1)```
  
  ## Traceback
```
Traceback (most recent call last):

  File "<ipython-input-53-e715fc8e0a42>", line 1, in <module>
    obj.get('MoFMode_qntPostInj2Max_T',27,1)

  File "/anaconda3/lib/python3.6/site-packages/asammdf/mdf_v4.py", line 4053, in get
    ref_ch_nr, ref_dg_nr = ca_block.referenced_channels[i]

IndexError: list index out of range
```
  
# Description
dependencies:
```
thisGroup['channel_dependencies'][1]
Out[57]: 
[{'id': b'##CA',
  'reserved0': 0,
  'block_len': 112,
  'links_nr': 8,
  'composition_addr': 0,
  'ca_type': 2,
  'storage': 0,
  'dims': 1,
  'flags': 17,
  'byte_offset_base': 2,
  'invalidation_bit_base': 0,
  'dim_size_0': 15}]
```
Channel info:
```
thisGroup['channels'][1]
Out[54]: <Channel (name: MoFMode_qntPostInj2Max_T, unit: mg, comment: <CNcomment><TX/><names><display>MoFMode_qntPostInj2Max_T</display></names><raster>1.000000</raster></CNcomment>, address: 0x629740, conversion: <ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: {}, address: 0x0, fields: {'id': b'##CC', 'reserved0': 0, 'block_len': 128, 'links_nr': 4, 'name_addr': 0, 'unit_addr': 0, 'comment_addr': 0, 'inv_conv_addr': 0, 'conversion_type': 2, 'precision': 0, 'flags': 0, 'ref_param_nr': 0, 'val_param_nr': 6, 'min_phy_value': 0.0, 'max_phy_value': 0.0, 'P1': 0.0, 'P2': 0.01, 'P3': 0.0, 'P4': 0.0, 'P5': 0.0, 'P6': 1.0})>, source: <SourceInformation (name: , path: EtasCalibrationRecordingDevice, comment: , address: 0x0, fields: {'id': b'##SI', 'reserved0': 0, 'block_len': 56, 'links_nr': 3, 'name_addr': 4885560, 'path_addr': 4885592, 'comment_addr': 0, 'source_type': 4, 'bus_type': 1, 'flags': 0, 'reserved1': b'\x00\x00\x00\x00\x00'})>, fields: {'id': b'##CN', 'reserved0': 0, 'block_len': 160, 'links_nr': 8, 'next_ch_addr': 6461464, 'component_addr': 7072720, 'name_addr': 4885504, 'source_addr': 6461192, 'conversion_addr': 6415440, 'data_block_addr': 0, 'unit_addr': 4885824, 'comment_addr': 4885648, 'channel_type': 0, 'sync_type': 0, 'data_type': 2, 'bit_offset': 0, 'byte_offset': 8, 'bit_count': 16, 'flags': 0, 'pos_invalidation_bit': 0, 'precision': 255, 'reserved1': 0, 'attachment_nr': 0, 'min_raw_value': 0.0, 'max_raw_value': 0.0, 'lower_limit': 0.0, 'upper_limit': 0.0, 'lower_ext_limit': 0.0, 'upper_ext_limit': 0.0})>
```

this is the channel that caused the issue.

**Comment by danielhrisca** [comment]
Hello @nahidpervez ,

please use the latest development code; if you run your script again we should get a detailed print from this line https://github.com/danielhrisca/asammdf/blob/development/asammdf/mdf_v4.py#L4359

**Comment by nahidpervez** [comment]
Thanks @danielhrisca 
may be for batch processing purpose, we might need a way not to raise an exception. For example, when converting whole group, this exception will cause the whole group to fail.
Any recommendation?

**Comment by danielhrisca** [comment]
That's a good point. I will implement an option to choose between raising an exception and giving an warning.

For the purpose of debegging the real issue, please share the detailed print

**Comment by danielhrisca** [comment]
Hello Nahid,

can you make a screenshot of the channel array block using MDFValidator. You can see the block's address using ``thisGroup['channel_dependencies'][1].address``?

For 'ca_type' == 2 the channel array block should either have the values for the fixed axes or it should have the links that reference the channels used as axis. In your print there is neither.

**Comment by nahidpervez** [comment]
hello @danielhrisca, Sorry for the delayed response. I dont have a windows machine handy at this moment. I will try to get something later this week.

**Comment by danielhrisca** [comment]
I am sorry for not seeing this earlier. 

Regarding the screenshot, I was able to get MDFValidator running under Wine on Ubuntu. The XML parssing (MDBLOCK handling) requires additional software to be installed, but the core functionality works.

**Comment by danielhrisca** [comment]
@nahidpervez 
can you still help with debugging this issue?

**Comment by nahidpervez** [comment]
Hey Daniel, 

- Nahid Pervez

**Comment by nahidpervez** [comment]
@daniel i can stab at it later this week. Is this something urgent?

**Comment by danielhrisca** [comment]
It's not urgent for me, but it would be nice to get some progress on this

**Comment by danielhrisca** [comment]
@nahidpervez 
this issue is more then 1 year old. Is there anything we can do to advance it?

**Comment by danielhrisca** [comment]
Please reopen if this is still relevant
