### ISSUE TITLE
[Bug] mdf.iter_to_dataframe() does not respect float_interpolation_mode

### ISSUE THREAD

**Issue by andrewdenixg** [danielhrisca/asammdf#810]
# Python version
3.9

# Asammdf Version
7.2.0

# Code Snippet

```
mdf2.configure(float_interpolation = 0)
df = mdf.iter_to_dataframe(raster = 0.01)
```

## MDF version
  4.10

# Description
https://github.com/danielhrisca/asammdf/blob/fda5d791ac0a78943eb3dcf8899811cdcda34b82/asammdf/mdf.py#L3962

should be changed to 

 ```
signal.interp(
                        master,
                        integer_interpolation_mode = self._integer_interpolation,
                        float_interpolation_mode = self._float_interpolation
                    )
```

Currently iter_to_dataframe always uses float interpolation mode 1, but it's essential for my use case that we don't attempt to interpolate float values in the dataframe.

**Comment by danielhrisca** [comment]
@andrewdenixg please try  the development branch code
