### ISSUE TITLE
Linux wheel on PyPi

### ISSUE THREAD

**Issue by hanneskaeufler** [danielhrisca/asammdf#812]
# Description

It appears on pypi there are only prebuilt wheels for windows and macos. It would be nice to also have ubuntu 20.04 comptible wheels with each release.

**Comment by danielhrisca** [comment]
For Linux you just need to install buildessentials and pythondev

**Comment by hanneskaeufler** [comment]
Thanks for the quick reaponse, but with the goal of slimming down requirements, size, and runtime for CI workers, I want to avoid exactly that :)

**Comment by danielhrisca** [comment]
Please try the wheels from this build https://github.com/danielhrisca/asammdf/actions/runs/3986043212

**Comment by hanneskaeufler** [comment]
> Please try the wheels from this build https://github.com/danielhrisca/asammdf/actions/runs/3986043212

Tried it and works like a charm. Would love to have a release with this on PyPi <3

**Comment by danielhrisca** [comment]
7.3.0 will land in the next weeks

@zariiii9003 good job with the CI improvements

**Comment by danielhrisca** [comment]
@hanneskaeufler please check the PyPI wheels https://pypi.org/project/asammdf/#files
