### ISSUE TITLE
reading problem for large mf4 files

### ISSUE THREAD

**Issue by Lsardi** [danielhrisca/asammdf#818]
# Python version
_Please run the following snippet and write the output here_
```python
'python=3.9.12 (main, Apr  5 2022, 01:53:17) \n[Clang 12.0.0 ]'
'os=macOS-10.16-x86_64-i386-64bit'
'numpy=1.21.5'
ldf is not supported
xls is not supported
'asammdf=6.2.0'
```
# Code 

  ## MDF version
4.10

  ## Code snippet
with MDF("file.mf4") as mdf_file:
    df = mdf_file.to_dataframe()
  
  ## Traceback
I have no trace of execution because my operating system has stopped the python process 
  
# Description

I am working with files of different sizes. the to_datadrame function works on small files (example 10mo) but for larger files it uses too much ram. i tried to add the options raster=1,reduce_memory_usage=True, ignore_value2text_conversions=True. but the resulting dataframe is not what i want. 
I have run my code on a windows server with 200gb of ram and a 150mo file and the ram memory is 100% used. I have a 1gb file that I need to decode into a parquet. is this possible with your library?

**Comment by danielhrisca** [comment]
If you don't use the raster and you have a file with many unique time bases then you will end up with a huge DataFrame. The reason for this is that the union of all timestamps is computed, and all the signals are resampled with this common time base. 

Also the 1GB could be using compression for the data blocks, so the actual data size can be higher.
