### ISSUE TITLE
Meaningless values by coding mdf_extract_bus_logging function, while GUI works  fine.

### ISSUE THREAD

**Issue by AleFala** [danielhrisca/asammdf#819]
# Python version

```python
('python=3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC ' 'v.1916 64 bit (AMD64)]')
'os=Windows-10-10.0.19045-SP0'
'numpy=1.23.5'
'asammdf=7.3.2'
```
# Code 

  ## MDF version
4.11

  ## Code snippet
mdf = asammdf.MDF('file.MF4')
dbc = { "CAN" : [("dbc1.dbc", 0), ("dbc2.dbc", 0), ("dbc3.dbc", 0), ("dbc4.dbc", 0), ("dbc5.dbc", 0)] }
extracted = mdf.extract_bus_logging(database_files=dbc)
extracted.export("csv", filename="exported",time_as_date=True)
extracted.export("mat", filename="exported",format='5', oned_as='column', compression=True)
  
  ## Traceback
 No Error Traceback. The 'extracted' variable is successfully exported as .csv and .mat, but the problem is related to the values of specific signals which are different from the same signals exported by the GUI.
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

I've tried converting the mf4 file both via code (posted above) and via the asammdf GUI, using the same dbc files and mdf.extract_bus_logging function.
What results is the different value of some variables. With the GUI these values ​​make sense. This cannot be said of the code.
At first glance it seems that through code, the values ​​of these variables which are negative according to the GUI, are set to meaningless values.

Unfortunately I can not trace the problem, not even being too good at analyzing the differences between the code and the GUI.

**Comment by danielhrisca** [comment]
please share a screenshot with the GUI settings when you do the export

**Comment by AleFala** [comment]
![image](https://user-images.githubusercontent.com/124251335/218523653-67e5869a-4b7e-4df4-86be-01866b1f00da.png)

**Comment by danielhrisca** [comment]
The screenshot is not from the bus logging tab so please check again. The same function is called by the GUI. 

Can you send the file for analysis?

**Comment by danielhrisca** [comment]
I cannot reproduce

**Comment by AleFala** [comment]
Do you need something more to further investigate the problem?
I really don't know where the problem may lie.

Thank you.

**Comment by danielhrisca** [comment]
The file would help

**Comment by AleFala** [comment]
Can I share the mf4 and dbc files just with you so that you can check the problem? Can I share with the email or other channel? 

Thank you.

**Comment by AleFala** [comment]
i sent files via email.

**Comment by RossThompsonPS** [comment]
Did you get a solution to this issue?

**Comment by Collin-Brock** [comment]
I had the same issue. For me using version 7.2.0 of asammdf fixed this issue. All later versions had the same issue where some of the channel data when exporting where negative values appeared would be erroneously high values.

**Comment by Mayerch1** [comment]
The issue seems to exist in pip releases `7.3.0` up to the most recent `7.3.14`.
A CAN signal limited from _-327.68_ up to _327.67_ (factor _0.01_ on 16bit **signed** integer) will result in positive values up to _655.35_

Going back to pip release `7.2.0` will fix the issue.

Looks like an issue with unsigned/signed conversion, 
Interpreting the CAN signals as **unsigned** integer would yield the observed maximum value of _655.35_.
