### ISSUE TITLE
file_comment field returns empty in MDF4

### ISSUE THREAD

**Issue by nahidpervez** [danielhrisca/asammdf#82]
for MDF3 the file_comment field returns a block of string, however, in MDF4 this field returns nothing.

**Comment by danielhrisca** [comment]
Hello Nahid,

is there a file comment to begin with? You can use MDFValidator to check this

**Comment by nahidpervez** [comment]
Yes, there is comment in the file.

**Comment by danielhrisca** [comment]
Using the development branch code you can access the file comment like this

```python
mdf = MDF(filename)
comment = mdf.header.comment
```
