### ISSUE TITLE
Key error when trying to convert mdf 3.00 file: group with master channel only?

### ISSUE THREAD

**Issue by da2el** [danielhrisca/asammdf#820]
# Python version
'python=3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.19044-SP0'
'numpy=1.24.1'
'asammdf=7.1.0

  ## MDF version
3.00

  ## Code snippet
    with asammdf.MDF(inFile) as mdf:
        mdf=mdf.convert("4.10")
  
  ## Traceback
  File C:\TestData\TranslateMDFSignalNames.py:83 in convertFile
    mdf=mdf.convert(version)

  File ~\.conda\envs\BMSValidation\lib\site-packages\asammdf\mdf.py:815 in convert
    for idx, sigs in enumerate(

  File ~\.conda\envs\BMSValidation\lib\site-packages\asammdf\blocks\mdf_v3.py:3831 in _yield_selected_signals
    channels = groups[index]

KeyError: 5
  
# Description
_Disclaimer: This could be an issue with the original mdf file (created by ETAS Experiment Environment). Other files created by ETAS INCA do not show the problem._
The MDF version of the original file is 3.00. Trying to convert the file to version 4.10 or any other version results in a key error. It seems that the file contains a group with only the master channel present, for which _included_channels returns a dict which cannot be parsed correctly, i.e. calling
`mdf.included_channels(5)`
returns
`{5: {}}`
instead of something like {5: {5: [] } }

likewise
```
len(mdf.groups[5].channels)
 1
```

and
```
mdf.masters_db.get(5,None)
 0
```

I found that changing in mdf_v3.py (lines 3761+3762 in v7.10)

```
            if included_channels:
                gps[index] = sorted(included_channels)
```

to

```
            if included_channels is not None:
                gps[index] = sorted(included_channels)
```

allows the conversion to proceed, and the resulting file seems ok in ETAS MDA. I do not know, however, if this violates the filetype specifications or could introduce other issues somewhere else. If this is of interest, I could provide the offending mdf file, please let me know if anyone wants to investigate further.

**Comment by danielhrisca** [comment]
@da2el please try the development branch code

**Comment by da2el** [comment]
Hi Daniel,
please excuse the long delay. I can confirm that the issue is resolved using the most recent development version! Thank you for the quick fix!
