### ISSUE TITLE
Can Not Import 'MDF4' from 'asammdf'

### ISSUE THREAD

**Issue by ege126** [danielhrisca/asammdf#822]
# Python version
_Python Version: 3.11.2_

# Code 

  ## MDF version
  _asammdf Version: 7.3.2_

  ## Code snippet
 ```
 from asammdf import MDF4
 def open_mdf4(filename):
    mdf = MDF4(filename, version='4.00')
    #mdf = MDF4('LIDAR_LJ02613_20200404_093147_PDX-003-001-054_VBS01_000000.mf4', version='4.00')
```  
   ## Traceback
_Traceback (most recent call last):
  File "C:\Users\duenege\Documents\DENEME\dlt_extractor_Simple.py", line 3, in <module>
    from asammdf import MDF4
ImportError: cannot import name 'MDF4' from 'asammdf' (C:\Users\duenege\AppData\Local\Programs\Python\Python311\Lib\site-packages\asammdf\__init__.py)_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_The script is unable to import the 'MDF4' function from asammdf module. I also tried using ```import asammdf``` with the function use ```asammdf.MDF4``` but it does not work again. I installed asammdf by ```pip install asammdf```, and also tried reinstalling, I am still unable to proceed._

**Comment by danielhrisca** [comment]
That is exactly on purpose.

You must always use the `MDF` class thst provides uniform acces to MDF v3 and v4 files

**Comment by ege126** [comment]
Does this feature come with the newer versions? Because the code I provided was perfectly in use on another device. How can I use ```MDF``` class for the same purpose? Is it enough just to replace ```MDF4``` with ```MDF```? In the documentation there is no hint about the use or where not to use the ```MDF4```. Could you enlighten?

**Comment by danielhrisca** [comment]
You just have to use MDF instead of MF4.

MDF contains all the methods specific to the MDF4 or MDF3 classes, but also extra methods (like filter, export, to_dataframe...) that are not available in the other classes.

**Comment by ege126** [comment]
Thank you for the explanation.
