### ISSUE TITLE
when load "dspf" file, the plot window shows error

### ISSUE THREAD

**Issue by Zhao00Xu** [danielhrisca/asammdf#823]
# Python version
('python=3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19045-SP0'
'numpy=1.23.3'
'asammdf=7.3.2'
# Code 

  ## MDF version
  4.10

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description
first, open a mdf file, drag a channel group to the mdi_area and choose the plot, second, minimize the plot window and save as a "dspf" file, close the "Single File" or close the main window, third, open the mdf file again, and load the dspf file which you saved just now, maximize the plot window, the plot area in plot window is empty.

**Comment by danielhrisca** [comment]
@Zhao00Xu please try the development branch code

**Comment by Zhao00Xu** [comment]
thank you.
