### ISSUE TITLE
numpy.core.multiarray failed to import failed when trying to import asammdf

### ISSUE THREAD

**Issue by Abhishek6970** [danielhrisca/asammdf#826]
ImportError                               Traceback (most recent call last)
[<ipython-input-3-3ecd158f4829>](https://localhost:8080/#) in <module>
----> 1 import asammdf

3 frames
[/usr/local/lib/python3.9/dist-packages/asammdf/blocks/mdf_v3.py](https://localhost:8080/#) in <module>
     50 from ..version import __version__
     51 from .conversion_utils import conversion_transfer
---> 52 from .cutils import get_channel_raw_bytes
     53 from .mdf_common import MDF_Common
     54 from .options import get_global_option

ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by danielhrisca** [comment]
which numpy version do you have?

**Comment by Abhishek6970** [comment]
Tested with 1.19, 1.22 and 1.24

**Comment by danielhrisca** [comment]
there must be some problem on your setup. Can you try a fresh virtual env?

**Comment by Abhishek6970** [comment]
Sure, Let me try and get back to you :)
