### ISSUE TITLE
ModuleNotFoundError: No module named 'pyqtgraph.canvas.CanvasTemplate_pyside6'

### ISSUE THREAD

**Issue by zariiii9003** [danielhrisca/asammdf#832]
The template files were removed in https://github.com/pyqtgraph/pyqtgraph/pull/2448

https://github.com/danielhrisca/asammdf/blob/180a1588737ae7aaf367aaa8fd1c81aff616df16/src/asammdf/gui/widgets/plot.py#L16

**Comment by zariiii9003** [comment]
Thank you 👍

**Comment by raleighlittles** [comment]
@danielhrisca I'm still having the same issue, even with the latest version of asammdf. 

https://github.com/danielhrisca/asammdf/issues/868

**Comment by reneebeling** [comment]
@danielhrisca the same for me. It only works with pyqtgraph==0.13.1, as mentioned by @zariiii9003 

![image](https://github.com/danielhrisca/asammdf/assets/64730014/dea3bda1-3344-4d0c-a5a5-6f3bbe9ae7f3)

**Comment by xMesa-git** [comment]
same for 0.13.3, reverted to 0.13.1 but had errors somewhere else...
