### ISSUE TITLE
zlib-ng

### ISSUE THREAD

**Issue by rhpvorderman** [danielhrisca/asammdf#834]
Hi @danielhrisca. I maintain python-isal which is a dependency of your project. Recently I also made bindings for zlib-ng: https://github.com/pycompression/python-zlib-ng. I see asammdf also allows editing (and thus saving mdf files). Zlib-ng should speed up the higher compression levels (which ISA-L does not support). This might be of interest to you so I thought I'd drop a note.

**Comment by danielhrisca** [comment]
Thank you Ruben, the time penalty for higher compression levels doesn't make much sense from my point. The size is maybe 10% smaller and the execution time is order of magnitude higher.
