### ISSUE TITLE
Timedelta ValueError in offset, particularly in large mf4 file

### ISSUE THREAD

**Issue by haydersaad** [danielhrisca/asammdf#836]
# Python version

'python=3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 '
 'bit (AMD64)]'
'os=Windows-10-10.0.19044-SP0'
'numpy=1.24.2'
'asammdf=7.3.2'

# Code 

  ## MDF version
  I do not understand how to run the MDF version command. 
  Should I do something like: print(MDF(path-to-mf4-file).version)?
  If it helps, it is an mf4 file.

  ## Code snippet
  The line below in v4_blocks (line 5469) results in the error.
  tz = timezone(timedelta(minutes=self.tz_offset + self.daylight_save_time))
  
  This line is called by mdf.py line 2148
  mdf.header.start_time = self.header.start_time
  
  ## Traceback
File c:\Users\hsaad\firmware\firmware\.venv\lib\site-packages\asammdf\mdf.py:4481, in MDF.to_dataframe(self, channels, raster, time_from_zero, empty_channels, keep_arrays, use_display_names, time_as_date, reduce_memory_usage, raw, ignore_value2text_conversions, use_interpolation, only_basenames, interpolate_outwards_with_nan, numeric_1D_only, progress)
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4401'>4402</a> """generate pandas DataFrame
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4402'>4403</a> 
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4403'>4404</a> Parameters
   (...)
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4477'>4478</a> 
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4478'>4479</a> """
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4479'>4480</a> if channels is not None:
-> <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4480'>4481</a>     mdf = self.filter(channels)
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4482'>4483</a>     result = mdf.to_dataframe(
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4483'>4484</a>         raster=raster,
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4484'>4485</a>         time_from_zero=time_from_zero,
   (...)
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4495'>4496</a>         numeric_1D_only=numeric_1D_only,
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4496'>4497</a>     )
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=4498'>4499</a>     mdf.close()

File c:\Users\hsaad\firmware\firmware\.venv\lib\site-packages\asammdf\mdf.py:2148, in MDF.filter(self, channels, version, progress)
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=2145'>2146</a> float_interpolation_mode = self._float_interpolation
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=2146'>2147</a> mdf.configure(from_other=self)
-> <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=2147'>2148</a> mdf.header.start_time = self.header.start_time
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=2149'>2150</a> self.configure(copy_on_get=False)
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/mdf.py?line=2151'>2152</a> if self.name:

File c:\Users\hsaad\firmware\firmware\.venv\lib\site-packages\asammdf\blocks\v4_blocks.py:5469, in HeaderBlock.start_time(self)
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/blocks/v4_blocks.py?line=5466'>5467</a>     tz = dateutil.tz.tzlocal()
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/blocks/v4_blocks.py?line=5467'>5468</a> else:
-> <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/blocks/v4_blocks.py?line=5468'>5469</a>     tz = timezone(timedelta(minutes=self.tz_offset + self.daylight_save_time))
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/blocks/v4_blocks.py?line=5470'>5471</a> try:
   <a href='file:///c%3A/Users/hsaad/firmware/firmware/.venv/lib/site-packages/asammdf/blocks/v4_blocks.py?line=5471'>5472</a>     timestamp = datetime.fromtimestamp(timestamp, tz)

ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24), not datetime.timedelta(days=19, seconds=46800).
  
# Description
I am trying to load the mf4 file ( 32GB in size) and this is the error I get. I understand 32GB might be a lot, but the code worked just find on a similar 19GB file. Please let me know if there's any more information I can provide you with ( I will not be able to provide you with the 32GB file due to its large size).
![image](https://user-images.githubusercontent.com/91809942/227070947-d9b8a04c-05d4-4885-8b1c-4c4f34e5cadd.png)

Thank you!

**Comment by danielhrisca** [comment]
please show the header block using MDFValidator from vector
![image](https://user-images.githubusercontent.com/20952040/227138718-9844d073-b968-4114-a991-a6e94d664462.png)

**Comment by haydersaad** [comment]
![image](https://user-images.githubusercontent.com/91809942/227279224-a8569276-e73d-48be-af31-c360314e7282.png)

**Comment by danielhrisca** [comment]
Obviously the file is corrupted

**Comment by haydersaad** [comment]
![image](https://user-images.githubusercontent.com/91809942/227282244-5da08b75-33fa-49b2-a145-0bc512097629.png)

Does this file seem corrupted to you as well? Because this one runs properly when I try to plot all alerts.

**Comment by haydersaad** [comment]
I am able to load those smaller files consistently. 
Would there be a way for me to ignore offset values completely. As in, I do not care which timezone the plots are in, as long as they are relatively the same to each other.
Thank you very much once again for your help!

**Comment by danielhrisca** [comment]
Just set a new `start_time` before processing the file

```pythony
from datetime import datetime
import time

localtz = dateutil.tz.tzlocal()
start_time = datetime.fromtimestamp(time.time(), tz=localtz)

mdf = MDF(file_name)
mdf.start_time = start_time 
```

**Comment by danielhrisca** [comment]
Which application was used to record the files? You can see in the IDblock

![image](https://user-images.githubusercontent.com/20952040/227287364-9a4cb22c-09e2-4a87-af8e-b2b819548c5b.png)

**Comment by haydersaad** [comment]
![image](https://user-images.githubusercontent.com/91809942/227287906-77a9b490-fa84-416d-94e5-81f2cd553da4.png)

**Comment by haydersaad** [comment]
Will do!
In the meantime, for your suggestion to set a new start_time, should I do it here?
![image](https://user-images.githubusercontent.com/91809942/227290381-f5a96abf-a7c8-47b7-be9a-167303883b51.png)
localtz = dateutil.tz.tzlocal()
start_time = datetime.fromtimestamp(time.time(), tz=localtz)
As in mdf.header.start_time = start_time

**Comment by danielhrisca** [comment]
No I mean in your script just after you create the MDF object
