### ISSUE TITLE
b hypen data format

### ISSUE THREAD

**Issue by tistelac** [danielhrisca/asammdf#837]
# Python version

('python=3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.22.4'
'asammdf=7.0.7'

# Code 

  ## MDF version
 4.10

  ## Code snippet
my_signal = my_mdf.get('VehSpd_Cval_CPC').samples
my_signal_physical = my_mdf.get('VehSpd_Cval_CPC').physical().samples

print('my_signal[0]', my_signal[0])
print('my_signal_physical[0]', my_signal_physical[0])  

# Description

Data comes back in format b'*number*'

Please advice, thank you
my_signal[0] b'99.74609375'
my_signal_physical[0] b'99.74609375'

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

Data comes back in format b'

Please advice, thank you

[bhypen_issue.zip](https://github.com/danielhrisca/asammdf/files/11064803/bhypen_issue.zip)

**Comment by danielhrisca** [comment]
Update to 7.3.3.

**Comment by tistelac** [comment]
[b_apastroph_Latitude_Cval_CTP.zip](https://github.com/danielhrisca/asammdf/files/11078753/b_apastroph_Latitude_Cval_CTP.zip)

Some channels still come in as b'
channel:
Latitude_Cval_CTP

## output
Latitude_Cval_CTP[0] b'45.55901899999998'

## Code snippet
mdf_path = r'C:\Data\Test Files\b_apastroph_Latitude_Cval_CTP.mf4'
my_mdf = MDF(mdf_path) #, 'low', time_from_zero=True)
print(MDF(mdf_path).version)

Latitude_Cval_CTP_lists = my_mdf.whereis('Latitude_Cval_CTP')
Latitude_Cval_CTP = my_mdf.get(None, Latitude_Cval_CTP_lists[0][0], Latitude_Cval_CTP_lists[0][1]).samples
print('Latitude_Cval_CTP[0]', Latitude_Cval_CTP[0])

## output
Latitude_Cval_CTP[0] b'45.55901899999998'


## MDF version
('python=3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.24.2'
'asammdf=7.3.3'
4.10

**Comment by danielhrisca** [comment]
Try the master branch code

**Comment by tistelac** [comment]
master branch on 
https://github.com/danielhrisca/asammdf

Is at 'asammdf=7.3.2'

'asammdf=7.3.2' same issue, Latitude_Cval_CTP[0] = b'45.55901899999998'

I also tried the latest PyPi version 'asammdf=7.3.5  same issue

**Comment by danielhrisca** [comment]
7.3.6 is available on PyPI
