### ISSUE TITLE
Lacks support of previous *.mat file types

### ISSUE THREAD

**Issue by famouspotatoes1** [danielhrisca/asammdf#853]
# asammdf version
  7.2.0
  
# Description
This version appears to have dropped support for exporting earlier *.mat file types. If possible, I would like to have those available again. The reason is, I use R for file processing and it has limited support for v7.3 matlab files. Also, the old *.mat file types were smaller in size than the new "hdf5" based type.

**Comment by danielhrisca** [comment]
If you are running from source you just need to install scipy

**Comment by famouspotatoes1** [comment]
Ok, thanks Daniel. Is there a pre-compiled version anywhere? I used to use one from CSS electronics but it looks like Martin is pointing people to download the zip file now. I'm not set up to build it myself and add dependencies where needed.

**Comment by danielhrisca** [comment]
You can use this executable build https://github.com/danielhrisca/asammdf/actions/runs/4742499464 (download the `dist/zip` archive and launch `asammdfgui.exe` from the Windows folder)

![image](https://user-images.githubusercontent.com/20952040/233061505-8cf601f5-8561-438e-a713-092a07da5674.png)
