### ISSUE TITLE
Unable to load and display graphs for large mf4 files on linux: Kernel died

### ISSUE THREAD

**Issue by haydersaad** [danielhrisca/asammdf#858]
# Python version
'python=3.10.10 (tags/v3.10.10:aad5f6a, Feb 7 2023, 17:20:36) [MSC v.1929 64 '
'bit (AMD64)]'
'os=Windows-10-10.0.19044-SP0'
'numpy=1.24.2'
'asammdf=7.3.2'

On linux dockerised vm:
'python=3.10.8'
'os="Debian GNU/Linux 9 (stretch)"'
'asammdf==5.21.0'
'numpy=1.23.4'

# Code 

  ## MDF version
mf4 (MDF4.10 I believe)

  ## Code snippet
loaded_mf4 = MDF(mf4_path, channels=[signal])
df = loaded_mf4.to_dataframe(use_interpolation=False, time_as_date=True, channels=[signal], reduce_memory_usage=True).tz_convert('UTC')
  ## Traceback
12:46:52    File "/usr/local/lib/python3.10/site-packages/papermill/execute.py", line 113, in execute_notebook
12:46:52      nb = papermill_engines.execute_notebook_with_engine(
12:46:52    File "/usr/local/lib/python3.10/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
12:46:52      return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
12:46:52    File "/usr/local/lib/python3.10/site-packages/papermill/engines.py", line 367, in execute_notebook
12:46:52      cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
12:46:52    File "/usr/local/lib/python3.10/site-packages/papermill/engines.py", line 436, in execute_managed_notebook
12:46:52      return PapermillNotebookClient(nb_man, **final_kwargs).execute()
12:46:52    File "/usr/local/lib/python3.10/site-packages/papermill/clientwrap.py", line 45, in execute
12:46:52      self.papermill_execute_cells()
12:46:52    File "/usr/local/lib/python3.10/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
12:46:52      self.execute_cell(cell, index)
12:46:52    File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
12:46:52      return just_run(coro(*args, **kwargs))
12:46:52    File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
12:46:52      return loop.run_until_complete(coro)
12:46:52    File "/usr/local/lib/python3.10/site-packages/nest_asyncio.py", line 90, in run_until_complete
12:46:52      return f.result()
12:46:52    File "/usr/local/lib/python3.10/asyncio/futures.py", line 201, in result
12:46:52      raise self._exception.with_traceback(self._exception_tb)
12:46:52    File "/usr/local/lib/python3.10/asyncio/tasks.py", line 234, in __step
12:46:52      result = coro.throw(exc)
12:46:52    File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1004, in async_execute_cell
12:46:52      raise DeadKernelError("Kernel died")
12:46:52  nbclient.exceptions.DeadKernelError: Kernel died
12:46:52  ERROR:asyncio:Task was destroyed but it is pending!

# Description
 As seen in the traceback, my kernel keeps dying. FYI, this occurs only when I am on linux and am using mf4 file >5GB. My jupyter notebook works perfectly on windows for any mf4 file size (i tried upto 32 GB's with no problem). However, my jupyter notebook does not run when on a dockerised linux vm and file size >2.5gb.
 
 I suspect it may be because I am running out of memory, so I did some tests to see memory usage on windows as well as linux: On windows I am using ~700MB of RAM for a 13 GB mf4 file(file processed within 5 minutes). While on linux, I am throttling at 16GB of RAM and then kernel dies eventually.
 I have tried using memory="low" parameter as well as reduce_memory_usage="True" without any success.
 I also tried using raster=1 (this errors out because i sometimes have multiple mf4 files and I need to join their time series data, and raster=1 doesn't allow me to join the time series data).
 I also tried to enable ignore_value_2_text_conversion but that does not solve my problem either.
 
 For now, my biggest question is: Why is the mf4 file parsed perfectly and easily and quickly on windows, but always breaks with linux?
 Please let me know if you need any more information from my side to help you understand my problem
 
 Thank you for your time.

**Comment by haydersaad** [comment]
Just to be sure asammdf versioning is not the problem, I switched windows asammdf version to 5.21.0 and everything works just fine just like before.
This further seems to narrow down that dockerised linux vm is the main difference resulting in kernel died

**Comment by danielhrisca** [comment]
@haydersaad please try again with the development branch code
