### ISSUE TITLE
Reduce_memory_usage and invalidation_bits behaviour

### ISSUE THREAD

**Issue by car-efficiency** [danielhrisca/asammdf#859]
# Python version
_Please run the following snippet and write the output here_
'python=3.9.5 (default, Jul  5 2021, 13:54:33) \n[GCC 9.2.0]'
'os=Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17'
'numpy=1.23.5'
'asammdf=7.3.12'
# Code 

  ## MDF version
 4.00

  ## Code snippet
```
                        df_mf4_stacked=mf4_stacked.to_dataframe(
                            channels=channels,
                            raster=raster,
                            time_from_zero=True,
                            reduce_memory_usage=True,
                            ignore_value2text_conversions=True,
                        )
```
  
  ## Traceback

>   File "/home/../lib/python3.9/site-packages/asammdf/mdf.py", line 4493, in to_dataframe
>     result = mdf.to_dataframe(
>   File "/home/../lib/python3.9/site-packages/asammdf/mdf.py", line 4736, in to_dataframe
>     sig.samples = downcast(sig.samples)
>   File "/home/../lib/python3.9/site-packages/asammdf/blocks/utils.py", line 1642, in downcast
>     min_ = array.min()
>   File "/home/../lib/python3.9/site-packages/numpy/core/_methods.py", line 44, in _amin
>     return umr_minimum(a, axis, None, out, keepdims, initial, where)
> ValueError: zero-size array to reduction operation minimum which has no identity

  
# Description

The creation of a dataframe fails. One signal in the mf4 file has all invalidation_bits in the array are set to "true". The signal samples are an array of zeros.
![image](https://user-images.githubusercontent.com/132067129/236816443-a5141fb0-5482-4c2c-a223-16325841d748.png)
![image](https://user-images.githubusercontent.com/132067129/236816515-d635cc3c-2d37-49d0-b7e0-862606bcf400.png)

Therefore, the "validate" method in signal.py removes all signal samples and returns a signal object with an empty array.
![image](https://user-images.githubusercontent.com/132067129/236816620-761d444d-65e8-4b05-8663-c486b8b4b0ee.png)

This empty sig.samles array leads to the error in utils.py because we use the reduce_memory_usage feature while using with large mf4 files (that is also why we cannot just deactivate reduce_memory_usage). 
![image](https://user-images.githubusercontent.com/132067129/236817694-12fccade-c8d4-46f8-bcd1-8d65738ae3dc.png)
![image](https://user-images.githubusercontent.com/132067129/236817860-7eb01677-e979-48b0-8574-e1de29dec4dd.png)

Is there a way to solve this problem?

Thank you very much for your help.

**Comment by danielhrisca** [comment]
can this be closed now?

**Comment by car-efficiency** [comment]
Thank you very much
