### ISSUE TITLE
Unable to Run asammdf GUI due to ModuleNotFoundError

### ISSUE THREAD

**Issue by saran9991** [danielhrisca/asammdf#863]
# Python version

('python=3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.22621-SP0'
'numpy=1.24.3'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.3.12'

# Traceback
ModuleNotFoundError: No module named '**pyqtgraph.canvas.CanvasTemplate_pyside6**'
ModuleNotFoundError: No module named '**pyqtgraph.console.template_generic**'
  
# Description

After installing the asammdf GUI via the command `pip install asammdf[gui]` and after manually installing the modules: PyQt5 and pyqtgraph, I encountered errors related to pyqtgraph module, as shown above. 

I think this issue could be due to discrepancies in library versions. The exact version of PyQT5 and pyqtgraph required to successfully run asammdf GUI isn't explicitly mentioned in the documentation. It is possible that the GUI does not operate properly with the latest versions of these libraries.

Any help would be nice, thank you!

**Comment by tk-130** [comment]
I also encountered a similar phenomenon. And I have confirmed that installing pyside6 with 6.3.1 eliminates a phenomenon similar to the one you have discovered.

**Comment by felixFleetZero** [comment]
Same issue with Python 3.10.11, had to force install QtPy v2.3.1 and pyside6 v6.3.1 to have the GUI working without crashing due to the ModuleNotFoundError!
Shouldn't the requirements.txt of the module be updated to force those versions?
Also, seems that version of pyside6 doesn't support Python 3.11, would be good to add that to the README.

**Comment by danielhrisca** [comment]
With the latest release 7.3.16 running pip install asammdf[gui] will install the correct pinned version
