### ISSUE TITLE
Slow handling of large number of small MF4 files

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#865]
Hi Daniel,

Not sure if this is something that is possible to improve, but just an observation:

I am trying to concatenate 2000+ small MF4 files (~100-150 kb each), a total of ~300 MB in uncompressed form.

From past experiences, asammdf can handle quite well single 300 MB files - but it seems to practically crash and become non-functional when I load and attempt to concatenate the large number of small files.

Perhaps there is a way to tweak the logic of what is actually loaded in asammdf during this process - and/or make the processing somehow sequential in case this is a RAM issue or similar. 

I have attached the data I used to test this below:
https://canlogger.csselectronics.com/temp/testdata.zip

**Comment by JulianWgs** [comment]
(Not associated with the project)

Can you [provide the code](https://matthewrocklin.com/minimal-bug-reports) you are using? This would help to see how you are using asammdf. Calling a fast function (asammdf) in a loop with a lot of iterations (hot-loop) has always been a performance bottleneck of python. I would advise you to profile the program with [line_profiler](https://github.com/pyutils/line_profiler) to see where to program spends most of the time. If it is spending most of the time reading data from the hard drive you might consider a `ThreadPoolExecutor` or else a `ProcessPoolExecutor` from `concurrent.futures`. You can read more about it [here](https://realpython.com/python-concurrency/). Another angle could be to use dask as it greatly simplifies multiprocessing with complex libraries / data structures.

Alse keep in mind that issue are usually not a space to answer usage questions, but I dont know how it is handled in this repo :)

**Comment by MatinF** [comment]
This refers to usage in the asammdf GUI, not via the asammdf Python API directly.

**Comment by danielhrisca** [comment]
Please try out the development branch

**Comment by MatinF** [comment]
Hi Daniel,

the dev branch is much better in terms of loading the files into the concatenation menu and does not seem to 'collapse' under the large number of files. 

When actually hitting concatenate, the GUI seems to be stuck at the first file for a very long time, after which it appears to process files extremely fast. I'm guessing some form of "initialization" is done here in the start. I think this is a minor issue, main consideration would be whether to change the text in the pop up box to state "preparing concatenation (this may take a while)" before it moves on to looping through the files. Subsequent files are processed very fast (~15 per second).

Overall, this works great. It would be awesome to get a new official release GUI build based on this latest dev build. 

Martin
