### ISSUE TITLE
get_group time_from_zero=True can lead to bugs

### ISSUE THREAD

**Issue by JulianWgs** [danielhrisca/asammdf#866]
Hi all,

I recently had a bug in my code that was caused by the default value of `time_from_zero=True` in `get_group`.

I used the following code snippet to get the time of a warning:

```python
# Returns the first timestamp where the signal is no longer "No Warning"
timestamp= (mdf.get_group(1337`)["Signal"] != "No Warning!").idxmax()
```

If I now used this time anywhere else it will be wrong.

1. If I use with another group I got by using `get_group` they will be slightly desynchronized as both signal didnt start at the exact same time.
2. If I use that signal in asammdf plot (plt.axvline) it will be off by the start time of the signal.

To my knowledge this is the only place this happens. Every other API (e.g. `get`) does not do this.

What is the reason for this? I believe a better standard value would be `time_from_zero=False`.

I know this would be a breaking change, but since it is not unreasonably bad, it would be fine to wait for the next major release.

Best regards & thanks for the awesome library
Julian

Edit: The same is True for `MDF.to_dataframe`.

**Comment by danielhrisca** [comment]
For compatibility reasons I wouldn't change the default value, so I guess you just have to keep in mind to set the argument value to False
