### ISSUE TITLE
Question on "time" and "Time"

### ISSUE THREAD

**Issue by WaetzoldP** [danielhrisca/asammdf#87]
I've got a simple question:
Depending on  several versions of MDF the time signal is referenced as "time" and "Time" respectively. Is this inevitable due to meet the specifications? In practise this turned out to be quite cumbersome.

**Comment by danielhrisca** [comment]
Hello @WaetzoldP,

there is no mandatory name for the master channel.

Can you point out where this creates problems for you?

**Comment by WaetzoldP** [comment]
As I mentioned above: It's just cumbersome for the subsequent processing. IMHO it would be nice, if asammdf behaves consistently, i.e. always uses "time". Hence postprocessing would be more simple.

**Comment by danielhrisca** [comment]
Hello @WaetzoldP ,

__asammdf__ will use 'time' by default when creating new channels. However the time channel name will be preserved when reading a measurement. Please have a try with the latest development branch code.

**Comment by danielhrisca** [comment]
Is there anything more to add to this issue?
