### ISSUE TITLE
Bug in CSV export causes incorrect values for some signals

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#870]
Tested in asammdf GUI 7.2.0 on Windows 10. Log file attached below.

To reproduce:

1) Check the values of the signal `AmbientAirTemp` in e.g. tabular dispaly to verify values in the range 20-23 degC as below:
![image](https://github.com/danielhrisca/asammdf/assets/26184427/2eec49fb-ac4a-4686-9409-2217f695164b)

2) Export the single signal to verify that values get exported to CSV correctly

3) Export the full log file with all signals to CSV using Single Time Base and absolute date and time to verify that some values of the `AmbientAirTemp` signal are assigned extreme and invalid values

Log file:
[0000000149.MF4_wheel allignement.zip](https://github.com/danielhrisca/asammdf/files/11790648/0000000149.MF4_wheel.allignement.zip)

**Comment by danielhrisca** [comment]
Hello Martin,

I cannot reproduce the problem with the development branch code

![image](https://github.com/danielhrisca/asammdf/assets/20952040/f864b831-0a71-4195-8e1a-02eaf4998db4)

**Comment by koenvane** [comment]
Thanks for support i wait for solution

**Comment by MatinF** [comment]
Just FYI I tried testing the export on the latest GUI zip release `7.3.3`, though here the problem is still present and it also produces below error. 

```
Error: <class 'TypeError'>	 
finished(int) needs 1 argument(s), 0 given!

Details: 2023-06-21, 08:57:01
--------------------------------------------------------------------------------
<class 'TypeError'>	 
finished(int) needs 1 argument(s), 0 given!
--------------------------------------------------------------------------------
  File "asammdf\gui\utils.py", line 309, in thread_complete

```

If you have a pip freeze I can try with Daniel, then I'll be happy to check out the development version.

**Comment by danielhrisca** [comment]
> If you have a pip freeze I can try with Daniel, then I'll be happy to check out the development version.

https://github.com/danielhrisca/asammdf/actions/runs/5319150244

**Comment by MatinF** [comment]
I tested this now with the dev build and it seems the problem is resolved. Closing this
