### ISSUE TITLE
`extract_bus_logging()` returns an empty MDF when used with CSS Electronics DBC file

### ISSUE THREAD

**Issue by raleighlittles** [danielhrisca/asammdf#871]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
``` 

```
'python=3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]'
'os=Linux-5.19.0-45-generic-x86_64-with-glibc2.35'
'numpy=1.24.3'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.3.12'

```

# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

4.11

  ## Code snippet

```python
import asammdf
mdf = asammdf.MDF("/mnt/shares/canedge_mdf4_files/data/20230619033840_versa.MF4")
databases = {
    "CAN": [("/home/raleigh/github/CanEdge_OBD_Organizer/CSS-Electronics-OBD2-v1.4.dbc", 0), ("/home/raleigh/github/CanEdge_OBD_Organizer/CSS-Electronics-OBD2-Extended-v1.4.dbc", 0)]
}

extracted_mdf = mdf.extract_bus_logging(database_files=databases)
extracted_mdf.to_dataframe()
```

If I then print `extracted_mdf.to_dataframe()`, I get this:

```
Empty DataFrame
Columns: []
Index: []
```
 
  
# Description

I'm trying to use the `extract_bus_logging()` function in conjunction with the DBC file that CSS Electronics provides: https://www.csselectronics.com/pages/obd2-dbc-file

But the resulting MDF created is empty.

Here is the original MF4 file that I'm using (Github doesn't allow uploading of this file type): https://drive.google.com/file/d/1HH8rdoSV9PiId0Lv8ST4UrMJDqTZsW5e/view?usp=sharing

![image](https://github.com/danielhrisca/asammdf/assets/2137201/6a5ecaf1-142e-4ec8-94b3-ee05906f76d7)

**Comment by MatinF** [comment]
Have you checked whether there is indeed OBD2 response data (ID `7e8`) in the raw data? The GUI/API for asammdf works with our OBD2 DBC file, so most likely this is not an issue with the GUI/API, but rather that your car does not respond to the OBD2 requests you're sending, or that the device is not configured for requesting OBD2 data. See the CANedge Intro Record section for details. 

Suggest closing this as I do not believe this is an asammdf problem.

**Comment by raleighlittles** [comment]
@MatinF  You're completely right, thank you; I missed that section of the instructions. Once I actually setup some messages in the config section, that dataframe was no longer empty.


![Screenshot from 2023-07-05 15-32-08](https://github.com/danielhrisca/asammdf/assets/2137201/6551bba3-2437-4966-90e0-82e979dc33e6)
