### ISSUE TITLE
Zoom y-axis not working

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#881]
# Python version
('python=3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19045-SP0'
'numpy=1.25.0'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.3.12'
  
# Description

Hi,
it isn't possible to zoom in / out with mouse wheel. It was working fine in the past. I'm sorry but I cantn't remember, which version of asammdf worked correctly.

Kind regards

**Comment by danielhrisca** [comment]
@stlweb please try the latest release

**Comment by stlweb** [comment]
@danielhrisca  I've tested with 7.3.18 and it is working as expected 
Thanks
