### ISSUE TITLE
Wrong decoding of file with version 7.3.13(correct with version 7.2.0)

### ISSUE THREAD

**Issue by MiroJelev** [danielhrisca/asammdf#884]
# Python version
```('python=3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19045-SP0'
'numpy=1.25.1'
ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.3.13'
```

# Code 
  ## MDF version
4.11

  ## Code snippet

```from asammdf import MDF
mf4 = MDF(input_file)
decoded_mf4 = mf4.extract_bus_logging({"CAN": [(dbc_file, 0)]})
decoded_mf4.save(decoded_file, overwrite=True, compression=0)
```

## Traceback

# Description
With version 7.3.13(in red) of asammdf the MF4 file is incorrectly interpreted for signals of 1000Hz.  
 - The values jump from zero to max as can be seen on the graph. 
 - Some values are represented correctly(maybe non-zero ones?).
 - There are no negative values.

For version 7.2.0(in blue) of asammdf the file is interpreted correctly as seen on the screenshot.

<img width="1361" alt="screenshot" src="https://github.com/danielhrisca/asammdf/assets/61290340/a9773ad1-0c83-4467-9f38-e0843f1d2785">

**Comment by danielhrisca** [comment]
@MiroJelev please try the development branch code
