### ISSUE TITLE
`pip install asammdf[gui]` is not recognized

### ISSUE THREAD

**Issue by Mastermind497** [danielhrisca/asammdf#886]
# Python version
Tested on:
 - 3.11.4
 - 3.9.13

# Description

No matter what i do, whenever I attempt to run `pip install asammdf[gui]` like it says in the docs, I keep getting the following error message (tried with multiple different python version)

![image](https://github.com/danielhrisca/asammdf/assets/39387439/6c267498-dc07-49d6-aa14-0d2ff9ba51b7)

**Comment by danielhrisca** [comment]
Are you running on 64 bit python?

**Comment by Mastermind497** [comment]
I am running 64 bit python, but on a Linux system. Is the GUI available only on windows?

**Comment by steinhae** [comment]
I had the same problem and solved it by using
`pip install "asammdf[gui]"`
