### ISSUE TITLE
Not able to read Mat file

### ISSUE THREAD

**Issue by az299260** [danielhrisca/asammdf#892]
'python=3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) 
[MSC v.1929 64 bit '
'(AMD64)]'
'os=Windows-10-10.0.22621-SP0'
'numpy=1.21.2'
'asammdf=6.4.4'

# Description
I have a mat file and i'm able to read it via python, but facing difficulties in resampling the data.
Earlier i was able to resample in mdf file from asammdf but now i have a mat file.

It'll be helpfull if i can either read mat files form asammdf to write it to mdf
or
can i directly resample mat file after reading into asammdf

**Comment by danielhrisca** [comment]
There is no mat read support, just the 3xport is available

**Comment by az299260** [comment]
Is there any plan to add mat read support or other way you are aware of converting mat to mdf? because i'm facing difficulties in resampling the signals after reading mat file in python

**Comment by danielhrisca** [comment]
There is no plan to add `.mat` read support
