### ISSUE TITLE
Copied data values from tabular display includes header

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#897]
Tested in `asammdf 7.3.13.dev9`.

**Expected behavior**
When copying a data value from the tabular display, I would expect to get that data value only when pasting it - ideally as a trimmed string/value.

**Observed behavior**
Instead, copying e.g. a CAN ID value from a raw CAN bus trace returns the below:
```
         ID
6  18DAF115
```
In other words, both the column and row index is included as well. This is in practice not very useful for quick copy/paste action of single values. Suggest changing at least the behavior for single value copy/paste to be the cell value only.

**Comment by MatinF** [comment]
Note that this still seems to be an issue in `v7.3.16`

**Comment by danielhrisca** [comment]
@MatinF please try the development branch code

**Comment by MatinF** [comment]
Thanks Daniel, this is fixed in the dev
