### ISSUE TITLE
Use pandas' Series class for the Signal class

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#9]
This issue is an idea actually: why not inherit pandas' Series class for the Signal class?

If you don't already know what is a Series in pandas, see here: http://pandas.pydata.org/pandas-docs/stable/timeseries.html

I think the benefit of using pandas' Series, is that it is already known by many users and it would make all methods from Series already available to manipulate a Signal object.

**Comment by jed-frey** [comment]
Is all MDF data known to be time series? . For example in engines we used angle series. I don't know the spec well enough to know if it calls out other series types. (And I don't think my company has paid to read it).

If so, not reinventing the wheel always makes for less work.

**Comment by danielhrisca** [comment]
Hello Julien,

I've looked for a good solution for handling signals in the time domain. 

Pandas series only works if all your channels have the same timebase, and most of the times you will have channels acquired at different rates from different sources.

Please consider this scenario:
``` python
from pandas import Series
from asammdf import Signal
import numpy
numpy.set_printoptions(threshold=numpy.nan)

df1 = {'t': [0.1*x for x in range(10)],
       'vals' : [3 for x in range(10)]}

df2 = {'t': [0.1*x + 0.05 for x in range(10)],
       'vals' : [3 for x in range(10)]}

S1 = Series(df1['vals'], df1['t'])
S2 = Series(df2['vals'], df2['t'])

print("Pandas Series add", S1.add(S2), sep='\n')

S1 = Signal(df1['vals'], df1['t'], name='s1')
S2 = Signal(df2['vals'], df2['t'], name='s2')

print('\n')

print("asammdf Signal add", S1 + S2, sep='\n')
```
this prints
```python
Pandas Series add
0.00   NaN
0.05   NaN
0.10   NaN
0.15   NaN
0.20   NaN
0.25   NaN
0.30   NaN
0.35   NaN
0.40   NaN
0.45   NaN
0.50   NaN
0.55   NaN
0.60   NaN
0.65   NaN
0.70   NaN
0.75   NaN
0.80   NaN
0.85   NaN
0.90   NaN
0.95   NaN
dtype: float64


asammdf Signal add
Signal { name="s1":	s=[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]	t=[ 0.    0.05  0.1   0.15  0.2   0.25  0.3   0.35  0.4   0.45  0.5   0.55
  0.6   0.65  0.7   0.75  0.8   0.85  0.9   0.95]	unit=""	conversion=None }
```

From my point of view that the _Signal_ code is more natural to use and provides sane results.

**Comment by JulienGrv** [comment]
Ok, I see your point here. A solution could be to inherit from Series and overwrite the add method with yours, this will solve this problem.

Btw, the problem is caused by the floating point precision. 0.00 != 0.0 for pandas add, so it returns NaN instead of 6.

**Comment by danielhrisca** [comment]
Actually the timestamps are completely different
```
t1 = [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9]
t2 = [0.05, 0.15000000000000002, 0.25, 0.35000000000000003, 0.45, 0.55, 0.6500000000000001, 0.7500000000000001, 0.8500000000000001, 0.9500000000000001]
```
This cannot be handled by the pandas Series.

**Comment by JulienGrv** [comment]
Ok let's close this issue for now :)
