### ISSUE TITLE
Unable to install asammdf library

### ISSUE THREAD

**Issue by dhiraj797** [danielhrisca/asammdf#900]
#Unable to install the asammdf library
# Python version
3.6.3

#numpy version
1.19.5

# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  Building wheel for lz4 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\knr2ban\.conda\envs\rv\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\knr2ban\\AppData\\Local\\Temp\\pip-install-xw6rq3b7\\lz4_db1435e7169840c5857e89ae0d6fa66b\\setup.py'"'"'; __file__='"'"'C:\\Users\\knr2ban\\AppData\\Local\\Temp\\pip-install-xw6rq3b7\\lz4_db1435e7169840c5857e89ae0d6fa66b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\knr2ban\AppData\Local\Temp\pip-wheel-ytml41ad'
       cwd: C:\Users\knr2ban\AppData\Local\Temp\pip-install-xw6rq3b7\lz4_db1435e7169840c5857e89ae0d6fa66b\
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\lz4
  copying lz4\version.py -> build\lib.win-amd64-3.6\lz4
  copying lz4\__init__.py -> build\lib.win-amd64-3.6\lz4
  creating build\lib.win-amd64-3.6\lz4\block
  copying lz4\block\__init__.py -> build\lib.win-amd64-3.6\lz4\block
  creating build\lib.win-amd64-3.6\lz4\frame
  copying lz4\frame\__init__.py -> build\lib.win-amd64-3.6\lz4\frame
  creating build\lib.win-amd64-3.6\lz4\stream
  copying lz4\stream\__init__.py -> build\lib.win-amd64-3.6\lz4\stream
  running build_ext
  building 'lz4._version' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for lz4
  Running setup.py clean for lz4
Failed to build lz4
Installing collected packages: lz4, asammdf
    Running setup.py install for lz4 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\knr2ban\.conda\envs\rv\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\knr2ban\\AppData\\Local\\Temp\\pip-install-xw6rq3b7\\lz4_db1435e7169840c5857e89ae0d6fa66b\\setup.py'"'"'; __file__='"'"'C:\\Users\\knr2ban\\AppData\\Local\\Temp\\pip-install-xw6rq3b7\\lz4_db1435e7169840c5857e89ae0d6fa66b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\knr2ban\AppData\Local\Temp\pip-record-diyl4hr3\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\knr2ban\.conda\envs\rv\Include\lz4'
         cwd: C:\Users\knr2ban\AppData\Local\Temp\pip-install-xw6rq3b7\lz4_db1435e7169840c5857e89ae0d6fa66b\
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\lz4
    copying lz4\version.py -> build\lib.win-amd64-3.6\lz4
    copying lz4\__init__.py -> build\lib.win-amd64-3.6\lz4
    creating build\lib.win-amd64-3.6\lz4\block
    copying lz4\block\__init__.py -> build\lib.win-amd64-3.6\lz4\block
    creating build\lib.win-amd64-3.6\lz4\frame
    copying lz4\frame\__init__.py -> build\lib.win-amd64-3.6\lz4\frame
    creating build\lib.win-amd64-3.6\lz4\stream
    copying lz4\stream\__init__.py -> build\lib.win-amd64-3.6\lz4\stream
    running build_ext
    building 'lz4._version' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\knr2ban\.conda\envs\rv\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\knr2ban\\AppData\\Local\\Temp\\pip-install-xw6rq3b7\\lz4_db1435e7169840c5857e89ae0d6fa66b\\setup.py'"'"'; __file__='"'"'C:\\Users\\knr2ban\\AppData\\Local\\Temp\\pip-install-xw6rq3b7\\lz4_db1435e7169840c5857e89ae0d6fa66b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\knr2ban\AppData\Local\Temp\pip-record-diyl4hr3\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\knr2ban\.conda\envs\rv\Include\lz4' Check the logs for full command output.
  
# Description

Unable to install asammdf library

**Comment by danielhrisca** [comment]
@dhiraj797 the latest asammdf is supported for 64 bit Python >= 3.8
