### ISSUE TITLE
Long channelnames get cut on save()

### ISSUE THREAD

**Issue by Ruudii8** [danielhrisca/asammdf#91]
# Python version
'python=2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]'
'os=Windows-10-10.0.15063'
'numpy=1.15.0'
'asammdf=4.0.0.dev'
  
# Description
Long channelnames get cut if I save the file (even without modifications). Seems like maximum length for a channelname is 32 characters?
Is this a wrong configuration or missing parameter or a restriction in your code?

**Comment by danielhrisca** [comment]
Hello @Ruudii8,
 I suspect you use mdf v3. The spec says that the short name should be a 0 terminated 32 char string. I the channel name is >= 32 chars there should be a text block referenced by the long name address 

![image](https://user-images.githubusercontent.com/20952040/45022165-35af3000-b03c-11e8-80c2-247a9fdbe540.png)

Is this the case for you, or do you have some other issue?

**Comment by Ruudii8** [comment]
Yes, seems like this is the origin of the problem.
I need to read files, add some channels and save it. But it seems that there the long name gets lost.

I compared a channel with a long name from the original file and the saved one.

original one:
name: 'long name'
long_name_addr: 123456
short_name: 'short name'

saved one:
name: 'short name'
long_name_addr: 0
short_name: 'short name'

Shouldn't the reader also write a 'long_name_addr' and the long name as 'name'?

**Comment by danielhrisca** [comment]
There is no need to waste space if the full channel name fits in 31 chars. Long channel names are not mandatory in the specification.

**Comment by Ruudii8** [comment]
Unfortunately I need to work with channel names that are longer than 31 chars. 
So there is no possibility to write long channel names with the mdf reader?

**Comment by Ruudii8** [comment]
When I'm running the same code as you the TextBlock and long channelname is missing.
Tried on asammdf Version 3.5 and 4.0.0.dev.

Imageupload is not working at the moment, but MDF Validator says 'string is  not zero terminated' at cn_name. cn_tx_longname and cn_tx_displayname have 0x0000 as value

**Comment by danielhrisca** [comment]
I've found an error in the header block writing. I'm not sure how that impacted the channel names, but it seems to work now. Please check with the development branch code.

**Comment by Ruudii8** [comment]
It's working now.
Thanks for the fast help, you're awesome :) 👍
