### ISSUE TITLE
Disabled channels disappearing from plot when new ones added

### ISSUE THREAD

**Issue by Bill-Davis-Vonnen** [danielhrisca/asammdf#914]
# Python version
_Please run the following snippet and write the output here_
('python=3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.22621-SP0'
'numpy=1.21.2'
'asammdf=6.4.0'
--> I'm actually using 7.2.0 but 6.4.0 is still installed.

  
# Description

When I have any signals in the display plot disabled (unchecked), and then I drag new signals into the plot, all disabled signals disappear.  The only work around I've found is to make sure I enable everything before adding new stuff, but I often forget and then curse that I have to start over to get the plot where I want it.  Is there some secret way to make everything show? Or do later versions fix this bug? 

In pictures: 
1) 4 channels plotted
2) 2 disabled
3) 2 more channels dragged in
4) disabled channels have disappeared

![asammdf issue-1](https://github.com/danielhrisca/asammdf/assets/54862065/1745bbeb-fbfe-45fe-bc2b-077f23207b27)
![asammdf issue-2](https://github.com/danielhrisca/asammdf/assets/54862065/12d32ed8-46c5-4787-928a-816e03917203)
![asammdf issue-3](https://github.com/danielhrisca/asammdf/assets/54862065/4956e289-4d65-4bf1-b5e7-f8531d38830f)
![asammdf issue-4](https://github.com/danielhrisca/asammdf/assets/54862065/869df533-23a2-475a-b0b3-3a513a3f3fc4)

**Comment by danielhrisca** [comment]
This is caused by the `Hide disabled channels` option. The actual problem is that you have this enabled and the channels are not hidden right away after being disabled

![hide](https://github.com/danielhrisca/asammdf/assets/20952040/16402cfc-96a9-4bfb-b4a3-2af9b839a425)

**Comment by Bill-Davis-Vonnen** [comment]
Thanks. That's a great feature.  I wish I realized it was there sooner!
