### ISSUE TITLE
read xcp error

### ISSUE THREAD

**Issue by zkailinzhang** [danielhrisca/asammdf#915]
run data = asammdf.MDF(file, 'r'), error follow

error with line no: 1963
b'BA_ "ILused" BU_ PAS 1;\r\n'
error with line no: 1964
b'BA_ "NmAsrNode" BU_ PAS 1;\r\n'
error with line no: 1965
b'BA_ "NmAsrNodeIdentifier" BU_ PAS 40;\r\n'
error with line no: 1966
b'BA_ "NodeLayerModules" BU_ PAS "CANoeILNLSPA.dll,AsrNM33.dll";\r\n'
error with line no: 1968
b'BA_ "ILused" BU_ PSCM1 1;\r\n'
error with line no: 1969
b'BA_ "NmAsrNode" BU_ PSCM1 1;\r\n'
error with line no: 1970
b'BA_ "NmAsrNodeIdentifier" BU_ PSCM1 35;\r\n'
error with line no: 1971
b'BA_ "NodeLayerModules" BU_ PSCM1 "CANoeILNLSPA.dll,AsrNM33.dll";\r\n'
error with line no: 1973
b'BA_ "ILused" BU_ RBCM 1;\r\n'
error with line no: 1974
b'BA_ "NmAsrNode" BU_ RBCM 1;\r\n'
error with line no: 1975
b'BA_ "NmAsrNodeIdentifier" BU_ RBCM 53;\r\n'
error with line no: 1976
b'BA_ "NodeLayerModules" BU_ RBCM "CANoeILNLSPA.dll,AsrNM33.dll";\r\n'
error with line no: 1978
b'BA_ "ILused" BU_ SAS 1;\r\n'
error with line no: 1979
b'BA_ "NmAsrNode" BU_ SAS 1;\r\n'
error with line no: 1980
b'BA_ "NmAsrNodeIdentifier" BU_ SAS 39;\r\n'
error with line no: 1981
b'BA_ "NodeLayerModules" BU_ SAS "CANoeILNLSPA.dll,AsrNM33.dll";\r\n'
error with line no: 1983
b'BA_ "ILused" BU_ VDDM 1;\r\n'
error with line no: 1984
b'BA_ "NmAsrNode" BU_ VDDM 1;\r\n'
error with line no: 1985
b'BA_ "NmAsrNodeIdentifier" BU_ VDDM 33;\r\n'
error with line no: 1986

**Comment by danielhrisca** [comment]
@zkailinzhang  please provide more details
