### ISSUE TITLE
populate DataGroup and Channel Group fields

### ISSUE THREAD

**Issue by nos86** [danielhrisca/asammdf#92]
Hi @danielhrisca,
first of all, I'd like to congrat with you (and the team) about the amazing library you have created.
Library is very powerful and fast, unfortunately the documentation has some missing parts.

I'm currently using the programmatic interface and, on the current job, I need to create an MDF4 starting from several Pandas Dataframes. This file has to have a specific structure in terms of DataGroup and Channel Group with populated fields (like cg_tx_acq_name).
Can you help me to understand how I can set those fields in python scripts?

If it's easier, an example is enough to understand.

Thanks in advance,
Salvo

**Comment by danielhrisca** [comment]
Hello Salvo,

I must admit that appending does not expose all those fields in the method call. You can however set them on the ChannelGroup object (https://asammdf.readthedocs.io/en/development/v4blocks.html#asammdf.v4_blocks.ChannelGroup) afterwards, before saving

```python
from asammdf import MDF, Signal

mdf = MDF(version='4.10')

sig = Signal(
    name='S1',
    samples=[1,2,3],
    timestamps=[0.1, 0.15, 0.2],
)

mdf.append(sig)

mdf.groups[-1]['channel_group'].acq_name = 'custom name'

mdf.save('test.mf4', overwrite=True)
```

![image](https://user-images.githubusercontent.com/20952040/45080836-740d2380-b0fe-11e8-903a-1323395eb624.png)

**Comment by nos86** [comment]
Super..! It works perfectly.
Thank you so much for the prompt feedback.

**Comment by danielhrisca** [comment]
I've added the option to append a DataFrame to MDF v4. Could you give it a try?

```python
mdf = MDF(version='4.10')

# prepare a pandas DataFrame (df)

mdf.append(df)

# ...
```

**Comment by nos86** [comment]
Seems very interesting and powerful, but how I can set the unit for each channel?

**Comment by nos86** [comment]
Great..!
My best compliments for your work.

Salvo
