### ISSUE TITLE
J1939 DBC: Support vFrameFormat default value

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#927]
In the DBC file format, it is possible to define 'default' values for various attributes, incl. `vFrameFormat`. In the case of a J1939 DBC file, this can be used to specify that all messages are to be interpreted as `J1939PG` with a single line.

However, asammdf currently only looks at individual ID-by-ID `vFrameFormat` lines, ignoring the default value. As a result, setting only the default value of `vFrameFormat` to `J1939PG` implies that all IDs are treated as regular 29-bit extended IDs, instead of being interpreted via PGN decoding. 

This would be nice to change to adhere to the DBC standard, but also to ensure that it's possible to create 'light' DBC files for faster decoding purposes.

**Comment by danielhrisca** [comment]
@MatinF please provide an example DBC

**Comment by MatinF** [comment]
This is resolved in the latest development version, thanks Daniel - would be great with a 7.3.17 release as it resolves a lot of the outstanding issues :-)
