### ISSUE TITLE
Unable to save string channel when MDF is compressed

### ISSUE THREAD

**Issue by nos86** [danielhrisca/asammdf#93]
# Python version: 
```python
import numpy as np
import asammdf

mdf = asammdf.MDF4(memory='full')

# string channel
sig = asammdf.Signal(
    np.array(['test'.encode('ascii')]),
    [0],
    name='Channel_string',
    comment='String channel',
)
mdf.append([sig])

mdf.save('data\\no_compression.mf4', overwrite=True, compression=False)
mdf.save('data\\with_compression.mf4', overwrite=True, compression=True)
```
# Code 

## MDF version 4.10

# Description
Hi daniel,
using the example supplied above, the both MDF has the channel inside, but in the compressed file, value disappears. Is it a bug or I'm doing something wrong?

For your convenience, I'm going to attach the generated files.

Thanks for your work,
Salvo

[compressionIssue.zip](https://github.com/danielhrisca/asammdf/files/2427253/compressionIssue.zip)

**Comment by danielhrisca** [comment]
Hello Salvo,

I will have time to investigate this on Sunday.

**Comment by danielhrisca** [comment]
Please re-open if the fix is not working for you
