### ISSUE TITLE
mdf.to_dataframe(list of signals)

### ISSUE THREAD

**Issue by Tamimi123600** [danielhrisca/asammdf#935]
I have got an mf4 file. From which i am trying to extract certain signals and then create a dataframe out of those signals. Extract_signals is a list of signals i which to extract. When i apply 'mdf.to_dataframe(extract_signals)', there is a signal that doesnt appear in the dataframe. 

The description of the signal is as follows: 
Signal Name <Signal XXHsymeetr_Rq:
	samples=[0 0 0 ... 0 0 0]
	timestamps=[1.0000e-02 2.0000e-02 3.0000e-02 ... 3.8149e+02 3.8150e+02 3.8151e+02]
	invalidation_bits=[ True  True  True ...  True  True  True]
	unit=""
	conversion=None
	source=None
	comment="<CNcomment xmlns="http://www.asam.net/mdf/v4"><TX>PHB_ILS_Fan_Rq</TX><raster>0.100000</raster></CNcomment>"
	flags="0"
	mastermeta="('TIME', 1)"
	raw=False
	display_names={}
	attachment=None>

I searched a bit for it and it seems its not appearing in the dataframe because of the 'invalidation_bits' parameter from the output. Within the asammdf documentation, to change that and allow the signal 'PHB...' to appear in the dataframe, I must add a parameter: mdf.to_dataframe(extract_signals, empty_channels='zeros'). After running this line of code, that signal appeared in the dataframe. But that just means that any empty channels should be filled with zero. And PHB_ILS_Fan_Rq is not empty as you can see above. 
  

Is there a better explanation or understanding for this issue. 
Thanks

**Comment by danielhrisca** [comment]
If the invalidation_bits element index `i` is true then `PHB_ILS_Fan_Rq.samples[i]` is not valid (the recording tool decides to set this information) and is ignored. In you case all the samples are invalid so you end up with an empty array

**Comment by Tamimi123600** [comment]
Thanks daniel for your prompt reply.
I have two follow up questions. 

1. When i check the signal 'PHB_ILS_Fan_Rq' on gui.exe. I can see values of the signal. Which is the list of zeros above. Is that just by default? 

2. To insert the signal into the dataframe, was the parameter i inserted correct

Thanks

**Comment by danielhrisca** [comment]
Do you see the values in a tabular window?

**Comment by Tamimi123600** [comment]
Yes, next to each timestamp is zero. Just like below here:
Signal Name <Signal PHB_ILS_Fan_Rq:
samples=[0 0 0 ... 0 0 0]

**Comment by danielhrisca** [comment]
The tabular window is build using `mdf.to_dataframe(extract_signals, empty_channels='zeros')` in the background. It's just a concidence that the raw channel values are also 0 in your case. 

If you would load the channel in a Plot window you would see it has no samples

**Comment by Tamimi123600** [comment]
Thanks daniel for your time
