### ISSUE TITLE
Couldn't create a new Attribute for common properties in Headed md_comment

### ISSUE THREAD

**Issue by saideepthik** [danielhrisca/asammdf#937]
in my script  would like to access like this
new_mdf.header.loggername= 'XYZ'

changes made to library to create a new attribute: 
In v4_blocks:
@property
    def loggername(self):
        return self._common_properties.get("loggername", "")

    @loggername.setter
    def loggername(self, value):
        self._common_properties["loggername"] = value

v4_constants:
HD_COMMENT_TEMPLATE = """<HDcomment>
<TX>{}</TX>
<common_properties>
    <e name="author">{}</e>
    <e name="department">{}</e>
    <e name="project">{}</e>
    <e name="subject">{}</e>
    <e name="loggername">{}</e>
</common_properties>
</HDcomment>"""

in v2_v3_blocks.py:
added the feild to headerblock initialization
self.loggername_field,
 and also setter
@property
    def loggername(self):
        return self._common_properties.get("loggername", "")

    @loggername.setter
    def loggername(self, value):
        self._common_properties["loggername"] = value

And to_blocks() added the variable
self.loggername_field = self.loggername.encode("latin-1")

mdf.py: Header items:
"loggername_field"

I'm not finding where would i miss something to add and make of this new attribute in HD_Comment. 

Please enlighten me with your inputs.
Useful answers are much appreciated.

**Comment by saideepthik** [comment]
![image](https://github.com/danielhrisca/asammdf/assets/34998473/004bb587-0dee-4cff-9a28-b6f64b783c5b)

**Comment by danielhrisca** [comment]
It is enough to set the key and value to `_common_properties` 

Please give more details

**Comment by saideepthik** [comment]
May i know which details are you looking for? Please!

**Comment by saideepthik** [comment]
I resolved the issue thanks!
