### ISSUE TITLE
Pandas export

### ISSUE THREAD

**Issue by nos86** [danielhrisca/asammdf#94]
# Code 

  ## MDF version
4.10

  ## Code snippet
```python
import asammdf

m = asammdf.MDF('measure.mf4', memory='full')
m.export('pandas')
```
  
  ## Traceback
```python
Must specify filename for exportif MDF was created without a file name
Traceback (most recent call last):

  File "<ipython-input-91-2a7904dd38e3>", line 3, in <module>
    a.export('pandas').set_index('time')

AttributeError: 'NoneType' object has no attribute 'set_index
```

# Description

Hi Daniel (again),

I'd like to highlight you a minor issue I found today. When you use the export command for a pandas conversion, it requires to have a filename that will be not used because the dataframe will be returned as output of the function. My suggestion is to skip the parameter check if fmt == "pandas".

The current workaround, I'm using is:
```python
m.export('pandas', filename='dummy')
```

**Comment by danielhrisca** [comment]
Thank you, I will include this fix

**Comment by danielhrisca** [comment]
Please re-open if the fix is not working for you
