### ISSUE TITLE
Cannot search signal names from a dat file 

### ISSUE THREAD

**Issue by sanilogc2122** [danielhrisca/asammdf#940]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._
![image](https://github.com/danielhrisca/asammdf/assets/127383217/dd8aabd6-44f9-4c7d-95f1-39d67d024952)

**Comment by danielhrisca** [comment]
Which asammdf version do you use?

**Comment by sanilogc2122** [comment]
version : asammdf 7.2.0


Thanks,

Sanil Mhatre



[cid:ea470f6c-4d14-4545-b2b9-0fd73dbfd13f]   https://www.hyliion.com/

The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.



________________________________

**Comment by danielhrisca** [comment]
Try the latest release
