### ISSUE TITLE
bad result for value to text/scale conversion

### ISSUE THREAD

**Issue by chen-jin-jc** [danielhrisca/asammdf#946]
# Python version

> 'python=3.8.10 (default, Jul 27 2023, 21:46:20) \n[GCC 9.4.0]'
'os=Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5'
'numpy=1.24.3'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.3.18'

# Code 

  ## MDF version
4.00

  ## Code snippet
https://github.com/danielhrisca/asammdf/blob/d06645eb6d782836750396c66e6263d26fc724a9/src/asammdf/blocks/v4_blocks.py#L3423C25-L3423C29
  
  ## Traceback
bad result for value to text/scale conversion tabular look-up
  
# Description
```            all_bytes = True
              for v in ret.tolist():
                  if not isinstance(v, bytes):
                      all_bytes = False
                      break

              if not all_bytes:
                  try:
                      ret = ret.astype("f8")
                  except:
                      if as_bytes:
                          ret = ret.astype(bytes)
                      elif not as_object:
                          ret = np.array([np.nan if isinstance(v, bytes) else v for v in ret.tolist()])
              else:
                  ret = ret.astype(bytes)
```

for the value to text conversion, the above logic is first trying to convert the value to float, if at least one value is bytes, the conversion failed, and it will try to replace all bytes value with np.nan, there is also a similar issue mentioned here #770.
with asammdf 7.1.x, we could get the bytes array instead of array with [np.nan ...]
for value to text/scale conversion, i would expect to have a safe strategy, is that the case we can cover more case if we try bytes first?

**Comment by danielhrisca** [comment]
set `all_bytes=True`

**Comment by chen-jin-jc** [comment]
thanks for the hint, 
i didn't find the way to configure the `get` or `select` to use `all_bytes=True` , or you mean to set the `as_bytes` for `convert` 
but here https://github.com/danielhrisca/asammdf/blob/d06645eb6d782836750396c66e6263d26fc724a9/src/asammdf/blocks/mdf_v4.py#L6588C28-L6588C38
shows the convert will use the default value `as_bytes=False`

**Comment by chen-jin-jc** [comment]
the look up of a CCBLOCK of "value to text/scale" can contain only TXBLOCK (string) or CCBLOCK (string or float)
maybe in `convert` we can check the ref_link type, only if all the ref_link are scale conversion, we should try "float", otherwise by mixed conversion type, bytes should be better

**Comment by danielhrisca** [comment]
You can call `select` with raw=True, then use the conversion attribute

ch.conversion.convert(ch.samples, as_bytes=True)

**Comment by chen-jin-jc** [comment]
that could be one option to use, but the problem for me is, if i use `select` and give different `record_offset` `record_count`, `select` will return different dtypes of signal.
according to specification, if cc_flag bit 2 is set, the look up must be point to a TXBLOCK (which is string), only the default conversion could be scale.
one suggestion could be
`
all_bytes = True
if not self.flags & 4: # bit2 => Status String
    for v in ret.tolist():
        if not isinstance(v, bytes):
            all_bytes = False
            break
if not all_bytes:
    try:
        ret = ret.astype("f8")
    except:
        if as_bytes:
            ret = ret.astype(bytes)
        elif not as_object:
            ret = np.array([np.nan if isinstance(v, bytes) else v for v in ret.tolist()])
else:
    ret = ret.astype(bytes)
`
the `for loop` to detect all bytes could be also improved by checking conversion type of each CCBLOCK, but CCBLOCK could contain a chain of conversion, i am not sure how to handle the chain.

**Comment by AndreiJurj12** [comment]
Hello, I have added here one simple file for reference/demonstration.
[example_conversion_file.zip](https://github.com/danielhrisca/asammdf/files/13597676/example_conversion_file.zip)

7.0.2 outputs for the channel: "Value 1", "Value 1", 13.5, "Value 1", "Value 1"
7.3.17 outputs for the channel: NaN, NaN, 13.5, NaN, NaN
I would upload a demonstration image, but for some strange reason it doesn't work. I am really wondering whether really the last behaviour is desired vs the first as we are losing a lot of information with the default way of acquiring the signal data.

**Comment by danielhrisca** [comment]
@AndreiJurj12 

```python
m = MDF(r'example_conversion_file.mf4')
c = m.get('converted_channel', raw=True)
print(c.conversion.convert(c.samples, as_bytes=True))
print(c.conversion.convert(c.samples, as_bytes=False))
```

prints

```
[b'Value 1' b'Value 1' b'13.5' b'Value 1' b'Value 1']
[ nan  nan 13.5  nan  nan]
```
