### ISSUE TITLE
Header comment XML string is unformatted

### ISSUE THREAD

**Issue by Orbinaut42** [danielhrisca/asammdf#949]
# Python version
('python=3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.25.0'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.3.12'
  
# Description

In newer versions of asammdf, the "HDcomment" XML tag in the comment property of the header block is created as a single line without line breaks and indents. This makes it hard to read in some file viewers, including the asammdf GUI, especially if you add some additional tags. Other XML comments like the file history comment include line breaks. Also the header comment in files created with other programs e.g. Vector Canoe includes line brakes and indents.

Can we have the header comment XML string to include line breaks and indents?

**Comment by danielhrisca** [comment]
@Orbinaut42 please try the development branch code

**Comment by Orbinaut42** [comment]
Perfect, thank you!
