### ISSUE TITLE
README link updates

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#951]
Hi Daniel,

It looks like some of the links from the README to our pages need to be updated:

https://canlogger.csselectronics.com/canedge-getting-started/log-file-tools/asammdf-api/
--> should be https://canlogger.csselectronics.com/canedge-getting-started/ce3/log-file-tools/asammdf-gui/

https://canlogger.csselectronics.com/canedge-getting-started/log-file-tools/asammdf-gui/
--> https://canlogger.csselectronics.com/canedge-getting-started/ce3/log-file-tools/asammdf-gui/

**Comment by travis2319** [comment]
I am willing to contribute
![Screenshot 2024-02-06 210412](https://github.com/danielhrisca/asammdf/assets/41868352/d5b8a012-d89d-4a00-97f6-5073c45eb504)

**Comment by travis2319** [comment]
done!!
