### ISSUE TITLE
Python 3.12 install error

### ISSUE THREAD

**Issue by pepo83** [danielhrisca/asammdf#953]
Hello, I get the following error when I try to install asammdf:

Microsoft Windows [Version 10.0.19045.3570]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\WINDOWS\system32>pip install asammdf
Collecting asammdf
  Using cached asammdf-7.3.18.tar.gz (743 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting canmatrix>=1.0 (from canmatrix[arxml,dbc]>=1.0->asammdf)
  Using cached canmatrix-1.0-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting lz4 (from asammdf)
  Using cached lz4-4.3.2.tar.gz (170 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numexpr (from asammdf)
  Using cached numexpr-2.8.7-cp312-cp312-win_amd64.whl.metadata (8.9 kB)
Requirement already satisfied: numpy>=1.23.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from asammdf) (1.26.2)
Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from asammdf) (2.1.3)
Collecting typing-extensions (from asammdf)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: python-dateutil in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from asammdf) (2.8.2)
Collecting lxml>=4.9.3 (from asammdf)
  Using cached lxml-4.9.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Collecting isal (from asammdf)
  Using cached isal-1.5.2-cp312-cp312-win_amd64.whl.metadata (10 kB)
Collecting attrs>=19.2.0 (from canmatrix>=1.0->canmatrix[arxml,dbc]>=1.0->asammdf)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting click (from canmatrix>=1.0->canmatrix[arxml,dbc]>=1.0->asammdf)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting future (from canmatrix>=1.0->canmatrix[arxml,dbc]>=1.0->asammdf)
  Using cached future-0.18.3-py3-none-any.whl
Requirement already satisfied: six in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from canmatrix>=1.0->canmatrix[arxml,dbc]>=1.0->asammdf) (1.16.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pandas->asammdf) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pandas->asammdf) (2023.3)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from click->canmatrix>=1.0->canmatrix[arxml,dbc]>=1.0->asammdf) (0.4.6)
Using cached canmatrix-1.0-py2.py3-none-any.whl (322 kB)
Using cached lxml-4.9.3-cp312-cp312-win_amd64.whl (3.8 MB)
Using cached isal-1.5.2-cp312-cp312-win_amd64.whl (198 kB)
Using cached numexpr-2.8.7-cp312-cp312-win_amd64.whl (95 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Building wheels for collected packages: asammdf, lz4
  Building wheel for asammdf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for asammdf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [179 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\asammdf
      copying src\asammdf\mdf.py -> build\lib.win-amd64-cpython-312\asammdf
      copying src\asammdf\signal.py -> build\lib.win-amd64-cpython-312\asammdf
      copying src\asammdf\tool.py -> build\lib.win-amd64-cpython-312\asammdf
      copying src\asammdf\types.py -> build\lib.win-amd64-cpython-312\asammdf
      copying src\asammdf\version.py -> build\lib.win-amd64-cpython-312\asammdf
      copying src\asammdf\__init__.py -> build\lib.win-amd64-cpython-312\asammdf
      creating build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\bus_logging_utils.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\conversion_utils.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\mdf_common.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\mdf_v2.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\mdf_v3.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\mdf_v4.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\options.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\source_utils.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\utils.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\v2_v3_blocks.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\v2_v3_constants.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\v4_blocks.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\v4_constants.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\blocks\__init__.py -> build\lib.win-amd64-cpython-312\asammdf\blocks
      creating build\lib.win-amd64-cpython-312\asammdf\gui
      copying src\asammdf\gui\asammdfgui.py -> build\lib.win-amd64-cpython-312\asammdf\gui
      copying src\asammdf\gui\plot.py -> build\lib.win-amd64-cpython-312\asammdf\gui
      copying src\asammdf\gui\utils.py -> build\lib.win-amd64-cpython-312\asammdf\gui
      copying src\asammdf\gui\__init__.py -> build\lib.win-amd64-cpython-312\asammdf\gui
      creating build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\advanced_search.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\advanced_search_helpers.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\bus_database_manager.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\channel_group_info.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\channel_info.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\conversion_editor.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\define_channel.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\dependencies_dlg.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\error_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\functions_manager.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\gps_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\messagebox.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\multi_search.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\range_editor.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\simple_search.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\window_selection_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      copying src\asammdf\gui\dialogs\__init__.py -> build\lib.win-amd64-cpython-312\asammdf\gui\dialogs
      creating build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\attachment.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\bar.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\batch_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\bus_database_manager.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_bar_display_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_group_info_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_info_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_stats.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\database_item.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\define_channel_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\define_conversion_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\error_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\fft_window.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\file_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\functions_manager.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\gps.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\gps_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\main_window.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\multi_search_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\numeric_offline.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\range_editor_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\range_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\resource_rc.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\search_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\signal_scale.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\simple_search_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\tabular.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\tabular_filter.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\vrtt_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\vtt_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\windows_selection_dialog.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\__init__.py -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      creating build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\attachment.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\bar.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\batch.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\bus_database_manager.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\can_bus_trace.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\channel_bar_display.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\channel_group_info.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\channel_info.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\channel_stats.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\collapsiblebox.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\cursor.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\database_item.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\dict_to_tree.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\fft_window.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\file.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\flexray_bus_trace.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\formated_axis.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\functions_manager.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\gps.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\lin_bus_trace.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\list.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\list_item.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\loader.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\main.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\mdi_area.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\numeric.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\plot.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\plot_standalone.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\python_highlighter.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\range_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\search.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\signal_scale.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\tabular.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\tabular_base.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\tabular_filter.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\tree.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\tree_item.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\viewbox.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\vrtt_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\vtt_widget.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      copying src\asammdf\gui\widgets\__init__.py -> build\lib.win-amd64-cpython-312\asammdf\gui\widgets
      running egg_info
      writing src\asammdf.egg-info\PKG-INFO
      writing dependency_links to src\asammdf.egg-info\dependency_links.txt
      writing entry points to src\asammdf.egg-info\entry_points.txt
      writing requirements to src\asammdf.egg-info\requires.txt
      writing top-level names to src\asammdf.egg-info\top_level.txt
      reading manifest file 'src\asammdf.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'src\asammdf.egg-info\SOURCES.txt'
      copying src\asammdf\blocks\cutils.c -> build\lib.win-amd64-cpython-312\asammdf\blocks
      copying src\asammdf\gui\ui\attachment.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\bar.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\batch_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\bus_database_manager.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_bar_display_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_group_info_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_info_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\channel_stats.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\database_item.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\define_channel_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\define_conversion_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\error_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\fft_window.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\file_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\functions_manager.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\gps.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\gps_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\main_window.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\multi_search_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\numeric_offline.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\range_editor_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\range_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\resource.qrc -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\search_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\signal_scale.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\simple_search_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\tabular.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\tabular_filter.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\vrtt_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\vtt_widget.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      copying src\asammdf\gui\ui\windows_selection_dialog.ui -> build\lib.win-amd64-cpython-312\asammdf\gui\ui
      running build_ext
      building 'asammdf.blocks.cutils' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\src
      creating build\temp.win-amd64-cpython-312\Release\src\asammdf
      creating build\temp.win-amd64-cpython-312\Release\src\asammdf\blocks
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Temp\pip-build-env-afgz6qj8\overlay\Lib\site-packages\numpy\core\include -IC:\Users\user\AppData\Local\Programs\Python\Python312\include -IC:\Users\user\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcsrc/asammdf/blocks/cutils.c /Fobuild\temp.win-amd64-cpython-312\Release\src/asammdf/blocks/cutils.obj -std=c99
      cl : Befehlszeile warning D9002 : Unbekannte Option "-std=c99" wird ignoriert.
      cutils.c
      C:\Users\user\AppData\Local\Programs\Python\Python312\include\pyconfig.h(59): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "io.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for asammdf
  Building wheel for lz4 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lz4 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\lz4
      copying lz4\version.py -> build\lib.win-amd64-cpython-312\lz4
      copying lz4\__init__.py -> build\lib.win-amd64-cpython-312\lz4
      creating build\lib.win-amd64-cpython-312\lz4\block
      copying lz4\block\__init__.py -> build\lib.win-amd64-cpython-312\lz4\block
      creating build\lib.win-amd64-cpython-312\lz4\frame
      copying lz4\frame\__init__.py -> build\lib.win-amd64-cpython-312\lz4\frame
      running build_ext
      building 'lz4._version' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\lz4
      creating build\temp.win-amd64-cpython-312\Release\lz4libs
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ilz4libs -IC:\Users\user\AppData\Local\Programs\Python\Python312\include -IC:\Users\user\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tclz4/_version.c /Fobuild\temp.win-amd64-cpython-312\Release\lz4/_version.obj /Ot /Wall /wd4711 /wd4820
      _version.c
      C:\Users\user\AppData\Local\Programs\Python\Python312\include\pyconfig.h(59): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "io.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lz4
Failed to build asammdf lz4
ERROR: Could not build wheels for asammdf, lz4, which is required to install pyproject.toml-based projects

**Comment by danielhrisca** [comment]
use 64 bit python

**Comment by pepo83** [comment]
I am using 64bit Python.

**Comment by danielhrisca** [comment]
https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory

**Comment by pepo83** [comment]
This reply solved my issue:

> It can be solved by adding include dirs and library dirs as follow:
> 
> ```set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt;E:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared```
> 
> ```
> set LIB=E:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\onecore\x64;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib\amd64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64
> ```
> 
> and if then you are now getting a problem: link error can run with rc.exe; you also need copy rc.exe and rc.dll (x64) to the dir which is the same with the running link.exe

I had to copy the rc.exe/dll also.
