### ISSUE TITLE
In MDF files samples and timestamps length mismatch

### ISSUE THREAD

**Issue by AkbarAlam** [danielhrisca/asammdf#96]
I am using this tool for analyzing MDF files, I am getting this error 

asammdf.utils.MdfException: <SIGNAL_NAME> samples and timestamps length mismatch (58 vs 67)

I have used ETAS tools to check the signal but there it seemed everything is fine, what is going wrong here?

**Comment by danielhrisca** [comment]
Hello Akbar,

can you give some information about your setup: asammdf version, Python version?

**Comment by AkbarAlam** [comment]
I am using python version :  3.6.5
and asammdf version : 3.5.0

**Comment by AkbarAlam** [comment]
I have updated to the latest version. same problem

**Comment by AkbarAlam** [comment]
this is the Log I am geeting 
```
SIGNAL_NAME_ERROR samples and timestamps length mismatch (54 vs 63)
NoneType: None

MDF ============================================================================
name: .FILENAME.mf4
version: 4.10
memory: full
read fragment size: 0
write fragment size: 8388608

GROUP ==========================================================================
sorted: True
data location: 2
data block type: 0
param: 0
data size: []
data block size: []
data block addr: []
data block: { ..INFO ..}



record_size: {0: 14}
dependencies [None, None, None, None, None, None, None, None, None, None, None, None]
parets: {0: ('time', 0), 4: ('SINGNAL_1', 4), 5: ('SINGNAL_2', 2), 10: ('SINGNAL_3', 0), 3: ('SINGNAL_4', 7), 2: ('SINGNAL_5', 12), 9: ('SINGNAL_6', 9), 6: ('SINGNAL_7', 2), 7: ('SINGNAL_7', 1), 1: ('SINGNAL_8', 0)}
dtypes: [('time', '<u8'), ('SINGNAL_9', 'u1'), ('SINGNAL_10', 'u1'), ('SINGNAL_11', 'u1'), ('SINGNAL_12', 'u1'), ('invalidation_bytes', 'u1', (0,))]


CHANNEL GROUP ==================================================================
{'id': b'##CG', 'reserved0': 0, 'block_len': 104, 'links_nr': 6, 'next_cg_addr': 0, 'first_ch_addr': 1259552, 'acq_name_addr': 1263680, 'acq_source_addr': 6616, 'first_sample_reduction_addr': 0, 'comment_addr': 1263712, 'record_id': 0, 'cycles_nr': 54, 'flags': 0, 'path_separator': 0, 'reserved1': 0, 'samples_byte_nr': 14, 'invalidation_bytes_nr': 0}

CHANNEL ========================================================================
<Channel (name: SINGNAL_NAME_ERROR, unit: -, comment: , address: 0x133d20,
    conversion: <ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: {}, address: 0x1e2888, fields: {'id': b'##CC', 'reserved0': 0, 'block_len': 96, 'links_nr': 4, 'name_addr': 0, 'unit_addr': 0, 'comment_addr': 0, 'inv_conv_addr': 0, 'conversion_type': 1, 'precision': 0, 'flags': 0, 'ref_param_nr': 0, 'val_param_nr': 2, 'min_phy_value': 0.0, 'max_phy_value': 0.0, 'b': 0.0, 'a': 1.0})>,
    source: None,
    fields: {'id': b'##CN', 'reserved0': 0, 'block_len': 160, 'links_nr': 8, 'next_ch_addr': 1260992, 'component_addr': 0, 'name_addr': 1262024, 'source_addr': 0, 'conversion_addr': 1262080, 'data_block_addr': 0, 'unit_addr': 1262176, 'comment_addr': 0, 'channel_type': 0, 'sync_type': 0, 'data_type': 1, 'bit_offset': 6, 'byte_offset': 12, 'bit_count': 3, 'flags': 0, 'pos_invalidation_bit': 0, 'precision': 0, 'reserved1': 0, 'attachment_nr': 0, 'min_raw_value': 0.0, 'max_raw_value': 0.0, 'lower_limit': 0.0, 'upper_limit': 0.0, 'lower_ext_limit': 0.0, 'upper_ext_limit': 0.0})>

CHANNEL ARRAY ==================================================================
None

MASTER CACHE ===================================================================
[((0, 0), 2252), ((1, 0), 81), ((2, 0), 11273), ((3, 0), 11425), ((4, 0), 804), ((5, 0), 457), ((6, 0), 79), ((7, 0), 11420), ((8, 0), 125), ((9, 0), 79), ((10, 0), 80), ((11, 0), 79), ((12, 0), 1238), ((13, 0), 112), ((14, 0), 0), ((15, 0), 11330), ((16, 0), 63)]
```

**Comment by danielhrisca** [comment]
Hello Akbar, 

there is some conflicting information after you have done the name scrambling.

You can use the _scramble_ method of the _MDF_ class and post the debug information again. 

### **Make sure to run the _scramble_ method on a copy of the original measurement !!!**

```python

from asammdf import MDF

measurement = 'copy of original.mf4'
MDF.scramble(measurement)

mdf = MDF(measurement)
# this should trigger your error again
mdf.convert('4.11')
```

**Comment by AkbarAlam** [comment]
Thanks for the heads up

here is the log again 


```
RGYTNYTKLNLMHURBJFRJTTWDH samples and timestamps length mismatch (58 vs 67)
NoneType: None
MDF ============================================================================
name: ./Data_folder/newData/rcsd_noempty-relative_2018-10-01T09-26-40.mf4
version: 4.10
memory: full
read fragment size: 0
write fragment size: 8388608

GROUP ==========================================================================
sorted: False
data location: 2
data block type: 0
param: 0
data size: []
data block size: []
data block addr: []
data block: {'id': b'##DT', 'reserved0': 0, 'block_len': 836, 'links_nr': 0, 'data': b'\xc8\xa2y\x18\xebqY\x15M$\x92\x00\x00\x00\xa0\x8b\x9b\x8f\xebqY\x15I$\x92\x00\x00\x00\x18\xe2\xd7\x06\xecqY\x15I$\x92\x00\x00\x00\xd0\\(~\xecqY\x15I$\x92\x00\x00\x00(HT\xf5\xecqY\x15I$\x91\x00\x00\x008n\x8dl\xedqY\x15I$\x91\x00\x00\x00\x00\x0b\xca\xe3\xedqY\x15I$Q\x00\x00\x00\xe0%\x1b[\xeeqY\x15I$Q\x00\x00\x00pxW\xd2\xeeqY\x15I$Q\x00\x00\x00\x90\xb9\x92I\xefqY\x15I$Q\x00\x00\x00P\x99\xcb\xc0\xefqY\x15I$Q\x00\x00\x00\xf0x\xf77\xf0qY\x15I$Q\x00\x00\x00\xd8o2\xaf\xf0qY\x15I$Q\x00\x00\x00 Qn&\xf1qY\x15I$Q\x00\x00\x00(\r\xab\x9d\xf1qY\x15I$Q\x00\x00\x00\x00Z\xe6\x14\xf2qY\x15I$Q\x00\x00\x00H\xac$\x8c\xf2qY\x15I$Q\x00\x00\x00(K`\x03\xf3qY\x15I$Q\x00\x00\x00p+\xb1z\xf3qY\x15I$Q\x00\x00\x00p\x19\xd8\xf1\xf3qY\x15I$Q\x00\x00\x00X\x1c\x11i\xf4qY\x15I$Q\x00\x00\x00\x90\xb8Q\xe0\xf4qY\x15I$Q\x00\x00\x000\xc7\x8aW\xf5qY\x15I$Q\x00\x00\x00\x98\x02\xc5\xce\xf5qY\x15I$Q\x00\x00\x00x\x95\x02F\xf6qY\x15I$Q\x00\x00\x00\xd8\x0cO\xbd\xf6qY\x15I$Q\x00\x00\x00h\xe8\x894\xf7qY\x15I$Q\x00\x00\x00h5\xb6\xab\xf7qY\x15I$Q\x00\x00\x00\xd8\xc2\xf0"\xf8qY\x15I$Q\x00\x00\x00h\x92-\x9a\xf8qY\x15I$Q\x00\x00\x00\x88tc\x11\xf9qY\x15I$Q\x00\x00\x00\xd8\x18\xa2\x88\xf9qY\x15I$Q\x00\x00\x00 }\xdd\xff\xf9qY\x15I$Q\x00\x00\x00\x80\xdd\x18w\xfaqY\x15I$Q\x00\x00\x00\xe8\x89U\xee\xfaqY\x15I$Q\x00\x00\x00\xa0\x11\x8fe\xfbqY\x15I$Q\x00\x00\x00X\xf8\xcd\xdc\xfbqY\x15I$Q\x00\x00\x00\x181\rT\xfcqY\x15I$Q\x00\x00\x00X\xe4B\xcb\xfcqY\x15I$Q\x00\x00\x00h\xfe}B\xfdqY\x15I$Q\x00\x00\x00\x90\x97\xb8\xb9\xfdqY\x15I$Q\x00\x00\x00\xa0\xb1\xf30\xfeqY\x15I$Q\x00\x00\x00\xc8\xe4>\xa8\xfeqY\x15I$Q\x00\x00\x00\xd8K\xa6\x96\xffqY\x15I$Q\x00\x00\x00(#c\xfc\x00rY\x15I$Q\x00\x00\x00h\xee\x94s\x01rY\x15I$Q\x00\x00\x00\x00"\xcf\xea\x01rY\x15I$Q\x00\x00\x008S\x0cb\x02rY\x15I$Q\x00\x00\x008S\x0cb\x02rY\x15I$Q\x00\x00\x00(%F\xd9\x02rY\x15I$Q\x00\x00\x00X\x93\x80P\x03rY\x15I$Q\x00\x00\x00\x00e\xbc\xc7\x03rY\x15I$Q\x00\x00\x00\xb0\x17\xf6>\x04rY\x15I$Q\x00\x00\x00\x90\x9e5\xb6\x04rY\x15I$Q\x00\x00\x00h\xf1o-\x05rY\x15I$Q\x00\x00\x00 y\xa9\xa4\x05rY\x15I$Q\x00\x00\x00\xd8}\xe3\x1b\x06rY\x15I$Q\x00\x00\x00hM \x93\x06rY\x15I$Q\x00\x00\x00'}
record_size: {10: 16, 33: 13, 9: 14, 50: 13, 53: 13, 41: 13, 17: 13, 46: 13, 24: 13, 36: 13, 43: 10, 32: 13, 40: 13, 23: 16, 39: 13, 7: 13, 25: 13, 35: 13, 20: 11, 31: 11, 1: 64, 13: 14, 4: 13, 14: 11, 16: 13, 28: 13, 48: 13, 6: 9, 47: 13, 26: 13, 5: 12, 42: 11, 2: 11, 8: 15, 30: 13, 49: 13, 12: 11, 15: 11, 11: 16, 18: 15, 45: 11, 44: 13, 34: 13, 29: 13, 38: 13, 22: 14, 37: 10, 21: 11, 51: 13, 3: 10, 27: 13, 52: 11, 19: 10}
dependencies [None, None, None, None, None, None, None, None, None, None, None, None]
parets: {0: ('ZENU', 0), 8: ('NBKWEONJWSQWBUUKWMGQYTIDI', 4), 10: ('NBKWEONJWSQWBUUKWMGQYTIDI', 2), 9: ('SVIWBBLKVUXEURUTHSIFKCXAN', 0), 6: ('PYAFUUUTUQWROUINQAIMXZXMIJ', 7), 4: ('PYAFUUUTUQWROUINQAIMXZXMIJ', 12), 7: ('PYAFUUUTUQWROUINQAIMXZXMIJ', 9), 11: ('MIGTDPMJTTIYFETOWDDUCIIOZATULCN', 2), 3: ('MIGTDPMJTTIYFETOWDDUCIIOZATULCN', 1), 2: ('MIGTDPMJTTIYFETOWDDUCIIOZATULCN', 0)}
dtypes: [('ZENU', '<u8'), ('NBKWEONJWSQWBUUKWMGQYTIDI', 'u1'), ('SVIWBBLKVUXEURUTHSIFKCXAN', 'u1'), ('PYAFUUUTUQWROUINQAIMXZXMIJ', 'u1'), ('MIGTDPMJTTIYFETOWDDUCIIOZATULCN', 'u1'), ('invalidation_bytes', 'u1', (0,))]

CHANNEL GROUP ==================================================================
{'id': b'##CG', 'reserved0': 0, 'block_len': 104, 'links_nr': 6, 'next_cg_addr': 544, 'first_ch_addr': 70224, 'acq_name_addr': 74352, 'acq_source_addr': 7032, 'first_sample_reduction_addr': 0, 'comment_addr': 74384, 'record_id': 1, 'cycles_nr': 58, 'flags': 0, 'path_separator': 0, 'reserved1': 0, 'samples_byte_nr': 14, 'invalidation_bytes_nr': 0}

CHANNEL ========================================================================
<Channel (name: RGYTNYTKLNLMHURBJFRJTTWDH, unit: YAG, comment: , address: 0x112f0,
    conversion: <ChannelConversion (name: , unit: , comment: , formula: , referenced blocks: {}, address: 0x12130, fields: {'id': b'##CC', 'reserved0': 0, 'block_len': 96, 'links_nr': 4, 'name_addr': 0, 'unit_addr': 0, 'comment_addr': 0, 'inv_conv_addr': 0, 'conversion_type': 1, 'precision': 0, 'flags': 0, 'ref_param_nr': 0, 'val_param_nr': 2, 'min_phy_value': 0.0, 'max_phy_value': 0.0, 'b': 0.7, 'a': 0.1})>,
    source: None,
    fields: {'id': b'##CN', 'reserved0': 0, 'block_len': 160, 'links_nr': 8, 'next_ch_addr': 70544, 'component_addr': 0, 'name_addr': 73976, 'source_addr': 0, 'conversion_addr': 74032, 'data_block_addr': 0, 'unit_addr': 74128, 'comment_addr': 0, 'channel_type': 0, 'sync_type': 0, 'data_type': 1, 'bit_offset': 6, 'byte_offset': 9, 'bit_count': 6, 'flags': 0, 'pos_invalidation_bit': 0, 'precision': 0, 'reserved1': 0, 'attachment_nr': 0, 'min_raw_value': 0.0, 'max_raw_value': 0.0, 'lower_limit': 0.0, 'upper_limit': 0.0, 'lower_ext_limit': 0.0, 'upper_ext_limit': 0.0})>

CHANNEL ARRAY ==================================================================
None

MASTER CACHE ===================================================================
[((0, 0), 1128), ((1, 0), 7970), ((2, 0), 67)]
---------------------------------------------------------------------------
MdfException                              Traceback (most recent call last)
<ipython-input-45-7f390eccfa87> in <module>()
----> 1 mdf.convert('4.11')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py in convert(self, version, memory)
    581                             data=fragment,
    582                             raw=True,
--> 583                             ignore_invalidation_bits=True,
    584                         )
    585                         if version < '4.00' and sig.samples.dtype.kind == 'S':

~\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf_v4.py in get(self, name, group, index, raster, samples_only, data, raw, ignore_invalidation_bits, source)
   5309                     bit_count=bit_count,
   5310                     stream_sync=stream_sync,
-> 5311                     invalidation_bits=invalidation_bits,
   5312                 )
   5313             except:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\signal.py in __init__(self, samples, timestamps, unit, name, conversion, comment, raw, master_metadata, display_name, attachment, source, bit_count, stream_sync, invalidation_bits)
     95                 )
     96                 logger.exception(message)
---> 97                 raise MdfException(message)
     98             self.samples = samples
     99             self.timestamps = timestamps

MdfException: RGYTNYTKLNLMHURBJFRJTTWDH samples and timestamps length mismatch (58 vs 67)
```

**Comment by danielhrisca** [comment]
Is it possible to send the scrambled file?

**Comment by AkbarAlam** [comment]
you mean the MDF file ?

**Comment by danielhrisca** [comment]
Yes, it would make it easier to investigate.

**Comment by AkbarAlam** [comment]
It would be hard But I am trying,
Just for info I/we have tried with Matlab and we can read that signal as well :O

**Comment by danielhrisca** [comment]
Thank you Akbar. I am sure the file is ok since ETAS and MDFvalidator don't show any errors. There is a subtle bug in asammdf and I can't find it from your previous debug prints.

**Comment by AkbarAlam** [comment]
I have checked your mail and we are talking about it.

However I just received another MDF files, which worked. The change was, In one channel in previous MDF files the Difference between each time and signals were very small in nano seconds range, They changed/ removed that signal and now it works .... I am not sure yet if that is the problem

**Comment by danielhrisca** [comment]
I pretty confident that was not problem, but anyway the best would be to find the real problem and fix it. Thank you for your collaboration.

**Comment by danielhrisca** [comment]
Hello Akbar,

I found an error in the __prepare_record_ method (https://github.com/danielhrisca/asammdf/commit/34b639a224e8091beaa38f8d3fbd11b3c69c1c8f). 

Please check the development code; I was able to convert the scrambled file without errors.

**Comment by AkbarAlam** [comment]
I will check , will inform you today

**Comment by AkbarAlam** [comment]
Hi , I have installed the development version. Well I am still getting the error

**Comment by danielhrisca** [comment]
Are you sure? I don't have errors with the scrambled file that you have sent

**Comment by AkbarAlam** [comment]
So sorry, I imported the wrong version, yes it worked.

Well, I will check with some files and I will inform you tomorrow. Thank you so much for the support :)

**Comment by AkbarAlam** [comment]
small question, 
well if I want to  export all signals in one file then I can use the builtin method such as `mdf.export('csv','./data/data_all.csv',single_time_base=True)` right ? this one works, but if the value of the signal is empty at a certain time frame then the tool inserts  0 ? 

since I was earlier using 3.5.0 version , I have used pandas to take all signals in one file. Now If I use that methods I still get `ValueError: arrays must all be same length` , however my that method works with other files what I have tried

**Comment by danielhrisca** [comment]
_single_time_base_ will interpolate the signals: linear interpolation for float types and previous sample for the rest.

you should have a look at the _empty_channels_ argument (https://asammdf.readthedocs.io/en/master/api.html#asammdf.mdf.MDF.export) that by default will fill the empty channel with zeros.

**Comment by danielhrisca** [comment]
Regarding the pandas export error I've ran an export using the scrambled file and got no errors. Do you have problems with other files?

**Comment by eileenmandelbrot** [comment]
Hi Daniel, I have the exact same error with the current release. Is there a way to pip install the latest development version?
Thank you very much in advance!

**Comment by danielhrisca** [comment]
Hello Eileen,

to pip install a branch you can use this

```
pip install repo/archive/branchname.zip
```

In our casr

```
pip install https://github.com/danielhrisca/asammdf/archive/development.zip
```


In case you have the same problem please share the complete error traceback message

**Comment by eileenmandelbrot** [comment]
Basically the error always occurs in the get_group function in mdf.py:

Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/hdp/current/spark2-client/python/pyspark/worker.py", line 171, in main
    process()
  File "/usr/hdp/current/spark2-client/python/pyspark/worker.py", line 166, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/hdp/current/spark2-client/python/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "<ipython-input-14-42af507d6ec9>", line 1, in <lambda>
  **File "/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/asammdf/mdf.py", line 2788, in get_group
    return DataFrame.from_dict(pandas_dict)**
  File "/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py", line 985, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py", line 459, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py", line 7356, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py", line 7402, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length

**Comment by danielhrisca** [comment]
@eileenmandelbrot 
Can you checo the lengths of the arrays in the mdict? Are there any empty arrays?

**Comment by eileenmandelbrot** [comment]
Yes, there might be both empty arrays and occasionally None values in the arrays among the signals. 
Is this what causes the problem?

**Comment by eileenmandelbrot** [comment]
I try to use get_group() function with the new development version (asammdf==4.7.0.dev0), it gives me the same error, actually the error message is the same as reported in issue#97

**Comment by danielhrisca** [comment]
I will have a look tomorrow

**Comment by danielhrisca** [comment]
@eileenmandelbrot 

Please run your scripts again sugin the latest development commit (https://github.com/danielhrisca/asammdf/commit/5e4888892e241881f74754323f0c505c4c9821da) and share the printed output.

**Comment by eileenmandelbrot** [comment]
Hi Daniel, I run the code again, this time the error is "arrays must all be same length"

---------------------------------------------------------------------------------------------------
~/.local/lib/python3.6/site-packages/asammdf/mdf.py in iter_groups(self)
   2361 
   2362         for i, group in enumerate(self.groups):
-> 2363             yield self.get_group(i)
   2364 
   2365     def resample(self, raster, memory=None, version=None):

~/.local/lib/python3.6/site-packages/asammdf/mdf.py in get_group(self, index)
   2959 
   2960         try:
-> 2961             return DataFrame.from_dict(pandas_dict)
   2962         except:
   2963             debug_channel(self, group, None, None)

/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py in from_dict(cls, data, orient, dtype, columns)
    983             raise ValueError('only recognize index or columns for orient')
    984 
--> 985         return cls(data, index=index, columns=columns, dtype=dtype)
    986 
    987     def to_dict(self, orient='dict', into=dict):

/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    346                                  dtype=dtype, copy=copy)
    347         elif isinstance(data, dict):
--> 348             mgr = self._init_dict(data, index, columns, dtype=dtype)
    349         elif isinstance(data, ma.MaskedArray):
    350             import numpy.ma.mrecords as mrecords

/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py in _init_dict(self, data, index, columns, dtype)
    457             arrays = [data[k] for k in keys]
    458 
--> 459         return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    460 
    461     def _init_ndarray(self, values, index, columns, dtype=None, copy=False):

/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py in _arrays_to_mgr(arrays, arr_names, index, columns, dtype)
   7354     # figure out the index, if necessary
   7355     if index is None:
-> 7356         index = extract_index(arrays)
   7357 
   7358     # don't force copy because getting jammed in an ndarray anyway

/nfs/scratch/dst/apps/anaconda3/envs/pyHadoop/lib/python3.6/site-packages/pandas/core/frame.py in extract_index(data)
   7400             lengths = list(set(raw_lengths))
   7401             if len(lengths) > 1:
-> 7402                 raise ValueError('arrays must all be same length')
   7403 
   7404             if have_dicts:

ValueError: arrays must all be same length

**Comment by danielhrisca** [comment]
@eileenmandelbrot 
what is the mdf version of your file?
Can check again with the latest release 4.7.7 and with the code from the Py3 branch?
