### ISSUE TITLE
Record size larger than 32 MB leads to infinite loop

### ISSUE THREAD

**Issue by GBali89** [danielhrisca/asammdf#961]
# Python version
```
'python=3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'
'os=Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35'
'numpy=1.26.2'
ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.3.18'
```
# Code 

  ## MDF version
 `'version': '4.10'`

  ## Code snippet
 `MDF(file_path)`
Or open file from GUI
  
  ## Traceback
 No traceback
  
# Description

The effect is that both the GUI and the API keeps hanging and eating all the RAM when someone tries to open an MDF file that has this large record size.

Problem occurs here: https://github.com/danielhrisca/asammdf/blob/master/src/asammdf/blocks/mdf_v4.py#L1688
```python
  if record_size:
      _32_MB = 32 * 1024 * 1024 // record_size * record_size
  else:
      _32_MB = 32 * 1024 * 1024
```
If record size is larger than `32 * 1024 * 1024`, then `_32_MB` becomes `0`.
This leads to falling into an infinite loop later in the function, e.g.
```python
  while True:
      if size > _32_MB:
          total_size -= _32_MB
          size -= _32_MB
```
I don't know how common this is, this is the first time I'm handling mdf4 files, but the case should be handled either way.
I guess the most straightforward way would be to use 32MB chunks if this happens?

**Comment by danielhrisca** [comment]
I would like to see that measurement if you could share it via e-mail

**Comment by danielhrisca** [comment]
Please try the development branch code

**Comment by GBali89** [comment]
> I would like to see that measurement if you could share it via e-mail

I am sorry, but I can't do that, even with scrambling as I do not own the data.

**Comment by GBali89** [comment]
> Please try the development branch code

Works well, thank you!

**Comment by danielhrisca** [comment]
Is it some sort of video/image recoding?

**Comment by jcfuentes** [comment]
yes, it is a 4k video recording.

> Is it some sort of video/image recoding?

**Comment by GBali89** [comment]
> Is it some sort of video/image recoding?

Sorry for the late answer, it is camera and lidar data.

**Comment by jcfuentes** [comment]
Are you working for an OEM in Oberbayern? 😉

**Comment by GBali89** [comment]
No :)
