### ISSUE TITLE
Can we avoid to raise an error of to_dataframe of ''multiple occurrences"?

### ISSUE THREAD

**Issue by shangrilaer** [danielhrisca/asammdf#968]
As I've some mdf files with dump channels of same name , what I want is to just convert with these names with a counter added to its end but not raise a error and the file not converted.

**Comment by danielhrisca** [comment]
coniogure the object to not raise the error

```python
mdf = MDF(filename)
mdf.configure(raise_on_multiple_occurrences=False)
mdf.to_dataframe()
```
