### ISSUE TITLE
mdf.iter_groups() ignores raster

### ISSUE THREAD

**Issue by mw25** [danielhrisca/asammdf#970]
# Code 

https://github.com/danielhrisca/asammdf/blob/d06645eb6d782836750396c66e6263d26fc724a9/src/asammdf/mdf.py#L2910
  
# Description

It seems that iter_groups ignores the raster parameter.

**Comment by danielhrisca** [comment]
@mw25 please try the development branch

**Comment by mw25** [comment]
Thank you, it's working fine.
