### ISSUE TITLE
Attribute Error- 'MDF4' object has no attribute 'get_channel_data'

### ISSUE THREAD

**Issue by pooraniR** [danielhrisca/asammdf#974]

**Comment by danielhrisca** [comment]
this API function is not part of `asammdf`,  it is part of `mdfreader`

**Comment by pooraniR** [comment]
What do you mean by mdfreader? I see this API function defined on asammdf documentation- https://asammdf.readthedocs.io/en/2.1.0/mdf4.html
Please explain.

**Comment by danielhrisca** [comment]
2.1.0 was released 7 years ago https://pypi.org/project/asammdf/2.1.0/

You should update to the latest version

**Comment by pooraniR** [comment]
Okay, but is get_channel_data an attribute in the latest version? Can you point to the latest documentation as well?

**Comment by danielhrisca** [comment]
https://pypi.org/project/asammdf/

**Comment by caro-merz** [comment]
I am working with VLDS channels. Is there something like get_channel_data where I can get the data from SDBLOCKs of VLDS channels and their length?
