### ISSUE TITLE
Error code while reading mf4 file

### ISSUE THREAD

**Issue by raffsa** [danielhrisca/asammdf#98]
Hello,

I have a problem reading an MF4 file and I don't understand the reason for it:

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-76-1262cc149ca3> in <module>()
     13 
     14 
---> 15 mdf = MDF('/media/data2/jupyter_notebooks/sacherr/Files_test/213-2047_20170306205838_70A.mf4')

/usr/local/lib/python3.6/site-packages/asammdf/mdf.py in __init__(self, name, memory, version, callback)
     96                     self._mdf = MDF3(name, memory, callback=callback)
     97                 elif version in MDF4_VERSIONS:
---> 98                     self._mdf = MDF4(name, memory, callback=callback)
     99                 elif version in MDF2_VERSIONS:
    100                     self._mdf = MDF2(name, memory, callback=callback)

/usr/local/lib/python3.6/site-packages/asammdf/mdf_v4.py in __init__(self, name, memory, version, callback)
    340         if name:
    341             self._file = open(self.name, 'rb')
--> 342             self._read()
    343 
    344         else:

/usr/local/lib/python3.6/site-packages/asammdf/mdf_v4.py in _read(self)
    596                     size=size,
    597                 )
--> 598                 data = next(data)
    599 
    600                 if record_id_nr == 0:

StopIteration:

**Comment by raffsa** [comment]
mdf.info()

{'version': '4.00',
 'groups': 1,
 'group 0': {'cycles': 156,
  'channels count': 488,
  'channel 0': 'name="Time_abs" type=master',
  'channel 1': 'name="Time_rel" type=value',
  'channel 2': 'name="-_50701105" type=value',
  'channel 3': 'name="AG_49081941" type=value',
  'channel 4': 'name="AG_49081942" type=value',
  'channel 5': 'name="AG_49081943" type=value',
.......
.......

**Comment by danielhrisca** [comment]
please run this:

```python
import asammdf
print(asammdf.__version__)
```

**Comment by raffsa** [comment]
the asammdf version 3.5.0 is used

**Comment by danielhrisca** [comment]
In this case the first thing to try is to upgrade to 4.1.1

``pip install -I --no-deps asammdf`` ( or maybe ``pip3 install -I --no-deps asammdf``)

**Comment by raffsa** [comment]
i updated it to 4.1.1 but i still got the same error code

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-1-7a75fa4d35fb> in <module>()
     14 import asammdf
     15 print(asammdf.__version__)
---> 16 mdf = MDF('/media/data2/jupyter_notebooks/sacherr/Files_test/213-2047_20170412114053_70A.mf4')
     17 mdf.info()

/usr/local/lib/python3.6/site-packages/asammdf/mdf.py in __init__(self, name, memory, version, **kwargs)
    116                 self._mdf = MDF3(name, memory, **kwargs)
    117             elif version in MDF4_VERSIONS:
--> 118                 self._mdf = MDF4(name, memory, **kwargs)
    119             elif version in MDF2_VERSIONS:
    120                 self._mdf = MDF2(name, memory, **kwargs)

/usr/local/lib/python3.6/site-packages/asammdf/mdf_v4.py in __init__(self, name, memory, version, **kwargs)
    246                 self._file = open(self.name, 'rb')
    247                 self._from_filelike = False
--> 248             self._read()
    249 
    250         else:

/usr/local/lib/python3.6/site-packages/asammdf/mdf_v4.py in _read(self)
    519                     size=size,
    520                 )
--> 521                 data = next(data)
    522 
    523                 if record_id_nr == 0:

StopIteration:

**Comment by danielhrisca** [comment]
Please insert this

```python
                print(dat_addr, size)
```

here https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf_v4.py#L515

**Comment by danielhrisca** [comment]
@raffsa 
Please try the latest development code; I've fixed a bug that might be the root cause of your error

**Comment by danielhrisca** [comment]
@raffsa 
did you manage to try de latest released version? or the Py3 branch?

**Comment by danielhrisca** [comment]
@raffsa 

any updates?

**Comment by danielhrisca** [comment]
Please reopen if this is still relevant
