### ISSUE TITLE
Grid lines overlap plot lines

### ISSUE THREAD

**Issue by kapilvetriv** [danielhrisca/asammdf#983]
When we have lines plotted & enable the grid, the grid line is overlaid on the plot lines. 
it becomes difficult to see when the plot line is a constant value.

Can we overlay the plotlines upon the grid lines?

('python=3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19045-SP0'
'numpy=1.26.1'
'asammdf=7.3.15'

**Comment by danielhrisca** [comment]
@kapilvetriv please try the development branch code
