### ISSUE TITLE
data organizing on a mdf file 

### ISSUE THREAD

**Issue by barkanhvl** [danielhrisca/asammdf#995]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._
Hello. I'm gathering data from test vehicles on field but most of the data are useless for me. For ex: i have a 10 days data, but half of it is vehicle stationary position, just power on. But i need running data. So when i open all the file, i need to delete some regions. On attached file you can see a 11 days of data. But red circles are useless. So i need to select that regions and delete. As a result, a new filtered file should able to be created. 
![Screenshot 2024-03-15 130115](https://github.com/danielhrisca/asammdf/assets/123003168/519b9558-02c5-46c6-aea0-3d758cc0827d)

**Comment by danielhrisca** [comment]
I don't get what your problem is
